#!/bin/bash
#
# Install Script
#
#  1. Execute Database Create Scripts
#  2. Link php files into cgi-bin
#  3. Link include directory into cgi-bin
#
# TODO:Make Oracle Connection String a Parameter
#
. /etc/profile.local
. ${HOME}/.bash_profile
if [ $# -lt '4' ]
then
  echo "";
  echo "Usage   : install <oracle connection> <instance cgi-bin> <data tablespace> <index tablespace>";
  echo "";
  echo "Example : install user/password@DB /opt/iba/web/trn/cgi-bin PAS_DATA PAS_INDX";
  echo "";
  exit 0
fi
export ORACLE_CONNECT=$1
export CGIBIN=$2
export DATA=$3
export INDX=$4
sed s/TABLESPACE_DATA/$DATA/g calendar.sql | sed s/TABLESPACE_INDX/$INDX/g >calendar-tables.sql
sqlplus $ORACLE_CONNECT <<EOF
@calendar-tables
@calendar-data
@calendar-seq
EOF
#
# TODO:Make php/cgi-bin locations parameters
#
export BASEDIR=$(pwd)
echo $BASEDIR
ln -s $BASEDIR/EventListAJAX.php $CGIBIN
ln -s $BASEDIR/Events.php $CGIBIN
ln -s $BASEDIR/EventStatus.php $CGIBIN
ln -s $BASEDIR/EventTypes.php $CGIBIN
ln -s $BASEDIR/EventUpdate.php $CGIBIN
ln -s $BASEDIR/FutureEvents.php $CGIBIN
ln -s $BASEDIR/TheatreEventList.php $CGIBIN
ln -s $BASEDIR/TheatreEventView.php $CGIBIN
ln -s $BASEDIR/include $CGIBIN
echo "Complete";
