CREATE TABLE RESFLNAF
(
  REFLLTY VARCHAR(2)   DEFAULT ' ' NOT NULL,
  REFLLKY VARCHAR(10)  DEFAULT ' ' NOT NULL,
  REFLLAB VARCHAR(3)   DEFAULT ' ' NOT NULL,
  REFLUCS VARCHAR(12)  DEFAULT ' ' NOT NULL,
  REFLUSC VARCHAR(12)  DEFAULT ' ' NOT NULL,
  REFLVST VARCHAR(100) DEFAULT ' ' NOT NULL,
  REFLDSS VARCHAR(10)  DEFAULT ' ' NOT NULL,
  REFLCNT VARCHAR(10)  DEFAULT ' ' NOT NULL,
  REFLSPA VARCHAR(50)  DEFAULT ' ' NOT NULL,
  LF      CHAR(1)      DEFAULT ' ' NOT NULL
)

CREATE UNIQUE INDEX RESFLNA1 ON RESFLNAF
(
  REFLLTY,
  REFLLKY,
  REFLLAB,
  REFLUCS,
  REFLUSC,
  REFLVST,
  REFLDSS
)

CREATE UNIQUE INDEX RESFLNA2 ON RESFLNAF
(
  REFLLTY,
  REFLLKY,
  REFLCNT,
  REFLLAB,
  REFLUCS,
  REFLUSC,
  REFLVST,
  REFLDSS
)

CREATE UNIQUE INDEX RESFLNA3 ON RESFLNAF
(
  REFLLTY,
  REFLLKY,
  REFLLAB,
  REFLCNT,
  REFLUCS,
  REFLUSC,
  REFLVST,
  REFLDSS
)

