#!/bin/bash
#
# Upgrade Script
#
. /etc/profile.local
. ${HOME}/.bash_profile
if [ $# -lt '4' ]
then
  echo "";
  echo "Usage   : upgrade <oracle connection> <instance cgi-bin> <data tablespace> <index tablespace>";
  echo "";
  echo "Example : upgrade user/password@DB /opt/iba/web/trn/cgi-bin PAS_DATA PAS_INDX";
  echo "";
  exit 0
fi
#
# Run the SQL upgrade script
#
export ORACLE_CONNECT=$1
export CGIBIN=$2
export DATA=$3
export INDX=$4
sed s/TABLESPACE_DATA/$DATA/g calendar-upd.sql | sed s/TABLESPACE_INDX/$INDX/g >calendar-update.sql
sqlplus $ORACLE_CONNECT <<EOF
@calendar-update
EOF
#
# Link any new object to cgi-bin
#
export BASEDIR=$(pwd)
echo $BASEDIR
echo "Complete";
