create table allactaf
(
  alacdept    char(3) default ' ' not null,
  alacdoct    char(10) default ' ' not null,
  alaccodt    char(8) default ' ' not null,
  alaccotm    char(8) default ' ' not null,
  alacloca    char(3) default ' ' not null,
  alacserv    char(6) default ' ' not null,
  alacunit    decimal(6,0) default 0 not null,
  alacstat    char(1) default ' ' not null,
  alacudt1    char(8) default ' ' not null,
  alacutm1    char(8) default ' ' not null,
  alacudt2    char(8) default ' ' not null,
  alacutm2    char(8) default ' ' not null,
  alacudt3    char(8) default ' ' not null,
  alacutm3    char(8) default ' ' not null,
  alacudt4    char(8) default ' ' not null,
  alacutm4    char(8) default ' ' not null,
  alacuhc1    char(10) default ' ' not null,
  alacuhc2    char(10) default ' ' not null,
  alacuhc3    char(10) default ' ' not null,
  alacuhc4    char(10) default ' ' not null,
  alacudi1    char(9) default ' ' not null,
  alacudi2    char(9) default ' ' not null,
  alacudi3    char(9) default ' ' not null,
  alacudi4    char(60) default ' ' not null,
  alacudi5    char(60) default ' ' not null,
  alacudi6    char(60) default ' ' not null,
  alacuyn1    char(1) default ' ' not null,
  alacuyn2    char(1) default ' ' not null,
  alacuyn3    char(1) default ' ' not null,
  alacuyn4    char(1) default ' ' not null,
  alacuyn5    char(1) default ' ' not null,
  alacuyn6    char(1) default ' ' not null,
  alacuyn7    char(1) default ' ' not null,
  alacuyn8    char(1) default ' ' not null,
  alacuyn9    char(1) default ' ' not null,
  alacuff1    char(60) default ' ' not null,
  alacuff2    char(60) default ' ' not null,
  alacuff3    char(60) default ' ' not null,
  alacuc01    char(3) default ' ' not null,
  alacuc02    char(3) default ' ' not null,
  alacuc03    char(3) default ' ' not null,
  alacuc04    char(3) default ' ' not null,
  alacuc05    char(3) default ' ' not null,
  alacuc06    char(3) default ' ' not null,
  alacuc07    char(3) default ' ' not null,
  alacuc08    char(3) default ' ' not null,
  alacuc09    char(3) default ' ' not null,
  alacuc10    char(3) default ' ' not null,
  alacuc11    char(3) default ' ' not null,
  alacuc12    char(3) default ' ' not null,
  alacuf01    decimal(14,2) default 0 not null,
  alacuf02    decimal(14,2) default 0 not null,
  alacuf03    decimal(14,2) default 0 not null,
  alacuf04    decimal(14,2) default 0 not null,
  alacuf05    decimal(14,2) default 0 not null,
  alacuf06    decimal(14,2) default 0 not null,
  alacuf07    decimal(8,0) default 0 not null,
  alacuf08    decimal(8,0) default 0 not null,
  alacuf09    decimal(8,0) default 0 not null,
  alacuf10    decimal(8,0) default 0 not null,
  alacuf11    decimal(8,0) default 0 not null,
  alacuf12    decimal(8,0) default 0 not null,
  alaccomm    char(60) default ' ' not null,
  alaccdat    char(8) default ' ' not null,
  alacctim    char(8) default ' ' not null,
  alaccuid    char(10) default ' ' not null,
  alacudat    char(8) default ' ' not null,
  alacutim    char(8) default ' ' not null,
  alacuuid    char(10) default ' ' not null,
  alacspar    char(40) default ' ' not null,
  lf          char(1)
);
create unique index allacta1 on allactaf
(
alacdept,
alaccodt,
alaccotm,
alacdoct
);
create unique index allacta2 on allactaf
(
alacdoct,
alaccodt,
alaccotm,
alacdept
);
revoke all on allactaf from public ; 
grant select on allactaf to public ; 
