create table allbiaaf
(
  albavisn    char(8) default ' ' not null,
  albadate    char(8) default ' ' not null,
  albatime    char(8) default ' ' not null,
  albadrk1    decimal(4,0) default 0 not null,
  albadrk2    decimal(4,0) default 0 not null,
  albadrk3    decimal(4,0) default 0 not null,
  albadrk4    decimal(4,0) default 0 not null,
  albaeat1    decimal(4,0) default 0 not null,
  albaeat2    decimal(4,0) default 0 not null,
  albaeat3    decimal(4,0) default 0 not null,
  albaeat4    decimal(4,0) default 0 not null,
  albaupp1    decimal(4,0) default 0 not null,
  albaupp2    decimal(4,0) default 0 not null,
  albaupp3    decimal(4,0) default 0 not null,
  albaupp4    decimal(4,0) default 0 not null,
  albalow1    decimal(4,0) default 0 not null,
  albalow2    decimal(4,0) default 0 not null,
  albalow3    decimal(4,0) default 0 not null,
  albalow4    decimal(4,0) default 0 not null,
  albabrc1    decimal(4,0) default 0 not null,
  albabrc2    decimal(4,0) default 0 not null,
  albabrc3    decimal(4,0) default 0 not null,
  albabrc4    decimal(4,0) default 0 not null,
  albagrm1    decimal(4,0) default 0 not null,
  albagrm2    decimal(4,0) default 0 not null,
  albagrm3    decimal(4,0) default 0 not null,
  albagrm4    decimal(4,0) default 0 not null,
  albawsh1    decimal(4,0) default 0 not null,
  albawsh2    decimal(4,0) default 0 not null,
  albawsh3    decimal(4,0) default 0 not null,
  albawsh4    decimal(4,0) default 0 not null,
  albaurn1    decimal(4,0) default 0 not null,
  albaurn2    decimal(4,0) default 0 not null,
  albaurn3    decimal(4,0) default 0 not null,
  albaurn4    decimal(4,0) default 0 not null,
  albabow1    decimal(4,0) default 0 not null,
  albabow2    decimal(4,0) default 0 not null,
  albabow3    decimal(4,0) default 0 not null,
  albabow4    decimal(4,0) default 0 not null,
  albacar1    decimal(4,0) default 0 not null,
  albacar2    decimal(4,0) default 0 not null,
  albacar3    decimal(4,0) default 0 not null,
  albacar4    decimal(4,0) default 0 not null,
  albachr1    decimal(4,0) default 0 not null,
  albachr2    decimal(4,0) default 0 not null,
  albachr3    decimal(4,0) default 0 not null,
  albachr4    decimal(4,0) default 0 not null,
  albatol1    decimal(4,0) default 0 not null,
  albatol2    decimal(4,0) default 0 not null,
  albatol3    decimal(4,0) default 0 not null,
  albatol4    decimal(4,0) default 0 not null,
  albashw1    decimal(4,0) default 0 not null,
  albashw2    decimal(4,0) default 0 not null,
  albashw3    decimal(4,0) default 0 not null,
  albashw4    decimal(4,0) default 0 not null,
  albalvl1    decimal(4,0) default 0 not null,
  albalvl2    decimal(4,0) default 0 not null,
  albalvl3    decimal(4,0) default 0 not null,
  albalvl4    decimal(4,0) default 0 not null,
  albaupd1    decimal(4,0) default 0 not null,
  albaupd2    decimal(4,0) default 0 not null,
  albaupd3    decimal(4,0) default 0 not null,
  albaupd4    decimal(4,0) default 0 not null,
  albapro1    decimal(4,0) default 0 not null,
  albapro2    decimal(4,0) default 0 not null,
  albapro3    decimal(4,0) default 0 not null,
  albapro4    decimal(4,0) default 0 not null,
  albadelf    char(1) default ' ' not null,
  albacuid    char(10) default ' ' not null,
  albacdat    char(8) default ' ' not null,
  albactim    char(8) default ' ' not null,
  albauuid    char(10) default ' ' not null,
  albaudat    char(8) default ' ' not null,
  albautim    char(8) default ' ' not null,
  albaduid    char(10) default ' ' not null,
  albaddat    char(8) default ' ' not null,
  albadtim    char(8) default ' ' not null,
  albatots    char(3) default ' ' not null,
  albaspar    char(17) default ' ' not null,
  lf          char(1)
);
create unique index allbiaa1 on allbiaaf
(
albavisn,
albadate,
albatime
);
revoke all on allbiaaf from public ; 
grant select on allbiaaf to public ; 
