create table allauden
(
  alenaudd    char(8) default ' ' not null,
  alenaudt    char(8) default ' ' not null,
  alenaudp    char(2) default ' ' not null,
  alenaudr    char(1) default ' ' not null,
  alenauds    decimal(1,0) default 0 not null,
  alenaudo    char(4) default ' ' not null,
  alenvisn    char(8) default ' ' not null,
  alenenct    char(8) default ' ' not null,
  alenclin    char(6) default ' ' not null,
  alenhcp     char(10) default ' ' not null,
  alensdat    char(8) default ' ' not null,
  alenstim    char(8) default ' ' not null,
  alenloca    char(3) default ' ' not null,
  alenlink    char(8) default ' ' not null,
  alentype    char(3) default ' ' not null,
  alenserv    char(6) default ' ' not null,
  alendiun    decimal(6,0) default 0 not null,
  alendbun    decimal(6,0) default 0 not null,
  aleninun    decimal(6,0) default 0 not null,
  alenibun    decimal(6,0) default 0 not null,
  alenbulk    char(3) default ' ' not null,
  alenrsta    char(1) default ' ' not null,
  alenudt1    char(8) default ' ' not null,
  alenutm1    char(8) default ' ' not null,
  alenudt2    char(8) default ' ' not null,
  alenutm2    char(8) default ' ' not null,
  alenudt3    char(8) default ' ' not null,
  alenutm3    char(8) default ' ' not null,
  alenudt4    char(8) default ' ' not null,
  alenutm4    char(8) default ' ' not null,
  alenuhc1    char(10) default ' ' not null,
  alenuhc2    char(10) default ' ' not null,
  alenuhc3    char(10) default ' ' not null,
  alenuhc4    char(10) default ' ' not null,
  alenudi1    char(9) default ' ' not null,
  alenudi2    char(9) default ' ' not null,
  alenudi3    char(9) default ' ' not null,
  alenudi4    char(60) default ' ' not null,
  alenudi5    char(60) default ' ' not null,
  alenudi6    char(60) default ' ' not null,
  alenuyn1    char(1) default ' ' not null,
  alenuyn2    char(1) default ' ' not null,
  alenuyn3    char(1) default ' ' not null,
  alenuyn4    char(1) default ' ' not null,
  alenuyn5    char(1) default ' ' not null,
  alenuyn6    char(1) default ' ' not null,
  alenuyn7    char(1) default ' ' not null,
  alenuyn8    char(1) default ' ' not null,
  alenuyn9    char(1) default ' ' not null,
  alenuff1    char(60) default ' ' not null,
  alenuff2    char(60) default ' ' not null,
  alenuff3    char(60) default ' ' not null,
  alenuc01    char(3) default ' ' not null,
  alenuc02    char(3) default ' ' not null,
  alenuc03    char(3) default ' ' not null,
  alenuc04    char(3) default ' ' not null,
  alenuc05    char(3) default ' ' not null,
  alenuc06    char(3) default ' ' not null,
  alenuc07    char(3) default ' ' not null,
  alenuc08    char(3) default ' ' not null,
  alenuc09    char(3) default ' ' not null,
  alenuc10    char(3) default ' ' not null,
  alenuc11    char(3) default ' ' not null,
  alenuc12    char(3) default ' ' not null,
  alenuc13    char(3) default ' ' not null,
  alenuc14    char(3) default ' ' not null,
  alenuc15    char(3) default ' ' not null,
  alenuc16    char(3) default ' ' not null,
  alenuc17    char(3) default ' ' not null,
  alenuc18    char(3) default ' ' not null,
  alenuc19    char(3) default ' ' not null,
  alenuc20    char(3) default ' ' not null,
  alenuc21    char(3) default ' ' not null,
  alenuc22    char(3) default ' ' not null,
  alenuc23    char(3) default ' ' not null,
  alenuc24    char(3) default ' ' not null,
  alenuc25    char(3) default ' ' not null,
  alenuc26    char(3) default ' ' not null,
  alenuc27    char(3) default ' ' not null,
  alenuc28    char(3) default ' ' not null,
  alenuc29    char(3) default ' ' not null,
  alenuc30    char(3) default ' ' not null,
  alenuc31    char(3) default ' ' not null,
  alenuc32    char(3) default ' ' not null,
  alenuc33    char(3) default ' ' not null,
  alenuc34    char(3) default ' ' not null,
  alenuc35    char(3) default ' ' not null,
  alenuc36    char(3) default ' ' not null,
  alenuc37    char(3) default ' ' not null,
  alenuc38    char(3) default ' ' not null,
  alenuc39    char(3) default ' ' not null,
  alenuc40    char(3) default ' ' not null,
  alenuf01    decimal(14,2) default 0 not null,
  alenuf02    decimal(14,2) default 0 not null,
  alenuf03    decimal(14,2) default 0 not null,
  alenuf04    decimal(14,2) default 0 not null,
  alenuf05    decimal(14,2) default 0 not null,
  alenuf06    decimal(14,2) default 0 not null,
  alenuf07    decimal(14,2) default 0 not null,
  alenuf08    decimal(14,2) default 0 not null,
  alenuf09    decimal(14,2) default 0 not null,
  alenuf10    decimal(14,2) default 0 not null,
  alenuf11    decimal(8,0) default 0 not null,
  alenuf12    decimal(8,0) default 0 not null,
  alenuf13    decimal(8,0) default 0 not null,
  alenuf14    decimal(8,0) default 0 not null,
  alenuf15    decimal(8,0) default 0 not null,
  alenuf16    decimal(8,0) default 0 not null,
  alenuf17    decimal(8,0) default 0 not null,
  alenuf18    decimal(8,0) default 0 not null,
  alenuf19    decimal(8,0) default 0 not null,
  alenuf20    decimal(8,0) default 0 not null,
  alencmt1    char(80) default ' ' not null,
  alencmt2    char(80) default ' ' not null,
  alencdat    char(8) default ' ' not null,
  alenctim    char(8) default ' ' not null,
  alencuid    char(10) default ' ' not null,
  alenudat    char(8) default ' ' not null,
  alenutim    char(8) default ' ' not null,
  alenuuid    char(10) default ' ' not null,
  alencomp    char(3) default ' ' not null,
  alenuniq    char(8) default ' ' not null,
  alenssac    char(1) default ' ' not null,
  alenrevd    char(8) default ' ' not null,
  alencref    char(20) default ' ' not null,
  alenpurc    char(3) default ' ' not null,
  alencont    char(3) default ' ' not null,
  alenmohr    char(1) default ' ' not null,
  alenrhos    char(5) default ' ' not null,
  alencart    char(3) default ' ' not null,
  alenstra    char(3) default ' ' not null,
  alenoutc    char(3) default ' ' not null,
  alensrvd    char(3) default ' ' not null,
  alensdep    char(3) default ' ' not null,
  alenaccn    char(20) default ' ' not null,
  alenspar    char(24) default ' ' not null,
  lf          char(1)
);
create index allauden on allauden
(
alenaudd,
alenaudt,
alenaudp,
alenaudr
);
create index allaudea on allauden
(
alenvisn,
alenenct,
alenaudd,
alenaudt
);
revoke all on allauden from public ; 
grant select on allauden to public ; 
create table allencaf
(
  alenvisn    char(8) default ' ' not null,
  alenenct    char(8) default ' ' not null,
  alenclin    char(6) default ' ' not null,
  alenhcp     char(10) default ' ' not null,
  alensdat    char(8) default ' ' not null,
  alenstim    char(8) default ' ' not null,
  alenloca    char(3) default ' ' not null,
  alenlink    char(8) default ' ' not null,
  alentype    char(3) default ' ' not null,
  alenserv    char(6) default ' ' not null,
  alendiun    decimal(6,0) default 0 not null,
  alendbun    decimal(6,0) default 0 not null,
  aleninun    decimal(6,0) default 0 not null,
  alenibun    decimal(6,0) default 0 not null,
  alenbulk    char(3) default ' ' not null,
  alenrsta    char(1) default ' ' not null,
  alenudt1    char(8) default ' ' not null,
  alenutm1    char(8) default ' ' not null,
  alenudt2    char(8) default ' ' not null,
  alenutm2    char(8) default ' ' not null,
  alenudt3    char(8) default ' ' not null,
  alenutm3    char(8) default ' ' not null,
  alenudt4    char(8) default ' ' not null,
  alenutm4    char(8) default ' ' not null,
  alenuhc1    char(10) default ' ' not null,
  alenuhc2    char(10) default ' ' not null,
  alenuhc3    char(10) default ' ' not null,
  alenuhc4    char(10) default ' ' not null,
  alenudi1    char(9) default ' ' not null,
  alenudi2    char(9) default ' ' not null,
  alenudi3    char(9) default ' ' not null,
  alenudi4    char(60) default ' ' not null,
  alenudi5    char(60) default ' ' not null,
  alenudi6    char(60) default ' ' not null,
  alenuyn1    char(1) default ' ' not null,
  alenuyn2    char(1) default ' ' not null,
  alenuyn3    char(1) default ' ' not null,
  alenuyn4    char(1) default ' ' not null,
  alenuyn5    char(1) default ' ' not null,
  alenuyn6    char(1) default ' ' not null,
  alenuyn7    char(1) default ' ' not null,
  alenuyn8    char(1) default ' ' not null,
  alenuyn9    char(1) default ' ' not null,
  alenuff1    char(60) default ' ' not null,
  alenuff2    char(60) default ' ' not null,
  alenuff3    char(60) default ' ' not null,
  alenuc01    char(3) default ' ' not null,
  alenuc02    char(3) default ' ' not null,
  alenuc03    char(3) default ' ' not null,
  alenuc04    char(3) default ' ' not null,
  alenuc05    char(3) default ' ' not null,
  alenuc06    char(3) default ' ' not null,
  alenuc07    char(3) default ' ' not null,
  alenuc08    char(3) default ' ' not null,
  alenuc09    char(3) default ' ' not null,
  alenuc10    char(3) default ' ' not null,
  alenuc11    char(3) default ' ' not null,
  alenuc12    char(3) default ' ' not null,
  alenuc13    char(3) default ' ' not null,
  alenuc14    char(3) default ' ' not null,
  alenuc15    char(3) default ' ' not null,
  alenuc16    char(3) default ' ' not null,
  alenuc17    char(3) default ' ' not null,
  alenuc18    char(3) default ' ' not null,
  alenuc19    char(3) default ' ' not null,
  alenuc20    char(3) default ' ' not null,
  alenuc21    char(3) default ' ' not null,
  alenuc22    char(3) default ' ' not null,
  alenuc23    char(3) default ' ' not null,
  alenuc24    char(3) default ' ' not null,
  alenuc25    char(3) default ' ' not null,
  alenuc26    char(3) default ' ' not null,
  alenuc27    char(3) default ' ' not null,
  alenuc28    char(3) default ' ' not null,
  alenuc29    char(3) default ' ' not null,
  alenuc30    char(3) default ' ' not null,
  alenuc31    char(3) default ' ' not null,
  alenuc32    char(3) default ' ' not null,
  alenuc33    char(3) default ' ' not null,
  alenuc34    char(3) default ' ' not null,
  alenuc35    char(3) default ' ' not null,
  alenuc36    char(3) default ' ' not null,
  alenuc37    char(3) default ' ' not null,
  alenuc38    char(3) default ' ' not null,
  alenuc39    char(3) default ' ' not null,
  alenuc40    char(3) default ' ' not null,
  alenuf01    decimal(14,2) default 0 not null,
  alenuf02    decimal(14,2) default 0 not null,
  alenuf03    decimal(14,2) default 0 not null,
  alenuf04    decimal(14,2) default 0 not null,
  alenuf05    decimal(14,2) default 0 not null,
  alenuf06    decimal(14,2) default 0 not null,
  alenuf07    decimal(14,2) default 0 not null,
  alenuf08    decimal(14,2) default 0 not null,
  alenuf09    decimal(14,2) default 0 not null,
  alenuf10    decimal(14,2) default 0 not null,
  alenuf11    decimal(8,0) default 0 not null,
  alenuf12    decimal(8,0) default 0 not null,
  alenuf13    decimal(8,0) default 0 not null,
  alenuf14    decimal(8,0) default 0 not null,
  alenuf15    decimal(8,0) default 0 not null,
  alenuf16    decimal(8,0) default 0 not null,
  alenuf17    decimal(8,0) default 0 not null,
  alenuf18    decimal(8,0) default 0 not null,
  alenuf19    decimal(8,0) default 0 not null,
  alenuf20    decimal(8,0) default 0 not null,
  alencmt1    char(80) default ' ' not null,
  alencmt2    char(80) default ' ' not null,
  alencdat    char(8) default ' ' not null,
  alenctim    char(8) default ' ' not null,
  alencuid    char(10) default ' ' not null,
  alenudat    char(8) default ' ' not null,
  alenutim    char(8) default ' ' not null,
  alenuuid    char(10) default ' ' not null,
  alencomp    char(3) default ' ' not null,
  alenuniq    char(8) default ' ' not null,
  alenssac    char(1) default ' ' not null,
  alenrevd    char(8) default ' ' not null,
  alencref    char(20) default ' ' not null,
  alenpurc    char(3) default ' ' not null,
  alencont    char(3) default ' ' not null,
  alenmohr    char(1) default ' ' not null,
  alenrhos    char(5) default ' ' not null,
  alencart    char(3) default ' ' not null,
  alenstra    char(3) default ' ' not null,
  alenoutc    char(3) default ' ' not null,
  alensrvd    char(3) default ' ' not null,
  alensdep    char(3) default ' ' not null,
  alenaccn    char(20) default ' ' not null,
  alenspar    char(24) default ' ' not null,
  lf          char(1)
);
create unique index allenca1 on allencaf
(
alenvisn,
alenenct
);
create unique index allenca2 on allencaf
(
alenhcp,
alensdat,
alenstim,
alenvisn,
alenenct
);
create unique index allenca3 on allencaf
(
alenuniq,
alenvisn,
alenenct
);
create unique index allenca4 on allencaf
(
alensdat,
alenvisn,
alenenct
);
create unique index allenca5 on allencaf
(
alencuid,
alensdat,
alenstim,
alenvisn,
alenenct
);
create unique index allenca6 on allencaf
(
alenvisn,
alensdat,
alenstim,
alenenct
);
create unique index allenca7 on allencaf
(
alenlink,
alenvisn,
alenenct
);
revoke all on allencaf from public ; 
grant select on allencaf to public ; 
