create table allqueaf
(
  dalqumes    char(20) default ' ' not null,
  alrevisn    char(8) default ' ' not null,
  alenenct    char(8) default ' ' not null,
  alenclin    char(6) default ' ' not null,
  alenhcp     char(10) default ' ' not null,
  alensdat    char(8) default ' ' not null,
  alenstim    char(8) default ' ' not null,
  alenloca    char(3) default ' ' not null,
  alenlink    char(8) default ' ' not null,
  alentype    char(3) default ' ' not null,
  alenserv    char(6) default ' ' not null,
  alendiun    decimal(6,0) default 0 not null,
  alendbun    decimal(6,0) default 0 not null,
  aleninun    decimal(6,0) default 0 not null,
  alenibun    decimal(6,0) default 0 not null,
  alenbulk    char(3) default ' ' not null,
  alenrsta    char(1) default ' ' not null,
  alenudt1    char(8) default ' ' not null,
  alenutm1    char(8) default ' ' not null,
  alenudt2    char(8) default ' ' not null,
  alenutm2    char(8) default ' ' not null,
  alenudt3    char(8) default ' ' not null,
  alenutm3    char(8) default ' ' not null,
  alenudt4    char(8) default ' ' not null,
  alenutm4    char(8) default ' ' not null,
  alenuhc1    char(10) default ' ' not null,
  alenuhc2    char(10) default ' ' not null,
  alenuhc3    char(10) default ' ' not null,
  alenuhc4    char(10) default ' ' not null,
  alenudi1    char(9) default ' ' not null,
  alenudi2    char(9) default ' ' not null,
  alenudi3    char(9) default ' ' not null,
  alenudi4    char(60) default ' ' not null,
  alenudi5    char(60) default ' ' not null,
  alenudi6    char(60) default ' ' not null,
  alenuyn1    char(1) default ' ' not null,
  alenuyn2    char(1) default ' ' not null,
  alenuyn3    char(1) default ' ' not null,
  alenuyn4    char(1) default ' ' not null,
  alenuyn5    char(1) default ' ' not null,
  alenuyn6    char(1) default ' ' not null,
  alenuyn7    char(1) default ' ' not null,
  alenuyn8    char(1) default ' ' not null,
  alenuyn9    char(1) default ' ' not null,
  alenuff1    char(60) default ' ' not null,
  alenuff2    char(60) default ' ' not null,
  alenuff3    char(60) default ' ' not null,
  alenuc01    char(3) default ' ' not null,
  alenuc02    char(3) default ' ' not null,
  alenuc03    char(3) default ' ' not null,
  alenuc04    char(3) default ' ' not null,
  alenuc05    char(3) default ' ' not null,
  alenuc06    char(3) default ' ' not null,
  alenuc07    char(3) default ' ' not null,
  alenuc08    char(3) default ' ' not null,
  alenuc09    char(3) default ' ' not null,
  alenuc10    char(3) default ' ' not null,
  alenuc11    char(3) default ' ' not null,
  alenuc12    char(3) default ' ' not null,
  alenuc13    char(3) default ' ' not null,
  alenuc14    char(3) default ' ' not null,
  alenuc15    char(3) default ' ' not null,
  alenuc16    char(3) default ' ' not null,
  alenuc17    char(3) default ' ' not null,
  alenuc18    char(3) default ' ' not null,
  alenuc19    char(3) default ' ' not null,
  alenuc20    char(3) default ' ' not null,
  alenuc21    char(3) default ' ' not null,
  alenuc22    char(3) default ' ' not null,
  alenuc23    char(3) default ' ' not null,
  alenuc24    char(3) default ' ' not null,
  alenuc25    char(3) default ' ' not null,
  alenuc26    char(3) default ' ' not null,
  alenuc27    char(3) default ' ' not null,
  alenuc28    char(3) default ' ' not null,
  alenuc29    char(3) default ' ' not null,
  alenuc30    char(3) default ' ' not null,
  alenuc31    char(3) default ' ' not null,
  alenuc32    char(3) default ' ' not null,
  alenuc33    char(3) default ' ' not null,
  alenuc34    char(3) default ' ' not null,
  alenuc35    char(3) default ' ' not null,
  alenuc36    char(3) default ' ' not null,
  alenuc37    char(3) default ' ' not null,
  alenuc38    char(3) default ' ' not null,
  alenuc39    char(3) default ' ' not null,
  alenuc40    char(3) default ' ' not null,
  alenuf01    decimal(14,2) default 0 not null,
  alenuf02    decimal(14,2) default 0 not null,
  alenuf03    decimal(14,2) default 0 not null,
  alenuf04    decimal(14,2) default 0 not null,
  alenuf05    decimal(14,2) default 0 not null,
  alenuf06    decimal(14,2) default 0 not null,
  alenuf07    decimal(14,2) default 0 not null,
  alenuf08    decimal(14,2) default 0 not null,
  alenuf09    decimal(14,2) default 0 not null,
  alenuf10    decimal(14,2) default 0 not null,
  alenuf11    decimal(8,0) default 0 not null,
  alenuf12    decimal(8,0) default 0 not null,
  alenuf13    decimal(8,0) default 0 not null,
  alenuf14    decimal(8,0) default 0 not null,
  alenuf15    decimal(8,0) default 0 not null,
  alenuf16    decimal(8,0) default 0 not null,
  alenuf17    decimal(8,0) default 0 not null,
  alenuf18    decimal(8,0) default 0 not null,
  alenuf19    decimal(8,0) default 0 not null,
  alenuf20    decimal(8,0) default 0 not null,
  alencmt1    char(80) default ' ' not null,
  alencmt2    char(80) default ' ' not null,
  alencomp    char(3) default ' ' not null,
  alenuniq    char(8) default ' ' not null,
  alenssac    char(1) default ' ' not null,
  alenrevd    char(8) default ' ' not null,
  alencref    char(20) default ' ' not null,
  alenpurc    char(3) default ' ' not null,
  alencont    char(3) default ' ' not null,
  alenmohr    char(1) default ' ' not null,
  alenrhos    char(5) default ' ' not null,
  alencart    char(3) default ' ' not null,
  alenstra    char(3) default ' ' not null,
  alenoutc    char(3) default ' ' not null,
  alensrvd    char(3) default ' ' not null,
  alensdep    char(3) default ' ' not null,
  alreurno    char(8) default ' ' not null,
  alrestat    char(1) default ' ' not null,
  alredact    char(8) default ' ' not null,
  alrelink    char(8) default ' ' not null,
  alrerclo    char(3) default ' ' not null,
  alredclo    char(8) default ' ' not null,
  alretclo    char(8) default ' ' not null,
  alreuclo    char(10) default ' ' not null,
  alrercan    char(3) default ' ' not null,
  alredcan    char(8) default ' ' not null,
  alretcan    char(8) default ' ' not null,
  alreucan    char(10) default ' ' not null,
  alrerina    char(3) default ' ' not null,
  alredina    char(8) default ' ' not null,
  alretina    char(8) default ' ' not null,
  alredinu    char(8) default ' ' not null,
  alreuina    char(10) default ' ' not null,
  alrerdat    char(8) default ' ' not null,
  alrerdep    char(3) default ' ' not null,
  alrerdoc    char(10) default ' ' not null,
  alrerhcp    char(10) default ' ' not null,
  alrerhcr    char(10) default ' ' not null,
  alrerhct    char(2) default ' ' not null,
  alredept    char(3) default ' ' not null,
  alreunit    char(3) default ' ' not null,
  alreprty    char(3) default ' ' not null,
  alrepro1    char(9) default ' ' not null,
  alrepro2    char(9) default ' ' not null,
  alrepro3    char(9) default ' ' not null,
  alredia1    char(9) default ' ' not null,
  alredia2    char(9) default ' ' not null,
  alredia3    char(9) default ' ' not null,
  alresrce    char(3) default ' ' not null,
  alrecomp    char(3) default ' ' not null,
  alrebulk    char(1) default ' ' not null,
  alredrev    char(8) default ' ' not null,
  alrehcp     char(10) default ' ' not null,
  alredrec    char(8) default ' ' not null,
  alreuc01    char(3) default ' ' not null,
  alreuc02    char(3) default ' ' not null,
  alreuc03    char(3) default ' ' not null,
  alreuc04    char(3) default ' ' not null,
  alreuc05    char(3) default ' ' not null,
  alreuc06    char(3) default ' ' not null,
  alreuc07    char(3) default ' ' not null,
  alreuc08    char(3) default ' ' not null,
  alreuc09    char(3) default ' ' not null,
  alreuc10    char(3) default ' ' not null,
  alreuc11    char(3) default ' ' not null,
  alreuc12    char(3) default ' ' not null,
  alreuc13    char(3) default ' ' not null,
  alreuc14    char(3) default ' ' not null,
  alreuc15    char(3) default ' ' not null,
  alreuc16    char(3) default ' ' not null,
  alreuc17    char(3) default ' ' not null,
  alreuc18    char(3) default ' ' not null,
  alreuc19    char(3) default ' ' not null,
  alreuc20    char(3) default ' ' not null,
  alreuc21    char(3) default ' ' not null,
  alreuc22    char(3) default ' ' not null,
  alreuc23    char(3) default ' ' not null,
  alreuc24    char(3) default ' ' not null,
  alreuc25    char(3) default ' ' not null,
  alreuc26    char(3) default ' ' not null,
  alreuc27    char(3) default ' ' not null,
  alreuc28    char(3) default ' ' not null,
  alreuc29    char(3) default ' ' not null,
  alreuc30    char(3) default ' ' not null,
  alreuc31    char(3) default ' ' not null,
  alreuc32    char(3) default ' ' not null,
  alreuc33    char(3) default ' ' not null,
  alreuc34    char(3) default ' ' not null,
  alreuc35    char(3) default ' ' not null,
  alreuc36    char(3) default ' ' not null,
  alreuc37    char(3) default ' ' not null,
  alreuc38    char(3) default ' ' not null,
  alreuc39    char(3) default ' ' not null,
  alreuc40    char(3) default ' ' not null,
  alreuyn1    char(1) default ' ' not null,
  alreuyn2    char(1) default ' ' not null,
  alreuyn3    char(1) default ' ' not null,
  alreuyn4    char(1) default ' ' not null,
  alreuhc1    char(10) default ' ' not null,
  alreuhc2    char(10) default ' ' not null,
  alreuhc3    char(10) default ' ' not null,
  alreuhc4    char(10) default ' ' not null,
  alreufr1    char(60) default ' ' not null,
  alreufr2    char(60) default ' ' not null,
  alreudt1    char(8) default ' ' not null,
  alreutm1    char(8) default ' ' not null,
  alreudt2    char(8) default ' ' not null,
  alreutm2    char(8) default ' ' not null,
  alreudt3    char(8) default ' ' not null,
  alreutm3    char(8) default ' ' not null,
  alreudt4    char(8) default ' ' not null,
  alreutm4    char(8) default ' ' not null,
  alreuno1    decimal(14,2) default 0 not null,
  alreuno2    decimal(14,2) default 0 not null,
  alrectyp    char(6) default ' ' not null,
  alrehosn    char(3) default ' ' not null,
  alrefhcp    char(60) default ' ' not null,
  alrehcp1    char(60) default ' ' not null,
  alrehcp2    char(60) default ' ' not null,
  alrehcp3    char(60) default ' ' not null,
  alrehcpc    char(8) default ' ' not null,
  alrehcps    char(8) default ' ' not null,
  alrehcpb    char(20) default ' ' not null,
  alrehcpf    char(20) default ' ' not null,
  alrehcpp    char(10) default ' ' not null,
  alrestyp    char(3) default ' ' not null,
  alreprcm    char(50) default ' ' not null,
  alrepsit    char(6) default ' ' not null,
  alreclid    char(6) default ' ' not null,
  alrecsta    char(3) default ' ' not null,
  alrerrej    char(3) default ' ' not null,
  alreccom    char(50) default ' ' not null,
  alrertyp    char(3) default ' ' not null,
  alrerexp    char(8) default ' ' not null,
  alremdat    char(8) default ' ' not null,
  alreprdt    char(8) default ' ' not null,
  alresrej    char(3) default ' ' not null,
  alresrdt    char(8) default ' ' not null,
  alresrtm    char(8) default ' ' not null,
  alresrui    char(10) default ' ' not null,
  alreudt5    char(8) default ' ' not null,
  alreutm5    char(8) default ' ' not null,
  alreuyn5    char(1) default ' ' not null,
  alreudid    char(10) default ' ' not null,
  alreudt6    char(8) default ' ' not null,
  alreutm6    char(8) default ' ' not null,
  alreuyn6    char(1) default ' ' not null,
  alrerevd    char(8) default ' ' not null,
  alrepurc    char(3) default ' ' not null,
  alreoutp    char(3) default ' ' not null,
  alrecont    char(3) default ' ' not null,
  alrescor    char(6) default ' ' not null,
  alremohr    char(1) default ' ' not null,
  alreevpr    char(3) default ' ' not null,
  alrediat    char(50) default ' ' not null,
  alreuyn7    char(1) default ' ' not null,
  alreuyn8    char(1) default ' ' not null,
  alreuyn9    char(1) default ' ' not null,
  alreucd1    char(1) default ' ' not null,
  alreucd2    char(1) default ' ' not null,
  alreucd3    char(1) default ' ' not null,
  alreorig    char(30) default ' ' not null,
  alreyn10    char(1) default ' ' not null,
  alreyn11    char(1) default ' ' not null,
  alreyn12    char(1) default ' ' not null,
  alreudt7    char(8) default ' ' not null,
  alreutm7    char(8) default ' ' not null,
  alreudt8    char(8) default ' ' not null,
  alreutm8    char(8) default ' ' not null,
  alreudt9    char(8) default ' ' not null,
  alreutm9    char(8) default ' ' not null,
  alreeiod    char(8) default ' ' not null,
  alreacdd    char(8) default ' ' not null,
  alreud10    char(8) default ' ' not null,
  alrenvin    char(1) default ' ' not null,
  alrecdat    char(8) default ' ' not null,
  alrectim    char(8) default ' ' not null,
  alreudat    char(8) default ' ' not null,
  alretrgs    char(3) default ' ' not null,
  alretrgd    char(8) default ' ' not null,
  alrebkov    char(3) default ' ' not null,
  alrebkpr    char(3) default ' ' not null,
  alrebkpm    char(2) default ' ' not null,
  alrebkba    char(1) default ' ' not null,
  alressub    char(3) default ' ' not null,
  alquspar    char(27) default ' ' not null,
  lf          char(1)
);
create unique index allquea1 on allqueaf
(
dalqumes
);
revoke all on allqueaf from public ; 
grant select on allqueaf to public ; 
