create table allaudre
(
  alreaudd    char(8) default ' ' not null,
  alreaudt    char(8) default ' ' not null,
  alreaudp    char(2) default ' ' not null,
  alreaudr    char(1) default ' ' not null,
  alreauds    decimal(1,0) default 0 not null,
  alreaudo    char(4) default ' ' not null,
  alrevisn    char(8) default ' ' not null,
  alreurno    char(8) default ' ' not null,
  alrestat    char(1) default ' ' not null,
  alredact    char(8) default ' ' not null,
  alrelink    char(8) default ' ' not null,
  alrerclo    char(3) default ' ' not null,
  alredclo    char(8) default ' ' not null,
  alretclo    char(8) default ' ' not null,
  alreuclo    char(10) default ' ' not null,
  alrercan    char(3) default ' ' not null,
  alredcan    char(8) default ' ' not null,
  alretcan    char(8) default ' ' not null,
  alreucan    char(10) default ' ' not null,
  alrerina    char(3) default ' ' not null,
  alredina    char(8) default ' ' not null,
  alretina    char(8) default ' ' not null,
  alredinu    char(8) default ' ' not null,
  alreuina    char(10) default ' ' not null,
  alrerdat    char(8) default ' ' not null,
  alrerdep    char(3) default ' ' not null,
  alrerdoc    char(10) default ' ' not null,
  alrerhcp    char(10) default ' ' not null,
  alrerhcr    char(10) default ' ' not null,
  alrerhct    char(2) default ' ' not null,
  alredept    char(3) default ' ' not null,
  alreunit    char(3) default ' ' not null,
  alreprty    char(3) default ' ' not null,
  alrepro1    char(9) default ' ' not null,
  alrepro2    char(9) default ' ' not null,
  alrepro3    char(9) default ' ' not null,
  alredia1    char(9) default ' ' not null,
  alredia2    char(9) default ' ' not null,
  alredia3    char(9) default ' ' not null,
  alresrce    char(3) default ' ' not null,
  alrecomp    char(3) default ' ' not null,
  alrebulk    char(1) default ' ' not null,
  alredrev    char(8) default ' ' not null,
  alrehcp     char(10) default ' ' not null,
  alredrec    char(8) default ' ' not null,
  alreuc01    char(3) default ' ' not null,
  alreuc02    char(3) default ' ' not null,
  alreuc03    char(3) default ' ' not null,
  alreuc04    char(3) default ' ' not null,
  alreuc05    char(3) default ' ' not null,
  alreuc06    char(3) default ' ' not null,
  alreuc07    char(3) default ' ' not null,
  alreuc08    char(3) default ' ' not null,
  alreuc09    char(3) default ' ' not null,
  alreuc10    char(3) default ' ' not null,
  alreuc11    char(3) default ' ' not null,
  alreuc12    char(3) default ' ' not null,
  alreuc13    char(3) default ' ' not null,
  alreuc14    char(3) default ' ' not null,
  alreuc15    char(3) default ' ' not null,
  alreuc16    char(3) default ' ' not null,
  alreuc17    char(3) default ' ' not null,
  alreuc18    char(3) default ' ' not null,
  alreuc19    char(3) default ' ' not null,
  alreuc20    char(3) default ' ' not null,
  alreuc21    char(3) default ' ' not null,
  alreuc22    char(3) default ' ' not null,
  alreuc23    char(3) default ' ' not null,
  alreuc24    char(3) default ' ' not null,
  alreuc25    char(3) default ' ' not null,
  alreuc26    char(3) default ' ' not null,
  alreuc27    char(3) default ' ' not null,
  alreuc28    char(3) default ' ' not null,
  alreuc29    char(3) default ' ' not null,
  alreuc30    char(3) default ' ' not null,
  alreuc31    char(3) default ' ' not null,
  alreuc32    char(3) default ' ' not null,
  alreuc33    char(3) default ' ' not null,
  alreuc34    char(3) default ' ' not null,
  alreuc35    char(3) default ' ' not null,
  alreuc36    char(3) default ' ' not null,
  alreuc37    char(3) default ' ' not null,
  alreuc38    char(3) default ' ' not null,
  alreuc39    char(3) default ' ' not null,
  alreuc40    char(3) default ' ' not null,
  alreuyn1    char(1) default ' ' not null,
  alreuyn2    char(1) default ' ' not null,
  alreuyn3    char(1) default ' ' not null,
  alreuyn4    char(1) default ' ' not null,
  alreuhc1    char(10) default ' ' not null,
  alreuhc2    char(10) default ' ' not null,
  alreuhc3    char(10) default ' ' not null,
  alreuhc4    char(10) default ' ' not null,
  alreufr1    char(60) default ' ' not null,
  alreufr2    char(60) default ' ' not null,
  alreudt1    char(8) default ' ' not null,
  alreutm1    char(8) default ' ' not null,
  alreudt2    char(8) default ' ' not null,
  alreutm2    char(8) default ' ' not null,
  alreudt3    char(8) default ' ' not null,
  alreutm3    char(8) default ' ' not null,
  alreudt4    char(8) default ' ' not null,
  alreutm4    char(8) default ' ' not null,
  alreuno1    decimal(14,2) default 0 not null,
  alreuno2    decimal(14,2) default 0 not null,
  alrecdat    char(8) default ' ' not null,
  alrectim    char(8) default ' ' not null,
  alrecuid    char(10) default ' ' not null,
  alreudat    char(8) default ' ' not null,
  alreutim    char(8) default ' ' not null,
  alreuuid    char(10) default ' ' not null,
  alrectyp    char(6) default ' ' not null,
  alrehosn    char(3) default ' ' not null,
  alrefhcp    char(60) default ' ' not null,
  alrehcp1    char(60) default ' ' not null,
  alrehcp2    char(60) default ' ' not null,
  alrehcp3    char(60) default ' ' not null,
  alrehcpc    char(8) default ' ' not null,
  alrehcps    char(8) default ' ' not null,
  alrehcpb    char(20) default ' ' not null,
  alrehcpf    char(20) default ' ' not null,
  alrehcpp    char(10) default ' ' not null,
  alrestyp    char(3) default ' ' not null,
  alreprcm    char(50) default ' ' not null,
  alrepsit    char(6) default ' ' not null,
  alreclid    char(6) default ' ' not null,
  alrecsta    char(3) default ' ' not null,
  alrerrej    char(3) default ' ' not null,
  alreccom    char(50) default ' ' not null,
  alrertyp    char(3) default ' ' not null,
  alrerexp    char(8) default ' ' not null,
  alremdat    char(8) default ' ' not null,
  alreprdt    char(8) default ' ' not null,
  alresrej    char(3) default ' ' not null,
  alresrdt    char(8) default ' ' not null,
  alresrtm    char(8) default ' ' not null,
  alresrui    char(10) default ' ' not null,
  alreudt5    char(8) default ' ' not null,
  alreutm5    char(8) default ' ' not null,
  alreuyn5    char(1) default ' ' not null,
  alreudid    char(10) default ' ' not null,
  alreudt6    char(8) default ' ' not null,
  alreutm6    char(8) default ' ' not null,
  alreuyn6    char(1) default ' ' not null,
  alrerevd    char(8) default ' ' not null,
  alrepurc    char(3) default ' ' not null,
  alreoutp    char(3) default ' ' not null,
  alrecont    char(3) default ' ' not null,
  alrescor    char(6) default ' ' not null,
  alremohr    char(1) default ' ' not null,
  alreevpr    char(3) default ' ' not null,
  alrediat    char(50) default ' ' not null,
  alreuyn7    char(1) default ' ' not null,
  alreuyn8    char(1) default ' ' not null,
  alreuyn9    char(1) default ' ' not null,
  alreucd1    char(1) default ' ' not null,
  alreucd2    char(1) default ' ' not null,
  alreucd3    char(1) default ' ' not null,
  alreorig    char(30) default ' ' not null,
  alreyn10    char(1) default ' ' not null,
  alreyn11    char(1) default ' ' not null,
  alreyn12    char(1) default ' ' not null,
  alreudt7    char(8) default ' ' not null,
  alreutm7    char(8) default ' ' not null,
  alreudt8    char(8) default ' ' not null,
  alreutm8    char(8) default ' ' not null,
  alreudt9    char(8) default ' ' not null,
  alreutm9    char(8) default ' ' not null,
  alreeiod    char(8) default ' ' not null,
  alreacdd    char(8) default ' ' not null,
  alreud10    char(8) default ' ' not null,
  alrenvin    char(1) default ' ' not null,
  alreuhc5    char(10) default ' ' not null,
  alreuhc6    char(10) default ' ' not null,
  alreuhc7    char(10) default ' ' not null,
  alreuhc8    char(10) default ' ' not null,
  alrerrdt    char(8) default ' ' not null,
  alredia4    char(9) default ' ' not null,
  alredia5    char(9) default ' ' not null,
  alreprc1    char(9) default ' ' not null,
  alreprc2    char(9) default ' ' not null,
  alreprc3    char(9) default ' ' not null,
  alreprc4    char(9) default ' ' not null,
  alreprc5    char(9) default ' ' not null,
  alreud11    char(8) default ' ' not null,
  alreut11    char(8) default ' ' not null,
  alreud12    char(8) default ' ' not null,
  alreut12    char(8) default ' ' not null,
  alreud13    char(8) default ' ' not null,
  alreut13    char(8) default ' ' not null,
  alreud14    char(8) default ' ' not null,
  alreut14    char(8) default ' ' not null,
  alreud15    char(8) default ' ' not null,
  alreut15    char(8) default ' ' not null,
  alretrgs    char(3) default ' ' not null,
  alretrgd    char(8) default ' ' not null,
  alrebkov    char(3) default ' ' not null,
  alrebkpr    char(3) default ' ' not null,
  alrebkpm    char(2) default ' ' not null,
  alrebkba    char(1) default ' ' not null,
  alreftsc    char(3) default ' ' not null,
  alressub    char(3) default ' ' not null,
  alrespar    char(44) default ' ' not null,
  lf          char(1)
);
create index allaudre on allaudre
(
alreaudd,
alreaudt,
alreaudp,
alreaudr
);
create index allaudr2 on allaudre
(
alrevisn,
alreaudd,
alreaudt,
alreaudp,
alreaudr
);
revoke all on allaudre from public ; 
grant select on allaudre to public ; 
create table allrefaf
(
  alrevisn    char(8) default ' ' not null,
  alreurno    char(8) default ' ' not null,
  alrestat    char(1) default ' ' not null,
  alredact    char(8) default ' ' not null,
  alrelink    char(8) default ' ' not null,
  alrerclo    char(3) default ' ' not null,
  alredclo    char(8) default ' ' not null,
  alretclo    char(8) default ' ' not null,
  alreuclo    char(10) default ' ' not null,
  alrercan    char(3) default ' ' not null,
  alredcan    char(8) default ' ' not null,
  alretcan    char(8) default ' ' not null,
  alreucan    char(10) default ' ' not null,
  alrerina    char(3) default ' ' not null,
  alredina    char(8) default ' ' not null,
  alretina    char(8) default ' ' not null,
  alredinu    char(8) default ' ' not null,
  alreuina    char(10) default ' ' not null,
  alrerdat    char(8) default ' ' not null,
  alrerdep    char(3) default ' ' not null,
  alrerdoc    char(10) default ' ' not null,
  alrerhcp    char(10) default ' ' not null,
  alrerhcr    char(10) default ' ' not null,
  alrerhct    char(2) default ' ' not null,
  alredept    char(3) default ' ' not null,
  alreunit    char(3) default ' ' not null,
  alreprty    char(3) default ' ' not null,
  alrepro1    char(9) default ' ' not null,
  alrepro2    char(9) default ' ' not null,
  alrepro3    char(9) default ' ' not null,
  alredia1    char(9) default ' ' not null,
  alredia2    char(9) default ' ' not null,
  alredia3    char(9) default ' ' not null,
  alresrce    char(3) default ' ' not null,
  alrecomp    char(3) default ' ' not null,
  alrebulk    char(1) default ' ' not null,
  alredrev    char(8) default ' ' not null,
  alrehcp     char(10) default ' ' not null,
  alredrec    char(8) default ' ' not null,
  alreuc01    char(3) default ' ' not null,
  alreuc02    char(3) default ' ' not null,
  alreuc03    char(3) default ' ' not null,
  alreuc04    char(3) default ' ' not null,
  alreuc05    char(3) default ' ' not null,
  alreuc06    char(3) default ' ' not null,
  alreuc07    char(3) default ' ' not null,
  alreuc08    char(3) default ' ' not null,
  alreuc09    char(3) default ' ' not null,
  alreuc10    char(3) default ' ' not null,
  alreuc11    char(3) default ' ' not null,
  alreuc12    char(3) default ' ' not null,
  alreuc13    char(3) default ' ' not null,
  alreuc14    char(3) default ' ' not null,
  alreuc15    char(3) default ' ' not null,
  alreuc16    char(3) default ' ' not null,
  alreuc17    char(3) default ' ' not null,
  alreuc18    char(3) default ' ' not null,
  alreuc19    char(3) default ' ' not null,
  alreuc20    char(3) default ' ' not null,
  alreuc21    char(3) default ' ' not null,
  alreuc22    char(3) default ' ' not null,
  alreuc23    char(3) default ' ' not null,
  alreuc24    char(3) default ' ' not null,
  alreuc25    char(3) default ' ' not null,
  alreuc26    char(3) default ' ' not null,
  alreuc27    char(3) default ' ' not null,
  alreuc28    char(3) default ' ' not null,
  alreuc29    char(3) default ' ' not null,
  alreuc30    char(3) default ' ' not null,
  alreuc31    char(3) default ' ' not null,
  alreuc32    char(3) default ' ' not null,
  alreuc33    char(3) default ' ' not null,
  alreuc34    char(3) default ' ' not null,
  alreuc35    char(3) default ' ' not null,
  alreuc36    char(3) default ' ' not null,
  alreuc37    char(3) default ' ' not null,
  alreuc38    char(3) default ' ' not null,
  alreuc39    char(3) default ' ' not null,
  alreuc40    char(3) default ' ' not null,
  alreuyn1    char(1) default ' ' not null,
  alreuyn2    char(1) default ' ' not null,
  alreuyn3    char(1) default ' ' not null,
  alreuyn4    char(1) default ' ' not null,
  alreuhc1    char(10) default ' ' not null,
  alreuhc2    char(10) default ' ' not null,
  alreuhc3    char(10) default ' ' not null,
  alreuhc4    char(10) default ' ' not null,
  alreufr1    char(60) default ' ' not null,
  alreufr2    char(60) default ' ' not null,
  alreudt1    char(8) default ' ' not null,
  alreutm1    char(8) default ' ' not null,
  alreudt2    char(8) default ' ' not null,
  alreutm2    char(8) default ' ' not null,
  alreudt3    char(8) default ' ' not null,
  alreutm3    char(8) default ' ' not null,
  alreudt4    char(8) default ' ' not null,
  alreutm4    char(8) default ' ' not null,
  alreuno1    decimal(14,2) default 0 not null,
  alreuno2    decimal(14,2) default 0 not null,
  alrecdat    char(8) default ' ' not null,
  alrectim    char(8) default ' ' not null,
  alrecuid    char(10) default ' ' not null,
  alreudat    char(8) default ' ' not null,
  alreutim    char(8) default ' ' not null,
  alreuuid    char(10) default ' ' not null,
  alrectyp    char(6) default ' ' not null,
  alrehosn    char(3) default ' ' not null,
  alrefhcp    char(60) default ' ' not null,
  alrehcp1    char(60) default ' ' not null,
  alrehcp2    char(60) default ' ' not null,
  alrehcp3    char(60) default ' ' not null,
  alrehcpc    char(8) default ' ' not null,
  alrehcps    char(8) default ' ' not null,
  alrehcpb    char(20) default ' ' not null,
  alrehcpf    char(20) default ' ' not null,
  alrehcpp    char(10) default ' ' not null,
  alrestyp    char(3) default ' ' not null,
  alreprcm    char(50) default ' ' not null,
  alrepsit    char(6) default ' ' not null,
  alreclid    char(6) default ' ' not null,
  alrecsta    char(3) default ' ' not null,
  alrerrej    char(3) default ' ' not null,
  alreccom    char(50) default ' ' not null,
  alrertyp    char(3) default ' ' not null,
  alrerexp    char(8) default ' ' not null,
  alremdat    char(8) default ' ' not null,
  alreprdt    char(8) default ' ' not null,
  alresrej    char(3) default ' ' not null,
  alresrdt    char(8) default ' ' not null,
  alresrtm    char(8) default ' ' not null,
  alresrui    char(10) default ' ' not null,
  alreudt5    char(8) default ' ' not null,
  alreutm5    char(8) default ' ' not null,
  alreuyn5    char(1) default ' ' not null,
  alreudid    char(10) default ' ' not null,
  alreudt6    char(8) default ' ' not null,
  alreutm6    char(8) default ' ' not null,
  alreuyn6    char(1) default ' ' not null,
  alrerevd    char(8) default ' ' not null,
  alrepurc    char(3) default ' ' not null,
  alreoutp    char(3) default ' ' not null,
  alrecont    char(3) default ' ' not null,
  alrescor    char(6) default ' ' not null,
  alremohr    char(1) default ' ' not null,
  alreevpr    char(3) default ' ' not null,
  alrediat    char(50) default ' ' not null,
  alreuyn7    char(1) default ' ' not null,
  alreuyn8    char(1) default ' ' not null,
  alreuyn9    char(1) default ' ' not null,
  alreucd1    char(1) default ' ' not null,
  alreucd2    char(1) default ' ' not null,
  alreucd3    char(1) default ' ' not null,
  alreorig    char(30) default ' ' not null,
  alreyn10    char(1) default ' ' not null,
  alreyn11    char(1) default ' ' not null,
  alreyn12    char(1) default ' ' not null,
  alreudt7    char(8) default ' ' not null,
  alreutm7    char(8) default ' ' not null,
  alreudt8    char(8) default ' ' not null,
  alreutm8    char(8) default ' ' not null,
  alreudt9    char(8) default ' ' not null,
  alreutm9    char(8) default ' ' not null,
  alreeiod    char(8) default ' ' not null,
  alreacdd    char(8) default ' ' not null,
  alreud10    char(8) default ' ' not null,
  alrenvin    char(1) default ' ' not null,
  alreuhc5    char(10) default ' ' not null,
  alreuhc6    char(10) default ' ' not null,
  alreuhc7    char(10) default ' ' not null,
  alreuhc8    char(10) default ' ' not null,
  alrerrdt    char(8) default ' ' not null,
  alredia4    char(9) default ' ' not null,
  alredia5    char(9) default ' ' not null,
  alreprc1    char(9) default ' ' not null,
  alreprc2    char(9) default ' ' not null,
  alreprc3    char(9) default ' ' not null,
  alreprc4    char(9) default ' ' not null,
  alreprc5    char(9) default ' ' not null,
  alreud11    char(8) default ' ' not null,
  alreut11    char(8) default ' ' not null,
  alreud12    char(8) default ' ' not null,
  alreut12    char(8) default ' ' not null,
  alreud13    char(8) default ' ' not null,
  alreut13    char(8) default ' ' not null,
  alreud14    char(8) default ' ' not null,
  alreut14    char(8) default ' ' not null,
  alreud15    char(8) default ' ' not null,
  alreut15    char(8) default ' ' not null,
  alretrgs    char(3) default ' ' not null,
  alretrgd    char(8) default ' ' not null,
  alrebkov    char(3) default ' ' not null,
  alrebkpr    char(3) default ' ' not null,
  alrebkpm    char(2) default ' ' not null,
  alrebkba    char(1) default ' ' not null,
  alreftsc    char(3) default ' ' not null,
  alressub    char(3) default ' ' not null,
  alrespar    char(44) default ' ' not null,
  lf          char(1)
);
create unique index allrefa1 on allrefaf
(
alrevisn
);
create unique index allrefa2 on allrefaf
(
alreurno,
alrevisn
);
create unique index allrefa3 on allrefaf
(
alrestat,
alrerdat,
alrevisn
);
create unique index allrefa4 on allrefaf
(
alredept,
alrestat,
alrehcp,
alrevisn
);
create unique index allrefa5 on allrefaf
(
alrehcp,
alrestat,
alrerdat,
alrevisn
);
create unique index allrefa6 on allrefaf
(
alredept,
alrestat,
alrerdat,
alrehcp,
alrevisn
);
create unique index allrefa7 on allrefaf
(
alredept,
alrestat,
alredrec,
alrehcp,
alrevisn
);
revoke all on allrefaf from public ; 
grant select on allrefaf to public ; 
