create table bokqueaf
(
  dbkqumes    char(20) default ' ' not null,
  bkrebook    char(8) default ' ' not null,
  bkreurno    char(8) default ' ' not null,
  bkreadoc    char(6) default ' ' not null,
  bkresdoc    char(6) default ' ' not null,
  bkreedat    char(8) default ' ' not null,
  bkreatim    char(8) default ' ' not null,
  bkrepdat    char(8) default ' ' not null,
  bkreptim    char(8) default ' ' not null,
  bkreadat    char(8) default ' ' not null,
  bkretype    char(3) default ' ' not null,
  bkrecanc    char(3) default ' ' not null,
  bkreomem    char(1) default ' ' not null,
  bkreprev    char(1) default ' ' not null,
  bkreaccm    char(3) default ' ' not null,
  bkreproc    char(9) default ' ' not null,
  bkrecnt     decimal(2,0) default 0 not null,
  bkreward    char(3) default ' ' not null,
  bkreadmn    char(8) default ' ' not null,
  bkreprea    char(1) default ' ' not null,
  bkreebed    char(3) default ' ' not null,
  bkreclss    char(3) default ' ' not null,
  bkreatyp    char(3) default ' ' not null,
  bkredept    char(3) default ' ' not null,
  bkretdoc    char(6) default ' ' not null,
  bkreclmt    char(3) default ' ' not null,
  bkrerfgp    char(8) default ' ' not null,
  bkregppc    char(6) default ' ' not null,
  bkregpfa    char(20) default ' ' not null,
  bkreresi    char(3) default ' ' not null,
  bkreeaty    char(3) default ' ' not null,
  bkreecra    char(20) default ' ' not null,
  bkregppt    char(2) default ' ' not null,
  bkredofr    char(3) default ' ' not null,
  bkreoper    char(4) default ' ' not null,
  bkreelos    decimal(3,0) default 0 not null,
  bkrebkdt    char(8) default ' ' not null,
  bkrxpowd    char(3) default ' ' not null,
  bkrxadwd    char(3) default ' ' not null,
  bkrxcdte    char(8) default ' ' not null,
  bkrxpsty    char(1) default ' ' not null,
  bkrxcndt    char(8) default ' ' not null,
  bkrxudf1    char(3) default ' ' not null,
  bkrxudf2    char(3) default ' ' not null,
  bkrxudf3    char(3) default ' ' not null,
  bkrxudf4    char(3) default ' ' not null,
  bkrxudf5    char(3) default ' ' not null,
  bkrxudd1    char(8) default ' ' not null,
  bkrxudd2    char(8) default ' ' not null,
  bkrxudd3    char(8) default ' ' not null,
  bkrxudd4    char(8) default ' ' not null,
  bkrxuff1    char(50) default ' ' not null,
  bkrxuff2    char(50) default ' ' not null,
  bkrxuff3    char(50) default ' ' not null,
  bkrxuff4    char(50) default ' ' not null,
  bkrxedc1    char(10) default ' ' not null,
  bkrxedc2    char(10) default ' ' not null,
  bkrxedc3    char(10) default ' ' not null,
  bkrxodte    char(8) default ' ' not null,
  bkrxoprd    char(3) default ' ' not null,
  bkquspar    char(65) default ' ' not null,
  lf          char(1)
);
create unique index bokquea1 on bokqueaf
(
dbkqumes
);
revoke all on bokqueaf from public ; 
grant select on bokqueaf to public ; 
