create table bokrauaf
(
  bkruaurq    char(10) default ' ' not null,
  bkruauty    char(1) default ' ' not null,
  bkruadat    char(8) default ' ' not null,
  bkruatim    char(8) default ' ' not null,
  bkruausr    char(10) default ' ' not null,
  bkruurno    char(8) default ' ' not null,
  bkruvisn    char(8) default ' ' not null,
  bkrubkty    char(3) default ' ' not null,
  bkrureqn    char(10) default ' ' not null,
  bkrustat    char(1) default ' ' not null,
  bkruhosp    char(3) default ' ' not null,
  bkruprio    char(3) default ' ' not null,
  bkrusnam    char(40) default ' ' not null,
  bkrugnam    char(40) default ' ' not null,
  bkrubdat    char(8) default ' ' not null,
  bkrugend    char(1) default ' ' not null,
  bkrurdoc    char(10) default ' ' not null,
  bkruunit    char(3) default ' ' not null,
  bkrucsdt    char(8) default ' ' not null,
  bkrucstm    char(8) default ' ' not null,
  bkructct    char(100) default ' ' not null,
  bkrulocn    char(50) default ' ' not null,
  bkruadpt    char(3) default ' ' not null,
  bkruepow    char(3) default ' ' not null,
  bkrusurg    char(10) default ' ' not null,
  bkruthet    char(6) default ' ' not null,
  bkruanae    char(3) default ' ' not null,
  bkrumbs1    char(9) default ' ' not null,
  bkrumbs2    char(9) default ' ' not null,
  bkrumbs3    char(9) default ' ' not null,
  bkrumbd1    char(80) default ' ' not null,
  bkrumbd2    char(80) default ' ' not null,
  bkrumbd3    char(80) default ' ' not null,
  bkrupror    char(40) default ' ' not null,
  bkrudura    char(3) default ' ' not null,
  bkruinfc    char(3) default ' ' not null,
  bkruequ1    char(3) default ' ' not null,
  bkruequ2    char(3) default ' ' not null,
  bkruequ3    char(3) default ' ' not null,
  bkrucdat    char(8) default ' ' not null,
  bkructim    char(8) default ' ' not null,
  bkrucusr    char(10) default ' ' not null,
  bkruudat    char(8) default ' ' not null,
  bkruutim    char(8) default ' ' not null,
  bkruuusr    char(10) default ' ' not null,
  bkrucndt    char(8) default ' ' not null,
  bkrucntm    char(8) default ' ' not null,
  bkrucnus    char(10) default ' ' not null,
  bkrucncd    char(3) default ' ' not null,
  bkruopty    char(3) default ' ' not null,
  bkrutrcd    char(3) default ' ' not null,
  bkruatcd    char(3) default ' ' not null,
  bkruatyp    char(3) default ' ' not null,
  bkructyp    char(3) default ' ' not null,
  bkruelos    char(3) default ' ' not null,
  bkructy6    char(3) default ' ' not null,
  bkructy7    char(3) default ' ' not null,
  bkructy8    char(3) default ' ' not null,
  bkructy9    char(3) default ' ' not null,
  bkruasrc    char(3) default ' ' not null,
  bkrubtyp    char(3) default ' ' not null,
  bkruelon    char(3) default ' ' not null,
  bkrucsnt    char(1) default ' ' not null,
  bkruccdt    char(8) default ' ' not null,
  bkruspar    char(100) default ' ' not null,
  lf          char(1)
);
create unique index bokraua1 on bokrauaf
(
bkruaurq,
bkruadat,
bkruatim,
bkruauty
);
revoke all on bokrauaf from public ; 
grant select on bokrauaf to public ; 
