create table ccsaudep
(
  ccepaudd    char(8) default ' ' not null,
  ccepaudt    char(8) default ' ' not null,
  ccepaudp    char(2) default ' ' not null,
  ccepaudr    char(1) default ' ' not null,
  ccepauds    decimal(1,0) default 0 not null,
  ccepaudo    char(4) default ' ' not null,
  ccephcd     char(2) default ' ' not null,
  ccepeps     char(16) default ' ' not null,
  ccepsur     char(20) default ' ' not null,
  ccepgiv     char(25) default ' ' not null,
  ccepcom     char(1) default ' ' not null,
  ccepurn     char(10) default ' ' not null,
  ccepsdt     char(8) default ' ' not null,
  ccepltd     char(8) default ' ' not null,
  cceplos     decimal(6,0) default 0 not null,
  ccepinpt    char(1) default ' ' not null,
  ccepday     char(1) default ' ' not null,
  ccepvist    char(2) default ' ' not null,
  ccepsex     char(1) default ' ' not null,
  ccepdob     char(8) default ' ' not null,
  ccepagey    char(3) default ' ' not null,
  ccepagem    char(2) default ' ' not null,
  ccepaged    char(2) default ' ' not null,
  ccepcob     char(3) default ' ' not null,
  cceprel     char(3) default ' ' not null,
  ccepddat    char(8) default ' ' not null,
  ccepdwar    char(3) default ' ' not null,
  ccepdsta    char(3) default ' ' not null,
  ccepddes    char(3) default ' ' not null,
  ccepdmbs    char(9) default ' ' not null,
  ccepddpt    char(3) default ' ' not null,
  ccepdser    char(3) default ' ' not null,
  ccepmdcc    char(4) default ' ' not null,
  ccepdrgc    char(4) default ' ' not null,
  ccepadat    char(8) default ' ' not null,
  ccepawar    char(3) default ' ' not null,
  ccepasrc    char(3) default ' ' not null,
  ccepacls    char(3) default ' ' not null,
  ccepacar    char(3) default ' ' not null,
  ccepadpt    char(3) default ' ' not null,
  ccepaser    char(3) default ' ' not null,
  ccepardc    char(10) default ' ' not null,
  ccepatdc    char(10) default ' ' not null,
  ccepaadc    char(10) default ' ' not null,
  ccepdadc    char(10) default ' ' not null,
  ccepahfd    char(6) default ' ' not null,
  ccepahtb    char(8) default ' ' not null,
  ccepambs    char(9) default ' ' not null,
  ccepopcl    char(6) default ' ' not null,
  cceppdia    char(9) default ' ' not null,
  ccepsdia    char(9) default ' ' not null,
  cceppopp    char(9) default ' ' not null,
  ccepsopp    char(9) default ' ' not null,
  ccepexc     char(1) default ' ' not null,
  cceppmbs    char(9) default ' ' not null,
  ccepsmbs    char(9) default ' ' not null,
  ccepmu1     char(3) default ' ' not null,
  ccepmu2     char(3) default ' ' not null,
  ccepmu3     char(3) default ' ' not null,
  ccepmu4     char(3) default ' ' not null,
  ccepmu5     char(3) default ' ' not null,
  ccepmu6     char(3) default ' ' not null,
  ccepmu7     char(3) default ' ' not null,
  cceppcd     char(10) default ' ' not null,
  ccepclm     char(3) default ' ' not null,
  ccepcli     char(6) default ' ' not null,
  ccepcty     char(3) default ' ' not null,
  ccepana     char(3) default ' ' not null,
  ccepoty     char(3) default ' ' not null,
  ccepttr     char(3) default ' ' not null,
  ccepoy6     char(3) default ' ' not null,
  ccepoy7     char(3) default ' ' not null,
  ccepoy8     char(3) default ' ' not null,
  ccepoy9     char(3) default ' ' not null,
  cceporm     char(6) default ' ' not null,
  ccepoki     char(3) default ' ' not null,
  ccepotp     char(3) default ' ' not null,
  cceptst     char(3) default ' ' not null,
  ccepins     char(3) default ' ' not null,
  cceptim     char(5) default ' ' not null,
  cceptdp     char(5) default ' ' not null,
  ccepast     char(3) default ' ' not null,
  ccepamd     char(3) default ' ' not null,
  ccepau1     char(3) default ' ' not null,
  ccepau2     char(3) default ' ' not null,
  ccepau3     char(3) default ' ' not null,
  ccepau4     char(3) default ' ' not null,
  ccepau5     char(3) default ' ' not null,
  ccepau6     char(3) default ' ' not null,
  ccepau7     char(3) default ' ' not null,
  ccepau8     char(3) default ' ' not null,
  ccepawt     char(3) default ' ' not null,
  ccepapr     char(3) default ' ' not null,
  ccepaet     char(3) default ' ' not null,
  ccepart     char(3) default ' ' not null,
  ccepain     char(3) default ' ' not null,
  ccepapl     char(3) default ' ' not null,
  ccepapy     char(3) default ' ' not null,
  ccepost     char(6) default ' ' not null,
  ccepocl     char(6) default ' ' not null,
  ccepoct     char(6) default ' ' not null,
  ccepovt     char(3) default ' ' not null,
  ccepody     char(1) default ' ' not null,
  cceposs     char(3) default ' ' not null,
  ccepods     char(3) default ' ' not null,
  ccepoat     char(3) default ' ' not null,
  ccepopr     char(3) default ' ' not null,
  ccepou1     char(3) default ' ' not null,
  ccepou2     char(3) default ' ' not null,
  ccepou3     char(3) default ' ' not null,
  ccepou4     char(3) default ' ' not null,
  ccepodp     char(3) default ' ' not null,
  ccepotr     char(3) default ' ' not null,
  ccepolg     char(3) default ' ' not null,
  ccepoot     char(3) default ' ' not null,
  ccepmu8     char(3) default ' ' not null,
  ccepmu9     char(3) default ' ' not null,
  ccepmu10    char(3) default ' ' not null,
  ccepphp     char(3) default ' ' not null,
  ccepagn     char(3) default ' ' not null,
  ccepvw5     decimal(12,4) default 0 not null,
  ccepv5a     decimal(12,4) default 0 not null,
  ccepcmx     char(1) default ' ' not null,
  ccepv8a     decimal(12,4) default 0 not null,
  ccepintr    char(1) default ' ' not null,
  ccepstat    char(1) default ' ' not null,
  ccepcind    char(3) default ' ' not null,
  ccepspca    char(3) default ' ' not null,
  cceprsta    char(1) default ' ' not null,
  cceprhcp    char(10) default ' ' not null,
  ccepprb1    char(9) default ' ' not null,
  ccepprb2    char(9) default ' ' not null,
  ccepprb3    char(9) default ' ' not null,
  ccepdia1    char(9) default ' ' not null,
  ccepdia2    char(9) default ' ' not null,
  ccepdia3    char(9) default ' ' not null,
  ccepencn    char(3) default ' ' not null,
  ccepserp    char(10) default ' ' not null,
  ccepacty    char(6) default ' ' not null,
  ccepserd    char(8) default ' ' not null,
  ccepptyp    char(3) default ' ' not null,
  ccepdept    char(3) default ' ' not null,
  ccepdunt    decimal(6,0) default 0 not null,
  ccepdbun    decimal(6,0) default 0 not null,
  ccepiunt    decimal(6,0) default 0 not null,
  ccepibun    decimal(6,0) default 0 not null,
  ccepabrg    char(3) default ' ' not null,
  ccepcadm    char(3) default ' ' not null,
  ccepirad    char(3) default ' ' not null,
  ccepidus    char(3) default ' ' not null,
  ccepcrav    char(3) default ' ' not null,
  cceprcct    char(3) default ' ' not null,
  ccepindc    char(1) default ' ' not null,
  ccepmdav    char(3) default ' ' not null,
  ccepcsng    char(3) default ' ' not null,
  ccepasut    char(3) default ' ' not null,
  ccepelps    char(3) default ' ' not null,
  ccepempl    char(3) default ' ' not null,
  ccepfinp    char(3) default ' ' not null,
  ccepoccp    char(3) default ' ' not null,
  cceppalc    char(3) default ' ' not null,
  ccepppal    char(3) default ' ' not null,
  cceppppt    char(3) default ' ' not null,
  cceppsos    char(3) default ' ' not null,
  cceppysp    char(3) default ' ' not null,
  ccepqldb    char(3) default ' ' not null,
  ccepread    char(3) default ' ' not null,
  ccepudin    char(3) default ' ' not null,
  ccepurea    char(3) default ' ' not null,
  ccepusac    char(3) default ' ' not null,
  ccepuvth    char(3) default ' ' not null,
  ccepdvac    char(3) default ' ' not null,
  ccepfldr    char(3) default ' ' not null,
  cceppccl    char(1) default ' ' not null,
  ccepsdrg    char(4) default ' ' not null,
  ccepuint    decimal(4,0) default 0 not null,
  ccepuccu    decimal(4,0) default 0 not null,
  ccepumec    decimal(4,0) default 0 not null,
  ccepcpap    decimal(5,0) default 0 not null,
  cceprclo    char(3) default ' ' not null,
  ccepsrce    char(3) default ' ' not null,
  ccepstyp    char(6) default ' ' not null,
  ccepasit    char(6) default ' ' not null,
  ccepuc21    char(3) default ' ' not null,
  ccepuc09    char(3) default ' ' not null,
  ccepuc20    char(3) default ' ' not null,
  ccepuc28    char(3) default ' ' not null,
  cceprhc1    char(10) default ' ' not null,
  ccepadts    char(5) default ' ' not null,
  ccepdcts    char(5) default ' ' not null,
  ccepspa     char(50) default ' ' not null,
  lf          char(1)
);
create index ccsaudep on ccsaudep
(
ccepaudd,
ccepaudt,
ccepaudp,
ccepaudr
);
revoke all on ccsaudep from public ; 
grant select on ccsaudep to public ; 
create table ccsepsaf
(
  ccephcd     char(2) default ' ' not null,
  ccepeps     char(16) default ' ' not null,
  ccepsur     char(20) default ' ' not null,
  ccepgiv     char(25) default ' ' not null,
  ccepcom     char(1) default ' ' not null,
  ccepurn     char(10) default ' ' not null,
  ccepsdt     char(8) default ' ' not null,
  ccepltd     char(8) default ' ' not null,
  cceplos     decimal(6,0) default 0 not null,
  ccepinpt    char(1) default ' ' not null,
  ccepday     char(1) default ' ' not null,
  ccepvist    char(2) default ' ' not null,
  ccepsex     char(1) default ' ' not null,
  ccepdob     char(8) default ' ' not null,
  ccepagey    char(3) default ' ' not null,
  ccepagem    char(2) default ' ' not null,
  ccepaged    char(2) default ' ' not null,
  ccepcob     char(3) default ' ' not null,
  cceprel     char(3) default ' ' not null,
  ccepddat    char(8) default ' ' not null,
  ccepdwar    char(3) default ' ' not null,
  ccepdsta    char(3) default ' ' not null,
  ccepddes    char(3) default ' ' not null,
  ccepdmbs    char(9) default ' ' not null,
  ccepddpt    char(3) default ' ' not null,
  ccepdser    char(3) default ' ' not null,
  ccepmdcc    char(4) default ' ' not null,
  ccepdrgc    char(4) default ' ' not null,
  ccepadat    char(8) default ' ' not null,
  ccepawar    char(3) default ' ' not null,
  ccepasrc    char(3) default ' ' not null,
  ccepacls    char(3) default ' ' not null,
  ccepacar    char(3) default ' ' not null,
  ccepadpt    char(3) default ' ' not null,
  ccepaser    char(3) default ' ' not null,
  ccepardc    char(10) default ' ' not null,
  ccepatdc    char(10) default ' ' not null,
  ccepaadc    char(10) default ' ' not null,
  ccepdadc    char(10) default ' ' not null,
  ccepahfd    char(6) default ' ' not null,
  ccepahtb    char(8) default ' ' not null,
  ccepambs    char(9) default ' ' not null,
  ccepopcl    char(6) default ' ' not null,
  cceppdia    char(9) default ' ' not null,
  ccepsdia    char(9) default ' ' not null,
  cceppopp    char(9) default ' ' not null,
  ccepsopp    char(9) default ' ' not null,
  ccepexc     char(1) default ' ' not null,
  cceppmbs    char(9) default ' ' not null,
  ccepsmbs    char(9) default ' ' not null,
  ccepmu1     char(3) default ' ' not null,
  ccepmu2     char(3) default ' ' not null,
  ccepmu3     char(3) default ' ' not null,
  ccepmu4     char(3) default ' ' not null,
  ccepmu5     char(3) default ' ' not null,
  ccepmu6     char(3) default ' ' not null,
  ccepmu7     char(3) default ' ' not null,
  cceppcd     char(10) default ' ' not null,
  ccepclm     char(3) default ' ' not null,
  ccepcli     char(6) default ' ' not null,
  ccepcty     char(3) default ' ' not null,
  ccepana     char(3) default ' ' not null,
  ccepoty     char(3) default ' ' not null,
  ccepttr     char(3) default ' ' not null,
  ccepoy6     char(3) default ' ' not null,
  ccepoy7     char(3) default ' ' not null,
  ccepoy8     char(3) default ' ' not null,
  ccepoy9     char(3) default ' ' not null,
  cceporm     char(6) default ' ' not null,
  ccepoki     char(3) default ' ' not null,
  ccepotp     char(3) default ' ' not null,
  cceptst     char(3) default ' ' not null,
  ccepins     char(3) default ' ' not null,
  cceptim     char(5) default ' ' not null,
  cceptdp     char(5) default ' ' not null,
  ccepast     char(3) default ' ' not null,
  ccepamd     char(3) default ' ' not null,
  ccepau1     char(3) default ' ' not null,
  ccepau2     char(3) default ' ' not null,
  ccepau3     char(3) default ' ' not null,
  ccepau4     char(3) default ' ' not null,
  ccepau5     char(3) default ' ' not null,
  ccepau6     char(3) default ' ' not null,
  ccepau7     char(3) default ' ' not null,
  ccepau8     char(3) default ' ' not null,
  ccepawt     char(3) default ' ' not null,
  ccepapr     char(3) default ' ' not null,
  ccepaet     char(3) default ' ' not null,
  ccepart     char(3) default ' ' not null,
  ccepain     char(3) default ' ' not null,
  ccepapl     char(3) default ' ' not null,
  ccepapy     char(3) default ' ' not null,
  ccepost     char(6) default ' ' not null,
  ccepocl     char(6) default ' ' not null,
  ccepoct     char(6) default ' ' not null,
  ccepovt     char(3) default ' ' not null,
  ccepody     char(1) default ' ' not null,
  cceposs     char(3) default ' ' not null,
  ccepods     char(3) default ' ' not null,
  ccepoat     char(3) default ' ' not null,
  ccepopr     char(3) default ' ' not null,
  ccepou1     char(3) default ' ' not null,
  ccepou2     char(3) default ' ' not null,
  ccepou3     char(3) default ' ' not null,
  ccepou4     char(3) default ' ' not null,
  ccepodp     char(3) default ' ' not null,
  ccepotr     char(3) default ' ' not null,
  ccepolg     char(3) default ' ' not null,
  ccepoot     char(3) default ' ' not null,
  ccepmu8     char(3) default ' ' not null,
  ccepmu9     char(3) default ' ' not null,
  ccepmu10    char(3) default ' ' not null,
  ccepphp     char(3) default ' ' not null,
  ccepagn     char(3) default ' ' not null,
  ccepvw5     decimal(12,4) default 0 not null,
  ccepv5a     decimal(12,4) default 0 not null,
  ccepcmx     char(1) default ' ' not null,
  ccepv8a     decimal(12,4) default 0 not null,
  ccepintr    char(1) default ' ' not null,
  ccepstat    char(1) default ' ' not null,
  ccepcind    char(3) default ' ' not null,
  ccepspca    char(3) default ' ' not null,
  cceprsta    char(1) default ' ' not null,
  cceprhcp    char(10) default ' ' not null,
  ccepprb1    char(9) default ' ' not null,
  ccepprb2    char(9) default ' ' not null,
  ccepprb3    char(9) default ' ' not null,
  ccepdia1    char(9) default ' ' not null,
  ccepdia2    char(9) default ' ' not null,
  ccepdia3    char(9) default ' ' not null,
  ccepencn    char(3) default ' ' not null,
  ccepserp    char(10) default ' ' not null,
  ccepacty    char(6) default ' ' not null,
  ccepserd    char(8) default ' ' not null,
  ccepptyp    char(3) default ' ' not null,
  ccepdept    char(3) default ' ' not null,
  ccepdunt    decimal(6,0) default 0 not null,
  ccepdbun    decimal(6,0) default 0 not null,
  ccepiunt    decimal(6,0) default 0 not null,
  ccepibun    decimal(6,0) default 0 not null,
  ccepabrg    char(3) default ' ' not null,
  ccepcadm    char(3) default ' ' not null,
  ccepirad    char(3) default ' ' not null,
  ccepidus    char(3) default ' ' not null,
  ccepcrav    char(3) default ' ' not null,
  cceprcct    char(3) default ' ' not null,
  ccepindc    char(1) default ' ' not null,
  ccepmdav    char(3) default ' ' not null,
  ccepcsng    char(3) default ' ' not null,
  ccepasut    char(3) default ' ' not null,
  ccepelps    char(3) default ' ' not null,
  ccepempl    char(3) default ' ' not null,
  ccepfinp    char(3) default ' ' not null,
  ccepoccp    char(3) default ' ' not null,
  cceppalc    char(3) default ' ' not null,
  ccepppal    char(3) default ' ' not null,
  cceppppt    char(3) default ' ' not null,
  cceppsos    char(3) default ' ' not null,
  cceppysp    char(3) default ' ' not null,
  ccepqldb    char(3) default ' ' not null,
  ccepread    char(3) default ' ' not null,
  ccepudin    char(3) default ' ' not null,
  ccepurea    char(3) default ' ' not null,
  ccepusac    char(3) default ' ' not null,
  ccepuvth    char(3) default ' ' not null,
  ccepdvac    char(3) default ' ' not null,
  ccepfldr    char(3) default ' ' not null,
  cceppccl    char(1) default ' ' not null,
  ccepsdrg    char(4) default ' ' not null,
  ccepuint    decimal(4,0) default 0 not null,
  ccepuccu    decimal(4,0) default 0 not null,
  ccepumec    decimal(4,0) default 0 not null,
  ccepcpap    decimal(5,0) default 0 not null,
  cceprclo    char(3) default ' ' not null,
  ccepsrce    char(3) default ' ' not null,
  ccepstyp    char(6) default ' ' not null,
  ccepasit    char(6) default ' ' not null,
  ccepuc21    char(3) default ' ' not null,
  ccepuc09    char(3) default ' ' not null,
  ccepuc20    char(3) default ' ' not null,
  ccepuc28    char(3) default ' ' not null,
  cceprhc1    char(10) default ' ' not null,
  ccepadts    char(5) default ' ' not null,
  ccepdcts    char(5) default ' ' not null,
  ccepspa     char(50) default ' ' not null,
  lf          char(1)
);
create unique index ccsepsa1 on ccsepsaf
(
ccephcd,
ccepeps
);
create unique index ccsepsa2 on ccsepsaf
(
ccepcom,
ccephcd,
ccepeps
);
create unique index ccsepsa3 on ccsepsaf
(
ccepltd,
ccephcd,
ccepeps
);
create unique index ccsepsa4 on ccsepsaf
(
ccepddat,
ccephcd,
ccepeps
);
create unique index ccsepsa5 on ccsepsaf
(
ccepurn,
ccephcd,
ccepeps
);
revoke all on ccsepsaf from public ; 
grant select on ccsepsaf to public ; 
