create table ccseyaaf
(
  cceyeid     char(4) default ' ' not null,
  cceyba1     decimal(1,0) default 0 not null,
  cceyba2     decimal(1,0) default 0 not null,
  cceyba3     decimal(1,0) default 0 not null,
  cceybao     decimal(1,0) default 0 not null,
  cceyith     decimal(1,0) default 0 not null,
  cceyia1     decimal(1,0) default 0 not null,
  cceyia2     decimal(1,0) default 0 not null,
  cceyia3     decimal(1,0) default 0 not null,
  cceyiao     decimal(1,0) default 0 not null,
  cceyim1     decimal(1,0) default 0 not null,
  cceyim2     decimal(1,0) default 0 not null,
  cceyim3     decimal(1,0) default 0 not null,
  cceyimo     decimal(1,0) default 0 not null,
  cceyeth1    decimal(1,0) default 0 not null,
  cceyea11    decimal(1,0) default 0 not null,
  cceyea21    decimal(1,0) default 0 not null,
  cceyea31    decimal(1,0) default 0 not null,
  cceyeao1    decimal(1,0) default 0 not null,
  cceyem11    decimal(1,0) default 0 not null,
  cceyem21    decimal(1,0) default 0 not null,
  cceyem31    decimal(1,0) default 0 not null,
  cceyemo1    decimal(1,0) default 0 not null,
  cceyeth2    decimal(1,0) default 0 not null,
  cceyea12    decimal(1,0) default 0 not null,
  cceyea22    decimal(1,0) default 0 not null,
  cceyea32    decimal(1,0) default 0 not null,
  cceyeao2    decimal(1,0) default 0 not null,
  cceyem12    decimal(1,0) default 0 not null,
  cceyem22    decimal(1,0) default 0 not null,
  cceyem32    decimal(1,0) default 0 not null,
  cceyemo2    decimal(1,0) default 0 not null,
  cceyeth3    decimal(1,0) default 0 not null,
  cceyea13    decimal(1,0) default 0 not null,
  cceyea23    decimal(1,0) default 0 not null,
  cceyea33    decimal(1,0) default 0 not null,
  cceyeao3    decimal(1,0) default 0 not null,
  cceyem13    decimal(1,0) default 0 not null,
  cceyem23    decimal(1,0) default 0 not null,
  cceyem33    decimal(1,0) default 0 not null,
  cceyemo3    decimal(1,0) default 0 not null,
  cceyeth4    decimal(1,0) default 0 not null,
  cceyea14    decimal(1,0) default 0 not null,
  cceyea24    decimal(1,0) default 0 not null,
  cceyea34    decimal(1,0) default 0 not null,
  cceyeao4    decimal(1,0) default 0 not null,
  cceyem14    decimal(1,0) default 0 not null,
  cceyem24    decimal(1,0) default 0 not null,
  cceyem34    decimal(1,0) default 0 not null,
  cceyemo4    decimal(1,0) default 0 not null,
  cceyeth5    decimal(1,0) default 0 not null,
  cceyea15    decimal(1,0) default 0 not null,
  cceyea25    decimal(1,0) default 0 not null,
  cceyea35    decimal(1,0) default 0 not null,
  cceyeao5    decimal(1,0) default 0 not null,
  cceyem15    decimal(1,0) default 0 not null,
  cceyem25    decimal(1,0) default 0 not null,
  cceyem35    decimal(1,0) default 0 not null,
  cceyemo5    decimal(1,0) default 0 not null,
  cceyspa     char(40) default ' ' not null,
  lf          char(1)
);
create unique index ccseyaa1 on ccseyaaf
(
cceyeid
);
revoke all on ccseyaaf from public ; 
grant select on ccseyaaf to public ; 
