create table ccsaudia
(
  cciaaudd    char(8) default ' ' not null,
  cciaaudt    char(8) default ' ' not null,
  cciaaudp    char(2) default ' ' not null,
  cciaaudr    char(1) default ' ' not null,
  cciaauds    decimal(1,0) default 0 not null,
  cciaaudo    char(4) default ' ' not null,
  cciahcd     char(2) default ' ' not null,
  cciaeps     char(16) default ' ' not null,
  cciaba1     decimal(8,2) default 0 not null,
  cciaba2     decimal(8,2) default 0 not null,
  cciaba3     decimal(8,2) default 0 not null,
  ccialos     decimal(8,2) default 0 not null,
  cciaith     decimal(10,2) default 0 not null,
  cciaia1     decimal(10,2) default 0 not null,
  cciaia2     decimal(10,2) default 0 not null,
  cciaia3     decimal(10,2) default 0 not null,
  cciaiao     decimal(10,2) default 0 not null,
  cciaim1     decimal(10,2) default 0 not null,
  cciaim2     decimal(10,2) default 0 not null,
  cciaim3     decimal(10,2) default 0 not null,
  cciaimo     decimal(10,2) default 0 not null,
  cciaeth1    decimal(10,2) default 0 not null,
  cciaeth2    decimal(10,2) default 0 not null,
  cciaeth3    decimal(10,2) default 0 not null,
  cciaeth4    decimal(10,2) default 0 not null,
  cciaeth5    decimal(10,2) default 0 not null,
  cciaea11    decimal(10,2) default 0 not null,
  cciaea12    decimal(10,2) default 0 not null,
  cciaea13    decimal(10,2) default 0 not null,
  cciaea14    decimal(10,2) default 0 not null,
  cciaea15    decimal(10,2) default 0 not null,
  cciaea21    decimal(10,2) default 0 not null,
  cciaea22    decimal(10,2) default 0 not null,
  cciaea23    decimal(10,2) default 0 not null,
  cciaea24    decimal(10,2) default 0 not null,
  cciaea25    decimal(10,2) default 0 not null,
  cciaea31    decimal(10,2) default 0 not null,
  cciaea32    decimal(10,2) default 0 not null,
  cciaea33    decimal(10,2) default 0 not null,
  cciaea34    decimal(10,2) default 0 not null,
  cciaea35    decimal(10,2) default 0 not null,
  cciaeao1    decimal(10,2) default 0 not null,
  cciaeao2    decimal(10,2) default 0 not null,
  cciaeao3    decimal(10,2) default 0 not null,
  cciaeao4    decimal(10,2) default 0 not null,
  cciaeao5    decimal(10,2) default 0 not null,
  cciaem11    decimal(10,2) default 0 not null,
  cciaem12    decimal(10,2) default 0 not null,
  cciaem13    decimal(10,2) default 0 not null,
  cciaem14    decimal(10,2) default 0 not null,
  cciaem15    decimal(10,2) default 0 not null,
  cciaem21    decimal(10,2) default 0 not null,
  cciaem22    decimal(10,2) default 0 not null,
  cciaem23    decimal(10,2) default 0 not null,
  cciaem24    decimal(10,2) default 0 not null,
  cciaem25    decimal(10,2) default 0 not null,
  cciaem31    decimal(10,2) default 0 not null,
  cciaem32    decimal(10,2) default 0 not null,
  cciaem33    decimal(10,2) default 0 not null,
  cciaem34    decimal(10,2) default 0 not null,
  cciaem35    decimal(10,2) default 0 not null,
  cciaemo1    decimal(10,2) default 0 not null,
  cciaemo2    decimal(10,2) default 0 not null,
  cciaemo3    decimal(10,2) default 0 not null,
  cciaemo4    decimal(10,2) default 0 not null,
  cciaemo5    decimal(10,2) default 0 not null,
  cciatt1     decimal(6,2) default 0 not null,
  cciatt2     decimal(6,2) default 0 not null,
  cciatt3     decimal(6,2) default 0 not null,
  cciatt4     decimal(6,2) default 0 not null,
  cciaspa     char(14) default ' ' not null,
  lf          char(1)
);
create index ccsaudia on ccsaudia
(
cciaaudd,
cciaaudt,
cciaaudp,
cciaaudr
);
revoke all on ccsaudia from public ; 
grant select on ccsaudia to public ; 
create table ccsiadaf
(
  cciahcd     char(2) default ' ' not null,
  cciaeps     char(16) default ' ' not null,
  cciaba1     decimal(8,2) default 0 not null,
  cciaba2     decimal(8,2) default 0 not null,
  cciaba3     decimal(8,2) default 0 not null,
  ccialos     decimal(8,2) default 0 not null,
  cciaith     decimal(10,2) default 0 not null,
  cciaia1     decimal(10,2) default 0 not null,
  cciaia2     decimal(10,2) default 0 not null,
  cciaia3     decimal(10,2) default 0 not null,
  cciaiao     decimal(10,2) default 0 not null,
  cciaim1     decimal(10,2) default 0 not null,
  cciaim2     decimal(10,2) default 0 not null,
  cciaim3     decimal(10,2) default 0 not null,
  cciaimo     decimal(10,2) default 0 not null,
  cciaeth1    decimal(10,2) default 0 not null,
  cciaeth2    decimal(10,2) default 0 not null,
  cciaeth3    decimal(10,2) default 0 not null,
  cciaeth4    decimal(10,2) default 0 not null,
  cciaeth5    decimal(10,2) default 0 not null,
  cciaea11    decimal(10,2) default 0 not null,
  cciaea12    decimal(10,2) default 0 not null,
  cciaea13    decimal(10,2) default 0 not null,
  cciaea14    decimal(10,2) default 0 not null,
  cciaea15    decimal(10,2) default 0 not null,
  cciaea21    decimal(10,2) default 0 not null,
  cciaea22    decimal(10,2) default 0 not null,
  cciaea23    decimal(10,2) default 0 not null,
  cciaea24    decimal(10,2) default 0 not null,
  cciaea25    decimal(10,2) default 0 not null,
  cciaea31    decimal(10,2) default 0 not null,
  cciaea32    decimal(10,2) default 0 not null,
  cciaea33    decimal(10,2) default 0 not null,
  cciaea34    decimal(10,2) default 0 not null,
  cciaea35    decimal(10,2) default 0 not null,
  cciaeao1    decimal(10,2) default 0 not null,
  cciaeao2    decimal(10,2) default 0 not null,
  cciaeao3    decimal(10,2) default 0 not null,
  cciaeao4    decimal(10,2) default 0 not null,
  cciaeao5    decimal(10,2) default 0 not null,
  cciaem11    decimal(10,2) default 0 not null,
  cciaem12    decimal(10,2) default 0 not null,
  cciaem13    decimal(10,2) default 0 not null,
  cciaem14    decimal(10,2) default 0 not null,
  cciaem15    decimal(10,2) default 0 not null,
  cciaem21    decimal(10,2) default 0 not null,
  cciaem22    decimal(10,2) default 0 not null,
  cciaem23    decimal(10,2) default 0 not null,
  cciaem24    decimal(10,2) default 0 not null,
  cciaem25    decimal(10,2) default 0 not null,
  cciaem31    decimal(10,2) default 0 not null,
  cciaem32    decimal(10,2) default 0 not null,
  cciaem33    decimal(10,2) default 0 not null,
  cciaem34    decimal(10,2) default 0 not null,
  cciaem35    decimal(10,2) default 0 not null,
  cciaemo1    decimal(10,2) default 0 not null,
  cciaemo2    decimal(10,2) default 0 not null,
  cciaemo3    decimal(10,2) default 0 not null,
  cciaemo4    decimal(10,2) default 0 not null,
  cciaemo5    decimal(10,2) default 0 not null,
  cciatt1     decimal(6,2) default 0 not null,
  cciatt2     decimal(6,2) default 0 not null,
  cciatt3     decimal(6,2) default 0 not null,
  cciatt4     decimal(6,2) default 0 not null,
  cciaspa     char(14) default ' ' not null,
  lf          char(1)
);
create unique index ccsiada1 on ccsiadaf
(
cciahcd,
cciaeps
);
revoke all on ccsiadaf from public ; 
grant select on ccsiadaf to public ; 
