create table depcphaf
(
  dppcdate    char(8) default ' ' not null,
  dppcward    char(3) default ' ' not null,
  dppctime    char(5) default ' ' not null,
  dppcshft    char(3) default ' ' not null,
  ddppcadm    char(8) default ' ' not null,
  dppccatg    char(3) default ' ' not null,
  dppcat01    char(3) default ' ' not null,
  dppcat02    char(3) default ' ' not null,
  dppcat03    char(3) default ' ' not null,
  dppcat04    char(3) default ' ' not null,
  dppcat05    char(3) default ' ' not null,
  dppcat06    char(3) default ' ' not null,
  dppcat07    char(3) default ' ' not null,
  dppcat08    char(3) default ' ' not null,
  dppcat09    char(3) default ' ' not null,
  dppcat10    char(3) default ' ' not null,
  dppcat11    char(3) default ' ' not null,
  dppcat12    char(3) default ' ' not null,
  dppcat13    char(3) default ' ' not null,
  dppcat14    char(3) default ' ' not null,
  dppcat15    char(3) default ' ' not null,
  dppcat16    char(3) default ' ' not null,
  dppcat17    char(3) default ' ' not null,
  dppcat18    char(3) default ' ' not null,
  dppcat19    char(3) default ' ' not null,
  dppcat20    char(3) default ' ' not null,
  dppcat21    char(3) default ' ' not null,
  dppcat22    char(3) default ' ' not null,
  dppcat23    char(3) default ' ' not null,
  dppcat24    char(3) default ' ' not null,
  dppcat25    char(3) default ' ' not null,
  dppcat26    char(3) default ' ' not null,
  dppcat27    char(3) default ' ' not null,
  dppcat28    char(3) default ' ' not null,
  dppcat29    char(3) default ' ' not null,
  dppcat30    char(3) default ' ' not null,
  dppcat31    char(3) default ' ' not null,
  dppcat32    char(3) default ' ' not null,
  dppcat33    char(3) default ' ' not null,
  dppcat34    char(3) default ' ' not null,
  dppcat35    char(3) default ' ' not null,
  dppcat36    char(3) default ' ' not null,
  dppcat37    char(3) default ' ' not null,
  dppcat38    char(3) default ' ' not null,
  dppcat39    char(3) default ' ' not null,
  dppcat40    char(3) default ' ' not null,
  dppcat41    char(3) default ' ' not null,
  dppcat42    char(3) default ' ' not null,
  dppcat43    char(3) default ' ' not null,
  dppcat44    char(3) default ' ' not null,
  dppcat45    char(3) default ' ' not null,
  dppcat46    char(3) default ' ' not null,
  dppcat47    char(3) default ' ' not null,
  dppcat48    char(3) default ' ' not null,
  dppcat49    char(3) default ' ' not null,
  dppcat50    char(3) default ' ' not null,
  dppcat51    char(3) default ' ' not null,
  dppcat52    char(3) default ' ' not null,
  dppcat53    char(3) default ' ' not null,
  dppcat54    char(3) default ' ' not null,
  dppcat55    char(3) default ' ' not null,
  dppcat56    char(3) default ' ' not null,
  dppcat57    char(3) default ' ' not null,
  dppcat58    char(3) default ' ' not null,
  dppcat59    char(3) default ' ' not null,
  dppcat60    char(3) default ' ' not null,
  ddppctot    char(4) default ' ' not null,
  dppcspre    char(16) default ' ' not null,
  lf          char(1)
);
create unique index depcpha1 on depcphaf
(
dppcdate,
dppcward,
dppctime,
dppcshft,
ddppcadm
);
create unique index depcpha2 on depcphaf
(
ddppcadm,
dppcdate,
dppctime,
dppcshft,
dppcward
);
revoke all on depcphaf from public ; 
grant select on depcphaf to public ; 
