create table emrcliaf
(
  emcivisn    char(8) default ' ' not null,
  emcior01    char(1) default ' ' not null,
  emcior02    char(1) default ' ' not null,
  emcior03    char(1) default ' ' not null,
  emcior04    char(1) default ' ' not null,
  emcior05    char(1) default ' ' not null,
  emcior06    char(1) default ' ' not null,
  emcior07    char(1) default ' ' not null,
  emcior08    char(1) default ' ' not null,
  emcior09    char(1) default ' ' not null,
  emcior10    char(1) default ' ' not null,
  emcipr01    char(1) default ' ' not null,
  emcipr02    char(1) default ' ' not null,
  emcipr03    char(1) default ' ' not null,
  emcipr04    char(1) default ' ' not null,
  emcipr05    char(1) default ' ' not null,
  emcipr06    char(1) default ' ' not null,
  emcipr07    char(1) default ' ' not null,
  emcipr08    char(1) default ' ' not null,
  emcipr09    char(1) default ' ' not null,
  emcipr10    char(1) default ' ' not null,
  emcirs01    char(1) default ' ' not null,
  emcirs02    char(1) default ' ' not null,
  emcirs03    char(1) default ' ' not null,
  emcirs04    char(1) default ' ' not null,
  emcirs05    char(1) default ' ' not null,
  emcirs06    char(1) default ' ' not null,
  emcirs07    char(1) default ' ' not null,
  emcirs08    char(1) default ' ' not null,
  emcirs09    char(1) default ' ' not null,
  emcirs10    char(1) default ' ' not null,
  emcipcom    char(3) default ' ' not null,
  emcilmds    char(50) default ' ' not null,
  emcilmcd    char(10) default ' ' not null,
  emcilmcf    char(3) default ' ' not null,
  emcirccd    char(10) default ' ' not null,
  emcircff    char(50) default ' ' not null,
  emcirctm    char(5) default ' ' not null,
  emciscff    char(50) default ' ' not null,
  emciscvc    char(3) default ' ' not null,
  emcitsct    char(5) default ' ' not null,
  emciprdt    char(8) default ' ' not null,
  emcirrff    char(50) default ' ' not null,
  emciuwcr    char(10) default ' ' not null,
  emcircdt    char(8) default ' ' not null,
  emcitrcd    char(8) default ' ' not null,
  emciuupd    char(10) default ' ' not null,
  emcirudt    char(8) default ' ' not null,
  emcitrup    char(8) default ' ' not null,
  emcispar    char(100) default ' ' not null,
  lf          char(1)
);
create unique index emrclia1 on emrcliaf
(
emcivisn
);
revoke all on emrcliaf from public ; 
grant select on emrcliaf to public ; 
