create table emrvisaf
(
  demviadm    char(8) default ' ' not null,
  demvista    char(1) default ' ' not null,
  emviurno    char(8) default ' ' not null,
  emvidate    char(8) default ' ' not null,
  emvitime    char(8) default ' ' not null,
  emvitrig    char(3) default ' ' not null,
  emvicom1    char(50) default ' ' not null,
  emvicom2    char(50) default ' ' not null,
  emvilocn    char(3) default ' ' not null,
  emvidoct    char(10) default ' ' not null,
  emvicomp    char(3) default ' ' not null,
  emviclas    char(3) default ' ' not null,
  emviinsr    char(3) default ' ' not null,
  emvisrce    char(3) default ' ' not null,
  emvisitn    char(3) default ' ' not null,
  emvimode    char(3) default ' ' not null,
  emviadmt    decimal(1,0) default 0 not null,
  emvidurn    decimal(4,0) default 0 not null,
  emviempl    char(20) default ' ' not null,
  emviwait    char(3) default ' ' not null,
  emviprev    char(3) default ' ' not null,
  emvifund    char(6) default ' ' not null,
  emvitabl    char(8) default ' ' not null,
  emvirefg    char(10) default ' ' not null,
  emvirefd    char(10) default ' ' not null,
  emviplin    char(3) default ' ' not null,
  emviinit    char(3) default ' ' not null,
  emvirtas    char(3) default ' ' not null,
  emviddat    char(8) default ' ' not null,
  emvidtim    char(8) default ' ' not null,
  emvidsta    char(3) default ' ' not null,
  emviopr1    char(10) default ' ' not null,
  emviopr2    char(10) default ' ' not null,
  emviuc01    char(3) default ' ' not null,
  emviuc02    char(3) default ' ' not null,
  emviuc03    char(3) default ' ' not null,
  emviuc04    char(3) default ' ' not null,
  emviuc05    char(3) default ' ' not null,
  emviuc06    char(3) default ' ' not null,
  emviuc07    char(3) default ' ' not null,
  emviuc08    char(3) default ' ' not null,
  emviuc09    char(3) default ' ' not null,
  emviuc10    char(3) default ' ' not null,
  emviuc11    char(3) default ' ' not null,
  emviuc12    char(3) default ' ' not null,
  emviuc13    char(3) default ' ' not null,
  emviuc14    char(3) default ' ' not null,
  emviuc15    char(3) default ' ' not null,
  emviuc16    char(3) default ' ' not null,
  emviuc17    char(3) default ' ' not null,
  emviuc18    char(3) default ' ' not null,
  emviuc19    char(3) default ' ' not null,
  emviuc20    char(3) default ' ' not null,
  emviuc21    char(3) default ' ' not null,
  emviuc22    char(3) default ' ' not null,
  emviuc23    char(3) default ' ' not null,
  emviuc24    char(3) default ' ' not null,
  emviuc25    char(3) default ' ' not null,
  emviuc26    char(3) default ' ' not null,
  emviuc27    char(3) default ' ' not null,
  emviuc28    char(3) default ' ' not null,
  emviuc29    char(3) default ' ' not null,
  emviuc30    char(3) default ' ' not null,
  emviud01    char(8) default ' ' not null,
  emviud02    char(8) default ' ' not null,
  emviud03    char(8) default ' ' not null,
  emviud04    char(8) default ' ' not null,
  emviud05    char(8) default ' ' not null,
  emviud06    char(8) default ' ' not null,
  emviud07    char(8) default ' ' not null,
  emviud08    char(8) default ' ' not null,
  emviud09    char(8) default ' ' not null,
  emviud10    char(8) default ' ' not null,
  emviut01    char(8) default ' ' not null,
  emviut02    char(8) default ' ' not null,
  emviut03    char(8) default ' ' not null,
  emviut04    char(8) default ' ' not null,
  emviut05    char(8) default ' ' not null,
  emviut06    char(8) default ' ' not null,
  emviut07    char(8) default ' ' not null,
  emviut08    char(8) default ' ' not null,
  emviut09    char(8) default ' ' not null,
  emviut10    char(8) default ' ' not null,
  emviyn01    decimal(1,0) default 0 not null,
  emviyn02    decimal(1,0) default 0 not null,
  emviyn03    decimal(1,0) default 0 not null,
  emviyn04    decimal(1,0) default 0 not null,
  emviyn05    decimal(1,0) default 0 not null,
  emviyn06    decimal(1,0) default 0 not null,
  emviyn07    decimal(1,0) default 0 not null,
  emviyn08    decimal(1,0) default 0 not null,
  emviyn09    decimal(1,0) default 0 not null,
  emviyn10    decimal(1,0) default 0 not null,
  emvitxt1    char(50) default ' ' not null,
  emvitxt2    char(50) default ' ' not null,
  emvitxt3    char(50) default ' ' not null,
  emvitxt4    char(50) default ' ' not null,
  emvitxt5    char(50) default ' ' not null,
  emviun01    decimal(6,0) default 0 not null,
  emviun02    decimal(6,0) default 0 not null,
  emviun03    decimal(6,0) default 0 not null,
  emviun04    decimal(6,0) default 0 not null,
  emviun05    decimal(6,0) default 0 not null,
  emvielap    char(3) default ' ' not null,
  emvinsdt    char(8) default ' ' not null,
  emvinstm    char(8) default ' ' not null,
  emvidrdt    char(8) default ' ' not null,
  emvidrtm    char(8) default ' ' not null,
  emvipatt    decimal(3,0) default 0 not null,
  emvitsrc    char(5) default ' ' not null,
  emvidest    char(5) default ' ' not null,
  emviambl    char(15) default ' ' not null,
  emviregn    char(2) default ' ' not null,
  emvisent    char(1) default ' ' not null,
  emviur01    char(6) default ' ' not null,
  emviur02    char(6) default ' ' not null,
  emviur03    char(6) default ' ' not null,
  emviur04    char(6) default ' ' not null,
  emviur05    char(6) default ' ' not null,
  emvipadm    char(8) default ' ' not null,
  emviewrd    char(3) default ' ' not null,
  emviebed    char(3) default ' ' not null,
  emvihfmn    char(19) default ' ' not null,
  emviacls    char(3) default ' ' not null,
  emviccls    char(3) default ' ' not null,
  emvitrns    char(10) default ' ' not null,
  emvidum1    char(3) default ' ' not null,
  emvitrdt    char(8) default ' ' not null,
  emvitrtm    char(8) default ' ' not null,
  emviatns    char(10) default ' ' not null,
  emvidum2    char(3) default ' ' not null,
  emviexlc    char(3) default ' ' not null,
  emvisite    char(3) default ' ' not null,
  emviunit    char(3) default ' ' not null,
  emvicom3    char(50) default ' ' not null,
  emvicom4    char(50) default ' ' not null,
  emvicom5    char(50) default ' ' not null,
  emvicom6    char(50) default ' ' not null,
  emviinj1    char(50) default ' ' not null,
  emviinj2    char(50) default ' ' not null,
  emvinati    char(3) default ' ' not null,
  emviinjc    char(3) default ' ' not null,
  emvihumi    char(3) default ' ' not null,
  emviacti    char(3) default ' ' not null,
  emviloco    char(25) default ' ' not null,
  emviprlo    char(3) default ' ' not null,
  emviprtm    char(8) default ' ' not null,
  emvidpdt    char(8) default ' ' not null,
  emvidptm    char(8) default ' ' not null,
  emviexrs    char(3) default ' ' not null,
  emvidlrs    char(3) default ' ' not null,
  emvispdt    char(8) default ' ' not null,
  emvisptm    char(8) default ' ' not null,
  emvisadt    char(8) default ' ' not null,
  emvisatm    char(8) default ' ' not null,
  emvimpra    char(10) default ' ' not null,
  emvimpdt    char(8) default ' ' not null,
  emvimptm    char(8) default ' ' not null,
  emviaadt    char(8) default ' ' not null,
  emviaatm    char(8) default ' ' not null,
  emviahdt    char(8) default ' ' not null,
  emviahtm    char(8) default ' ' not null,
  emvidadt    char(8) default ' ' not null,
  emvidatm    char(8) default ' ' not null,
  emvipurc    char(3) default ' ' not null,
  emvimncd    char(10) default ' ' not null,
  emvimndt    char(8) default ' ' not null,
  emvimntm    char(8) default ' ' not null,
  emvimdcd    char(10) default ' ' not null,
  emvimddt    char(8) default ' ' not null,
  emvimdtm    char(8) default ' ' not null,
  emviuc31    char(3) default ' ' not null,
  emviuc32    char(3) default ' ' not null,
  emviuc33    char(3) default ' ' not null,
  emviuc34    char(3) default ' ' not null,
  emviuc35    char(3) default ' ' not null,
  emvirefp    char(3) default ' ' not null,
  emvirepm    char(2) default ' ' not null,
  emviredt    char(8) default ' ' not null,
  emvibnaa    char(1) default ' ' not null,
  emvivsty    char(3) default ' ' not null,
  emvivplc    char(3) default ' ' not null,
  emviahcp    char(10) default ' ' not null,
  emviahst    char(1) default ' ' not null,
  emvidisd    char(3) default ' ' not null,
  emvidrug    char(1) default ' ' not null,
  emvispar    char(41) default ' ' not null,
  lf          char(1)
);
create unique index emrvisa1 on emrvisaf
(
demviadm
);
create unique index emrvisa2 on emrvisaf
(
demvista,
demviadm
);
create unique index emrvisa3 on emrvisaf
(
emviurno,
demviadm
);
create unique index emrvisa4 on emrvisaf
(
emvidate,
emvitime,
demviadm
);
create unique index emrvisa5 on emrvisaf
(
emvisite,
demvista,
demviadm
);
create unique index emrvisa6 on emrvisaf
(
emvisite,
emvidate,
emvitime,
demviadm
);
create unique index emrvisa7 on emrvisaf
(
emvilocn,
demviadm
);
revoke all on emrvisaf from public ; 
grant select on emrvisaf to public ; 
