create table eocaccaf
(
  ecacaccn    char(20) default ' ' not null,
  ecacacca    decimal(1,0) default 0 not null,
  ecacdat1    char(8) default ' ' not null,
  ecactim1    char(5) default ' ' not null,
  ecacdat2    char(8) default ' ' not null,
  ecactim2    char(5) default ' ' not null,
  ecacdat3    char(8) default ' ' not null,
  ecactim3    char(5) default ' ' not null,
  ecacdat4    char(8) default ' ' not null,
  ecactim4    char(5) default ' ' not null,
  ecacdat5    char(8) default ' ' not null,
  ecactim5    char(5) default ' ' not null,
  ecacdat6    char(8) default ' ' not null,
  ecactim6    char(5) default ' ' not null,
  ecacdoc1    char(6) default ' ' not null,
  ecacdoc2    char(6) default ' ' not null,
  ecacdoc3    char(6) default ' ' not null,
  ecacdoc4    char(6) default ' ' not null,
  ecacdoc5    char(6) default ' ' not null,
  ecacdoc6    char(6) default ' ' not null,
  ecacdia1    char(9) default ' ' not null,
  ecacdia2    char(9) default ' ' not null,
  ecacdia3    char(9) default ' ' not null,
  ecacdia4    char(60) default ' ' not null,
  ecacdia5    char(60) default ' ' not null,
  ecacdia6    char(60) default ' ' not null,
  ecacyno1    decimal(1,0) default 0 not null,
  ecacyno2    decimal(1,0) default 0 not null,
  ecacyno3    decimal(1,0) default 0 not null,
  ecacyno4    decimal(1,0) default 0 not null,
  ecacyno5    decimal(1,0) default 0 not null,
  ecacyno6    decimal(1,0) default 0 not null,
  ecacfre1    char(60) default ' ' not null,
  ecacfre2    char(60) default ' ' not null,
  ecacfre3    char(60) default ' ' not null,
  ecacfre4    char(60) default ' ' not null,
  ecacfre5    char(60) default ' ' not null,
  ecacfre6    char(60) default ' ' not null,
  ecacfre7    char(60) default ' ' not null,
  ecacfre8    char(60) default ' ' not null,
  ecacfre9    char(60) default ' ' not null,
  ecacfr10    char(60) default ' ' not null,
  ecaccod1    char(3) default ' ' not null,
  ecaccod2    char(3) default ' ' not null,
  ecaccod3    char(3) default ' ' not null,
  ecaccod4    char(3) default ' ' not null,
  ecaccod5    char(3) default ' ' not null,
  ecaccod6    char(3) default ' ' not null,
  ecaccod7    char(3) default ' ' not null,
  ecaccod8    char(3) default ' ' not null,
  ecaccod9    char(3) default ' ' not null,
  ecacnum1    decimal(8,0) default 0 not null,
  ecacnum2    decimal(8,0) default 0 not null,
  ecacdacc    char(8) default ' ' not null,
  ecacspar    char(30) default ' ' not null,
  lf          char(1)
);
create unique index eocacca1 on eocaccaf
(
ecacaccn
);
revoke all on eocaccaf from public ; 
grant select on eocaccaf to public ; 
