create table fmslmcaf
(
  fmlcledg    char(2) default ' ' not null,
  fmlcyear    char(4) default ' ' not null,
  fmlc01fr    char(8) default ' ' not null,
  fmlc01to    char(8) default ' ' not null,
  fmlc01de    char(15) default ' ' not null,
  fmlc01in    decimal(1,0) default 0 not null,
  fmlc02fr    char(8) default ' ' not null,
  fmlc02to    char(8) default ' ' not null,
  fmlc02de    char(15) default ' ' not null,
  fmlc02in    decimal(1,0) default 0 not null,
  fmlc03fr    char(8) default ' ' not null,
  fmlc03to    char(8) default ' ' not null,
  fmlc03de    char(15) default ' ' not null,
  fmlc03in    decimal(1,0) default 0 not null,
  fmlc04fr    char(8) default ' ' not null,
  fmlc04to    char(8) default ' ' not null,
  fmlc04de    char(15) default ' ' not null,
  fmlc04in    decimal(1,0) default 0 not null,
  fmlc05fr    char(8) default ' ' not null,
  fmlc05to    char(8) default ' ' not null,
  fmlc05de    char(15) default ' ' not null,
  fmlc05in    decimal(1,0) default 0 not null,
  fmlc06fr    char(8) default ' ' not null,
  fmlc06to    char(8) default ' ' not null,
  fmlc06de    char(15) default ' ' not null,
  fmlc06in    decimal(1,0) default 0 not null,
  fmlc07fr    char(8) default ' ' not null,
  fmlc07to    char(8) default ' ' not null,
  fmlc07de    char(15) default ' ' not null,
  fmlc07in    decimal(1,0) default 0 not null,
  fmlc08fr    char(8) default ' ' not null,
  fmlc08to    char(8) default ' ' not null,
  fmlc08de    char(15) default ' ' not null,
  fmlc08in    decimal(1,0) default 0 not null,
  fmlc09fr    char(8) default ' ' not null,
  fmlc09to    char(8) default ' ' not null,
  fmlc09de    char(15) default ' ' not null,
  fmlc09in    decimal(1,0) default 0 not null,
  fmlc10fr    char(8) default ' ' not null,
  fmlc10to    char(8) default ' ' not null,
  fmlc10de    char(15) default ' ' not null,
  fmlc10in    decimal(1,0) default 0 not null,
  fmlc11fr    char(8) default ' ' not null,
  fmlc11to    char(8) default ' ' not null,
  fmlc11de    char(15) default ' ' not null,
  fmlc11in    decimal(1,0) default 0 not null,
  fmlc12fr    char(8) default ' ' not null,
  fmlc12to    char(8) default ' ' not null,
  fmlc12de    char(15) default ' ' not null,
  fmlc12in    decimal(1,0) default 0 not null,
  fmlc13fr    char(8) default ' ' not null,
  fmlc13to    char(8) default ' ' not null,
  fmlc13de    char(15) default ' ' not null,
  fmlc13in    decimal(1,0) default 0 not null,
  fmlcylc     decimal(1,0) default 0 not null,
  fmlcbudg    char(4) default ' ' not null,
  fmlccbud    char(4) default ' ' not null,
  fmlcspar    char(10) default ' ' not null,
  lf          char(1)
);
create unique index fmslmca1 on fmslmcaf
(
fmlcledg,
fmlcyear
);
revoke all on fmslmcaf from public ; 
grant select on fmslmcaf to public ; 
