create table ibasceaf
(
  ibseurno    char(8) default ' ' not null,
  ibsevisn    char(8) default ' ' not null,
  ibsecntr    char(8) default ' ' not null,
  ibsefl01    char(1) default ' ' not null,
  ibsefl02    char(1) default ' ' not null,
  ibsefl03    char(1) default ' ' not null,
  ibsefl04    char(1) default ' ' not null,
  ibsefl05    char(1) default ' ' not null,
  ibsefl06    char(1) default ' ' not null,
  ibsefl07    char(1) default ' ' not null,
  ibsefl08    char(1) default ' ' not null,
  ibsefl09    char(1) default ' ' not null,
  ibsefl10    char(1) default ' ' not null,
  ibsefl11    char(1) default ' ' not null,
  ibsefl12    char(1) default ' ' not null,
  ibsefl13    char(1) default ' ' not null,
  ibsefl14    char(1) default ' ' not null,
  ibsefl15    char(1) default ' ' not null,
  ibsefl16    char(1) default ' ' not null,
  ibsefl17    char(1) default ' ' not null,
  ibsefl18    char(1) default ' ' not null,
  ibsefl19    char(1) default ' ' not null,
  ibsefl20    char(1) default ' ' not null,
  ibsecd01    char(1) default ' ' not null,
  ibsecd02    char(1) default ' ' not null,
  ibsecd03    char(1) default ' ' not null,
  ibsecd04    char(1) default ' ' not null,
  ibsecd05    char(1) default ' ' not null,
  ibsecd06    char(1) default ' ' not null,
  ibsecd07    char(1) default ' ' not null,
  ibsecd08    char(1) default ' ' not null,
  ibsecd09    char(1) default ' ' not null,
  ibsecd10    char(1) default ' ' not null,
  ibsecd11    char(1) default ' ' not null,
  ibsecd12    char(1) default ' ' not null,
  ibsecd13    char(1) default ' ' not null,
  ibsecd14    char(1) default ' ' not null,
  ibsecd15    char(1) default ' ' not null,
  ibsesd01    char(6) default ' ' not null,
  ibsesd02    char(6) default ' ' not null,
  ibsesd03    char(8) default ' ' not null,
  ibsesd04    char(8) default ' ' not null,
  ibsesd05    char(10) default ' ' not null,
  ibsesd06    char(10) default ' ' not null,
  ibsemd01    char(50) default ' ' not null,
  ibsemd02    char(50) default ' ' not null,
  ibsemd03    char(50) default ' ' not null,
  ibsemd04    char(50) default ' ' not null,
  ibsemd05    char(50) default ' ' not null,
  ibsemd06    char(50) default ' ' not null,
  ibsemd07    char(50) default ' ' not null,
  ibsemd08    char(50) default ' ' not null,
  ibsemd09    char(50) default ' ' not null,
  ibsemd10    char(50) default ' ' not null,
  ibsemd11    char(50) default ' ' not null,
  ibsemd12    char(50) default ' ' not null,
  ibsexl01    char(200) default ' ' not null,
  ibsexl02    char(200) default ' ' not null,
  ibsexl03    char(200) default ' ' not null,
  ibsexl04    char(200) default ' ' not null,
  ibsexl05    char(200) default ' ' not null,
  ibsecdat    char(8) default ' ' not null,
  ibsectim    char(8) default ' ' not null,
  ibsecuid    char(10) default ' ' not null,
  ibseudat    char(8) default ' ' not null,
  ibseutim    char(8) default ' ' not null,
  ibseuuid    char(10) default ' ' not null,
  ibsespar    char(40) default ' ' not null,
  lf          char(1)
);
create unique index ibascea1 on ibasceaf
(
ibseurno,
ibsevisn
);
revoke all on ibasceaf from public ; 
grant select on ibasceaf to public ; 
