create table mehdiaaf
(
  dmhdiadm    char(8) default ' ' not null,
  mhdidate    char(8) default ' ' not null,
  mhdiicd1    char(9) default ' ' not null,
  mhdides1    char(200) default ' ' not null,
  mhdisup1    decimal(1,0) default 0 not null,
  mhdidat1    char(8) default ' ' not null,
  mhdiicd2    char(9) default ' ' not null,
  mhdides2    char(200) default ' ' not null,
  mhdisup2    decimal(1,0) default 0 not null,
  mhdidat2    char(8) default ' ' not null,
  mhdix1ca    char(9) default ' ' not null,
  mhdix1cb    char(9) default ' ' not null,
  mhdix1cc    char(9) default ' ' not null,
  mhdix1da    char(70) default ' ' not null,
  mhdix1db    char(70) default ' ' not null,
  mhdix1dc    char(70) default ' ' not null,
  mhdix2ca    char(9) default ' ' not null,
  mhdix2cb    char(9) default ' ' not null,
  mhdix2cc    char(9) default ' ' not null,
  mhdix2da    char(70) default ' ' not null,
  mhdix2db    char(70) default ' ' not null,
  mhdix2dc    char(70) default ' ' not null,
  mhdix3ds    char(50) default ' ' not null,
  mhdix4cd    char(3) default ' ' not null,
  mhdix5cd    char(3) default ' ' not null,
  mhdixdat    char(8) default ' ' not null,
  mhdioper    char(4) default ' ' not null,
  mhdiaxiv    char(20) default ' ' not null,
  mhdimohr    char(1) default ' ' not null,
  mhdix3ca    char(9) default ' ' not null,
  mhdix3cb    char(9) default ' ' not null,
  mhdix3cc    char(9) default ' ' not null,
  mhdix3da    char(70) default ' ' not null,
  mhdix3db    char(70) default ' ' not null,
  mhdix3dc    char(70) default ' ' not null,
  mhdicdat    char(8) default ' ' not null,
  mhdictim    char(8) default ' ' not null,
  mhdicuid    char(10) default ' ' not null,
  mhdiudat    char(8) default ' ' not null,
  mhdiutim    char(8) default ' ' not null,
  mhdiuuid    char(10) default ' ' not null,
  mhdiicd3    char(9) default ' ' not null,
  mhdides3    char(200) default ' ' not null,
  mhdisup3    decimal(1,0) default 0 not null,
  mhdidat3    char(8) default ' ' not null,
  mhdiicd4    char(9) default ' ' not null,
  mhdides4    char(200) default ' ' not null,
  mhdisup4    decimal(1,0) default 0 not null,
  mhdidat4    char(8) default ' ' not null,
  mhdiicd5    char(9) default ' ' not null,
  mhdides5    char(200) default ' ' not null,
  mhdisup5    decimal(1,0) default 0 not null,
  mhdidat5    char(8) default ' ' not null,
  mhdiicd6    char(9) default ' ' not null,
  mhdides6    char(200) default ' ' not null,
  mhdisup6    decimal(1,0) default 0 not null,
  mhdidat6    char(8) default ' ' not null,
  mhdip1ca    char(1) default ' ' not null,
  mhdip1cb    char(1) default ' ' not null,
  mhdip1cc    char(1) default ' ' not null,
  mhdip2ca    char(1) default ' ' not null,
  mhdip2cb    char(1) default ' ' not null,
  mhdip2cc    char(1) default ' ' not null,
  mhdihcpc    char(10) default ' ' not null,
  mhdicast    char(10) default ' ' not null,
  mhdidty1    char(1) default ' ' not null,
  mhdidty2    char(1) default ' ' not null,
  mhdidty3    char(1) default ' ' not null,
  mhdidty4    char(1) default ' ' not null,
  mhdidty5    char(1) default ' ' not null,
  mhdidty6    char(1) default ' ' not null,
  mhdiurno    char(8) default ' ' not null,
  mhdispar    char(46) default ' ' not null,
  lf          char(1)
);
create unique index mehdiaa1 on mehdiaaf
(
dmhdiadm,
mhdidate
);
create unique index mehdiaa2 on mehdiaaf
(
mhdiurno,
dmhdiadm,
mhdidate
);
revoke all on mehdiaaf from public ; 
grant select on mehdiaaf to public ; 
