create table mehhonaf
(
  mhhnvisn    char(8) default ' ' not null,
  mhhnuniq    char(8) default ' ' not null,
  mhhnhoty    char(3) default ' ' not null,
  mhhnactv    char(1) default ' ' not null,
  mhhnsent    char(1) default ' ' not null,
  mhhnhdat    char(8) default ' ' not null,
  mhhnsset    char(3) default ' ' not null,
  mhhnreas    char(3) default ' ' not null,
  mhhnrhcp    char(10) default ' ' not null,
  mhhncast    char(10) default ' ' not null,
  mhhnphcp    char(10) default ' ' not null,
  mhhnwebc    char(10) default ' ' not null,
  mhhncdte    char(8) default ' ' not null,
  mhhnctim    char(8) default ' ' not null,
  mhhncomp    char(1) default ' ' not null,
  mhhnwebf    char(10) default ' ' not null,
  mhhndatf    char(8) default ' ' not null,
  mhhntimf    char(8) default ' ' not null,
  mhhnwebu    char(10) default ' ' not null,
  mhhndatu    char(8) default ' ' not null,
  mhhntimu    char(8) default ' ' not null,
  mhhnfocu    char(3) default ' ' not null,
  mhhnculs    char(3) default ' ' not null,
  mhhnngos    char(1) default ' ' not null,
  mhhnngoa    char(1) default ' ' not null,
  mhhnngow    char(1) default ' ' not null,
  mhhnvoca    char(1) default ' ' not null,
  mhhnnsng    char(1) default ' ' not null,
  mhhncols    char(3) default ' ' not null,
  mhhnmoda    char(3) default ' ' not null,
  mhhnadq1    char(1) default ' ' not null,
  mhhnadq2    char(1) default ' ' not null,
  mhhnadq3    char(1) default ' ' not null,
  mhhnadq4    char(1) default ' ' not null,
  mhhnadq5    char(1) default ' ' not null,
  mhhnadq6    char(1) default ' ' not null,
  mhhnadq7    char(1) default ' ' not null,
  mhhnadq8    char(1) default ' ' not null,
  mhhnaq8a    char(1) default ' ' not null,
  mhhnfree    char(35) default ' ' not null,
  mhhnadq9    char(1) default ' ' not null,
  mhhnaq10    char(1) default ' ' not null,
  mhhnaq11    char(1) default ' ' not null,
  mhhnaq12    char(1) default ' ' not null,
  mhhncyq1    char(1) default ' ' not null,
  mhhncyq2    char(1) default ' ' not null,
  mhhncyq3    char(1) default ' ' not null,
  mhhncyq4    char(1) default ' ' not null,
  mhhncyq5    char(1) default ' ' not null,
  mhhncyq6    char(1) default ' ' not null,
  mhhncyq7    char(1) default ' ' not null,
  mhhncyq8    char(1) default ' ' not null,
  mhhncyq9    char(1) default ' ' not null,
  mhhncq10    char(1) default ' ' not null,
  mhhncq11    char(1) default ' ' not null,
  mhhncq12    char(1) default ' ' not null,
  mhhncq13    char(1) default ' ' not null,
  mhhncq14    char(1) default ' ' not null,
  mhhncq15    char(1) default ' ' not null,
  mhhnldq1    char(1) default ' ' not null,
  mhhnldq2    char(1) default ' ' not null,
  mhhnldq3    char(1) default ' ' not null,
  mhhnldq4    char(1) default ' ' not null,
  mhhnldq5    char(1) default ' ' not null,
  mhhnldq6    char(1) default ' ' not null,
  mhhnldq7    char(1) default ' ' not null,
  mhhnldq8    char(1) default ' ' not null,
  mhhnldq9    char(1) default ' ' not null,
  mhhnlq10    char(1) default ' ' not null,
  mhhnlq11    char(1) default ' ' not null,
  mhhnlq12    char(1) default ' ' not null,
  mhhnlq13    char(1) default ' ' not null,
  mhhnlq14    char(1) default ' ' not null,
  mhhnlq15    char(1) default ' ' not null,
  mhhnlq16    char(1) default ' ' not null,
  mhhnlq17    char(1) default ' ' not null,
  mhhnlq18    char(1) default ' ' not null,
  mhhnscq1    char(1) default ' ' not null,
  mhhnscq2    char(1) default ' ' not null,
  mhhnscq3    char(1) default ' ' not null,
  mhhnscq4    char(1) default ' ' not null,
  mhhnscq5    char(1) default ' ' not null,
  mhhnscq6    char(1) default ' ' not null,
  mhhnscq7    char(1) default ' ' not null,
  mhhnhver    char(3) default ' ' not null,
  mhhnld3a    char(3) default ' ' not null,
  mhhnrdat    char(8) default ' ' not null,
  mhhnrfmv    char(2) default ' ' not null,
  mhhndays    char(2) default ' ' not null,
  mhhnceps    char(2) default ' ' not null,
  mhhnam01    char(2) default ' ' not null,
  mhhnam02    char(2) default ' ' not null,
  mhhnam03    char(2) default ' ' not null,
  mhhnam04    char(2) default ' ' not null,
  mhhnam05    char(2) default ' ' not null,
  mhhnam06    char(2) default ' ' not null,
  mhhnam7a    char(2) default ' ' not null,
  mhhnam7b    char(2) default ' ' not null,
  mhhnam7c    char(2) default ' ' not null,
  mhhnam7d    char(2) default ' ' not null,
  mhhnam7e    char(2) default ' ' not null,
  mhhnam7f    char(2) default ' ' not null,
  mhhnam08    char(2) default ' ' not null,
  mhhnam9a    char(1) default ' ' not null,
  mhhnam9b    char(1) default ' ' not null,
  mhhnam9c    char(1) default ' ' not null,
  mhhnam10    char(2) default ' ' not null,
  mhhnam11    char(1) default ' ' not null,
  mhhnam12    char(2) default ' ' not null,
  mhhnam13    char(2) default ' ' not null,
  mhhnam14    char(2) default ' ' not null,
  mhhnam15    char(2) default ' ' not null,
  mhhnam16    char(2) default ' ' not null,
  mhhnam17    char(2) default ' ' not null,
  mhhnam18    char(2) default ' ' not null,
  mhhnam19    char(2) default ' ' not null,
  mhhnam20    char(2) default ' ' not null,
  mhhnurno    char(8) default ' ' not null,
  mhhndelf    char(1) default ' ' not null,
  mhhnduid    char(10) default ' ' not null,
  mhhnddte    char(8) default ' ' not null,
  mhhndtme    char(8) default ' ' not null,
  mhhndres    char(3) default ' ' not null,
  mhhnspar    char(40) default ' ' not null,
  lf          char(1)
);
create unique index mehhona1 on mehhonaf
(
mhhnvisn,
mhhnuniq
);
create unique index mehhona2 on mehhonaf
(
mhhnrdat,
mhhnvisn,
mhhnuniq
);
create unique index mehhona3 on mehhonaf
(
mhhnvisn,
mhhnhdat,
mhhnuniq
);
create unique index mehhona4 on mehhonaf
(
mhhnurno,
mhhnvisn,
mhhnuniq
);
revoke all on mehhonaf from public ; 
grant select on mehhonaf to public ; 
