create table mehscraf
(
  mhscurno    char(8) default ' ' not null,
  mhscsdat    char(8) default ' ' not null,
  mhsccoun    char(5) default ' ' not null,
  mhscuc01    char(3) default ' ' not null,
  mhscuc02    char(3) default ' ' not null,
  mhscuc03    char(3) default ' ' not null,
  mhscuc04    char(3) default ' ' not null,
  mhscuc05    char(3) default ' ' not null,
  mhscuc06    char(3) default ' ' not null,
  mhscuc07    char(3) default ' ' not null,
  mhscuc08    char(3) default ' ' not null,
  mhscuc09    char(3) default ' ' not null,
  mhscuc10    char(3) default ' ' not null,
  mhscuc11    char(3) default ' ' not null,
  mhscuc12    char(3) default ' ' not null,
  mhscuc13    char(3) default ' ' not null,
  mhscuc14    char(3) default ' ' not null,
  mhscuc15    char(3) default ' ' not null,
  mhscudt1    char(8) default ' ' not null,
  mhscutm1    char(8) default ' ' not null,
  mhscudt2    char(8) default ' ' not null,
  mhscutm2    char(8) default ' ' not null,
  mhscudt3    char(8) default ' ' not null,
  mhscutm3    char(8) default ' ' not null,
  mhscudt4    char(8) default ' ' not null,
  mhscutm4    char(8) default ' ' not null,
  mhscudt5    char(8) default ' ' not null,
  mhscutm5    char(8) default ' ' not null,
  mhscudt6    char(8) default ' ' not null,
  mhscutm6    char(8) default ' ' not null,
  mhscudt7    char(8) default ' ' not null,
  mhscutm7    char(8) default ' ' not null,
  mhscudt8    char(8) default ' ' not null,
  mhscutm8    char(8) default ' ' not null,
  mhscudt9    char(8) default ' ' not null,
  mhscutm9    char(8) default ' ' not null,
  mhscuhc1    char(10) default ' ' not null,
  mhscuhc2    char(10) default ' ' not null,
  mhscuhc3    char(10) default ' ' not null,
  mhscuhc4    char(10) default ' ' not null,
  mhscuhc5    char(10) default ' ' not null,
  mhscuhc6    char(10) default ' ' not null,
  mhscuhc7    char(10) default ' ' not null,
  mhscuhc8    char(10) default ' ' not null,
  mhscuhc9    char(10) default ' ' not null,
  mhscuyn1    char(1) default ' ' not null,
  mhscuyn2    char(1) default ' ' not null,
  mhscuyn3    char(1) default ' ' not null,
  mhscuyn4    char(1) default ' ' not null,
  mhscuyn5    char(1) default ' ' not null,
  mhscuyn6    char(1) default ' ' not null,
  mhscuyn7    char(1) default ' ' not null,
  mhscuyn8    char(1) default ' ' not null,
  mhscuyn9    char(1) default ' ' not null,
  mhscuff1    char(60) default ' ' not null,
  mhscuff2    char(60) default ' ' not null,
  mhscuff3    char(60) default ' ' not null,
  mhscuff4    char(60) default ' ' not null,
  mhscuff5    char(60) default ' ' not null,
  mhsccdat    char(8) default ' ' not null,
  mhscctim    char(8) default ' ' not null,
  mhsccuid    char(10) default ' ' not null,
  mhscudat    char(8) default ' ' not null,
  mhscutim    char(8) default ' ' not null,
  mhscuuid    char(10) default ' ' not null,
  mhscstat    char(1) default ' ' not null,
  mhscspar    char(100) default ' ' not null,
  lf          char(1)
);
create unique index mehscra1 on mehscraf
(
mhscurno,
mhscsdat
);
revoke all on mehscraf from public ; 
grant select on mehscraf to public ; 
