create table obsdetaf
(
obdevist    char(8),
obdedate    char(8),
obdetime    char(8),
obdetyp     char(3),
obdepuls    decimal(3,0),
obdetemp    decimal(4,1),
obdebpsy    decimal(3,0),
obdebpdi    decimal(3,0),
obderesp    decimal(3,0),
obdepox     decimal(3,0),
obdeo2f     decimal(3,0),
obdepfl     decimal(4,0),
obdefoc     char(3),
obdefic     char(3),
obdefot     decimal(6,0),
obdefin     decimal(6,0),
obdeeyeo    char(1),
obdeverb    char(1),
obdemoto    char(1),
obdepsl     char(1),
obdepsr     char(1),
obdeprl     char(1),
obdeprr     char(1),
obdelmla    char(1),
obdelmrm    char(1),
obdelmll    char(1),
obdelmrl    char(1),
obdeact     char(3),
obdeuy1     char(1),
obdeuy2     char(1),
obdeuy3     char(1),
obdeuy4     char(1),
obdeuc1     char(3),
obdeuc2     char(3),
obdeun1     decimal(8,2),
obdeun2     decimal(8,2),
obdeun3     decimal(8,2),
obdeun4     decimal(8,2),
obdeuid     char(10),
obdemdat    char(8),
obdemtim    char(8),
obdecom1    char(40),
obdecom2    char(40),
obdecom3    char(40),
obdepnsc    char(2),
obdecvps    char(1),
obdespa     char(17),
lf          char(1)
);
create unique index obsdeta1 on obsdetaf
(
obdevist,
obdedate,
obdetime
);
revoke all on obsdetaf from public ; 
grant select on obsdetaf to public ; 
