create table opraudar
(
  oparaudd    char(8) default ' ' not null,
  oparaudt    char(8) default ' ' not null,
  oparaudp    char(2) default ' ' not null,
  oparaudr    char(1) default ' ' not null,
  oparauds    decimal(1,0) default 0 not null,
  oparaudo    char(4) default ' ' not null,
  oparunid    char(10) default ' ' not null,
  oparatim    char(8) default ' ' not null,
  oparanur    char(6) default ' ' not null,
  oparrlat    char(3) default ' ' not null,
  oparpclc    char(1) default ' ' not null,
  oparcsfs    char(1) default ' ' not null,
  oparmdre    char(1) default ' ' not null,
  oparxray    char(1) default ' ' not null,
  oparblem    char(1) default ' ' not null,
  oparmupj    char(1) default ' ' not null,
  oparpmed    char(1) default ' ' not null,
  oparalck    char(1) default ' ' not null,
  oparprot    char(40) default ' ' not null,
  oparuc01    char(3) default ' ' not null,
  oparuc02    char(3) default ' ' not null,
  oparuc03    char(3) default ' ' not null,
  oparuc04    char(3) default ' ' not null,
  oparuc05    char(3) default ' ' not null,
  oparuc06    char(3) default ' ' not null,
  oparuc07    char(3) default ' ' not null,
  oparuc08    char(3) default ' ' not null,
  oparuc09    char(3) default ' ' not null,
  oparuc10    char(3) default ' ' not null,
  oparuy01    char(1) default ' ' not null,
  oparuy02    char(1) default ' ' not null,
  oparuy03    char(1) default ' ' not null,
  oparuy04    char(1) default ' ' not null,
  oparuy05    char(1) default ' ' not null,
  oparut01    char(8) default ' ' not null,
  oparut02    char(8) default ' ' not null,
  oparut03    char(8) default ' ' not null,
  oparut04    char(8) default ' ' not null,
  oparut05    char(8) default ' ' not null,
  oparuf01    decimal(6,0) default 0 not null,
  oparuf02    decimal(6,0) default 0 not null,
  oparuf03    decimal(6,0) default 0 not null,
  oparuf04    decimal(6,0) default 0 not null,
  oparuf05    decimal(6,0) default 0 not null,
  opartcal    char(8) default ' ' not null,
  oparuiar    char(10) default ' ' not null,
  oparanap    char(8) default ' ' not null,
  oparanas    char(8) default ' ' not null,
  oparanae    char(8) default ' ' not null,
  oparityp    char(3) default ' ' not null,
  oparuc11    char(3) default ' ' not null,
  oparuc12    char(3) default ' ' not null,
  oparuc13    char(3) default ' ' not null,
  oparuc14    char(3) default ' ' not null,
  oparuc15    char(3) default ' ' not null,
  oparuc16    char(3) default ' ' not null,
  oparuc17    char(3) default ' ' not null,
  oparuc18    char(3) default ' ' not null,
  oparuc19    char(3) default ' ' not null,
  oparuc20    char(3) default ' ' not null,
  oparuy06    char(1) default ' ' not null,
  oparuy07    char(1) default ' ' not null,
  oparuy08    char(1) default ' ' not null,
  oparuy09    char(1) default ' ' not null,
  oparuy10    char(1) default ' ' not null,
  oparut06    char(8) default ' ' not null,
  oparut07    char(8) default ' ' not null,
  oparut08    char(8) default ' ' not null,
  oparut09    char(8) default ' ' not null,
  oparut10    char(8) default ' ' not null,
  oparuf06    decimal(6,0) default 0 not null,
  oparuf07    decimal(6,0) default 0 not null,
  oparuf08    decimal(6,0) default 0 not null,
  oparuf09    decimal(6,0) default 0 not null,
  oparuf10    decimal(6,0) default 0 not null,
  oparuana    char(10) default ' ' not null,
  opartirf    char(8) default ' ' not null,
  oparnuf1    char(6) default ' ' not null,
  oparnuf2    char(6) default ' ' not null,
  opartirb    char(8) default ' ' not null,
  oparnub1    char(6) default ' ' not null,
  oparnub2    char(6) default ' ' not null,
  opartird    char(8) default ' ' not null,
  oparnud1    char(6) default ' ' not null,
  oparnud2    char(6) default ' ' not null,
  opartetc    char(8) default ' ' not null,
  oparurec    char(10) default ' ' not null,
  opartexp    char(8) default ' ' not null,
  oparticu    char(8) default ' ' not null,
  oparrdcd    char(3) default ' ' not null,
  opartidp    char(8) default ' ' not null,
  oparuc21    char(3) default ' ' not null,
  oparuc22    char(3) default ' ' not null,
  oparuc23    char(3) default ' ' not null,
  oparuc24    char(3) default ' ' not null,
  oparuc25    char(3) default ' ' not null,
  oparuc26    char(3) default ' ' not null,
  oparuc27    char(3) default ' ' not null,
  oparuc28    char(3) default ' ' not null,
  oparuc29    char(3) default ' ' not null,
  oparuc30    char(3) default ' ' not null,
  oparuy11    char(1) default ' ' not null,
  oparuy12    char(1) default ' ' not null,
  oparuy13    char(1) default ' ' not null,
  oparuy14    char(1) default ' ' not null,
  oparuy15    char(1) default ' ' not null,
  oparut11    char(8) default ' ' not null,
  oparut12    char(8) default ' ' not null,
  oparut13    char(8) default ' ' not null,
  oparut14    char(8) default ' ' not null,
  oparut15    char(8) default ' ' not null,
  oparuf11    decimal(6,0) default 0 not null,
  oparuf12    decimal(6,0) default 0 not null,
  oparuf13    decimal(6,0) default 0 not null,
  oparuf14    decimal(6,0) default 0 not null,
  oparuf15    decimal(6,0) default 0 not null,
  oparuyn1    char(10) default ' ' not null,
  oparuyn2    char(10) default ' ' not null,
  oparadst    char(8) default ' ' not null,
  oparadet    char(8) default ' ' not null,
  oparut16    char(8) default ' ' not null,
  oparut17    char(8) default ' ' not null,
  oparut18    char(8) default ' ' not null,
  oparut19    char(8) default ' ' not null,
  oparspar    char(50) default ' ' not null,
  lf          char(1)
);
create index opraudar on opraudar
(
oparaudd,
oparaudt,
oparaudp,
oparaudr
);
revoke all on opraudar from public ; 
grant select on opraudar to public ; 
create table oprardaf
(
  oparunid    char(10) default ' ' not null,
  oparatim    char(8) default ' ' not null,
  oparanur    char(6) default ' ' not null,
  oparrlat    char(3) default ' ' not null,
  oparpclc    char(1) default ' ' not null,
  oparcsfs    char(1) default ' ' not null,
  oparmdre    char(1) default ' ' not null,
  oparxray    char(1) default ' ' not null,
  oparblem    char(1) default ' ' not null,
  oparmupj    char(1) default ' ' not null,
  oparpmed    char(1) default ' ' not null,
  oparalck    char(1) default ' ' not null,
  oparprot    char(40) default ' ' not null,
  oparuc01    char(3) default ' ' not null,
  oparuc02    char(3) default ' ' not null,
  oparuc03    char(3) default ' ' not null,
  oparuc04    char(3) default ' ' not null,
  oparuc05    char(3) default ' ' not null,
  oparuc06    char(3) default ' ' not null,
  oparuc07    char(3) default ' ' not null,
  oparuc08    char(3) default ' ' not null,
  oparuc09    char(3) default ' ' not null,
  oparuc10    char(3) default ' ' not null,
  oparuy01    char(1) default ' ' not null,
  oparuy02    char(1) default ' ' not null,
  oparuy03    char(1) default ' ' not null,
  oparuy04    char(1) default ' ' not null,
  oparuy05    char(1) default ' ' not null,
  oparut01    char(8) default ' ' not null,
  oparut02    char(8) default ' ' not null,
  oparut03    char(8) default ' ' not null,
  oparut04    char(8) default ' ' not null,
  oparut05    char(8) default ' ' not null,
  oparuf01    decimal(6,0) default 0 not null,
  oparuf02    decimal(6,0) default 0 not null,
  oparuf03    decimal(6,0) default 0 not null,
  oparuf04    decimal(6,0) default 0 not null,
  oparuf05    decimal(6,0) default 0 not null,
  opartcal    char(8) default ' ' not null,
  oparuiar    char(10) default ' ' not null,
  oparanap    char(8) default ' ' not null,
  oparanas    char(8) default ' ' not null,
  oparanae    char(8) default ' ' not null,
  oparityp    char(3) default ' ' not null,
  oparuc11    char(3) default ' ' not null,
  oparuc12    char(3) default ' ' not null,
  oparuc13    char(3) default ' ' not null,
  oparuc14    char(3) default ' ' not null,
  oparuc15    char(3) default ' ' not null,
  oparuc16    char(3) default ' ' not null,
  oparuc17    char(3) default ' ' not null,
  oparuc18    char(3) default ' ' not null,
  oparuc19    char(3) default ' ' not null,
  oparuc20    char(3) default ' ' not null,
  oparuy06    char(1) default ' ' not null,
  oparuy07    char(1) default ' ' not null,
  oparuy08    char(1) default ' ' not null,
  oparuy09    char(1) default ' ' not null,
  oparuy10    char(1) default ' ' not null,
  oparut06    char(8) default ' ' not null,
  oparut07    char(8) default ' ' not null,
  oparut08    char(8) default ' ' not null,
  oparut09    char(8) default ' ' not null,
  oparut10    char(8) default ' ' not null,
  oparuf06    decimal(6,0) default 0 not null,
  oparuf07    decimal(6,0) default 0 not null,
  oparuf08    decimal(6,0) default 0 not null,
  oparuf09    decimal(6,0) default 0 not null,
  oparuf10    decimal(6,0) default 0 not null,
  oparuana    char(10) default ' ' not null,
  opartirf    char(8) default ' ' not null,
  oparnuf1    char(6) default ' ' not null,
  oparnuf2    char(6) default ' ' not null,
  opartirb    char(8) default ' ' not null,
  oparnub1    char(6) default ' ' not null,
  oparnub2    char(6) default ' ' not null,
  opartird    char(8) default ' ' not null,
  oparnud1    char(6) default ' ' not null,
  oparnud2    char(6) default ' ' not null,
  opartetc    char(8) default ' ' not null,
  oparurec    char(10) default ' ' not null,
  opartexp    char(8) default ' ' not null,
  oparticu    char(8) default ' ' not null,
  oparrdcd    char(3) default ' ' not null,
  opartidp    char(8) default ' ' not null,
  oparuc21    char(3) default ' ' not null,
  oparuc22    char(3) default ' ' not null,
  oparuc23    char(3) default ' ' not null,
  oparuc24    char(3) default ' ' not null,
  oparuc25    char(3) default ' ' not null,
  oparuc26    char(3) default ' ' not null,
  oparuc27    char(3) default ' ' not null,
  oparuc28    char(3) default ' ' not null,
  oparuc29    char(3) default ' ' not null,
  oparuc30    char(3) default ' ' not null,
  oparuy11    char(1) default ' ' not null,
  oparuy12    char(1) default ' ' not null,
  oparuy13    char(1) default ' ' not null,
  oparuy14    char(1) default ' ' not null,
  oparuy15    char(1) default ' ' not null,
  oparut11    char(8) default ' ' not null,
  oparut12    char(8) default ' ' not null,
  oparut13    char(8) default ' ' not null,
  oparut14    char(8) default ' ' not null,
  oparut15    char(8) default ' ' not null,
  oparuf11    decimal(6,0) default 0 not null,
  oparuf12    decimal(6,0) default 0 not null,
  oparuf13    decimal(6,0) default 0 not null,
  oparuf14    decimal(6,0) default 0 not null,
  oparuf15    decimal(6,0) default 0 not null,
  oparuyn1    char(10) default ' ' not null,
  oparuyn2    char(10) default ' ' not null,
  oparadst    char(8) default ' ' not null,
  oparadet    char(8) default ' ' not null,
  oparut16    char(8) default ' ' not null,
  oparut17    char(8) default ' ' not null,
  oparut18    char(8) default ' ' not null,
  oparut19    char(8) default ' ' not null,
  oparspar    char(50) default ' ' not null,
  lf          char(1)
);
create unique index oprarda1 on oprardaf
(
oparunid
);
revoke all on oprardaf from public ; 
grant select on oprardaf to public ; 
