create table opraaeaf
(
  opaadate    char(8) default ' ' not null,
  opaatime    char(5) default ' ' not null,
  opaaclin    char(6) default ' ' not null,
  opaacase    char(3) default ' ' not null,
  opaaadmn    char(8) default ' ' not null,
  opaageur    char(1) default ' ' not null,
  opaageac    char(1) default ' ' not null,
  opaagep1    char(1) default ' ' not null,
  opaagep2    char(1) default ' ' not null,
  opaapmra    char(1) default ' ' not null,
  opaapmp1    char(2) default ' ' not null,
  opaapmp2    char(2) default ' ' not null,
  opaarfps    char(1) default ' ' not null,
  opaarfta    char(1) default ' ' not null,
  opaarfbr    char(1) default ' ' not null,
  opaarfrd    char(1) default ' ' not null,
  opaarfla    char(1) default ' ' not null,
  opaarfbo    char(1) default ' ' not null,
  opaarfas    char(1) default ' ' not null,
  opaarfvb    char(1) default ' ' not null,
  opaarfre    char(1) default ' ' not null,
  opaarfrc    char(1) default ' ' not null,
  opaaccia    char(1) default ' ' not null,
  opaacccp    char(1) default ' ' not null,
  opaaccec    char(1) default ' ' not null,
  opaaccna    char(1) default ' ' not null,
  opaacchp    char(1) default ' ' not null,
  opaacchr    char(1) default ' ' not null,
  opaaccbr    char(1) default ' ' not null,
  opaaccta    char(1) default ' ' not null,
  opaabtb1    char(1) default ' ' not null,
  opaabtb2    char(1) default ' ' not null,
  opaabtb3    char(1) default ' ' not null,
  opaaorde    char(1) default ' ' not null,
  opaaordt    char(1) default ' ' not null,
  opaaoran    char(1) default ' ' not null,
  opaaorse    char(1) default ' ' not null,
  opaaorun    char(1) default ' ' not null,
  opaaorir    char(1) default ' ' not null,
  opaaornb    char(1) default ' ' not null,
  opaaorst    char(1) default ' ' not null,
  opaadiin    char(1) default ' ' not null,
  opaaadve    char(1) default ' ' not null,
  opaadidt    char(300) default ' ' not null,
  opaaotfd    char(50) default ' ' not null,
  opaaotf1    char(50) default ' ' not null,
  opaaotf2    char(50) default ' ' not null,
  opaaotf3    char(50) default ' ' not null,
  opaaotf4    char(50) default ' ' not null,
  opaaotf5    char(50) default ' ' not null,
  opaarfde    char(1) default ' ' not null,
  opaaspar    char(81) default ' ' not null,
  lf          char(1)
);
create unique index opraae11 on opraaeaf
(
opaadate,
opaatime,
opaaclin,
opaacase,
opaaadmn
);
revoke all on opraaeaf from public ; 
grant select on opraaeaf to public ; 
