create table oprauddc
(
opdcaudd    char(8),
opdcaudt    char(8),
opdcaudp    char(2),
opdcaudr    char(1),
opdcauds    decimal(1,0),
opdcaudo    char(4),
opdcuniq    char(10),
opdcteam    char(1),
opdcotm1    char(5),
opdcotm2    char(5),
opdcotm3    char(5),
opdcotm4    char(5),
opdcicd1    char(9),
opdcicd2    char(9),
opdcicd3    char(9),
opdcicd4    char(9),
opdcicd5    char(9),
opdcicd6    char(9),
opdccont    char(1),
opdcdura    decimal(4,0),
opdcnoop    decimal(3,0),
opdcimc1    char(6),
opdcimc2    char(6),
opdcimc3    char(6),
opdcimc4    char(6),
opdcimc5    char(6),
opdcimc6    char(6),
opdcimc7    char(6),
opdcimc8    char(6),
opdcimc9    char(6),
opdcim10    char(6),
opdcimq1    decimal(3,0),
opdcimq2    decimal(3,0),
opdcimq3    decimal(3,0),
opdcimq4    decimal(3,0),
opdcimq5    decimal(3,0),
opdcimq6    decimal(3,0),
opdcimq7    decimal(3,0),
opdcimq8    decimal(3,0),
opdcimq9    decimal(3,0),
opdciq10    decimal(3,0),
opdcusr1    char(3),
opdcusr2    char(3),
opdcusr3    char(3),
opdcusr4    char(3),
opdcusr5    char(3),
opdcusr6    char(3),
opdcusr7    char(3),
opdcusr8    char(3),
opdcspar    char(23),
lf          char(1)
);
create index oprauddc on oprauddc
(
opdcaudd,
opdcaudt,
opdcaudp,
opdcaudr
);
revoke all on oprauddc from public ; 
grant select on oprauddc to public ; 
create table oprdetcf
(
opdcuniq    char(10),
opdcteam    char(1),
opdcotm1    char(5),
opdcotm2    char(5),
opdcotm3    char(5),
opdcotm4    char(5),
opdcicd1    char(9),
opdcicd2    char(9),
opdcicd3    char(9),
opdcicd4    char(9),
opdcicd5    char(9),
opdcicd6    char(9),
opdccont    char(1),
opdcdura    decimal(4,0),
opdcnoop    decimal(3,0),
opdcimc1    char(6),
opdcimc2    char(6),
opdcimc3    char(6),
opdcimc4    char(6),
opdcimc5    char(6),
opdcimc6    char(6),
opdcimc7    char(6),
opdcimc8    char(6),
opdcimc9    char(6),
opdcim10    char(6),
opdcimq1    decimal(3,0),
opdcimq2    decimal(3,0),
opdcimq3    decimal(3,0),
opdcimq4    decimal(3,0),
opdcimq5    decimal(3,0),
opdcimq6    decimal(3,0),
opdcimq7    decimal(3,0),
opdcimq8    decimal(3,0),
opdcimq9    decimal(3,0),
opdciq10    decimal(3,0),
opdcusr1    char(3),
opdcusr2    char(3),
opdcusr3    char(3),
opdcusr4    char(3),
opdcusr5    char(3),
opdcusr6    char(3),
opdcusr7    char(3),
opdcusr8    char(3),
opdcspar    char(23),
lf          char(1)
);
create unique index oprdetc1 on oprdetcf
(
opdcuniq,
opdcteam
);
revoke all on oprdetcf from public ; 
grant select on oprdetcf to public ; 
