create table oprauddb
(
opdbaudd    char(8),
opdbaudt    char(8),
opdbaudp    char(2),
opdbaudr    char(1),
opdbauds    decimal(1,0),
opdbaudo    char(4),
opdbuniq    char(10),
opdbteam    char(1),
opdbtyd1    char(3),
opdbtyd2    char(3),
opdbtyd3    char(3),
opdbtyd4    char(3),
opdbtyd5    char(3),
opdbtyd6    char(3),
opdbtyd7    char(3),
opdbtyd8    char(3),
opdbdcc1    char(6),
opdbdcc2    char(6),
opdbdcc3    char(6),
opdbdcc4    char(6),
opdbdcc5    char(6),
opdbdcc6    char(6),
opdbdcc7    char(6),
opdbdcc8    char(6),
opdblvd1    char(3),
opdblvd2    char(3),
opdblvd3    char(3),
opdblvd4    char(3),
opdblvd5    char(3),
opdblvd6    char(3),
opdblvd7    char(3),
opdblvd8    char(3),
opdbtyn1    char(3),
opdbtyn2    char(3),
opdbtyn3    char(3),
opdbtyn4    char(3),
opdbtyn5    char(3),
opdbtyn6    char(3),
opdbnuc1    char(6),
opdbnuc2    char(6),
opdbnuc3    char(6),
opdbnuc4    char(6),
opdbnuc5    char(6),
opdbnuc6    char(6),
opdbusr1    char(3),
opdbusr2    char(3),
opdbusr3    char(3),
opdbusr4    char(3),
opdbspar    char(30),
lf          char(1)
);
create index oprauddb on oprauddb
(
opdbaudd,
opdbaudt,
opdbaudp,
opdbaudr
);
revoke all on oprauddb from public ; 
grant select on oprauddb to public ; 
create table oprdetbf
(
opdbuniq    char(10),
opdbteam    char(1),
opdbtyd1    char(3),
opdbtyd2    char(3),
opdbtyd3    char(3),
opdbtyd4    char(3),
opdbtyd5    char(3),
opdbtyd6    char(3),
opdbtyd7    char(3),
opdbtyd8    char(3),
opdbdcc1    char(6),
opdbdcc2    char(6),
opdbdcc3    char(6),
opdbdcc4    char(6),
opdbdcc5    char(6),
opdbdcc6    char(6),
opdbdcc7    char(6),
opdbdcc8    char(6),
opdblvd1    char(3),
opdblvd2    char(3),
opdblvd3    char(3),
opdblvd4    char(3),
opdblvd5    char(3),
opdblvd6    char(3),
opdblvd7    char(3),
opdblvd8    char(3),
opdbtyn1    char(3),
opdbtyn2    char(3),
opdbtyn3    char(3),
opdbtyn4    char(3),
opdbtyn5    char(3),
opdbtyn6    char(3),
opdbnuc1    char(6),
opdbnuc2    char(6),
opdbnuc3    char(6),
opdbnuc4    char(6),
opdbnuc5    char(6),
opdbnuc6    char(6),
opdbusr1    char(3),
opdbusr2    char(3),
opdbusr3    char(3),
opdbusr4    char(3),
opdbspar    char(30),
lf          char(1)
);
create unique index oprdetb1 on oprdetbf
(
opdbuniq,
opdbteam
);
revoke all on oprdetbf from public ; 
grant select on oprdetbf to public ; 
