create table opraudda
(
  opdaaudd    char(8) default ' ' not null,
  opdaaudt    char(8) default ' ' not null,
  opdaaudp    char(2) default ' ' not null,
  opdaaudr    char(1) default ' ' not null,
  opdaauds    decimal(1,0) default 0 not null,
  opdaaudo    char(4) default ' ' not null,
  opdadate    char(8) default ' ' not null,
  opdatime    char(5) default ' ' not null,
  opdaclin    char(6) default ' ' not null,
  dopdasta    char(1) default ' ' not null,
  opdacase    char(3) default ' ' not null,
  opdaadmn    char(8) default ' ' not null,
  opdauniq    char(10) default ' ' not null,
  opdaexps    char(5) default ' ' not null,
  opdaexpd    decimal(4,0) default 0 not null,
  opdaanae    char(3) default ' ' not null,
  opdatype    char(3) default ' ' not null,
  opdatran    char(3) default ' ' not null,
  opdausr1    char(3) default ' ' not null,
  opdausr2    char(3) default ' ' not null,
  opdausr3    char(3) default ' ' not null,
  opdausr4    char(3) default ' ' not null,
  opdawait    char(1) default ' ' not null,
  opdaprov    char(9) default ' ' not null,
  opdaprv2    char(9) default ' ' not null,
  opdaprv3    char(9) default ' ' not null,
  opdades1    char(80) default ' ' not null,
  opdades2    char(80) default ' ' not null,
  opdades3    char(80) default ' ' not null,
  opdacomm    char(40) default ' ' not null,
  opdacanc    char(3) default ' ' not null,
  opdathet    char(6) default ' ' not null,
  opdapre1    char(5) default ' ' not null,
  opdapre2    char(5) default ' ' not null,
  opdapre3    char(5) default ' ' not null,
  opdapre4    char(5) default ' ' not null,
  opdapre5    char(5) default ' ' not null,
  opdapos1    char(5) default ' ' not null,
  opdapos2    char(5) default ' ' not null,
  opdapos3    char(5) default ' ' not null,
  opdapos4    char(5) default ' ' not null,
  opdatdur    decimal(4,0) default 0 not null,
  opdaknow    char(3) default ' ' not null,
  opdacdat    char(8) default ' ' not null,
  opdaeqr1    char(3) default ' ' not null,
  opdaeqr2    char(3) default ' ' not null,
  opdaleqr    char(3) default ' ' not null,
  opdaeqr3    char(3) default ' ' not null,
  opdaunit    char(3) default ' ' not null,
  opdaurno    char(8) default ' ' not null,
  opdaproc    char(9) default ' ' not null,
  opdacont    char(2) default ' ' not null,
  opdaasrc    char(3) default ' ' not null,
  opdacsst    char(1) default ' ' not null,
  opdacsdt    char(8) default ' ' not null,
  opdacrdt    char(8) default ' ' not null,
  opdactim    char(8) default ' ' not null,
  opdawebc    char(10) default ' ' not null,
  opdaudat    char(8) default ' ' not null,
  opdautim    char(8) default ' ' not null,
  opdawebu    char(10) default ' ' not null,
  opdapcom    char(1) default ' ' not null,
  opdavun1    char(10) default ' ' not null,
  opdavun2    char(10) default ' ' not null,
  opdaphmn    char(10) default ' ' not null,
  opdareqn    char(10) default ' ' not null,
  opdades4    char(80) default ' ' not null,
  opdades5    char(80) default ' ' not null,
  opdades6    char(80) default ' ' not null,
  opdafast    char(8) default ' ' not null,
  opdaaprc    char(1) default ' ' not null,
  opdaacpd    char(1) default ' ' not null,
  opdaricm    char(3) default ' ' not null,
  opdamhrc    char(1) default ' ' not null,
  opdapowd    char(3) default ' ' not null,
  opdapobd    char(3) default ' ' not null,
  opdactyp    char(3) default ' ' not null,
  opdaatyp    char(3) default ' ' not null,
  opdadtff    char(8) default ' ' not null,
  opdadtfl    char(8) default ' ' not null,
  opdaprv4    char(9) default ' ' not null,
  opdaprv5    char(9) default ' ' not null,
  opdaprv6    char(9) default ' ' not null,
  opdahosp    char(3) default ' ' not null,
  opdaspar    char(47) default ' ' not null,
  lf          char(1)
);
create index opraudda on opraudda
(
opdaaudd,
opdaaudt,
opdaaudp,
opdaaudr
);
revoke all on opraudda from public ; 
grant select on opraudda to public ; 
create table oprdetaf
(
  opdadate    char(8) default ' ' not null,
  opdatime    char(5) default ' ' not null,
  opdaclin    char(6) default ' ' not null,
  dopdasta    char(1) default ' ' not null,
  opdacase    char(3) default ' ' not null,
  opdaadmn    char(8) default ' ' not null,
  opdauniq    char(10) default ' ' not null,
  opdaexps    char(5) default ' ' not null,
  opdaexpd    decimal(4,0) default 0 not null,
  opdaanae    char(3) default ' ' not null,
  opdatype    char(3) default ' ' not null,
  opdatran    char(3) default ' ' not null,
  opdausr1    char(3) default ' ' not null,
  opdausr2    char(3) default ' ' not null,
  opdausr3    char(3) default ' ' not null,
  opdausr4    char(3) default ' ' not null,
  opdawait    char(1) default ' ' not null,
  opdaprov    char(9) default ' ' not null,
  opdaprv2    char(9) default ' ' not null,
  opdaprv3    char(9) default ' ' not null,
  opdades1    char(80) default ' ' not null,
  opdades2    char(80) default ' ' not null,
  opdades3    char(80) default ' ' not null,
  opdacomm    char(40) default ' ' not null,
  opdacanc    char(3) default ' ' not null,
  opdathet    char(6) default ' ' not null,
  opdapre1    char(5) default ' ' not null,
  opdapre2    char(5) default ' ' not null,
  opdapre3    char(5) default ' ' not null,
  opdapre4    char(5) default ' ' not null,
  opdapre5    char(5) default ' ' not null,
  opdapos1    char(5) default ' ' not null,
  opdapos2    char(5) default ' ' not null,
  opdapos3    char(5) default ' ' not null,
  opdapos4    char(5) default ' ' not null,
  opdatdur    decimal(4,0) default 0 not null,
  opdaknow    char(3) default ' ' not null,
  opdacdat    char(8) default ' ' not null,
  opdaeqr1    char(3) default ' ' not null,
  opdaeqr2    char(3) default ' ' not null,
  opdaleqr    char(3) default ' ' not null,
  opdaeqr3    char(3) default ' ' not null,
  opdaunit    char(3) default ' ' not null,
  opdaurno    char(8) default ' ' not null,
  opdaproc    char(9) default ' ' not null,
  opdacont    char(2) default ' ' not null,
  opdaasrc    char(3) default ' ' not null,
  opdacsst    char(1) default ' ' not null,
  opdacsdt    char(8) default ' ' not null,
  opdacrdt    char(8) default ' ' not null,
  opdactim    char(8) default ' ' not null,
  opdawebc    char(10) default ' ' not null,
  opdaudat    char(8) default ' ' not null,
  opdautim    char(8) default ' ' not null,
  opdawebu    char(10) default ' ' not null,
  opdapcom    char(1) default ' ' not null,
  opdavun1    char(10) default ' ' not null,
  opdavun2    char(10) default ' ' not null,
  opdaphmn    char(10) default ' ' not null,
  opdareqn    char(10) default ' ' not null,
  opdades4    char(80) default ' ' not null,
  opdades5    char(80) default ' ' not null,
  opdades6    char(80) default ' ' not null,
  opdafast    char(8) default ' ' not null,
  opdaaprc    char(1) default ' ' not null,
  opdaacpd    char(1) default ' ' not null,
  opdaricm    char(3) default ' ' not null,
  opdamhrc    char(1) default ' ' not null,
  opdapowd    char(3) default ' ' not null,
  opdapobd    char(3) default ' ' not null,
  opdactyp    char(3) default ' ' not null,
  opdaatyp    char(3) default ' ' not null,
  opdadtff    char(8) default ' ' not null,
  opdadtfl    char(8) default ' ' not null,
  opdaprv4    char(9) default ' ' not null,
  opdaprv5    char(9) default ' ' not null,
  opdaprv6    char(9) default ' ' not null,
  opdahosp    char(3) default ' ' not null,
  opdaspar    char(47) default ' ' not null,
  lf          char(1)
);
create unique index oprdeta1 on oprdetaf
(
opdahosp,
opdadate,
opdatime,
opdaclin,
dopdasta,
opdacase
);
create unique index oprdeta2 on oprdetaf
(
opdaadmn,
dopdasta,
opdadate,
opdatime,
opdaclin,
opdacase
);
create unique index oprdeta3 on oprdetaf
(
opdauniq
);
create unique index oprdeta4 on oprdetaf
(
opdaurno,
opdaproc,
opdacont,
opdauniq
);
create unique index oprdeta5 on oprdetaf
(
opdahosp,
opdadate,
opdatime,
opdaclin,
opdacase,
dopdasta
);
create unique index oprdeta6 on oprdetaf
(
opdadate,
opdatime,
opdaclin,
opdacase,
dopdasta,
opdahosp
);
revoke all on oprdetaf from public ; 
grant select on oprdetaf to public ; 
