create table oprjrraf
(
opjruniq    char(10),
opjrrcnt    char(2),
opjrtype    char(1),
opjrjoin    char(1),
opjrside    char(1),
opjrprim    char(1),
opjrdi01    char(1),
opjrdi02    char(1),
opjrdi03    char(1),
opjrdi04    char(1),
opjrdi05    char(1),
opjrdi06    char(1),
opjrdi07    char(1),
opjrdi08    char(1),
opjrdi09    char(1),
opjrdi10    char(1),
opjrdi11    char(1),
opjrdi12    char(1),
opjrdi13    char(1),
opjrdi14    char(1),
opjrdi15    char(1),
opjrdi16    char(1),
opjrdi17    char(1),
opjrdi18    char(1),
opjrdi19    char(1),
opjrdi20    char(1),
opjrdi21    char(1),
opjrdi22    char(1),
opjrdi23    char(1),
opjrdi24    char(1),
opjrdi25    char(1),
opjrdc01    char(50),
opjrdc02    char(50),
opjrdc03    char(50),
opjrdc04    char(50),
opjrdc05    char(50),
opjruncm    char(1),
opjruncl    char(1),
opjrcmt1    char(70),
opjrcmt2    char(70),
opjrcmt3    char(70),
opjrcmt4    char(70),
opjrcmt5    char(70),
opjrcomp    char(1),
opjrcmps    char(3),
opjrreop    char(1),
opjrrres    char(50),
opjrcemp    char(1),
opjrcnmp    char(50),
opjrcemt    char(1),
opjrcnmt    char(50),
opjrcemf    char(1),
opjrcnmf    char(50),
opjrcema    char(1),
opjrcnma    char(50),
opjrcemx    char(1),
opjrcnmx    char(50),
opjrcemd    char(1),
opjrscrw    char(1),
opjrscrn    char(3),
opjrwire    char(1),
opjrgrip    char(1),
opjrgric    char(50),
opjrcabl    char(1),
opjrcabc    char(50),
opjrcabn    char(3),
opjrcdat    char(8),
opjrctim    char(8),
opjrcuid    char(10),
opjrudat    char(8),
opjrutim    char(8),
opjruuid    char(10),
opjrspar    char(80),
lf          char(1)
);
create unique index oprjrra1 on oprjrraf
(
opjruniq,
opjrrcnt
);
revoke all on oprjrraf from public ; 
grant select on oprjrraf to public ; 
