create table oprpocaf
(
  oppounid    char(10) default ' ' not null,
  dopporty    char(1) default ' ' not null,
  oppopidb    char(1) default ' ' not null,
  opposatf    char(1) default ' ' not null,
  oppoaatf    char(1) default ' ' not null,
  oppobatf    char(1) default ' ' not null,
  oppotbpf    char(1) default ' ' not null,
  oppotnbm    char(8) default ' ' not null,
  oppotnbf    char(8) default ' ' not null,
  opponbmc    char(1) default ' ' not null,
  opponbfc    char(1) default ' ' not null,
  oppoalln    char(1) default ' ' not null,
  oppoecgr    char(1) default ' ' not null,
  oppolabr    char(1) default ' ' not null,
  oppocomb    char(1) default ' ' not null,
  oppomedc    char(1) default ' ' not null,
  oppodrin    char(1) default ' ' not null,
  oppoflub    char(1) default ' ' not null,
  oppoxray    char(1) default ' ' not null,
  oppodiac    char(1) default ' ' not null,
  oppodent    char(3) default ' ' not null,
  oppovals    char(3) default ' ' not null,
  opposhav    char(1) default ' ' not null,
  oppourvd    char(8) default ' ' not null,
  oppointr    char(3) default ' ' not null,
  oppolabn    decimal(2,0) default 0 not null,
  oppouc01    char(3) default ' ' not null,
  oppouc02    char(3) default ' ' not null,
  oppouc03    char(3) default ' ' not null,
  oppouc04    char(3) default ' ' not null,
  oppouc05    char(3) default ' ' not null,
  oppouc06    char(3) default ' ' not null,
  oppouc07    char(3) default ' ' not null,
  oppouc08    char(3) default ' ' not null,
  oppouc09    char(3) default ' ' not null,
  oppouc10    char(3) default ' ' not null,
  oppouc11    char(3) default ' ' not null,
  oppouc12    char(3) default ' ' not null,
  oppouc13    char(3) default ' ' not null,
  oppouc14    char(3) default ' ' not null,
  oppouc15    char(3) default ' ' not null,
  oppouc16    char(3) default ' ' not null,
  oppouc17    char(3) default ' ' not null,
  oppouc18    char(3) default ' ' not null,
  oppouc19    char(3) default ' ' not null,
  oppouc20    char(3) default ' ' not null,
  oppouy01    char(1) default ' ' not null,
  oppouy02    char(1) default ' ' not null,
  oppouy03    char(1) default ' ' not null,
  oppouy04    char(1) default ' ' not null,
  oppouy05    char(1) default ' ' not null,
  oppouy06    char(1) default ' ' not null,
  oppouy07    char(1) default ' ' not null,
  oppouy08    char(1) default ' ' not null,
  oppouy09    char(1) default ' ' not null,
  oppouy10    char(1) default ' ' not null,
  oppout01    char(8) default ' ' not null,
  oppout02    char(8) default ' ' not null,
  oppout03    char(8) default ' ' not null,
  oppout04    char(8) default ' ' not null,
  oppout05    char(8) default ' ' not null,
  oppout06    char(8) default ' ' not null,
  oppout07    char(8) default ' ' not null,
  oppout08    char(8) default ' ' not null,
  oppout09    char(8) default ' ' not null,
  oppout10    char(8) default ' ' not null,
  oppouf01    decimal(6,0) default 0 not null,
  oppouf02    decimal(6,0) default 0 not null,
  oppouf03    decimal(6,0) default 0 not null,
  oppouf04    decimal(6,0) default 0 not null,
  oppouf05    decimal(6,0) default 0 not null,
  oppouf06    decimal(6,0) default 0 not null,
  oppouf07    decimal(6,0) default 0 not null,
  oppouf08    decimal(6,0) default 0 not null,
  oppouf09    decimal(6,0) default 0 not null,
  oppouf10    decimal(6,0) default 0 not null,
  oppoudr1    char(10) default ' ' not null,
  oppoudr2    char(10) default ' ' not null,
  oppoudr3    char(10) default ' ' not null,
  oppoudr4    char(10) default ' ' not null,
  oppoudr5    char(10) default ' ' not null,
  oppounr1    char(10) default ' ' not null,
  oppounr2    char(10) default ' ' not null,
  oppounr3    char(10) default ' ' not null,
  oppounr4    char(10) default ' ' not null,
  oppounr5    char(10) default ' ' not null,
  oppoud01    char(8) default ' ' not null,
  oppoud02    char(8) default ' ' not null,
  oppoud03    char(8) default ' ' not null,
  oppoud04    char(8) default ' ' not null,
  oppoud05    char(8) default ' ' not null,
  oppoud06    char(8) default ' ' not null,
  oppoud07    char(8) default ' ' not null,
  oppoud08    char(8) default ' ' not null,
  oppoud09    char(8) default ' ' not null,
  oppoud10    char(8) default ' ' not null,
  oppospar    char(50) default ' ' not null,
  lf          char(1)
);
create unique index oprpoca1 on oprpocaf
(
oppounid,
dopporty
);
create unique index oprpoca2 on oprpocaf
(
dopporty,
oppounid
);
revoke all on oprpocaf from public ; 
grant select on oprpocaf to public ; 
