create table opraudse
(
  opseaudd    char(8) default ' ' not null,
  opseaudt    char(8) default ' ' not null,
  opseaudp    char(2) default ' ' not null,
  opseaudr    char(1) default ' ' not null,
  opseauds    decimal(1,0) default 0 not null,
  opseaudo    char(4) default ' ' not null,
  opsedate    char(8) default ' ' not null,
  opsetime    char(5) default ' ' not null,
  opseclin    char(6) default ' ' not null,
  dopsesus    char(1) default ' ' not null,
  opseday     decimal(1,0) default 0 not null,
  opsebook    char(8) default ' ' not null,
  opseendt    char(5) default ' ' not null,
  opsedura    decimal(4,0) default 0 not null,
  opsebrkt    decimal(3,0) default 0 not null,
  opseprep    decimal(2,0) default 0 not null,
  opsetper    char(3) default ' ' not null,
  opsetype    char(3) default ' ' not null,
  opsethet    char(6) default ' ' not null,
  opsecord    char(6) default ' ' not null,
  opseanae    char(6) default ' ' not null,
  opsestat    decimal(1,0) default 0 not null,
  opsetimb    decimal(4,0) default 0 not null,
  opseacts    char(5) default ' ' not null,
  opseacte    char(5) default ' ' not null,
  opseactd    decimal(4,0) default 0 not null,
  opseover    char(3) default ' ' not null,
  opsedela    char(3) default ' ' not null,
  opsecanc    char(3) default ' ' not null,
  opsetyd1    char(3) default ' ' not null,
  opsetyd2    char(3) default ' ' not null,
  opsetyd3    char(3) default ' ' not null,
  opsetyd4    char(3) default ' ' not null,
  opsetyd5    char(3) default ' ' not null,
  opsetyd6    char(3) default ' ' not null,
  opsetyd7    char(3) default ' ' not null,
  opsetyd8    char(3) default ' ' not null,
  opsedcc1    char(6) default ' ' not null,
  opsedcc2    char(6) default ' ' not null,
  opsedcc3    char(6) default ' ' not null,
  opsedcc4    char(6) default ' ' not null,
  opsedcc5    char(6) default ' ' not null,
  opsedcc6    char(6) default ' ' not null,
  opsedcc7    char(6) default ' ' not null,
  opsedcc8    char(6) default ' ' not null,
  opselvd1    char(3) default ' ' not null,
  opselvd2    char(3) default ' ' not null,
  opselvd3    char(3) default ' ' not null,
  opselvd4    char(3) default ' ' not null,
  opselvd5    char(3) default ' ' not null,
  opselvd6    char(3) default ' ' not null,
  opselvd7    char(3) default ' ' not null,
  opselvd8    char(3) default ' ' not null,
  opsetyn1    char(3) default ' ' not null,
  opsetyn2    char(3) default ' ' not null,
  opsetyn3    char(3) default ' ' not null,
  opsetyn4    char(3) default ' ' not null,
  opsetyn5    char(3) default ' ' not null,
  opsetyn6    char(3) default ' ' not null,
  opsenuc1    char(6) default ' ' not null,
  opsenuc2    char(6) default ' ' not null,
  opsenuc3    char(6) default ' ' not null,
  opsenuc4    char(6) default ' ' not null,
  opsenuc5    char(6) default ' ' not null,
  opsenuc6    char(6) default ' ' not null,
  opseusr1    char(3) default ' ' not null,
  opseusr2    char(3) default ' ' not null,
  opseusr3    char(3) default ' ' not null,
  opseusr4    char(3) default ' ' not null,
  opsexdoc    char(6) default ' ' not null,
  opseendd    char(8) default ' ' not null,
  opseacds    char(8) default ' ' not null,
  opseacde    char(8) default ' ' not null,
  opsespi1    char(50) default ' ' not null,
  opsespi2    char(50) default ' ' not null,
  opsendlk    char(2) default ' ' not null,
  opsestyp    char(3) default ' ' not null,
  opsedgsi    char(3) default ' ' not null,
  opsefind    char(8) default ' ' not null,
  opsefint    char(8) default ' ' not null,
  opsehosp    char(3) default ' ' not null,
  opsecndt    char(8) default ' ' not null,
  opsecntm    char(8) default ' ' not null,
  opsecnid    char(10) default ' ' not null,
  opsedtcm    char(1) default ' ' not null,
  opseucdt    char(10) default ' ' not null,
  opsedcdt    char(8) default ' ' not null,
  opsetcdt    char(8) default ' ' not null,
  opseuudt    char(10) default ' ' not null,
  opsedudt    char(8) default ' ' not null,
  opsetudt    char(8) default ' ' not null,
  opseadts    char(1) default ' ' not null,
  opsespar    char(49) default ' ' not null,
  lf          char(1)
);
create index opraudse on opraudse
(
opseaudd,
opseaudt,
opseaudp,
opseaudr
);
revoke all on opraudse from public ; 
grant select on opraudse to public ; 
create table oprsesaf
(
  opsedate    char(8) default ' ' not null,
  opsetime    char(5) default ' ' not null,
  opseclin    char(6) default ' ' not null,
  dopsesus    char(1) default ' ' not null,
  opseday     decimal(1,0) default 0 not null,
  opsebook    char(8) default ' ' not null,
  opseendt    char(5) default ' ' not null,
  opsedura    decimal(4,0) default 0 not null,
  opsebrkt    decimal(3,0) default 0 not null,
  opseprep    decimal(2,0) default 0 not null,
  opsetper    char(3) default ' ' not null,
  opsetype    char(3) default ' ' not null,
  opsethet    char(6) default ' ' not null,
  opsecord    char(6) default ' ' not null,
  opseanae    char(6) default ' ' not null,
  opsestat    decimal(1,0) default 0 not null,
  opsetimb    decimal(4,0) default 0 not null,
  opseacts    char(5) default ' ' not null,
  opseacte    char(5) default ' ' not null,
  opseactd    decimal(4,0) default 0 not null,
  opseover    char(3) default ' ' not null,
  opsedela    char(3) default ' ' not null,
  opsecanc    char(3) default ' ' not null,
  opsetyd1    char(3) default ' ' not null,
  opsetyd2    char(3) default ' ' not null,
  opsetyd3    char(3) default ' ' not null,
  opsetyd4    char(3) default ' ' not null,
  opsetyd5    char(3) default ' ' not null,
  opsetyd6    char(3) default ' ' not null,
  opsetyd7    char(3) default ' ' not null,
  opsetyd8    char(3) default ' ' not null,
  opsedcc1    char(6) default ' ' not null,
  opsedcc2    char(6) default ' ' not null,
  opsedcc3    char(6) default ' ' not null,
  opsedcc4    char(6) default ' ' not null,
  opsedcc5    char(6) default ' ' not null,
  opsedcc6    char(6) default ' ' not null,
  opsedcc7    char(6) default ' ' not null,
  opsedcc8    char(6) default ' ' not null,
  opselvd1    char(3) default ' ' not null,
  opselvd2    char(3) default ' ' not null,
  opselvd3    char(3) default ' ' not null,
  opselvd4    char(3) default ' ' not null,
  opselvd5    char(3) default ' ' not null,
  opselvd6    char(3) default ' ' not null,
  opselvd7    char(3) default ' ' not null,
  opselvd8    char(3) default ' ' not null,
  opsetyn1    char(3) default ' ' not null,
  opsetyn2    char(3) default ' ' not null,
  opsetyn3    char(3) default ' ' not null,
  opsetyn4    char(3) default ' ' not null,
  opsetyn5    char(3) default ' ' not null,
  opsetyn6    char(3) default ' ' not null,
  opsenuc1    char(6) default ' ' not null,
  opsenuc2    char(6) default ' ' not null,
  opsenuc3    char(6) default ' ' not null,
  opsenuc4    char(6) default ' ' not null,
  opsenuc5    char(6) default ' ' not null,
  opsenuc6    char(6) default ' ' not null,
  opseusr1    char(3) default ' ' not null,
  opseusr2    char(3) default ' ' not null,
  opseusr3    char(3) default ' ' not null,
  opseusr4    char(3) default ' ' not null,
  opsexdoc    char(6) default ' ' not null,
  opseendd    char(8) default ' ' not null,
  opseacds    char(8) default ' ' not null,
  opseacde    char(8) default ' ' not null,
  opsespi1    char(50) default ' ' not null,
  opsespi2    char(50) default ' ' not null,
  opsendlk    char(2) default ' ' not null,
  opsestyp    char(3) default ' ' not null,
  opsedgsi    char(3) default ' ' not null,
  opsefind    char(8) default ' ' not null,
  opsefint    char(8) default ' ' not null,
  opsehosp    char(3) default ' ' not null,
  opsecndt    char(8) default ' ' not null,
  opsecntm    char(8) default ' ' not null,
  opsecnid    char(10) default ' ' not null,
  opsedtcm    char(1) default ' ' not null,
  opseucdt    char(10) default ' ' not null,
  opsedcdt    char(8) default ' ' not null,
  opsetcdt    char(8) default ' ' not null,
  opseuudt    char(10) default ' ' not null,
  opsedudt    char(8) default ' ' not null,
  opsetudt    char(8) default ' ' not null,
  opseadts    char(1) default ' ' not null,
  opsespar    char(49) default ' ' not null,
  lf          char(1)
);
create unique index oprsesa1 on oprsesaf
(
opsehosp,
opsedate,
opsetime,
opseclin
);
create unique index oprsesa2 on oprsesaf
(
opseclin,
opsehosp,
opsedate,
opsetime
);
create unique index oprsesa3 on oprsesaf
(
dopsesus,
opseclin,
opsehosp,
opsedate,
opsetime
);
create unique index oprsesa4 on oprsesaf
(
opsehosp,
opsedate,
opsethet,
opsetime,
opseclin
);
create unique index oprsesa5 on oprsesaf
(
opsetype,
opsehosp,
opsedate,
opsetime,
opsethet,
opseclin
);
create unique index oprsesa6 on oprsesaf
(
opseanae,
opsehosp,
opsedate,
opsetime,
opseclin
);
create unique index oprsesa7 on oprsesaf
(
opsedate,
opsetime,
opseclin,
opsehosp
);
revoke all on oprsesaf from public ; 
grant select on oprsesaf to public ; 
