create table opraudsg
(
  opsgaudd    char(8) default ' ' not null,
  opsgaudt    char(8) default ' ' not null,
  opsgaudp    char(2) default ' ' not null,
  opsgaudr    char(1) default ' ' not null,
  opsgauds    decimal(1,0) default 0 not null,
  opsgaudo    char(4) default ' ' not null,
  opsgunid    char(10) default ' ' not null,
  opsgtmno    char(1) default ' ' not null,
  opsgtips    char(8) default ' ' not null,
  opsgtidr    char(8) default ' ' not null,
  opsgtiss    char(8) default ' ' not null,
  opsgtise    char(8) default ' ' not null,
  opsgsgdl    char(3) default ' ' not null,
  opsgccnt    char(1) default ' ' not null,
  opsgcnto    char(6) default ' ' not null,
  opsgblos    char(3) default ' ' not null,
  opsgwcon    char(3) default ' ' not null,
  opsgwcm1    char(3) default ' ' not null,
  opsgwcm2    char(3) default ' ' not null,
  opsgwcm3    char(3) default ' ' not null,
  opsgicd1    char(15) default ' ' not null,
  opsgicd2    char(15) default ' ' not null,
  opsgicd3    char(15) default ' ' not null,
  opsgdst1    char(4) default ' ' not null,
  opsgdcd1    char(15) default ' ' not null,
  opsgdnm1    char(15) default ' ' not null,
  opsgdps1    char(20) default ' ' not null,
  opsgdck1    char(1) default ' ' not null,
  opsgdpr1    char(1) default ' ' not null,
  opsgdst2    char(4) default ' ' not null,
  opsgdcd2    char(15) default ' ' not null,
  opsgdnm2    char(15) default ' ' not null,
  opsgdps2    char(20) default ' ' not null,
  opsgdck2    char(1) default ' ' not null,
  opsgdpr2    char(1) default ' ' not null,
  opsgcat1    char(15) default ' ' not null,
  opsgcat2    char(15) default ' ' not null,
  opsgdrt1    char(15) default ' ' not null,
  opsgdrt2    char(15) default ' ' not null,
  opsgpack    char(15) default ' ' not null,
  opsgdrs1    char(15) default ' ' not null,
  opsgdrs2    char(15) default ' ' not null,
  opsgdrs3    char(15) default ' ' not null,
  opsgwdv1    char(15) default ' ' not null,
  opsgwdv2    char(15) default ' ' not null,
  opsgwdv3    char(15) default ' ' not null,
  opsgirig    char(15) default ' ' not null,
  opsgirgs    char(15) default ' ' not null,
  opsgirai    decimal(4,0) default 0 not null,
  opsgirao    decimal(4,0) default 0 not null,
  opsgclfs    char(2) default ' ' not null,
  opsginfc    char(1) default ' ' not null,
  opsgspmi    char(2) default ' ' not null,
  opsgspap    char(2) default ' ' not null,
  opsgothr    char(37) default ' ' not null,
  opsguc01    char(3) default ' ' not null,
  opsguc02    char(3) default ' ' not null,
  opsguc03    char(3) default ' ' not null,
  opsguc04    char(3) default ' ' not null,
  opsguc05    char(3) default ' ' not null,
  opsguc06    char(3) default ' ' not null,
  opsguc07    char(3) default ' ' not null,
  opsguc08    char(3) default ' ' not null,
  opsguc09    char(3) default ' ' not null,
  opsguc10    char(3) default ' ' not null,
  opsguc11    char(3) default ' ' not null,
  opsguc12    char(3) default ' ' not null,
  opsguc13    char(3) default ' ' not null,
  opsguc14    char(3) default ' ' not null,
  opsguc15    char(3) default ' ' not null,
  opsguc16    char(3) default ' ' not null,
  opsguc17    char(3) default ' ' not null,
  opsguc18    char(3) default ' ' not null,
  opsguc19    char(3) default ' ' not null,
  opsguc20    char(3) default ' ' not null,
  opsguy01    char(1) default ' ' not null,
  opsguy02    char(1) default ' ' not null,
  opsguy03    char(1) default ' ' not null,
  opsguy04    char(1) default ' ' not null,
  opsguy05    char(1) default ' ' not null,
  opsguy06    char(1) default ' ' not null,
  opsguy07    char(1) default ' ' not null,
  opsguy08    char(1) default ' ' not null,
  opsguy09    char(1) default ' ' not null,
  opsguy10    char(1) default ' ' not null,
  opsgut01    char(8) default ' ' not null,
  opsgut02    char(8) default ' ' not null,
  opsgut03    char(8) default ' ' not null,
  opsgut04    char(8) default ' ' not null,
  opsgut05    char(8) default ' ' not null,
  opsgut06    char(8) default ' ' not null,
  opsgut07    char(8) default ' ' not null,
  opsgut08    char(8) default ' ' not null,
  opsgut09    char(8) default ' ' not null,
  opsgut10    char(8) default ' ' not null,
  opsguf01    decimal(6,0) default 0 not null,
  opsguf02    decimal(6,0) default 0 not null,
  opsguf03    decimal(6,0) default 0 not null,
  opsguf04    decimal(6,0) default 0 not null,
  opsguf05    decimal(6,0) default 0 not null,
  opsguf06    decimal(6,0) default 0 not null,
  opsguf07    decimal(6,0) default 0 not null,
  opsguf08    decimal(6,0) default 0 not null,
  opsguf09    decimal(6,0) default 0 not null,
  opsguf10    decimal(6,0) default 0 not null,
  opsguthr    char(10) default ' ' not null,
  opsgides    char(60) default ' ' not null,
  opsgnoop    decimal(3,0) default 0 not null,
  opsgdt3u    char(6) default ' ' not null,
  opsgdt3c    char(15) default ' ' not null,
  opsgspar    char(28) default ' ' not null,
  lf          char(1)
);
create index opraudsg on opraudsg
(
opsgaudd,
opsgaudt,
opsgaudp,
opsgaudr
);
revoke all on opraudsg from public ; 
grant select on opraudsg to public ; 
create table oprsrgaf
(
  opsgunid    char(10) default ' ' not null,
  opsgtmno    char(1) default ' ' not null,
  opsgtips    char(8) default ' ' not null,
  opsgtidr    char(8) default ' ' not null,
  opsgtiss    char(8) default ' ' not null,
  opsgtise    char(8) default ' ' not null,
  opsgsgdl    char(3) default ' ' not null,
  opsgccnt    char(1) default ' ' not null,
  opsgcnto    char(6) default ' ' not null,
  opsgblos    char(3) default ' ' not null,
  opsgwcon    char(3) default ' ' not null,
  opsgwcm1    char(3) default ' ' not null,
  opsgwcm2    char(3) default ' ' not null,
  opsgwcm3    char(3) default ' ' not null,
  opsgicd1    char(15) default ' ' not null,
  opsgicd2    char(15) default ' ' not null,
  opsgicd3    char(15) default ' ' not null,
  opsgdst1    char(4) default ' ' not null,
  opsgdcd1    char(15) default ' ' not null,
  opsgdnm1    char(15) default ' ' not null,
  opsgdps1    char(20) default ' ' not null,
  opsgdck1    char(1) default ' ' not null,
  opsgdpr1    char(1) default ' ' not null,
  opsgdst2    char(4) default ' ' not null,
  opsgdcd2    char(15) default ' ' not null,
  opsgdnm2    char(15) default ' ' not null,
  opsgdps2    char(20) default ' ' not null,
  opsgdck2    char(1) default ' ' not null,
  opsgdpr2    char(1) default ' ' not null,
  opsgcat1    char(15) default ' ' not null,
  opsgcat2    char(15) default ' ' not null,
  opsgdrt1    char(15) default ' ' not null,
  opsgdrt2    char(15) default ' ' not null,
  opsgpack    char(15) default ' ' not null,
  opsgdrs1    char(15) default ' ' not null,
  opsgdrs2    char(15) default ' ' not null,
  opsgdrs3    char(15) default ' ' not null,
  opsgwdv1    char(15) default ' ' not null,
  opsgwdv2    char(15) default ' ' not null,
  opsgwdv3    char(15) default ' ' not null,
  opsgirig    char(15) default ' ' not null,
  opsgirgs    char(15) default ' ' not null,
  opsgirai    decimal(4,0) default 0 not null,
  opsgirao    decimal(4,0) default 0 not null,
  opsgclfs    char(2) default ' ' not null,
  opsginfc    char(1) default ' ' not null,
  opsgspmi    char(2) default ' ' not null,
  opsgspap    char(2) default ' ' not null,
  opsgothr    char(37) default ' ' not null,
  opsguc01    char(3) default ' ' not null,
  opsguc02    char(3) default ' ' not null,
  opsguc03    char(3) default ' ' not null,
  opsguc04    char(3) default ' ' not null,
  opsguc05    char(3) default ' ' not null,
  opsguc06    char(3) default ' ' not null,
  opsguc07    char(3) default ' ' not null,
  opsguc08    char(3) default ' ' not null,
  opsguc09    char(3) default ' ' not null,
  opsguc10    char(3) default ' ' not null,
  opsguc11    char(3) default ' ' not null,
  opsguc12    char(3) default ' ' not null,
  opsguc13    char(3) default ' ' not null,
  opsguc14    char(3) default ' ' not null,
  opsguc15    char(3) default ' ' not null,
  opsguc16    char(3) default ' ' not null,
  opsguc17    char(3) default ' ' not null,
  opsguc18    char(3) default ' ' not null,
  opsguc19    char(3) default ' ' not null,
  opsguc20    char(3) default ' ' not null,
  opsguy01    char(1) default ' ' not null,
  opsguy02    char(1) default ' ' not null,
  opsguy03    char(1) default ' ' not null,
  opsguy04    char(1) default ' ' not null,
  opsguy05    char(1) default ' ' not null,
  opsguy06    char(1) default ' ' not null,
  opsguy07    char(1) default ' ' not null,
  opsguy08    char(1) default ' ' not null,
  opsguy09    char(1) default ' ' not null,
  opsguy10    char(1) default ' ' not null,
  opsgut01    char(8) default ' ' not null,
  opsgut02    char(8) default ' ' not null,
  opsgut03    char(8) default ' ' not null,
  opsgut04    char(8) default ' ' not null,
  opsgut05    char(8) default ' ' not null,
  opsgut06    char(8) default ' ' not null,
  opsgut07    char(8) default ' ' not null,
  opsgut08    char(8) default ' ' not null,
  opsgut09    char(8) default ' ' not null,
  opsgut10    char(8) default ' ' not null,
  opsguf01    decimal(6,0) default 0 not null,
  opsguf02    decimal(6,0) default 0 not null,
  opsguf03    decimal(6,0) default 0 not null,
  opsguf04    decimal(6,0) default 0 not null,
  opsguf05    decimal(6,0) default 0 not null,
  opsguf06    decimal(6,0) default 0 not null,
  opsguf07    decimal(6,0) default 0 not null,
  opsguf08    decimal(6,0) default 0 not null,
  opsguf09    decimal(6,0) default 0 not null,
  opsguf10    decimal(6,0) default 0 not null,
  opsguthr    char(10) default ' ' not null,
  opsgides    char(60) default ' ' not null,
  opsgnoop    decimal(3,0) default 0 not null,
  opsgdt3u    char(6) default ' ' not null,
  opsgdt3c    char(15) default ' ' not null,
  opsgspar    char(28) default ' ' not null,
  lf          char(1)
);
create unique index oprsrga1 on oprsrgaf
(
opsgunid,
opsgtmno
);
revoke all on oprsrgaf from public ; 
grant select on oprsrgaf to public ; 
