create table outaudb1
(
  otbbaudd    char(8) default ' ' not null,
  otbbaudt    char(8) default ' ' not null,
  otbbaudp    char(2) default ' ' not null,
  otbbaudr    char(1) default ' ' not null,
  otbbauds    decimal(1,0) default 0 not null,
  otbbaudo    char(4) default ' ' not null,
  otbbsite    char(6) default ' ' not null,
  dobaoutn    char(8) default ' ' not null,
  obasrcr     char(3) default ' ' not null,
  obacomp     char(3) default ' ' not null,
  obaclass    char(3) default ' ' not null,
  obains      char(3) default ' ' not null,
  obaattn     char(3) default ' ' not null,
  obadoct     char(6) default ' ' not null,
  obacomm     char(25) default ' ' not null,
  otbbfund    char(6) default ' ' not null,
  otbbtble    char(8) default ' ' not null,
  dotbbpvi    char(3) default ' ' not null,
  otbbclal    char(3) default ' ' not null,
  otbbspar    char(4) default ' ' not null,
  obadate     char(8) default ' ' not null,
  obacat      char(3) default ' ' not null,
  obaprty     char(3) default ' ' not null,
  obarschd    char(3) default ' ' not null,
  obbport     char(2) default ' ' not null,
  obbbook     char(1) default ' ' not null,
  obbctyp     char(6) default ' ' not null,
  obousr1     char(3) default ' ' not null,
  obousr2     char(3) default ' ' not null,
  obousr3     char(3) default ' ' not null,
  obousr4     char(3) default ' ' not null,
  obaladmn    char(8) default ' ' not null,
  otbbdept    char(3) default ' ' not null,
  otbbtran    char(3) default ' ' not null,
  otbblngi    char(3) default ' ' not null,
  otbbtmfs    char(8) default ' ' not null,
  otbbtmbo    char(8) default ' ' not null,
  otbbgpfa    char(20) default ' ' not null,
  otbbecra    char(20) default ' ' not null,
  otbbrfgp    char(10) default ' ' not null,
  otbbgppc    char(10) default ' ' not null,
  otbbadcs    char(10) default ' ' not null,
  otbbcitm    char(5) default ' ' not null,
  otbbastm    char(5) default ' ' not null,
  otbbdptm    char(5) default ' ' not null,
  otbboutc    char(3) default ' ' not null,
  otbbsndl    char(1) default ' ' not null,
  otbbgppt    char(2) default ' ' not null,
  otbbdofr    char(3) default ' ' not null,
  otbboper    char(4) default ' ' not null,
  obousr5     char(3) default ' ' not null,
  obousr6     char(3) default ' ' not null,
  obousr7     char(3) default ' ' not null,
  obousr8     char(3) default ' ' not null,
  otbbrank    char(6) default ' ' not null,
  otbbspca    char(3) default ' ' not null,
  otbbcind    char(3) default ' ' not null,
  otbbflup    char(1) default ' ' not null,
  otbbscar    char(1) default ' ' not null,
  otbbgldt    char(8) default ' ' not null,
  otbbsngl    char(1) default ' ' not null,
  otbbnmds    char(3) default ' ' not null,
  otbbcart    char(3) default ' ' not null,
  otbbsrvd    char(3) default ' ' not null,
  otbbclhr    char(1) default ' ' not null,
  otbbcont    char(3) default ' ' not null,
  otbbtcod    char(3) default ' ' not null,
  otbbpurc    char(3) default ' ' not null,
  otbbbkov    char(3) default ' ' not null,
  otbbbkpr    char(3) default ' ' not null,
  otbbbkpm    char(2) default ' ' not null,
  otbbbkba    char(1) default ' ' not null,
  otbbrdat    char(8) default ' ' not null,
  otbbhcp1    char(10) default ' ' not null,
  otbbhcp2    char(10) default ' ' not null,
  otbbhcp3    char(10) default ' ' not null,
  otbbhcp4    char(10) default ' ' not null,
  otbbspr1    char(10) default ' ' not null,
  lf          char(1)
);
create index outaubb1 on outaudb1
(
otbbaudd,
otbbaudt,
otbbaudp,
otbbaudr
);
revoke all on outaudb1 from public ; 
grant select on outaudb1 to public ; 
create table outbb1af
(
  dobaoutn    char(8) default ' ' not null,
  obasrcr     char(3) default ' ' not null,
  obacomp     char(3) default ' ' not null,
  obaclass    char(3) default ' ' not null,
  obains      char(3) default ' ' not null,
  obaattn     char(3) default ' ' not null,
  obadoct     char(6) default ' ' not null,
  obacomm     char(25) default ' ' not null,
  otbbfund    char(6) default ' ' not null,
  otbbtble    char(8) default ' ' not null,
  dotbbpvi    char(3) default ' ' not null,
  otbbclal    char(3) default ' ' not null,
  otbbspar    char(4) default ' ' not null,
  obadate     char(8) default ' ' not null,
  obacat      char(3) default ' ' not null,
  obaprty     char(3) default ' ' not null,
  obarschd    char(3) default ' ' not null,
  obbport     char(2) default ' ' not null,
  obbbook     char(1) default ' ' not null,
  obbctyp     char(6) default ' ' not null,
  obousr1     char(3) default ' ' not null,
  obousr2     char(3) default ' ' not null,
  obousr3     char(3) default ' ' not null,
  obousr4     char(3) default ' ' not null,
  obaladmn    char(8) default ' ' not null,
  otbbdept    char(3) default ' ' not null,
  otbbtran    char(3) default ' ' not null,
  otbblngi    char(3) default ' ' not null,
  otbbtmfs    char(8) default ' ' not null,
  otbbtmbo    char(8) default ' ' not null,
  otbbgpfa    char(20) default ' ' not null,
  otbbecra    char(20) default ' ' not null,
  otbbrfgp    char(10) default ' ' not null,
  otbbgppc    char(10) default ' ' not null,
  otbbadcs    char(10) default ' ' not null,
  otbbcitm    char(5) default ' ' not null,
  otbbastm    char(5) default ' ' not null,
  otbbdptm    char(5) default ' ' not null,
  otbboutc    char(3) default ' ' not null,
  otbbsndl    char(1) default ' ' not null,
  otbbgppt    char(2) default ' ' not null,
  otbbdofr    char(3) default ' ' not null,
  otbboper    char(4) default ' ' not null,
  obousr5     char(3) default ' ' not null,
  obousr6     char(3) default ' ' not null,
  obousr7     char(3) default ' ' not null,
  obousr8     char(3) default ' ' not null,
  otbbrank    char(6) default ' ' not null,
  otbbspca    char(3) default ' ' not null,
  otbbcind    char(3) default ' ' not null,
  otbbflup    char(1) default ' ' not null,
  otbbscar    char(1) default ' ' not null,
  otbbgldt    char(8) default ' ' not null,
  otbbsngl    char(1) default ' ' not null,
  otbbnmds    char(3) default ' ' not null,
  otbbcart    char(3) default ' ' not null,
  otbbsrvd    char(3) default ' ' not null,
  otbbclhr    char(1) default ' ' not null,
  otbbcont    char(3) default ' ' not null,
  otbbtcod    char(3) default ' ' not null,
  otbbpurc    char(3) default ' ' not null,
  otbbbkov    char(3) default ' ' not null,
  otbbbkpr    char(3) default ' ' not null,
  otbbbkpm    char(2) default ' ' not null,
  otbbbkba    char(1) default ' ' not null,
  otbbrdat    char(8) default ' ' not null,
  otbbhcp1    char(10) default ' ' not null,
  otbbhcp2    char(10) default ' ' not null,
  otbbhcp3    char(10) default ' ' not null,
  otbbhcp4    char(10) default ' ' not null,
  otbbspr1    char(10) default ' ' not null,
  lf          char(1)
);
create unique index outbb1a1 on outbb1af
(
dobaoutn
);
create unique index outbb1a2 on outbb1af
(
obadate,
dobaoutn
);
revoke all on outbb1af from public ; 
grant select on outbb1af to public ; 
