create table outdemaf
(
  otdmurno    char(8) default ' ' not null,
  otdmadat    char(8) default ' ' not null,
  otdmatim    char(8) default ' ' not null,
  otdmtitl    char(4) default ' ' not null,
  otdmsnam    char(40) default ' ' not null,
  otdmfgnm    char(40) default ' ' not null,
  otdmsgnm    char(40) default ' ' not null,
  otdmgend    char(1) default ' ' not null,
  otdmbdat    char(8) default ' ' not null,
  otdmmsta    char(3) default ' ' not null,
  otdmmedn    char(10) default ' ' not null,
  otdmmedr    char(2) default ' ' not null,
  otdmmedv    char(8) default ' ' not null,
  otdmdved    char(8) default ' ' not null,
  otdmdvan    char(20) default ' ' not null,
  otdmdvac    char(3) default ' ' not null,
  otdmadd1    char(35) default ' ' not null,
  otdmadd2    char(35) default ' ' not null,
  otdmadd3    char(35) default ' ' not null,
  otdmadd4    char(35) default ' ' not null,
  otdmpost    char(8) default ' ' not null,
  otdmtelp    char(20) default ' ' not null,
  otdmtelw    char(20) default ' ' not null,
  otdmtelm    char(20) default ' ' not null,
  otdmemai    char(80) default ' ' not null,
  otdmdecd    char(8) default ' ' not null,
  otdmdety    char(3) default ' ' not null,
  otdmukdd    char(1) default ' ' not null,
  otdmc1ty    char(3) default ' ' not null,
  otdmc1tl    char(4) default ' ' not null,
  otdmc1sn    char(40) default ' ' not null,
  otdmc1g1    char(40) default ' ' not null,
  otdmc1g2    char(40) default ' ' not null,
  otdmc1a1    char(35) default ' ' not null,
  otdmc1a2    char(35) default ' ' not null,
  otdmc1a3    char(35) default ' ' not null,
  otdmc1a4    char(35) default ' ' not null,
  otdmc1pc    char(8) default ' ' not null,
  otdmc1tp    char(20) default ' ' not null,
  otdmc1tb    char(20) default ' ' not null,
  otdmc1tm    char(20) default ' ' not null,
  otdmc1rp    char(10) default ' ' not null,
  otdmc1em    char(80) default ' ' not null,
  otdmc2ty    char(3) default ' ' not null,
  otdmc2tl    char(4) default ' ' not null,
  otdmc2sn    char(40) default ' ' not null,
  otdmc2g1    char(40) default ' ' not null,
  otdmc2g2    char(40) default ' ' not null,
  otdmc2a1    char(35) default ' ' not null,
  otdmc2a2    char(35) default ' ' not null,
  otdmc2a3    char(35) default ' ' not null,
  otdmc2a4    char(35) default ' ' not null,
  otdmc2pc    char(8) default ' ' not null,
  otdmc2tp    char(20) default ' ' not null,
  otdmc2tb    char(20) default ' ' not null,
  otdmc2tm    char(20) default ' ' not null,
  otdmc2rp    char(10) default ' ' not null,
  otdmc2em    char(80) default ' ' not null,
  otdma1sn    char(30) default ' ' not null,
  otdma1fg    char(30) default ' ' not null,
  otdma1sg    char(30) default ' ' not null,
  otdma1ge    char(1) default ' ' not null,
  otdma1db    char(8) default ' ' not null,
  otdma2sn    char(30) default ' ' not null,
  otdma2fg    char(30) default ' ' not null,
  otdma2sg    char(30) default ' ' not null,
  otdma2ge    char(1) default ' ' not null,
  otdma2db    char(8) default ' ' not null,
  otdma3sn    char(30) default ' ' not null,
  otdma3fg    char(30) default ' ' not null,
  otdma3sg    char(30) default ' ' not null,
  otdma3ge    char(1) default ' ' not null,
  otdma3db    char(8) default ' ' not null,
  otdma4sn    char(30) default ' ' not null,
  otdma4fg    char(30) default ' ' not null,
  otdma4sg    char(30) default ' ' not null,
  otdma4ge    char(1) default ' ' not null,
  otdma4db    char(8) default ' ' not null,
  otdmsfed    char(8) default ' ' not null,
  otdmsfno    char(20) default ' ' not null,
  otdmsfct    char(3) default ' ' not null,
  otdmdvct    char(3) default ' ' not null,
  otdmcdat    char(8) default ' ' not null,
  otdmctim    char(8) default ' ' not null,
  otdmcuid    char(10) default ' ' not null,
  otdmudat    char(8) default ' ' not null,
  otdmutim    char(8) default ' ' not null,
  otdmuuid    char(10) default ' ' not null,
  otdmpmcn    char(3) default ' ' not null,
  otdmpmcr    char(3) default ' ' not null,
  otdmspar    char(44) default ' ' not null,
  lf          char(1)
);
create unique index outdema1 on outdemaf
(
otdmurno,
otdmadat,
otdmatim
);
revoke all on outdemaf from public ; 
grant select on outdemaf to public ; 
