create table outhedaf
(
  othesite    char(6) default ' ' not null,
  otheclin    char(6) default ' ' not null,
  othewday    char(1) default ' ' not null,
  othestrt    char(5) default ' ' not null,
  otheshno    char(2) default ' ' not null,
  othesdat    char(8) default ' ' not null,
  othedtcc    char(8) default ' ' not null,
  othecom1    char(40) default ' ' not null,
  othecom2    char(40) default ' ' not null,
  otheins1    char(40) default ' ' not null,
  otheins2    char(40) default ' ' not null,
  otheins3    char(40) default ' ' not null,
  othedurn    decimal(3,0) default 0 not null,
  othebfin    char(5) default ' ' not null,
  othesend    char(5) default ' ' not null,
  otheltyp    char(3) default ' ' not null,
  otheclse    char(6) default ' ' not null,
  othehosp    char(3) default ' ' not null,
  othelocn    char(4) default ' ' not null,
  othectyp    char(6) default ' ' not null,
  othecind    char(3) default ' ' not null,
  othegbok    char(1) default ' ' not null,
  otheadep    char(3) default ' ' not null,
  othecenc    char(1) default ' ' not null,
  othekdoc    char(1) default ' ' not null,
  othedefd    char(10) default ' ' not null,
  otheccar    char(1) default ' ' not null,
  othectrn    char(1) default ' ' not null,
  othendps    char(3) default ' ' not null,
  othecpmi    char(1) default ' ' not null,
  othecpag    char(1) default ' ' not null,
  othectel    char(20) default ' ' not null,
  othenmds    char(3) default ' ' not null,
  othecart    char(3) default ' ' not null,
  othesrvd    char(3) default ' ' not null,
  otheclhr    char(1) default ' ' not null,
  othemltd    char(1) default ' ' not null,
  othexpul    char(1) default ' ' not null,
  othemref    char(1) default ' ' not null,
  othehpio    char(20) default ' ' not null,
  othetcod    char(3) default ' ' not null,
  othetced    char(8) default ' ' not null,
  othehcli    char(20) default ' ' not null,
  othehcai    char(20) default ' ' not null,
  otheaopn    char(1) default ' ' not null,
  otheaofr    char(1) default ' ' not null,
  otheaowm    char(5) default ' ' not null,
  otheaaow    char(3) default ' ' not null,
  othedate    char(8) default ' ' not null,
  othehcp1    char(10) default ' ' not null,
  othehcp2    char(10) default ' ' not null,
  othehcp3    char(10) default ' ' not null,
  othehcp4    char(10) default ' ' not null,
  othepcod    char(9) default ' ' not null,
  othespar    char(41) default ' ' not null,
  lf          char(1)
);
create unique index outheda1 on outhedaf
(
othesite,
otheclin,
othewday,
othestrt,
otheshno,
othesdat
);
create unique index outheda2 on outhedaf
(
othesite,
othehosp,
otheclin,
othewday,
othestrt,
otheshno,
othesdat
);
revoke all on outhedaf from public ; 
grant select on outhedaf to public ; 
