create table outqmaaf
(
  dotqmmes    char(20) default ' ' not null,
  omasite     char(6) default ' ' not null,
  omaclin     char(6) default ' ' not null,
  omatyp      char(6) default ' ' not null,
  omaday      decimal(1,0) default 0 not null,
  omastart    char(5) default ' ' not null,
  omafin      char(5) default ' ' not null,
  omaend      char(5) default ' ' not null,
  omacind     char(3) default ' ' not null,
  omareg      char(1) default ' ' not null,
  omakdoc     char(1) default ' ' not null,
  omacom1     char(40) default ' ' not null,
  omacom2     char(40) default ' ' not null,
  omadurn     decimal(3,0) default 0 not null,
  omanewsl    decimal(1,0) default 0 not null,
  omaspcsl    decimal(1,0) default 0 not null,
  omastat     decimal(1,0) default 0 not null,
  omafreqm    char(5) default ' ' not null,
  domaseq     char(4) default ' ' not null,
  omalock     char(2) default ' ' not null,
  omafreqf    decimal(1,0) default 0 not null,
  omafreqy    char(52) default ' ' not null,
  omadate     char(8) default ' ' not null,
  otmaavis    char(1) default ' ' not null,
  otmastvt    char(1) default ' ' not null,
  otmasupx    char(1) default ' ' not null,
  otmaruse    char(1) default ' ' not null,
  otmadcmb    char(1) default ' ' not null,
  otmaixta    char(1) default ' ' not null,
  otmadefd    char(6) default ' ' not null,
  otmauatr    char(1) default ' ' not null,
  otmaddna    decimal(2,0) default 0 not null,
  otmandrp    decimal(2,0) default 0 not null,
  otmalptr    decimal(3,0) default 0 not null,
  otmalgpd    decimal(3,0) default 0 not null,
  otmalptd    decimal(3,0) default 0 not null,
  otmabklt    decimal(3,0) default 0 not null,
  otmaralt    decimal(3,0) default 0 not null,
  otmarslt    decimal(3,0) default 0 not null,
  otmaclse    char(6) default ' ' not null,
  otmahosp    char(3) default ' ' not null,
  otmacloc    char(30) default ' ' not null,
  otmawdcl    char(1) default ' ' not null,
  otmaward    char(3) default ' ' not null,
  otmaltyp    char(3) default ' ' not null,
  otmadfsl    char(1) default ' ' not null,
  otmadfgn    char(1) default ' ' not null,
  otmagrps    char(1) default ' ' not null,
  dotmasov    char(1) default ' ' not null,
  dotmanoo    char(2) default ' ' not null,
  dotmaslf    char(1) default ' ' not null,
  dotmaslr    char(1) default ' ' not null,
  otmasbkl    char(2) default ' ' not null,
  otmasapl    char(2) default ' ' not null,
  otmaspmm    char(2) default ' ' not null,
  otmasgpm    char(2) default ' ' not null,
  dotmalpp    char(3) default ' ' not null,
  dotmasrl    char(3) default ' ' not null,
  dotmanco    char(1) default ' ' not null,
  otmalocn    char(4) default ' ' not null,
  otmadtco    char(8) default ' ' not null,
  otmadtcc    char(8) default ' ' not null,
  otmains1    char(40) default ' ' not null,
  otmains2    char(40) default ' ' not null,
  otmains3    char(40) default ' ' not null,
  otmalser    char(3) default ' ' not null,
  otmaumci    char(1) default ' ' not null,
  otmaprov    char(10) default ' ' not null,
  otmambst    char(4) default ' ' not null,
  otmaroom    char(3) default ' ' not null,
  otmaledg    char(2) default ' ' not null,
  otmacctr    char(12) default ' ' not null,
  otmamprc    char(6) default ' ' not null,
  otmambsa    char(1) default ' ' not null,
  otmaldna    char(3) default ' ' not null,
  otmaadep    char(3) default ' ' not null,
  otmacenc    char(1) default ' ' not null,
  otmaccar    char(1) default ' ' not null,
  otmactrn    char(1) default ' ' not null,
  otmadpsl    char(3) default ' ' not null,
  otmacpmi    char(1) default ' ' not null,
  otmacpag    char(1) default ' ' not null,
  otmactel    char(20) default ' ' not null,
  otmanmds    char(3) default ' ' not null,
  otmacart    char(3) default ' ' not null,
  otmasrvd    char(3) default ' ' not null,
  otmaclhr    char(1) default ' ' not null,
  otmamltd    char(1) default ' ' not null,
  otmaxpul    char(1) default ' ' not null,
  otmatcod    char(3) default ' ' not null,
  otqmspar    char(97) default ' ' not null,
  lf          char(1)
);
create unique index outqmaa1 on outqmaaf
(
dotqmmes
);
revoke all on outqmaaf from public ; 
grant select on outqmaaf to public ; 
