create table outqueaf
(
  dotqumes    char(20) default ' ' not null,
  obasite     char(6) default ' ' not null,
  obaclin     char(6) default ' ' not null,
  obadate     char(8) default ' ' not null,
  obastrt     char(5) default ' ' not null,
  obaslot     decimal(3,0) default 0 not null,
  obatime     char(5) default ' ' not null,
  obactyp     char(6) default ' ' not null,
  obavisit    char(3) default ' ' not null,
  obaoutno    char(8) default ' ' not null,
  obasesst    char(3) default ' ' not null,
  obasrcr     char(3) default ' ' not null,
  obacomp     char(3) default ' ' not null,
  obaclass    char(3) default ' ' not null,
  obains      char(3) default ' ' not null,
  obaattn     char(3) default ' ' not null,
  obadoct     char(6) default ' ' not null,
  obacomm     char(25) default ' ' not null,
  otbbfund    char(6) default ' ' not null,
  otbbtble    char(8) default ' ' not null,
  otbbpvis    decimal(3,0) default 0 not null,
  otbbclal    char(3) default ' ' not null,
  otbbspar    char(4) default ' ' not null,
  obacat      char(3) default ' ' not null,
  obaprty     char(3) default ' ' not null,
  obarschd    char(3) default ' ' not null,
  obbbook     char(1) default ' ' not null,
  obousr1     char(3) default ' ' not null,
  obousr2     char(3) default ' ' not null,
  obousr3     char(3) default ' ' not null,
  obousr4     char(3) default ' ' not null,
  obaladmn    char(8) default ' ' not null,
  otbbdept    char(3) default ' ' not null,
  otbbtran    char(3) default ' ' not null,
  otbblngi    char(3) default ' ' not null,
  otbbtmfs    char(8) default ' ' not null,
  otbbtmbo    char(8) default ' ' not null,
  otbbgpfa    char(20) default ' ' not null,
  otbbecra    char(20) default ' ' not null,
  otbbrfgp    char(10) default ' ' not null,
  otbbgppc    char(10) default ' ' not null,
  otbbadcs    char(10) default ' ' not null,
  otbbcitm    char(5) default ' ' not null,
  otbbastm    char(5) default ' ' not null,
  otbbdptm    char(5) default ' ' not null,
  otbboutc    char(3) default ' ' not null,
  otbbsndl    char(1) default ' ' not null,
  otbbgppt    char(2) default ' ' not null,
  otbbdofr    char(3) default ' ' not null,
  obousr5     char(3) default ' ' not null,
  obousr6     char(3) default ' ' not null,
  obousr7     char(3) default ' ' not null,
  obousr8     char(3) default ' ' not null,
  otbbrank    char(6) default ' ' not null,
  otbbspca    char(3) default ' ' not null,
  otbbcind    char(3) default ' ' not null,
  otbbflup    char(1) default ' ' not null,
  otbbscar    char(1) default ' ' not null,
  otbbgldt    char(8) default ' ' not null,
  otbbsngl    char(1) default ' ' not null,
  otbbnmds    char(3) default ' ' not null,
  otbbcart    char(3) default ' ' not null,
  otbbsrvd    char(3) default ' ' not null,
  otbbclhr    char(1) default ' ' not null,
  otbbcont    char(3) default ' ' not null,
  otbbtcod    char(3) default ' ' not null,
  oprssite    char(6) default ' ' not null,
  oprsclin    char(6) default ' ' not null,
  oprsdate    char(8) default ' ' not null,
  oprsstrt    char(5) default ' ' not null,
  oprsslot    decimal(3,0) default 0 not null,
  oprstime    char(5) default ' ' not null,
  oprsoutn    char(8) default ' ' not null,
  oprsreas    char(3) default ' ' not null,
  oprsncli    char(6) default ' ' not null,
  oprsndat    char(8) default ' ' not null,
  oprsnstr    char(5) default ' ' not null,
  oprsnslo    decimal(3,0) default 0 not null,
  oprsntim    char(5) default ' ' not null,
  oprsnvis    char(3) default ' ' not null,
  oprsntyp    char(6) default ' ' not null,
  oprsvist    char(3) default ' ' not null,
  oprsctyp    char(6) default ' ' not null,
  opcnsite    char(6) default ' ' not null,
  opcnclin    char(6) default ' ' not null,
  opcndate    char(8) default ' ' not null,
  opcnstrt    char(5) default ' ' not null,
  opcnslot    decimal(3,0) default 0 not null,
  opcntime    char(5) default ' ' not null,
  opcnoutn    char(8) default ' ' not null,
  opcnreas    char(3) default ' ' not null,
  opcnvtyp    char(3) default ' ' not null,
  otmaltyp    char(3) default ' ' not null,
  obastat     decimal(1,0) default 0 not null,
  otbbpurc    char(3) default ' ' not null,
  otbbbkov    char(3) default ' ' not null,
  otbbbkpr    char(3) default ' ' not null,
  otbbbkpm    char(2) default ' ' not null,
  otbbbkba    char(1) default ' ' not null,
  otbbrdat    char(8) default ' ' not null,
  otthstat    char(3) default ' ' not null,
  otthrsit    char(255) default ' ' not null,
  otthrcod    char(10) default ' ' not null,
  otthradd    char(512) default ' ' not null,
  otthwurl    char(255) default ' ' not null,
  otthe164    char(20) default ' ' not null,
  otquspar    char(21) default ' ' not null,
  lf          char(1)
);
create unique index outquea1 on outqueaf
(
dotqumes
);
revoke all on outqueaf from public ; 
grant select on outqueaf to public ; 
