create table outrquaf
(
dotrqmes    char(20),
otrloutn    char(8),
otrlurno    char(8),
otrldate    char(8),
otrlrdoc    char(10),
otrlcons    char(6),
otrldept    char(3),
otrlprio    char(3),
otrldiag    char(50),
otrlusd1    char(3),
otrlusd2    char(3),
otrlusd3    char(3),
otrlusd4    char(3),
otrlbsit    char(6),
otrlbcli    char(6),
otrlbdte    char(8),
otrlbstr    char(5),
otrlbslt    char(3),
otrlrfgp    char(10),
otrlgppc    char(10),
otrlrqst    char(20),
otrlcdte    char(8),
otrlreas    char(3),
otrlspfc    char(3),
otrlcad1    char(35),
otrlcad2    char(35),
otrlcad3    char(35),
otrlcad4    char(35),
otrlcpc     char(8),
otrlecrn    char(20),
otrlgpfh    char(20),
otrlgppt    char(2),
otrloper    char(4),
otrlctyp    char(6),
otrlsite    char(6),
otrlsrce    char(3),
otrlrhcp    char(10),
otrldrec    char(8),
otrldpri    char(8),
otrlpurc    char(3),
otrltref    decimal(1,0),
otrlrank    char(6),
otrludat    char(8),
otrlutim    char(8),
otrluuid    char(10),
otrlcdat    char(8),
otrlctim    char(8),
otrlcuid    char(8),
otrlclam    char(3),
otrqspar    char(20),
lf          char(1)
);
create unique index outrqua1 on outrquaf
(
dotrqmes
);
revoke all on outrquaf from public ; 
grant select on outrquaf to public ; 
