create table patcrdaf
(
  dptcddad    char(8) default ' ' not null,
  dptcdcnr    char(8) default ' ' not null,
  ptcdadte    char(8) default ' ' not null,
  ptcdddte    char(8) default ' ' not null,
  ptcdtmrc    char(8) default ' ' not null,
  ptcdmtsp    char(8) default ' ' not null,
  ptcdukpr    decimal(1,0) default 0 not null,
  ptcdprmm    char(9) default ' ' not null,
  ptcdhtyp    char(9) default ' ' not null,
  ptcdmet1    char(9) default ' ' not null,
  ptcdmet2    char(9) default ' ' not null,
  ptcdmet3    char(9) default ' ' not null,
  ptcdlatr    char(3) default ' ' not null,
  ptcdstag    char(3) default ' ' not null,
  ptcdbt01    char(1) default ' ' not null,
  ptcdbt02    char(1) default ' ' not null,
  ptcdbt03    char(1) default ' ' not null,
  ptcdbt04    char(1) default ' ' not null,
  ptcdbt05    char(1) default ' ' not null,
  ptcdbt06    char(1) default ' ' not null,
  ptcdbt07    char(1) default ' ' not null,
  ptcdbt08    char(1) default ' ' not null,
  ptcdbt09    char(1) default ' ' not null,
  ptcdbt10    char(1) default ' ' not null,
  ptcdotdg    char(50) default ' ' not null,
  ptcdrflg    decimal(1,0) default 0 not null,
  ptcdpath    char(9) default ' ' not null,
  ptcddgpr    char(1) default ' ' not null,
  ptcdfcpr    char(250) default ' ' not null,
  ptcdbo01    char(1) default ' ' not null,
  ptcdbo02    char(1) default ' ' not null,
  ptcdbo03    char(1) default ' ' not null,
  ptcdbo04    char(1) default ' ' not null,
  ptcdbo05    char(1) default ' ' not null,
  ptcdbo06    char(1) default ' ' not null,
  ptcdbo07    char(1) default ' ' not null,
  ptcdbo08    char(1) default ' ' not null,
  ptcdbo09    char(1) default ' ' not null,
  ptcddgot    char(50) default ' ' not null,
  ptcdautp    decimal(1,0) default 0 not null,
  ptcdbrlw    decimal(5,3) default 0 not null,
  ptcdmlin    char(3) default ' ' not null,
  ptcdrplb    char(3) default ' ' not null,
  ptcdbtsz    decimal(5,3) default 0 not null,
  ptcdcklv    char(3) default ' ' not null,
  ptcdglsc    decimal(5,3) default 0 not null,
  ptcdcomm    char(50) default ' ' not null,
  ptcddtex    char(8) default ' ' not null,
  ptcddtrc    char(8) default ' ' not null,
  ptcdtmcr    char(8) default ' ' not null,
  ptcduscr    char(10) default ' ' not null,
  ptcddtup    char(8) default ' ' not null,
  ptcdtmup    char(8) default ' ' not null,
  ptcdusup    char(10) default ' ' not null,
  ptcdbsdg    char(3) default ' ' not null,
  ptcdestm    char(1) default ' ' not null,
  ptcdcelt    char(1) default ' ' not null,
  ptcddocc    char(10) default ' ' not null,
  ptcddocn    char(10) default ' ' not null,
  ptcdntdt    char(8) default ' ' not null,
  ptcdsnt1    char(1) default ' ' not null,
  ptcdsnt2    char(1) default ' ' not null,
  ptcdsnt3    char(1) default ' ' not null,
  ptcdbod1    char(1) default ' ' not null,
  ptcdbod2    char(1) default ' ' not null,
  ptcdbod3    char(1) default ' ' not null,
  ptcdbod4    char(1) default ' ' not null,
  ptcdbod5    char(1) default ' ' not null,
  ptcdbol5    char(10) default ' ' not null,
  ptcdbod6    char(1) default ' ' not null,
  ptcdbol6    char(10) default ' ' not null,
  ptcdbod7    char(1) default ' ' not null,
  ptcdbol7    char(10) default ' ' not null,
  ptcdgd01    char(1) default ' ' not null,
  ptcdgd02    char(1) default ' ' not null,
  ptcdgd03    char(1) default ' ' not null,
  ptcdgd04    char(1) default ' ' not null,
  ptcdgd05    char(1) default ' ' not null,
  ptcdgd06    char(1) default ' ' not null,
  ptcdgd07    char(1) default ' ' not null,
  ptcdgd08    char(1) default ' ' not null,
  ptcdgd09    char(1) default ' ' not null,
  ptcdplod    char(25) default ' ' not null,
  ptcdcod1    char(35) default ' ' not null,
  ptcdcod2    char(35) default ' ' not null,
  ptcdcsgt    char(10) default ' ' not null,
  ptcdcsgn    char(10) default ' ' not null,
  ptcdcsgm    char(10) default ' ' not null,
  ptcdcssg    char(10) default ' ' not null,
  ptcdcscm    char(10) default ' ' not null,
  ptcdtnon    char(1) default ' ' not null,
  ptcdtsur    char(1) default ' ' not null,
  ptcdtsdt    char(8) default ' ' not null,
  ptcdtrad    char(1) default ' ' not null,
  ptcdtrdt    char(8) default ' ' not null,
  ptcdtchm    char(1) default ' ' not null,
  ptcdtcdt    char(8) default ' ' not null,
  ptcdthor    char(1) default ' ' not null,
  ptcdthdt    char(8) default ' ' not null,
  ptcdtbio    char(1) default ' ' not null,
  ptcdtbdt    char(8) default ' ' not null,
  ptcdrldt    char(8) default ' ' not null,
  ptcdndcl    char(35) default ' ' not null,
  ptcdtsab    char(1) default ' ' not null,
  ptcdtoth    char(1) default ' ' not null,
  ptcdthos    char(35) default ' ' not null,
  ptcdrst1    char(1) default ' ' not null,
  ptcdrst2    char(1) default ' ' not null,
  ptcdrst3    char(1) default ' ' not null,
  ptcdrst4    char(1) default ' ' not null,
  ptcdrst5    char(1) default ' ' not null,
  ptcdsurb    char(45) default ' ' not null,
  ptcdstte    char(7) default ' ' not null,
  ptcdpost    char(8) default ' ' not null,
  ptcdmet4    char(9) default ' ' not null,
  ptcdmet5    char(9) default ' ' not null,
  ptcdmet6    char(9) default ' ' not null,
  ptcdecog    char(3) default ' ' not null,
  ptcdradi    char(3) default ' ' not null,
  ptcdsyst    char(3) default ' ' not null,
  ptcdscfl    char(1) default ' ' not null,
  ptcdcssy    char(3) default ' ' not null,
  ptcdbdia    char(3) default ' ' not null,
  ptcdspar    char(50) default ' ' not null,
  lf          char(1)
);
create unique index patcrda1 on patcrdaf
(
dptcddad,
ptcdprmm,
dptcdcnr
);
create unique index patcrda2 on patcrdaf
(
ptcddtex,
dptcddad,
ptcdprmm,
dptcdcnr
);
create unique index patcrda3 on patcrdaf
(
ptcddtrc,
ptcdtmcr,
dptcddad,
ptcdprmm,
dptcdcnr
);
create unique index patcrda4 on patcrdaf
(
ptcddtup,
ptcdtmup,
dptcddad,
ptcdprmm,
dptcdcnr
);
revoke all on patcrdaf from public ; 
grant select on patcrdaf to public ; 
