create table patdo1af
(
  dcode       char(6) default ' ' not null,
  dtitl       char(9) default ' ' not null,
  dgname      char(25) default ' ' not null,
  dsname      char(20) default ' ' not null,
  drtype      char(3) default ' ' not null,
  drname      char(25) default ' ' not null,
  dsadd1      char(35) default ' ' not null,
  dsadd2      char(35) default ' ' not null,
  dsadd3      char(35) default ' ' not null,
  dsadd4      char(35) default ' ' not null,
  dspost      char(8) default ' ' not null,
  ptdoseml    char(80) default ' ' not null,
  dteles      char(20) default ' ' not null,
  dtelep      char(20) default ' ' not null,
  dpager      char(20) default ' ' not null,
  dassoc1     char(25) default ' ' not null,
  dassoc2     char(25) default ' ' not null,
  dassoc3     char(25) default ' ' not null,
  dassoc4     char(25) default ' ' not null,
  dassoc5     char(25) default ' ' not null,
  dprov       char(10) default ' ' not null,
  dteleh      char(20) default ' ' not null,
  dhadd1      char(35) default ' ' not null,
  dhadd2      char(35) default ' ' not null,
  dhadd3      char(35) default ' ' not null,
  dhadd4      char(35) default ' ' not null,
  dhpost      char(8) default ' ' not null,
  ptdoheml    char(80) default ' ' not null,
  dafirst     char(8) default ' ' not null,
  dalast      char(8) default ' ' not null,
  dayears     decimal(2,0) default 0 not null,
  daccred     char(3) default ' ' not null,
  drtype2     char(3) default ' ' not null,
  drtype3     char(3) default ' ' not null,
  drtype4     char(3) default ' ' not null,
  drtype5     char(3) default ' ' not null,
  dfspare     char(2) default ' ' not null,
  dbirth      char(8) default ' ' not null,
  dhcscod     decimal(3,0) default 0 not null,
  dalevel     char(3) default ' ' not null,
  drstat      decimal(1,0) default 0 not null,
  ptdofaxn    char(12) default ' ' not null,
  ptdohfax    char(12) default ' ' not null,
  ptdomobl    char(12) default ' ' not null,
  ptdoglcc    char(5) default ' ' not null,
  ptdowhdp    char(6) default ' ' not null,
  ptdomreg    char(10) default ' ' not null,
  ptdonhsn    char(10) default ' ' not null,
  dlupddte    char(8) default ' ' not null,
  dlupdtme    char(8) default ' ' not null,
  ptdoudf1    char(3) default ' ' not null,
  ptdoudf2    char(3) default ' ' not null,
  ptdoudf3    char(3) default ' ' not null,
  ptdoudf4    char(3) default ' ' not null,
  ptdoudf5    char(3) default ' ' not null,
  ptdoinsc    char(6) default ' ' not null,
  ptdoinsn    char(20) default ' ' not null,
  ptdoinsf    char(8) default ' ' not null,
  ptdoinst    char(8) default ' ' not null,
  ptdoregn    char(20) default ' ' not null,
  ptdoregf    char(8) default ' ' not null,
  ptdoregt    char(8) default ' ' not null,
  ptdovisa    char(8) default ' ' not null,
  ptdocomt    char(3) default ' ' not null,
  ptdopref    char(30) default ' ' not null,
  ptdoabnn    char(11) default ' ' not null,
  ptdodina    char(8) default ' ' not null,
  ptdodact    char(8) default ' ' not null,
  ptdodaco    char(8) default ' ' not null,
  ptdopro2    char(10) default ' ' not null,
  ptdopro3    char(10) default ' ' not null,
  ptdopro4    char(10) default ' ' not null,
  ptdopro5    char(10) default ' ' not null,
  ptdosdat    char(8) default ' ' not null,
  ptdoedat    char(8) default ' ' not null,
  ptdoaupd    char(1) default ' ' not null,
  ptdohoss    char(1) default ' ' not null,
  ptdoexml    char(1) default ' ' not null,
  ptdodeac    char(8) default ' ' not null,
  ptdoahc1    char(3) default ' ' not null,
  ptdoahc2    char(3) default ' ' not null,
  ptdoahc3    char(3) default ' ' not null,
  daspare     char(50) default ' ' not null,
  lf          char(1)
);
create unique index patdo1a1 on patdo1af
(
dcode
);
create unique index patdo1a2 on patdo1af
(
dsname,
dcode
);
create unique index patdo1a3 on patdo1af
(
dalevel,
dsname,
dcode
);
revoke all on patdo1af from public ; 
grant select on patdo1af to public ; 
