create table patex101
(
  dptxaadm    char(8) default ' ' not null,
  ptxaadat    char(8) default ' ' not null,
  ptxaddat    char(8) default ' ' not null,
  ptxadayc    decimal(1,0) default 0 not null,
  ptxaplos    decimal(4,0) default 0 not null,
  ptxaalos    decimal(4,0) default 0 not null,
  ptxaplve    decimal(4,0) default 0 not null,
  ptxaalve    decimal(4,0) default 0 not null,
  ptxaawrd    char(3) default ' ' not null,
  ptxaabed    char(3) default ' ' not null,
  ptxaswrd    char(3) default ' ' not null,
  ptxasbed    char(3) default ' ' not null,
  ptxadwrd    char(3) default ' ' not null,
  ptxadbed    char(3) default ' ' not null,
  ptxaatyp    char(3) default ' ' not null,
  ptxastyp    char(3) default ' ' not null,
  ptxadtyp    char(3) default ' ' not null,
  ptxasex     char(1) default ' ' not null,
  ptxapost    char(8) default ' ' not null,
  ptxamlga    char(4) default ' ' not null,
  ptxaplga    char(4) default ' ' not null,
  ptxarelg    char(3) default ' ' not null,
  ptxacont    char(3) default ' ' not null,
  ptxaresi    char(3) default ' ' not null,
  ptxamstt    char(3) default ' ' not null,
  ptxaaagd    decimal(5,0) default 0 not null,
  ptxaaagm    decimal(4,0) default 0 not null,
  ptxaaagy    decimal(3,0) default 0 not null,
  ptxasagd    decimal(5,0) default 0 not null,
  ptxasagm    decimal(4,0) default 0 not null,
  ptxasagy    decimal(3,0) default 0 not null,
  ptxadagd    decimal(5,0) default 0 not null,
  ptxadagm    decimal(4,0) default 0 not null,
  ptxadagy    decimal(3,0) default 0 not null,
  ptxapus1    char(3) default ' ' not null,
  ptxapus2    char(3) default ' ' not null,
  ptxapus3    char(3) default ' ' not null,
  ptxapus4    char(3) default ' ' not null,
  ptxapus5    char(3) default ' ' not null,
  ptxapus6    char(3) default ' ' not null,
  ptxapyn1    char(1) default ' ' not null,
  ptxapyn2    char(1) default ' ' not null,
  ptxapyn3    char(1) default ' ' not null,
  ptxadcse    char(1) default ' ' not null,
  ptxaddth    char(8) default ' ' not null,
  ptxabadd    char(1) default ' ' not null,
  ptxaaadc    char(6) default ' ' not null,
  ptxaaadt    char(3) default ' ' not null,
  ptxasadc    char(6) default ' ' not null,
  ptxasadt    char(3) default ' ' not null,
  ptxadadc    char(6) default ' ' not null,
  ptxadadt    char(3) default ' ' not null,
  ptxaardc    char(6) default ' ' not null,
  ptxaardt    char(3) default ' ' not null,
  ptxaatdc    char(6) default ' ' not null,
  ptxaatdt    char(6) default ' ' not null,
  ptxasour    char(3) default ' ' not null,
  ptxaahos    char(5) default ' ' not null,
  ptxaclmc    char(3) default ' ' not null,
  ptxadiet    char(3) default ' ' not null,
  ptxaacls    char(3) default ' ' not null,
  ptxaacre    char(3) default ' ' not null,
  ptxascre    char(3) default ' ' not null,
  ptxadcre    char(3) default ' ' not null,
  ptxaadpt    char(3) default ' ' not null,
  ptxasdpt    char(3) default ' ' not null,
  ptxaddpt    char(3) default ' ' not null,
  ptxafund    char(6) default ' ' not null,
  ptxaftbl    char(8) default ' ' not null,
  ptxaaus1    char(3) default ' ' not null,
  ptxaaus2    char(3) default ' ' not null,
  ptxaaus3    char(3) default ' ' not null,
  ptxaaus4    char(3) default ' ' not null,
  ptxaaus5    char(3) default ' ' not null,
  ptxaaus6    char(3) default ' ' not null,
  ptxaaus7    char(3) default ' ' not null,
  ptxaadia    char(9) default ' ' not null,
  ptxaddia    char(9) default ' ' not null,
  ptxadstt    char(3) default ' ' not null,
  ptxaddst    char(3) default ' ' not null,
  ptxadhos    char(5) default ' ' not null,
  ptxadus1    char(3) default ' ' not null,
  ptxadus2    char(3) default ' ' not null,
  ptxadus3    char(3) default ' ' not null,
  ptxadus4    char(3) default ' ' not null,
  ptxadus5    char(3) default ' ' not null,
  ptxadrgc    char(6) default ' ' not null,
  ptxamdcc    char(5) default ' ' not null,
  ptxaopid    char(10) default ' ' not null,
  ptxarloc    char(3) default ' ' not null,
  ptxaabrg    char(3) default ' ' not null,
  ptxacadm    char(3) default ' ' not null,
  ptxairad    char(3) default ' ' not null,
  ptxaidus    char(3) default ' ' not null,
  ptxamhls    char(3) default ' ' not null,
  ptxaasut    char(3) default ' ' not null,
  ptxaelps    char(3) default ' ' not null,
  ptxaempl    char(3) default ' ' not null,
  ptxaread    char(3) default ' ' not null,
  ptxaudin    char(3) default ' ' not null,
  ptxaurea    char(3) default ' ' not null,
  ptxauvth    char(3) default ' ' not null,
  ptxaplan    char(3) default ' ' not null,
  ptxaspre    char(19) default ' ' not null,
  lf          char(1)
);
create unique index patex101 on patex101
(
dptxaadm
);
revoke all on patex101 from public ; 
grant select on patex101 to public ; 

create table patex102
(
  dptxaadm    char(8) default ' ' not null,
  ptxaadat    char(8) default ' ' not null,
  ptxaddat    char(8) default ' ' not null,
  ptxadayc    decimal(1,0) default 0 not null,
  ptxaplos    decimal(4,0) default 0 not null,
  ptxaalos    decimal(4,0) default 0 not null,
  ptxaplve    decimal(4,0) default 0 not null,
  ptxaalve    decimal(4,0) default 0 not null,
  ptxaawrd    char(3) default ' ' not null,
  ptxaabed    char(3) default ' ' not null,
  ptxaswrd    char(3) default ' ' not null,
  ptxasbed    char(3) default ' ' not null,
  ptxadwrd    char(3) default ' ' not null,
  ptxadbed    char(3) default ' ' not null,
  ptxaatyp    char(3) default ' ' not null,
  ptxastyp    char(3) default ' ' not null,
  ptxadtyp    char(3) default ' ' not null,
  ptxasex     char(1) default ' ' not null,
  ptxapost    char(8) default ' ' not null,
  ptxamlga    char(4) default ' ' not null,
  ptxaplga    char(4) default ' ' not null,
  ptxarelg    char(3) default ' ' not null,
  ptxacont    char(3) default ' ' not null,
  ptxaresi    char(3) default ' ' not null,
  ptxamstt    char(3) default ' ' not null,
  ptxaaagd    decimal(5,0) default 0 not null,
  ptxaaagm    decimal(4,0) default 0 not null,
  ptxaaagy    decimal(3,0) default 0 not null,
  ptxasagd    decimal(5,0) default 0 not null,
  ptxasagm    decimal(4,0) default 0 not null,
  ptxasagy    decimal(3,0) default 0 not null,
  ptxadagd    decimal(5,0) default 0 not null,
  ptxadagm    decimal(4,0) default 0 not null,
  ptxadagy    decimal(3,0) default 0 not null,
  ptxapus1    char(3) default ' ' not null,
  ptxapus2    char(3) default ' ' not null,
  ptxapus3    char(3) default ' ' not null,
  ptxapus4    char(3) default ' ' not null,
  ptxapus5    char(3) default ' ' not null,
  ptxapus6    char(3) default ' ' not null,
  ptxapyn1    char(1) default ' ' not null,
  ptxapyn2    char(1) default ' ' not null,
  ptxapyn3    char(1) default ' ' not null,
  ptxadcse    char(1) default ' ' not null,
  ptxaddth    char(8) default ' ' not null,
  ptxabadd    char(1) default ' ' not null,
  ptxaaadc    char(6) default ' ' not null,
  ptxaaadt    char(3) default ' ' not null,
  ptxasadc    char(6) default ' ' not null,
  ptxasadt    char(3) default ' ' not null,
  ptxadadc    char(6) default ' ' not null,
  ptxadadt    char(3) default ' ' not null,
  ptxaardc    char(6) default ' ' not null,
  ptxaardt    char(3) default ' ' not null,
  ptxaatdc    char(6) default ' ' not null,
  ptxaatdt    char(6) default ' ' not null,
  ptxasour    char(3) default ' ' not null,
  ptxaahos    char(5) default ' ' not null,
  ptxaclmc    char(3) default ' ' not null,
  ptxadiet    char(3) default ' ' not null,
  ptxaacls    char(3) default ' ' not null,
  ptxaacre    char(3) default ' ' not null,
  ptxascre    char(3) default ' ' not null,
  ptxadcre    char(3) default ' ' not null,
  ptxaadpt    char(3) default ' ' not null,
  ptxasdpt    char(3) default ' ' not null,
  ptxaddpt    char(3) default ' ' not null,
  ptxafund    char(6) default ' ' not null,
  ptxaftbl    char(8) default ' ' not null,
  ptxaaus1    char(3) default ' ' not null,
  ptxaaus2    char(3) default ' ' not null,
  ptxaaus3    char(3) default ' ' not null,
  ptxaaus4    char(3) default ' ' not null,
  ptxaaus5    char(3) default ' ' not null,
  ptxaaus6    char(3) default ' ' not null,
  ptxaaus7    char(3) default ' ' not null,
  ptxaadia    char(9) default ' ' not null,
  ptxaddia    char(9) default ' ' not null,
  ptxadstt    char(3) default ' ' not null,
  ptxaddst    char(3) default ' ' not null,
  ptxadhos    char(5) default ' ' not null,
  ptxadus1    char(3) default ' ' not null,
  ptxadus2    char(3) default ' ' not null,
  ptxadus3    char(3) default ' ' not null,
  ptxadus4    char(3) default ' ' not null,
  ptxadus5    char(3) default ' ' not null,
  ptxadrgc    char(6) default ' ' not null,
  ptxamdcc    char(5) default ' ' not null,
  ptxaopid    char(10) default ' ' not null,
  ptxarloc    char(3) default ' ' not null,
  ptxaabrg    char(3) default ' ' not null,
  ptxacadm    char(3) default ' ' not null,
  ptxairad    char(3) default ' ' not null,
  ptxaidus    char(3) default ' ' not null,
  ptxamhls    char(3) default ' ' not null,
  ptxaasut    char(3) default ' ' not null,
  ptxaelps    char(3) default ' ' not null,
  ptxaempl    char(3) default ' ' not null,
  ptxaread    char(3) default ' ' not null,
  ptxaudin    char(3) default ' ' not null,
  ptxaurea    char(3) default ' ' not null,
  ptxauvth    char(3) default ' ' not null,
  ptxaplan    char(3) default ' ' not null,
  ptxaspre    char(19) default ' ' not null,
  lf          char(1)
);
create unique index patex102 on patex102
(
dptxaadm
);
revoke all on patex102 from public ;
grant select on patex102 to public ;

create table patex103
(
  dptxaadm    char(8) default ' ' not null,
  ptxaadat    char(8) default ' ' not null,
  ptxaddat    char(8) default ' ' not null,
  ptxadayc    decimal(1,0) default 0 not null,
  ptxaplos    decimal(4,0) default 0 not null,
  ptxaalos    decimal(4,0) default 0 not null,
  ptxaplve    decimal(4,0) default 0 not null,
  ptxaalve    decimal(4,0) default 0 not null,
  ptxaawrd    char(3) default ' ' not null,
  ptxaabed    char(3) default ' ' not null,
  ptxaswrd    char(3) default ' ' not null,
  ptxasbed    char(3) default ' ' not null,
  ptxadwrd    char(3) default ' ' not null,
  ptxadbed    char(3) default ' ' not null,
  ptxaatyp    char(3) default ' ' not null,
  ptxastyp    char(3) default ' ' not null,
  ptxadtyp    char(3) default ' ' not null,
  ptxasex     char(1) default ' ' not null,
  ptxapost    char(8) default ' ' not null,
  ptxamlga    char(4) default ' ' not null,
  ptxaplga    char(4) default ' ' not null,
  ptxarelg    char(3) default ' ' not null,
  ptxacont    char(3) default ' ' not null,
  ptxaresi    char(3) default ' ' not null,
  ptxamstt    char(3) default ' ' not null,
  ptxaaagd    decimal(5,0) default 0 not null,
  ptxaaagm    decimal(4,0) default 0 not null,
  ptxaaagy    decimal(3,0) default 0 not null,
  ptxasagd    decimal(5,0) default 0 not null,
  ptxasagm    decimal(4,0) default 0 not null,
  ptxasagy    decimal(3,0) default 0 not null,
  ptxadagd    decimal(5,0) default 0 not null,
  ptxadagm    decimal(4,0) default 0 not null,
  ptxadagy    decimal(3,0) default 0 not null,
  ptxapus1    char(3) default ' ' not null,
  ptxapus2    char(3) default ' ' not null,
  ptxapus3    char(3) default ' ' not null,
  ptxapus4    char(3) default ' ' not null,
  ptxapus5    char(3) default ' ' not null,
  ptxapus6    char(3) default ' ' not null,
  ptxapyn1    char(1) default ' ' not null,
  ptxapyn2    char(1) default ' ' not null,
  ptxapyn3    char(1) default ' ' not null,
  ptxadcse    char(1) default ' ' not null,
  ptxaddth    char(8) default ' ' not null,
  ptxabadd    char(1) default ' ' not null,
  ptxaaadc    char(6) default ' ' not null,
  ptxaaadt    char(3) default ' ' not null,
  ptxasadc    char(6) default ' ' not null,
  ptxasadt    char(3) default ' ' not null,
  ptxadadc    char(6) default ' ' not null,
  ptxadadt    char(3) default ' ' not null,
  ptxaardc    char(6) default ' ' not null,
  ptxaardt    char(3) default ' ' not null,
  ptxaatdc    char(6) default ' ' not null,
  ptxaatdt    char(6) default ' ' not null,
  ptxasour    char(3) default ' ' not null,
  ptxaahos    char(5) default ' ' not null,
  ptxaclmc    char(3) default ' ' not null,
  ptxadiet    char(3) default ' ' not null,
  ptxaacls    char(3) default ' ' not null,
  ptxaacre    char(3) default ' ' not null,
  ptxascre    char(3) default ' ' not null,
  ptxadcre    char(3) default ' ' not null,
  ptxaadpt    char(3) default ' ' not null,
  ptxasdpt    char(3) default ' ' not null,
  ptxaddpt    char(3) default ' ' not null,
  ptxafund    char(6) default ' ' not null,
  ptxaftbl    char(8) default ' ' not null,
  ptxaaus1    char(3) default ' ' not null,
  ptxaaus2    char(3) default ' ' not null,
  ptxaaus3    char(3) default ' ' not null,
  ptxaaus4    char(3) default ' ' not null,
  ptxaaus5    char(3) default ' ' not null,
  ptxaaus6    char(3) default ' ' not null,
  ptxaaus7    char(3) default ' ' not null,
  ptxaadia    char(9) default ' ' not null,
  ptxaddia    char(9) default ' ' not null,
  ptxadstt    char(3) default ' ' not null,
  ptxaddst    char(3) default ' ' not null,
  ptxadhos    char(5) default ' ' not null,
  ptxadus1    char(3) default ' ' not null,
  ptxadus2    char(3) default ' ' not null,
  ptxadus3    char(3) default ' ' not null,
  ptxadus4    char(3) default ' ' not null,
  ptxadus5    char(3) default ' ' not null,
  ptxadrgc    char(6) default ' ' not null,
  ptxamdcc    char(5) default ' ' not null,
  ptxaopid    char(10) default ' ' not null,
  ptxarloc    char(3) default ' ' not null,
  ptxaabrg    char(3) default ' ' not null,
  ptxacadm    char(3) default ' ' not null,
  ptxairad    char(3) default ' ' not null,
  ptxaidus    char(3) default ' ' not null,
  ptxamhls    char(3) default ' ' not null,
  ptxaasut    char(3) default ' ' not null,
  ptxaelps    char(3) default ' ' not null,
  ptxaempl    char(3) default ' ' not null,
  ptxaread    char(3) default ' ' not null,
  ptxaudin    char(3) default ' ' not null,
  ptxaurea    char(3) default ' ' not null,
  ptxauvth    char(3) default ' ' not null,
  ptxaplan    char(3) default ' ' not null,
  ptxaspre    char(19) default ' ' not null,
  lf          char(1)
);
create unique index patex103 on patex103
(
dptxaadm
);
revoke all on patex103 from public ;
grant select on patex103 to public ;

create table patex104
(
  dptxaadm    char(8) default ' ' not null,
  ptxaadat    char(8) default ' ' not null,
  ptxaddat    char(8) default ' ' not null,
  ptxadayc    decimal(1,0) default 0 not null,
  ptxaplos    decimal(4,0) default 0 not null,
  ptxaalos    decimal(4,0) default 0 not null,
  ptxaplve    decimal(4,0) default 0 not null,
  ptxaalve    decimal(4,0) default 0 not null,
  ptxaawrd    char(3) default ' ' not null,
  ptxaabed    char(3) default ' ' not null,
  ptxaswrd    char(3) default ' ' not null,
  ptxasbed    char(3) default ' ' not null,
  ptxadwrd    char(3) default ' ' not null,
  ptxadbed    char(3) default ' ' not null,
  ptxaatyp    char(3) default ' ' not null,
  ptxastyp    char(3) default ' ' not null,
  ptxadtyp    char(3) default ' ' not null,
  ptxasex     char(1) default ' ' not null,
  ptxapost    char(8) default ' ' not null,
  ptxamlga    char(4) default ' ' not null,
  ptxaplga    char(4) default ' ' not null,
  ptxarelg    char(3) default ' ' not null,
  ptxacont    char(3) default ' ' not null,
  ptxaresi    char(3) default ' ' not null,
  ptxamstt    char(3) default ' ' not null,
  ptxaaagd    decimal(5,0) default 0 not null,
  ptxaaagm    decimal(4,0) default 0 not null,
  ptxaaagy    decimal(3,0) default 0 not null,
  ptxasagd    decimal(5,0) default 0 not null,
  ptxasagm    decimal(4,0) default 0 not null,
  ptxasagy    decimal(3,0) default 0 not null,
  ptxadagd    decimal(5,0) default 0 not null,
  ptxadagm    decimal(4,0) default 0 not null,
  ptxadagy    decimal(3,0) default 0 not null,
  ptxapus1    char(3) default ' ' not null,
  ptxapus2    char(3) default ' ' not null,
  ptxapus3    char(3) default ' ' not null,
  ptxapus4    char(3) default ' ' not null,
  ptxapus5    char(3) default ' ' not null,
  ptxapus6    char(3) default ' ' not null,
  ptxapyn1    char(1) default ' ' not null,
  ptxapyn2    char(1) default ' ' not null,
  ptxapyn3    char(1) default ' ' not null,
  ptxadcse    char(1) default ' ' not null,
  ptxaddth    char(8) default ' ' not null,
  ptxabadd    char(1) default ' ' not null,
  ptxaaadc    char(6) default ' ' not null,
  ptxaaadt    char(3) default ' ' not null,
  ptxasadc    char(6) default ' ' not null,
  ptxasadt    char(3) default ' ' not null,
  ptxadadc    char(6) default ' ' not null,
  ptxadadt    char(3) default ' ' not null,
  ptxaardc    char(6) default ' ' not null,
  ptxaardt    char(3) default ' ' not null,
  ptxaatdc    char(6) default ' ' not null,
  ptxaatdt    char(6) default ' ' not null,
  ptxasour    char(3) default ' ' not null,
  ptxaahos    char(5) default ' ' not null,
  ptxaclmc    char(3) default ' ' not null,
  ptxadiet    char(3) default ' ' not null,
  ptxaacls    char(3) default ' ' not null,
  ptxaacre    char(3) default ' ' not null,
  ptxascre    char(3) default ' ' not null,
  ptxadcre    char(3) default ' ' not null,
  ptxaadpt    char(3) default ' ' not null,
  ptxasdpt    char(3) default ' ' not null,
  ptxaddpt    char(3) default ' ' not null,
  ptxafund    char(6) default ' ' not null,
  ptxaftbl    char(8) default ' ' not null,
  ptxaaus1    char(3) default ' ' not null,
  ptxaaus2    char(3) default ' ' not null,
  ptxaaus3    char(3) default ' ' not null,
  ptxaaus4    char(3) default ' ' not null,
  ptxaaus5    char(3) default ' ' not null,
  ptxaaus6    char(3) default ' ' not null,
  ptxaaus7    char(3) default ' ' not null,
  ptxaadia    char(9) default ' ' not null,
  ptxaddia    char(9) default ' ' not null,
  ptxadstt    char(3) default ' ' not null,
  ptxaddst    char(3) default ' ' not null,
  ptxadhos    char(5) default ' ' not null,
  ptxadus1    char(3) default ' ' not null,
  ptxadus2    char(3) default ' ' not null,
  ptxadus3    char(3) default ' ' not null,
  ptxadus4    char(3) default ' ' not null,
  ptxadus5    char(3) default ' ' not null,
  ptxadrgc    char(6) default ' ' not null,
  ptxamdcc    char(5) default ' ' not null,
  ptxaopid    char(10) default ' ' not null,
  ptxarloc    char(3) default ' ' not null,
  ptxaabrg    char(3) default ' ' not null,
  ptxacadm    char(3) default ' ' not null,
  ptxairad    char(3) default ' ' not null,
  ptxaidus    char(3) default ' ' not null,
  ptxamhls    char(3) default ' ' not null,
  ptxaasut    char(3) default ' ' not null,
  ptxaelps    char(3) default ' ' not null,
  ptxaempl    char(3) default ' ' not null,
  ptxaread    char(3) default ' ' not null,
  ptxaudin    char(3) default ' ' not null,
  ptxaurea    char(3) default ' ' not null,
  ptxauvth    char(3) default ' ' not null,
  ptxaplan    char(3) default ' ' not null,
  ptxaspre    char(19) default ' ' not null,
  lf          char(1)
);
create unique index patex104 on patex104
(
dptxaadm
);
revoke all on patex104 from public ;
grant select on patex104 to public ;

create table patex105
(
  dptxaadm    char(8) default ' ' not null,
  ptxaadat    char(8) default ' ' not null,
  ptxaddat    char(8) default ' ' not null,
  ptxadayc    decimal(1,0) default 0 not null,
  ptxaplos    decimal(4,0) default 0 not null,
  ptxaalos    decimal(4,0) default 0 not null,
  ptxaplve    decimal(4,0) default 0 not null,
  ptxaalve    decimal(4,0) default 0 not null,
  ptxaawrd    char(3) default ' ' not null,
  ptxaabed    char(3) default ' ' not null,
  ptxaswrd    char(3) default ' ' not null,
  ptxasbed    char(3) default ' ' not null,
  ptxadwrd    char(3) default ' ' not null,
  ptxadbed    char(3) default ' ' not null,
  ptxaatyp    char(3) default ' ' not null,
  ptxastyp    char(3) default ' ' not null,
  ptxadtyp    char(3) default ' ' not null,
  ptxasex     char(1) default ' ' not null,
  ptxapost    char(8) default ' ' not null,
  ptxamlga    char(4) default ' ' not null,
  ptxaplga    char(4) default ' ' not null,
  ptxarelg    char(3) default ' ' not null,
  ptxacont    char(3) default ' ' not null,
  ptxaresi    char(3) default ' ' not null,
  ptxamstt    char(3) default ' ' not null,
  ptxaaagd    decimal(5,0) default 0 not null,
  ptxaaagm    decimal(4,0) default 0 not null,
  ptxaaagy    decimal(3,0) default 0 not null,
  ptxasagd    decimal(5,0) default 0 not null,
  ptxasagm    decimal(4,0) default 0 not null,
  ptxasagy    decimal(3,0) default 0 not null,
  ptxadagd    decimal(5,0) default 0 not null,
  ptxadagm    decimal(4,0) default 0 not null,
  ptxadagy    decimal(3,0) default 0 not null,
  ptxapus1    char(3) default ' ' not null,
  ptxapus2    char(3) default ' ' not null,
  ptxapus3    char(3) default ' ' not null,
  ptxapus4    char(3) default ' ' not null,
  ptxapus5    char(3) default ' ' not null,
  ptxapus6    char(3) default ' ' not null,
  ptxapyn1    char(1) default ' ' not null,
  ptxapyn2    char(1) default ' ' not null,
  ptxapyn3    char(1) default ' ' not null,
  ptxadcse    char(1) default ' ' not null,
  ptxaddth    char(8) default ' ' not null,
  ptxabadd    char(1) default ' ' not null,
  ptxaaadc    char(6) default ' ' not null,
  ptxaaadt    char(3) default ' ' not null,
  ptxasadc    char(6) default ' ' not null,
  ptxasadt    char(3) default ' ' not null,
  ptxadadc    char(6) default ' ' not null,
  ptxadadt    char(3) default ' ' not null,
  ptxaardc    char(6) default ' ' not null,
  ptxaardt    char(3) default ' ' not null,
  ptxaatdc    char(6) default ' ' not null,
  ptxaatdt    char(6) default ' ' not null,
  ptxasour    char(3) default ' ' not null,
  ptxaahos    char(5) default ' ' not null,
  ptxaclmc    char(3) default ' ' not null,
  ptxadiet    char(3) default ' ' not null,
  ptxaacls    char(3) default ' ' not null,
  ptxaacre    char(3) default ' ' not null,
  ptxascre    char(3) default ' ' not null,
  ptxadcre    char(3) default ' ' not null,
  ptxaadpt    char(3) default ' ' not null,
  ptxasdpt    char(3) default ' ' not null,
  ptxaddpt    char(3) default ' ' not null,
  ptxafund    char(6) default ' ' not null,
  ptxaftbl    char(8) default ' ' not null,
  ptxaaus1    char(3) default ' ' not null,
  ptxaaus2    char(3) default ' ' not null,
  ptxaaus3    char(3) default ' ' not null,
  ptxaaus4    char(3) default ' ' not null,
  ptxaaus5    char(3) default ' ' not null,
  ptxaaus6    char(3) default ' ' not null,
  ptxaaus7    char(3) default ' ' not null,
  ptxaadia    char(9) default ' ' not null,
  ptxaddia    char(9) default ' ' not null,
  ptxadstt    char(3) default ' ' not null,
  ptxaddst    char(3) default ' ' not null,
  ptxadhos    char(5) default ' ' not null,
  ptxadus1    char(3) default ' ' not null,
  ptxadus2    char(3) default ' ' not null,
  ptxadus3    char(3) default ' ' not null,
  ptxadus4    char(3) default ' ' not null,
  ptxadus5    char(3) default ' ' not null,
  ptxadrgc    char(6) default ' ' not null,
  ptxamdcc    char(5) default ' ' not null,
  ptxaopid    char(10) default ' ' not null,
  ptxarloc    char(3) default ' ' not null,
  ptxaabrg    char(3) default ' ' not null,
  ptxacadm    char(3) default ' ' not null,
  ptxairad    char(3) default ' ' not null,
  ptxaidus    char(3) default ' ' not null,
  ptxamhls    char(3) default ' ' not null,
  ptxaasut    char(3) default ' ' not null,
  ptxaelps    char(3) default ' ' not null,
  ptxaempl    char(3) default ' ' not null,
  ptxaread    char(3) default ' ' not null,
  ptxaudin    char(3) default ' ' not null,
  ptxaurea    char(3) default ' ' not null,
  ptxauvth    char(3) default ' ' not null,
  ptxaplan    char(3) default ' ' not null,
  ptxaspre    char(19) default ' ' not null,
  lf          char(1)
);
create unique index patex105 on patex105
(
dptxaadm
);
revoke all on patex105 from public ;
grant select on patex105 to public ;

create table patex106
(
  dptxaadm    char(8) default ' ' not null,
  ptxaadat    char(8) default ' ' not null,
  ptxaddat    char(8) default ' ' not null,
  ptxadayc    decimal(1,0) default 0 not null,
  ptxaplos    decimal(4,0) default 0 not null,
  ptxaalos    decimal(4,0) default 0 not null,
  ptxaplve    decimal(4,0) default 0 not null,
  ptxaalve    decimal(4,0) default 0 not null,
  ptxaawrd    char(3) default ' ' not null,
  ptxaabed    char(3) default ' ' not null,
  ptxaswrd    char(3) default ' ' not null,
  ptxasbed    char(3) default ' ' not null,
  ptxadwrd    char(3) default ' ' not null,
  ptxadbed    char(3) default ' ' not null,
  ptxaatyp    char(3) default ' ' not null,
  ptxastyp    char(3) default ' ' not null,
  ptxadtyp    char(3) default ' ' not null,
  ptxasex     char(1) default ' ' not null,
  ptxapost    char(8) default ' ' not null,
  ptxamlga    char(4) default ' ' not null,
  ptxaplga    char(4) default ' ' not null,
  ptxarelg    char(3) default ' ' not null,
  ptxacont    char(3) default ' ' not null,
  ptxaresi    char(3) default ' ' not null,
  ptxamstt    char(3) default ' ' not null,
  ptxaaagd    decimal(5,0) default 0 not null,
  ptxaaagm    decimal(4,0) default 0 not null,
  ptxaaagy    decimal(3,0) default 0 not null,
  ptxasagd    decimal(5,0) default 0 not null,
  ptxasagm    decimal(4,0) default 0 not null,
  ptxasagy    decimal(3,0) default 0 not null,
  ptxadagd    decimal(5,0) default 0 not null,
  ptxadagm    decimal(4,0) default 0 not null,
  ptxadagy    decimal(3,0) default 0 not null,
  ptxapus1    char(3) default ' ' not null,
  ptxapus2    char(3) default ' ' not null,
  ptxapus3    char(3) default ' ' not null,
  ptxapus4    char(3) default ' ' not null,
  ptxapus5    char(3) default ' ' not null,
  ptxapus6    char(3) default ' ' not null,
  ptxapyn1    char(1) default ' ' not null,
  ptxapyn2    char(1) default ' ' not null,
  ptxapyn3    char(1) default ' ' not null,
  ptxadcse    char(1) default ' ' not null,
  ptxaddth    char(8) default ' ' not null,
  ptxabadd    char(1) default ' ' not null,
  ptxaaadc    char(6) default ' ' not null,
  ptxaaadt    char(3) default ' ' not null,
  ptxasadc    char(6) default ' ' not null,
  ptxasadt    char(3) default ' ' not null,
  ptxadadc    char(6) default ' ' not null,
  ptxadadt    char(3) default ' ' not null,
  ptxaardc    char(6) default ' ' not null,
  ptxaardt    char(3) default ' ' not null,
  ptxaatdc    char(6) default ' ' not null,
  ptxaatdt    char(6) default ' ' not null,
  ptxasour    char(3) default ' ' not null,
  ptxaahos    char(5) default ' ' not null,
  ptxaclmc    char(3) default ' ' not null,
  ptxadiet    char(3) default ' ' not null,
  ptxaacls    char(3) default ' ' not null,
  ptxaacre    char(3) default ' ' not null,
  ptxascre    char(3) default ' ' not null,
  ptxadcre    char(3) default ' ' not null,
  ptxaadpt    char(3) default ' ' not null,
  ptxasdpt    char(3) default ' ' not null,
  ptxaddpt    char(3) default ' ' not null,
  ptxafund    char(6) default ' ' not null,
  ptxaftbl    char(8) default ' ' not null,
  ptxaaus1    char(3) default ' ' not null,
  ptxaaus2    char(3) default ' ' not null,
  ptxaaus3    char(3) default ' ' not null,
  ptxaaus4    char(3) default ' ' not null,
  ptxaaus5    char(3) default ' ' not null,
  ptxaaus6    char(3) default ' ' not null,
  ptxaaus7    char(3) default ' ' not null,
  ptxaadia    char(9) default ' ' not null,
  ptxaddia    char(9) default ' ' not null,
  ptxadstt    char(3) default ' ' not null,
  ptxaddst    char(3) default ' ' not null,
  ptxadhos    char(5) default ' ' not null,
  ptxadus1    char(3) default ' ' not null,
  ptxadus2    char(3) default ' ' not null,
  ptxadus3    char(3) default ' ' not null,
  ptxadus4    char(3) default ' ' not null,
  ptxadus5    char(3) default ' ' not null,
  ptxadrgc    char(6) default ' ' not null,
  ptxamdcc    char(5) default ' ' not null,
  ptxaopid    char(10) default ' ' not null,
  ptxarloc    char(3) default ' ' not null,
  ptxaabrg    char(3) default ' ' not null,
  ptxacadm    char(3) default ' ' not null,
  ptxairad    char(3) default ' ' not null,
  ptxaidus    char(3) default ' ' not null,
  ptxamhls    char(3) default ' ' not null,
  ptxaasut    char(3) default ' ' not null,
  ptxaelps    char(3) default ' ' not null,
  ptxaempl    char(3) default ' ' not null,
  ptxaread    char(3) default ' ' not null,
  ptxaudin    char(3) default ' ' not null,
  ptxaurea    char(3) default ' ' not null,
  ptxauvth    char(3) default ' ' not null,
  ptxaplan    char(3) default ' ' not null,
  ptxaspre    char(19) default ' ' not null,
  lf          char(1)
);
create unique index patex106 on patex106
(
dptxaadm
);
revoke all on patex106 from public ;
grant select on patex106 to public ;

create table patex107
(
  dptxaadm    char(8) default ' ' not null,
  ptxaadat    char(8) default ' ' not null,
  ptxaddat    char(8) default ' ' not null,
  ptxadayc    decimal(1,0) default 0 not null,
  ptxaplos    decimal(4,0) default 0 not null,
  ptxaalos    decimal(4,0) default 0 not null,
  ptxaplve    decimal(4,0) default 0 not null,
  ptxaalve    decimal(4,0) default 0 not null,
  ptxaawrd    char(3) default ' ' not null,
  ptxaabed    char(3) default ' ' not null,
  ptxaswrd    char(3) default ' ' not null,
  ptxasbed    char(3) default ' ' not null,
  ptxadwrd    char(3) default ' ' not null,
  ptxadbed    char(3) default ' ' not null,
  ptxaatyp    char(3) default ' ' not null,
  ptxastyp    char(3) default ' ' not null,
  ptxadtyp    char(3) default ' ' not null,
  ptxasex     char(1) default ' ' not null,
  ptxapost    char(8) default ' ' not null,
  ptxamlga    char(4) default ' ' not null,
  ptxaplga    char(4) default ' ' not null,
  ptxarelg    char(3) default ' ' not null,
  ptxacont    char(3) default ' ' not null,
  ptxaresi    char(3) default ' ' not null,
  ptxamstt    char(3) default ' ' not null,
  ptxaaagd    decimal(5,0) default 0 not null,
  ptxaaagm    decimal(4,0) default 0 not null,
  ptxaaagy    decimal(3,0) default 0 not null,
  ptxasagd    decimal(5,0) default 0 not null,
  ptxasagm    decimal(4,0) default 0 not null,
  ptxasagy    decimal(3,0) default 0 not null,
  ptxadagd    decimal(5,0) default 0 not null,
  ptxadagm    decimal(4,0) default 0 not null,
  ptxadagy    decimal(3,0) default 0 not null,
  ptxapus1    char(3) default ' ' not null,
  ptxapus2    char(3) default ' ' not null,
  ptxapus3    char(3) default ' ' not null,
  ptxapus4    char(3) default ' ' not null,
  ptxapus5    char(3) default ' ' not null,
  ptxapus6    char(3) default ' ' not null,
  ptxapyn1    char(1) default ' ' not null,
  ptxapyn2    char(1) default ' ' not null,
  ptxapyn3    char(1) default ' ' not null,
  ptxadcse    char(1) default ' ' not null,
  ptxaddth    char(8) default ' ' not null,
  ptxabadd    char(1) default ' ' not null,
  ptxaaadc    char(6) default ' ' not null,
  ptxaaadt    char(3) default ' ' not null,
  ptxasadc    char(6) default ' ' not null,
  ptxasadt    char(3) default ' ' not null,
  ptxadadc    char(6) default ' ' not null,
  ptxadadt    char(3) default ' ' not null,
  ptxaardc    char(6) default ' ' not null,
  ptxaardt    char(3) default ' ' not null,
  ptxaatdc    char(6) default ' ' not null,
  ptxaatdt    char(6) default ' ' not null,
  ptxasour    char(3) default ' ' not null,
  ptxaahos    char(5) default ' ' not null,
  ptxaclmc    char(3) default ' ' not null,
  ptxadiet    char(3) default ' ' not null,
  ptxaacls    char(3) default ' ' not null,
  ptxaacre    char(3) default ' ' not null,
  ptxascre    char(3) default ' ' not null,
  ptxadcre    char(3) default ' ' not null,
  ptxaadpt    char(3) default ' ' not null,
  ptxasdpt    char(3) default ' ' not null,
  ptxaddpt    char(3) default ' ' not null,
  ptxafund    char(6) default ' ' not null,
  ptxaftbl    char(8) default ' ' not null,
  ptxaaus1    char(3) default ' ' not null,
  ptxaaus2    char(3) default ' ' not null,
  ptxaaus3    char(3) default ' ' not null,
  ptxaaus4    char(3) default ' ' not null,
  ptxaaus5    char(3) default ' ' not null,
  ptxaaus6    char(3) default ' ' not null,
  ptxaaus7    char(3) default ' ' not null,
  ptxaadia    char(9) default ' ' not null,
  ptxaddia    char(9) default ' ' not null,
  ptxadstt    char(3) default ' ' not null,
  ptxaddst    char(3) default ' ' not null,
  ptxadhos    char(5) default ' ' not null,
  ptxadus1    char(3) default ' ' not null,
  ptxadus2    char(3) default ' ' not null,
  ptxadus3    char(3) default ' ' not null,
  ptxadus4    char(3) default ' ' not null,
  ptxadus5    char(3) default ' ' not null,
  ptxadrgc    char(6) default ' ' not null,
  ptxamdcc    char(5) default ' ' not null,
  ptxaopid    char(10) default ' ' not null,
  ptxarloc    char(3) default ' ' not null,
  ptxaabrg    char(3) default ' ' not null,
  ptxacadm    char(3) default ' ' not null,
  ptxairad    char(3) default ' ' not null,
  ptxaidus    char(3) default ' ' not null,
  ptxamhls    char(3) default ' ' not null,
  ptxaasut    char(3) default ' ' not null,
  ptxaelps    char(3) default ' ' not null,
  ptxaempl    char(3) default ' ' not null,
  ptxaread    char(3) default ' ' not null,
  ptxaudin    char(3) default ' ' not null,
  ptxaurea    char(3) default ' ' not null,
  ptxauvth    char(3) default ' ' not null,
  ptxaplan    char(3) default ' ' not null,
  ptxaspre    char(19) default ' ' not null,
  lf          char(1)
);
create unique index patex107 on patex107
(
dptxaadm
);
revoke all on patex107 from public ;
grant select on patex107 to public ;

create table patex108
(
  dptxaadm    char(8) default ' ' not null,
  ptxaadat    char(8) default ' ' not null,
  ptxaddat    char(8) default ' ' not null,
  ptxadayc    decimal(1,0) default 0 not null,
  ptxaplos    decimal(4,0) default 0 not null,
  ptxaalos    decimal(4,0) default 0 not null,
  ptxaplve    decimal(4,0) default 0 not null,
  ptxaalve    decimal(4,0) default 0 not null,
  ptxaawrd    char(3) default ' ' not null,
  ptxaabed    char(3) default ' ' not null,
  ptxaswrd    char(3) default ' ' not null,
  ptxasbed    char(3) default ' ' not null,
  ptxadwrd    char(3) default ' ' not null,
  ptxadbed    char(3) default ' ' not null,
  ptxaatyp    char(3) default ' ' not null,
  ptxastyp    char(3) default ' ' not null,
  ptxadtyp    char(3) default ' ' not null,
  ptxasex     char(1) default ' ' not null,
  ptxapost    char(8) default ' ' not null,
  ptxamlga    char(4) default ' ' not null,
  ptxaplga    char(4) default ' ' not null,
  ptxarelg    char(3) default ' ' not null,
  ptxacont    char(3) default ' ' not null,
  ptxaresi    char(3) default ' ' not null,
  ptxamstt    char(3) default ' ' not null,
  ptxaaagd    decimal(5,0) default 0 not null,
  ptxaaagm    decimal(4,0) default 0 not null,
  ptxaaagy    decimal(3,0) default 0 not null,
  ptxasagd    decimal(5,0) default 0 not null,
  ptxasagm    decimal(4,0) default 0 not null,
  ptxasagy    decimal(3,0) default 0 not null,
  ptxadagd    decimal(5,0) default 0 not null,
  ptxadagm    decimal(4,0) default 0 not null,
  ptxadagy    decimal(3,0) default 0 not null,
  ptxapus1    char(3) default ' ' not null,
  ptxapus2    char(3) default ' ' not null,
  ptxapus3    char(3) default ' ' not null,
  ptxapus4    char(3) default ' ' not null,
  ptxapus5    char(3) default ' ' not null,
  ptxapus6    char(3) default ' ' not null,
  ptxapyn1    char(1) default ' ' not null,
  ptxapyn2    char(1) default ' ' not null,
  ptxapyn3    char(1) default ' ' not null,
  ptxadcse    char(1) default ' ' not null,
  ptxaddth    char(8) default ' ' not null,
  ptxabadd    char(1) default ' ' not null,
  ptxaaadc    char(6) default ' ' not null,
  ptxaaadt    char(3) default ' ' not null,
  ptxasadc    char(6) default ' ' not null,
  ptxasadt    char(3) default ' ' not null,
  ptxadadc    char(6) default ' ' not null,
  ptxadadt    char(3) default ' ' not null,
  ptxaardc    char(6) default ' ' not null,
  ptxaardt    char(3) default ' ' not null,
  ptxaatdc    char(6) default ' ' not null,
  ptxaatdt    char(6) default ' ' not null,
  ptxasour    char(3) default ' ' not null,
  ptxaahos    char(5) default ' ' not null,
  ptxaclmc    char(3) default ' ' not null,
  ptxadiet    char(3) default ' ' not null,
  ptxaacls    char(3) default ' ' not null,
  ptxaacre    char(3) default ' ' not null,
  ptxascre    char(3) default ' ' not null,
  ptxadcre    char(3) default ' ' not null,
  ptxaadpt    char(3) default ' ' not null,
  ptxasdpt    char(3) default ' ' not null,
  ptxaddpt    char(3) default ' ' not null,
  ptxafund    char(6) default ' ' not null,
  ptxaftbl    char(8) default ' ' not null,
  ptxaaus1    char(3) default ' ' not null,
  ptxaaus2    char(3) default ' ' not null,
  ptxaaus3    char(3) default ' ' not null,
  ptxaaus4    char(3) default ' ' not null,
  ptxaaus5    char(3) default ' ' not null,
  ptxaaus6    char(3) default ' ' not null,
  ptxaaus7    char(3) default ' ' not null,
  ptxaadia    char(9) default ' ' not null,
  ptxaddia    char(9) default ' ' not null,
  ptxadstt    char(3) default ' ' not null,
  ptxaddst    char(3) default ' ' not null,
  ptxadhos    char(5) default ' ' not null,
  ptxadus1    char(3) default ' ' not null,
  ptxadus2    char(3) default ' ' not null,
  ptxadus3    char(3) default ' ' not null,
  ptxadus4    char(3) default ' ' not null,
  ptxadus5    char(3) default ' ' not null,
  ptxadrgc    char(6) default ' ' not null,
  ptxamdcc    char(5) default ' ' not null,
  ptxaopid    char(10) default ' ' not null,
  ptxarloc    char(3) default ' ' not null,
  ptxaabrg    char(3) default ' ' not null,
  ptxacadm    char(3) default ' ' not null,
  ptxairad    char(3) default ' ' not null,
  ptxaidus    char(3) default ' ' not null,
  ptxamhls    char(3) default ' ' not null,
  ptxaasut    char(3) default ' ' not null,
  ptxaelps    char(3) default ' ' not null,
  ptxaempl    char(3) default ' ' not null,
  ptxaread    char(3) default ' ' not null,
  ptxaudin    char(3) default ' ' not null,
  ptxaurea    char(3) default ' ' not null,
  ptxauvth    char(3) default ' ' not null,
  ptxaplan    char(3) default ' ' not null,
  ptxaspre    char(19) default ' ' not null,
  lf          char(1)
);
create unique index patex108 on patex108
(
dptxaadm
);
revoke all on patex108 from public ;
grant select on patex108 to public ;

create table patex109
(
  dptxaadm    char(8) default ' ' not null,
  ptxaadat    char(8) default ' ' not null,
  ptxaddat    char(8) default ' ' not null,
  ptxadayc    decimal(1,0) default 0 not null,
  ptxaplos    decimal(4,0) default 0 not null,
  ptxaalos    decimal(4,0) default 0 not null,
  ptxaplve    decimal(4,0) default 0 not null,
  ptxaalve    decimal(4,0) default 0 not null,
  ptxaawrd    char(3) default ' ' not null,
  ptxaabed    char(3) default ' ' not null,
  ptxaswrd    char(3) default ' ' not null,
  ptxasbed    char(3) default ' ' not null,
  ptxadwrd    char(3) default ' ' not null,
  ptxadbed    char(3) default ' ' not null,
  ptxaatyp    char(3) default ' ' not null,
  ptxastyp    char(3) default ' ' not null,
  ptxadtyp    char(3) default ' ' not null,
  ptxasex     char(1) default ' ' not null,
  ptxapost    char(8) default ' ' not null,
  ptxamlga    char(4) default ' ' not null,
  ptxaplga    char(4) default ' ' not null,
  ptxarelg    char(3) default ' ' not null,
  ptxacont    char(3) default ' ' not null,
  ptxaresi    char(3) default ' ' not null,
  ptxamstt    char(3) default ' ' not null,
  ptxaaagd    decimal(5,0) default 0 not null,
  ptxaaagm    decimal(4,0) default 0 not null,
  ptxaaagy    decimal(3,0) default 0 not null,
  ptxasagd    decimal(5,0) default 0 not null,
  ptxasagm    decimal(4,0) default 0 not null,
  ptxasagy    decimal(3,0) default 0 not null,
  ptxadagd    decimal(5,0) default 0 not null,
  ptxadagm    decimal(4,0) default 0 not null,
  ptxadagy    decimal(3,0) default 0 not null,
  ptxapus1    char(3) default ' ' not null,
  ptxapus2    char(3) default ' ' not null,
  ptxapus3    char(3) default ' ' not null,
  ptxapus4    char(3) default ' ' not null,
  ptxapus5    char(3) default ' ' not null,
  ptxapus6    char(3) default ' ' not null,
  ptxapyn1    char(1) default ' ' not null,
  ptxapyn2    char(1) default ' ' not null,
  ptxapyn3    char(1) default ' ' not null,
  ptxadcse    char(1) default ' ' not null,
  ptxaddth    char(8) default ' ' not null,
  ptxabadd    char(1) default ' ' not null,
  ptxaaadc    char(6) default ' ' not null,
  ptxaaadt    char(3) default ' ' not null,
  ptxasadc    char(6) default ' ' not null,
  ptxasadt    char(3) default ' ' not null,
  ptxadadc    char(6) default ' ' not null,
  ptxadadt    char(3) default ' ' not null,
  ptxaardc    char(6) default ' ' not null,
  ptxaardt    char(3) default ' ' not null,
  ptxaatdc    char(6) default ' ' not null,
  ptxaatdt    char(6) default ' ' not null,
  ptxasour    char(3) default ' ' not null,
  ptxaahos    char(5) default ' ' not null,
  ptxaclmc    char(3) default ' ' not null,
  ptxadiet    char(3) default ' ' not null,
  ptxaacls    char(3) default ' ' not null,
  ptxaacre    char(3) default ' ' not null,
  ptxascre    char(3) default ' ' not null,
  ptxadcre    char(3) default ' ' not null,
  ptxaadpt    char(3) default ' ' not null,
  ptxasdpt    char(3) default ' ' not null,
  ptxaddpt    char(3) default ' ' not null,
  ptxafund    char(6) default ' ' not null,
  ptxaftbl    char(8) default ' ' not null,
  ptxaaus1    char(3) default ' ' not null,
  ptxaaus2    char(3) default ' ' not null,
  ptxaaus3    char(3) default ' ' not null,
  ptxaaus4    char(3) default ' ' not null,
  ptxaaus5    char(3) default ' ' not null,
  ptxaaus6    char(3) default ' ' not null,
  ptxaaus7    char(3) default ' ' not null,
  ptxaadia    char(9) default ' ' not null,
  ptxaddia    char(9) default ' ' not null,
  ptxadstt    char(3) default ' ' not null,
  ptxaddst    char(3) default ' ' not null,
  ptxadhos    char(5) default ' ' not null,
  ptxadus1    char(3) default ' ' not null,
  ptxadus2    char(3) default ' ' not null,
  ptxadus3    char(3) default ' ' not null,
  ptxadus4    char(3) default ' ' not null,
  ptxadus5    char(3) default ' ' not null,
  ptxadrgc    char(6) default ' ' not null,
  ptxamdcc    char(5) default ' ' not null,
  ptxaopid    char(10) default ' ' not null,
  ptxarloc    char(3) default ' ' not null,
  ptxaabrg    char(3) default ' ' not null,
  ptxacadm    char(3) default ' ' not null,
  ptxairad    char(3) default ' ' not null,
  ptxaidus    char(3) default ' ' not null,
  ptxamhls    char(3) default ' ' not null,
  ptxaasut    char(3) default ' ' not null,
  ptxaelps    char(3) default ' ' not null,
  ptxaempl    char(3) default ' ' not null,
  ptxaread    char(3) default ' ' not null,
  ptxaudin    char(3) default ' ' not null,
  ptxaurea    char(3) default ' ' not null,
  ptxauvth    char(3) default ' ' not null,
  ptxaplan    char(3) default ' ' not null,
  ptxaspre    char(19) default ' ' not null,
  lf          char(1)
);
create unique index patex109 on patex109
(
dptxaadm
);
revoke all on patex109 from public ;
grant select on patex109 to public ;

create table patex110
(
  dptxaadm    char(8) default ' ' not null,
  ptxaadat    char(8) default ' ' not null,
  ptxaddat    char(8) default ' ' not null,
  ptxadayc    decimal(1,0) default 0 not null,
  ptxaplos    decimal(4,0) default 0 not null,
  ptxaalos    decimal(4,0) default 0 not null,
  ptxaplve    decimal(4,0) default 0 not null,
  ptxaalve    decimal(4,0) default 0 not null,
  ptxaawrd    char(3) default ' ' not null,
  ptxaabed    char(3) default ' ' not null,
  ptxaswrd    char(3) default ' ' not null,
  ptxasbed    char(3) default ' ' not null,
  ptxadwrd    char(3) default ' ' not null,
  ptxadbed    char(3) default ' ' not null,
  ptxaatyp    char(3) default ' ' not null,
  ptxastyp    char(3) default ' ' not null,
  ptxadtyp    char(3) default ' ' not null,
  ptxasex     char(1) default ' ' not null,
  ptxapost    char(8) default ' ' not null,
  ptxamlga    char(4) default ' ' not null,
  ptxaplga    char(4) default ' ' not null,
  ptxarelg    char(3) default ' ' not null,
  ptxacont    char(3) default ' ' not null,
  ptxaresi    char(3) default ' ' not null,
  ptxamstt    char(3) default ' ' not null,
  ptxaaagd    decimal(5,0) default 0 not null,
  ptxaaagm    decimal(4,0) default 0 not null,
  ptxaaagy    decimal(3,0) default 0 not null,
  ptxasagd    decimal(5,0) default 0 not null,
  ptxasagm    decimal(4,0) default 0 not null,
  ptxasagy    decimal(3,0) default 0 not null,
  ptxadagd    decimal(5,0) default 0 not null,
  ptxadagm    decimal(4,0) default 0 not null,
  ptxadagy    decimal(3,0) default 0 not null,
  ptxapus1    char(3) default ' ' not null,
  ptxapus2    char(3) default ' ' not null,
  ptxapus3    char(3) default ' ' not null,
  ptxapus4    char(3) default ' ' not null,
  ptxapus5    char(3) default ' ' not null,
  ptxapus6    char(3) default ' ' not null,
  ptxapyn1    char(1) default ' ' not null,
  ptxapyn2    char(1) default ' ' not null,
  ptxapyn3    char(1) default ' ' not null,
  ptxadcse    char(1) default ' ' not null,
  ptxaddth    char(8) default ' ' not null,
  ptxabadd    char(1) default ' ' not null,
  ptxaaadc    char(6) default ' ' not null,
  ptxaaadt    char(3) default ' ' not null,
  ptxasadc    char(6) default ' ' not null,
  ptxasadt    char(3) default ' ' not null,
  ptxadadc    char(6) default ' ' not null,
  ptxadadt    char(3) default ' ' not null,
  ptxaardc    char(6) default ' ' not null,
  ptxaardt    char(3) default ' ' not null,
  ptxaatdc    char(6) default ' ' not null,
  ptxaatdt    char(6) default ' ' not null,
  ptxasour    char(3) default ' ' not null,
  ptxaahos    char(5) default ' ' not null,
  ptxaclmc    char(3) default ' ' not null,
  ptxadiet    char(3) default ' ' not null,
  ptxaacls    char(3) default ' ' not null,
  ptxaacre    char(3) default ' ' not null,
  ptxascre    char(3) default ' ' not null,
  ptxadcre    char(3) default ' ' not null,
  ptxaadpt    char(3) default ' ' not null,
  ptxasdpt    char(3) default ' ' not null,
  ptxaddpt    char(3) default ' ' not null,
  ptxafund    char(6) default ' ' not null,
  ptxaftbl    char(8) default ' ' not null,
  ptxaaus1    char(3) default ' ' not null,
  ptxaaus2    char(3) default ' ' not null,
  ptxaaus3    char(3) default ' ' not null,
  ptxaaus4    char(3) default ' ' not null,
  ptxaaus5    char(3) default ' ' not null,
  ptxaaus6    char(3) default ' ' not null,
  ptxaaus7    char(3) default ' ' not null,
  ptxaadia    char(9) default ' ' not null,
  ptxaddia    char(9) default ' ' not null,
  ptxadstt    char(3) default ' ' not null,
  ptxaddst    char(3) default ' ' not null,
  ptxadhos    char(5) default ' ' not null,
  ptxadus1    char(3) default ' ' not null,
  ptxadus2    char(3) default ' ' not null,
  ptxadus3    char(3) default ' ' not null,
  ptxadus4    char(3) default ' ' not null,
  ptxadus5    char(3) default ' ' not null,
  ptxadrgc    char(6) default ' ' not null,
  ptxamdcc    char(5) default ' ' not null,
  ptxaopid    char(10) default ' ' not null,
  ptxarloc    char(3) default ' ' not null,
  ptxaabrg    char(3) default ' ' not null,
  ptxacadm    char(3) default ' ' not null,
  ptxairad    char(3) default ' ' not null,
  ptxaidus    char(3) default ' ' not null,
  ptxamhls    char(3) default ' ' not null,
  ptxaasut    char(3) default ' ' not null,
  ptxaelps    char(3) default ' ' not null,
  ptxaempl    char(3) default ' ' not null,
  ptxaread    char(3) default ' ' not null,
  ptxaudin    char(3) default ' ' not null,
  ptxaurea    char(3) default ' ' not null,
  ptxauvth    char(3) default ' ' not null,
  ptxaplan    char(3) default ' ' not null,
  ptxaspre    char(19) default ' ' not null,
  lf          char(1)
);
create unique index patex110 on patex110
(
dptxaadm
);
revoke all on patex110 from public ;
grant select on patex110 to public ;

create table patex111
(
  dptxaadm    char(8) default ' ' not null,
  ptxaadat    char(8) default ' ' not null,
  ptxaddat    char(8) default ' ' not null,
  ptxadayc    decimal(1,0) default 0 not null,
  ptxaplos    decimal(4,0) default 0 not null,
  ptxaalos    decimal(4,0) default 0 not null,
  ptxaplve    decimal(4,0) default 0 not null,
  ptxaalve    decimal(4,0) default 0 not null,
  ptxaawrd    char(3) default ' ' not null,
  ptxaabed    char(3) default ' ' not null,
  ptxaswrd    char(3) default ' ' not null,
  ptxasbed    char(3) default ' ' not null,
  ptxadwrd    char(3) default ' ' not null,
  ptxadbed    char(3) default ' ' not null,
  ptxaatyp    char(3) default ' ' not null,
  ptxastyp    char(3) default ' ' not null,
  ptxadtyp    char(3) default ' ' not null,
  ptxasex     char(1) default ' ' not null,
  ptxapost    char(8) default ' ' not null,
  ptxamlga    char(4) default ' ' not null,
  ptxaplga    char(4) default ' ' not null,
  ptxarelg    char(3) default ' ' not null,
  ptxacont    char(3) default ' ' not null,
  ptxaresi    char(3) default ' ' not null,
  ptxamstt    char(3) default ' ' not null,
  ptxaaagd    decimal(5,0) default 0 not null,
  ptxaaagm    decimal(4,0) default 0 not null,
  ptxaaagy    decimal(3,0) default 0 not null,
  ptxasagd    decimal(5,0) default 0 not null,
  ptxasagm    decimal(4,0) default 0 not null,
  ptxasagy    decimal(3,0) default 0 not null,
  ptxadagd    decimal(5,0) default 0 not null,
  ptxadagm    decimal(4,0) default 0 not null,
  ptxadagy    decimal(3,0) default 0 not null,
  ptxapus1    char(3) default ' ' not null,
  ptxapus2    char(3) default ' ' not null,
  ptxapus3    char(3) default ' ' not null,
  ptxapus4    char(3) default ' ' not null,
  ptxapus5    char(3) default ' ' not null,
  ptxapus6    char(3) default ' ' not null,
  ptxapyn1    char(1) default ' ' not null,
  ptxapyn2    char(1) default ' ' not null,
  ptxapyn3    char(1) default ' ' not null,
  ptxadcse    char(1) default ' ' not null,
  ptxaddth    char(8) default ' ' not null,
  ptxabadd    char(1) default ' ' not null,
  ptxaaadc    char(6) default ' ' not null,
  ptxaaadt    char(3) default ' ' not null,
  ptxasadc    char(6) default ' ' not null,
  ptxasadt    char(3) default ' ' not null,
  ptxadadc    char(6) default ' ' not null,
  ptxadadt    char(3) default ' ' not null,
  ptxaardc    char(6) default ' ' not null,
  ptxaardt    char(3) default ' ' not null,
  ptxaatdc    char(6) default ' ' not null,
  ptxaatdt    char(6) default ' ' not null,
  ptxasour    char(3) default ' ' not null,
  ptxaahos    char(5) default ' ' not null,
  ptxaclmc    char(3) default ' ' not null,
  ptxadiet    char(3) default ' ' not null,
  ptxaacls    char(3) default ' ' not null,
  ptxaacre    char(3) default ' ' not null,
  ptxascre    char(3) default ' ' not null,
  ptxadcre    char(3) default ' ' not null,
  ptxaadpt    char(3) default ' ' not null,
  ptxasdpt    char(3) default ' ' not null,
  ptxaddpt    char(3) default ' ' not null,
  ptxafund    char(6) default ' ' not null,
  ptxaftbl    char(8) default ' ' not null,
  ptxaaus1    char(3) default ' ' not null,
  ptxaaus2    char(3) default ' ' not null,
  ptxaaus3    char(3) default ' ' not null,
  ptxaaus4    char(3) default ' ' not null,
  ptxaaus5    char(3) default ' ' not null,
  ptxaaus6    char(3) default ' ' not null,
  ptxaaus7    char(3) default ' ' not null,
  ptxaadia    char(9) default ' ' not null,
  ptxaddia    char(9) default ' ' not null,
  ptxadstt    char(3) default ' ' not null,
  ptxaddst    char(3) default ' ' not null,
  ptxadhos    char(5) default ' ' not null,
  ptxadus1    char(3) default ' ' not null,
  ptxadus2    char(3) default ' ' not null,
  ptxadus3    char(3) default ' ' not null,
  ptxadus4    char(3) default ' ' not null,
  ptxadus5    char(3) default ' ' not null,
  ptxadrgc    char(6) default ' ' not null,
  ptxamdcc    char(5) default ' ' not null,
  ptxaopid    char(10) default ' ' not null,
  ptxarloc    char(3) default ' ' not null,
  ptxaabrg    char(3) default ' ' not null,
  ptxacadm    char(3) default ' ' not null,
  ptxairad    char(3) default ' ' not null,
  ptxaidus    char(3) default ' ' not null,
  ptxamhls    char(3) default ' ' not null,
  ptxaasut    char(3) default ' ' not null,
  ptxaelps    char(3) default ' ' not null,
  ptxaempl    char(3) default ' ' not null,
  ptxaread    char(3) default ' ' not null,
  ptxaudin    char(3) default ' ' not null,
  ptxaurea    char(3) default ' ' not null,
  ptxauvth    char(3) default ' ' not null,
  ptxaplan    char(3) default ' ' not null,
  ptxaspre    char(19) default ' ' not null,
  lf          char(1)
);
create unique index patex111 on patex111
(
dptxaadm
);
revoke all on patex111 from public ;
grant select on patex111 to public ;

create table patex112
(
  dptxaadm    char(8) default ' ' not null,
  ptxaadat    char(8) default ' ' not null,
  ptxaddat    char(8) default ' ' not null,
  ptxadayc    decimal(1,0) default 0 not null,
  ptxaplos    decimal(4,0) default 0 not null,
  ptxaalos    decimal(4,0) default 0 not null,
  ptxaplve    decimal(4,0) default 0 not null,
  ptxaalve    decimal(4,0) default 0 not null,
  ptxaawrd    char(3) default ' ' not null,
  ptxaabed    char(3) default ' ' not null,
  ptxaswrd    char(3) default ' ' not null,
  ptxasbed    char(3) default ' ' not null,
  ptxadwrd    char(3) default ' ' not null,
  ptxadbed    char(3) default ' ' not null,
  ptxaatyp    char(3) default ' ' not null,
  ptxastyp    char(3) default ' ' not null,
  ptxadtyp    char(3) default ' ' not null,
  ptxasex     char(1) default ' ' not null,
  ptxapost    char(8) default ' ' not null,
  ptxamlga    char(4) default ' ' not null,
  ptxaplga    char(4) default ' ' not null,
  ptxarelg    char(3) default ' ' not null,
  ptxacont    char(3) default ' ' not null,
  ptxaresi    char(3) default ' ' not null,
  ptxamstt    char(3) default ' ' not null,
  ptxaaagd    decimal(5,0) default 0 not null,
  ptxaaagm    decimal(4,0) default 0 not null,
  ptxaaagy    decimal(3,0) default 0 not null,
  ptxasagd    decimal(5,0) default 0 not null,
  ptxasagm    decimal(4,0) default 0 not null,
  ptxasagy    decimal(3,0) default 0 not null,
  ptxadagd    decimal(5,0) default 0 not null,
  ptxadagm    decimal(4,0) default 0 not null,
  ptxadagy    decimal(3,0) default 0 not null,
  ptxapus1    char(3) default ' ' not null,
  ptxapus2    char(3) default ' ' not null,
  ptxapus3    char(3) default ' ' not null,
  ptxapus4    char(3) default ' ' not null,
  ptxapus5    char(3) default ' ' not null,
  ptxapus6    char(3) default ' ' not null,
  ptxapyn1    char(1) default ' ' not null,
  ptxapyn2    char(1) default ' ' not null,
  ptxapyn3    char(1) default ' ' not null,
  ptxadcse    char(1) default ' ' not null,
  ptxaddth    char(8) default ' ' not null,
  ptxabadd    char(1) default ' ' not null,
  ptxaaadc    char(6) default ' ' not null,
  ptxaaadt    char(3) default ' ' not null,
  ptxasadc    char(6) default ' ' not null,
  ptxasadt    char(3) default ' ' not null,
  ptxadadc    char(6) default ' ' not null,
  ptxadadt    char(3) default ' ' not null,
  ptxaardc    char(6) default ' ' not null,
  ptxaardt    char(3) default ' ' not null,
  ptxaatdc    char(6) default ' ' not null,
  ptxaatdt    char(6) default ' ' not null,
  ptxasour    char(3) default ' ' not null,
  ptxaahos    char(5) default ' ' not null,
  ptxaclmc    char(3) default ' ' not null,
  ptxadiet    char(3) default ' ' not null,
  ptxaacls    char(3) default ' ' not null,
  ptxaacre    char(3) default ' ' not null,
  ptxascre    char(3) default ' ' not null,
  ptxadcre    char(3) default ' ' not null,
  ptxaadpt    char(3) default ' ' not null,
  ptxasdpt    char(3) default ' ' not null,
  ptxaddpt    char(3) default ' ' not null,
  ptxafund    char(6) default ' ' not null,
  ptxaftbl    char(8) default ' ' not null,
  ptxaaus1    char(3) default ' ' not null,
  ptxaaus2    char(3) default ' ' not null,
  ptxaaus3    char(3) default ' ' not null,
  ptxaaus4    char(3) default ' ' not null,
  ptxaaus5    char(3) default ' ' not null,
  ptxaaus6    char(3) default ' ' not null,
  ptxaaus7    char(3) default ' ' not null,
  ptxaadia    char(9) default ' ' not null,
  ptxaddia    char(9) default ' ' not null,
  ptxadstt    char(3) default ' ' not null,
  ptxaddst    char(3) default ' ' not null,
  ptxadhos    char(5) default ' ' not null,
  ptxadus1    char(3) default ' ' not null,
  ptxadus2    char(3) default ' ' not null,
  ptxadus3    char(3) default ' ' not null,
  ptxadus4    char(3) default ' ' not null,
  ptxadus5    char(3) default ' ' not null,
  ptxadrgc    char(6) default ' ' not null,
  ptxamdcc    char(5) default ' ' not null,
  ptxaopid    char(10) default ' ' not null,
  ptxarloc    char(3) default ' ' not null,
  ptxaabrg    char(3) default ' ' not null,
  ptxacadm    char(3) default ' ' not null,
  ptxairad    char(3) default ' ' not null,
  ptxaidus    char(3) default ' ' not null,
  ptxamhls    char(3) default ' ' not null,
  ptxaasut    char(3) default ' ' not null,
  ptxaelps    char(3) default ' ' not null,
  ptxaempl    char(3) default ' ' not null,
  ptxaread    char(3) default ' ' not null,
  ptxaudin    char(3) default ' ' not null,
  ptxaurea    char(3) default ' ' not null,
  ptxauvth    char(3) default ' ' not null,
  ptxaplan    char(3) default ' ' not null,
  ptxaspre    char(19) default ' ' not null,
  lf          char(1)
);
create unique index patex112 on patex112
(
dptxaadm
);
revoke all on patex112 from public ;
grant select on patex112 to public ;

create table patex113
(
  dptxaadm    char(8) default ' ' not null,
  ptxaadat    char(8) default ' ' not null,
  ptxaddat    char(8) default ' ' not null,
  ptxadayc    decimal(1,0) default 0 not null,
  ptxaplos    decimal(4,0) default 0 not null,
  ptxaalos    decimal(4,0) default 0 not null,
  ptxaplve    decimal(4,0) default 0 not null,
  ptxaalve    decimal(4,0) default 0 not null,
  ptxaawrd    char(3) default ' ' not null,
  ptxaabed    char(3) default ' ' not null,
  ptxaswrd    char(3) default ' ' not null,
  ptxasbed    char(3) default ' ' not null,
  ptxadwrd    char(3) default ' ' not null,
  ptxadbed    char(3) default ' ' not null,
  ptxaatyp    char(3) default ' ' not null,
  ptxastyp    char(3) default ' ' not null,
  ptxadtyp    char(3) default ' ' not null,
  ptxasex     char(1) default ' ' not null,
  ptxapost    char(8) default ' ' not null,
  ptxamlga    char(4) default ' ' not null,
  ptxaplga    char(4) default ' ' not null,
  ptxarelg    char(3) default ' ' not null,
  ptxacont    char(3) default ' ' not null,
  ptxaresi    char(3) default ' ' not null,
  ptxamstt    char(3) default ' ' not null,
  ptxaaagd    decimal(5,0) default 0 not null,
  ptxaaagm    decimal(4,0) default 0 not null,
  ptxaaagy    decimal(3,0) default 0 not null,
  ptxasagd    decimal(5,0) default 0 not null,
  ptxasagm    decimal(4,0) default 0 not null,
  ptxasagy    decimal(3,0) default 0 not null,
  ptxadagd    decimal(5,0) default 0 not null,
  ptxadagm    decimal(4,0) default 0 not null,
  ptxadagy    decimal(3,0) default 0 not null,
  ptxapus1    char(3) default ' ' not null,
  ptxapus2    char(3) default ' ' not null,
  ptxapus3    char(3) default ' ' not null,
  ptxapus4    char(3) default ' ' not null,
  ptxapus5    char(3) default ' ' not null,
  ptxapus6    char(3) default ' ' not null,
  ptxapyn1    char(1) default ' ' not null,
  ptxapyn2    char(1) default ' ' not null,
  ptxapyn3    char(1) default ' ' not null,
  ptxadcse    char(1) default ' ' not null,
  ptxaddth    char(8) default ' ' not null,
  ptxabadd    char(1) default ' ' not null,
  ptxaaadc    char(6) default ' ' not null,
  ptxaaadt    char(3) default ' ' not null,
  ptxasadc    char(6) default ' ' not null,
  ptxasadt    char(3) default ' ' not null,
  ptxadadc    char(6) default ' ' not null,
  ptxadadt    char(3) default ' ' not null,
  ptxaardc    char(6) default ' ' not null,
  ptxaardt    char(3) default ' ' not null,
  ptxaatdc    char(6) default ' ' not null,
  ptxaatdt    char(6) default ' ' not null,
  ptxasour    char(3) default ' ' not null,
  ptxaahos    char(5) default ' ' not null,
  ptxaclmc    char(3) default ' ' not null,
  ptxadiet    char(3) default ' ' not null,
  ptxaacls    char(3) default ' ' not null,
  ptxaacre    char(3) default ' ' not null,
  ptxascre    char(3) default ' ' not null,
  ptxadcre    char(3) default ' ' not null,
  ptxaadpt    char(3) default ' ' not null,
  ptxasdpt    char(3) default ' ' not null,
  ptxaddpt    char(3) default ' ' not null,
  ptxafund    char(6) default ' ' not null,
  ptxaftbl    char(8) default ' ' not null,
  ptxaaus1    char(3) default ' ' not null,
  ptxaaus2    char(3) default ' ' not null,
  ptxaaus3    char(3) default ' ' not null,
  ptxaaus4    char(3) default ' ' not null,
  ptxaaus5    char(3) default ' ' not null,
  ptxaaus6    char(3) default ' ' not null,
  ptxaaus7    char(3) default ' ' not null,
  ptxaadia    char(9) default ' ' not null,
  ptxaddia    char(9) default ' ' not null,
  ptxadstt    char(3) default ' ' not null,
  ptxaddst    char(3) default ' ' not null,
  ptxadhos    char(5) default ' ' not null,
  ptxadus1    char(3) default ' ' not null,
  ptxadus2    char(3) default ' ' not null,
  ptxadus3    char(3) default ' ' not null,
  ptxadus4    char(3) default ' ' not null,
  ptxadus5    char(3) default ' ' not null,
  ptxadrgc    char(6) default ' ' not null,
  ptxamdcc    char(5) default ' ' not null,
  ptxaopid    char(10) default ' ' not null,
  ptxarloc    char(3) default ' ' not null,
  ptxaabrg    char(3) default ' ' not null,
  ptxacadm    char(3) default ' ' not null,
  ptxairad    char(3) default ' ' not null,
  ptxaidus    char(3) default ' ' not null,
  ptxamhls    char(3) default ' ' not null,
  ptxaasut    char(3) default ' ' not null,
  ptxaelps    char(3) default ' ' not null,
  ptxaempl    char(3) default ' ' not null,
  ptxaread    char(3) default ' ' not null,
  ptxaudin    char(3) default ' ' not null,
  ptxaurea    char(3) default ' ' not null,
  ptxauvth    char(3) default ' ' not null,
  ptxaplan    char(3) default ' ' not null,
  ptxaspre    char(19) default ' ' not null,
  lf          char(1)
);
create unique index patex113 on patex113
(
dptxaadm
);
revoke all on patex113 from public ;
grant select on patex113 to public ;

create table patex114
(
  dptxaadm    char(8) default ' ' not null,
  ptxaadat    char(8) default ' ' not null,
  ptxaddat    char(8) default ' ' not null,
  ptxadayc    decimal(1,0) default 0 not null,
  ptxaplos    decimal(4,0) default 0 not null,
  ptxaalos    decimal(4,0) default 0 not null,
  ptxaplve    decimal(4,0) default 0 not null,
  ptxaalve    decimal(4,0) default 0 not null,
  ptxaawrd    char(3) default ' ' not null,
  ptxaabed    char(3) default ' ' not null,
  ptxaswrd    char(3) default ' ' not null,
  ptxasbed    char(3) default ' ' not null,
  ptxadwrd    char(3) default ' ' not null,
  ptxadbed    char(3) default ' ' not null,
  ptxaatyp    char(3) default ' ' not null,
  ptxastyp    char(3) default ' ' not null,
  ptxadtyp    char(3) default ' ' not null,
  ptxasex     char(1) default ' ' not null,
  ptxapost    char(8) default ' ' not null,
  ptxamlga    char(4) default ' ' not null,
  ptxaplga    char(4) default ' ' not null,
  ptxarelg    char(3) default ' ' not null,
  ptxacont    char(3) default ' ' not null,
  ptxaresi    char(3) default ' ' not null,
  ptxamstt    char(3) default ' ' not null,
  ptxaaagd    decimal(5,0) default 0 not null,
  ptxaaagm    decimal(4,0) default 0 not null,
  ptxaaagy    decimal(3,0) default 0 not null,
  ptxasagd    decimal(5,0) default 0 not null,
  ptxasagm    decimal(4,0) default 0 not null,
  ptxasagy    decimal(3,0) default 0 not null,
  ptxadagd    decimal(5,0) default 0 not null,
  ptxadagm    decimal(4,0) default 0 not null,
  ptxadagy    decimal(3,0) default 0 not null,
  ptxapus1    char(3) default ' ' not null,
  ptxapus2    char(3) default ' ' not null,
  ptxapus3    char(3) default ' ' not null,
  ptxapus4    char(3) default ' ' not null,
  ptxapus5    char(3) default ' ' not null,
  ptxapus6    char(3) default ' ' not null,
  ptxapyn1    char(1) default ' ' not null,
  ptxapyn2    char(1) default ' ' not null,
  ptxapyn3    char(1) default ' ' not null,
  ptxadcse    char(1) default ' ' not null,
  ptxaddth    char(8) default ' ' not null,
  ptxabadd    char(1) default ' ' not null,
  ptxaaadc    char(6) default ' ' not null,
  ptxaaadt    char(3) default ' ' not null,
  ptxasadc    char(6) default ' ' not null,
  ptxasadt    char(3) default ' ' not null,
  ptxadadc    char(6) default ' ' not null,
  ptxadadt    char(3) default ' ' not null,
  ptxaardc    char(6) default ' ' not null,
  ptxaardt    char(3) default ' ' not null,
  ptxaatdc    char(6) default ' ' not null,
  ptxaatdt    char(6) default ' ' not null,
  ptxasour    char(3) default ' ' not null,
  ptxaahos    char(5) default ' ' not null,
  ptxaclmc    char(3) default ' ' not null,
  ptxadiet    char(3) default ' ' not null,
  ptxaacls    char(3) default ' ' not null,
  ptxaacre    char(3) default ' ' not null,
  ptxascre    char(3) default ' ' not null,
  ptxadcre    char(3) default ' ' not null,
  ptxaadpt    char(3) default ' ' not null,
  ptxasdpt    char(3) default ' ' not null,
  ptxaddpt    char(3) default ' ' not null,
  ptxafund    char(6) default ' ' not null,
  ptxaftbl    char(8) default ' ' not null,
  ptxaaus1    char(3) default ' ' not null,
  ptxaaus2    char(3) default ' ' not null,
  ptxaaus3    char(3) default ' ' not null,
  ptxaaus4    char(3) default ' ' not null,
  ptxaaus5    char(3) default ' ' not null,
  ptxaaus6    char(3) default ' ' not null,
  ptxaaus7    char(3) default ' ' not null,
  ptxaadia    char(9) default ' ' not null,
  ptxaddia    char(9) default ' ' not null,
  ptxadstt    char(3) default ' ' not null,
  ptxaddst    char(3) default ' ' not null,
  ptxadhos    char(5) default ' ' not null,
  ptxadus1    char(3) default ' ' not null,
  ptxadus2    char(3) default ' ' not null,
  ptxadus3    char(3) default ' ' not null,
  ptxadus4    char(3) default ' ' not null,
  ptxadus5    char(3) default ' ' not null,
  ptxadrgc    char(6) default ' ' not null,
  ptxamdcc    char(5) default ' ' not null,
  ptxaopid    char(10) default ' ' not null,
  ptxarloc    char(3) default ' ' not null,
  ptxaabrg    char(3) default ' ' not null,
  ptxacadm    char(3) default ' ' not null,
  ptxairad    char(3) default ' ' not null,
  ptxaidus    char(3) default ' ' not null,
  ptxamhls    char(3) default ' ' not null,
  ptxaasut    char(3) default ' ' not null,
  ptxaelps    char(3) default ' ' not null,
  ptxaempl    char(3) default ' ' not null,
  ptxaread    char(3) default ' ' not null,
  ptxaudin    char(3) default ' ' not null,
  ptxaurea    char(3) default ' ' not null,
  ptxauvth    char(3) default ' ' not null,
  ptxaplan    char(3) default ' ' not null,
  ptxaspre    char(19) default ' ' not null,
  lf          char(1)
);
create unique index patex114 on patex114
(
dptxaadm
);
revoke all on patex114 from public ;
grant select on patex114 to public ;

create table patex115
(
  dptxaadm    char(8) default ' ' not null,
  ptxaadat    char(8) default ' ' not null,
  ptxaddat    char(8) default ' ' not null,
  ptxadayc    decimal(1,0) default 0 not null,
  ptxaplos    decimal(4,0) default 0 not null,
  ptxaalos    decimal(4,0) default 0 not null,
  ptxaplve    decimal(4,0) default 0 not null,
  ptxaalve    decimal(4,0) default 0 not null,
  ptxaawrd    char(3) default ' ' not null,
  ptxaabed    char(3) default ' ' not null,
  ptxaswrd    char(3) default ' ' not null,
  ptxasbed    char(3) default ' ' not null,
  ptxadwrd    char(3) default ' ' not null,
  ptxadbed    char(3) default ' ' not null,
  ptxaatyp    char(3) default ' ' not null,
  ptxastyp    char(3) default ' ' not null,
  ptxadtyp    char(3) default ' ' not null,
  ptxasex     char(1) default ' ' not null,
  ptxapost    char(8) default ' ' not null,
  ptxamlga    char(4) default ' ' not null,
  ptxaplga    char(4) default ' ' not null,
  ptxarelg    char(3) default ' ' not null,
  ptxacont    char(3) default ' ' not null,
  ptxaresi    char(3) default ' ' not null,
  ptxamstt    char(3) default ' ' not null,
  ptxaaagd    decimal(5,0) default 0 not null,
  ptxaaagm    decimal(4,0) default 0 not null,
  ptxaaagy    decimal(3,0) default 0 not null,
  ptxasagd    decimal(5,0) default 0 not null,
  ptxasagm    decimal(4,0) default 0 not null,
  ptxasagy    decimal(3,0) default 0 not null,
  ptxadagd    decimal(5,0) default 0 not null,
  ptxadagm    decimal(4,0) default 0 not null,
  ptxadagy    decimal(3,0) default 0 not null,
  ptxapus1    char(3) default ' ' not null,
  ptxapus2    char(3) default ' ' not null,
  ptxapus3    char(3) default ' ' not null,
  ptxapus4    char(3) default ' ' not null,
  ptxapus5    char(3) default ' ' not null,
  ptxapus6    char(3) default ' ' not null,
  ptxapyn1    char(1) default ' ' not null,
  ptxapyn2    char(1) default ' ' not null,
  ptxapyn3    char(1) default ' ' not null,
  ptxadcse    char(1) default ' ' not null,
  ptxaddth    char(8) default ' ' not null,
  ptxabadd    char(1) default ' ' not null,
  ptxaaadc    char(6) default ' ' not null,
  ptxaaadt    char(3) default ' ' not null,
  ptxasadc    char(6) default ' ' not null,
  ptxasadt    char(3) default ' ' not null,
  ptxadadc    char(6) default ' ' not null,
  ptxadadt    char(3) default ' ' not null,
  ptxaardc    char(6) default ' ' not null,
  ptxaardt    char(3) default ' ' not null,
  ptxaatdc    char(6) default ' ' not null,
  ptxaatdt    char(6) default ' ' not null,
  ptxasour    char(3) default ' ' not null,
  ptxaahos    char(5) default ' ' not null,
  ptxaclmc    char(3) default ' ' not null,
  ptxadiet    char(3) default ' ' not null,
  ptxaacls    char(3) default ' ' not null,
  ptxaacre    char(3) default ' ' not null,
  ptxascre    char(3) default ' ' not null,
  ptxadcre    char(3) default ' ' not null,
  ptxaadpt    char(3) default ' ' not null,
  ptxasdpt    char(3) default ' ' not null,
  ptxaddpt    char(3) default ' ' not null,
  ptxafund    char(6) default ' ' not null,
  ptxaftbl    char(8) default ' ' not null,
  ptxaaus1    char(3) default ' ' not null,
  ptxaaus2    char(3) default ' ' not null,
  ptxaaus3    char(3) default ' ' not null,
  ptxaaus4    char(3) default ' ' not null,
  ptxaaus5    char(3) default ' ' not null,
  ptxaaus6    char(3) default ' ' not null,
  ptxaaus7    char(3) default ' ' not null,
  ptxaadia    char(9) default ' ' not null,
  ptxaddia    char(9) default ' ' not null,
  ptxadstt    char(3) default ' ' not null,
  ptxaddst    char(3) default ' ' not null,
  ptxadhos    char(5) default ' ' not null,
  ptxadus1    char(3) default ' ' not null,
  ptxadus2    char(3) default ' ' not null,
  ptxadus3    char(3) default ' ' not null,
  ptxadus4    char(3) default ' ' not null,
  ptxadus5    char(3) default ' ' not null,
  ptxadrgc    char(6) default ' ' not null,
  ptxamdcc    char(5) default ' ' not null,
  ptxaopid    char(10) default ' ' not null,
  ptxarloc    char(3) default ' ' not null,
  ptxaabrg    char(3) default ' ' not null,
  ptxacadm    char(3) default ' ' not null,
  ptxairad    char(3) default ' ' not null,
  ptxaidus    char(3) default ' ' not null,
  ptxamhls    char(3) default ' ' not null,
  ptxaasut    char(3) default ' ' not null,
  ptxaelps    char(3) default ' ' not null,
  ptxaempl    char(3) default ' ' not null,
  ptxaread    char(3) default ' ' not null,
  ptxaudin    char(3) default ' ' not null,
  ptxaurea    char(3) default ' ' not null,
  ptxauvth    char(3) default ' ' not null,
  ptxaplan    char(3) default ' ' not null,
  ptxaspre    char(19) default ' ' not null,
  lf          char(1)
);
create unique index patex115 on patex115
(
dptxaadm
);
revoke all on patex115 from public ;
grant select on patex115 to public ;

create table patex116
(
  dptxaadm    char(8) default ' ' not null,
  ptxaadat    char(8) default ' ' not null,
  ptxaddat    char(8) default ' ' not null,
  ptxadayc    decimal(1,0) default 0 not null,
  ptxaplos    decimal(4,0) default 0 not null,
  ptxaalos    decimal(4,0) default 0 not null,
  ptxaplve    decimal(4,0) default 0 not null,
  ptxaalve    decimal(4,0) default 0 not null,
  ptxaawrd    char(3) default ' ' not null,
  ptxaabed    char(3) default ' ' not null,
  ptxaswrd    char(3) default ' ' not null,
  ptxasbed    char(3) default ' ' not null,
  ptxadwrd    char(3) default ' ' not null,
  ptxadbed    char(3) default ' ' not null,
  ptxaatyp    char(3) default ' ' not null,
  ptxastyp    char(3) default ' ' not null,
  ptxadtyp    char(3) default ' ' not null,
  ptxasex     char(1) default ' ' not null,
  ptxapost    char(8) default ' ' not null,
  ptxamlga    char(4) default ' ' not null,
  ptxaplga    char(4) default ' ' not null,
  ptxarelg    char(3) default ' ' not null,
  ptxacont    char(3) default ' ' not null,
  ptxaresi    char(3) default ' ' not null,
  ptxamstt    char(3) default ' ' not null,
  ptxaaagd    decimal(5,0) default 0 not null,
  ptxaaagm    decimal(4,0) default 0 not null,
  ptxaaagy    decimal(3,0) default 0 not null,
  ptxasagd    decimal(5,0) default 0 not null,
  ptxasagm    decimal(4,0) default 0 not null,
  ptxasagy    decimal(3,0) default 0 not null,
  ptxadagd    decimal(5,0) default 0 not null,
  ptxadagm    decimal(4,0) default 0 not null,
  ptxadagy    decimal(3,0) default 0 not null,
  ptxapus1    char(3) default ' ' not null,
  ptxapus2    char(3) default ' ' not null,
  ptxapus3    char(3) default ' ' not null,
  ptxapus4    char(3) default ' ' not null,
  ptxapus5    char(3) default ' ' not null,
  ptxapus6    char(3) default ' ' not null,
  ptxapyn1    char(1) default ' ' not null,
  ptxapyn2    char(1) default ' ' not null,
  ptxapyn3    char(1) default ' ' not null,
  ptxadcse    char(1) default ' ' not null,
  ptxaddth    char(8) default ' ' not null,
  ptxabadd    char(1) default ' ' not null,
  ptxaaadc    char(6) default ' ' not null,
  ptxaaadt    char(3) default ' ' not null,
  ptxasadc    char(6) default ' ' not null,
  ptxasadt    char(3) default ' ' not null,
  ptxadadc    char(6) default ' ' not null,
  ptxadadt    char(3) default ' ' not null,
  ptxaardc    char(6) default ' ' not null,
  ptxaardt    char(3) default ' ' not null,
  ptxaatdc    char(6) default ' ' not null,
  ptxaatdt    char(6) default ' ' not null,
  ptxasour    char(3) default ' ' not null,
  ptxaahos    char(5) default ' ' not null,
  ptxaclmc    char(3) default ' ' not null,
  ptxadiet    char(3) default ' ' not null,
  ptxaacls    char(3) default ' ' not null,
  ptxaacre    char(3) default ' ' not null,
  ptxascre    char(3) default ' ' not null,
  ptxadcre    char(3) default ' ' not null,
  ptxaadpt    char(3) default ' ' not null,
  ptxasdpt    char(3) default ' ' not null,
  ptxaddpt    char(3) default ' ' not null,
  ptxafund    char(6) default ' ' not null,
  ptxaftbl    char(8) default ' ' not null,
  ptxaaus1    char(3) default ' ' not null,
  ptxaaus2    char(3) default ' ' not null,
  ptxaaus3    char(3) default ' ' not null,
  ptxaaus4    char(3) default ' ' not null,
  ptxaaus5    char(3) default ' ' not null,
  ptxaaus6    char(3) default ' ' not null,
  ptxaaus7    char(3) default ' ' not null,
  ptxaadia    char(9) default ' ' not null,
  ptxaddia    char(9) default ' ' not null,
  ptxadstt    char(3) default ' ' not null,
  ptxaddst    char(3) default ' ' not null,
  ptxadhos    char(5) default ' ' not null,
  ptxadus1    char(3) default ' ' not null,
  ptxadus2    char(3) default ' ' not null,
  ptxadus3    char(3) default ' ' not null,
  ptxadus4    char(3) default ' ' not null,
  ptxadus5    char(3) default ' ' not null,
  ptxadrgc    char(6) default ' ' not null,
  ptxamdcc    char(5) default ' ' not null,
  ptxaopid    char(10) default ' ' not null,
  ptxarloc    char(3) default ' ' not null,
  ptxaabrg    char(3) default ' ' not null,
  ptxacadm    char(3) default ' ' not null,
  ptxairad    char(3) default ' ' not null,
  ptxaidus    char(3) default ' ' not null,
  ptxamhls    char(3) default ' ' not null,
  ptxaasut    char(3) default ' ' not null,
  ptxaelps    char(3) default ' ' not null,
  ptxaempl    char(3) default ' ' not null,
  ptxaread    char(3) default ' ' not null,
  ptxaudin    char(3) default ' ' not null,
  ptxaurea    char(3) default ' ' not null,
  ptxauvth    char(3) default ' ' not null,
  ptxaplan    char(3) default ' ' not null,
  ptxaspre    char(19) default ' ' not null,
  lf          char(1)
);
create unique index patex116 on patex116
(
dptxaadm
);
revoke all on patex116 from public ;
grant select on patex116 to public ;

