create table patfimaf
(
  ptfivisn    char(8) default ' ' not null,
  ptfidate    char(8) default ' ' not null,
  ptfitime    char(8) default ' ' not null,
  ptfitype    char(1) default ' ' not null,
  ptfieats    decimal(2,0) default 0 not null,
  ptfieatg    decimal(2,0) default 0 not null,
  ptfieatc    char(50) default ' ' not null,
  ptfigrms    decimal(2,0) default 0 not null,
  ptfigrmg    decimal(2,0) default 0 not null,
  ptfigrmc    char(50) default ' ' not null,
  ptfibths    decimal(2,0) default 0 not null,
  ptfibthg    decimal(2,0) default 0 not null,
  ptfibthc    char(50) default ' ' not null,
  ptfiupbs    decimal(2,0) default 0 not null,
  ptfiupbg    decimal(2,0) default 0 not null,
  ptfiupbc    char(50) default ' ' not null,
  ptfilwbs    decimal(2,0) default 0 not null,
  ptfilwbg    decimal(2,0) default 0 not null,
  ptfilwbc    char(50) default ' ' not null,
  ptfitlts    decimal(2,0) default 0 not null,
  ptfitltg    decimal(2,0) default 0 not null,
  ptfitltc    char(50) default ' ' not null,
  ptfiblms    decimal(2,0) default 0 not null,
  ptfiblmg    decimal(2,0) default 0 not null,
  ptfiblmc    char(50) default ' ' not null,
  ptfibwms    decimal(2,0) default 0 not null,
  ptfibwmg    decimal(2,0) default 0 not null,
  ptfibwmc    char(50) default ' ' not null,
  ptfitbds    decimal(2,0) default 0 not null,
  ptfitbdg    decimal(2,0) default 0 not null,
  ptfitbdc    char(50) default ' ' not null,
  ptfittls    decimal(2,0) default 0 not null,
  ptfittlg    decimal(2,0) default 0 not null,
  ptfittlc    char(50) default ' ' not null,
  ptfitbts    decimal(2,0) default 0 not null,
  ptfitbtg    decimal(2,0) default 0 not null,
  ptfitbtc    char(50) default ' ' not null,
  ptfilocd    char(3) default ' ' not null,
  ptfilocs    decimal(2,0) default 0 not null,
  ptfilocg    decimal(2,0) default 0 not null,
  ptfilocc    char(50) default ' ' not null,
  ptfistrs    decimal(2,0) default 0 not null,
  ptfistrg    decimal(2,0) default 0 not null,
  ptfistrc    char(50) default ' ' not null,
  ptficocd    char(3) default ' ' not null,
  ptficoms    decimal(2,0) default 0 not null,
  ptficomg    decimal(2,0) default 0 not null,
  ptficomc    char(50) default ' ' not null,
  ptfiexcd    char(3) default ' ' not null,
  ptfiexps    decimal(2,0) default 0 not null,
  ptfiexpg    decimal(2,0) default 0 not null,
  ptfiexpc    char(50) default ' ' not null,
  ptfiscis    decimal(2,0) default 0 not null,
  ptfiscig    decimal(2,0) default 0 not null,
  ptfiscic    char(50) default ' ' not null,
  ptfiprbs    decimal(2,0) default 0 not null,
  ptfiprbg    decimal(2,0) default 0 not null,
  ptfiprbc    char(50) default ' ' not null,
  ptfimems    decimal(2,0) default 0 not null,
  ptfimemg    decimal(2,0) default 0 not null,
  ptfimemc    char(50) default ' ' not null,
  ptfiases    char(1) default ' ' not null,
  ptfiascd    char(10) default ' ' not null,
  ptfiasdn    char(3) default ' ' not null,
  ptfinscd    char(10) default ' ' not null,
  ptfinsid    char(10) default ' ' not null,
  ptfinsdt    char(8) default ' ' not null,
  ptfinstm    char(8) default ' ' not null,
  ptfiphcd    char(10) default ' ' not null,
  ptfiphdt    char(8) default ' ' not null,
  ptfiphtm    char(8) default ' ' not null,
  ptfiotcd    char(10) default ' ' not null,
  ptfiotdt    char(8) default ' ' not null,
  ptfiottm    char(8) default ' ' not null,
  ptfidelt    char(1) default ' ' not null,
  ptficuid    char(10) default ' ' not null,
  ptficdat    char(8) default ' ' not null,
  ptfictim    char(8) default ' ' not null,
  ptfiuuid    char(10) default ' ' not null,
  ptfiudat    char(8) default ' ' not null,
  ptfiutim    char(8) default ' ' not null,
  ptfiduid    char(10) default ' ' not null,
  ptfiddat    char(8) default ' ' not null,
  ptfidtim    char(8) default ' ' not null,
  ptfiimpc    char(7) default ' ' not null,
  ptficplt    char(1) default ' ' not null,
  ptfifuid    char(10) default ' ' not null,
  ptfifdte    char(8) default ' ' not null,
  ptfiftme    char(8) default ' ' not null,
  ptfidres    char(3) default ' ' not null,
  ptfispar    char(50) default ' ' not null,
  lf          char(1)
);
create unique index patfima1 on patfimaf
(
ptfivisn,
ptfidate,
ptfitime
);
revoke all on patfimaf from public ; 
grant select on patfimaf to public ; 
