create table patfapaf
(
ptfpclai    char(3),
ptfpacpl    char(3),
ptfpfac1    char(3),
ptfpdfa1    char(3),
ptfpplt1    char(1),
ptfppin1    char(1),
ptfpocg1    char(3),
ptfpfac2    char(3),
ptfpdfa2    char(3),
ptfpplt2    char(1),
ptfppin2    char(1),
ptfpocg2    char(3),
ptfpfac3    char(3),
ptfpdfa3    char(3),
ptfpplt3    char(1),
ptfppin3    char(1),
ptfpocg3    char(3),
ptfpfac4    char(3),
ptfpdfa4    char(3),
ptfpplt4    char(1),
ptfppin4    char(1),
ptfpocg4    char(3),
ptfpfac5    char(3),
ptfpdfa5    char(3),
ptfpplt5    char(1),
ptfppin5    char(1),
ptfpocg5    char(3),
ptfpfac6    char(3),
ptfpdfa6    char(3),
ptfpplt6    char(1),
ptfppin6    char(1),
ptfpocg6    char(3),
ptfpfac7    char(3),
ptfpdfa7    char(3),
ptfpplt7    char(1),
ptfppin7    char(1),
ptfpocg7    char(3),
ptfpfac8    char(3),
ptfpdfa8    char(3),
ptfpplt8    char(1),
ptfppin8    char(1),
ptfpocg8    char(3),
ptfpfac9    char(3),
ptfpdfa9    char(3),
ptfpplt9    char(1),
ptfppin9    char(1),
ptfpocg9    char(3),
ptfpfac0    char(3),
ptfpdfa0    char(3),
ptfpplt0    char(1),
ptfppin0    char(1),
ptfpocg0    char(3),
ptfpspar    char(77),
lf          char(1)
);
create unique index patfapa1 on patfapaf
(
ptfpclai,
ptfpacpl
);
revoke all on patfapaf from public ; 
grant select on patfapaf to public ; 
