create table pathtraf
(
  pthtadmn    char(8) default ' ' not null,
  pthttrns    char(6) default ' ' not null,
  pthttdeb    char(1) default ' ' not null,
  pthtdcod    char(8) default ' ' not null,
  pthtamtt    decimal(14,2) default 0 not null,
  pthtamtg    decimal(14,2) default 0 not null,
  pthtamth    decimal(14,2) default 0 not null,
  pthtamti    decimal(14,2) default 0 not null,
  pthtamtp    decimal(14,2) default 0 not null,
  pthtfcen    char(2) default ' ' not null,
  pthtfyer    char(2) default ' ' not null,
  pthtfmon    char(2) default ' ' not null,
  pthtfday    char(2) default ' ' not null,
  pthttcen    char(2) default ' ' not null,
  pthttyer    decimal(2,0) default 0 not null,
  pthttmon    decimal(2,0) default 0 not null,
  pthttday    decimal(2,0) default 0 not null,
  pthtttyp    char(2) default ' ' not null,
  pthtitem    char(9) default ' ' not null,
  pthttref    char(8) default ' ' not null,
  pthtpayt    decimal(1,0) default 0 not null,
  pthtrcpt    char(12) default ' ' not null,
  pthtdesc    char(30) default ' ' not null,
  pthtinvp    decimal(1,0) default 0 not null,
  pthtrect    char(1) default ' ' not null,
  pthtnday    decimal(4,0) default 0 not null,
  pthtclmd    decimal(1,0) default 0 not null,
  pthtrbat    decimal(14,2) default 0 not null,
  pthtdoct    char(6) default ' ' not null,
  pthtserv    decimal(5,0) default 0 not null,
  pthtdoco    char(6) default ' ' not null,
  pthtpinv    char(8) default ' ' not null,
  pthtptrn    char(6) default ' ' not null,
  pthtsess    char(2) default ' ' not null,
  pthtmisg    char(3) default ' ' not null,
  pthtdept    char(3) default ' ' not null,
  pthtward    char(3) default ' ' not null,
  pthtclmt    char(3) default ' ' not null,
  pthtadmt    char(3) default ' ' not null,
  pthtbtch    char(8) default ' ' not null,
  pthtninv    decimal(1,0) default 0 not null,
  pthtlspt    decimal(14,2) default 0 not null,
  pthtlsrb    decimal(14,2) default 0 not null,
  pthtdtyp    decimal(1,0) default 0 not null,
  pthtdes2    char(35) default ' ' not null,
  pthtepsd    decimal(1,0) default 0 not null,
  pthttccu    decimal(1,0) default 0 not null,
  pthtgsta    decimal(1,0) default 0 not null,
  pthtgstc    char(6) default ' ' not null,
  pthtgstm    decimal(14,2) default 0 not null,
  pthteffd    char(8) default ' ' not null,
  pthtgstl    decimal(14,2) default 0 not null,
  pthtttim    char(8) default ' ' not null,
  pthtcrst    char(1) default ' ' not null,
  pthtuniq    char(10) default ' ' not null,
  pthtbtyp    char(3) default ' ' not null,
  pthtcntr    char(6) default ' ' not null,
  pthtsunq    char(3) default ' ' not null,
  pthtbatc    char(16) default ' ' not null,
  pthtadpt    decimal(14,2) default 0 not null,
  pthtadrb    decimal(14,2) default 0 not null,
  pthtcnid    char(6) default ' ' not null,
  pthtlsd1    char(30) default ' ' not null,
  pthtlsd2    char(35) default ' ' not null,
  pthttmno    char(1) default ' ' not null,
  pthtpmbs    char(3) default ' ' not null,
  pthtpcod    char(3) default ' ' not null,
  pthtspar    char(100) default ' ' not null,
  lf          char(1)
);
create unique index pathtra1 on pathtraf
(
pthtadmn,
pthttref,
pthttrns
);
create unique index pathtra2 on pathtraf
(
pthtadmn,
pthtpinv,
pthtptrn,
pthttref,
pthttrns
);
revoke all on pathtraf from public ; 
grant select on pathtraf to public ; 
