create table pathspaf
(
  pthshosp    char(3) default ' ' not null,
  pthsname    char(50) default ' ' not null,
  pthsadd1    char(35) default ' ' not null,
  pthsadd2    char(35) default ' ' not null,
  pthsadd3    char(35) default ' ' not null,
  pthsadd4    char(35) default ' ' not null,
  pthspcod    char(8) default ' ' not null,
  pthstele    char(20) default ' ' not null,
  pthsfaxn    char(20) default ' ' not null,
  pthsunit    char(5) default ' ' not null,
  pthshdpc    char(8) default ' ' not null,
  pthsmrpr    char(6) default ' ' not null,
  pthspact    char(12) default ' ' not null,
  pthshsno    char(2) default ' ' not null,
  pthspmbs    char(1) default ' ' not null,
  pthstfee    char(1) default ' ' not null,
  pthshloc    char(4) default ' ' not null,
  pthsrcty    char(3) default ' ' not null,
  pthsvolm    char(2) default ' ' not null,
  pthsstat    char(3) default ' ' not null,
  pthsdclm    char(3) default ' ' not null,
  pthsappr    char(10) default ' ' not null,
  pthsufms    char(1) default ' ' not null,
  pthsabnn    char(11) default ' ' not null,
  pthshsid    char(5) default ' ' not null,
  pthshcen    char(3) default ' ' not null,
  pthsptin    char(1) default ' ' not null,
  pthsspid    char(1) default ' ' not null,
  pthsedip    char(2) default ' ' not null,
  pthsorid    char(8) default ' ' not null,
  pthsmorg    char(1) default ' ' not null,
  pthschot    char(1) default ' ' not null,
  pthschod    char(1) default ' ' not null,
  pthshost    char(1) default ' ' not null,
  pthsudva    char(1) default ' ' not null,
  pthslocn    char(8) default ' ' not null,
  pthserre    char(3) default ' ' not null,
  pthsercd    char(6) default ' ' not null,
  pthserca    char(15) default ' ' not null,
  pthscfcd    char(6) default ' ' not null,
  pthsemal    char(80) default ' ' not null,
  pthsersr    char(3) default ' ' not null,
  pthssnam    char(10) default ' ' not null,
  pthstord    char(1) default ' ' not null,
  pthshhos    char(3) default ' ' not null,
  pthscrsr    char(3) default ' ' not null,
  pthsrcop    char(10) default ' ' not null,
  pthshbid    char(4) default ' ' not null,
  pthsdcdt    char(4) default ' ' not null,
  pthshpio    char(20) default ' ' not null,
  pthscfst    char(3) default ' ' not null,
  pthshdhb    char(3) default ' ' not null,
  pthsagnc    char(3) default ' ' not null,
  pthsucrg    char(1) default ' ' not null,
  pthshsst    char(1) default ' ' not null,
  pthsactr    char(10) default ' ' not null,
  pthsagel    char(3) default ' ' not null,
  pthsageh    char(3) default ' ' not null,
  pthsmaph    char(2) default ' ' not null,
  pthsspar    char(16) default ' ' not null,
  lf          char(1)
);
create unique index pathspa1 on pathspaf
(
pthshosp
);
revoke all on pathspaf from public ; 
grant select on pathspaf to public ; 
