create table patinpaf
(
dptipadm    char(8),
ptipurno    char(8),
ptiprtyp    char(2),
ptipclam    char(3),
ptiphfnd    char(6),
ptipftbl    char(8),
ptipatyp    char(3),
ptipward    char(3),
ptipwbed    char(3),
ptipbtyp    char(3),
ptipbday    decimal(3,0),
ptipeday    decimal(3,0),
ptiplday    decimal(3,0),
ptipcuri    char(1),
ptipadat    char(8),
ptipddat    char(8),
ptipaccf    char(8),
ptipacct    char(8),
ptipadoc    char(6),
ptipfnam    char(54),
ptipdtyp    char(3),
ptipddoc    char(6),
ptiprdoc    char(6),
ptiproom    char(6),
ptipitem    char(9),
ptipmhdp    char(1),
ptipband    char(3),
dptiptrn    char(6),
ptipttyp    decimal(1,0),
ptiparev    decimal(14,2),
ptiptrev    decimal(14,2),
ptipprev    decimal(14,2),
ptiphrev    decimal(14,2),
ptipirev    decimal(14,2),
ptiplrev    decimal(14,2),
ptipmrev    decimal(14,2),
ptipgrev    decimal(14,2),
ptippmbs    char(9),
ptipgpor    decimal(14,2),
ptiporat    decimal(14,2),
ptipdrat    decimal(14,2),
ptipaddt    decimal(14,2),
ptipfreb    decimal(14,2),
ptipppor    decimal(14,2),
ptiprpor    decimal(14,2),
ptipctyp    decimal(1,0),
ptippdrg    char(9),
ptipndrg    char(4),
ptipsdrg    char(4),
ptipnmdc    char(4),
ptipsmdc    char(4),
ptipgrp1    char(3),
ptipgrp2    char(3),
ptipgrp3    char(3),
ptipcdat    char(8),
ptipctim    char(8),
ptipoper    char(4),
ptipgstu    char(1),
ptipspar    char(30),
lf          char(1)
);
create unique index patinpa1 on patinpaf
(
dptipadm,
ptiprtyp,
dptiptrn
);
revoke all on patinpaf from public ; 
grant select on patinpaf to public ; 
