create table patma1af
(
  purno       char(8) default ' ' not null,
  pport       char(2) default ' ' not null,
  pchgdte     char(8) default ' ' not null,
  ptitl       char(4) default ' ' not null,
  phosp       decimal(1,0) default 0 not null,
  pldays      decimal(3,0) default 0 not null,
  pbdebt      decimal(1,0) default 0 not null,
  psname      char(20) default ' ' not null,
  pgname      char(25) default ' ' not null,
  ppsname     char(19) default ' ' not null,
  padd1       char(35) default ' ' not null,
  padd2       char(35) default ' ' not null,
  psubrb      char(35) default ' ' not null,
  padd4       char(35) default ' ' not null,
  ppost       char(8) default ' ' not null,
  ptelep      char(20) default ' ' not null,
  pteleb      char(20) default ' ' not null,
  psex        char(1) default ' ' not null,
  pmstat      char(3) default ' ' not null,
  pbdate      char(8) default ' ' not null,
  psage       decimal(3,0) default 0 not null,
  pcont       char(3) default ' ' not null,
  preg        char(3) default ' ' not null,
  ptype       char(3) default ' ' not null,
  poccup      char(14) default ' ' not null,
  plddate     char(8) default ' ' not null,
  pmedi       char(10) default ' ' not null,
  ppenno      char(15) default ' ' not null,
  ppndte      char(6) default ' ' not null,
  prepat      char(10) default ' ' not null,
  psmok       decimal(1,0) default 0 not null,
  pstat       decimal(1,0) default 0 not null,
  pmicro      char(20) default ' ' not null,
  pcease      decimal(1,0) default 0 not null,
  pcase       decimal(1,0) default 0 not null,
  pautopy     decimal(1,0) default 0 not null,
  phigh1      char(3) default ' ' not null,
  phigh2      char(3) default ' ' not null,
  phigh3      char(3) default ' ' not null,
  plocdoc     char(30) default ' ' not null,
  pfundh      char(6) default ' ' not null,
  pfndtb      char(8) default ' ' not null,
  ptmaspar    char(10) default ' ' not null,
  pusr1       char(3) default ' ' not null,
  pusr2       char(3) default ' ' not null,
  pusr3       char(3) default ' ' not null,
  pusr4       char(3) default ' ' not null,
  pusr5       char(3) default ' ' not null,
  pusr6       char(3) default ' ' not null,
  puyn1       decimal(1,0) default 0 not null,
  puyn2       decimal(1,0) default 0 not null,
  puyn3       decimal(1,0) default 0 not null,
  pyrres      decimal(2,0) default 0 not null,
  pnkname     char(20) default ' ' not null,
  pnkadd1     char(35) default ' ' not null,
  pnkadd2     char(35) default ' ' not null,
  pnksubr     char(35) default ' ' not null,
  pnkadd4     char(35) default ' ' not null,
  pnkpost     char(8) default ' ' not null,
  pnktelp     char(20) default ' ' not null,
  pnktelb     char(20) default ' ' not null,
  pnkrelp     char(10) default ' ' not null,
  plstinp     char(8) default ' ' not null,
  plstout     char(8) default ' ' not null,
  pnxray      decimal(3,0) default 0 not null,
  pfndyy      char(2) default ' ' not null,
  pfndcg      char(6) default ' ' not null,
  pdecdte     char(8) default ' ' not null,
  phcnotes    char(20) default ' ' not null,
  pdiet       char(3) default ' ' not null,
  pinithos    char(2) default ' ' not null,
  phkaduni    char(10) default ' ' not null,
  ptmaempc    char(6) default ' ' not null,
  ptmanoko    char(14) default ' ' not null,
  ptmanoke    char(6) default ' ' not null,
  ptmadcno    char(10) default ' ' not null,
  ptmaukdb    char(1) default ' ' not null,
  ptmaukdd    char(1) default ' ' not null,
  pfndmm      char(19) default ' ' not null,
  ptmadcdt    char(8) default ' ' not null,
  ptmahcp1    char(10) default ' ' not null,
  ptmahcl1    char(10) default ' ' not null,
  ptmahcg1    char(2) default ' ' not null,
  ptmahcp2    char(10) default ' ' not null,
  ptmahcl2    char(10) default ' ' not null,
  ptmahcg2    char(2) default ' ' not null,
  ptmahcp3    char(10) default ' ' not null,
  ptmahcl3    char(10) default ' ' not null,
  ptmahcg3    char(2) default ' ' not null,
  ptmahcp4    char(10) default ' ' not null,
  ptmahcl4    char(10) default ' ' not null,
  ptmahcg4    char(2) default ' ' not null,
  ptmahcp5    char(10) default ' ' not null,
  ptmahcl5    char(10) default ' ' not null,
  ptmahcg5    char(2) default ' ' not null,
  ptmasnam    char(40) default ' ' not null,
  ptmadcud    char(8) default ' ' not null,
  ptmadcut    char(8) default ' ' not null,
  ptmadcuu    char(10) default ' ' not null,
  ptmauuid    char(10) default ' ' not null,
  ptmautim    char(8) default ' ' not null,
  ptmaspa2    char(10) default ' ' not null,
  lf          char(1)
);
create unique index patma1a1 on patma1af
(
purno
);
create  index patma1a2 on patma1af
(
pbdate
);
create unique index patma1a3 on patma1af
(
pmedi,
purno
);
create unique index patma1a4 on patma1af
(
ppsname,
purno
);
revoke all on patma1af from public ; 
grant select on patma1af to public ; 
