create table patmtdaf
(
  dptmdadm    char(8) default ' ' not null,
  ptmdmadm    decimal(4,0) default 0 not null,
  ptmdmsep    decimal(4,0) default 0 not null,
  ptmdmsts    decimal(4,0) default 0 not null,
  ptmdmlve    decimal(3,0) default 0 not null,
  ptmdminh    decimal(4,0) default 0 not null,
  ptmdmbed    decimal(5,0) default 0 not null,
  ptmdmhas    decimal(4,0) default 0 not null,
  ptmdmhab    decimal(5,0) default 0 not null,
  ptmdmpas    decimal(4,0) default 0 not null,
  ptmdmpab    decimal(5,0) default 0 not null,
  ptmdmhns    decimal(4,0) default 0 not null,
  ptmdmhnb    decimal(5,0) default 0 not null,
  ptmdmpns    decimal(4,0) default 0 not null,
  ptmdmpnb    decimal(5,0) default 0 not null,
  ptmdmh5s    decimal(4,0) default 0 not null,
  ptmdmh5b    decimal(5,0) default 0 not null,
  ptmdmp5s    decimal(4,0) default 0 not null,
  ptmdmp5b    decimal(5,0) default 0 not null,
  ptmdmcos    decimal(4,0) default 0 not null,
  ptmdmcob    decimal(5,0) default 0 not null,
  ptmdmcns    decimal(4,0) default 0 not null,
  ptmdmcnb    decimal(5,0) default 0 not null,
  ptmdmies    decimal(4,0) default 0 not null,
  ptmdmieb    decimal(5,0) default 0 not null,
  ptmdmins    decimal(4,0) default 0 not null,
  ptmdminb    decimal(5,0) default 0 not null,
  ptmdmhcs    decimal(4,0) default 0 not null,
  ptmdmhcb    decimal(5,0) default 0 not null,
  ptmdmpcs    decimal(4,0) default 0 not null,
  ptmdmpcb    decimal(5,0) default 0 not null,
  ptmdyhat    decimal(6,0) default 0 not null,
  ptmdypat    decimal(6,0) default 0 not null,
  ptmdycot    decimal(6,0) default 0 not null,
  ptmdyiet    decimal(6,0) default 0 not null,
  ptmdyhnt    decimal(6,0) default 0 not null,
  ptmdypnt    decimal(6,0) default 0 not null,
  ptmdyh5t    decimal(6,0) default 0 not null,
  ptmdyp5t    decimal(6,0) default 0 not null,
  ptmdyhct    decimal(6,0) default 0 not null,
  ptmdypct    decimal(6,0) default 0 not null,
  ptmdycnt    decimal(6,0) default 0 not null,
  ptmdyint    decimal(6,0) default 0 not null,
  ptmdmhsd    decimal(4,0) default 0 not null,
  ptmdmpsd    decimal(4,0) default 0 not null,
  ptmdmcsd    decimal(4,0) default 0 not null,
  ptmdmisd    decimal(4,0) default 0 not null,
  ptmdmhcd    decimal(4,0) default 0 not null,
  ptmdmpcd    decimal(4,0) default 0 not null,
  ptmdform    decimal(1,0) default 0 not null,
  ptmdmuep    decimal(3,0) default 0 not null,
  ptmdmubd    decimal(4,0) default 0 not null,
  ptmdhosp    char(3) default ' ' not null,
  ptmdmops    decimal(2,0) default 0 not null,
  ptmdmopb    decimal(3,0) default 0 not null,
  ptmdyopt    decimal(5,0) default 0 not null,
  ptmdspar    char(52) default ' ' not null,
  lf          char(1)
);
create unique index patmtda1 on patmtdaf
(
dptmdadm
);
revoke all on patmtdaf from public ; 
grant select on patmtdaf to public ; 
