create table patmx1af
(
  purno       char(8) default ' ' not null,
  ptmxrdat    char(8) default ' ' not null,
  ptmxmeal    char(30) default ' ' not null,
  ptmxlga     char(4) default ' ' not null,
  ptmxls      char(3) default ' ' not null,
  ptmxlsdt    char(8) default ' ' not null,
  ptmxfhmd    char(1) default ' ' not null,
  ptmxmhu1    char(3) default ' ' not null,
  ptmxmhu2    char(3) default ' ' not null,
  ptmxmhu3    char(3) default ' ' not null,
  ptmxecnm    char(20) default ' ' not null,
  ptmxeca1    char(35) default ' ' not null,
  ptmxeca2    char(35) default ' ' not null,
  ptmxeca3    char(35) default ' ' not null,
  ptmxeca4    char(35) default ' ' not null,
  ptmxecpc    char(8) default ' ' not null,
  ptmxecpp    char(20) default ' ' not null,
  ptmxecbp    char(20) default ' ' not null,
  ptmxecre    char(10) default ' ' not null,
  ptmxnrnm    char(20) default ' ' not null,
  ptmxnra1    char(35) default ' ' not null,
  ptmxnra2    char(35) default ' ' not null,
  ptmxnra3    char(35) default ' ' not null,
  ptmxnra4    char(35) default ' ' not null,
  ptmxnrpc    char(8) default ' ' not null,
  ptmxnrpp    char(20) default ' ' not null,
  ptmxnrbp    char(20) default ' ' not null,
  ptmxnrre    char(10) default ' ' not null,
  ptmx3bex    char(8) default ' ' not null,
  ptmxcard    char(20) default ' ' not null,
  ptmxcexp    char(8) default ' ' not null,
  ptmxcxmp    char(3) default ' ' not null,
  ptmxfmly    char(12) default ' ' not null,
  ptmxchnm    char(20) default ' ' not null,
  ptmxdofr    char(3) default ' ' not null,
  ptmxregp    char(8) default ' ' not null,
  ptmxgppc    char(6) default ' ' not null,
  ptmxspid    char(20) default ' ' not null,
  ptmxgppt    char(2) default ' ' not null,
  ptmxosdt    char(8) default ' ' not null,
  ptmxoper    char(4) default ' ' not null,
  ptmxukdo    char(1) default ' ' not null,
  ptmxcell    char(20) default ' ' not null,
  ptmxadd1    char(35) default ' ' not null,
  ptmxadd2    char(35) default ' ' not null,
  ptmxadd3    char(35) default ' ' not null,
  ptmxadd4    char(35) default ' ' not null,
  ptmxpost    char(8) default ' ' not null,
  ptmxmccd    char(2) default ' ' not null,
  ptmxsin1    char(1) default ' ' not null,
  ptmxsin2    char(1) default ' ' not null,
  ptmxsin3    char(1) default ' ' not null,
  ptmxsin4    char(1) default ' ' not null,
  ptmxsin5    char(1) default ' ' not null,
  ptmxctim    char(20) default ' ' not null,
  ptmxslac    char(8) default ' ' not null,
  ptmxfiln    char(3) default ' ' not null,
  ptmxdeaf    char(3) default ' ' not null,
  ptmxosms    char(1) default ' ' not null,
  ptmxuuid    char(10) default ' ' not null,
  ptmxespf    char(2) default ' ' not null,
  ptmxspar    char(48) default ' ' not null,
  lf          char(1)
);
create unique index patmx1a1 on patmx1af
(
purno
);
revoke all on patmx1af from public ; 
grant select on patmx1af to public ; 
