create table patptdaf
(
  dptpdadm    char(8) default ' ' not null,
  ptpdmadm    decimal(4,0) default 0 not null,
  ptpdmsep    decimal(4,0) default 0 not null,
  ptpdmsts    decimal(4,0) default 0 not null,
  ptpdmlve    decimal(3,0) default 0 not null,
  ptpdminh    decimal(4,0) default 0 not null,
  ptpdmbed    decimal(5,0) default 0 not null,
  ptpdmhas    decimal(4,0) default 0 not null,
  ptpdmhab    decimal(5,0) default 0 not null,
  ptpdmpas    decimal(4,0) default 0 not null,
  ptpdmpab    decimal(5,0) default 0 not null,
  ptpdmhns    decimal(4,0) default 0 not null,
  ptpdmhnb    decimal(5,0) default 0 not null,
  ptpdmpns    decimal(4,0) default 0 not null,
  ptpdmpnb    decimal(5,0) default 0 not null,
  ptpdmh5s    decimal(4,0) default 0 not null,
  ptpdmh5b    decimal(5,0) default 0 not null,
  ptpdmp5s    decimal(4,0) default 0 not null,
  ptpdmp5b    decimal(5,0) default 0 not null,
  ptpdmcos    decimal(4,0) default 0 not null,
  ptpdmcob    decimal(5,0) default 0 not null,
  ptpdmcns    decimal(4,0) default 0 not null,
  ptpdmcnb    decimal(5,0) default 0 not null,
  ptpdmies    decimal(4,0) default 0 not null,
  ptpdmieb    decimal(5,0) default 0 not null,
  ptpdmins    decimal(4,0) default 0 not null,
  ptpdminb    decimal(5,0) default 0 not null,
  ptpdmhcs    decimal(4,0) default 0 not null,
  ptpdmhcb    decimal(5,0) default 0 not null,
  ptpdmpcs    decimal(4,0) default 0 not null,
  ptpdmpcb    decimal(5,0) default 0 not null,
  ptpdyhat    decimal(6,0) default 0 not null,
  ptpdypat    decimal(6,0) default 0 not null,
  ptpdycot    decimal(6,0) default 0 not null,
  ptpdyiet    decimal(6,0) default 0 not null,
  ptpdyhnt    decimal(6,0) default 0 not null,
  ptpdypnt    decimal(6,0) default 0 not null,
  ptpdyh5t    decimal(6,0) default 0 not null,
  ptpdyp5t    decimal(6,0) default 0 not null,
  ptpdyhct    decimal(6,0) default 0 not null,
  ptpdypct    decimal(6,0) default 0 not null,
  ptpdycnt    decimal(6,0) default 0 not null,
  ptpdyint    decimal(6,0) default 0 not null,
  ptpdmhsd    decimal(4,0) default 0 not null,
  ptpdmpsd    decimal(4,0) default 0 not null,
  ptpdmcsd    decimal(4,0) default 0 not null,
  ptpdmisd    decimal(4,0) default 0 not null,
  ptpdmhcd    decimal(4,0) default 0 not null,
  ptpdmpcd    decimal(4,0) default 0 not null,
  ptpdform    decimal(1,0) default 0 not null,
  ptpdmuep    decimal(3,0) default 0 not null,
  ptpdmubd    decimal(4,0) default 0 not null,
  ptpdhosp    char(3) default ' ' not null,
  ptpdmops    decimal(2,0) default 0 not null,
  ptpdmopb    decimal(3,0) default 0 not null,
  ptpdyopt    decimal(5,0) default 0 not null,
  ptpdspar    char(52) default ' ' not null,
  lf          char(1)
);
create unique index patptda1 on patptdaf
(
dptpdadm
);
revoke all on patptdaf from public ; 
grant select on patptdaf to public ; 
