create table patytdaf
(
  dptydadm    char(8) default ' ' not null,
  ptydyadm    decimal(5,0) default 0 not null,
  ptydysep    decimal(5,0) default 0 not null,
  ptydysts    decimal(5,0) default 0 not null,
  ptydybed    decimal(6,0) default 0 not null,
  ptydyhas    decimal(5,0) default 0 not null,
  ptydyhab    decimal(6,0) default 0 not null,
  ptydyhat    decimal(6,0) default 0 not null,
  ptydypas    decimal(5,0) default 0 not null,
  ptydypab    decimal(6,0) default 0 not null,
  ptydypat    decimal(6,0) default 0 not null,
  ptydycos    decimal(5,0) default 0 not null,
  ptydycob    decimal(6,0) default 0 not null,
  ptydycot    decimal(6,0) default 0 not null,
  ptydyies    decimal(5,0) default 0 not null,
  ptydyieb    decimal(6,0) default 0 not null,
  ptydyiet    decimal(6,0) default 0 not null,
  ptydyhns    decimal(5,0) default 0 not null,
  ptydyhnb    decimal(6,0) default 0 not null,
  ptydyhnt    decimal(6,0) default 0 not null,
  ptydypns    decimal(5,0) default 0 not null,
  ptydypnb    decimal(6,0) default 0 not null,
  ptydypnt    decimal(6,0) default 0 not null,
  ptydyh5s    decimal(5,0) default 0 not null,
  ptydyh5b    decimal(6,0) default 0 not null,
  ptydyh5t    decimal(6,0) default 0 not null,
  ptydyp5s    decimal(5,0) default 0 not null,
  ptydyp5b    decimal(6,0) default 0 not null,
  ptydyp5t    decimal(6,0) default 0 not null,
  ptydyhcs    decimal(5,0) default 0 not null,
  ptydyhcb    decimal(6,0) default 0 not null,
  ptydyhct    decimal(6,0) default 0 not null,
  ptydypcs    decimal(5,0) default 0 not null,
  ptydypcb    decimal(6,0) default 0 not null,
  ptydypct    decimal(6,0) default 0 not null,
  ptydycns    decimal(5,0) default 0 not null,
  ptydycnb    decimal(6,0) default 0 not null,
  ptydycnt    decimal(6,0) default 0 not null,
  ptydyins    decimal(5,0) default 0 not null,
  ptydyinb    decimal(6,0) default 0 not null,
  ptydyint    decimal(6,0) default 0 not null,
  ptydyhsd    decimal(5,0) default 0 not null,
  ptydypsd    decimal(5,0) default 0 not null,
  ptydycsd    decimal(5,0) default 0 not null,
  ptydyisd    decimal(5,0) default 0 not null,
  ptydyhcd    decimal(5,0) default 0 not null,
  ptydypcd    decimal(5,0) default 0 not null,
  ptydform    decimal(1,0) default 0 not null,
  ptydyuep    decimal(4,0) default 0 not null,
  ptydyubd    decimal(5,0) default 0 not null,
  ptyddtdl    char(8) default ' ' not null,
  ptydhosp    char(3) default ' ' not null,
  ptydyops    decimal(4,0) default 0 not null,
  ptydyopb    decimal(5,0) default 0 not null,
  ptydyopt    decimal(5,0) default 0 not null,
  ptydspar    char(50) default ' ' not null,
  lf          char(1)
);
create unique index patytda1 on patytdaf
(
dptydadm
);
revoke all on patytdaf from public ; 
grant select on patytdaf to public ; 
