create table pmsapgaf
(
  pmagurno    char(8) default ' ' not null,
  pmagatyp    char(3) default ' ' not null,
  pmagclam    char(3) default ' ' not null,
  pmagfund    char(6) default ' ' not null,
  pmagtabt    char(3) default ' ' not null,
  pmagedat    char(8) default ' ' not null,
  pmagpcde    char(8) default ' ' not null,
  pmagicde    char(7) default ' ' not null,
  pmagvers    char(2) default ' ' not null,
  pmagsnap    char(3) default ' ' not null,
  pmagmest    char(3) default ' ' not null,
  pmagmeen    char(3) default ' ' not null,
  pmagfadm    char(1) default ' ' not null,
  pmagtimp    char(1) default ' ' not null,
  pmagdadm    char(8) default ' ' not null,
  pmagtocc    char(3) default ' ' not null,
  pmagemor    char(1) default ' ' not null,
  pmagcmr1    char(3) default ' ' not null,
  pmagcmr2    char(3) default ' ' not null,
  pmagcmr3    char(3) default ' ' not null,
  pmagcmr4    char(3) default ' ' not null,
  pmagcmp1    char(3) default ' ' not null,
  pmagcmp2    char(3) default ' ' not null,
  pmagcmp3    char(3) default ' ' not null,
  pmagcmp4    char(3) default ' ' not null,
  pmagasso    char(1) default ' ' not null,
  pmagacpa    char(3) default ' ' not null,
  pmagacpd    char(3) default ' ' not null,
  pmaglspa    char(3) default ' ' not null,
  pmaglspd    char(3) default ' ' not null,
  pmagemst    char(3) default ' ' not null,
  pmagrfdt    char(8) default ' ' not null,
  pmagdart    char(8) default ' ' not null,
  pmagsrpd    char(1) default ' ' not null,
  pmagsrps    char(1) default ' ' not null,
  pmagsrpn    char(1) default ' ' not null,
  pmagsrpa    char(1) default ' ' not null,
  pmagsrpp    char(1) default ' ' not null,
  pmagsrpm    char(1) default ' ' not null,
  pmagsrpg    char(1) default ' ' not null,
  pmagsrpt    char(1) default ' ' not null,
  pmagsrpc    char(1) default ' ' not null,
  pmagdrae    char(8) default ' ' not null,
  pmagemsa    char(3) default ' ' not null,
  pmagdcrd    char(8) default ' ' not null,
  pmagsrad    char(1) default ' ' not null,
  pmagsras    char(1) default ' ' not null,
  pmagsran    char(1) default ' ' not null,
  pmagsraa    char(1) default ' ' not null,
  pmagsrap    char(1) default ' ' not null,
  pmagsram    char(1) default ' ' not null,
  pmagsrag    char(1) default ' ' not null,
  pmagsrat    char(1) default ' ' not null,
  pmagsrac    char(1) default ' ' not null,
  pmagdefp    char(8) default ' ' not null,
  pmagcamn    char(1) default ' ' not null,
  pmagesas    char(3) default ' ' not null,
  pmagessc    char(3) default ' ' not null,
  pmageesc    char(3) default ' ' not null,
  pmagvdee    char(1) default ' ' not null,
  pmageeas    char(3) default ' ' not null,
  pmagdrca    char(8) default ' ' not null,
  pmagpacs    char(3) default ' ' not null,
  pmagdwpc    char(1) default ' ' not null,
  pmagpppc    char(1) default ' ' not null,
  pmagappc    char(1) default ' ' not null,
  pmagpace    char(3) default ' ' not null,
  pmagpros    char(1) default ' ' not null,
  pmagdfpf    char(8) default ' ' not null,
  pmagrdif    char(3) default ' ' not null,
  pmagdtug    decimal(3,1) default 0 not null,
  pmagd06m    decimal(4,1) default 0 not null,
  pmagd10m    decimal(3,1) default 0 not null,
  pmagfrai    char(3) default ' ' not null,
  pmagpitd    char(1) default ' ' not null,
  pmagf12m    char(1) default ' ' not null,
  pmagwl12    char(1) default ' ' not null,
  pmagdcrc    char(10) default ' ' not null,
  pmagides    char(3) default ' ' not null,
  pmagudt1    char(8) default ' ' not null,
  pmagudt2    char(8) default ' ' not null,
  pmagudt3    char(8) default ' ' not null,
  pmaguct1    char(3) default ' ' not null,
  pmaguct2    char(3) default ' ' not null,
  pmaguct3    char(3) default ' ' not null,
  pmaguct4    char(3) default ' ' not null,
  pmaguct5    char(3) default ' ' not null,
  pmaguyn1    char(1) default ' ' not null,
  pmaguyn2    char(1) default ' ' not null,
  pmaguyn3    char(1) default ' ' not null,
  pmaguyn4    char(1) default ' ' not null,
  pmaguyn5    char(1) default ' ' not null,
  pmagcdat    char(8) default ' ' not null,
  pmagctim    char(8) default ' ' not null,
  pmagcuid    char(10) default ' ' not null,
  pmagudat    char(8) default ' ' not null,
  pmagutim    char(8) default ' ' not null,
  pmaguuid    char(10) default ' ' not null,
  pmagdugo    char(4) default ' ' not null,
  pmagdwlk    char(4) default ' ' not null,
  pmagspar    char(92) default ' ' not null,
  lf          char(1)
);
create unique index pmsapga1 on pmsapgaf
(
pmagurno,
pmagatyp,
pmagclam,
pmagfund,
pmagtabt,
pmagedat
);
revoke all on pmsapgaf from public ; 
grant select on pmsapgaf to public ; 
