create table pmsencaf
(
  pmenvisn    char(8) default ' ' not null,
  pmenenct    char(8) default ' ' not null,
  pmensdep    char(3) default ' ' not null,
  pmenshcp    char(10) default ' ' not null,
  pmensdat    char(8) default ' ' not null,
  pmenstim    char(8) default ' ' not null,
  pmenloca    char(3) default ' ' not null,
  pmenserv    char(6) default ' ' not null,
  pmensrvd    char(3) default ' ' not null,
  pmendiun    decimal(6,0) default 0 not null,
  pmendbun    decimal(6,0) default 0 not null,
  pmeninun    decimal(6,0) default 0 not null,
  pmenibun    decimal(6,0) default 0 not null,
  pmencomp    char(3) default ' ' not null,
  pmenbulk    char(3) default ' ' not null,
  pmenpurc    char(3) default ' ' not null,
  pmencont    char(3) default ' ' not null,
  pmentype    char(3) default ' ' not null,
  pmenrsta    char(1) default ' ' not null,
  pmenudt1    char(8) default ' ' not null,
  pmenutm1    char(8) default ' ' not null,
  pmenudt2    char(8) default ' ' not null,
  pmenutm2    char(8) default ' ' not null,
  pmenudt3    char(8) default ' ' not null,
  pmenutm3    char(8) default ' ' not null,
  pmenudt4    char(8) default ' ' not null,
  pmenutm4    char(8) default ' ' not null,
  pmenahc1    char(10) default ' ' not null,
  pmenahc2    char(10) default ' ' not null,
  pmenahc3    char(10) default ' ' not null,
  pmenahc4    char(10) default ' ' not null,
  pmenuhc1    char(10) default ' ' not null,
  pmenuhc2    char(10) default ' ' not null,
  pmenuhc3    char(10) default ' ' not null,
  pmenuhc4    char(10) default ' ' not null,
  pmenudi1    char(9) default ' ' not null,
  pmenudi2    char(9) default ' ' not null,
  pmenudi3    char(9) default ' ' not null,
  pmenffd1    char(80) default ' ' not null,
  pmenffd2    char(80) default ' ' not null,
  pmenffd3    char(80) default ' ' not null,
  pmenudp1    char(9) default ' ' not null,
  pmenudp2    char(9) default ' ' not null,
  pmenudp3    char(9) default ' ' not null,
  pmenuyn1    char(1) default ' ' not null,
  pmenuyn2    char(1) default ' ' not null,
  pmenuyn3    char(1) default ' ' not null,
  pmenuyn4    char(1) default ' ' not null,
  pmenuyn5    char(1) default ' ' not null,
  pmenuyn6    char(1) default ' ' not null,
  pmenuyn7    char(1) default ' ' not null,
  pmenuyn8    char(1) default ' ' not null,
  pmenuyn9    char(1) default ' ' not null,
  pmenuff1    char(80) default ' ' not null,
  pmenuff2    char(80) default ' ' not null,
  pmenuff3    char(80) default ' ' not null,
  pmenuc01    char(3) default ' ' not null,
  pmenuc02    char(3) default ' ' not null,
  pmenuc03    char(3) default ' ' not null,
  pmenuc04    char(3) default ' ' not null,
  pmenuc05    char(3) default ' ' not null,
  pmenuc06    char(3) default ' ' not null,
  pmenuc07    char(3) default ' ' not null,
  pmenuc08    char(3) default ' ' not null,
  pmenuc09    char(3) default ' ' not null,
  pmenuc10    char(3) default ' ' not null,
  pmenuc11    char(3) default ' ' not null,
  pmenuc12    char(3) default ' ' not null,
  pmenuc13    char(3) default ' ' not null,
  pmenuc14    char(3) default ' ' not null,
  pmenuc15    char(3) default ' ' not null,
  pmenuc16    char(3) default ' ' not null,
  pmenuc17    char(3) default ' ' not null,
  pmenuc18    char(3) default ' ' not null,
  pmenuc19    char(3) default ' ' not null,
  pmenuc20    char(3) default ' ' not null,
  pmenuc21    char(3) default ' ' not null,
  pmenuc22    char(3) default ' ' not null,
  pmenuc23    char(3) default ' ' not null,
  pmenuc24    char(3) default ' ' not null,
  pmenuc25    char(3) default ' ' not null,
  pmenuc26    char(3) default ' ' not null,
  pmenuc27    char(3) default ' ' not null,
  pmenuc28    char(3) default ' ' not null,
  pmenuc29    char(3) default ' ' not null,
  pmenuc30    char(3) default ' ' not null,
  pmenuc31    char(3) default ' ' not null,
  pmenuc32    char(3) default ' ' not null,
  pmenuc33    char(3) default ' ' not null,
  pmenuc34    char(3) default ' ' not null,
  pmenuc35    char(3) default ' ' not null,
  pmenuc36    char(3) default ' ' not null,
  pmenuc37    char(3) default ' ' not null,
  pmenuc38    char(3) default ' ' not null,
  pmenuc39    char(3) default ' ' not null,
  pmenuc40    char(3) default ' ' not null,
  pmenuf01    decimal(16,2) default 0 not null,
  pmenuf02    decimal(16,2) default 0 not null,
  pmenuf03    decimal(16,2) default 0 not null,
  pmenuf04    decimal(16,2) default 0 not null,
  pmenuf05    decimal(16,2) default 0 not null,
  pmenuf06    decimal(16,2) default 0 not null,
  pmenuf07    decimal(16,2) default 0 not null,
  pmenuf08    decimal(16,2) default 0 not null,
  pmenuf09    decimal(16,2) default 0 not null,
  pmenuf10    decimal(16,2) default 0 not null,
  pmenuf11    decimal(8,0) default 0 not null,
  pmenuf12    decimal(8,0) default 0 not null,
  pmenuf13    decimal(8,0) default 0 not null,
  pmenuf14    decimal(8,0) default 0 not null,
  pmenuf15    decimal(8,0) default 0 not null,
  pmenuf16    decimal(8,0) default 0 not null,
  pmenuf17    decimal(8,0) default 0 not null,
  pmenuf18    decimal(8,0) default 0 not null,
  pmenuf19    decimal(8,0) default 0 not null,
  pmenuf20    decimal(8,0) default 0 not null,
  pmencmt1    char(80) default ' ' not null,
  pmencmt2    char(80) default ' ' not null,
  pmencdat    char(8) default ' ' not null,
  pmenctim    char(8) default ' ' not null,
  pmencuid    char(10) default ' ' not null,
  pmenudat    char(8) default ' ' not null,
  pmenutim    char(8) default ' ' not null,
  pmenuuid    char(10) default ' ' not null,
  pmenssac    char(1) default ' ' not null,
  pmenmohr    char(1) default ' ' not null,
  pmenoutc    char(3) default ' ' not null,
  pmenaccn    char(20) default ' ' not null,
  pmenspar    char(50) default ' ' not null,
  lf          char(1)
);
create unique index pmsenca1 on pmsencaf
(
pmenvisn,
pmenenct
);
create unique index pmsenca2 on pmsencaf
(
pmenvisn,
pmensdat,
pmenstim,
pmenenct
);
revoke all on pmsencaf from public ; 
grant select on pmsencaf to public ; 
