create table pmsextaf
(
  pmexvisn    char(8) default ' ' not null,
  pmexclam    char(3) default ' ' not null,
  pmexname    char(50) default ' ' not null,
  pmexadd1    char(35) default ' ' not null,
  pmexadd2    char(35) default ' ' not null,
  pmexadd3    char(35) default ' ' not null,
  pmexadd4    char(35) default ' ' not null,
  pmexpost    char(8) default ' ' not null,
  pmextele    char(20) default ' ' not null,
  pmexadat    char(8) default ' ' not null,
  pmexabic    char(1) default ' ' not null,
  pmexicod    char(6) default ' ' not null,
  pmexclmn    char(20) default ' ' not null,
  pmexicon    char(50) default ' ' not null,
  pmexcom1    char(40) default ' ' not null,
  pmexcom2    char(40) default ' ' not null,
  pmexurno    char(8) default ' ' not null,
  pmexvdat    char(8) default ' ' not null,
  pmexodin    char(1) default ' ' not null,
  pmexserv    char(3) default ' ' not null,
  pmexrank    char(50) default ' ' not null,
  pmexsnum    char(20) default ' ' not null,
  pmexbase    char(50) default ' ' not null,
  pmexmcom    char(3) default ' ' not null,
  pmexunit    char(50) default ' ' not null,
  pmexmcnm    char(80) default ' ' not null,
  pmexssnm    char(20) default ' ' not null,
  pmexcont    char(3) default ' ' not null,
  pmexctel    char(20) default ' ' not null,
  pmexomem    char(20) default ' ' not null,
  pmexiedt    char(8) default ' ' not null,
  pmexsbil    char(1) default ' ' not null,
  pmextins    char(1) default ' ' not null,
  pmexipol    char(20) default ' ' not null,
  pmexiexd    char(8) default ' ' not null,
  pmexsnam    char(50) default ' ' not null,
  pmexsagn    char(50) default ' ' not null,
  pmexscon    char(50) default ' ' not null,
  pmexdat1    char(8) default ' ' not null,
  pmexdat2    char(8) default ' ' not null,
  pmexdat3    char(8) default ' ' not null,
  pmexdat4    char(8) default ' ' not null,
  pmexdat5    char(8) default ' ' not null,
  pmextim1    char(8) default ' ' not null,
  pmextim2    char(8) default ' ' not null,
  pmextim3    char(8) default ' ' not null,
  pmextim4    char(8) default ' ' not null,
  pmextim5    char(8) default ' ' not null,
  pmexuyn1    char(1) default ' ' not null,
  pmexuyn2    char(1) default ' ' not null,
  pmexuyn3    char(1) default ' ' not null,
  pmexuyn4    char(1) default ' ' not null,
  pmexuyn5    char(1) default ' ' not null,
  pmexcat1    char(3) default ' ' not null,
  pmexcat2    char(3) default ' ' not null,
  pmexcat3    char(3) default ' ' not null,
  pmexcat4    char(3) default ' ' not null,
  pmexcat5    char(3) default ' ' not null,
  pmexucm1    char(50) default ' ' not null,
  pmexucm2    char(50) default ' ' not null,
  pmexucm3    char(50) default ' ' not null,
  pmexucm4    char(50) default ' ' not null,
  pmexucm5    char(50) default ' ' not null,
  pmexslnm    char(50) default ' ' not null,
  pmexsad1    char(35) default ' ' not null,
  pmexsad2    char(35) default ' ' not null,
  pmexsad3    char(35) default ' ' not null,
  pmexsad4    char(35) default ' ' not null,
  pmexspos    char(8) default ' ' not null,
  pmexstel    char(20) default ' ' not null,
  pmexscnm    char(50) default ' ' not null,
  pmexvtyp    char(3) default ' ' not null,
  pmexvexp    char(8) default ' ' not null,
  pmexpasn    char(20) default ' ' not null,
  pmexpasc    char(3) default ' ' not null,
  pmexosvs    char(3) default ' ' not null,
  pmexbasc    char(3) default ' ' not null,
  pmexecon    char(50) default ' ' not null,
  pmexephn    char(20) default ' ' not null,
  pmexcad1    char(35) default ' ' not null,
  pmexcad2    char(35) default ' ' not null,
  pmexcad3    char(35) default ' ' not null,
  pmexcad4    char(35) default ' ' not null,
  pmexcpcd    char(8) default ' ' not null,
  pmexcnam    char(50) default ' ' not null,
  pmexcphn    char(20) default ' ' not null,
  pmexcinj    char(3) default ' ' not null,
  pmexincd    char(3) default ' ' not null,
  pmexaccf    char(3) default ' ' not null,
  pmexplin    char(3) default ' ' not null,
  pmexacti    char(3) default ' ' not null,
  pmexadte    char(8) default ' ' not null,
  pmexatme    char(8) default ' ' not null,
  pmexaclc    char(3) default ' ' not null,
  pmexaloc    char(50) default ' ' not null,
  pmexainz    char(1) default ' ' not null,
  pmexmovv    char(1) default ' ' not null,
  pmexspti    char(1) default ' ' not null,
  pmexsprt    char(3) default ' ' not null,
  pmexreci    char(1) default ' ' not null,
  pmextric    char(1) default ' ' not null,
  pmexesta    char(3) default ' ' not null,
  pmexpddt    char(8) default ' ' not null,
  pmexarg1    char(40) default ' ' not null,
  pmexarg2    char(40) default ' ' not null,
  pmexarsn    char(40) default ' ' not null,
  pmexartl    char(4) default ' ' not null,
  pmexarrp    char(10) default ' ' not null,
  pmexasst    char(1) default ' ' not null,
  pmexneed    char(1) default ' ' not null,
  pmexcnor    char(1) default ' ' not null,
  pmexaltw    char(1) default ' ' not null,
  pmextypa    char(3) default ' ' not null,
  pmexsalt    char(8) default ' ' not null,
  pmexhpda    char(2) default ' ' not null,
  pmexunfd    char(3) default ' ' not null,
  pmexunft    char(3) default ' ' not null,
  pmexfisd    char(8) default ' ' not null,
  pmexrnwd    char(8) default ' ' not null,
  pmexcsta    char(1) default ' ' not null,
  pmextwrk    char(3) default ' ' not null,
  pmexoest    char(50) default ' ' not null,
  pmextpro    char(10) default ' ' not null,
  pmexauth    char(20) default ' ' not null,
  pmexauda    char(8) default ' ' not null,
  pmexrefn    char(20) default ' ' not null,
  pmexpoli    char(20) default ' ' not null,
  pmexrego    char(36) default ' ' not null,
  pmexdrps    char(1) default ' ' not null,
  pmexengd    char(20) default ' ' not null,
  pmexinjr    char(30) default ' ' not null,
  pmexmtrn    char(10) default ' ' not null,
  pmexmsev    char(30) default ' ' not null,
  pmexrsev    char(20) default ' ' not null,
  pmexodd1    char(30) default ' ' not null,
  pmexodd2    char(30) default ' ' not null,
  pmexodd3    char(30) default ' ' not null,
  pmextclm    char(1) default ' ' not null,
  pmexmtyp    char(3) default ' ' not null,
  pmexalel    char(3) default ' ' not null,
  pmexpolc    char(1) default ' ' not null,
  pmexidno    char(20) default ' ' not null,
  pmexschl    char(6) default ' ' not null,
  pmexcuid    char(10) default ' ' not null,
  pmexcdat    char(8) default ' ' not null,
  pmexctim    char(8) default ' ' not null,
  pmexuuid    char(10) default ' ' not null,
  pmexudat    char(8) default ' ' not null,
  pmexutim    char(8) default ' ' not null,
  pmexdano    char(20) default ' ' not null,
  pmexpmkn    char(20) default ' ' not null,
  pmexfsrc    char(3) default ' ' not null,
  pmexhfnd    char(6) default ' ' not null,
  pmexftbl    char(8) default ' ' not null,
  pmexhfmn    char(19) default ' ' not null,
  pmexhfcn    char(40) default ' ' not null,
  pmexspar    char(40) default ' ' not null,
  lf          char(1)
);
create unique index pmsexta1 on pmsextaf
(
pmexvisn,
pmexclam
);
create unique index pmsexta2 on pmsextaf
(
pmexurno,
pmexvisn,
pmexclam
);
create unique index pmsexta3 on pmsextaf
(
pmexurno,
pmexadat,
pmexvisn,
pmexclam
);
revoke all on pmsextaf from public ; 
grant select on pmsextaf to public ; 
