create table pmsfidaf
(
pmfifino    char(12),
pmfiuniq    char(3),
pmfiurno    char(8),
pmfiadmn    char(8),
pmfiadat    char(8),
pmfistay    char(3),
pmfieddt    char(8),
pmficlty    char(3),
pmfihfnd    char(6),
pmfihftb    char(8),
pmfisgam    decimal(8,2),
pmfiagam    decimal(8,2),
pmfianga    decimal(8,2),
pmfiphyi    decimal(8,2),
pmfiphys    decimal(8,2),
pmfixray    decimal(8,2),
pmfisplb    decimal(8,2),
pmfimisc    decimal(8,2),
pmfiphar    decimal(8,2),
pmfipros    decimal(8,2),
pmfihexc    decimal(8,2),
pmfifast    char(50),
pmfidedt    char(5),
pmfieanp    char(10),
pmfithf1    char(9),
pmfithf2    char(9),
pmfithf3    char(9),
pmfithf4    char(9),
pmfithf5    char(9),
pmfithf6    char(9),
pmfimcc1    char(9),
pmfimcc2    char(9),
pmfimcc3    char(9),
pmfibtyp    char(3),
pmfiatyp    char(3),
pmfiagst    char(1),
pmfiecos    decimal(14,2),
pmfitpoa    decimal(14,2),
pmfieacp    decimal(14,2),
pmfieach    decimal(14,2),
pmfietcp    decimal(14,2),
pmfietch    decimal(14,2),
pmfiemcp    decimal(14,2),
pmfiemch    decimal(14,2),
pmfiqua1    decimal(3,0),
pmfiqua2    decimal(3,0),
pmfiqua3    decimal(3,0),
pmfithq1    decimal(3,0),
pmfithq2    decimal(3,0),
pmfithq3    decimal(3,0),
pmfithq4    decimal(3,0),
pmfithq5    decimal(3,0),
pmfithq6    decimal(3,0),
pmfiitg1    decimal(8,2),
pmfiitg2    decimal(8,2),
pmfiitg3    decimal(8,2),
pmfithg1    decimal(8,2),
pmfithg2    decimal(8,2),
pmfithg3    decimal(8,2),
pmfithg4    decimal(8,2),
pmfithg5    decimal(8,2),
pmfithg6    decimal(8,2),
pmficdat    char(8),
pmfictim    char(8),
pmficuid    char(10),
pmfiudat    char(8),
pmfiutim    char(8),
pmfiuuid    char(10),
pmfiphca    decimal(8,2),
pmfiedva    decimal(8,2),
pmfispar    char(20),
lf          char(1)
);
create unique index pmsfida1 on pmsfidaf
(
pmfifino,
pmfiuniq
);
create unique index pmsfida2 on pmsfidaf
(
pmfiurno,
pmfifino,
pmfiuniq
);
revoke all on pmsfidaf from public ; 
grant select on pmsfidaf to public ; 
