create table pmslbraf
(
  pmlbuniq    char(10) default ' ' not null,
  pmlbadmn    char(8) default ' ' not null,
  pmlbcntr    char(3) default ' ' not null,
  pmlbaudc    char(3) default ' ' not null,
  pmlbonsl    char(3) default ' ' not null,
  pmlbdatl    char(8) default ' ' not null,
  pmlbtiml    char(8) default ' ' not null,
  pmlbmin1    char(5) default ' ' not null,
  pmlbdat2    char(8) default ' ' not null,
  pmlbtim2    char(8) default ' ' not null,
  pmlbmin2    char(5) default ' ' not null,
  pmlbdatr    char(8) default ' ' not null,
  pmlbindi    char(9) default ' ' not null,
  pmlbindf    char(50) default ' ' not null,
  pmlbindo    char(9) default ' ' not null,
  pmlbinof    char(50) default ' ' not null,
  pmlbanlg    char(3) default ' ' not null,
  pmlbposd    char(3) default ' ' not null,
  pmlbcoll    char(3) default ' ' not null,
  pmlbpres    char(3) default ' ' not null,
  pmlbmemb    char(3) default ' ' not null,
  pmlbnves    char(2) default ' ' not null,
  pmlbtypb    char(3) default ' ' not null,
  pmlbprop    char(3) default ' ' not null,
  pmlbman3    char(3) default ' ' not null,
  pmlbplac    char(3) default ' ' not null,
  pmlbmpla    char(3) default ' ' not null,
  pmlbepis    char(3) default ' ' not null,
  pmlbperi    char(3) default ' ' not null,
  pmlbpert    char(3) default ' ' not null,
  pmlbperr    char(3) default ' ' not null,
  pmlbbldl    char(4) default ' ' not null,
  pmlbbltr    char(3) default ' ' not null,
  pmlbdlic    char(3) default ' ' not null,
  pmlbdmid    char(10) default ' ' not null,
  pmlbddoc    char(10) default ' ' not null,
  pmlbdana    char(10) default ' ' not null,
  pmlbnumb    char(2) default ' ' not null,
  pmlbmidr    char(10) default ' ' not null,
  pmlbwebc    char(10) default ' ' not null,
  pmlbdatc    char(8) default ' ' not null,
  pmlbtimc    char(8) default ' ' not null,
  pmlbwebu    char(10) default ' ' not null,
  pmlbdatu    char(8) default ' ' not null,
  pmlbtimu    char(8) default ' ' not null,
  pmlbrecs    char(1) default ' ' not null,
  pmlbwebd    char(10) default ' ' not null,
  pmlbdatd    char(8) default ' ' not null,
  pmlbtimd    char(8) default ' ' not null,
  pmlbreas    char(3) default ' ' not null,
  pmlbspar    char(57) default ' ' not null,
  lf          char(1)
);
create unique index pmslbra1 on pmslbraf
(
pmlbuniq,
pmlbadmn,
pmlbcntr,
pmlbaudc
);
revoke all on pmslbraf from public ; 
grant select on pmslbraf to public ; 
