create table pmsqviaf
(
  dpmqvmes    char(20) default ' ' not null,
  dpmqvtrn    char(2) default ' ' not null,
  aadmno      char(8) default ' ' not null,
  aurno       char(8) default ' ' not null,
  adate       char(8) default ' ' not null,
  atime       char(8) default ' ' not null,
  astat       decimal(1,0) default 0 not null,
  ainvprt     decimal(3,0) default 0 not null,
  alacdte     char(8) default ' ' not null,
  acancel     char(3) default ' ' not null,
  adoctr      char(6) default ' ' not null,
  adocta      char(6) default ' ' not null,
  adoctl      char(30) default ' ' not null,
  asrce       char(3) default ' ' not null,
  atype       char(3) default ' ' not null,
  aclss       char(3) default ' ' not null,
  acare       char(3) default ' ' not null,
  afundh      char(6) default ' ' not null,
  afndtb      char(8) default ' ' not null,
  afndmm      char(19) default ' ' not null,
  aelig       decimal(1,0) default 0 not null,
  avisit      decimal(1,0) default 0 not null,
  aalerg      decimal(1,0) default 0 not null,
  ailln       decimal(1,0) default 0 not null,
  adiag1      char(80) default ' ' not null,
  adiag2      char(80) default ' ' not null,
  adisc       decimal(8,2) default 0 not null,
  adoctt      char(6) default ' ' not null,
  aclssft     char(3) default ' ' not null,
  aallow      char(2) default ' ' not null,
  ambs        char(9) default ' ' not null,
  aclaim      char(3) default ' ' not null,
  adiet       char(3) default ' ' not null,
  aploccr     char(3) default ' ' not null,
  astay       decimal(3,0) default 0 not null,
  adyhosp     decimal(4,0) default 0 not null,
  amemb       decimal(1,0) default 0 not null,
  amembno     decimal(6,0) default 0 not null,
  acomm1      char(40) default ' ' not null,
  acomm2      char(30) default ' ' not null,
  aplur       decimal(1,0) default 0 not null,
  apurge      decimal(1,0) default 0 not null,
  ausr1       char(3) default ' ' not null,
  ausr2       char(3) default ' ' not null,
  ausr3       char(3) default ' ' not null,
  ausr4       char(3) default ' ' not null,
  ausr5       char(3) default ' ' not null,
  ausr6       char(3) default ' ' not null,
  ausr7       char(3) default ' ' not null,
  adschi      decimal(1,0) default 0 not null,
  ardrnam     char(22) default ' ' not null,
  afndyy      char(2) default ' ' not null,
  afndcg      char(6) default ' ' not null,
  aoccdte     char(8) default ' ' not null,
  acoddte     char(8) default ' ' not null,
  aretdte     char(8) default ' ' not null,
  amumadm     char(8) default ' ' not null,
  ptmipvis    decimal(3,0) default 0 not null,
  abwght      char(6) default ' ' not null,
  ptmsrfgp    char(8) default ' ' not null,
  ptmsgppc    char(6) default ' ' not null,
  ptmsfhan    char(20) default ' ' not null,
  ptmsecra    char(20) default ' ' not null,
  ptmsmgin    char(3) default ' ' not null,
  ptmiddig    decimal(1,0) default 0 not null,
  ptmigppt    char(2) default ' ' not null,
  ptmidofr    char(3) default ' ' not null,
  ptmirefd    char(8) default ' ' not null,
  ptmidfcn    char(8) default ' ' not null,
  ptmiphpu    char(3) default ' ' not null,
  ptmiagnc    char(3) default ' ' not null,
  ptmiessf    char(1) default ' ' not null,
  ptmiusr8    char(3) default ' ' not null,
  ptmiusr9    char(3) default ' ' not null,
  ptmiusr0    char(3) default ' ' not null,
  ptmipdrg    char(4) default ' ' not null,
  ptmioper    char(4) default ' ' not null,
  ptmixwrd    char(3) default ' ' not null,
  ptmiadoc    char(6) default ' ' not null,
  ptmiregs    char(6) default ' ' not null,
  ptmiuyn1    decimal(1,0) default 0 not null,
  ptmiuyn2    decimal(1,0) default 0 not null,
  ptmipano    char(8) default ' ' not null,
  ptmipadt    char(8) default ' ' not null,
  ptmipcmx    char(9) default ' ' not null,
  ptmigsta    char(1) default ' ' not null,
  ptmicmxp    char(1) default ' ' not null,
  ptmiebed    char(3) default ' ' not null,
  ptmidmov    char(1) default ' ' not null,
  ptmidfas    char(8) default ' ' not null,
  ptmicrcd    char(1) default ' ' not null,
  ptmifinv    char(1) default ' ' not null,
  ptmiconb    char(1) default ' ' not null,
  ptmidatc    char(8) default ' ' not null,
  ptmitimc    char(8) default ' ' not null,
  ptmiwebc    char(10) default ' ' not null,
  ptmidatu    char(8) default ' ' not null,
  ptmitimu    char(8) default ' ' not null,
  ptmiwebu    char(10) default ' ' not null,
  ptmi3bdy    char(4) default ' ' not null,
  ptmi3bad    char(8) default ' ' not null,
  ptmilsdn    char(8) default ' ' not null,
  ptmiogno    char(8) default ' ' not null,
  tward       char(3) default ' ' not null,
  tbed        char(3) default ' ' not null,
  tdate       char(8) default ' ' not null,
  ttime       char(8) default ' ' not null,
  turno       char(8) default ' ' not null,
  tadmn       char(8) default ' ' not null,
  tratef      decimal(14,2) default 0 not null,
  trateg      decimal(14,2) default 0 not null,
  tdisc       decimal(14,2) default 0 not null,
  tallw       decimal(14,2) default 0 not null,
  tatype      char(3) default ' ' not null,
  tadoct      char(6) default ' ' not null,
  trateh      decimal(14,2) default 0 not null,
  textra      decimal(14,2) default 0 not null,
  pttritfs    decimal(14,2) default 0 not null,
  trbtyp      char(3) default ' ' not null,
  trbend      decimal(3,0) default 0 not null,
  tchstat     char(3) default ' ' not null,
  tdept       char(3) default ' ' not null,
  pttrltyp    char(3) default ' ' not null,
  pttrepno    decimal(2,0) default 0 not null,
  pttrepsd    decimal(1,0) default 0 not null,
  pttrlspt    decimal(14,2) default 0 not null,
  pttrlsrb    decimal(14,2) default 0 not null,
  pttraend    decimal(4,0) default 0 not null,
  pttradpt    decimal(14,2) default 0 not null,
  pttradrb    decimal(14,2) default 0 not null,
  pttrnhac    char(3) default ' ' not null,
  pttroper    char(4) default ' ' not null,
  pttrauat    char(1) default ' ' not null,
  pttrcdat    char(8) default ' ' not null,
  pttrctim    char(8) default ' ' not null,
  pttrcuid    char(4) default ' ' not null,
  pttrltsc    char(5) default ' ' not null,
  pttrucid    char(10) default ' ' not null,
  pttruuid    char(10) default ' ' not null,
  pttrclty    char(3) default ' ' not null,
  pttrtrty    char(3) default ' ' not null,
  pttrteam    char(5) default ' ' not null,
  pttrrstr    char(10) default ' ' not null,
  pttrresi    char(10) default ' ' not null,
  pttrfsrc    char(3) default ' ' not null,
  pttrhfnd    char(6) default ' ' not null,
  pttrftbl    char(8) default ' ' not null,
  pttrhfmn    char(19) default ' ' not null,
  pttrhfcn    char(40) default ' ' not null,
  pmvxcsnr    char(1) default ' ' not null,
  pmvxpost    char(8) default ' ' not null,
  pmvxpind    char(3) default ' ' not null,
  pmvxvloc    char(40) default ' ' not null,
  pmvxcfsg    char(1) default ' ' not null,
  pmvxingp    char(1) default ' ' not null,
  pmvxcpth    char(3) default ' ' not null,
  pmvxhcp1    char(1) default ' ' not null,
  pmvxhcp2    char(1) default ' ' not null,
  pmvxhcp3    char(1) default ' ' not null,
  pmvxhcp4    char(1) default ' ' not null,
  pmvxrhc1    char(10) default ' ' not null,
  pmvxrh1g    char(10) default ' ' not null,
  pmvxrh1c    char(2) default ' ' not null,
  pmvxrhc2    char(10) default ' ' not null,
  pmvxrh2g    char(10) default ' ' not null,
  pmvxrh2c    char(2) default ' ' not null,
  pmvxrhc3    char(10) default ' ' not null,
  pmvxrh3g    char(10) default ' ' not null,
  pmvxrh3c    char(2) default ' ' not null,
  pmvxrhc4    char(10) default ' ' not null,
  pmvxrh4g    char(10) default ' ' not null,
  pmvxrh4c    char(2) default ' ' not null,
  pmvxabrg    char(3) default ' ' not null,
  pmvxcadm    char(3) default ' ' not null,
  pmvxirad    char(3) default ' ' not null,
  pmvxidus    char(3) default ' ' not null,
  pmvxcrav    char(3) default ' ' not null,
  pmvxrcct    char(3) default ' ' not null,
  pmvxapwd    char(3) default ' ' not null,
  pmvxapbd    char(3) default ' ' not null,
  pmvxpowd    char(3) default ' ' not null,
  pmvxpobd    char(3) default ' ' not null,
  pmvxpsty    char(1) default ' ' not null,
  pmvxvalw    char(1) default ' ' not null,
  pmvxpalw    char(1) default ' ' not null,
  pmvxindc    char(1) default ' ' not null,
  pmvxmdav    char(3) default ' ' not null,
  pmvxfrms    char(3) default ' ' not null,
  pmvxcsng    char(3) default ' ' not null,
  pmvxpwgt    decimal(6,0) default 0 not null,
  pmvxphgt    decimal(6,0) default 0 not null,
  pmvxdhwr    char(8) default ' ' not null,
  pmvxedc1    char(10) default ' ' not null,
  pmvxedc2    char(10) default ' ' not null,
  pmvxedc3    char(10) default ' ' not null,
  pmvxhome    char(1) default ' ' not null,
  pmvxudf1    char(50) default ' ' not null,
  pmvxudf2    char(50) default ' ' not null,
  pmvxudf3    char(50) default ' ' not null,
  pmvxudf4    char(50) default ' ' not null,
  pmvxudt1    char(13) default ' ' not null,
  pmvxudt2    char(13) default ' ' not null,
  pmvxudt3    char(13) default ' ' not null,
  pmvxudt4    char(13) default ' ' not null,
  pmvxudt5    char(13) default ' ' not null,
  pmvxudt6    char(13) default ' ' not null,
  pmvxcdte    char(8) default ' ' not null,
  pmvxctim    char(8) default ' ' not null,
  pmvxwebc    char(10) default ' ' not null,
  pmvxlupd    char(8) default ' ' not null,
  pmvxlupt    char(8) default ' ' not null,
  pmvxwebu    char(10) default ' ' not null,
  pmvxmhls    char(3) default ' ' not null,
  pmvxpicd    char(9) default ' ' not null,
  pmvxrmor    char(3) default ' ' not null,
  pmvxasut    char(3) default ' ' not null,
  pmvxelps    char(3) default ' ' not null,
  pmvxempl    char(3) default ' ' not null,
  pmvxfinp    char(3) default ' ' not null,
  pmvxoccp    char(3) default ' ' not null,
  pmvxpalc    char(3) default ' ' not null,
  pmvxppal    char(3) default ' ' not null,
  pmvxpppt    char(3) default ' ' not null,
  pmvxpsos    char(3) default ' ' not null,
  pmvxpysp    char(3) default ' ' not null,
  pmvxqldb    char(3) default ' ' not null,
  pmvxread    char(3) default ' ' not null,
  pmvxudin    char(3) default ' ' not null,
  pmvxurea    char(3) default ' ' not null,
  pmvxusac    char(3) default ' ' not null,
  pmvxuvth    char(3) default ' ' not null,
  pmvxintr    char(1) default ' ' not null,
  pmvxlng1    char(3) default ' ' not null,
  pmvxasgc    char(9) default ' ' not null,
  pmvxmhos    char(3) default ' ' not null,
  pmvxdspd    char(8) default ' ' not null,
  pmvxdsif    char(1) default ' ' not null,
  pmvxprmi    char(1) default ' ' not null,
  pmvxprai    char(1) default ' ' not null,
  pmvxpres    char(1) default ' ' not null,
  pmvxuitr    char(1) default ' ' not null,
  pmvxrpoa    char(1) default ' ' not null,
  pmvxrcn1    char(1) default ' ' not null,
  pmvxrcn2    char(1) default ' ' not null,
  pmvxrhfu    char(1) default ' ' not null,
  pmvxrdva    char(1) default ' ' not null,
  pmvxrslo    char(1) default ' ' not null,
  pmvxmloc    char(3) default ' ' not null,
  pmvxpacc    char(3) default ' ' not null,
  pmvxedu1    char(3) default ' ' not null,
  pmvxedu2    char(3) default ' ' not null,
  pmvxedu3    char(3) default ' ' not null,
  pmvxprgm    char(8) default ' ' not null,
  pmvxconf    char(1) default ' ' not null,
  pmvxeocl    char(8) default ' ' not null,
  pmvxsloc    char(3) default ' ' not null,
  pmvxscli    char(3) default ' ' not null,
  pmvxstra    char(3) default ' ' not null,
  pmvxqasn    char(12) default ' ' not null,
  pmvxatcp    char(1) default ' ' not null,
  pmvxatim    char(8) default ' ' not null,
  pmvxitim    char(8) default ' ' not null,
  pmvxhfgn    char(40) default ' ' not null,
  pmvxhfsn    char(40) default ' ' not null,
  pmvxfupi    char(2) default ' ' not null,
  pmvxpoec    char(1) default ' ' not null,
  pmvxpgid    char(3) default ' ' not null,
  pmvxticm    char(3) default ' ' not null,
  pmvxpilc    char(3) default ' ' not null,
  pmvxfvio    char(3) default ' ' not null,
  pmvxfndm    char(19) default ' ' not null,
  pmvxudf5    char(3) default ' ' not null,
  pmvxudf6    char(3) default ' ' not null,
  pmvxudf7    char(3) default ' ' not null,
  pmvxudf8    char(3) default ' ' not null,
  pmvxudf9    char(3) default ' ' not null,
  pmvxud10    char(3) default ' ' not null,
  pmvxud11    char(3) default ' ' not null,
  pmvxud12    char(3) default ' ' not null,
  pmvxud13    char(3) default ' ' not null,
  pmvxud14    char(3) default ' ' not null,
  pmvxud15    char(3) default ' ' not null,
  pmvxteam    char(5) default ' ' not null,
  pmvxnwhc    char(3) default ' ' not null,
  pmvxeddt    char(8) default ' ' not null,
  pmvxphld    char(3) default ' ' not null,
  pmvxploc    char(3) default ' ' not null,
  pmvxdtrt    char(8) default ' ' not null,
  pmvxdflg    char(9) default ' ' not null,
  pmvxfsrc    char(3) default ' ' not null,
  pmvxconm    char(40) default ' ' not null,
  pmvxcpdd    char(8) default ' ' not null,
  pmvxpbmi    char(5) default ' ' not null,
  ddate       char(8) default ' ' not null,
  dtime       char(8) default ' ' not null,
  dstat       char(3) default ' ' not null,
  ddest       char(3) default ' ' not null,
  ddiag       char(50) default ' ' not null,
  ddiag2      char(50) default ' ' not null,
  dusd1       char(3) default ' ' not null,
  dusd2       char(3) default ' ' not null,
  dusd3       char(3) default ' ' not null,
  dusd4       char(3) default ' ' not null,
  dusd5       char(3) default ' ' not null,
  dfmbs       char(9) default ' ' not null,
  ptdsdmdc    char(4) default ' ' not null,
  ptdsddrg    char(4) default ' ' not null,
  dwlreasn    char(3) default ' ' not null,
  ptdssidx    char(1) default ' ' not null,
  ptdsvogu    char(3) default ' ' not null,
  ptdsoper    char(4) default ' ' not null,
  ptdsuyn1    decimal(1,0) default 0 not null,
  ptdsuyn2    decimal(1,0) default 0 not null,
  ptdsuyn3    decimal(1,0) default 0 not null,
  ptdsuyn4    decimal(1,0) default 0 not null,
  ptdsdwrd    char(3) default ' ' not null,
  ptdsdlos    decimal(4,0) default 0 not null,
  ptdssref    char(4) default ' ' not null,
  ptdspald    char(3) default ' ' not null,
  ptdsdpmn    char(3) default ' ' not null,
  mhlrcode    char(3) default ' ' not null,
  pkname      char(80) default ' ' not null,
  pkadd1      char(35) default ' ' not null,
  pkadd2      char(35) default ' ' not null,
  pksubr      char(35) default ' ' not null,
  pkadd4      char(35) default ' ' not null,
  pkpost      char(8) default ' ' not null,
  pktelep     char(20) default ' ' not null,
  pkteleb     char(20) default ' ' not null,
  pkrelp      char(10) default ' ' not null,
  ptremobl    char(20) default ' ' not null,
  ptresnam    char(40) default ' ' not null,
  ptregnam    char(40) default ' ' not null,
  wstby       char(8) default ' ' not null,
  pmqvtdat    char(8) default ' ' not null,
  pmqvttim    char(8) default ' ' not null,
  oerdate     char(8) default ' ' not null,
  oertime     char(8) default ' ' not null,
  pmbrreqd    char(8) default ' ' not null,
  pmbrreqt    char(8) default ' ' not null,
  pmvxcnid    char(10) default ' ' not null,
  pmvxcndt    char(13) default ' ' not null,
  pmvxcase    char(10) default ' ' not null,
  pmvxeafl    char(1) default ' ' not null,
  ptdslsdn    char(8) default ' ' not null,
  ptdsclgp    char(12) default ' ' not null,
  pmqvspar    char(28) default ' ' not null,
  lf          char(1)
);
create unique index pmsqvia1 on pmsqviaf
(
dpmqvmes,
dpmqvtrn
);
revoke all on pmsqviaf from public ; 
grant select on pmsqviaf to public ; 
