create table pmstspaf
(
pmtsurno    char(8),
pmtsvisn    char(8),
pmtsuniq    char(3),
pmtstdat    char(8),
pmtsttim    char(8),
pmtspad1    char(35),
pmtspad2    char(35),
pmtspad3    char(35),
pmtspad4    char(35),
pmtsppos    char(8),
pmtsptlp    char(20),
pmtsptlb    char(20),
pmtsptlm    char(20),
pmtspeml    char(80),
pmtspmel    char(20),
pmtsrad1    char(35),
pmtsrad2    char(35),
pmtsrad3    char(35),
pmtsrad4    char(35),
pmtsrpos    char(8),
pmtsrtlp    char(20),
pmtsrtlb    char(20),
pmtsrtlm    char(20),
pmtsreml    char(80),
pmtsrmel    char(20),
pmtssame    char(1),
pmtsdad1    char(35),
pmtsdad2    char(35),
pmtsdad3    char(35),
pmtsdad4    char(35),
pmtsdpos    char(8),
pmtsdtlp    char(20),
pmtsdtlb    char(20),
pmtsdtlm    char(20),
pmtsdeml    char(80),
pmtsdmel    char(20),
pmtsfacl    char(3),
pmtstrns    char(3),
pmtsmobl    char(3),
pmtsbook    char(1),
pmtsaids    char(3),
pmtsment    char(3),
pmtsspec    char(3),
pmtsccen    char(10),
pmtsclam    char(3),
pmtsambs    char(1),
pmtsambn    char(10),
pmtsm40s    char(1),
pmtsm40n    char(20),
pmtsm40e    char(8),
pmtsrunn    char(3),
pmtscdat    char(8),
pmtsctim    char(8),
pmtscuid    char(10),
pmtsudat    char(8),
pmtsutim    char(8),
pmtsuuid    char(10),
pmtsruno    char(3),
pmtstrno    char(3),
pmtsrtdt    char(8),
pmtsrttm    char(8),
pmtsrtbk    char(1),
pmtsspar    char(77),
lf          char(1)
);
create unique index pmstspa1 on pmstspaf
(
pmtsurno,
pmtsvisn,
pmtsuniq
);
create unique index pmstspa2 on pmstspaf
(
pmtstdat,
pmtsttim,
pmtsurno,
pmtsvisn,
pmtsuniq
);
revoke all on pmstspaf from public ; 
grant select on pmstspaf to public ; 
