create table pmsvx1af
(
  pmvxvisn    char(8) default ' ' not null,
  pmvxvsdt    char(8) default ' ' not null,
  pmvxdoca    char(10) default ' ' not null,
  pmvxdoct    char(10) default ' ' not null,
  pmvxcsnr    char(1) default ' ' not null,
  pmvxpost    char(8) default ' ' not null,
  pmvxpind    char(3) default ' ' not null,
  pmvxvloc    char(40) default ' ' not null,
  pmvxcfsg    char(1) default ' ' not null,
  pmvxingp    char(1) default ' ' not null,
  pmvxcpth    char(3) default ' ' not null,
  pmvxhcp1    char(1) default ' ' not null,
  pmvxhcp2    char(1) default ' ' not null,
  pmvxhcp3    char(1) default ' ' not null,
  pmvxhcp4    char(1) default ' ' not null,
  pmvxrhc1    char(10) default ' ' not null,
  pmvxrh1g    char(10) default ' ' not null,
  pmvxrh1c    char(2) default ' ' not null,
  pmvxrhc2    char(10) default ' ' not null,
  pmvxrh2g    char(10) default ' ' not null,
  pmvxrh2c    char(2) default ' ' not null,
  pmvxrhc3    char(10) default ' ' not null,
  pmvxrh3g    char(10) default ' ' not null,
  pmvxrh3c    char(2) default ' ' not null,
  pmvxrhc4    char(10) default ' ' not null,
  pmvxrh4g    char(10) default ' ' not null,
  pmvxrh4c    char(2) default ' ' not null,
  pmvxabrg    char(3) default ' ' not null,
  pmvxcadm    char(3) default ' ' not null,
  pmvxirad    char(3) default ' ' not null,
  pmvxidus    char(3) default ' ' not null,
  pmvxcrav    char(3) default ' ' not null,
  pmvxrcct    char(3) default ' ' not null,
  pmvxapwd    char(3) default ' ' not null,
  pmvxapbd    char(3) default ' ' not null,
  pmvxpowd    char(3) default ' ' not null,
  pmvxpobd    char(3) default ' ' not null,
  pmvxpsty    char(1) default ' ' not null,
  pmvxvalw    char(1) default ' ' not null,
  pmvxpalw    char(1) default ' ' not null,
  pmvxindc    char(1) default ' ' not null,
  pmvxmdav    char(3) default ' ' not null,
  pmvxfrms    char(3) default ' ' not null,
  pmvxcsng    char(3) default ' ' not null,
  pmvxpwgt    decimal(6,0) default 0 not null,
  pmvxphgt    decimal(6,0) default 0 not null,
  pmvxdhwr    char(8) default ' ' not null,
  pmvxedc1    char(10) default ' ' not null,
  pmvxedc2    char(10) default ' ' not null,
  pmvxedc3    char(10) default ' ' not null,
  pmvxhome    char(1) default ' ' not null,
  pmvxudf1    char(50) default ' ' not null,
  pmvxudf2    char(50) default ' ' not null,
  pmvxudf3    char(50) default ' ' not null,
  pmvxudf4    char(50) default ' ' not null,
  pmvxudt1    char(13) default ' ' not null,
  pmvxudt2    char(13) default ' ' not null,
  pmvxudt3    char(13) default ' ' not null,
  pmvxudt4    char(13) default ' ' not null,
  pmvxudt5    char(13) default ' ' not null,
  pmvxudt6    char(13) default ' ' not null,
  pmvxcdte    char(8) default ' ' not null,
  pmvxctim    char(8) default ' ' not null,
  pmvxwebc    char(10) default ' ' not null,
  pmvxlupd    char(8) default ' ' not null,
  pmvxlupt    char(8) default ' ' not null,
  pmvxwebu    char(10) default ' ' not null,
  pmvxmhls    char(3) default ' ' not null,
  pmvxpicd    char(9) default ' ' not null,
  pmvxrmor    char(3) default ' ' not null,
  pmvxasut    char(3) default ' ' not null,
  pmvxelps    char(3) default ' ' not null,
  pmvxempl    char(3) default ' ' not null,
  pmvxfinp    char(3) default ' ' not null,
  pmvxoccp    char(3) default ' ' not null,
  pmvxpalc    char(3) default ' ' not null,
  pmvxppal    char(3) default ' ' not null,
  pmvxpppt    char(3) default ' ' not null,
  pmvxpsos    char(3) default ' ' not null,
  pmvxpysp    char(3) default ' ' not null,
  pmvxqldb    char(3) default ' ' not null,
  pmvxread    char(3) default ' ' not null,
  pmvxudin    char(3) default ' ' not null,
  pmvxurea    char(3) default ' ' not null,
  pmvxusac    char(3) default ' ' not null,
  pmvxuvth    char(3) default ' ' not null,
  pmvxintr    char(1) default ' ' not null,
  pmvxlng1    char(3) default ' ' not null,
  pmvxasgc    char(9) default ' ' not null,
  pmvxmhos    char(3) default ' ' not null,
  pmvxdspd    char(8) default ' ' not null,
  pmvxdsif    char(1) default ' ' not null,
  pmvxprmi    char(1) default ' ' not null,
  pmvxprai    char(1) default ' ' not null,
  pmvxpres    char(1) default ' ' not null,
  pmvxuitr    char(1) default ' ' not null,
  pmvxrpoa    char(1) default ' ' not null,
  pmvxrcn1    char(1) default ' ' not null,
  pmvxrcn2    char(1) default ' ' not null,
  pmvxrhfu    char(1) default ' ' not null,
  pmvxrdva    char(1) default ' ' not null,
  pmvxrslo    char(1) default ' ' not null,
  pmvxmloc    char(3) default ' ' not null,
  pmvxpacc    char(3) default ' ' not null,
  pmvxedu1    char(3) default ' ' not null,
  pmvxedu2    char(3) default ' ' not null,
  pmvxedu3    char(3) default ' ' not null,
  pmvxprgm    char(8) default ' ' not null,
  pmvxconf    char(1) default ' ' not null,
  pmvxeocl    char(8) default ' ' not null,
  pmvxsloc    char(3) default ' ' not null,
  pmvxscli    char(3) default ' ' not null,
  pmvxstra    char(3) default ' ' not null,
  pmvxqasn    char(12) default ' ' not null,
  pmvxatcp    char(1) default ' ' not null,
  pmvxatim    char(8) default ' ' not null,
  pmvxitim    char(8) default ' ' not null,
  pmvxhfgn    char(40) default ' ' not null,
  pmvxhfsn    char(40) default ' ' not null,
  pmvxfupi    char(2) default ' ' not null,
  pmvxpoec    char(1) default ' ' not null,
  pmvxpgid    char(3) default ' ' not null,
  pmvxticm    char(3) default ' ' not null,
  pmvxpilc    char(3) default ' ' not null,
  pmvxfvio    char(3) default ' ' not null,
  pmvxfndm    char(19) default ' ' not null,
  pmvxudf5    char(3) default ' ' not null,
  pmvxudf6    char(3) default ' ' not null,
  pmvxudf7    char(3) default ' ' not null,
  pmvxudf8    char(3) default ' ' not null,
  pmvxudf9    char(3) default ' ' not null,
  pmvxud10    char(3) default ' ' not null,
  pmvxud11    char(3) default ' ' not null,
  pmvxud12    char(3) default ' ' not null,
  pmvxud13    char(3) default ' ' not null,
  pmvxud14    char(3) default ' ' not null,
  pmvxud15    char(3) default ' ' not null,
  pmvxteam    char(5) default ' ' not null,
  pmvxnwhc    char(3) default ' ' not null,
  pmvxeddt    char(8) default ' ' not null,
  pmvxphld    char(3) default ' ' not null,
  pmvxploc    char(3) default ' ' not null,
  pmvxdtrt    char(8) default ' ' not null,
  pmvxdflg    char(9) default ' ' not null,
  pmvxfsrc    char(3) default ' ' not null,
  pmvxconm    char(40) default ' ' not null,
  pmvxcpdd    char(8) default ' ' not null,
  pmvxpbmi    char(5) default ' ' not null,
  pmvxcnid    char(10) default ' ' not null,
  pmvxcndt    char(13) default ' ' not null,
  pmvxcase    char(10) default ' ' not null,
  pmvxeafl    char(1) default ' ' not null,
  pmvxadmp    char(1) default ' ' not null,
  pmvxcono    char(1) default ' ' not null,
  pmvxmedh    char(1) default ' ' not null,
  pmvxspar    char(13) default ' ' not null,
  lf          char(1)
);
create unique index pmsvx1a1 on pmsvx1af
(
pmvxvisn
);
create unique index pmsvx1a2 on pmsvx1af
(
pmvxvsdt,
pmvxvisn
);
create unique index pmsvx1a3 on pmsvx1af
(
pmvxmhos,
pmvxvisn
);
create unique index pmsvx1a4 on pmsvx1af
(
pmvxcdte,
pmvxctim,
pmvxvisn
);
revoke all on pmsvx1af from public ; 
grant select on pmsvx1af to public ; 
