create table syshvraf
(
  syhvsys     char(2) default ' ' not null,
  syhvfil     char(2) default ' ' not null,
  syhvhid     char(1) default ' ' not null,
  syhvdes     char(20) default ' ' not null,
  syhvfld     char(4) default ' ' not null,
  syhvidx     char(1) default ' ' not null,
  syhvdtop    char(2) default ' ' not null,
  syhvdbot    char(2) default ' ' not null,
  syhvdlef    char(2) default ' ' not null,
  syhvdrig    char(2) default ' ' not null,
  syhvch01    char(20) default ' ' not null,
  syhvch02    char(20) default ' ' not null,
  syhvch03    char(20) default ' ' not null,
  syhvch04    char(20) default ' ' not null,
  syhvch05    char(20) default ' ' not null,
  syhvch06    char(20) default ' ' not null,
  syhvch07    char(20) default ' ' not null,
  syhvch08    char(20) default ' ' not null,
  syhvch09    char(20) default ' ' not null,
  syhvch10    char(20) default ' ' not null,
  syhvcf01    char(8) default ' ' not null,
  syhvcf02    char(8) default ' ' not null,
  syhvcf03    char(8) default ' ' not null,
  syhvcf04    char(8) default ' ' not null,
  syhvcf05    char(8) default ' ' not null,
  syhvcf06    char(8) default ' ' not null,
  syhvcf07    char(8) default ' ' not null,
  syhvcf08    char(8) default ' ' not null,
  syhvcf09    char(8) default ' ' not null,
  syhvcf10    char(8) default ' ' not null,
  syhver01    char(8) default ' ' not null,
  syhver02    char(8) default ' ' not null,
  syhver03    char(8) default ' ' not null,
  syhver04    char(8) default ' ' not null,
  syhver05    char(8) default ' ' not null,
  syhver06    char(8) default ' ' not null,
  syhver07    char(8) default ' ' not null,
  syhver08    char(8) default ' ' not null,
  syhver09    char(8) default ' ' not null,
  syhver10    char(8) default ' ' not null,
  syhvcw01    decimal(2,0) default 0 not null,
  syhvcw02    decimal(2,0) default 0 not null,
  syhvcw03    decimal(2,0) default 0 not null,
  syhvcw04    decimal(2,0) default 0 not null,
  syhvcw05    decimal(2,0) default 0 not null,
  syhvcw06    decimal(2,0) default 0 not null,
  syhvcw07    decimal(2,0) default 0 not null,
  syhvcw08    decimal(2,0) default 0 not null,
  syhvcw09    decimal(2,0) default 0 not null,
  syhvcw10    decimal(2,0) default 0 not null,
  syhvcbf     char(8) default ' ' not null,
  syhvspar    char(42) default ' ' not null,
  lf          char(1)
);
create unique index syshvra1 on syshvraf
(
syhvsys,
syhvfil,
syhvhid
);
revoke all on syshvraf from public ; 
grant select on syshvraf to public ; 
