create table visxdcaf
(
  vsxdvisn    char(8) default ' ' not null,
  vsxdtyda    char(3) default ' ' not null,
  vsxdval1    char(10) default ' ' not null,
  vsxdval2    char(10) default ' ' not null,
  vsxdval3    char(10) default ' ' not null,
  vsxdval4    char(10) default ' ' not null,
  vsxdval5    char(10) default ' ' not null,
  vsxdval6    char(10) default ' ' not null,
  vsxdval7    char(10) default ' ' not null,
  vsxdval8    char(10) default ' ' not null,
  vsxdval9    char(10) default ' ' not null,
  vsxdva10    char(10) default ' ' not null,
  vsxdcod1    char(3) default ' ' not null,
  vsxdcod2    char(3) default ' ' not null,
  vsxdcod3    char(3) default ' ' not null,
  vsxdcod4    char(3) default ' ' not null,
  vsxdcod5    char(3) default ' ' not null,
  vsxdcod6    char(3) default ' ' not null,
  vsxdcod7    char(3) default ' ' not null,
  vsxdcod8    char(3) default ' ' not null,
  vsxdcod9    char(3) default ' ' not null,
  vsxdco10    char(3) default ' ' not null,
  vsxdtxt1    char(80) default ' ' not null,
  vsxdtxt2    char(80) default ' ' not null,
  vsxdtxt3    char(80) default ' ' not null,
  vsxdtxt4    char(80) default ' ' not null,
  vsxdtxt5    char(80) default ' ' not null,
  vsxdtxt6    char(80) default ' ' not null,
  vsxdtxt7    char(80) default ' ' not null,
  vsxdtxt8    char(80) default ' ' not null,
  vsxdtxt9    char(80) default ' ' not null,
  vsxdtx10    char(80) default ' ' not null,
  vsxdyn01    char(1) default ' ' not null,
  vsxdyn02    char(1) default ' ' not null,
  vsxdyn03    char(1) default ' ' not null,
  vsxdyn04    char(1) default ' ' not null,
  vsxdyn05    char(1) default ' ' not null,
  vsxdyn06    char(1) default ' ' not null,
  vsxdyn07    char(1) default ' ' not null,
  vsxdyn08    char(1) default ' ' not null,
  vsxdyn09    char(1) default ' ' not null,
  vsxdyn10    char(1) default ' ' not null,
  vsxddat1    char(8) default ' ' not null,
  vsxdtim1    char(8) default ' ' not null,
  vsxddat2    char(8) default ' ' not null,
  vsxdtim2    char(8) default ' ' not null,
  vsxddat3    char(8) default ' ' not null,
  vsxdtim3    char(8) default ' ' not null,
  vsxddat4    char(8) default ' ' not null,
  vsxdtim4    char(8) default ' ' not null,
  vsxddat5    char(8) default ' ' not null,
  vsxdtim5    char(8) default ' ' not null,
  vsxddat6    char(8) default ' ' not null,
  vsxdtim6    char(8) default ' ' not null,
  vsxddat7    char(8) default ' ' not null,
  vsxdtim7    char(8) default ' ' not null,
  vsxddat8    char(8) default ' ' not null,
  vsxdtim8    char(8) default ' ' not null,
  vsxddat9    char(8) default ' ' not null,
  vsxdtim9    char(8) default ' ' not null,
  vsxdda10    char(8) default ' ' not null,
  vsxdti10    char(8) default ' ' not null,
  vsxddelt    char(1) default ' ' not null,
  vsxdcusr    char(10) default ' ' not null,
  vsxdcdat    char(8) default ' ' not null,
  vsxdctim    char(8) default ' ' not null,
  vsxduusr    char(10) default ' ' not null,
  vsxdudat    char(8) default ' ' not null,
  vsxdutim    char(8) default ' ' not null,
  vsxducid    char(10) default ' ' not null,
  vsxducdt    char(8) default ' ' not null,
  vsxductm    char(8) default ' ' not null,
  vsxdspar    char(100) default ' ' not null,
  lf          char(1)
);
create unique index visxdca1 on visxdcaf
(
vsxdvisn,
vsxdtyda
);
revoke all on visxdcaf from public ; 
grant select on visxdcaf to public ; 
