create table watextaf
(
wtexcode    char(4),
wtexdesc    char(35),
wtexfldt    char(8),
wtextldt    char(8),
wtexfvdt    char(8),
wtextvdt    char(8),
wtexfsdt    char(8),
wtextsdt    char(8),
wtexfrdt    char(8),
wtextrdt    char(8),
wtexunt     char(3),
wtexpri     char(3),
wtexnot     char(3),
wtexpgp     char(3),
wtexrmr     char(3),
wtexrgp     char(8),
wtexcon     char(6),
wtexpro     char(9),
wtexsrc     char(3),
wtexud1     char(3),
wtexud2     char(3),
wtexud3     char(3),
wtexud4     char(3),
wtexud5     char(3),
wtexud6     char(3),
wtexud7     char(3),
wtexud8     char(3),
wtexsta     char(1),
wtexanl1    char(3),
wtexanl2    char(3),
wtexanl3    char(3),
wtexanl4    char(3),
wtexanm1    char(3),
wtexanm2    char(3),
wtexanm3    char(3),
wtexpowd    char(3),
wtexidyc    char(3),
wtexllsc    char(3),
wtexcrtl    char(1),
wtexadmw    char(3),
wtexincd    char(1),
wtexovon    char(1),
wtexctyp    char(3),
wtexlist    char(3),
wtexfurn    char(8),
wtexturn    char(8),
wtexfpro    char(9),
wtextpro    char(9),
wtexfprs    char(1),
wtextprs    char(1),
wtexfuni    char(3),
wtextuni    char(3),
wtexfcon    char(10),
wtextcon    char(10),
wtexfses    decimal(5,0),
wtextses    decimal(5,0),
wtexadty    char(3),
wtexrsta    char(3),
wtexfpad    char(8),
wtextpad    char(8),
wtexfsyd    char(8),
wtextsyd    char(8),
wtexfsud    char(8),
wtextsud    char(8),
wtexfosd    char(8),
wtextosd    char(8),
wtexspa     char(57),
lf          char(1)
);
create unique index watexta1 on watextaf
(
wtexcode
);
create unique index watexta2 on watextaf
(
wtexdesc,
wtexcode
);
revoke all on watextaf from public ; 
grant select on watextaf to public ; 
