create table allactaf
(
  alacdept    varchar2(3) default ' ' not null,
  alacdoct    varchar2(10) default ' ' not null,
  alaccodt    varchar2(8) default ' ' not null,
  alaccotm    varchar2(8) default ' ' not null,
  alacloca    varchar2(3) default ' ' not null,
  alacserv    varchar2(6) default ' ' not null,
  alacunit    number(6,0) default 0 not null,
  alacstat    varchar2(1) default ' ' not null,
  alacudt1    varchar2(8) default ' ' not null,
  alacutm1    varchar2(8) default ' ' not null,
  alacudt2    varchar2(8) default ' ' not null,
  alacutm2    varchar2(8) default ' ' not null,
  alacudt3    varchar2(8) default ' ' not null,
  alacutm3    varchar2(8) default ' ' not null,
  alacudt4    varchar2(8) default ' ' not null,
  alacutm4    varchar2(8) default ' ' not null,
  alacuhc1    varchar2(10) default ' ' not null,
  alacuhc2    varchar2(10) default ' ' not null,
  alacuhc3    varchar2(10) default ' ' not null,
  alacuhc4    varchar2(10) default ' ' not null,
  alacudi1    varchar2(9) default ' ' not null,
  alacudi2    varchar2(9) default ' ' not null,
  alacudi3    varchar2(9) default ' ' not null,
  alacudi4    varchar2(60) default ' ' not null,
  alacudi5    varchar2(60) default ' ' not null,
  alacudi6    varchar2(60) default ' ' not null,
  alacuyn1    varchar2(1) default ' ' not null,
  alacuyn2    varchar2(1) default ' ' not null,
  alacuyn3    varchar2(1) default ' ' not null,
  alacuyn4    varchar2(1) default ' ' not null,
  alacuyn5    varchar2(1) default ' ' not null,
  alacuyn6    varchar2(1) default ' ' not null,
  alacuyn7    varchar2(1) default ' ' not null,
  alacuyn8    varchar2(1) default ' ' not null,
  alacuyn9    varchar2(1) default ' ' not null,
  alacuff1    varchar2(60) default ' ' not null,
  alacuff2    varchar2(60) default ' ' not null,
  alacuff3    varchar2(60) default ' ' not null,
  alacuc01    varchar2(3) default ' ' not null,
  alacuc02    varchar2(3) default ' ' not null,
  alacuc03    varchar2(3) default ' ' not null,
  alacuc04    varchar2(3) default ' ' not null,
  alacuc05    varchar2(3) default ' ' not null,
  alacuc06    varchar2(3) default ' ' not null,
  alacuc07    varchar2(3) default ' ' not null,
  alacuc08    varchar2(3) default ' ' not null,
  alacuc09    varchar2(3) default ' ' not null,
  alacuc10    varchar2(3) default ' ' not null,
  alacuc11    varchar2(3) default ' ' not null,
  alacuc12    varchar2(3) default ' ' not null,
  alacuf01    number(14,2) default 0 not null,
  alacuf02    number(14,2) default 0 not null,
  alacuf03    number(14,2) default 0 not null,
  alacuf04    number(14,2) default 0 not null,
  alacuf05    number(14,2) default 0 not null,
  alacuf06    number(14,2) default 0 not null,
  alacuf07    number(8,0) default 0 not null,
  alacuf08    number(8,0) default 0 not null,
  alacuf09    number(8,0) default 0 not null,
  alacuf10    number(8,0) default 0 not null,
  alacuf11    number(8,0) default 0 not null,
  alacuf12    number(8,0) default 0 not null,
  alaccomm    varchar2(60) default ' ' not null,
  alaccdat    varchar2(8) default ' ' not null,
  alacctim    varchar2(8) default ' ' not null,
  alaccuid    varchar2(10) default ' ' not null,
  alacudat    varchar2(8) default ' ' not null,
  alacutim    varchar2(8) default ' ' not null,
  alacuuid    varchar2(10) default ' ' not null,
  alacspar    varchar2(40) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint allacta1 primary key( 
alacdept,
alaccodt,
alaccotm,
alacdoct)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index allacta2 on allactaf
(
alacdoct,
alaccodt,
alaccotm,
alacdept
)
  tablespace pas_indx; 
