create table allbiaaf
(
  albavisn    varchar2(8) default ' ' not null,
  albadate    varchar2(8) default ' ' not null,
  albatime    varchar2(8) default ' ' not null,
  albadrk1    number(4,0) default 0 not null,
  albadrk2    number(4,0) default 0 not null,
  albadrk3    number(4,0) default 0 not null,
  albadrk4    number(4,0) default 0 not null,
  albaeat1    number(4,0) default 0 not null,
  albaeat2    number(4,0) default 0 not null,
  albaeat3    number(4,0) default 0 not null,
  albaeat4    number(4,0) default 0 not null,
  albaupp1    number(4,0) default 0 not null,
  albaupp2    number(4,0) default 0 not null,
  albaupp3    number(4,0) default 0 not null,
  albaupp4    number(4,0) default 0 not null,
  albalow1    number(4,0) default 0 not null,
  albalow2    number(4,0) default 0 not null,
  albalow3    number(4,0) default 0 not null,
  albalow4    number(4,0) default 0 not null,
  albabrc1    number(4,0) default 0 not null,
  albabrc2    number(4,0) default 0 not null,
  albabrc3    number(4,0) default 0 not null,
  albabrc4    number(4,0) default 0 not null,
  albagrm1    number(4,0) default 0 not null,
  albagrm2    number(4,0) default 0 not null,
  albagrm3    number(4,0) default 0 not null,
  albagrm4    number(4,0) default 0 not null,
  albawsh1    number(4,0) default 0 not null,
  albawsh2    number(4,0) default 0 not null,
  albawsh3    number(4,0) default 0 not null,
  albawsh4    number(4,0) default 0 not null,
  albaurn1    number(4,0) default 0 not null,
  albaurn2    number(4,0) default 0 not null,
  albaurn3    number(4,0) default 0 not null,
  albaurn4    number(4,0) default 0 not null,
  albabow1    number(4,0) default 0 not null,
  albabow2    number(4,0) default 0 not null,
  albabow3    number(4,0) default 0 not null,
  albabow4    number(4,0) default 0 not null,
  albacar1    number(4,0) default 0 not null,
  albacar2    number(4,0) default 0 not null,
  albacar3    number(4,0) default 0 not null,
  albacar4    number(4,0) default 0 not null,
  albachr1    number(4,0) default 0 not null,
  albachr2    number(4,0) default 0 not null,
  albachr3    number(4,0) default 0 not null,
  albachr4    number(4,0) default 0 not null,
  albatol1    number(4,0) default 0 not null,
  albatol2    number(4,0) default 0 not null,
  albatol3    number(4,0) default 0 not null,
  albatol4    number(4,0) default 0 not null,
  albashw1    number(4,0) default 0 not null,
  albashw2    number(4,0) default 0 not null,
  albashw3    number(4,0) default 0 not null,
  albashw4    number(4,0) default 0 not null,
  albalvl1    number(4,0) default 0 not null,
  albalvl2    number(4,0) default 0 not null,
  albalvl3    number(4,0) default 0 not null,
  albalvl4    number(4,0) default 0 not null,
  albaupd1    number(4,0) default 0 not null,
  albaupd2    number(4,0) default 0 not null,
  albaupd3    number(4,0) default 0 not null,
  albaupd4    number(4,0) default 0 not null,
  albapro1    number(4,0) default 0 not null,
  albapro2    number(4,0) default 0 not null,
  albapro3    number(4,0) default 0 not null,
  albapro4    number(4,0) default 0 not null,
  albadelf    varchar2(1) default ' ' not null,
  albacuid    varchar2(10) default ' ' not null,
  albacdat    varchar2(8) default ' ' not null,
  albactim    varchar2(8) default ' ' not null,
  albauuid    varchar2(10) default ' ' not null,
  albaudat    varchar2(8) default ' ' not null,
  albautim    varchar2(8) default ' ' not null,
  albaduid    varchar2(10) default ' ' not null,
  albaddat    varchar2(8) default ' ' not null,
  albadtim    varchar2(8) default ' ' not null,
  albatots    varchar2(3) default ' ' not null,
  albaspar    varchar2(17) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint allbiaa1 primary key( 
albavisn,
albadate,
albatime)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
