create table allauden
(
  alenaudd    varchar2(8) default ' ' not null,
  alenaudt    varchar2(8) default ' ' not null,
  alenaudp    varchar2(2) default ' ' not null,
  alenaudr    varchar2(1) default ' ' not null,
  alenauds    number(1,0) default 0 not null,
  alenaudo    varchar2(4) default ' ' not null,
  alenvisn    varchar2(8) default ' ' not null,
  alenenct    varchar2(8) default ' ' not null,
  alenclin    varchar2(6) default ' ' not null,
  alenhcp     varchar2(10) default ' ' not null,
  alensdat    varchar2(8) default ' ' not null,
  alenstim    varchar2(8) default ' ' not null,
  alenloca    varchar2(3) default ' ' not null,
  alenlink    varchar2(8) default ' ' not null,
  alentype    varchar2(3) default ' ' not null,
  alenserv    varchar2(6) default ' ' not null,
  alendiun    number(6,0) default 0 not null,
  alendbun    number(6,0) default 0 not null,
  aleninun    number(6,0) default 0 not null,
  alenibun    number(6,0) default 0 not null,
  alenbulk    varchar2(3) default ' ' not null,
  alenrsta    varchar2(1) default ' ' not null,
  alenudt1    varchar2(8) default ' ' not null,
  alenutm1    varchar2(8) default ' ' not null,
  alenudt2    varchar2(8) default ' ' not null,
  alenutm2    varchar2(8) default ' ' not null,
  alenudt3    varchar2(8) default ' ' not null,
  alenutm3    varchar2(8) default ' ' not null,
  alenudt4    varchar2(8) default ' ' not null,
  alenutm4    varchar2(8) default ' ' not null,
  alenuhc1    varchar2(10) default ' ' not null,
  alenuhc2    varchar2(10) default ' ' not null,
  alenuhc3    varchar2(10) default ' ' not null,
  alenuhc4    varchar2(10) default ' ' not null,
  alenudi1    varchar2(9) default ' ' not null,
  alenudi2    varchar2(9) default ' ' not null,
  alenudi3    varchar2(9) default ' ' not null,
  alenudi4    varchar2(60) default ' ' not null,
  alenudi5    varchar2(60) default ' ' not null,
  alenudi6    varchar2(60) default ' ' not null,
  alenuyn1    varchar2(1) default ' ' not null,
  alenuyn2    varchar2(1) default ' ' not null,
  alenuyn3    varchar2(1) default ' ' not null,
  alenuyn4    varchar2(1) default ' ' not null,
  alenuyn5    varchar2(1) default ' ' not null,
  alenuyn6    varchar2(1) default ' ' not null,
  alenuyn7    varchar2(1) default ' ' not null,
  alenuyn8    varchar2(1) default ' ' not null,
  alenuyn9    varchar2(1) default ' ' not null,
  alenuff1    varchar2(60) default ' ' not null,
  alenuff2    varchar2(60) default ' ' not null,
  alenuff3    varchar2(60) default ' ' not null,
  alenuc01    varchar2(3) default ' ' not null,
  alenuc02    varchar2(3) default ' ' not null,
  alenuc03    varchar2(3) default ' ' not null,
  alenuc04    varchar2(3) default ' ' not null,
  alenuc05    varchar2(3) default ' ' not null,
  alenuc06    varchar2(3) default ' ' not null,
  alenuc07    varchar2(3) default ' ' not null,
  alenuc08    varchar2(3) default ' ' not null,
  alenuc09    varchar2(3) default ' ' not null,
  alenuc10    varchar2(3) default ' ' not null,
  alenuc11    varchar2(3) default ' ' not null,
  alenuc12    varchar2(3) default ' ' not null,
  alenuc13    varchar2(3) default ' ' not null,
  alenuc14    varchar2(3) default ' ' not null,
  alenuc15    varchar2(3) default ' ' not null,
  alenuc16    varchar2(3) default ' ' not null,
  alenuc17    varchar2(3) default ' ' not null,
  alenuc18    varchar2(3) default ' ' not null,
  alenuc19    varchar2(3) default ' ' not null,
  alenuc20    varchar2(3) default ' ' not null,
  alenuc21    varchar2(3) default ' ' not null,
  alenuc22    varchar2(3) default ' ' not null,
  alenuc23    varchar2(3) default ' ' not null,
  alenuc24    varchar2(3) default ' ' not null,
  alenuc25    varchar2(3) default ' ' not null,
  alenuc26    varchar2(3) default ' ' not null,
  alenuc27    varchar2(3) default ' ' not null,
  alenuc28    varchar2(3) default ' ' not null,
  alenuc29    varchar2(3) default ' ' not null,
  alenuc30    varchar2(3) default ' ' not null,
  alenuc31    varchar2(3) default ' ' not null,
  alenuc32    varchar2(3) default ' ' not null,
  alenuc33    varchar2(3) default ' ' not null,
  alenuc34    varchar2(3) default ' ' not null,
  alenuc35    varchar2(3) default ' ' not null,
  alenuc36    varchar2(3) default ' ' not null,
  alenuc37    varchar2(3) default ' ' not null,
  alenuc38    varchar2(3) default ' ' not null,
  alenuc39    varchar2(3) default ' ' not null,
  alenuc40    varchar2(3) default ' ' not null,
  alenuf01    number(14,2) default 0 not null,
  alenuf02    number(14,2) default 0 not null,
  alenuf03    number(14,2) default 0 not null,
  alenuf04    number(14,2) default 0 not null,
  alenuf05    number(14,2) default 0 not null,
  alenuf06    number(14,2) default 0 not null,
  alenuf07    number(14,2) default 0 not null,
  alenuf08    number(14,2) default 0 not null,
  alenuf09    number(14,2) default 0 not null,
  alenuf10    number(14,2) default 0 not null,
  alenuf11    number(8,0) default 0 not null,
  alenuf12    number(8,0) default 0 not null,
  alenuf13    number(8,0) default 0 not null,
  alenuf14    number(8,0) default 0 not null,
  alenuf15    number(8,0) default 0 not null,
  alenuf16    number(8,0) default 0 not null,
  alenuf17    number(8,0) default 0 not null,
  alenuf18    number(8,0) default 0 not null,
  alenuf19    number(8,0) default 0 not null,
  alenuf20    number(8,0) default 0 not null,
  alencmt1    varchar2(80) default ' ' not null,
  alencmt2    varchar2(80) default ' ' not null,
  alencdat    varchar2(8) default ' ' not null,
  alenctim    varchar2(8) default ' ' not null,
  alencuid    varchar2(10) default ' ' not null,
  alenudat    varchar2(8) default ' ' not null,
  alenutim    varchar2(8) default ' ' not null,
  alenuuid    varchar2(10) default ' ' not null,
  alencomp    varchar2(3) default ' ' not null,
  alenuniq    varchar2(8) default ' ' not null,
  alenssac    varchar2(1) default ' ' not null,
  alenrevd    varchar2(8) default ' ' not null,
  alencref    varchar2(20) default ' ' not null,
  alenpurc    varchar2(3) default ' ' not null,
  alencont    varchar2(3) default ' ' not null,
  alenmohr    varchar2(1) default ' ' not null,
  alenrhos    varchar2(5) default ' ' not null,
  alencart    varchar2(3) default ' ' not null,
  alenstra    varchar2(3) default ' ' not null,
  alenoutc    varchar2(3) default ' ' not null,
  alensrvd    varchar2(3) default ' ' not null,
  alensdep    varchar2(3) default ' ' not null,
  alenaccn    varchar2(20) default ' ' not null,
  alenspar    varchar2(24) default ' ' not null,
  lf          varchar2(1) default ' ' not null
)
tablespace pas_data; 
create index allauden on allauden
(
alenaudd,
alenaudt,
alenaudp,
alenaudr
)
tablespace pas_indx; 
create index allaudea on allauden
(
alenvisn,
alenenct,
alenaudd,
alenaudt
)
tablespace pas_indx; 
create table allencaf
(
  alenvisn    varchar2(8) default ' ' not null,
  alenenct    varchar2(8) default ' ' not null,
  alenclin    varchar2(6) default ' ' not null,
  alenhcp     varchar2(10) default ' ' not null,
  alensdat    varchar2(8) default ' ' not null,
  alenstim    varchar2(8) default ' ' not null,
  alenloca    varchar2(3) default ' ' not null,
  alenlink    varchar2(8) default ' ' not null,
  alentype    varchar2(3) default ' ' not null,
  alenserv    varchar2(6) default ' ' not null,
  alendiun    number(6,0) default 0 not null,
  alendbun    number(6,0) default 0 not null,
  aleninun    number(6,0) default 0 not null,
  alenibun    number(6,0) default 0 not null,
  alenbulk    varchar2(3) default ' ' not null,
  alenrsta    varchar2(1) default ' ' not null,
  alenudt1    varchar2(8) default ' ' not null,
  alenutm1    varchar2(8) default ' ' not null,
  alenudt2    varchar2(8) default ' ' not null,
  alenutm2    varchar2(8) default ' ' not null,
  alenudt3    varchar2(8) default ' ' not null,
  alenutm3    varchar2(8) default ' ' not null,
  alenudt4    varchar2(8) default ' ' not null,
  alenutm4    varchar2(8) default ' ' not null,
  alenuhc1    varchar2(10) default ' ' not null,
  alenuhc2    varchar2(10) default ' ' not null,
  alenuhc3    varchar2(10) default ' ' not null,
  alenuhc4    varchar2(10) default ' ' not null,
  alenudi1    varchar2(9) default ' ' not null,
  alenudi2    varchar2(9) default ' ' not null,
  alenudi3    varchar2(9) default ' ' not null,
  alenudi4    varchar2(60) default ' ' not null,
  alenudi5    varchar2(60) default ' ' not null,
  alenudi6    varchar2(60) default ' ' not null,
  alenuyn1    varchar2(1) default ' ' not null,
  alenuyn2    varchar2(1) default ' ' not null,
  alenuyn3    varchar2(1) default ' ' not null,
  alenuyn4    varchar2(1) default ' ' not null,
  alenuyn5    varchar2(1) default ' ' not null,
  alenuyn6    varchar2(1) default ' ' not null,
  alenuyn7    varchar2(1) default ' ' not null,
  alenuyn8    varchar2(1) default ' ' not null,
  alenuyn9    varchar2(1) default ' ' not null,
  alenuff1    varchar2(60) default ' ' not null,
  alenuff2    varchar2(60) default ' ' not null,
  alenuff3    varchar2(60) default ' ' not null,
  alenuc01    varchar2(3) default ' ' not null,
  alenuc02    varchar2(3) default ' ' not null,
  alenuc03    varchar2(3) default ' ' not null,
  alenuc04    varchar2(3) default ' ' not null,
  alenuc05    varchar2(3) default ' ' not null,
  alenuc06    varchar2(3) default ' ' not null,
  alenuc07    varchar2(3) default ' ' not null,
  alenuc08    varchar2(3) default ' ' not null,
  alenuc09    varchar2(3) default ' ' not null,
  alenuc10    varchar2(3) default ' ' not null,
  alenuc11    varchar2(3) default ' ' not null,
  alenuc12    varchar2(3) default ' ' not null,
  alenuc13    varchar2(3) default ' ' not null,
  alenuc14    varchar2(3) default ' ' not null,
  alenuc15    varchar2(3) default ' ' not null,
  alenuc16    varchar2(3) default ' ' not null,
  alenuc17    varchar2(3) default ' ' not null,
  alenuc18    varchar2(3) default ' ' not null,
  alenuc19    varchar2(3) default ' ' not null,
  alenuc20    varchar2(3) default ' ' not null,
  alenuc21    varchar2(3) default ' ' not null,
  alenuc22    varchar2(3) default ' ' not null,
  alenuc23    varchar2(3) default ' ' not null,
  alenuc24    varchar2(3) default ' ' not null,
  alenuc25    varchar2(3) default ' ' not null,
  alenuc26    varchar2(3) default ' ' not null,
  alenuc27    varchar2(3) default ' ' not null,
  alenuc28    varchar2(3) default ' ' not null,
  alenuc29    varchar2(3) default ' ' not null,
  alenuc30    varchar2(3) default ' ' not null,
  alenuc31    varchar2(3) default ' ' not null,
  alenuc32    varchar2(3) default ' ' not null,
  alenuc33    varchar2(3) default ' ' not null,
  alenuc34    varchar2(3) default ' ' not null,
  alenuc35    varchar2(3) default ' ' not null,
  alenuc36    varchar2(3) default ' ' not null,
  alenuc37    varchar2(3) default ' ' not null,
  alenuc38    varchar2(3) default ' ' not null,
  alenuc39    varchar2(3) default ' ' not null,
  alenuc40    varchar2(3) default ' ' not null,
  alenuf01    number(14,2) default 0 not null,
  alenuf02    number(14,2) default 0 not null,
  alenuf03    number(14,2) default 0 not null,
  alenuf04    number(14,2) default 0 not null,
  alenuf05    number(14,2) default 0 not null,
  alenuf06    number(14,2) default 0 not null,
  alenuf07    number(14,2) default 0 not null,
  alenuf08    number(14,2) default 0 not null,
  alenuf09    number(14,2) default 0 not null,
  alenuf10    number(14,2) default 0 not null,
  alenuf11    number(8,0) default 0 not null,
  alenuf12    number(8,0) default 0 not null,
  alenuf13    number(8,0) default 0 not null,
  alenuf14    number(8,0) default 0 not null,
  alenuf15    number(8,0) default 0 not null,
  alenuf16    number(8,0) default 0 not null,
  alenuf17    number(8,0) default 0 not null,
  alenuf18    number(8,0) default 0 not null,
  alenuf19    number(8,0) default 0 not null,
  alenuf20    number(8,0) default 0 not null,
  alencmt1    varchar2(80) default ' ' not null,
  alencmt2    varchar2(80) default ' ' not null,
  alencdat    varchar2(8) default ' ' not null,
  alenctim    varchar2(8) default ' ' not null,
  alencuid    varchar2(10) default ' ' not null,
  alenudat    varchar2(8) default ' ' not null,
  alenutim    varchar2(8) default ' ' not null,
  alenuuid    varchar2(10) default ' ' not null,
  alencomp    varchar2(3) default ' ' not null,
  alenuniq    varchar2(8) default ' ' not null,
  alenssac    varchar2(1) default ' ' not null,
  alenrevd    varchar2(8) default ' ' not null,
  alencref    varchar2(20) default ' ' not null,
  alenpurc    varchar2(3) default ' ' not null,
  alencont    varchar2(3) default ' ' not null,
  alenmohr    varchar2(1) default ' ' not null,
  alenrhos    varchar2(5) default ' ' not null,
  alencart    varchar2(3) default ' ' not null,
  alenstra    varchar2(3) default ' ' not null,
  alenoutc    varchar2(3) default ' ' not null,
  alensrvd    varchar2(3) default ' ' not null,
  alensdep    varchar2(3) default ' ' not null,
  alenaccn    varchar2(20) default ' ' not null,
  alenspar    varchar2(24) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint allenca1 primary key( 
alenvisn,
alenenct)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index allenca2 on allencaf
(
alenhcp,
alensdat,
alenstim,
alenvisn,
alenenct
)
  tablespace pas_indx; 
create unique index allenca3 on allencaf
(
alenuniq,
alenvisn,
alenenct
)
  tablespace pas_indx; 
create unique index allenca4 on allencaf
(
alensdat,
alenvisn,
alenenct
)
  tablespace pas_indx; 
create unique index allenca5 on allencaf
(
alencuid,
alensdat,
alenstim,
alenvisn,
alenenct
)
  tablespace pas_indx; 
create unique index allenca6 on allencaf
(
alenvisn,
alensdat,
alenstim,
alenenct
)
  tablespace pas_indx; 
create unique index allenca7 on allencaf
(
alenlink,
alenvisn,
alenenct
)
  tablespace pas_indx; 
