create table allqueaf
(
  dalqumes    varchar2(20) default ' ' not null,
  alrevisn    varchar2(8) default ' ' not null,
  alenenct    varchar2(8) default ' ' not null,
  alenclin    varchar2(6) default ' ' not null,
  alenhcp     varchar2(10) default ' ' not null,
  alensdat    varchar2(8) default ' ' not null,
  alenstim    varchar2(8) default ' ' not null,
  alenloca    varchar2(3) default ' ' not null,
  alenlink    varchar2(8) default ' ' not null,
  alentype    varchar2(3) default ' ' not null,
  alenserv    varchar2(6) default ' ' not null,
  alendiun    number(6,0) default 0 not null,
  alendbun    number(6,0) default 0 not null,
  aleninun    number(6,0) default 0 not null,
  alenibun    number(6,0) default 0 not null,
  alenbulk    varchar2(3) default ' ' not null,
  alenrsta    varchar2(1) default ' ' not null,
  alenudt1    varchar2(8) default ' ' not null,
  alenutm1    varchar2(8) default ' ' not null,
  alenudt2    varchar2(8) default ' ' not null,
  alenutm2    varchar2(8) default ' ' not null,
  alenudt3    varchar2(8) default ' ' not null,
  alenutm3    varchar2(8) default ' ' not null,
  alenudt4    varchar2(8) default ' ' not null,
  alenutm4    varchar2(8) default ' ' not null,
  alenuhc1    varchar2(10) default ' ' not null,
  alenuhc2    varchar2(10) default ' ' not null,
  alenuhc3    varchar2(10) default ' ' not null,
  alenuhc4    varchar2(10) default ' ' not null,
  alenudi1    varchar2(9) default ' ' not null,
  alenudi2    varchar2(9) default ' ' not null,
  alenudi3    varchar2(9) default ' ' not null,
  alenudi4    varchar2(60) default ' ' not null,
  alenudi5    varchar2(60) default ' ' not null,
  alenudi6    varchar2(60) default ' ' not null,
  alenuyn1    varchar2(1) default ' ' not null,
  alenuyn2    varchar2(1) default ' ' not null,
  alenuyn3    varchar2(1) default ' ' not null,
  alenuyn4    varchar2(1) default ' ' not null,
  alenuyn5    varchar2(1) default ' ' not null,
  alenuyn6    varchar2(1) default ' ' not null,
  alenuyn7    varchar2(1) default ' ' not null,
  alenuyn8    varchar2(1) default ' ' not null,
  alenuyn9    varchar2(1) default ' ' not null,
  alenuff1    varchar2(60) default ' ' not null,
  alenuff2    varchar2(60) default ' ' not null,
  alenuff3    varchar2(60) default ' ' not null,
  alenuc01    varchar2(3) default ' ' not null,
  alenuc02    varchar2(3) default ' ' not null,
  alenuc03    varchar2(3) default ' ' not null,
  alenuc04    varchar2(3) default ' ' not null,
  alenuc05    varchar2(3) default ' ' not null,
  alenuc06    varchar2(3) default ' ' not null,
  alenuc07    varchar2(3) default ' ' not null,
  alenuc08    varchar2(3) default ' ' not null,
  alenuc09    varchar2(3) default ' ' not null,
  alenuc10    varchar2(3) default ' ' not null,
  alenuc11    varchar2(3) default ' ' not null,
  alenuc12    varchar2(3) default ' ' not null,
  alenuc13    varchar2(3) default ' ' not null,
  alenuc14    varchar2(3) default ' ' not null,
  alenuc15    varchar2(3) default ' ' not null,
  alenuc16    varchar2(3) default ' ' not null,
  alenuc17    varchar2(3) default ' ' not null,
  alenuc18    varchar2(3) default ' ' not null,
  alenuc19    varchar2(3) default ' ' not null,
  alenuc20    varchar2(3) default ' ' not null,
  alenuc21    varchar2(3) default ' ' not null,
  alenuc22    varchar2(3) default ' ' not null,
  alenuc23    varchar2(3) default ' ' not null,
  alenuc24    varchar2(3) default ' ' not null,
  alenuc25    varchar2(3) default ' ' not null,
  alenuc26    varchar2(3) default ' ' not null,
  alenuc27    varchar2(3) default ' ' not null,
  alenuc28    varchar2(3) default ' ' not null,
  alenuc29    varchar2(3) default ' ' not null,
  alenuc30    varchar2(3) default ' ' not null,
  alenuc31    varchar2(3) default ' ' not null,
  alenuc32    varchar2(3) default ' ' not null,
  alenuc33    varchar2(3) default ' ' not null,
  alenuc34    varchar2(3) default ' ' not null,
  alenuc35    varchar2(3) default ' ' not null,
  alenuc36    varchar2(3) default ' ' not null,
  alenuc37    varchar2(3) default ' ' not null,
  alenuc38    varchar2(3) default ' ' not null,
  alenuc39    varchar2(3) default ' ' not null,
  alenuc40    varchar2(3) default ' ' not null,
  alenuf01    number(14,2) default 0 not null,
  alenuf02    number(14,2) default 0 not null,
  alenuf03    number(14,2) default 0 not null,
  alenuf04    number(14,2) default 0 not null,
  alenuf05    number(14,2) default 0 not null,
  alenuf06    number(14,2) default 0 not null,
  alenuf07    number(14,2) default 0 not null,
  alenuf08    number(14,2) default 0 not null,
  alenuf09    number(14,2) default 0 not null,
  alenuf10    number(14,2) default 0 not null,
  alenuf11    number(8,0) default 0 not null,
  alenuf12    number(8,0) default 0 not null,
  alenuf13    number(8,0) default 0 not null,
  alenuf14    number(8,0) default 0 not null,
  alenuf15    number(8,0) default 0 not null,
  alenuf16    number(8,0) default 0 not null,
  alenuf17    number(8,0) default 0 not null,
  alenuf18    number(8,0) default 0 not null,
  alenuf19    number(8,0) default 0 not null,
  alenuf20    number(8,0) default 0 not null,
  alencmt1    varchar2(80) default ' ' not null,
  alencmt2    varchar2(80) default ' ' not null,
  alencomp    varchar2(3) default ' ' not null,
  alenuniq    varchar2(8) default ' ' not null,
  alenssac    varchar2(1) default ' ' not null,
  alenrevd    varchar2(8) default ' ' not null,
  alencref    varchar2(20) default ' ' not null,
  alenpurc    varchar2(3) default ' ' not null,
  alencont    varchar2(3) default ' ' not null,
  alenmohr    varchar2(1) default ' ' not null,
  alenrhos    varchar2(5) default ' ' not null,
  alencart    varchar2(3) default ' ' not null,
  alenstra    varchar2(3) default ' ' not null,
  alenoutc    varchar2(3) default ' ' not null,
  alensrvd    varchar2(3) default ' ' not null,
  alensdep    varchar2(3) default ' ' not null,
  alreurno    varchar2(8) default ' ' not null,
  alrestat    varchar2(1) default ' ' not null,
  alredact    varchar2(8) default ' ' not null,
  alrelink    varchar2(8) default ' ' not null,
  alrerclo    varchar2(3) default ' ' not null,
  alredclo    varchar2(8) default ' ' not null,
  alretclo    varchar2(8) default ' ' not null,
  alreuclo    varchar2(10) default ' ' not null,
  alrercan    varchar2(3) default ' ' not null,
  alredcan    varchar2(8) default ' ' not null,
  alretcan    varchar2(8) default ' ' not null,
  alreucan    varchar2(10) default ' ' not null,
  alrerina    varchar2(3) default ' ' not null,
  alredina    varchar2(8) default ' ' not null,
  alretina    varchar2(8) default ' ' not null,
  alredinu    varchar2(8) default ' ' not null,
  alreuina    varchar2(10) default ' ' not null,
  alrerdat    varchar2(8) default ' ' not null,
  alrerdep    varchar2(3) default ' ' not null,
  alrerdoc    varchar2(10) default ' ' not null,
  alrerhcp    varchar2(10) default ' ' not null,
  alrerhcr    varchar2(10) default ' ' not null,
  alrerhct    varchar2(2) default ' ' not null,
  alredept    varchar2(3) default ' ' not null,
  alreunit    varchar2(3) default ' ' not null,
  alreprty    varchar2(3) default ' ' not null,
  alrepro1    varchar2(9) default ' ' not null,
  alrepro2    varchar2(9) default ' ' not null,
  alrepro3    varchar2(9) default ' ' not null,
  alredia1    varchar2(9) default ' ' not null,
  alredia2    varchar2(9) default ' ' not null,
  alredia3    varchar2(9) default ' ' not null,
  alresrce    varchar2(3) default ' ' not null,
  alrecomp    varchar2(3) default ' ' not null,
  alrebulk    varchar2(1) default ' ' not null,
  alredrev    varchar2(8) default ' ' not null,
  alrehcp     varchar2(10) default ' ' not null,
  alredrec    varchar2(8) default ' ' not null,
  alreuc01    varchar2(3) default ' ' not null,
  alreuc02    varchar2(3) default ' ' not null,
  alreuc03    varchar2(3) default ' ' not null,
  alreuc04    varchar2(3) default ' ' not null,
  alreuc05    varchar2(3) default ' ' not null,
  alreuc06    varchar2(3) default ' ' not null,
  alreuc07    varchar2(3) default ' ' not null,
  alreuc08    varchar2(3) default ' ' not null,
  alreuc09    varchar2(3) default ' ' not null,
  alreuc10    varchar2(3) default ' ' not null,
  alreuc11    varchar2(3) default ' ' not null,
  alreuc12    varchar2(3) default ' ' not null,
  alreuc13    varchar2(3) default ' ' not null,
  alreuc14    varchar2(3) default ' ' not null,
  alreuc15    varchar2(3) default ' ' not null,
  alreuc16    varchar2(3) default ' ' not null,
  alreuc17    varchar2(3) default ' ' not null,
  alreuc18    varchar2(3) default ' ' not null,
  alreuc19    varchar2(3) default ' ' not null,
  alreuc20    varchar2(3) default ' ' not null,
  alreuc21    varchar2(3) default ' ' not null,
  alreuc22    varchar2(3) default ' ' not null,
  alreuc23    varchar2(3) default ' ' not null,
  alreuc24    varchar2(3) default ' ' not null,
  alreuc25    varchar2(3) default ' ' not null,
  alreuc26    varchar2(3) default ' ' not null,
  alreuc27    varchar2(3) default ' ' not null,
  alreuc28    varchar2(3) default ' ' not null,
  alreuc29    varchar2(3) default ' ' not null,
  alreuc30    varchar2(3) default ' ' not null,
  alreuc31    varchar2(3) default ' ' not null,
  alreuc32    varchar2(3) default ' ' not null,
  alreuc33    varchar2(3) default ' ' not null,
  alreuc34    varchar2(3) default ' ' not null,
  alreuc35    varchar2(3) default ' ' not null,
  alreuc36    varchar2(3) default ' ' not null,
  alreuc37    varchar2(3) default ' ' not null,
  alreuc38    varchar2(3) default ' ' not null,
  alreuc39    varchar2(3) default ' ' not null,
  alreuc40    varchar2(3) default ' ' not null,
  alreuyn1    varchar2(1) default ' ' not null,
  alreuyn2    varchar2(1) default ' ' not null,
  alreuyn3    varchar2(1) default ' ' not null,
  alreuyn4    varchar2(1) default ' ' not null,
  alreuhc1    varchar2(10) default ' ' not null,
  alreuhc2    varchar2(10) default ' ' not null,
  alreuhc3    varchar2(10) default ' ' not null,
  alreuhc4    varchar2(10) default ' ' not null,
  alreufr1    varchar2(60) default ' ' not null,
  alreufr2    varchar2(60) default ' ' not null,
  alreudt1    varchar2(8) default ' ' not null,
  alreutm1    varchar2(8) default ' ' not null,
  alreudt2    varchar2(8) default ' ' not null,
  alreutm2    varchar2(8) default ' ' not null,
  alreudt3    varchar2(8) default ' ' not null,
  alreutm3    varchar2(8) default ' ' not null,
  alreudt4    varchar2(8) default ' ' not null,
  alreutm4    varchar2(8) default ' ' not null,
  alreuno1    number(14,2) default 0 not null,
  alreuno2    number(14,2) default 0 not null,
  alrectyp    varchar2(6) default ' ' not null,
  alrehosn    varchar2(3) default ' ' not null,
  alrefhcp    varchar2(60) default ' ' not null,
  alrehcp1    varchar2(60) default ' ' not null,
  alrehcp2    varchar2(60) default ' ' not null,
  alrehcp3    varchar2(60) default ' ' not null,
  alrehcpc    varchar2(8) default ' ' not null,
  alrehcps    varchar2(8) default ' ' not null,
  alrehcpb    varchar2(20) default ' ' not null,
  alrehcpf    varchar2(20) default ' ' not null,
  alrehcpp    varchar2(10) default ' ' not null,
  alrestyp    varchar2(3) default ' ' not null,
  alreprcm    varchar2(50) default ' ' not null,
  alrepsit    varchar2(6) default ' ' not null,
  alreclid    varchar2(6) default ' ' not null,
  alrecsta    varchar2(3) default ' ' not null,
  alrerrej    varchar2(3) default ' ' not null,
  alreccom    varchar2(50) default ' ' not null,
  alrertyp    varchar2(3) default ' ' not null,
  alrerexp    varchar2(8) default ' ' not null,
  alremdat    varchar2(8) default ' ' not null,
  alreprdt    varchar2(8) default ' ' not null,
  alresrej    varchar2(3) default ' ' not null,
  alresrdt    varchar2(8) default ' ' not null,
  alresrtm    varchar2(8) default ' ' not null,
  alresrui    varchar2(10) default ' ' not null,
  alreudt5    varchar2(8) default ' ' not null,
  alreutm5    varchar2(8) default ' ' not null,
  alreuyn5    varchar2(1) default ' ' not null,
  alreudid    varchar2(10) default ' ' not null,
  alreudt6    varchar2(8) default ' ' not null,
  alreutm6    varchar2(8) default ' ' not null,
  alreuyn6    varchar2(1) default ' ' not null,
  alrerevd    varchar2(8) default ' ' not null,
  alrepurc    varchar2(3) default ' ' not null,
  alreoutp    varchar2(3) default ' ' not null,
  alrecont    varchar2(3) default ' ' not null,
  alrescor    varchar2(6) default ' ' not null,
  alremohr    varchar2(1) default ' ' not null,
  alreevpr    varchar2(3) default ' ' not null,
  alrediat    varchar2(50) default ' ' not null,
  alreuyn7    varchar2(1) default ' ' not null,
  alreuyn8    varchar2(1) default ' ' not null,
  alreuyn9    varchar2(1) default ' ' not null,
  alreucd1    varchar2(1) default ' ' not null,
  alreucd2    varchar2(1) default ' ' not null,
  alreucd3    varchar2(1) default ' ' not null,
  alreorig    varchar2(30) default ' ' not null,
  alreyn10    varchar2(1) default ' ' not null,
  alreyn11    varchar2(1) default ' ' not null,
  alreyn12    varchar2(1) default ' ' not null,
  alreudt7    varchar2(8) default ' ' not null,
  alreutm7    varchar2(8) default ' ' not null,
  alreudt8    varchar2(8) default ' ' not null,
  alreutm8    varchar2(8) default ' ' not null,
  alreudt9    varchar2(8) default ' ' not null,
  alreutm9    varchar2(8) default ' ' not null,
  alreeiod    varchar2(8) default ' ' not null,
  alreacdd    varchar2(8) default ' ' not null,
  alreud10    varchar2(8) default ' ' not null,
  alrenvin    varchar2(1) default ' ' not null,
  alrecdat    varchar2(8) default ' ' not null,
  alrectim    varchar2(8) default ' ' not null,
  alreudat    varchar2(8) default ' ' not null,
  alretrgs    varchar2(3) default ' ' not null,
  alretrgd    varchar2(8) default ' ' not null,
  alrebkov    varchar2(3) default ' ' not null,
  alrebkpr    varchar2(3) default ' ' not null,
  alrebkpm    varchar2(2) default ' ' not null,
  alrebkba    varchar2(1) default ' ' not null,
  alressub    varchar2(3) default ' ' not null,
  alquspar    varchar2(27) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint allquea1 primary key( 
dalqumes)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
