create table allaudre
(
  alreaudd    varchar2(8) default ' ' not null,
  alreaudt    varchar2(8) default ' ' not null,
  alreaudp    varchar2(2) default ' ' not null,
  alreaudr    varchar2(1) default ' ' not null,
  alreauds    number(1,0) default 0 not null,
  alreaudo    varchar2(4) default ' ' not null,
  alrevisn    varchar2(8) default ' ' not null,
  alreurno    varchar2(8) default ' ' not null,
  alrestat    varchar2(1) default ' ' not null,
  alredact    varchar2(8) default ' ' not null,
  alrelink    varchar2(8) default ' ' not null,
  alrerclo    varchar2(3) default ' ' not null,
  alredclo    varchar2(8) default ' ' not null,
  alretclo    varchar2(8) default ' ' not null,
  alreuclo    varchar2(10) default ' ' not null,
  alrercan    varchar2(3) default ' ' not null,
  alredcan    varchar2(8) default ' ' not null,
  alretcan    varchar2(8) default ' ' not null,
  alreucan    varchar2(10) default ' ' not null,
  alrerina    varchar2(3) default ' ' not null,
  alredina    varchar2(8) default ' ' not null,
  alretina    varchar2(8) default ' ' not null,
  alredinu    varchar2(8) default ' ' not null,
  alreuina    varchar2(10) default ' ' not null,
  alrerdat    varchar2(8) default ' ' not null,
  alrerdep    varchar2(3) default ' ' not null,
  alrerdoc    varchar2(10) default ' ' not null,
  alrerhcp    varchar2(10) default ' ' not null,
  alrerhcr    varchar2(10) default ' ' not null,
  alrerhct    varchar2(2) default ' ' not null,
  alredept    varchar2(3) default ' ' not null,
  alreunit    varchar2(3) default ' ' not null,
  alreprty    varchar2(3) default ' ' not null,
  alrepro1    varchar2(9) default ' ' not null,
  alrepro2    varchar2(9) default ' ' not null,
  alrepro3    varchar2(9) default ' ' not null,
  alredia1    varchar2(9) default ' ' not null,
  alredia2    varchar2(9) default ' ' not null,
  alredia3    varchar2(9) default ' ' not null,
  alresrce    varchar2(3) default ' ' not null,
  alrecomp    varchar2(3) default ' ' not null,
  alrebulk    varchar2(1) default ' ' not null,
  alredrev    varchar2(8) default ' ' not null,
  alrehcp     varchar2(10) default ' ' not null,
  alredrec    varchar2(8) default ' ' not null,
  alreuc01    varchar2(3) default ' ' not null,
  alreuc02    varchar2(3) default ' ' not null,
  alreuc03    varchar2(3) default ' ' not null,
  alreuc04    varchar2(3) default ' ' not null,
  alreuc05    varchar2(3) default ' ' not null,
  alreuc06    varchar2(3) default ' ' not null,
  alreuc07    varchar2(3) default ' ' not null,
  alreuc08    varchar2(3) default ' ' not null,
  alreuc09    varchar2(3) default ' ' not null,
  alreuc10    varchar2(3) default ' ' not null,
  alreuc11    varchar2(3) default ' ' not null,
  alreuc12    varchar2(3) default ' ' not null,
  alreuc13    varchar2(3) default ' ' not null,
  alreuc14    varchar2(3) default ' ' not null,
  alreuc15    varchar2(3) default ' ' not null,
  alreuc16    varchar2(3) default ' ' not null,
  alreuc17    varchar2(3) default ' ' not null,
  alreuc18    varchar2(3) default ' ' not null,
  alreuc19    varchar2(3) default ' ' not null,
  alreuc20    varchar2(3) default ' ' not null,
  alreuc21    varchar2(3) default ' ' not null,
  alreuc22    varchar2(3) default ' ' not null,
  alreuc23    varchar2(3) default ' ' not null,
  alreuc24    varchar2(3) default ' ' not null,
  alreuc25    varchar2(3) default ' ' not null,
  alreuc26    varchar2(3) default ' ' not null,
  alreuc27    varchar2(3) default ' ' not null,
  alreuc28    varchar2(3) default ' ' not null,
  alreuc29    varchar2(3) default ' ' not null,
  alreuc30    varchar2(3) default ' ' not null,
  alreuc31    varchar2(3) default ' ' not null,
  alreuc32    varchar2(3) default ' ' not null,
  alreuc33    varchar2(3) default ' ' not null,
  alreuc34    varchar2(3) default ' ' not null,
  alreuc35    varchar2(3) default ' ' not null,
  alreuc36    varchar2(3) default ' ' not null,
  alreuc37    varchar2(3) default ' ' not null,
  alreuc38    varchar2(3) default ' ' not null,
  alreuc39    varchar2(3) default ' ' not null,
  alreuc40    varchar2(3) default ' ' not null,
  alreuyn1    varchar2(1) default ' ' not null,
  alreuyn2    varchar2(1) default ' ' not null,
  alreuyn3    varchar2(1) default ' ' not null,
  alreuyn4    varchar2(1) default ' ' not null,
  alreuhc1    varchar2(10) default ' ' not null,
  alreuhc2    varchar2(10) default ' ' not null,
  alreuhc3    varchar2(10) default ' ' not null,
  alreuhc4    varchar2(10) default ' ' not null,
  alreufr1    varchar2(60) default ' ' not null,
  alreufr2    varchar2(60) default ' ' not null,
  alreudt1    varchar2(8) default ' ' not null,
  alreutm1    varchar2(8) default ' ' not null,
  alreudt2    varchar2(8) default ' ' not null,
  alreutm2    varchar2(8) default ' ' not null,
  alreudt3    varchar2(8) default ' ' not null,
  alreutm3    varchar2(8) default ' ' not null,
  alreudt4    varchar2(8) default ' ' not null,
  alreutm4    varchar2(8) default ' ' not null,
  alreuno1    number(14,2) default 0 not null,
  alreuno2    number(14,2) default 0 not null,
  alrecdat    varchar2(8) default ' ' not null,
  alrectim    varchar2(8) default ' ' not null,
  alrecuid    varchar2(10) default ' ' not null,
  alreudat    varchar2(8) default ' ' not null,
  alreutim    varchar2(8) default ' ' not null,
  alreuuid    varchar2(10) default ' ' not null,
  alrectyp    varchar2(6) default ' ' not null,
  alrehosn    varchar2(3) default ' ' not null,
  alrefhcp    varchar2(60) default ' ' not null,
  alrehcp1    varchar2(60) default ' ' not null,
  alrehcp2    varchar2(60) default ' ' not null,
  alrehcp3    varchar2(60) default ' ' not null,
  alrehcpc    varchar2(8) default ' ' not null,
  alrehcps    varchar2(8) default ' ' not null,
  alrehcpb    varchar2(20) default ' ' not null,
  alrehcpf    varchar2(20) default ' ' not null,
  alrehcpp    varchar2(10) default ' ' not null,
  alrestyp    varchar2(3) default ' ' not null,
  alreprcm    varchar2(50) default ' ' not null,
  alrepsit    varchar2(6) default ' ' not null,
  alreclid    varchar2(6) default ' ' not null,
  alrecsta    varchar2(3) default ' ' not null,
  alrerrej    varchar2(3) default ' ' not null,
  alreccom    varchar2(50) default ' ' not null,
  alrertyp    varchar2(3) default ' ' not null,
  alrerexp    varchar2(8) default ' ' not null,
  alremdat    varchar2(8) default ' ' not null,
  alreprdt    varchar2(8) default ' ' not null,
  alresrej    varchar2(3) default ' ' not null,
  alresrdt    varchar2(8) default ' ' not null,
  alresrtm    varchar2(8) default ' ' not null,
  alresrui    varchar2(10) default ' ' not null,
  alreudt5    varchar2(8) default ' ' not null,
  alreutm5    varchar2(8) default ' ' not null,
  alreuyn5    varchar2(1) default ' ' not null,
  alreudid    varchar2(10) default ' ' not null,
  alreudt6    varchar2(8) default ' ' not null,
  alreutm6    varchar2(8) default ' ' not null,
  alreuyn6    varchar2(1) default ' ' not null,
  alrerevd    varchar2(8) default ' ' not null,
  alrepurc    varchar2(3) default ' ' not null,
  alreoutp    varchar2(3) default ' ' not null,
  alrecont    varchar2(3) default ' ' not null,
  alrescor    varchar2(6) default ' ' not null,
  alremohr    varchar2(1) default ' ' not null,
  alreevpr    varchar2(3) default ' ' not null,
  alrediat    varchar2(50) default ' ' not null,
  alreuyn7    varchar2(1) default ' ' not null,
  alreuyn8    varchar2(1) default ' ' not null,
  alreuyn9    varchar2(1) default ' ' not null,
  alreucd1    varchar2(1) default ' ' not null,
  alreucd2    varchar2(1) default ' ' not null,
  alreucd3    varchar2(1) default ' ' not null,
  alreorig    varchar2(30) default ' ' not null,
  alreyn10    varchar2(1) default ' ' not null,
  alreyn11    varchar2(1) default ' ' not null,
  alreyn12    varchar2(1) default ' ' not null,
  alreudt7    varchar2(8) default ' ' not null,
  alreutm7    varchar2(8) default ' ' not null,
  alreudt8    varchar2(8) default ' ' not null,
  alreutm8    varchar2(8) default ' ' not null,
  alreudt9    varchar2(8) default ' ' not null,
  alreutm9    varchar2(8) default ' ' not null,
  alreeiod    varchar2(8) default ' ' not null,
  alreacdd    varchar2(8) default ' ' not null,
  alreud10    varchar2(8) default ' ' not null,
  alrenvin    varchar2(1) default ' ' not null,
  alreuhc5    varchar2(10) default ' ' not null,
  alreuhc6    varchar2(10) default ' ' not null,
  alreuhc7    varchar2(10) default ' ' not null,
  alreuhc8    varchar2(10) default ' ' not null,
  alrerrdt    varchar2(8) default ' ' not null,
  alredia4    varchar2(9) default ' ' not null,
  alredia5    varchar2(9) default ' ' not null,
  alreprc1    varchar2(9) default ' ' not null,
  alreprc2    varchar2(9) default ' ' not null,
  alreprc3    varchar2(9) default ' ' not null,
  alreprc4    varchar2(9) default ' ' not null,
  alreprc5    varchar2(9) default ' ' not null,
  alreud11    varchar2(8) default ' ' not null,
  alreut11    varchar2(8) default ' ' not null,
  alreud12    varchar2(8) default ' ' not null,
  alreut12    varchar2(8) default ' ' not null,
  alreud13    varchar2(8) default ' ' not null,
  alreut13    varchar2(8) default ' ' not null,
  alreud14    varchar2(8) default ' ' not null,
  alreut14    varchar2(8) default ' ' not null,
  alreud15    varchar2(8) default ' ' not null,
  alreut15    varchar2(8) default ' ' not null,
  alretrgs    varchar2(3) default ' ' not null,
  alretrgd    varchar2(8) default ' ' not null,
  alrebkov    varchar2(3) default ' ' not null,
  alrebkpr    varchar2(3) default ' ' not null,
  alrebkpm    varchar2(2) default ' ' not null,
  alrebkba    varchar2(1) default ' ' not null,
  alreftsc    varchar2(3) default ' ' not null,
  alressub    varchar2(3) default ' ' not null,
  alrespar    varchar2(44) default ' ' not null,
  lf          varchar2(1) default ' ' not null
)
tablespace pas_data; 
create index allaudre on allaudre
(
alreaudd,
alreaudt,
alreaudp,
alreaudr
)
tablespace pas_indx; 
create index allaudr2 on allaudre
(
alrevisn,
alreaudd,
alreaudt,
alreaudp,
alreaudr
)
tablespace pas_indx; 
create table allrefaf
(
  alrevisn    varchar2(8) default ' ' not null,
  alreurno    varchar2(8) default ' ' not null,
  alrestat    varchar2(1) default ' ' not null,
  alredact    varchar2(8) default ' ' not null,
  alrelink    varchar2(8) default ' ' not null,
  alrerclo    varchar2(3) default ' ' not null,
  alredclo    varchar2(8) default ' ' not null,
  alretclo    varchar2(8) default ' ' not null,
  alreuclo    varchar2(10) default ' ' not null,
  alrercan    varchar2(3) default ' ' not null,
  alredcan    varchar2(8) default ' ' not null,
  alretcan    varchar2(8) default ' ' not null,
  alreucan    varchar2(10) default ' ' not null,
  alrerina    varchar2(3) default ' ' not null,
  alredina    varchar2(8) default ' ' not null,
  alretina    varchar2(8) default ' ' not null,
  alredinu    varchar2(8) default ' ' not null,
  alreuina    varchar2(10) default ' ' not null,
  alrerdat    varchar2(8) default ' ' not null,
  alrerdep    varchar2(3) default ' ' not null,
  alrerdoc    varchar2(10) default ' ' not null,
  alrerhcp    varchar2(10) default ' ' not null,
  alrerhcr    varchar2(10) default ' ' not null,
  alrerhct    varchar2(2) default ' ' not null,
  alredept    varchar2(3) default ' ' not null,
  alreunit    varchar2(3) default ' ' not null,
  alreprty    varchar2(3) default ' ' not null,
  alrepro1    varchar2(9) default ' ' not null,
  alrepro2    varchar2(9) default ' ' not null,
  alrepro3    varchar2(9) default ' ' not null,
  alredia1    varchar2(9) default ' ' not null,
  alredia2    varchar2(9) default ' ' not null,
  alredia3    varchar2(9) default ' ' not null,
  alresrce    varchar2(3) default ' ' not null,
  alrecomp    varchar2(3) default ' ' not null,
  alrebulk    varchar2(1) default ' ' not null,
  alredrev    varchar2(8) default ' ' not null,
  alrehcp     varchar2(10) default ' ' not null,
  alredrec    varchar2(8) default ' ' not null,
  alreuc01    varchar2(3) default ' ' not null,
  alreuc02    varchar2(3) default ' ' not null,
  alreuc03    varchar2(3) default ' ' not null,
  alreuc04    varchar2(3) default ' ' not null,
  alreuc05    varchar2(3) default ' ' not null,
  alreuc06    varchar2(3) default ' ' not null,
  alreuc07    varchar2(3) default ' ' not null,
  alreuc08    varchar2(3) default ' ' not null,
  alreuc09    varchar2(3) default ' ' not null,
  alreuc10    varchar2(3) default ' ' not null,
  alreuc11    varchar2(3) default ' ' not null,
  alreuc12    varchar2(3) default ' ' not null,
  alreuc13    varchar2(3) default ' ' not null,
  alreuc14    varchar2(3) default ' ' not null,
  alreuc15    varchar2(3) default ' ' not null,
  alreuc16    varchar2(3) default ' ' not null,
  alreuc17    varchar2(3) default ' ' not null,
  alreuc18    varchar2(3) default ' ' not null,
  alreuc19    varchar2(3) default ' ' not null,
  alreuc20    varchar2(3) default ' ' not null,
  alreuc21    varchar2(3) default ' ' not null,
  alreuc22    varchar2(3) default ' ' not null,
  alreuc23    varchar2(3) default ' ' not null,
  alreuc24    varchar2(3) default ' ' not null,
  alreuc25    varchar2(3) default ' ' not null,
  alreuc26    varchar2(3) default ' ' not null,
  alreuc27    varchar2(3) default ' ' not null,
  alreuc28    varchar2(3) default ' ' not null,
  alreuc29    varchar2(3) default ' ' not null,
  alreuc30    varchar2(3) default ' ' not null,
  alreuc31    varchar2(3) default ' ' not null,
  alreuc32    varchar2(3) default ' ' not null,
  alreuc33    varchar2(3) default ' ' not null,
  alreuc34    varchar2(3) default ' ' not null,
  alreuc35    varchar2(3) default ' ' not null,
  alreuc36    varchar2(3) default ' ' not null,
  alreuc37    varchar2(3) default ' ' not null,
  alreuc38    varchar2(3) default ' ' not null,
  alreuc39    varchar2(3) default ' ' not null,
  alreuc40    varchar2(3) default ' ' not null,
  alreuyn1    varchar2(1) default ' ' not null,
  alreuyn2    varchar2(1) default ' ' not null,
  alreuyn3    varchar2(1) default ' ' not null,
  alreuyn4    varchar2(1) default ' ' not null,
  alreuhc1    varchar2(10) default ' ' not null,
  alreuhc2    varchar2(10) default ' ' not null,
  alreuhc3    varchar2(10) default ' ' not null,
  alreuhc4    varchar2(10) default ' ' not null,
  alreufr1    varchar2(60) default ' ' not null,
  alreufr2    varchar2(60) default ' ' not null,
  alreudt1    varchar2(8) default ' ' not null,
  alreutm1    varchar2(8) default ' ' not null,
  alreudt2    varchar2(8) default ' ' not null,
  alreutm2    varchar2(8) default ' ' not null,
  alreudt3    varchar2(8) default ' ' not null,
  alreutm3    varchar2(8) default ' ' not null,
  alreudt4    varchar2(8) default ' ' not null,
  alreutm4    varchar2(8) default ' ' not null,
  alreuno1    number(14,2) default 0 not null,
  alreuno2    number(14,2) default 0 not null,
  alrecdat    varchar2(8) default ' ' not null,
  alrectim    varchar2(8) default ' ' not null,
  alrecuid    varchar2(10) default ' ' not null,
  alreudat    varchar2(8) default ' ' not null,
  alreutim    varchar2(8) default ' ' not null,
  alreuuid    varchar2(10) default ' ' not null,
  alrectyp    varchar2(6) default ' ' not null,
  alrehosn    varchar2(3) default ' ' not null,
  alrefhcp    varchar2(60) default ' ' not null,
  alrehcp1    varchar2(60) default ' ' not null,
  alrehcp2    varchar2(60) default ' ' not null,
  alrehcp3    varchar2(60) default ' ' not null,
  alrehcpc    varchar2(8) default ' ' not null,
  alrehcps    varchar2(8) default ' ' not null,
  alrehcpb    varchar2(20) default ' ' not null,
  alrehcpf    varchar2(20) default ' ' not null,
  alrehcpp    varchar2(10) default ' ' not null,
  alrestyp    varchar2(3) default ' ' not null,
  alreprcm    varchar2(50) default ' ' not null,
  alrepsit    varchar2(6) default ' ' not null,
  alreclid    varchar2(6) default ' ' not null,
  alrecsta    varchar2(3) default ' ' not null,
  alrerrej    varchar2(3) default ' ' not null,
  alreccom    varchar2(50) default ' ' not null,
  alrertyp    varchar2(3) default ' ' not null,
  alrerexp    varchar2(8) default ' ' not null,
  alremdat    varchar2(8) default ' ' not null,
  alreprdt    varchar2(8) default ' ' not null,
  alresrej    varchar2(3) default ' ' not null,
  alresrdt    varchar2(8) default ' ' not null,
  alresrtm    varchar2(8) default ' ' not null,
  alresrui    varchar2(10) default ' ' not null,
  alreudt5    varchar2(8) default ' ' not null,
  alreutm5    varchar2(8) default ' ' not null,
  alreuyn5    varchar2(1) default ' ' not null,
  alreudid    varchar2(10) default ' ' not null,
  alreudt6    varchar2(8) default ' ' not null,
  alreutm6    varchar2(8) default ' ' not null,
  alreuyn6    varchar2(1) default ' ' not null,
  alrerevd    varchar2(8) default ' ' not null,
  alrepurc    varchar2(3) default ' ' not null,
  alreoutp    varchar2(3) default ' ' not null,
  alrecont    varchar2(3) default ' ' not null,
  alrescor    varchar2(6) default ' ' not null,
  alremohr    varchar2(1) default ' ' not null,
  alreevpr    varchar2(3) default ' ' not null,
  alrediat    varchar2(50) default ' ' not null,
  alreuyn7    varchar2(1) default ' ' not null,
  alreuyn8    varchar2(1) default ' ' not null,
  alreuyn9    varchar2(1) default ' ' not null,
  alreucd1    varchar2(1) default ' ' not null,
  alreucd2    varchar2(1) default ' ' not null,
  alreucd3    varchar2(1) default ' ' not null,
  alreorig    varchar2(30) default ' ' not null,
  alreyn10    varchar2(1) default ' ' not null,
  alreyn11    varchar2(1) default ' ' not null,
  alreyn12    varchar2(1) default ' ' not null,
  alreudt7    varchar2(8) default ' ' not null,
  alreutm7    varchar2(8) default ' ' not null,
  alreudt8    varchar2(8) default ' ' not null,
  alreutm8    varchar2(8) default ' ' not null,
  alreudt9    varchar2(8) default ' ' not null,
  alreutm9    varchar2(8) default ' ' not null,
  alreeiod    varchar2(8) default ' ' not null,
  alreacdd    varchar2(8) default ' ' not null,
  alreud10    varchar2(8) default ' ' not null,
  alrenvin    varchar2(1) default ' ' not null,
  alreuhc5    varchar2(10) default ' ' not null,
  alreuhc6    varchar2(10) default ' ' not null,
  alreuhc7    varchar2(10) default ' ' not null,
  alreuhc8    varchar2(10) default ' ' not null,
  alrerrdt    varchar2(8) default ' ' not null,
  alredia4    varchar2(9) default ' ' not null,
  alredia5    varchar2(9) default ' ' not null,
  alreprc1    varchar2(9) default ' ' not null,
  alreprc2    varchar2(9) default ' ' not null,
  alreprc3    varchar2(9) default ' ' not null,
  alreprc4    varchar2(9) default ' ' not null,
  alreprc5    varchar2(9) default ' ' not null,
  alreud11    varchar2(8) default ' ' not null,
  alreut11    varchar2(8) default ' ' not null,
  alreud12    varchar2(8) default ' ' not null,
  alreut12    varchar2(8) default ' ' not null,
  alreud13    varchar2(8) default ' ' not null,
  alreut13    varchar2(8) default ' ' not null,
  alreud14    varchar2(8) default ' ' not null,
  alreut14    varchar2(8) default ' ' not null,
  alreud15    varchar2(8) default ' ' not null,
  alreut15    varchar2(8) default ' ' not null,
  alretrgs    varchar2(3) default ' ' not null,
  alretrgd    varchar2(8) default ' ' not null,
  alrebkov    varchar2(3) default ' ' not null,
  alrebkpr    varchar2(3) default ' ' not null,
  alrebkpm    varchar2(2) default ' ' not null,
  alrebkba    varchar2(1) default ' ' not null,
  alreftsc    varchar2(3) default ' ' not null,
  alressub    varchar2(3) default ' ' not null,
  alrespar    varchar2(44) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint allrefa1 primary key( 
alrevisn)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index allrefa2 on allrefaf
(
alreurno,
alrevisn
)
  tablespace pas_indx; 
create unique index allrefa3 on allrefaf
(
alrestat,
alrerdat,
alrevisn
)
  tablespace pas_indx; 
create unique index allrefa4 on allrefaf
(
alredept,
alrestat,
alrehcp,
alrevisn
)
  tablespace pas_indx; 
create unique index allrefa5 on allrefaf
(
alrehcp,
alrestat,
alrerdat,
alrevisn
)
  tablespace pas_indx; 
create unique index allrefa6 on allrefaf
(
alredept,
alrestat,
alrerdat,
alrehcp,
alrevisn
)
  tablespace pas_indx; 
create unique index allrefa7 on allrefaf
(
alredept,
alrestat,
alredrec,
alrehcp,
alrevisn
)
  tablespace pas_indx; 
