create table bokcnfaf
(
  bkcfadmn    varchar2(8) default ' ' not null,
  bkcfpcpw    varchar2(40) default ' ' not null,
  bkcfrelp    varchar2(10) default ' ' not null,
  bkcfpdtc    varchar2(1) default ' ' not null,
  bkcfuiba    varchar2(1) default ' ' not null,
  bkcfuhas    varchar2(1) default ' ' not null,
  bkcfodcf    varchar2(1) default ' ' not null,
  bkcfatcf    varchar2(1) default ' ' not null,
  bkcffitm    varchar2(1) default ' ' not null,
  bkcfcanc    varchar2(1) default ' ' not null,
  bkcfrcan    varchar2(3) default ' ' not null,
  bkcfaill    varchar2(1) default ' ' not null,
  bkcfareg    varchar2(3) default ' ' not null,
  bkcfcpox    varchar2(1) default ' ' not null,
  bkcfcreg    varchar2(3) default ' ' not null,
  bkcfvdot    varchar2(1) default ' ' not null,
  bkcfvreg    varchar2(3) default ' ' not null,
  bkcfhcon    varchar2(1) default ' ' not null,
  bkcfcspc    varchar2(127) default ' ' not null,
  bkcfrlmh    varchar2(1) default ' ' not null,
  bkcfmhas    varchar2(1) default ' ' not null,
  bkcfmhsp    varchar2(127) default ' ' not null,
  bkcfmque    varchar2(1) default ' ' not null,
  bkcfmreg    varchar2(3) default ' ' not null,
  bkcfmqsp    varchar2(127) default ' ' not null,
  bkcfallg    varchar2(1) default ' ' not null,
  bkcfahas    varchar2(1) default ' ' not null,
  bkcfalsp    varchar2(127) default ' ' not null,
  bkcflclt    varchar2(1) default ' ' not null,
  bkcffsat    varchar2(1) default ' ' not null,
  bkcfovrn    varchar2(1) default ' ' not null,
  bkcfwtim    varchar2(1) default ' ' not null,
  bkcfdadp    varchar2(1) default ' ' not null,
  bkcfcntn    varchar2(20) default ' ' not null,
  bkcfpark    varchar2(1) default ' ' not null,
  bkcfcnst    varchar2(3) default ' ' not null,
  bkcfwebc    varchar2(10) default ' ' not null,
  bkcfcdat    varchar2(8) default ' ' not null,
  bkcfctim    varchar2(8) default ' ' not null,
  bkcfwebu    varchar2(10) default ' ' not null,
  bkcfudat    varchar2(8) default ' ' not null,
  bkcfutim    varchar2(8) default ' ' not null,
  bkcfspar    varchar2(50) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint bokcnfa1 primary key( 
bkcfadmn)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
