create table bokqueaf
(
  dbkqumes    varchar2(20) default ' ' not null,
  bkrebook    varchar2(8) default ' ' not null,
  bkreurno    varchar2(8) default ' ' not null,
  bkreadoc    varchar2(6) default ' ' not null,
  bkresdoc    varchar2(6) default ' ' not null,
  bkreedat    varchar2(8) default ' ' not null,
  bkreatim    varchar2(8) default ' ' not null,
  bkrepdat    varchar2(8) default ' ' not null,
  bkreptim    varchar2(8) default ' ' not null,
  bkreadat    varchar2(8) default ' ' not null,
  bkretype    varchar2(3) default ' ' not null,
  bkrecanc    varchar2(3) default ' ' not null,
  bkreomem    varchar2(1) default ' ' not null,
  bkreprev    varchar2(1) default ' ' not null,
  bkreaccm    varchar2(3) default ' ' not null,
  bkreproc    varchar2(9) default ' ' not null,
  bkrecnt     number(2,0) default 0 not null,
  bkreward    varchar2(3) default ' ' not null,
  bkreadmn    varchar2(8) default ' ' not null,
  bkreprea    varchar2(1) default ' ' not null,
  bkreebed    varchar2(3) default ' ' not null,
  bkreclss    varchar2(3) default ' ' not null,
  bkreatyp    varchar2(3) default ' ' not null,
  bkredept    varchar2(3) default ' ' not null,
  bkretdoc    varchar2(6) default ' ' not null,
  bkreclmt    varchar2(3) default ' ' not null,
  bkrerfgp    varchar2(8) default ' ' not null,
  bkregppc    varchar2(6) default ' ' not null,
  bkregpfa    varchar2(20) default ' ' not null,
  bkreresi    varchar2(3) default ' ' not null,
  bkreeaty    varchar2(3) default ' ' not null,
  bkreecra    varchar2(20) default ' ' not null,
  bkregppt    varchar2(2) default ' ' not null,
  bkredofr    varchar2(3) default ' ' not null,
  bkreoper    varchar2(4) default ' ' not null,
  bkreelos    number(3,0) default 0 not null,
  bkrebkdt    varchar2(8) default ' ' not null,
  bkrxpowd    varchar2(3) default ' ' not null,
  bkrxadwd    varchar2(3) default ' ' not null,
  bkrxcdte    varchar2(8) default ' ' not null,
  bkrxpsty    varchar2(1) default ' ' not null,
  bkrxcndt    varchar2(8) default ' ' not null,
  bkrxudf1    varchar2(3) default ' ' not null,
  bkrxudf2    varchar2(3) default ' ' not null,
  bkrxudf3    varchar2(3) default ' ' not null,
  bkrxudf4    varchar2(3) default ' ' not null,
  bkrxudf5    varchar2(3) default ' ' not null,
  bkrxudd1    varchar2(8) default ' ' not null,
  bkrxudd2    varchar2(8) default ' ' not null,
  bkrxudd3    varchar2(8) default ' ' not null,
  bkrxudd4    varchar2(8) default ' ' not null,
  bkrxuff1    varchar2(50) default ' ' not null,
  bkrxuff2    varchar2(50) default ' ' not null,
  bkrxuff3    varchar2(50) default ' ' not null,
  bkrxuff4    varchar2(50) default ' ' not null,
  bkrxedc1    varchar2(10) default ' ' not null,
  bkrxedc2    varchar2(10) default ' ' not null,
  bkrxedc3    varchar2(10) default ' ' not null,
  bkrxodte    varchar2(8) default ' ' not null,
  bkrxoprd    varchar2(3) default ' ' not null,
  bkquspar    varchar2(65) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint bokquea1 primary key( 
dbkqumes)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
