create table bokrauaf
(
  bkruaurq    varchar2(10) default ' ' not null,
  bkruauty    varchar2(1) default ' ' not null,
  bkruadat    varchar2(8) default ' ' not null,
  bkruatim    varchar2(8) default ' ' not null,
  bkruausr    varchar2(10) default ' ' not null,
  bkruurno    varchar2(8) default ' ' not null,
  bkruvisn    varchar2(8) default ' ' not null,
  bkrubkty    varchar2(3) default ' ' not null,
  bkrureqn    varchar2(10) default ' ' not null,
  bkrustat    varchar2(1) default ' ' not null,
  bkruhosp    varchar2(3) default ' ' not null,
  bkruprio    varchar2(3) default ' ' not null,
  bkrusnam    varchar2(40) default ' ' not null,
  bkrugnam    varchar2(40) default ' ' not null,
  bkrubdat    varchar2(8) default ' ' not null,
  bkrugend    varchar2(1) default ' ' not null,
  bkrurdoc    varchar2(10) default ' ' not null,
  bkruunit    varchar2(3) default ' ' not null,
  bkrucsdt    varchar2(8) default ' ' not null,
  bkrucstm    varchar2(8) default ' ' not null,
  bkructct    varchar2(100) default ' ' not null,
  bkrulocn    varchar2(50) default ' ' not null,
  bkruadpt    varchar2(3) default ' ' not null,
  bkruepow    varchar2(3) default ' ' not null,
  bkrusurg    varchar2(10) default ' ' not null,
  bkruthet    varchar2(6) default ' ' not null,
  bkruanae    varchar2(3) default ' ' not null,
  bkrumbs1    varchar2(9) default ' ' not null,
  bkrumbs2    varchar2(9) default ' ' not null,
  bkrumbs3    varchar2(9) default ' ' not null,
  bkrumbd1    varchar2(80) default ' ' not null,
  bkrumbd2    varchar2(80) default ' ' not null,
  bkrumbd3    varchar2(80) default ' ' not null,
  bkrupror    varchar2(40) default ' ' not null,
  bkrudura    varchar2(3) default ' ' not null,
  bkruinfc    varchar2(3) default ' ' not null,
  bkruequ1    varchar2(3) default ' ' not null,
  bkruequ2    varchar2(3) default ' ' not null,
  bkruequ3    varchar2(3) default ' ' not null,
  bkrucdat    varchar2(8) default ' ' not null,
  bkructim    varchar2(8) default ' ' not null,
  bkrucusr    varchar2(10) default ' ' not null,
  bkruudat    varchar2(8) default ' ' not null,
  bkruutim    varchar2(8) default ' ' not null,
  bkruuusr    varchar2(10) default ' ' not null,
  bkrucndt    varchar2(8) default ' ' not null,
  bkrucntm    varchar2(8) default ' ' not null,
  bkrucnus    varchar2(10) default ' ' not null,
  bkrucncd    varchar2(3) default ' ' not null,
  bkruopty    varchar2(3) default ' ' not null,
  bkrutrcd    varchar2(3) default ' ' not null,
  bkruatcd    varchar2(3) default ' ' not null,
  bkruatyp    varchar2(3) default ' ' not null,
  bkructyp    varchar2(3) default ' ' not null,
  bkruelos    varchar2(3) default ' ' not null,
  bkructy6    varchar2(3) default ' ' not null,
  bkructy7    varchar2(3) default ' ' not null,
  bkructy8    varchar2(3) default ' ' not null,
  bkructy9    varchar2(3) default ' ' not null,
  bkruasrc    varchar2(3) default ' ' not null,
  bkrubtyp    varchar2(3) default ' ' not null,
  bkruelon    varchar2(3) default ' ' not null,
  bkrucsnt    varchar2(1) default ' ' not null,
  bkruccdt    varchar2(8) default ' ' not null,
  bkruspar    varchar2(100) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint bokraua1 primary key( 
bkruaurq,
bkruadat,
bkruatim,
bkruauty)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
