create table ccscexaf
(
  ccexeid     varchar2(4) default ' ' not null,
  ccexr01     varchar2(3) default ' ' not null,
  ccexf01     varchar2(10) default ' ' not null,
  ccext01     varchar2(10) default ' ' not null,
  ccexr02     varchar2(3) default ' ' not null,
  ccexf02     varchar2(10) default ' ' not null,
  ccext02     varchar2(10) default ' ' not null,
  ccexr03     varchar2(3) default ' ' not null,
  ccexf03     varchar2(10) default ' ' not null,
  ccext03     varchar2(10) default ' ' not null,
  ccexr04     varchar2(3) default ' ' not null,
  ccexf04     varchar2(10) default ' ' not null,
  ccext04     varchar2(10) default ' ' not null,
  ccexr05     varchar2(3) default ' ' not null,
  ccexf05     varchar2(10) default ' ' not null,
  ccext05     varchar2(10) default ' ' not null,
  ccexr06     varchar2(3) default ' ' not null,
  ccexf06     varchar2(10) default ' ' not null,
  ccext06     varchar2(10) default ' ' not null,
  ccexr07     varchar2(3) default ' ' not null,
  ccexf07     varchar2(10) default ' ' not null,
  ccext07     varchar2(10) default ' ' not null,
  ccexr08     varchar2(3) default ' ' not null,
  ccexf08     varchar2(10) default ' ' not null,
  ccext08     varchar2(10) default ' ' not null,
  ccexr09     varchar2(3) default ' ' not null,
  ccexf09     varchar2(10) default ' ' not null,
  ccext09     varchar2(10) default ' ' not null,
  ccexr10     varchar2(3) default ' ' not null,
  ccexf10     varchar2(10) default ' ' not null,
  ccext10     varchar2(10) default ' ' not null,
  ccexr11     varchar2(3) default ' ' not null,
  ccexf11     varchar2(10) default ' ' not null,
  ccext11     varchar2(10) default ' ' not null,
  ccexr12     varchar2(3) default ' ' not null,
  ccexf12     varchar2(10) default ' ' not null,
  ccext12     varchar2(10) default ' ' not null,
  ccexr13     varchar2(3) default ' ' not null,
  ccexf13     varchar2(10) default ' ' not null,
  ccext13     varchar2(10) default ' ' not null,
  ccexr14     varchar2(3) default ' ' not null,
  ccexf14     varchar2(10) default ' ' not null,
  ccext14     varchar2(10) default ' ' not null,
  ccexspa     varchar2(23) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint ccscexa1 primary key( 
ccexeid)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
