create table ccseyaaf
(
  cceyeid     varchar2(4) default ' ' not null,
  cceyba1     number(1,0) default 0 not null,
  cceyba2     number(1,0) default 0 not null,
  cceyba3     number(1,0) default 0 not null,
  cceybao     number(1,0) default 0 not null,
  cceyith     number(1,0) default 0 not null,
  cceyia1     number(1,0) default 0 not null,
  cceyia2     number(1,0) default 0 not null,
  cceyia3     number(1,0) default 0 not null,
  cceyiao     number(1,0) default 0 not null,
  cceyim1     number(1,0) default 0 not null,
  cceyim2     number(1,0) default 0 not null,
  cceyim3     number(1,0) default 0 not null,
  cceyimo     number(1,0) default 0 not null,
  cceyeth1    number(1,0) default 0 not null,
  cceyea11    number(1,0) default 0 not null,
  cceyea21    number(1,0) default 0 not null,
  cceyea31    number(1,0) default 0 not null,
  cceyeao1    number(1,0) default 0 not null,
  cceyem11    number(1,0) default 0 not null,
  cceyem21    number(1,0) default 0 not null,
  cceyem31    number(1,0) default 0 not null,
  cceyemo1    number(1,0) default 0 not null,
  cceyeth2    number(1,0) default 0 not null,
  cceyea12    number(1,0) default 0 not null,
  cceyea22    number(1,0) default 0 not null,
  cceyea32    number(1,0) default 0 not null,
  cceyeao2    number(1,0) default 0 not null,
  cceyem12    number(1,0) default 0 not null,
  cceyem22    number(1,0) default 0 not null,
  cceyem32    number(1,0) default 0 not null,
  cceyemo2    number(1,0) default 0 not null,
  cceyeth3    number(1,0) default 0 not null,
  cceyea13    number(1,0) default 0 not null,
  cceyea23    number(1,0) default 0 not null,
  cceyea33    number(1,0) default 0 not null,
  cceyeao3    number(1,0) default 0 not null,
  cceyem13    number(1,0) default 0 not null,
  cceyem23    number(1,0) default 0 not null,
  cceyem33    number(1,0) default 0 not null,
  cceyemo3    number(1,0) default 0 not null,
  cceyeth4    number(1,0) default 0 not null,
  cceyea14    number(1,0) default 0 not null,
  cceyea24    number(1,0) default 0 not null,
  cceyea34    number(1,0) default 0 not null,
  cceyeao4    number(1,0) default 0 not null,
  cceyem14    number(1,0) default 0 not null,
  cceyem24    number(1,0) default 0 not null,
  cceyem34    number(1,0) default 0 not null,
  cceyemo4    number(1,0) default 0 not null,
  cceyeth5    number(1,0) default 0 not null,
  cceyea15    number(1,0) default 0 not null,
  cceyea25    number(1,0) default 0 not null,
  cceyea35    number(1,0) default 0 not null,
  cceyeao5    number(1,0) default 0 not null,
  cceyem15    number(1,0) default 0 not null,
  cceyem25    number(1,0) default 0 not null,
  cceyem35    number(1,0) default 0 not null,
  cceyemo5    number(1,0) default 0 not null,
  cceyspa     varchar2(40) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint ccseyaa1 primary key( 
cceyeid)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
