create table ccsaudep
(
  ccepaudd    varchar2(8) default ' ' not null,
  ccepaudt    varchar2(8) default ' ' not null,
  ccepaudp    varchar2(2) default ' ' not null,
  ccepaudr    varchar2(1) default ' ' not null,
  ccepauds    number(1,0) default 0 not null,
  ccepaudo    varchar2(4) default ' ' not null,
  ccephcd     varchar2(2) default ' ' not null,
  ccepeps     varchar2(16) default ' ' not null,
  ccepsur     varchar2(20) default ' ' not null,
  ccepgiv     varchar2(25) default ' ' not null,
  ccepcom     varchar2(1) default ' ' not null,
  ccepurn     varchar2(10) default ' ' not null,
  ccepsdt     varchar2(8) default ' ' not null,
  ccepltd     varchar2(8) default ' ' not null,
  cceplos     number(6,0) default 0 not null,
  ccepinpt    varchar2(1) default ' ' not null,
  ccepday     varchar2(1) default ' ' not null,
  ccepvist    varchar2(2) default ' ' not null,
  ccepsex     varchar2(1) default ' ' not null,
  ccepdob     varchar2(8) default ' ' not null,
  ccepagey    varchar2(3) default ' ' not null,
  ccepagem    varchar2(2) default ' ' not null,
  ccepaged    varchar2(2) default ' ' not null,
  ccepcob     varchar2(3) default ' ' not null,
  cceprel     varchar2(3) default ' ' not null,
  ccepddat    varchar2(8) default ' ' not null,
  ccepdwar    varchar2(3) default ' ' not null,
  ccepdsta    varchar2(3) default ' ' not null,
  ccepddes    varchar2(3) default ' ' not null,
  ccepdmbs    varchar2(9) default ' ' not null,
  ccepddpt    varchar2(3) default ' ' not null,
  ccepdser    varchar2(3) default ' ' not null,
  ccepmdcc    varchar2(4) default ' ' not null,
  ccepdrgc    varchar2(4) default ' ' not null,
  ccepadat    varchar2(8) default ' ' not null,
  ccepawar    varchar2(3) default ' ' not null,
  ccepasrc    varchar2(3) default ' ' not null,
  ccepacls    varchar2(3) default ' ' not null,
  ccepacar    varchar2(3) default ' ' not null,
  ccepadpt    varchar2(3) default ' ' not null,
  ccepaser    varchar2(3) default ' ' not null,
  ccepardc    varchar2(10) default ' ' not null,
  ccepatdc    varchar2(10) default ' ' not null,
  ccepaadc    varchar2(10) default ' ' not null,
  ccepdadc    varchar2(10) default ' ' not null,
  ccepahfd    varchar2(6) default ' ' not null,
  ccepahtb    varchar2(8) default ' ' not null,
  ccepambs    varchar2(9) default ' ' not null,
  ccepopcl    varchar2(6) default ' ' not null,
  cceppdia    varchar2(9) default ' ' not null,
  ccepsdia    varchar2(9) default ' ' not null,
  cceppopp    varchar2(9) default ' ' not null,
  ccepsopp    varchar2(9) default ' ' not null,
  ccepexc     varchar2(1) default ' ' not null,
  cceppmbs    varchar2(9) default ' ' not null,
  ccepsmbs    varchar2(9) default ' ' not null,
  ccepmu1     varchar2(3) default ' ' not null,
  ccepmu2     varchar2(3) default ' ' not null,
  ccepmu3     varchar2(3) default ' ' not null,
  ccepmu4     varchar2(3) default ' ' not null,
  ccepmu5     varchar2(3) default ' ' not null,
  ccepmu6     varchar2(3) default ' ' not null,
  ccepmu7     varchar2(3) default ' ' not null,
  cceppcd     varchar2(10) default ' ' not null,
  ccepclm     varchar2(3) default ' ' not null,
  ccepcli     varchar2(6) default ' ' not null,
  ccepcty     varchar2(3) default ' ' not null,
  ccepana     varchar2(3) default ' ' not null,
  ccepoty     varchar2(3) default ' ' not null,
  ccepttr     varchar2(3) default ' ' not null,
  ccepoy6     varchar2(3) default ' ' not null,
  ccepoy7     varchar2(3) default ' ' not null,
  ccepoy8     varchar2(3) default ' ' not null,
  ccepoy9     varchar2(3) default ' ' not null,
  cceporm     varchar2(6) default ' ' not null,
  ccepoki     varchar2(3) default ' ' not null,
  ccepotp     varchar2(3) default ' ' not null,
  cceptst     varchar2(3) default ' ' not null,
  ccepins     varchar2(3) default ' ' not null,
  cceptim     varchar2(5) default ' ' not null,
  cceptdp     varchar2(5) default ' ' not null,
  ccepast     varchar2(3) default ' ' not null,
  ccepamd     varchar2(3) default ' ' not null,
  ccepau1     varchar2(3) default ' ' not null,
  ccepau2     varchar2(3) default ' ' not null,
  ccepau3     varchar2(3) default ' ' not null,
  ccepau4     varchar2(3) default ' ' not null,
  ccepau5     varchar2(3) default ' ' not null,
  ccepau6     varchar2(3) default ' ' not null,
  ccepau7     varchar2(3) default ' ' not null,
  ccepau8     varchar2(3) default ' ' not null,
  ccepawt     varchar2(3) default ' ' not null,
  ccepapr     varchar2(3) default ' ' not null,
  ccepaet     varchar2(3) default ' ' not null,
  ccepart     varchar2(3) default ' ' not null,
  ccepain     varchar2(3) default ' ' not null,
  ccepapl     varchar2(3) default ' ' not null,
  ccepapy     varchar2(3) default ' ' not null,
  ccepost     varchar2(6) default ' ' not null,
  ccepocl     varchar2(6) default ' ' not null,
  ccepoct     varchar2(6) default ' ' not null,
  ccepovt     varchar2(3) default ' ' not null,
  ccepody     varchar2(1) default ' ' not null,
  cceposs     varchar2(3) default ' ' not null,
  ccepods     varchar2(3) default ' ' not null,
  ccepoat     varchar2(3) default ' ' not null,
  ccepopr     varchar2(3) default ' ' not null,
  ccepou1     varchar2(3) default ' ' not null,
  ccepou2     varchar2(3) default ' ' not null,
  ccepou3     varchar2(3) default ' ' not null,
  ccepou4     varchar2(3) default ' ' not null,
  ccepodp     varchar2(3) default ' ' not null,
  ccepotr     varchar2(3) default ' ' not null,
  ccepolg     varchar2(3) default ' ' not null,
  ccepoot     varchar2(3) default ' ' not null,
  ccepmu8     varchar2(3) default ' ' not null,
  ccepmu9     varchar2(3) default ' ' not null,
  ccepmu10    varchar2(3) default ' ' not null,
  ccepphp     varchar2(3) default ' ' not null,
  ccepagn     varchar2(3) default ' ' not null,
  ccepvw5     number(12,4) default 0 not null,
  ccepv5a     number(12,4) default 0 not null,
  ccepcmx     varchar2(1) default ' ' not null,
  ccepv8a     number(12,4) default 0 not null,
  ccepintr    varchar2(1) default ' ' not null,
  ccepstat    varchar2(1) default ' ' not null,
  ccepcind    varchar2(3) default ' ' not null,
  ccepspca    varchar2(3) default ' ' not null,
  cceprsta    varchar2(1) default ' ' not null,
  cceprhcp    varchar2(10) default ' ' not null,
  ccepprb1    varchar2(9) default ' ' not null,
  ccepprb2    varchar2(9) default ' ' not null,
  ccepprb3    varchar2(9) default ' ' not null,
  ccepdia1    varchar2(9) default ' ' not null,
  ccepdia2    varchar2(9) default ' ' not null,
  ccepdia3    varchar2(9) default ' ' not null,
  ccepencn    varchar2(3) default ' ' not null,
  ccepserp    varchar2(10) default ' ' not null,
  ccepacty    varchar2(6) default ' ' not null,
  ccepserd    varchar2(8) default ' ' not null,
  ccepptyp    varchar2(3) default ' ' not null,
  ccepdept    varchar2(3) default ' ' not null,
  ccepdunt    number(6,0) default 0 not null,
  ccepdbun    number(6,0) default 0 not null,
  ccepiunt    number(6,0) default 0 not null,
  ccepibun    number(6,0) default 0 not null,
  ccepabrg    varchar2(3) default ' ' not null,
  ccepcadm    varchar2(3) default ' ' not null,
  ccepirad    varchar2(3) default ' ' not null,
  ccepidus    varchar2(3) default ' ' not null,
  ccepcrav    varchar2(3) default ' ' not null,
  cceprcct    varchar2(3) default ' ' not null,
  ccepindc    varchar2(1) default ' ' not null,
  ccepmdav    varchar2(3) default ' ' not null,
  ccepcsng    varchar2(3) default ' ' not null,
  ccepasut    varchar2(3) default ' ' not null,
  ccepelps    varchar2(3) default ' ' not null,
  ccepempl    varchar2(3) default ' ' not null,
  ccepfinp    varchar2(3) default ' ' not null,
  ccepoccp    varchar2(3) default ' ' not null,
  cceppalc    varchar2(3) default ' ' not null,
  ccepppal    varchar2(3) default ' ' not null,
  cceppppt    varchar2(3) default ' ' not null,
  cceppsos    varchar2(3) default ' ' not null,
  cceppysp    varchar2(3) default ' ' not null,
  ccepqldb    varchar2(3) default ' ' not null,
  ccepread    varchar2(3) default ' ' not null,
  ccepudin    varchar2(3) default ' ' not null,
  ccepurea    varchar2(3) default ' ' not null,
  ccepusac    varchar2(3) default ' ' not null,
  ccepuvth    varchar2(3) default ' ' not null,
  ccepdvac    varchar2(3) default ' ' not null,
  ccepfldr    varchar2(3) default ' ' not null,
  cceppccl    varchar2(1) default ' ' not null,
  ccepsdrg    varchar2(4) default ' ' not null,
  ccepuint    number(4,0) default 0 not null,
  ccepuccu    number(4,0) default 0 not null,
  ccepumec    number(4,0) default 0 not null,
  ccepcpap    number(5,0) default 0 not null,
  cceprclo    varchar2(3) default ' ' not null,
  ccepsrce    varchar2(3) default ' ' not null,
  ccepstyp    varchar2(6) default ' ' not null,
  ccepasit    varchar2(6) default ' ' not null,
  ccepuc21    varchar2(3) default ' ' not null,
  ccepuc09    varchar2(3) default ' ' not null,
  ccepuc20    varchar2(3) default ' ' not null,
  ccepuc28    varchar2(3) default ' ' not null,
  cceprhc1    varchar2(10) default ' ' not null,
  ccepadts    varchar2(5) default ' ' not null,
  ccepdcts    varchar2(5) default ' ' not null,
  ccepspa     varchar2(50) default ' ' not null,
  lf          varchar2(1) default ' ' not null
)
tablespace pas_data; 
create index ccsaudep on ccsaudep
(
ccepaudd,
ccepaudt,
ccepaudp,
ccepaudr
)
tablespace pas_indx; 
create table ccsepsaf
(
  ccephcd     varchar2(2) default ' ' not null,
  ccepeps     varchar2(16) default ' ' not null,
  ccepsur     varchar2(20) default ' ' not null,
  ccepgiv     varchar2(25) default ' ' not null,
  ccepcom     varchar2(1) default ' ' not null,
  ccepurn     varchar2(10) default ' ' not null,
  ccepsdt     varchar2(8) default ' ' not null,
  ccepltd     varchar2(8) default ' ' not null,
  cceplos     number(6,0) default 0 not null,
  ccepinpt    varchar2(1) default ' ' not null,
  ccepday     varchar2(1) default ' ' not null,
  ccepvist    varchar2(2) default ' ' not null,
  ccepsex     varchar2(1) default ' ' not null,
  ccepdob     varchar2(8) default ' ' not null,
  ccepagey    varchar2(3) default ' ' not null,
  ccepagem    varchar2(2) default ' ' not null,
  ccepaged    varchar2(2) default ' ' not null,
  ccepcob     varchar2(3) default ' ' not null,
  cceprel     varchar2(3) default ' ' not null,
  ccepddat    varchar2(8) default ' ' not null,
  ccepdwar    varchar2(3) default ' ' not null,
  ccepdsta    varchar2(3) default ' ' not null,
  ccepddes    varchar2(3) default ' ' not null,
  ccepdmbs    varchar2(9) default ' ' not null,
  ccepddpt    varchar2(3) default ' ' not null,
  ccepdser    varchar2(3) default ' ' not null,
  ccepmdcc    varchar2(4) default ' ' not null,
  ccepdrgc    varchar2(4) default ' ' not null,
  ccepadat    varchar2(8) default ' ' not null,
  ccepawar    varchar2(3) default ' ' not null,
  ccepasrc    varchar2(3) default ' ' not null,
  ccepacls    varchar2(3) default ' ' not null,
  ccepacar    varchar2(3) default ' ' not null,
  ccepadpt    varchar2(3) default ' ' not null,
  ccepaser    varchar2(3) default ' ' not null,
  ccepardc    varchar2(10) default ' ' not null,
  ccepatdc    varchar2(10) default ' ' not null,
  ccepaadc    varchar2(10) default ' ' not null,
  ccepdadc    varchar2(10) default ' ' not null,
  ccepahfd    varchar2(6) default ' ' not null,
  ccepahtb    varchar2(8) default ' ' not null,
  ccepambs    varchar2(9) default ' ' not null,
  ccepopcl    varchar2(6) default ' ' not null,
  cceppdia    varchar2(9) default ' ' not null,
  ccepsdia    varchar2(9) default ' ' not null,
  cceppopp    varchar2(9) default ' ' not null,
  ccepsopp    varchar2(9) default ' ' not null,
  ccepexc     varchar2(1) default ' ' not null,
  cceppmbs    varchar2(9) default ' ' not null,
  ccepsmbs    varchar2(9) default ' ' not null,
  ccepmu1     varchar2(3) default ' ' not null,
  ccepmu2     varchar2(3) default ' ' not null,
  ccepmu3     varchar2(3) default ' ' not null,
  ccepmu4     varchar2(3) default ' ' not null,
  ccepmu5     varchar2(3) default ' ' not null,
  ccepmu6     varchar2(3) default ' ' not null,
  ccepmu7     varchar2(3) default ' ' not null,
  cceppcd     varchar2(10) default ' ' not null,
  ccepclm     varchar2(3) default ' ' not null,
  ccepcli     varchar2(6) default ' ' not null,
  ccepcty     varchar2(3) default ' ' not null,
  ccepana     varchar2(3) default ' ' not null,
  ccepoty     varchar2(3) default ' ' not null,
  ccepttr     varchar2(3) default ' ' not null,
  ccepoy6     varchar2(3) default ' ' not null,
  ccepoy7     varchar2(3) default ' ' not null,
  ccepoy8     varchar2(3) default ' ' not null,
  ccepoy9     varchar2(3) default ' ' not null,
  cceporm     varchar2(6) default ' ' not null,
  ccepoki     varchar2(3) default ' ' not null,
  ccepotp     varchar2(3) default ' ' not null,
  cceptst     varchar2(3) default ' ' not null,
  ccepins     varchar2(3) default ' ' not null,
  cceptim     varchar2(5) default ' ' not null,
  cceptdp     varchar2(5) default ' ' not null,
  ccepast     varchar2(3) default ' ' not null,
  ccepamd     varchar2(3) default ' ' not null,
  ccepau1     varchar2(3) default ' ' not null,
  ccepau2     varchar2(3) default ' ' not null,
  ccepau3     varchar2(3) default ' ' not null,
  ccepau4     varchar2(3) default ' ' not null,
  ccepau5     varchar2(3) default ' ' not null,
  ccepau6     varchar2(3) default ' ' not null,
  ccepau7     varchar2(3) default ' ' not null,
  ccepau8     varchar2(3) default ' ' not null,
  ccepawt     varchar2(3) default ' ' not null,
  ccepapr     varchar2(3) default ' ' not null,
  ccepaet     varchar2(3) default ' ' not null,
  ccepart     varchar2(3) default ' ' not null,
  ccepain     varchar2(3) default ' ' not null,
  ccepapl     varchar2(3) default ' ' not null,
  ccepapy     varchar2(3) default ' ' not null,
  ccepost     varchar2(6) default ' ' not null,
  ccepocl     varchar2(6) default ' ' not null,
  ccepoct     varchar2(6) default ' ' not null,
  ccepovt     varchar2(3) default ' ' not null,
  ccepody     varchar2(1) default ' ' not null,
  cceposs     varchar2(3) default ' ' not null,
  ccepods     varchar2(3) default ' ' not null,
  ccepoat     varchar2(3) default ' ' not null,
  ccepopr     varchar2(3) default ' ' not null,
  ccepou1     varchar2(3) default ' ' not null,
  ccepou2     varchar2(3) default ' ' not null,
  ccepou3     varchar2(3) default ' ' not null,
  ccepou4     varchar2(3) default ' ' not null,
  ccepodp     varchar2(3) default ' ' not null,
  ccepotr     varchar2(3) default ' ' not null,
  ccepolg     varchar2(3) default ' ' not null,
  ccepoot     varchar2(3) default ' ' not null,
  ccepmu8     varchar2(3) default ' ' not null,
  ccepmu9     varchar2(3) default ' ' not null,
  ccepmu10    varchar2(3) default ' ' not null,
  ccepphp     varchar2(3) default ' ' not null,
  ccepagn     varchar2(3) default ' ' not null,
  ccepvw5     number(12,4) default 0 not null,
  ccepv5a     number(12,4) default 0 not null,
  ccepcmx     varchar2(1) default ' ' not null,
  ccepv8a     number(12,4) default 0 not null,
  ccepintr    varchar2(1) default ' ' not null,
  ccepstat    varchar2(1) default ' ' not null,
  ccepcind    varchar2(3) default ' ' not null,
  ccepspca    varchar2(3) default ' ' not null,
  cceprsta    varchar2(1) default ' ' not null,
  cceprhcp    varchar2(10) default ' ' not null,
  ccepprb1    varchar2(9) default ' ' not null,
  ccepprb2    varchar2(9) default ' ' not null,
  ccepprb3    varchar2(9) default ' ' not null,
  ccepdia1    varchar2(9) default ' ' not null,
  ccepdia2    varchar2(9) default ' ' not null,
  ccepdia3    varchar2(9) default ' ' not null,
  ccepencn    varchar2(3) default ' ' not null,
  ccepserp    varchar2(10) default ' ' not null,
  ccepacty    varchar2(6) default ' ' not null,
  ccepserd    varchar2(8) default ' ' not null,
  ccepptyp    varchar2(3) default ' ' not null,
  ccepdept    varchar2(3) default ' ' not null,
  ccepdunt    number(6,0) default 0 not null,
  ccepdbun    number(6,0) default 0 not null,
  ccepiunt    number(6,0) default 0 not null,
  ccepibun    number(6,0) default 0 not null,
  ccepabrg    varchar2(3) default ' ' not null,
  ccepcadm    varchar2(3) default ' ' not null,
  ccepirad    varchar2(3) default ' ' not null,
  ccepidus    varchar2(3) default ' ' not null,
  ccepcrav    varchar2(3) default ' ' not null,
  cceprcct    varchar2(3) default ' ' not null,
  ccepindc    varchar2(1) default ' ' not null,
  ccepmdav    varchar2(3) default ' ' not null,
  ccepcsng    varchar2(3) default ' ' not null,
  ccepasut    varchar2(3) default ' ' not null,
  ccepelps    varchar2(3) default ' ' not null,
  ccepempl    varchar2(3) default ' ' not null,
  ccepfinp    varchar2(3) default ' ' not null,
  ccepoccp    varchar2(3) default ' ' not null,
  cceppalc    varchar2(3) default ' ' not null,
  ccepppal    varchar2(3) default ' ' not null,
  cceppppt    varchar2(3) default ' ' not null,
  cceppsos    varchar2(3) default ' ' not null,
  cceppysp    varchar2(3) default ' ' not null,
  ccepqldb    varchar2(3) default ' ' not null,
  ccepread    varchar2(3) default ' ' not null,
  ccepudin    varchar2(3) default ' ' not null,
  ccepurea    varchar2(3) default ' ' not null,
  ccepusac    varchar2(3) default ' ' not null,
  ccepuvth    varchar2(3) default ' ' not null,
  ccepdvac    varchar2(3) default ' ' not null,
  ccepfldr    varchar2(3) default ' ' not null,
  cceppccl    varchar2(1) default ' ' not null,
  ccepsdrg    varchar2(4) default ' ' not null,
  ccepuint    number(4,0) default 0 not null,
  ccepuccu    number(4,0) default 0 not null,
  ccepumec    number(4,0) default 0 not null,
  ccepcpap    number(5,0) default 0 not null,
  cceprclo    varchar2(3) default ' ' not null,
  ccepsrce    varchar2(3) default ' ' not null,
  ccepstyp    varchar2(6) default ' ' not null,
  ccepasit    varchar2(6) default ' ' not null,
  ccepuc21    varchar2(3) default ' ' not null,
  ccepuc09    varchar2(3) default ' ' not null,
  ccepuc20    varchar2(3) default ' ' not null,
  ccepuc28    varchar2(3) default ' ' not null,
  cceprhc1    varchar2(10) default ' ' not null,
  ccepadts    varchar2(5) default ' ' not null,
  ccepdcts    varchar2(5) default ' ' not null,
  ccepspa     varchar2(50) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint ccsepsa1 primary key( 
ccephcd,
ccepeps)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index ccsepsa2 on ccsepsaf
(
ccepcom,
ccephcd,
ccepeps
)
  tablespace pas_indx; 
create unique index ccsepsa3 on ccsepsaf
(
ccepltd,
ccephcd,
ccepeps
)
  tablespace pas_indx; 
create unique index ccsepsa4 on ccsepsaf
(
ccepddat,
ccephcd,
ccepeps
)
  tablespace pas_indx; 
create unique index ccsepsa5 on ccsepsaf
(
ccepurn,
ccephcd,
ccepeps
)
  tablespace pas_indx; 
