create table ceappmaf
(
  ceppind     varchar2(1) default ' ' not null,
  ceppdes     varchar2(35) default ' ' not null,
  ceppnurf    number(8,4) default 0 not null,
  ceppthef    number(8,4) default 0 not null,
  ceppphaf    number(8,4) default 0 not null,
  ceppicuf    number(8,4) default 0 not null,
  ceppallf    number(8,4) default 0 not null,
  ceppmssf    number(8,4) default 0 not null,
  cepptaxf    number(8,4) default 0 not null,
  ceppovhf    number(8,4) default 0 not null,
  ceppcatf    number(8,4) default 0 not null,
  ceppdepf    number(8,4) default 0 not null,
  ceppothf    number(8,4) default 0 not null,
  ceppnurv    number(8,4) default 0 not null,
  ceppthev    number(8,4) default 0 not null,
  ceppphav    number(8,4) default 0 not null,
  ceppicuv    number(8,4) default 0 not null,
  ceppallv    number(8,4) default 0 not null,
  ceppmssv    number(8,4) default 0 not null,
  cepptaxv    number(8,4) default 0 not null,
  ceppovhv    number(8,4) default 0 not null,
  ceppcatv    number(8,4) default 0 not null,
  ceppdepv    number(8,4) default 0 not null,
  ceppothv    number(8,4) default 0 not null,
  cepppro     number(8,4) default 0 not null,
  ceppicu     number(8,2) default 0 not null,
  ceppinci    number(1,0) default 0 not null,
  cepputh     number(1,0) default 0 not null,
  ceppb01     number(8,2) default 0 not null,
  ceppb02     number(8,2) default 0 not null,
  ceppb03     number(8,2) default 0 not null,
  ceppb04     number(8,2) default 0 not null,
  ceppb05     number(8,2) default 0 not null,
  ceppb06     number(8,2) default 0 not null,
  ceppb07     number(8,2) default 0 not null,
  ceppb08     number(8,2) default 0 not null,
  ceppb09     number(8,2) default 0 not null,
  ceppb10     number(8,2) default 0 not null,
  ceppb11     number(8,2) default 0 not null,
  ceppb12     number(8,2) default 0 not null,
  ceppb13     number(8,2) default 0 not null,
  ceppb14     number(8,2) default 0 not null,
  ceppb15     number(8,2) default 0 not null,
  ceppspa     varchar2(40) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint ceappma1 primary key( 
ceppind)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
