create table depcphaf
(
  dppcdate    varchar2(8) default ' ' not null,
  dppcward    varchar2(3) default ' ' not null,
  dppctime    varchar2(5) default ' ' not null,
  dppcshft    varchar2(3) default ' ' not null,
  ddppcadm    varchar2(8) default ' ' not null,
  dppccatg    varchar2(3) default ' ' not null,
  dppcat01    varchar2(3) default ' ' not null,
  dppcat02    varchar2(3) default ' ' not null,
  dppcat03    varchar2(3) default ' ' not null,
  dppcat04    varchar2(3) default ' ' not null,
  dppcat05    varchar2(3) default ' ' not null,
  dppcat06    varchar2(3) default ' ' not null,
  dppcat07    varchar2(3) default ' ' not null,
  dppcat08    varchar2(3) default ' ' not null,
  dppcat09    varchar2(3) default ' ' not null,
  dppcat10    varchar2(3) default ' ' not null,
  dppcat11    varchar2(3) default ' ' not null,
  dppcat12    varchar2(3) default ' ' not null,
  dppcat13    varchar2(3) default ' ' not null,
  dppcat14    varchar2(3) default ' ' not null,
  dppcat15    varchar2(3) default ' ' not null,
  dppcat16    varchar2(3) default ' ' not null,
  dppcat17    varchar2(3) default ' ' not null,
  dppcat18    varchar2(3) default ' ' not null,
  dppcat19    varchar2(3) default ' ' not null,
  dppcat20    varchar2(3) default ' ' not null,
  dppcat21    varchar2(3) default ' ' not null,
  dppcat22    varchar2(3) default ' ' not null,
  dppcat23    varchar2(3) default ' ' not null,
  dppcat24    varchar2(3) default ' ' not null,
  dppcat25    varchar2(3) default ' ' not null,
  dppcat26    varchar2(3) default ' ' not null,
  dppcat27    varchar2(3) default ' ' not null,
  dppcat28    varchar2(3) default ' ' not null,
  dppcat29    varchar2(3) default ' ' not null,
  dppcat30    varchar2(3) default ' ' not null,
  dppcat31    varchar2(3) default ' ' not null,
  dppcat32    varchar2(3) default ' ' not null,
  dppcat33    varchar2(3) default ' ' not null,
  dppcat34    varchar2(3) default ' ' not null,
  dppcat35    varchar2(3) default ' ' not null,
  dppcat36    varchar2(3) default ' ' not null,
  dppcat37    varchar2(3) default ' ' not null,
  dppcat38    varchar2(3) default ' ' not null,
  dppcat39    varchar2(3) default ' ' not null,
  dppcat40    varchar2(3) default ' ' not null,
  dppcat41    varchar2(3) default ' ' not null,
  dppcat42    varchar2(3) default ' ' not null,
  dppcat43    varchar2(3) default ' ' not null,
  dppcat44    varchar2(3) default ' ' not null,
  dppcat45    varchar2(3) default ' ' not null,
  dppcat46    varchar2(3) default ' ' not null,
  dppcat47    varchar2(3) default ' ' not null,
  dppcat48    varchar2(3) default ' ' not null,
  dppcat49    varchar2(3) default ' ' not null,
  dppcat50    varchar2(3) default ' ' not null,
  dppcat51    varchar2(3) default ' ' not null,
  dppcat52    varchar2(3) default ' ' not null,
  dppcat53    varchar2(3) default ' ' not null,
  dppcat54    varchar2(3) default ' ' not null,
  dppcat55    varchar2(3) default ' ' not null,
  dppcat56    varchar2(3) default ' ' not null,
  dppcat57    varchar2(3) default ' ' not null,
  dppcat58    varchar2(3) default ' ' not null,
  dppcat59    varchar2(3) default ' ' not null,
  dppcat60    varchar2(3) default ' ' not null,
  ddppctot    varchar2(4) default ' ' not null,
  dppcspre    varchar2(16) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint depcpha1 primary key( 
dppcdate,
dppcward,
dppctime,
dppcshft,
ddppcadm)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index depcpha2 on depcphaf
(
ddppcadm,
dppcdate,
dppctime,
dppcshft,
dppcward
)
  tablespace pas_indx; 
