create table emrcliaf
(
  emcivisn    varchar2(8) default ' ' not null,
  emcior01    varchar2(1) default ' ' not null,
  emcior02    varchar2(1) default ' ' not null,
  emcior03    varchar2(1) default ' ' not null,
  emcior04    varchar2(1) default ' ' not null,
  emcior05    varchar2(1) default ' ' not null,
  emcior06    varchar2(1) default ' ' not null,
  emcior07    varchar2(1) default ' ' not null,
  emcior08    varchar2(1) default ' ' not null,
  emcior09    varchar2(1) default ' ' not null,
  emcior10    varchar2(1) default ' ' not null,
  emcipr01    varchar2(1) default ' ' not null,
  emcipr02    varchar2(1) default ' ' not null,
  emcipr03    varchar2(1) default ' ' not null,
  emcipr04    varchar2(1) default ' ' not null,
  emcipr05    varchar2(1) default ' ' not null,
  emcipr06    varchar2(1) default ' ' not null,
  emcipr07    varchar2(1) default ' ' not null,
  emcipr08    varchar2(1) default ' ' not null,
  emcipr09    varchar2(1) default ' ' not null,
  emcipr10    varchar2(1) default ' ' not null,
  emcirs01    varchar2(1) default ' ' not null,
  emcirs02    varchar2(1) default ' ' not null,
  emcirs03    varchar2(1) default ' ' not null,
  emcirs04    varchar2(1) default ' ' not null,
  emcirs05    varchar2(1) default ' ' not null,
  emcirs06    varchar2(1) default ' ' not null,
  emcirs07    varchar2(1) default ' ' not null,
  emcirs08    varchar2(1) default ' ' not null,
  emcirs09    varchar2(1) default ' ' not null,
  emcirs10    varchar2(1) default ' ' not null,
  emcipcom    varchar2(3) default ' ' not null,
  emcilmds    varchar2(50) default ' ' not null,
  emcilmcd    varchar2(10) default ' ' not null,
  emcilmcf    varchar2(3) default ' ' not null,
  emcirccd    varchar2(10) default ' ' not null,
  emcircff    varchar2(50) default ' ' not null,
  emcirctm    varchar2(5) default ' ' not null,
  emciscff    varchar2(50) default ' ' not null,
  emciscvc    varchar2(3) default ' ' not null,
  emcitsct    varchar2(5) default ' ' not null,
  emciprdt    varchar2(8) default ' ' not null,
  emcirrff    varchar2(50) default ' ' not null,
  emciuwcr    varchar2(10) default ' ' not null,
  emcircdt    varchar2(8) default ' ' not null,
  emcitrcd    varchar2(8) default ' ' not null,
  emciuupd    varchar2(10) default ' ' not null,
  emcirudt    varchar2(8) default ' ' not null,
  emcitrup    varchar2(8) default ' ' not null,
  emcispar    varchar2(100) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint emrclia1 primary key( 
emcivisn)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
