create table emrvisaf
(
  demviadm    varchar2(8) default ' ' not null,
  demvista    varchar2(1) default ' ' not null,
  emviurno    varchar2(8) default ' ' not null,
  emvidate    varchar2(8) default ' ' not null,
  emvitime    varchar2(8) default ' ' not null,
  emvitrig    varchar2(3) default ' ' not null,
  emvicom1    varchar2(50) default ' ' not null,
  emvicom2    varchar2(50) default ' ' not null,
  emvilocn    varchar2(3) default ' ' not null,
  emvidoct    varchar2(10) default ' ' not null,
  emvicomp    varchar2(3) default ' ' not null,
  emviclas    varchar2(3) default ' ' not null,
  emviinsr    varchar2(3) default ' ' not null,
  emvisrce    varchar2(3) default ' ' not null,
  emvisitn    varchar2(3) default ' ' not null,
  emvimode    varchar2(3) default ' ' not null,
  emviadmt    number(1,0) default 0 not null,
  emvidurn    number(4,0) default 0 not null,
  emviempl    varchar2(20) default ' ' not null,
  emviwait    varchar2(3) default ' ' not null,
  emviprev    varchar2(3) default ' ' not null,
  emvifund    varchar2(6) default ' ' not null,
  emvitabl    varchar2(8) default ' ' not null,
  emvirefg    varchar2(10) default ' ' not null,
  emvirefd    varchar2(10) default ' ' not null,
  emviplin    varchar2(3) default ' ' not null,
  emviinit    varchar2(3) default ' ' not null,
  emvirtas    varchar2(3) default ' ' not null,
  emviddat    varchar2(8) default ' ' not null,
  emvidtim    varchar2(8) default ' ' not null,
  emvidsta    varchar2(3) default ' ' not null,
  emviopr1    varchar2(10) default ' ' not null,
  emviopr2    varchar2(10) default ' ' not null,
  emviuc01    varchar2(3) default ' ' not null,
  emviuc02    varchar2(3) default ' ' not null,
  emviuc03    varchar2(3) default ' ' not null,
  emviuc04    varchar2(3) default ' ' not null,
  emviuc05    varchar2(3) default ' ' not null,
  emviuc06    varchar2(3) default ' ' not null,
  emviuc07    varchar2(3) default ' ' not null,
  emviuc08    varchar2(3) default ' ' not null,
  emviuc09    varchar2(3) default ' ' not null,
  emviuc10    varchar2(3) default ' ' not null,
  emviuc11    varchar2(3) default ' ' not null,
  emviuc12    varchar2(3) default ' ' not null,
  emviuc13    varchar2(3) default ' ' not null,
  emviuc14    varchar2(3) default ' ' not null,
  emviuc15    varchar2(3) default ' ' not null,
  emviuc16    varchar2(3) default ' ' not null,
  emviuc17    varchar2(3) default ' ' not null,
  emviuc18    varchar2(3) default ' ' not null,
  emviuc19    varchar2(3) default ' ' not null,
  emviuc20    varchar2(3) default ' ' not null,
  emviuc21    varchar2(3) default ' ' not null,
  emviuc22    varchar2(3) default ' ' not null,
  emviuc23    varchar2(3) default ' ' not null,
  emviuc24    varchar2(3) default ' ' not null,
  emviuc25    varchar2(3) default ' ' not null,
  emviuc26    varchar2(3) default ' ' not null,
  emviuc27    varchar2(3) default ' ' not null,
  emviuc28    varchar2(3) default ' ' not null,
  emviuc29    varchar2(3) default ' ' not null,
  emviuc30    varchar2(3) default ' ' not null,
  emviud01    varchar2(8) default ' ' not null,
  emviud02    varchar2(8) default ' ' not null,
  emviud03    varchar2(8) default ' ' not null,
  emviud04    varchar2(8) default ' ' not null,
  emviud05    varchar2(8) default ' ' not null,
  emviud06    varchar2(8) default ' ' not null,
  emviud07    varchar2(8) default ' ' not null,
  emviud08    varchar2(8) default ' ' not null,
  emviud09    varchar2(8) default ' ' not null,
  emviud10    varchar2(8) default ' ' not null,
  emviut01    varchar2(8) default ' ' not null,
  emviut02    varchar2(8) default ' ' not null,
  emviut03    varchar2(8) default ' ' not null,
  emviut04    varchar2(8) default ' ' not null,
  emviut05    varchar2(8) default ' ' not null,
  emviut06    varchar2(8) default ' ' not null,
  emviut07    varchar2(8) default ' ' not null,
  emviut08    varchar2(8) default ' ' not null,
  emviut09    varchar2(8) default ' ' not null,
  emviut10    varchar2(8) default ' ' not null,
  emviyn01    number(1,0) default 0 not null,
  emviyn02    number(1,0) default 0 not null,
  emviyn03    number(1,0) default 0 not null,
  emviyn04    number(1,0) default 0 not null,
  emviyn05    number(1,0) default 0 not null,
  emviyn06    number(1,0) default 0 not null,
  emviyn07    number(1,0) default 0 not null,
  emviyn08    number(1,0) default 0 not null,
  emviyn09    number(1,0) default 0 not null,
  emviyn10    number(1,0) default 0 not null,
  emvitxt1    varchar2(50) default ' ' not null,
  emvitxt2    varchar2(50) default ' ' not null,
  emvitxt3    varchar2(50) default ' ' not null,
  emvitxt4    varchar2(50) default ' ' not null,
  emvitxt5    varchar2(50) default ' ' not null,
  emviun01    number(6,0) default 0 not null,
  emviun02    number(6,0) default 0 not null,
  emviun03    number(6,0) default 0 not null,
  emviun04    number(6,0) default 0 not null,
  emviun05    number(6,0) default 0 not null,
  emvielap    varchar2(3) default ' ' not null,
  emvinsdt    varchar2(8) default ' ' not null,
  emvinstm    varchar2(8) default ' ' not null,
  emvidrdt    varchar2(8) default ' ' not null,
  emvidrtm    varchar2(8) default ' ' not null,
  emvipatt    number(3,0) default 0 not null,
  emvitsrc    varchar2(5) default ' ' not null,
  emvidest    varchar2(5) default ' ' not null,
  emviambl    varchar2(15) default ' ' not null,
  emviregn    varchar2(2) default ' ' not null,
  emvisent    varchar2(1) default ' ' not null,
  emviur01    varchar2(6) default ' ' not null,
  emviur02    varchar2(6) default ' ' not null,
  emviur03    varchar2(6) default ' ' not null,
  emviur04    varchar2(6) default ' ' not null,
  emviur05    varchar2(6) default ' ' not null,
  emvipadm    varchar2(8) default ' ' not null,
  emviewrd    varchar2(3) default ' ' not null,
  emviebed    varchar2(3) default ' ' not null,
  emvihfmn    varchar2(19) default ' ' not null,
  emviacls    varchar2(3) default ' ' not null,
  emviccls    varchar2(3) default ' ' not null,
  emvitrns    varchar2(10) default ' ' not null,
  emvidum1    varchar2(3) default ' ' not null,
  emvitrdt    varchar2(8) default ' ' not null,
  emvitrtm    varchar2(8) default ' ' not null,
  emviatns    varchar2(10) default ' ' not null,
  emvidum2    varchar2(3) default ' ' not null,
  emviexlc    varchar2(3) default ' ' not null,
  emvisite    varchar2(3) default ' ' not null,
  emviunit    varchar2(3) default ' ' not null,
  emvicom3    varchar2(50) default ' ' not null,
  emvicom4    varchar2(50) default ' ' not null,
  emvicom5    varchar2(50) default ' ' not null,
  emvicom6    varchar2(50) default ' ' not null,
  emviinj1    varchar2(50) default ' ' not null,
  emviinj2    varchar2(50) default ' ' not null,
  emvinati    varchar2(3) default ' ' not null,
  emviinjc    varchar2(3) default ' ' not null,
  emvihumi    varchar2(3) default ' ' not null,
  emviacti    varchar2(3) default ' ' not null,
  emviloco    varchar2(25) default ' ' not null,
  emviprlo    varchar2(3) default ' ' not null,
  emviprtm    varchar2(8) default ' ' not null,
  emvidpdt    varchar2(8) default ' ' not null,
  emvidptm    varchar2(8) default ' ' not null,
  emviexrs    varchar2(3) default ' ' not null,
  emvidlrs    varchar2(3) default ' ' not null,
  emvispdt    varchar2(8) default ' ' not null,
  emvisptm    varchar2(8) default ' ' not null,
  emvisadt    varchar2(8) default ' ' not null,
  emvisatm    varchar2(8) default ' ' not null,
  emvimpra    varchar2(10) default ' ' not null,
  emvimpdt    varchar2(8) default ' ' not null,
  emvimptm    varchar2(8) default ' ' not null,
  emviaadt    varchar2(8) default ' ' not null,
  emviaatm    varchar2(8) default ' ' not null,
  emviahdt    varchar2(8) default ' ' not null,
  emviahtm    varchar2(8) default ' ' not null,
  emvidadt    varchar2(8) default ' ' not null,
  emvidatm    varchar2(8) default ' ' not null,
  emvipurc    varchar2(3) default ' ' not null,
  emvimncd    varchar2(10) default ' ' not null,
  emvimndt    varchar2(8) default ' ' not null,
  emvimntm    varchar2(8) default ' ' not null,
  emvimdcd    varchar2(10) default ' ' not null,
  emvimddt    varchar2(8) default ' ' not null,
  emvimdtm    varchar2(8) default ' ' not null,
  emviuc31    varchar2(3) default ' ' not null,
  emviuc32    varchar2(3) default ' ' not null,
  emviuc33    varchar2(3) default ' ' not null,
  emviuc34    varchar2(3) default ' ' not null,
  emviuc35    varchar2(3) default ' ' not null,
  emvirefp    varchar2(3) default ' ' not null,
  emvirepm    varchar2(2) default ' ' not null,
  emviredt    varchar2(8) default ' ' not null,
  emvibnaa    varchar2(1) default ' ' not null,
  emvivsty    varchar2(3) default ' ' not null,
  emvivplc    varchar2(3) default ' ' not null,
  emviahcp    varchar2(10) default ' ' not null,
  emviahst    varchar2(1) default ' ' not null,
  emvidisd    varchar2(3) default ' ' not null,
  emvidrug    varchar2(1) default ' ' not null,
  emvispar    varchar2(41) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint emrvisa1 primary key( 
demviadm)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index emrvisa2 on emrvisaf
(
demvista,
demviadm
)
  tablespace pas_indx; 
create unique index emrvisa3 on emrvisaf
(
emviurno,
demviadm
)
  tablespace pas_indx; 
create unique index emrvisa4 on emrvisaf
(
emvidate,
emvitime,
demviadm
)
  tablespace pas_indx; 
create unique index emrvisa5 on emrvisaf
(
emvisite,
demvista,
demviadm
)
  tablespace pas_indx; 
create unique index emrvisa6 on emrvisaf
(
emvisite,
emvidate,
emvitime,
demviadm
)
  tablespace pas_indx; 
create unique index emrvisa7 on emrvisaf
(
emvilocn,
demviadm
)
  tablespace pas_indx; 
