create table eocaccaf
(
  ecacaccn    varchar2(20) default ' ' not null,
  ecacacca    number(1,0) default 0 not null,
  ecacdat1    varchar2(8) default ' ' not null,
  ecactim1    varchar2(5) default ' ' not null,
  ecacdat2    varchar2(8) default ' ' not null,
  ecactim2    varchar2(5) default ' ' not null,
  ecacdat3    varchar2(8) default ' ' not null,
  ecactim3    varchar2(5) default ' ' not null,
  ecacdat4    varchar2(8) default ' ' not null,
  ecactim4    varchar2(5) default ' ' not null,
  ecacdat5    varchar2(8) default ' ' not null,
  ecactim5    varchar2(5) default ' ' not null,
  ecacdat6    varchar2(8) default ' ' not null,
  ecactim6    varchar2(5) default ' ' not null,
  ecacdoc1    varchar2(6) default ' ' not null,
  ecacdoc2    varchar2(6) default ' ' not null,
  ecacdoc3    varchar2(6) default ' ' not null,
  ecacdoc4    varchar2(6) default ' ' not null,
  ecacdoc5    varchar2(6) default ' ' not null,
  ecacdoc6    varchar2(6) default ' ' not null,
  ecacdia1    varchar2(9) default ' ' not null,
  ecacdia2    varchar2(9) default ' ' not null,
  ecacdia3    varchar2(9) default ' ' not null,
  ecacdia4    varchar2(60) default ' ' not null,
  ecacdia5    varchar2(60) default ' ' not null,
  ecacdia6    varchar2(60) default ' ' not null,
  ecacyno1    number(1,0) default 0 not null,
  ecacyno2    number(1,0) default 0 not null,
  ecacyno3    number(1,0) default 0 not null,
  ecacyno4    number(1,0) default 0 not null,
  ecacyno5    number(1,0) default 0 not null,
  ecacyno6    number(1,0) default 0 not null,
  ecacfre1    varchar2(60) default ' ' not null,
  ecacfre2    varchar2(60) default ' ' not null,
  ecacfre3    varchar2(60) default ' ' not null,
  ecacfre4    varchar2(60) default ' ' not null,
  ecacfre5    varchar2(60) default ' ' not null,
  ecacfre6    varchar2(60) default ' ' not null,
  ecacfre7    varchar2(60) default ' ' not null,
  ecacfre8    varchar2(60) default ' ' not null,
  ecacfre9    varchar2(60) default ' ' not null,
  ecacfr10    varchar2(60) default ' ' not null,
  ecaccod1    varchar2(3) default ' ' not null,
  ecaccod2    varchar2(3) default ' ' not null,
  ecaccod3    varchar2(3) default ' ' not null,
  ecaccod4    varchar2(3) default ' ' not null,
  ecaccod5    varchar2(3) default ' ' not null,
  ecaccod6    varchar2(3) default ' ' not null,
  ecaccod7    varchar2(3) default ' ' not null,
  ecaccod8    varchar2(3) default ' ' not null,
  ecaccod9    varchar2(3) default ' ' not null,
  ecacnum1    number(8,0) default 0 not null,
  ecacnum2    number(8,0) default 0 not null,
  ecacdacc    varchar2(8) default ' ' not null,
  ecacspar    varchar2(30) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint eocacca1 primary key( 
ecacaccn)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
