create table fmslmcaf
(
  fmlcledg    varchar2(2) default ' ' not null,
  fmlcyear    varchar2(4) default ' ' not null,
  fmlc01fr    varchar2(8) default ' ' not null,
  fmlc01to    varchar2(8) default ' ' not null,
  fmlc01de    varchar2(15) default ' ' not null,
  fmlc01in    number(1,0) default 0 not null,
  fmlc02fr    varchar2(8) default ' ' not null,
  fmlc02to    varchar2(8) default ' ' not null,
  fmlc02de    varchar2(15) default ' ' not null,
  fmlc02in    number(1,0) default 0 not null,
  fmlc03fr    varchar2(8) default ' ' not null,
  fmlc03to    varchar2(8) default ' ' not null,
  fmlc03de    varchar2(15) default ' ' not null,
  fmlc03in    number(1,0) default 0 not null,
  fmlc04fr    varchar2(8) default ' ' not null,
  fmlc04to    varchar2(8) default ' ' not null,
  fmlc04de    varchar2(15) default ' ' not null,
  fmlc04in    number(1,0) default 0 not null,
  fmlc05fr    varchar2(8) default ' ' not null,
  fmlc05to    varchar2(8) default ' ' not null,
  fmlc05de    varchar2(15) default ' ' not null,
  fmlc05in    number(1,0) default 0 not null,
  fmlc06fr    varchar2(8) default ' ' not null,
  fmlc06to    varchar2(8) default ' ' not null,
  fmlc06de    varchar2(15) default ' ' not null,
  fmlc06in    number(1,0) default 0 not null,
  fmlc07fr    varchar2(8) default ' ' not null,
  fmlc07to    varchar2(8) default ' ' not null,
  fmlc07de    varchar2(15) default ' ' not null,
  fmlc07in    number(1,0) default 0 not null,
  fmlc08fr    varchar2(8) default ' ' not null,
  fmlc08to    varchar2(8) default ' ' not null,
  fmlc08de    varchar2(15) default ' ' not null,
  fmlc08in    number(1,0) default 0 not null,
  fmlc09fr    varchar2(8) default ' ' not null,
  fmlc09to    varchar2(8) default ' ' not null,
  fmlc09de    varchar2(15) default ' ' not null,
  fmlc09in    number(1,0) default 0 not null,
  fmlc10fr    varchar2(8) default ' ' not null,
  fmlc10to    varchar2(8) default ' ' not null,
  fmlc10de    varchar2(15) default ' ' not null,
  fmlc10in    number(1,0) default 0 not null,
  fmlc11fr    varchar2(8) default ' ' not null,
  fmlc11to    varchar2(8) default ' ' not null,
  fmlc11de    varchar2(15) default ' ' not null,
  fmlc11in    number(1,0) default 0 not null,
  fmlc12fr    varchar2(8) default ' ' not null,
  fmlc12to    varchar2(8) default ' ' not null,
  fmlc12de    varchar2(15) default ' ' not null,
  fmlc12in    number(1,0) default 0 not null,
  fmlc13fr    varchar2(8) default ' ' not null,
  fmlc13to    varchar2(8) default ' ' not null,
  fmlc13de    varchar2(15) default ' ' not null,
  fmlc13in    number(1,0) default 0 not null,
  fmlcylc     number(1,0) default 0 not null,
  fmlcbudg    varchar2(4) default ' ' not null,
  fmlccbud    varchar2(4) default ' ' not null,
  fmlcspar    varchar2(10) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint fmslmca1 primary key( 
fmlcledg,
fmlcyear)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
