create table ibasceaf
(
  ibseurno    varchar2(8) default ' ' not null,
  ibsevisn    varchar2(8) default ' ' not null,
  ibsecntr    varchar2(8) default ' ' not null,
  ibsefl01    varchar2(1) default ' ' not null,
  ibsefl02    varchar2(1) default ' ' not null,
  ibsefl03    varchar2(1) default ' ' not null,
  ibsefl04    varchar2(1) default ' ' not null,
  ibsefl05    varchar2(1) default ' ' not null,
  ibsefl06    varchar2(1) default ' ' not null,
  ibsefl07    varchar2(1) default ' ' not null,
  ibsefl08    varchar2(1) default ' ' not null,
  ibsefl09    varchar2(1) default ' ' not null,
  ibsefl10    varchar2(1) default ' ' not null,
  ibsefl11    varchar2(1) default ' ' not null,
  ibsefl12    varchar2(1) default ' ' not null,
  ibsefl13    varchar2(1) default ' ' not null,
  ibsefl14    varchar2(1) default ' ' not null,
  ibsefl15    varchar2(1) default ' ' not null,
  ibsefl16    varchar2(1) default ' ' not null,
  ibsefl17    varchar2(1) default ' ' not null,
  ibsefl18    varchar2(1) default ' ' not null,
  ibsefl19    varchar2(1) default ' ' not null,
  ibsefl20    varchar2(1) default ' ' not null,
  ibsecd01    varchar2(1) default ' ' not null,
  ibsecd02    varchar2(1) default ' ' not null,
  ibsecd03    varchar2(1) default ' ' not null,
  ibsecd04    varchar2(1) default ' ' not null,
  ibsecd05    varchar2(1) default ' ' not null,
  ibsecd06    varchar2(1) default ' ' not null,
  ibsecd07    varchar2(1) default ' ' not null,
  ibsecd08    varchar2(1) default ' ' not null,
  ibsecd09    varchar2(1) default ' ' not null,
  ibsecd10    varchar2(1) default ' ' not null,
  ibsecd11    varchar2(1) default ' ' not null,
  ibsecd12    varchar2(1) default ' ' not null,
  ibsecd13    varchar2(1) default ' ' not null,
  ibsecd14    varchar2(1) default ' ' not null,
  ibsecd15    varchar2(1) default ' ' not null,
  ibsesd01    varchar2(6) default ' ' not null,
  ibsesd02    varchar2(6) default ' ' not null,
  ibsesd03    varchar2(8) default ' ' not null,
  ibsesd04    varchar2(8) default ' ' not null,
  ibsesd05    varchar2(10) default ' ' not null,
  ibsesd06    varchar2(10) default ' ' not null,
  ibsemd01    varchar2(50) default ' ' not null,
  ibsemd02    varchar2(50) default ' ' not null,
  ibsemd03    varchar2(50) default ' ' not null,
  ibsemd04    varchar2(50) default ' ' not null,
  ibsemd05    varchar2(50) default ' ' not null,
  ibsemd06    varchar2(50) default ' ' not null,
  ibsemd07    varchar2(50) default ' ' not null,
  ibsemd08    varchar2(50) default ' ' not null,
  ibsemd09    varchar2(50) default ' ' not null,
  ibsemd10    varchar2(50) default ' ' not null,
  ibsemd11    varchar2(50) default ' ' not null,
  ibsemd12    varchar2(50) default ' ' not null,
  ibsexl01    varchar2(200) default ' ' not null,
  ibsexl02    varchar2(200) default ' ' not null,
  ibsexl03    varchar2(200) default ' ' not null,
  ibsexl04    varchar2(200) default ' ' not null,
  ibsexl05    varchar2(200) default ' ' not null,
  ibsecdat    varchar2(8) default ' ' not null,
  ibsectim    varchar2(8) default ' ' not null,
  ibsecuid    varchar2(10) default ' ' not null,
  ibseudat    varchar2(8) default ' ' not null,
  ibseutim    varchar2(8) default ' ' not null,
  ibseuuid    varchar2(10) default ' ' not null,
  ibsespar    varchar2(40) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint ibascea1 primary key( 
ibseurno,
ibsevisn)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
