create table mehdiaaf
(
  dmhdiadm    varchar2(8) default ' ' not null,
  mhdidate    varchar2(8) default ' ' not null,
  mhdiicd1    varchar2(9) default ' ' not null,
  mhdides1    varchar2(200) default ' ' not null,
  mhdisup1    number(1,0) default 0 not null,
  mhdidat1    varchar2(8) default ' ' not null,
  mhdiicd2    varchar2(9) default ' ' not null,
  mhdides2    varchar2(200) default ' ' not null,
  mhdisup2    number(1,0) default 0 not null,
  mhdidat2    varchar2(8) default ' ' not null,
  mhdix1ca    varchar2(9) default ' ' not null,
  mhdix1cb    varchar2(9) default ' ' not null,
  mhdix1cc    varchar2(9) default ' ' not null,
  mhdix1da    varchar2(70) default ' ' not null,
  mhdix1db    varchar2(70) default ' ' not null,
  mhdix1dc    varchar2(70) default ' ' not null,
  mhdix2ca    varchar2(9) default ' ' not null,
  mhdix2cb    varchar2(9) default ' ' not null,
  mhdix2cc    varchar2(9) default ' ' not null,
  mhdix2da    varchar2(70) default ' ' not null,
  mhdix2db    varchar2(70) default ' ' not null,
  mhdix2dc    varchar2(70) default ' ' not null,
  mhdix3ds    varchar2(50) default ' ' not null,
  mhdix4cd    varchar2(3) default ' ' not null,
  mhdix5cd    varchar2(3) default ' ' not null,
  mhdixdat    varchar2(8) default ' ' not null,
  mhdioper    varchar2(4) default ' ' not null,
  mhdiaxiv    varchar2(20) default ' ' not null,
  mhdimohr    varchar2(1) default ' ' not null,
  mhdix3ca    varchar2(9) default ' ' not null,
  mhdix3cb    varchar2(9) default ' ' not null,
  mhdix3cc    varchar2(9) default ' ' not null,
  mhdix3da    varchar2(70) default ' ' not null,
  mhdix3db    varchar2(70) default ' ' not null,
  mhdix3dc    varchar2(70) default ' ' not null,
  mhdicdat    varchar2(8) default ' ' not null,
  mhdictim    varchar2(8) default ' ' not null,
  mhdicuid    varchar2(10) default ' ' not null,
  mhdiudat    varchar2(8) default ' ' not null,
  mhdiutim    varchar2(8) default ' ' not null,
  mhdiuuid    varchar2(10) default ' ' not null,
  mhdiicd3    varchar2(9) default ' ' not null,
  mhdides3    varchar2(200) default ' ' not null,
  mhdisup3    number(1,0) default 0 not null,
  mhdidat3    varchar2(8) default ' ' not null,
  mhdiicd4    varchar2(9) default ' ' not null,
  mhdides4    varchar2(200) default ' ' not null,
  mhdisup4    number(1,0) default 0 not null,
  mhdidat4    varchar2(8) default ' ' not null,
  mhdiicd5    varchar2(9) default ' ' not null,
  mhdides5    varchar2(200) default ' ' not null,
  mhdisup5    number(1,0) default 0 not null,
  mhdidat5    varchar2(8) default ' ' not null,
  mhdiicd6    varchar2(9) default ' ' not null,
  mhdides6    varchar2(200) default ' ' not null,
  mhdisup6    number(1,0) default 0 not null,
  mhdidat6    varchar2(8) default ' ' not null,
  mhdip1ca    varchar2(1) default ' ' not null,
  mhdip1cb    varchar2(1) default ' ' not null,
  mhdip1cc    varchar2(1) default ' ' not null,
  mhdip2ca    varchar2(1) default ' ' not null,
  mhdip2cb    varchar2(1) default ' ' not null,
  mhdip2cc    varchar2(1) default ' ' not null,
  mhdihcpc    varchar2(10) default ' ' not null,
  mhdicast    varchar2(10) default ' ' not null,
  mhdidty1    varchar2(1) default ' ' not null,
  mhdidty2    varchar2(1) default ' ' not null,
  mhdidty3    varchar2(1) default ' ' not null,
  mhdidty4    varchar2(1) default ' ' not null,
  mhdidty5    varchar2(1) default ' ' not null,
  mhdidty6    varchar2(1) default ' ' not null,
  mhdiurno    varchar2(8) default ' ' not null,
  mhdispar    varchar2(46) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint mehdiaa1 primary key( 
dmhdiadm,
mhdidate)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index mehdiaa2 on mehdiaaf
(
mhdiurno,
dmhdiadm,
mhdidate
)
  tablespace pas_indx; 
