create table mehhonaf
(
  mhhnvisn    varchar2(8) default ' ' not null,
  mhhnuniq    varchar2(8) default ' ' not null,
  mhhnhoty    varchar2(3) default ' ' not null,
  mhhnactv    varchar2(1) default ' ' not null,
  mhhnsent    varchar2(1) default ' ' not null,
  mhhnhdat    varchar2(8) default ' ' not null,
  mhhnsset    varchar2(3) default ' ' not null,
  mhhnreas    varchar2(3) default ' ' not null,
  mhhnrhcp    varchar2(10) default ' ' not null,
  mhhncast    varchar2(10) default ' ' not null,
  mhhnphcp    varchar2(10) default ' ' not null,
  mhhnwebc    varchar2(10) default ' ' not null,
  mhhncdte    varchar2(8) default ' ' not null,
  mhhnctim    varchar2(8) default ' ' not null,
  mhhncomp    varchar2(1) default ' ' not null,
  mhhnwebf    varchar2(10) default ' ' not null,
  mhhndatf    varchar2(8) default ' ' not null,
  mhhntimf    varchar2(8) default ' ' not null,
  mhhnwebu    varchar2(10) default ' ' not null,
  mhhndatu    varchar2(8) default ' ' not null,
  mhhntimu    varchar2(8) default ' ' not null,
  mhhnfocu    varchar2(3) default ' ' not null,
  mhhnculs    varchar2(3) default ' ' not null,
  mhhnngos    varchar2(1) default ' ' not null,
  mhhnngoa    varchar2(1) default ' ' not null,
  mhhnngow    varchar2(1) default ' ' not null,
  mhhnvoca    varchar2(1) default ' ' not null,
  mhhnnsng    varchar2(1) default ' ' not null,
  mhhncols    varchar2(3) default ' ' not null,
  mhhnmoda    varchar2(3) default ' ' not null,
  mhhnadq1    varchar2(1) default ' ' not null,
  mhhnadq2    varchar2(1) default ' ' not null,
  mhhnadq3    varchar2(1) default ' ' not null,
  mhhnadq4    varchar2(1) default ' ' not null,
  mhhnadq5    varchar2(1) default ' ' not null,
  mhhnadq6    varchar2(1) default ' ' not null,
  mhhnadq7    varchar2(1) default ' ' not null,
  mhhnadq8    varchar2(1) default ' ' not null,
  mhhnaq8a    varchar2(1) default ' ' not null,
  mhhnfree    varchar2(35) default ' ' not null,
  mhhnadq9    varchar2(1) default ' ' not null,
  mhhnaq10    varchar2(1) default ' ' not null,
  mhhnaq11    varchar2(1) default ' ' not null,
  mhhnaq12    varchar2(1) default ' ' not null,
  mhhncyq1    varchar2(1) default ' ' not null,
  mhhncyq2    varchar2(1) default ' ' not null,
  mhhncyq3    varchar2(1) default ' ' not null,
  mhhncyq4    varchar2(1) default ' ' not null,
  mhhncyq5    varchar2(1) default ' ' not null,
  mhhncyq6    varchar2(1) default ' ' not null,
  mhhncyq7    varchar2(1) default ' ' not null,
  mhhncyq8    varchar2(1) default ' ' not null,
  mhhncyq9    varchar2(1) default ' ' not null,
  mhhncq10    varchar2(1) default ' ' not null,
  mhhncq11    varchar2(1) default ' ' not null,
  mhhncq12    varchar2(1) default ' ' not null,
  mhhncq13    varchar2(1) default ' ' not null,
  mhhncq14    varchar2(1) default ' ' not null,
  mhhncq15    varchar2(1) default ' ' not null,
  mhhnldq1    varchar2(1) default ' ' not null,
  mhhnldq2    varchar2(1) default ' ' not null,
  mhhnldq3    varchar2(1) default ' ' not null,
  mhhnldq4    varchar2(1) default ' ' not null,
  mhhnldq5    varchar2(1) default ' ' not null,
  mhhnldq6    varchar2(1) default ' ' not null,
  mhhnldq7    varchar2(1) default ' ' not null,
  mhhnldq8    varchar2(1) default ' ' not null,
  mhhnldq9    varchar2(1) default ' ' not null,
  mhhnlq10    varchar2(1) default ' ' not null,
  mhhnlq11    varchar2(1) default ' ' not null,
  mhhnlq12    varchar2(1) default ' ' not null,
  mhhnlq13    varchar2(1) default ' ' not null,
  mhhnlq14    varchar2(1) default ' ' not null,
  mhhnlq15    varchar2(1) default ' ' not null,
  mhhnlq16    varchar2(1) default ' ' not null,
  mhhnlq17    varchar2(1) default ' ' not null,
  mhhnlq18    varchar2(1) default ' ' not null,
  mhhnscq1    varchar2(1) default ' ' not null,
  mhhnscq2    varchar2(1) default ' ' not null,
  mhhnscq3    varchar2(1) default ' ' not null,
  mhhnscq4    varchar2(1) default ' ' not null,
  mhhnscq5    varchar2(1) default ' ' not null,
  mhhnscq6    varchar2(1) default ' ' not null,
  mhhnscq7    varchar2(1) default ' ' not null,
  mhhnhver    varchar2(3) default ' ' not null,
  mhhnld3a    varchar2(3) default ' ' not null,
  mhhnrdat    varchar2(8) default ' ' not null,
  mhhnrfmv    varchar2(2) default ' ' not null,
  mhhndays    varchar2(2) default ' ' not null,
  mhhnceps    varchar2(2) default ' ' not null,
  mhhnam01    varchar2(2) default ' ' not null,
  mhhnam02    varchar2(2) default ' ' not null,
  mhhnam03    varchar2(2) default ' ' not null,
  mhhnam04    varchar2(2) default ' ' not null,
  mhhnam05    varchar2(2) default ' ' not null,
  mhhnam06    varchar2(2) default ' ' not null,
  mhhnam7a    varchar2(2) default ' ' not null,
  mhhnam7b    varchar2(2) default ' ' not null,
  mhhnam7c    varchar2(2) default ' ' not null,
  mhhnam7d    varchar2(2) default ' ' not null,
  mhhnam7e    varchar2(2) default ' ' not null,
  mhhnam7f    varchar2(2) default ' ' not null,
  mhhnam08    varchar2(2) default ' ' not null,
  mhhnam9a    varchar2(1) default ' ' not null,
  mhhnam9b    varchar2(1) default ' ' not null,
  mhhnam9c    varchar2(1) default ' ' not null,
  mhhnam10    varchar2(2) default ' ' not null,
  mhhnam11    varchar2(1) default ' ' not null,
  mhhnam12    varchar2(2) default ' ' not null,
  mhhnam13    varchar2(2) default ' ' not null,
  mhhnam14    varchar2(2) default ' ' not null,
  mhhnam15    varchar2(2) default ' ' not null,
  mhhnam16    varchar2(2) default ' ' not null,
  mhhnam17    varchar2(2) default ' ' not null,
  mhhnam18    varchar2(2) default ' ' not null,
  mhhnam19    varchar2(2) default ' ' not null,
  mhhnam20    varchar2(2) default ' ' not null,
  mhhnurno    varchar2(8) default ' ' not null,
  mhhndelf    varchar2(1) default ' ' not null,
  mhhnduid    varchar2(10) default ' ' not null,
  mhhnddte    varchar2(8) default ' ' not null,
  mhhndtme    varchar2(8) default ' ' not null,
  mhhndres    varchar2(3) default ' ' not null,
  mhhnspar    varchar2(40) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint mehhona1 primary key( 
mhhnvisn,
mhhnuniq)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index mehhona2 on mehhonaf
(
mhhnrdat,
mhhnvisn,
mhhnuniq
)
  tablespace pas_indx; 
create unique index mehhona3 on mehhonaf
(
mhhnvisn,
mhhnhdat,
mhhnuniq
)
  tablespace pas_indx; 
create unique index mehhona4 on mehhonaf
(
mhhnurno,
mhhnvisn,
mhhnuniq
)
  tablespace pas_indx; 
