create table mehscraf
(
  mhscurno    varchar2(8) default ' ' not null,
  mhscsdat    varchar2(8) default ' ' not null,
  mhsccoun    varchar2(5) default ' ' not null,
  mhscuc01    varchar2(3) default ' ' not null,
  mhscuc02    varchar2(3) default ' ' not null,
  mhscuc03    varchar2(3) default ' ' not null,
  mhscuc04    varchar2(3) default ' ' not null,
  mhscuc05    varchar2(3) default ' ' not null,
  mhscuc06    varchar2(3) default ' ' not null,
  mhscuc07    varchar2(3) default ' ' not null,
  mhscuc08    varchar2(3) default ' ' not null,
  mhscuc09    varchar2(3) default ' ' not null,
  mhscuc10    varchar2(3) default ' ' not null,
  mhscuc11    varchar2(3) default ' ' not null,
  mhscuc12    varchar2(3) default ' ' not null,
  mhscuc13    varchar2(3) default ' ' not null,
  mhscuc14    varchar2(3) default ' ' not null,
  mhscuc15    varchar2(3) default ' ' not null,
  mhscudt1    varchar2(8) default ' ' not null,
  mhscutm1    varchar2(8) default ' ' not null,
  mhscudt2    varchar2(8) default ' ' not null,
  mhscutm2    varchar2(8) default ' ' not null,
  mhscudt3    varchar2(8) default ' ' not null,
  mhscutm3    varchar2(8) default ' ' not null,
  mhscudt4    varchar2(8) default ' ' not null,
  mhscutm4    varchar2(8) default ' ' not null,
  mhscudt5    varchar2(8) default ' ' not null,
  mhscutm5    varchar2(8) default ' ' not null,
  mhscudt6    varchar2(8) default ' ' not null,
  mhscutm6    varchar2(8) default ' ' not null,
  mhscudt7    varchar2(8) default ' ' not null,
  mhscutm7    varchar2(8) default ' ' not null,
  mhscudt8    varchar2(8) default ' ' not null,
  mhscutm8    varchar2(8) default ' ' not null,
  mhscudt9    varchar2(8) default ' ' not null,
  mhscutm9    varchar2(8) default ' ' not null,
  mhscuhc1    varchar2(10) default ' ' not null,
  mhscuhc2    varchar2(10) default ' ' not null,
  mhscuhc3    varchar2(10) default ' ' not null,
  mhscuhc4    varchar2(10) default ' ' not null,
  mhscuhc5    varchar2(10) default ' ' not null,
  mhscuhc6    varchar2(10) default ' ' not null,
  mhscuhc7    varchar2(10) default ' ' not null,
  mhscuhc8    varchar2(10) default ' ' not null,
  mhscuhc9    varchar2(10) default ' ' not null,
  mhscuyn1    varchar2(1) default ' ' not null,
  mhscuyn2    varchar2(1) default ' ' not null,
  mhscuyn3    varchar2(1) default ' ' not null,
  mhscuyn4    varchar2(1) default ' ' not null,
  mhscuyn5    varchar2(1) default ' ' not null,
  mhscuyn6    varchar2(1) default ' ' not null,
  mhscuyn7    varchar2(1) default ' ' not null,
  mhscuyn8    varchar2(1) default ' ' not null,
  mhscuyn9    varchar2(1) default ' ' not null,
  mhscuff1    varchar2(60) default ' ' not null,
  mhscuff2    varchar2(60) default ' ' not null,
  mhscuff3    varchar2(60) default ' ' not null,
  mhscuff4    varchar2(60) default ' ' not null,
  mhscuff5    varchar2(60) default ' ' not null,
  mhsccdat    varchar2(8) default ' ' not null,
  mhscctim    varchar2(8) default ' ' not null,
  mhsccuid    varchar2(10) default ' ' not null,
  mhscudat    varchar2(8) default ' ' not null,
  mhscutim    varchar2(8) default ' ' not null,
  mhscuuid    varchar2(10) default ' ' not null,
  mhscstat    varchar2(1) default ' ' not null,
  mhscspar    varchar2(100) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint mehscra1 primary key( 
mhscurno,
mhscsdat)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
