create table obsdetaf
(
  obdevist    varchar2(8) default ' ' not null,
  obdedate    varchar2(8) default ' ' not null,
  obdetime    varchar2(8) default ' ' not null,
  obdetyp     varchar2(3) default ' ' not null,
  obdepuls    number(3,0) default 0 not null,
  obdetemp    number(4,1) default 0 not null,
  obdebpsy    number(3,0) default 0 not null,
  obdebpdi    number(3,0) default 0 not null,
  obderesp    number(3,0) default 0 not null,
  obdepox     number(3,0) default 0 not null,
  obdeo2f     number(3,0) default 0 not null,
  obdepfl     number(4,0) default 0 not null,
  obdefoc     varchar2(3) default ' ' not null,
  obdefic     varchar2(3) default ' ' not null,
  obdefot     number(6,0) default 0 not null,
  obdefin     number(6,0) default 0 not null,
  obdeeyeo    varchar2(1) default ' ' not null,
  obdeverb    varchar2(1) default ' ' not null,
  obdemoto    varchar2(1) default ' ' not null,
  obdepsl     varchar2(1) default ' ' not null,
  obdepsr     varchar2(1) default ' ' not null,
  obdeprl     varchar2(1) default ' ' not null,
  obdeprr     varchar2(1) default ' ' not null,
  obdelmla    varchar2(1) default ' ' not null,
  obdelmrm    varchar2(1) default ' ' not null,
  obdelmll    varchar2(1) default ' ' not null,
  obdelmrl    varchar2(1) default ' ' not null,
  obdeact     varchar2(3) default ' ' not null,
  obdeuy1     varchar2(1) default ' ' not null,
  obdeuy2     varchar2(1) default ' ' not null,
  obdeuy3     varchar2(1) default ' ' not null,
  obdeuy4     varchar2(1) default ' ' not null,
  obdeuc1     varchar2(3) default ' ' not null,
  obdeuc2     varchar2(3) default ' ' not null,
  obdeun1     number(8,2) default 0 not null,
  obdeun2     number(8,2) default 0 not null,
  obdeun3     number(8,2) default 0 not null,
  obdeun4     number(8,2) default 0 not null,
  obdeuid     varchar2(10) default ' ' not null,
  obdemdat    varchar2(8) default ' ' not null,
  obdemtim    varchar2(8) default ' ' not null,
  obdecom1    varchar2(40) default ' ' not null,
  obdecom2    varchar2(40) default ' ' not null,
  obdecom3    varchar2(40) default ' ' not null,
  obdepnsc    varchar2(2) default ' ' not null,
  obdecvps    varchar2(1) default ' ' not null,
  obdespa     varchar2(17) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint obsdeta1 primary key( 
obdevist,
obdedate,
obdetime)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
