create table opratraf
(
  opabuniq    varchar2(10) default ' ' not null,
  opabtype    varchar2(3) default ' ' not null,
  opabval1    varchar2(6) default ' ' not null,
  opabval2    varchar2(6) default ' ' not null,
  opabval3    varchar2(6) default ' ' not null,
  opabval4    varchar2(6) default ' ' not null,
  opabcod1    varchar2(3) default ' ' not null,
  opabcod2    varchar2(3) default ' ' not null,
  opabcod3    varchar2(3) default ' ' not null,
  opabcod4    varchar2(3) default ' ' not null,
  opabtxt1    varchar2(80) default ' ' not null,
  opabtxt2    varchar2(80) default ' ' not null,
  opabtxt3    varchar2(80) default ' ' not null,
  opabtxt4    varchar2(80) default ' ' not null,
  opabyn01    varchar2(1) default ' ' not null,
  opabyn02    varchar2(1) default ' ' not null,
  opabyn03    varchar2(1) default ' ' not null,
  opabyn04    varchar2(1) default ' ' not null,
  opabdelt    varchar2(1) default ' ' not null,
  opabcuid    varchar2(10) default ' ' not null,
  opabcdat    varchar2(8) default ' ' not null,
  opabctim    varchar2(8) default ' ' not null,
  opabuuid    varchar2(10) default ' ' not null,
  opabudat    varchar2(8) default ' ' not null,
  opabutim    varchar2(8) default ' ' not null,
  opabfuid    varchar2(10) default ' ' not null,
  opabfdat    varchar2(8) default ' ' not null,
  opabftim    varchar2(8) default ' ' not null,
  opabcod5    varchar2(3) default ' ' not null,
  opabcod6    varchar2(3) default ' ' not null,
  opabyn05    varchar2(1) default ' ' not null,
  opabyn06    varchar2(1) default ' ' not null,
  opabyn07    varchar2(1) default ' ' not null,
  opabyn08    varchar2(1) default ' ' not null,
  opabyn09    varchar2(1) default ' ' not null,
  opabyn10    varchar2(1) default ' ' not null,
  opabudd1    varchar2(8) default ' ' not null,
  opabudt1    varchar2(8) default ' ' not null,
  opabspar    varchar2(42) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint opratra1 primary key( 
opabuniq,
opabtype)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
