create table opraudar
(
  oparaudd    varchar2(8) default ' ' not null,
  oparaudt    varchar2(8) default ' ' not null,
  oparaudp    varchar2(2) default ' ' not null,
  oparaudr    varchar2(1) default ' ' not null,
  oparauds    number(1,0) default 0 not null,
  oparaudo    varchar2(4) default ' ' not null,
  oparunid    varchar2(10) default ' ' not null,
  oparatim    varchar2(8) default ' ' not null,
  oparanur    varchar2(6) default ' ' not null,
  oparrlat    varchar2(3) default ' ' not null,
  oparpclc    varchar2(1) default ' ' not null,
  oparcsfs    varchar2(1) default ' ' not null,
  oparmdre    varchar2(1) default ' ' not null,
  oparxray    varchar2(1) default ' ' not null,
  oparblem    varchar2(1) default ' ' not null,
  oparmupj    varchar2(1) default ' ' not null,
  oparpmed    varchar2(1) default ' ' not null,
  oparalck    varchar2(1) default ' ' not null,
  oparprot    varchar2(40) default ' ' not null,
  oparuc01    varchar2(3) default ' ' not null,
  oparuc02    varchar2(3) default ' ' not null,
  oparuc03    varchar2(3) default ' ' not null,
  oparuc04    varchar2(3) default ' ' not null,
  oparuc05    varchar2(3) default ' ' not null,
  oparuc06    varchar2(3) default ' ' not null,
  oparuc07    varchar2(3) default ' ' not null,
  oparuc08    varchar2(3) default ' ' not null,
  oparuc09    varchar2(3) default ' ' not null,
  oparuc10    varchar2(3) default ' ' not null,
  oparuy01    varchar2(1) default ' ' not null,
  oparuy02    varchar2(1) default ' ' not null,
  oparuy03    varchar2(1) default ' ' not null,
  oparuy04    varchar2(1) default ' ' not null,
  oparuy05    varchar2(1) default ' ' not null,
  oparut01    varchar2(8) default ' ' not null,
  oparut02    varchar2(8) default ' ' not null,
  oparut03    varchar2(8) default ' ' not null,
  oparut04    varchar2(8) default ' ' not null,
  oparut05    varchar2(8) default ' ' not null,
  oparuf01    number(6,0) default 0 not null,
  oparuf02    number(6,0) default 0 not null,
  oparuf03    number(6,0) default 0 not null,
  oparuf04    number(6,0) default 0 not null,
  oparuf05    number(6,0) default 0 not null,
  opartcal    varchar2(8) default ' ' not null,
  oparuiar    varchar2(10) default ' ' not null,
  oparanap    varchar2(8) default ' ' not null,
  oparanas    varchar2(8) default ' ' not null,
  oparanae    varchar2(8) default ' ' not null,
  oparityp    varchar2(3) default ' ' not null,
  oparuc11    varchar2(3) default ' ' not null,
  oparuc12    varchar2(3) default ' ' not null,
  oparuc13    varchar2(3) default ' ' not null,
  oparuc14    varchar2(3) default ' ' not null,
  oparuc15    varchar2(3) default ' ' not null,
  oparuc16    varchar2(3) default ' ' not null,
  oparuc17    varchar2(3) default ' ' not null,
  oparuc18    varchar2(3) default ' ' not null,
  oparuc19    varchar2(3) default ' ' not null,
  oparuc20    varchar2(3) default ' ' not null,
  oparuy06    varchar2(1) default ' ' not null,
  oparuy07    varchar2(1) default ' ' not null,
  oparuy08    varchar2(1) default ' ' not null,
  oparuy09    varchar2(1) default ' ' not null,
  oparuy10    varchar2(1) default ' ' not null,
  oparut06    varchar2(8) default ' ' not null,
  oparut07    varchar2(8) default ' ' not null,
  oparut08    varchar2(8) default ' ' not null,
  oparut09    varchar2(8) default ' ' not null,
  oparut10    varchar2(8) default ' ' not null,
  oparuf06    number(6,0) default 0 not null,
  oparuf07    number(6,0) default 0 not null,
  oparuf08    number(6,0) default 0 not null,
  oparuf09    number(6,0) default 0 not null,
  oparuf10    number(6,0) default 0 not null,
  oparuana    varchar2(10) default ' ' not null,
  opartirf    varchar2(8) default ' ' not null,
  oparnuf1    varchar2(6) default ' ' not null,
  oparnuf2    varchar2(6) default ' ' not null,
  opartirb    varchar2(8) default ' ' not null,
  oparnub1    varchar2(6) default ' ' not null,
  oparnub2    varchar2(6) default ' ' not null,
  opartird    varchar2(8) default ' ' not null,
  oparnud1    varchar2(6) default ' ' not null,
  oparnud2    varchar2(6) default ' ' not null,
  opartetc    varchar2(8) default ' ' not null,
  oparurec    varchar2(10) default ' ' not null,
  opartexp    varchar2(8) default ' ' not null,
  oparticu    varchar2(8) default ' ' not null,
  oparrdcd    varchar2(3) default ' ' not null,
  opartidp    varchar2(8) default ' ' not null,
  oparuc21    varchar2(3) default ' ' not null,
  oparuc22    varchar2(3) default ' ' not null,
  oparuc23    varchar2(3) default ' ' not null,
  oparuc24    varchar2(3) default ' ' not null,
  oparuc25    varchar2(3) default ' ' not null,
  oparuc26    varchar2(3) default ' ' not null,
  oparuc27    varchar2(3) default ' ' not null,
  oparuc28    varchar2(3) default ' ' not null,
  oparuc29    varchar2(3) default ' ' not null,
  oparuc30    varchar2(3) default ' ' not null,
  oparuy11    varchar2(1) default ' ' not null,
  oparuy12    varchar2(1) default ' ' not null,
  oparuy13    varchar2(1) default ' ' not null,
  oparuy14    varchar2(1) default ' ' not null,
  oparuy15    varchar2(1) default ' ' not null,
  oparut11    varchar2(8) default ' ' not null,
  oparut12    varchar2(8) default ' ' not null,
  oparut13    varchar2(8) default ' ' not null,
  oparut14    varchar2(8) default ' ' not null,
  oparut15    varchar2(8) default ' ' not null,
  oparuf11    number(6,0) default 0 not null,
  oparuf12    number(6,0) default 0 not null,
  oparuf13    number(6,0) default 0 not null,
  oparuf14    number(6,0) default 0 not null,
  oparuf15    number(6,0) default 0 not null,
  oparuyn1    varchar2(10) default ' ' not null,
  oparuyn2    varchar2(10) default ' ' not null,
  oparadst    varchar2(8) default ' ' not null,
  oparadet    varchar2(8) default ' ' not null,
  oparut16    varchar2(8) default ' ' not null,
  oparut17    varchar2(8) default ' ' not null,
  oparut18    varchar2(8) default ' ' not null,
  oparut19    varchar2(8) default ' ' not null,
  oparspar    varchar2(50) default ' ' not null,
  lf          varchar2(1) default ' ' not null
)
tablespace pas_data; 
create index opraudar on opraudar
(
oparaudd,
oparaudt,
oparaudp,
oparaudr
)
tablespace pas_indx; 
create table oprardaf
(
  oparunid    varchar2(10) default ' ' not null,
  oparatim    varchar2(8) default ' ' not null,
  oparanur    varchar2(6) default ' ' not null,
  oparrlat    varchar2(3) default ' ' not null,
  oparpclc    varchar2(1) default ' ' not null,
  oparcsfs    varchar2(1) default ' ' not null,
  oparmdre    varchar2(1) default ' ' not null,
  oparxray    varchar2(1) default ' ' not null,
  oparblem    varchar2(1) default ' ' not null,
  oparmupj    varchar2(1) default ' ' not null,
  oparpmed    varchar2(1) default ' ' not null,
  oparalck    varchar2(1) default ' ' not null,
  oparprot    varchar2(40) default ' ' not null,
  oparuc01    varchar2(3) default ' ' not null,
  oparuc02    varchar2(3) default ' ' not null,
  oparuc03    varchar2(3) default ' ' not null,
  oparuc04    varchar2(3) default ' ' not null,
  oparuc05    varchar2(3) default ' ' not null,
  oparuc06    varchar2(3) default ' ' not null,
  oparuc07    varchar2(3) default ' ' not null,
  oparuc08    varchar2(3) default ' ' not null,
  oparuc09    varchar2(3) default ' ' not null,
  oparuc10    varchar2(3) default ' ' not null,
  oparuy01    varchar2(1) default ' ' not null,
  oparuy02    varchar2(1) default ' ' not null,
  oparuy03    varchar2(1) default ' ' not null,
  oparuy04    varchar2(1) default ' ' not null,
  oparuy05    varchar2(1) default ' ' not null,
  oparut01    varchar2(8) default ' ' not null,
  oparut02    varchar2(8) default ' ' not null,
  oparut03    varchar2(8) default ' ' not null,
  oparut04    varchar2(8) default ' ' not null,
  oparut05    varchar2(8) default ' ' not null,
  oparuf01    number(6,0) default 0 not null,
  oparuf02    number(6,0) default 0 not null,
  oparuf03    number(6,0) default 0 not null,
  oparuf04    number(6,0) default 0 not null,
  oparuf05    number(6,0) default 0 not null,
  opartcal    varchar2(8) default ' ' not null,
  oparuiar    varchar2(10) default ' ' not null,
  oparanap    varchar2(8) default ' ' not null,
  oparanas    varchar2(8) default ' ' not null,
  oparanae    varchar2(8) default ' ' not null,
  oparityp    varchar2(3) default ' ' not null,
  oparuc11    varchar2(3) default ' ' not null,
  oparuc12    varchar2(3) default ' ' not null,
  oparuc13    varchar2(3) default ' ' not null,
  oparuc14    varchar2(3) default ' ' not null,
  oparuc15    varchar2(3) default ' ' not null,
  oparuc16    varchar2(3) default ' ' not null,
  oparuc17    varchar2(3) default ' ' not null,
  oparuc18    varchar2(3) default ' ' not null,
  oparuc19    varchar2(3) default ' ' not null,
  oparuc20    varchar2(3) default ' ' not null,
  oparuy06    varchar2(1) default ' ' not null,
  oparuy07    varchar2(1) default ' ' not null,
  oparuy08    varchar2(1) default ' ' not null,
  oparuy09    varchar2(1) default ' ' not null,
  oparuy10    varchar2(1) default ' ' not null,
  oparut06    varchar2(8) default ' ' not null,
  oparut07    varchar2(8) default ' ' not null,
  oparut08    varchar2(8) default ' ' not null,
  oparut09    varchar2(8) default ' ' not null,
  oparut10    varchar2(8) default ' ' not null,
  oparuf06    number(6,0) default 0 not null,
  oparuf07    number(6,0) default 0 not null,
  oparuf08    number(6,0) default 0 not null,
  oparuf09    number(6,0) default 0 not null,
  oparuf10    number(6,0) default 0 not null,
  oparuana    varchar2(10) default ' ' not null,
  opartirf    varchar2(8) default ' ' not null,
  oparnuf1    varchar2(6) default ' ' not null,
  oparnuf2    varchar2(6) default ' ' not null,
  opartirb    varchar2(8) default ' ' not null,
  oparnub1    varchar2(6) default ' ' not null,
  oparnub2    varchar2(6) default ' ' not null,
  opartird    varchar2(8) default ' ' not null,
  oparnud1    varchar2(6) default ' ' not null,
  oparnud2    varchar2(6) default ' ' not null,
  opartetc    varchar2(8) default ' ' not null,
  oparurec    varchar2(10) default ' ' not null,
  opartexp    varchar2(8) default ' ' not null,
  oparticu    varchar2(8) default ' ' not null,
  oparrdcd    varchar2(3) default ' ' not null,
  opartidp    varchar2(8) default ' ' not null,
  oparuc21    varchar2(3) default ' ' not null,
  oparuc22    varchar2(3) default ' ' not null,
  oparuc23    varchar2(3) default ' ' not null,
  oparuc24    varchar2(3) default ' ' not null,
  oparuc25    varchar2(3) default ' ' not null,
  oparuc26    varchar2(3) default ' ' not null,
  oparuc27    varchar2(3) default ' ' not null,
  oparuc28    varchar2(3) default ' ' not null,
  oparuc29    varchar2(3) default ' ' not null,
  oparuc30    varchar2(3) default ' ' not null,
  oparuy11    varchar2(1) default ' ' not null,
  oparuy12    varchar2(1) default ' ' not null,
  oparuy13    varchar2(1) default ' ' not null,
  oparuy14    varchar2(1) default ' ' not null,
  oparuy15    varchar2(1) default ' ' not null,
  oparut11    varchar2(8) default ' ' not null,
  oparut12    varchar2(8) default ' ' not null,
  oparut13    varchar2(8) default ' ' not null,
  oparut14    varchar2(8) default ' ' not null,
  oparut15    varchar2(8) default ' ' not null,
  oparuf11    number(6,0) default 0 not null,
  oparuf12    number(6,0) default 0 not null,
  oparuf13    number(6,0) default 0 not null,
  oparuf14    number(6,0) default 0 not null,
  oparuf15    number(6,0) default 0 not null,
  oparuyn1    varchar2(10) default ' ' not null,
  oparuyn2    varchar2(10) default ' ' not null,
  oparadst    varchar2(8) default ' ' not null,
  oparadet    varchar2(8) default ' ' not null,
  oparut16    varchar2(8) default ' ' not null,
  oparut17    varchar2(8) default ' ' not null,
  oparut18    varchar2(8) default ' ' not null,
  oparut19    varchar2(8) default ' ' not null,
  oparspar    varchar2(50) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint oprarda1 primary key( 
oparunid)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
