create table opraaeaf
(
  opaadate    varchar2(8) default ' ' not null,
  opaatime    varchar2(5) default ' ' not null,
  opaaclin    varchar2(6) default ' ' not null,
  opaacase    varchar2(3) default ' ' not null,
  opaaadmn    varchar2(8) default ' ' not null,
  opaageur    varchar2(1) default ' ' not null,
  opaageac    varchar2(1) default ' ' not null,
  opaagep1    varchar2(1) default ' ' not null,
  opaagep2    varchar2(1) default ' ' not null,
  opaapmra    varchar2(1) default ' ' not null,
  opaapmp1    varchar2(2) default ' ' not null,
  opaapmp2    varchar2(2) default ' ' not null,
  opaarfps    varchar2(1) default ' ' not null,
  opaarfta    varchar2(1) default ' ' not null,
  opaarfbr    varchar2(1) default ' ' not null,
  opaarfrd    varchar2(1) default ' ' not null,
  opaarfla    varchar2(1) default ' ' not null,
  opaarfbo    varchar2(1) default ' ' not null,
  opaarfas    varchar2(1) default ' ' not null,
  opaarfvb    varchar2(1) default ' ' not null,
  opaarfre    varchar2(1) default ' ' not null,
  opaarfrc    varchar2(1) default ' ' not null,
  opaaccia    varchar2(1) default ' ' not null,
  opaacccp    varchar2(1) default ' ' not null,
  opaaccec    varchar2(1) default ' ' not null,
  opaaccna    varchar2(1) default ' ' not null,
  opaacchp    varchar2(1) default ' ' not null,
  opaacchr    varchar2(1) default ' ' not null,
  opaaccbr    varchar2(1) default ' ' not null,
  opaaccta    varchar2(1) default ' ' not null,
  opaabtb1    varchar2(1) default ' ' not null,
  opaabtb2    varchar2(1) default ' ' not null,
  opaabtb3    varchar2(1) default ' ' not null,
  opaaorde    varchar2(1) default ' ' not null,
  opaaordt    varchar2(1) default ' ' not null,
  opaaoran    varchar2(1) default ' ' not null,
  opaaorse    varchar2(1) default ' ' not null,
  opaaorun    varchar2(1) default ' ' not null,
  opaaorir    varchar2(1) default ' ' not null,
  opaaornb    varchar2(1) default ' ' not null,
  opaaorst    varchar2(1) default ' ' not null,
  opaadiin    varchar2(1) default ' ' not null,
  opaaadve    varchar2(1) default ' ' not null,
  opaadidt    varchar2(300) default ' ' not null,
  opaaotfd    varchar2(50) default ' ' not null,
  opaaotf1    varchar2(50) default ' ' not null,
  opaaotf2    varchar2(50) default ' ' not null,
  opaaotf3    varchar2(50) default ' ' not null,
  opaaotf4    varchar2(50) default ' ' not null,
  opaaotf5    varchar2(50) default ' ' not null,
  opaarfde    varchar2(1) default ' ' not null,
  opaaspar    varchar2(81) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint opraae11 primary key( 
opaadate,
opaatime,
opaaclin,
opaacase,
opaaadmn)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
