create table opraudda
(
  opdaaudd    varchar2(8) default ' ' not null,
  opdaaudt    varchar2(8) default ' ' not null,
  opdaaudp    varchar2(2) default ' ' not null,
  opdaaudr    varchar2(1) default ' ' not null,
  opdaauds    number(1,0) default 0 not null,
  opdaaudo    varchar2(4) default ' ' not null,
  opdadate    varchar2(8) default ' ' not null,
  opdatime    varchar2(5) default ' ' not null,
  opdaclin    varchar2(6) default ' ' not null,
  dopdasta    varchar2(1) default ' ' not null,
  opdacase    varchar2(3) default ' ' not null,
  opdaadmn    varchar2(8) default ' ' not null,
  opdauniq    varchar2(10) default ' ' not null,
  opdaexps    varchar2(5) default ' ' not null,
  opdaexpd    number(4,0) default 0 not null,
  opdaanae    varchar2(3) default ' ' not null,
  opdatype    varchar2(3) default ' ' not null,
  opdatran    varchar2(3) default ' ' not null,
  opdausr1    varchar2(3) default ' ' not null,
  opdausr2    varchar2(3) default ' ' not null,
  opdausr3    varchar2(3) default ' ' not null,
  opdausr4    varchar2(3) default ' ' not null,
  opdawait    varchar2(1) default ' ' not null,
  opdaprov    varchar2(9) default ' ' not null,
  opdaprv2    varchar2(9) default ' ' not null,
  opdaprv3    varchar2(9) default ' ' not null,
  opdades1    varchar2(80) default ' ' not null,
  opdades2    varchar2(80) default ' ' not null,
  opdades3    varchar2(80) default ' ' not null,
  opdacomm    varchar2(40) default ' ' not null,
  opdacanc    varchar2(3) default ' ' not null,
  opdathet    varchar2(6) default ' ' not null,
  opdapre1    varchar2(5) default ' ' not null,
  opdapre2    varchar2(5) default ' ' not null,
  opdapre3    varchar2(5) default ' ' not null,
  opdapre4    varchar2(5) default ' ' not null,
  opdapre5    varchar2(5) default ' ' not null,
  opdapos1    varchar2(5) default ' ' not null,
  opdapos2    varchar2(5) default ' ' not null,
  opdapos3    varchar2(5) default ' ' not null,
  opdapos4    varchar2(5) default ' ' not null,
  opdatdur    number(4,0) default 0 not null,
  opdaknow    varchar2(3) default ' ' not null,
  opdacdat    varchar2(8) default ' ' not null,
  opdaeqr1    varchar2(3) default ' ' not null,
  opdaeqr2    varchar2(3) default ' ' not null,
  opdaleqr    varchar2(3) default ' ' not null,
  opdaeqr3    varchar2(3) default ' ' not null,
  opdaunit    varchar2(3) default ' ' not null,
  opdaurno    varchar2(8) default ' ' not null,
  opdaproc    varchar2(9) default ' ' not null,
  opdacont    varchar2(2) default ' ' not null,
  opdaasrc    varchar2(3) default ' ' not null,
  opdacsst    varchar2(1) default ' ' not null,
  opdacsdt    varchar2(8) default ' ' not null,
  opdacrdt    varchar2(8) default ' ' not null,
  opdactim    varchar2(8) default ' ' not null,
  opdawebc    varchar2(10) default ' ' not null,
  opdaudat    varchar2(8) default ' ' not null,
  opdautim    varchar2(8) default ' ' not null,
  opdawebu    varchar2(10) default ' ' not null,
  opdapcom    varchar2(1) default ' ' not null,
  opdavun1    varchar2(10) default ' ' not null,
  opdavun2    varchar2(10) default ' ' not null,
  opdaphmn    varchar2(10) default ' ' not null,
  opdareqn    varchar2(10) default ' ' not null,
  opdades4    varchar2(80) default ' ' not null,
  opdades5    varchar2(80) default ' ' not null,
  opdades6    varchar2(80) default ' ' not null,
  opdafast    varchar2(8) default ' ' not null,
  opdaaprc    varchar2(1) default ' ' not null,
  opdaacpd    varchar2(1) default ' ' not null,
  opdaricm    varchar2(3) default ' ' not null,
  opdamhrc    varchar2(1) default ' ' not null,
  opdapowd    varchar2(3) default ' ' not null,
  opdapobd    varchar2(3) default ' ' not null,
  opdactyp    varchar2(3) default ' ' not null,
  opdaatyp    varchar2(3) default ' ' not null,
  opdadtff    varchar2(8) default ' ' not null,
  opdadtfl    varchar2(8) default ' ' not null,
  opdaprv4    varchar2(9) default ' ' not null,
  opdaprv5    varchar2(9) default ' ' not null,
  opdaprv6    varchar2(9) default ' ' not null,
  opdahosp    varchar2(3) default ' ' not null,
  opdaspar    varchar2(47) default ' ' not null,
  lf          varchar2(1) default ' ' not null
)
tablespace pas_data; 
create index opraudda on opraudda
(
opdaaudd,
opdaaudt,
opdaaudp,
opdaaudr
)
tablespace pas_indx; 
create table oprdetaf
(
  opdadate    varchar2(8) default ' ' not null,
  opdatime    varchar2(5) default ' ' not null,
  opdaclin    varchar2(6) default ' ' not null,
  dopdasta    varchar2(1) default ' ' not null,
  opdacase    varchar2(3) default ' ' not null,
  opdaadmn    varchar2(8) default ' ' not null,
  opdauniq    varchar2(10) default ' ' not null,
  opdaexps    varchar2(5) default ' ' not null,
  opdaexpd    number(4,0) default 0 not null,
  opdaanae    varchar2(3) default ' ' not null,
  opdatype    varchar2(3) default ' ' not null,
  opdatran    varchar2(3) default ' ' not null,
  opdausr1    varchar2(3) default ' ' not null,
  opdausr2    varchar2(3) default ' ' not null,
  opdausr3    varchar2(3) default ' ' not null,
  opdausr4    varchar2(3) default ' ' not null,
  opdawait    varchar2(1) default ' ' not null,
  opdaprov    varchar2(9) default ' ' not null,
  opdaprv2    varchar2(9) default ' ' not null,
  opdaprv3    varchar2(9) default ' ' not null,
  opdades1    varchar2(80) default ' ' not null,
  opdades2    varchar2(80) default ' ' not null,
  opdades3    varchar2(80) default ' ' not null,
  opdacomm    varchar2(40) default ' ' not null,
  opdacanc    varchar2(3) default ' ' not null,
  opdathet    varchar2(6) default ' ' not null,
  opdapre1    varchar2(5) default ' ' not null,
  opdapre2    varchar2(5) default ' ' not null,
  opdapre3    varchar2(5) default ' ' not null,
  opdapre4    varchar2(5) default ' ' not null,
  opdapre5    varchar2(5) default ' ' not null,
  opdapos1    varchar2(5) default ' ' not null,
  opdapos2    varchar2(5) default ' ' not null,
  opdapos3    varchar2(5) default ' ' not null,
  opdapos4    varchar2(5) default ' ' not null,
  opdatdur    number(4,0) default 0 not null,
  opdaknow    varchar2(3) default ' ' not null,
  opdacdat    varchar2(8) default ' ' not null,
  opdaeqr1    varchar2(3) default ' ' not null,
  opdaeqr2    varchar2(3) default ' ' not null,
  opdaleqr    varchar2(3) default ' ' not null,
  opdaeqr3    varchar2(3) default ' ' not null,
  opdaunit    varchar2(3) default ' ' not null,
  opdaurno    varchar2(8) default ' ' not null,
  opdaproc    varchar2(9) default ' ' not null,
  opdacont    varchar2(2) default ' ' not null,
  opdaasrc    varchar2(3) default ' ' not null,
  opdacsst    varchar2(1) default ' ' not null,
  opdacsdt    varchar2(8) default ' ' not null,
  opdacrdt    varchar2(8) default ' ' not null,
  opdactim    varchar2(8) default ' ' not null,
  opdawebc    varchar2(10) default ' ' not null,
  opdaudat    varchar2(8) default ' ' not null,
  opdautim    varchar2(8) default ' ' not null,
  opdawebu    varchar2(10) default ' ' not null,
  opdapcom    varchar2(1) default ' ' not null,
  opdavun1    varchar2(10) default ' ' not null,
  opdavun2    varchar2(10) default ' ' not null,
  opdaphmn    varchar2(10) default ' ' not null,
  opdareqn    varchar2(10) default ' ' not null,
  opdades4    varchar2(80) default ' ' not null,
  opdades5    varchar2(80) default ' ' not null,
  opdades6    varchar2(80) default ' ' not null,
  opdafast    varchar2(8) default ' ' not null,
  opdaaprc    varchar2(1) default ' ' not null,
  opdaacpd    varchar2(1) default ' ' not null,
  opdaricm    varchar2(3) default ' ' not null,
  opdamhrc    varchar2(1) default ' ' not null,
  opdapowd    varchar2(3) default ' ' not null,
  opdapobd    varchar2(3) default ' ' not null,
  opdactyp    varchar2(3) default ' ' not null,
  opdaatyp    varchar2(3) default ' ' not null,
  opdadtff    varchar2(8) default ' ' not null,
  opdadtfl    varchar2(8) default ' ' not null,
  opdaprv4    varchar2(9) default ' ' not null,
  opdaprv5    varchar2(9) default ' ' not null,
  opdaprv6    varchar2(9) default ' ' not null,
  opdahosp    varchar2(3) default ' ' not null,
  opdaspar    varchar2(47) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint oprdeta1 primary key( 
opdahosp,
opdadate,
opdatime,
opdaclin,
dopdasta,
opdacase)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index oprdeta2 on oprdetaf
(
opdaadmn,
dopdasta,
opdadate,
opdatime,
opdaclin,
opdacase
)
  tablespace pas_indx; 
create unique index oprdeta3 on oprdetaf
(
opdauniq
)
  tablespace pas_indx; 
create unique index oprdeta4 on oprdetaf
(
opdaurno,
opdaproc,
opdacont,
opdauniq
)
  tablespace pas_indx; 
create unique index oprdeta5 on oprdetaf
(
opdahosp,
opdadate,
opdatime,
opdaclin,
opdacase,
dopdasta
)
  tablespace pas_indx; 
create unique index oprdeta6 on oprdetaf
(
opdadate,
opdatime,
opdaclin,
opdacase,
dopdasta,
opdahosp
)
  tablespace pas_indx; 
