create table oprauddc
(
  opdcaudd    varchar2(8) default ' ' not null,
  opdcaudt    varchar2(8) default ' ' not null,
  opdcaudp    varchar2(2) default ' ' not null,
  opdcaudr    varchar2(1) default ' ' not null,
  opdcauds    number(1,0) default 0 not null,
  opdcaudo    varchar2(4) default ' ' not null,
  opdcuniq    varchar2(10) default ' ' not null,
  opdcteam    varchar2(1) default ' ' not null,
  opdcotm1    varchar2(5) default ' ' not null,
  opdcotm2    varchar2(5) default ' ' not null,
  opdcotm3    varchar2(5) default ' ' not null,
  opdcotm4    varchar2(5) default ' ' not null,
  opdcicd1    varchar2(9) default ' ' not null,
  opdcicd2    varchar2(9) default ' ' not null,
  opdcicd3    varchar2(9) default ' ' not null,
  opdcicd4    varchar2(9) default ' ' not null,
  opdcicd5    varchar2(9) default ' ' not null,
  opdcicd6    varchar2(9) default ' ' not null,
  opdccont    varchar2(1) default ' ' not null,
  opdcdura    number(4,0) default 0 not null,
  opdcnoop    number(3,0) default 0 not null,
  opdcimc1    varchar2(6) default ' ' not null,
  opdcimc2    varchar2(6) default ' ' not null,
  opdcimc3    varchar2(6) default ' ' not null,
  opdcimc4    varchar2(6) default ' ' not null,
  opdcimc5    varchar2(6) default ' ' not null,
  opdcimc6    varchar2(6) default ' ' not null,
  opdcimc7    varchar2(6) default ' ' not null,
  opdcimc8    varchar2(6) default ' ' not null,
  opdcimc9    varchar2(6) default ' ' not null,
  opdcim10    varchar2(6) default ' ' not null,
  opdcimq1    number(3,0) default 0 not null,
  opdcimq2    number(3,0) default 0 not null,
  opdcimq3    number(3,0) default 0 not null,
  opdcimq4    number(3,0) default 0 not null,
  opdcimq5    number(3,0) default 0 not null,
  opdcimq6    number(3,0) default 0 not null,
  opdcimq7    number(3,0) default 0 not null,
  opdcimq8    number(3,0) default 0 not null,
  opdcimq9    number(3,0) default 0 not null,
  opdciq10    number(3,0) default 0 not null,
  opdcusr1    varchar2(3) default ' ' not null,
  opdcusr2    varchar2(3) default ' ' not null,
  opdcusr3    varchar2(3) default ' ' not null,
  opdcusr4    varchar2(3) default ' ' not null,
  opdcusr5    varchar2(3) default ' ' not null,
  opdcusr6    varchar2(3) default ' ' not null,
  opdcusr7    varchar2(3) default ' ' not null,
  opdcusr8    varchar2(3) default ' ' not null,
  opdcspar    varchar2(23) default ' ' not null,
  lf          varchar2(1) default ' ' not null
)
tablespace pas_data; 
create index oprauddc on oprauddc
(
opdcaudd,
opdcaudt,
opdcaudp,
opdcaudr
)
tablespace pas_indx; 
create table oprdetcf
(
  opdcuniq    varchar2(10) default ' ' not null,
  opdcteam    varchar2(1) default ' ' not null,
  opdcotm1    varchar2(5) default ' ' not null,
  opdcotm2    varchar2(5) default ' ' not null,
  opdcotm3    varchar2(5) default ' ' not null,
  opdcotm4    varchar2(5) default ' ' not null,
  opdcicd1    varchar2(9) default ' ' not null,
  opdcicd2    varchar2(9) default ' ' not null,
  opdcicd3    varchar2(9) default ' ' not null,
  opdcicd4    varchar2(9) default ' ' not null,
  opdcicd5    varchar2(9) default ' ' not null,
  opdcicd6    varchar2(9) default ' ' not null,
  opdccont    varchar2(1) default ' ' not null,
  opdcdura    number(4,0) default 0 not null,
  opdcnoop    number(3,0) default 0 not null,
  opdcimc1    varchar2(6) default ' ' not null,
  opdcimc2    varchar2(6) default ' ' not null,
  opdcimc3    varchar2(6) default ' ' not null,
  opdcimc4    varchar2(6) default ' ' not null,
  opdcimc5    varchar2(6) default ' ' not null,
  opdcimc6    varchar2(6) default ' ' not null,
  opdcimc7    varchar2(6) default ' ' not null,
  opdcimc8    varchar2(6) default ' ' not null,
  opdcimc9    varchar2(6) default ' ' not null,
  opdcim10    varchar2(6) default ' ' not null,
  opdcimq1    number(3,0) default 0 not null,
  opdcimq2    number(3,0) default 0 not null,
  opdcimq3    number(3,0) default 0 not null,
  opdcimq4    number(3,0) default 0 not null,
  opdcimq5    number(3,0) default 0 not null,
  opdcimq6    number(3,0) default 0 not null,
  opdcimq7    number(3,0) default 0 not null,
  opdcimq8    number(3,0) default 0 not null,
  opdcimq9    number(3,0) default 0 not null,
  opdciq10    number(3,0) default 0 not null,
  opdcusr1    varchar2(3) default ' ' not null,
  opdcusr2    varchar2(3) default ' ' not null,
  opdcusr3    varchar2(3) default ' ' not null,
  opdcusr4    varchar2(3) default ' ' not null,
  opdcusr5    varchar2(3) default ' ' not null,
  opdcusr6    varchar2(3) default ' ' not null,
  opdcusr7    varchar2(3) default ' ' not null,
  opdcusr8    varchar2(3) default ' ' not null,
  opdcspar    varchar2(23) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint oprdetc1 primary key( 
opdcuniq,
opdcteam)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
