create table oprauddb
(
  opdbaudd    varchar2(8) default ' ' not null,
  opdbaudt    varchar2(8) default ' ' not null,
  opdbaudp    varchar2(2) default ' ' not null,
  opdbaudr    varchar2(1) default ' ' not null,
  opdbauds    number(1,0) default 0 not null,
  opdbaudo    varchar2(4) default ' ' not null,
  opdbuniq    varchar2(10) default ' ' not null,
  opdbteam    varchar2(1) default ' ' not null,
  opdbtyd1    varchar2(3) default ' ' not null,
  opdbtyd2    varchar2(3) default ' ' not null,
  opdbtyd3    varchar2(3) default ' ' not null,
  opdbtyd4    varchar2(3) default ' ' not null,
  opdbtyd5    varchar2(3) default ' ' not null,
  opdbtyd6    varchar2(3) default ' ' not null,
  opdbtyd7    varchar2(3) default ' ' not null,
  opdbtyd8    varchar2(3) default ' ' not null,
  opdbdcc1    varchar2(6) default ' ' not null,
  opdbdcc2    varchar2(6) default ' ' not null,
  opdbdcc3    varchar2(6) default ' ' not null,
  opdbdcc4    varchar2(6) default ' ' not null,
  opdbdcc5    varchar2(6) default ' ' not null,
  opdbdcc6    varchar2(6) default ' ' not null,
  opdbdcc7    varchar2(6) default ' ' not null,
  opdbdcc8    varchar2(6) default ' ' not null,
  opdblvd1    varchar2(3) default ' ' not null,
  opdblvd2    varchar2(3) default ' ' not null,
  opdblvd3    varchar2(3) default ' ' not null,
  opdblvd4    varchar2(3) default ' ' not null,
  opdblvd5    varchar2(3) default ' ' not null,
  opdblvd6    varchar2(3) default ' ' not null,
  opdblvd7    varchar2(3) default ' ' not null,
  opdblvd8    varchar2(3) default ' ' not null,
  opdbtyn1    varchar2(3) default ' ' not null,
  opdbtyn2    varchar2(3) default ' ' not null,
  opdbtyn3    varchar2(3) default ' ' not null,
  opdbtyn4    varchar2(3) default ' ' not null,
  opdbtyn5    varchar2(3) default ' ' not null,
  opdbtyn6    varchar2(3) default ' ' not null,
  opdbnuc1    varchar2(6) default ' ' not null,
  opdbnuc2    varchar2(6) default ' ' not null,
  opdbnuc3    varchar2(6) default ' ' not null,
  opdbnuc4    varchar2(6) default ' ' not null,
  opdbnuc5    varchar2(6) default ' ' not null,
  opdbnuc6    varchar2(6) default ' ' not null,
  opdbusr1    varchar2(3) default ' ' not null,
  opdbusr2    varchar2(3) default ' ' not null,
  opdbusr3    varchar2(3) default ' ' not null,
  opdbusr4    varchar2(3) default ' ' not null,
  opdbspar    varchar2(30) default ' ' not null,
  lf          varchar2(1) default ' ' not null
)
tablespace pas_data; 
create index oprauddb on oprauddb
(
opdbaudd,
opdbaudt,
opdbaudp,
opdbaudr
)
tablespace pas_indx; 
create table oprdetbf
(
  opdbuniq    varchar2(10) default ' ' not null,
  opdbteam    varchar2(1) default ' ' not null,
  opdbtyd1    varchar2(3) default ' ' not null,
  opdbtyd2    varchar2(3) default ' ' not null,
  opdbtyd3    varchar2(3) default ' ' not null,
  opdbtyd4    varchar2(3) default ' ' not null,
  opdbtyd5    varchar2(3) default ' ' not null,
  opdbtyd6    varchar2(3) default ' ' not null,
  opdbtyd7    varchar2(3) default ' ' not null,
  opdbtyd8    varchar2(3) default ' ' not null,
  opdbdcc1    varchar2(6) default ' ' not null,
  opdbdcc2    varchar2(6) default ' ' not null,
  opdbdcc3    varchar2(6) default ' ' not null,
  opdbdcc4    varchar2(6) default ' ' not null,
  opdbdcc5    varchar2(6) default ' ' not null,
  opdbdcc6    varchar2(6) default ' ' not null,
  opdbdcc7    varchar2(6) default ' ' not null,
  opdbdcc8    varchar2(6) default ' ' not null,
  opdblvd1    varchar2(3) default ' ' not null,
  opdblvd2    varchar2(3) default ' ' not null,
  opdblvd3    varchar2(3) default ' ' not null,
  opdblvd4    varchar2(3) default ' ' not null,
  opdblvd5    varchar2(3) default ' ' not null,
  opdblvd6    varchar2(3) default ' ' not null,
  opdblvd7    varchar2(3) default ' ' not null,
  opdblvd8    varchar2(3) default ' ' not null,
  opdbtyn1    varchar2(3) default ' ' not null,
  opdbtyn2    varchar2(3) default ' ' not null,
  opdbtyn3    varchar2(3) default ' ' not null,
  opdbtyn4    varchar2(3) default ' ' not null,
  opdbtyn5    varchar2(3) default ' ' not null,
  opdbtyn6    varchar2(3) default ' ' not null,
  opdbnuc1    varchar2(6) default ' ' not null,
  opdbnuc2    varchar2(6) default ' ' not null,
  opdbnuc3    varchar2(6) default ' ' not null,
  opdbnuc4    varchar2(6) default ' ' not null,
  opdbnuc5    varchar2(6) default ' ' not null,
  opdbnuc6    varchar2(6) default ' ' not null,
  opdbusr1    varchar2(3) default ' ' not null,
  opdbusr2    varchar2(3) default ' ' not null,
  opdbusr3    varchar2(3) default ' ' not null,
  opdbusr4    varchar2(3) default ' ' not null,
  opdbspar    varchar2(30) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint oprdetb1 primary key( 
opdbuniq,
opdbteam)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
