create table oprjrraf
(
  opjruniq    varchar2(10) default ' ' not null,
  opjrrcnt    varchar2(2) default ' ' not null,
  opjrtype    varchar2(1) default ' ' not null,
  opjrjoin    varchar2(1) default ' ' not null,
  opjrside    varchar2(1) default ' ' not null,
  opjrprim    varchar2(1) default ' ' not null,
  opjrdi01    varchar2(1) default ' ' not null,
  opjrdi02    varchar2(1) default ' ' not null,
  opjrdi03    varchar2(1) default ' ' not null,
  opjrdi04    varchar2(1) default ' ' not null,
  opjrdi05    varchar2(1) default ' ' not null,
  opjrdi06    varchar2(1) default ' ' not null,
  opjrdi07    varchar2(1) default ' ' not null,
  opjrdi08    varchar2(1) default ' ' not null,
  opjrdi09    varchar2(1) default ' ' not null,
  opjrdi10    varchar2(1) default ' ' not null,
  opjrdi11    varchar2(1) default ' ' not null,
  opjrdi12    varchar2(1) default ' ' not null,
  opjrdi13    varchar2(1) default ' ' not null,
  opjrdi14    varchar2(1) default ' ' not null,
  opjrdi15    varchar2(1) default ' ' not null,
  opjrdi16    varchar2(1) default ' ' not null,
  opjrdi17    varchar2(1) default ' ' not null,
  opjrdi18    varchar2(1) default ' ' not null,
  opjrdi19    varchar2(1) default ' ' not null,
  opjrdi20    varchar2(1) default ' ' not null,
  opjrdi21    varchar2(1) default ' ' not null,
  opjrdi22    varchar2(1) default ' ' not null,
  opjrdi23    varchar2(1) default ' ' not null,
  opjrdi24    varchar2(1) default ' ' not null,
  opjrdi25    varchar2(1) default ' ' not null,
  opjrdc01    varchar2(50) default ' ' not null,
  opjrdc02    varchar2(50) default ' ' not null,
  opjrdc03    varchar2(50) default ' ' not null,
  opjrdc04    varchar2(50) default ' ' not null,
  opjrdc05    varchar2(50) default ' ' not null,
  opjruncm    varchar2(1) default ' ' not null,
  opjruncl    varchar2(1) default ' ' not null,
  opjrcmt1    varchar2(70) default ' ' not null,
  opjrcmt2    varchar2(70) default ' ' not null,
  opjrcmt3    varchar2(70) default ' ' not null,
  opjrcmt4    varchar2(70) default ' ' not null,
  opjrcmt5    varchar2(70) default ' ' not null,
  opjrcomp    varchar2(1) default ' ' not null,
  opjrcmps    varchar2(3) default ' ' not null,
  opjrreop    varchar2(1) default ' ' not null,
  opjrrres    varchar2(50) default ' ' not null,
  opjrcemp    varchar2(1) default ' ' not null,
  opjrcnmp    varchar2(50) default ' ' not null,
  opjrcemt    varchar2(1) default ' ' not null,
  opjrcnmt    varchar2(50) default ' ' not null,
  opjrcemf    varchar2(1) default ' ' not null,
  opjrcnmf    varchar2(50) default ' ' not null,
  opjrcema    varchar2(1) default ' ' not null,
  opjrcnma    varchar2(50) default ' ' not null,
  opjrcemx    varchar2(1) default ' ' not null,
  opjrcnmx    varchar2(50) default ' ' not null,
  opjrcemd    varchar2(1) default ' ' not null,
  opjrscrw    varchar2(1) default ' ' not null,
  opjrscrn    varchar2(3) default ' ' not null,
  opjrwire    varchar2(1) default ' ' not null,
  opjrgrip    varchar2(1) default ' ' not null,
  opjrgric    varchar2(50) default ' ' not null,
  opjrcabl    varchar2(1) default ' ' not null,
  opjrcabc    varchar2(50) default ' ' not null,
  opjrcabn    varchar2(3) default ' ' not null,
  opjrcdat    varchar2(8) default ' ' not null,
  opjrctim    varchar2(8) default ' ' not null,
  opjrcuid    varchar2(10) default ' ' not null,
  opjrudat    varchar2(8) default ' ' not null,
  opjrutim    varchar2(8) default ' ' not null,
  opjruuid    varchar2(10) default ' ' not null,
  opjrspar    varchar2(80) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint oprjrra1 primary key( 
opjruniq,
opjrrcnt)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
