create table oprpimaf
(
  oppiunid    varchar2(10) default ' ' not null,
  oppitmno    varchar2(1) default ' ' not null,
  doppicnt    varchar2(2) default ' ' not null,
  oppiicde    varchar2(15) default ' ' not null,
  oppiiqty    number(3,0) default 0 not null,
  oppiltsn    varchar2(20) default ' ' not null,
  oppicost    varchar2(10) default ' ' not null,
  oppiloca    varchar2(3) default ' ' not null,
  oppiuc01    varchar2(3) default ' ' not null,
  oppiuc02    varchar2(3) default ' ' not null,
  oppiuc03    varchar2(3) default ' ' not null,
  oppiuc04    varchar2(3) default ' ' not null,
  oppiuc05    varchar2(3) default ' ' not null,
  oppiuc06    varchar2(3) default ' ' not null,
  oppiuc07    varchar2(3) default ' ' not null,
  oppiuc08    varchar2(3) default ' ' not null,
  oppiuc09    varchar2(3) default ' ' not null,
  oppiuc10    varchar2(3) default ' ' not null,
  oppiuc11    varchar2(3) default ' ' not null,
  oppiuc12    varchar2(3) default ' ' not null,
  oppiuc13    varchar2(3) default ' ' not null,
  oppiuc14    varchar2(3) default ' ' not null,
  oppiuc15    varchar2(3) default ' ' not null,
  oppiuc16    varchar2(3) default ' ' not null,
  oppiuc17    varchar2(3) default ' ' not null,
  oppiuc18    varchar2(3) default ' ' not null,
  oppiuc19    varchar2(3) default ' ' not null,
  oppiuc20    varchar2(3) default ' ' not null,
  oppiuy01    varchar2(1) default ' ' not null,
  oppiuy02    varchar2(1) default ' ' not null,
  oppiuy03    varchar2(1) default ' ' not null,
  oppiuy04    varchar2(1) default ' ' not null,
  oppiuy05    varchar2(1) default ' ' not null,
  oppiuy06    varchar2(1) default ' ' not null,
  oppiuy07    varchar2(1) default ' ' not null,
  oppiuy08    varchar2(1) default ' ' not null,
  oppiuy09    varchar2(1) default ' ' not null,
  oppiuy10    varchar2(1) default ' ' not null,
  oppiut01    varchar2(8) default ' ' not null,
  oppiut02    varchar2(8) default ' ' not null,
  oppiut03    varchar2(8) default ' ' not null,
  oppiut04    varchar2(8) default ' ' not null,
  oppiut05    varchar2(8) default ' ' not null,
  oppiut06    varchar2(8) default ' ' not null,
  oppiut07    varchar2(8) default ' ' not null,
  oppiut08    varchar2(8) default ' ' not null,
  oppiut09    varchar2(8) default ' ' not null,
  oppiut10    varchar2(8) default ' ' not null,
  oppiuf01    number(6,0) default 0 not null,
  oppiuf02    number(6,0) default 0 not null,
  oppiuf03    number(6,0) default 0 not null,
  oppiuf04    number(6,0) default 0 not null,
  oppiuf05    number(6,0) default 0 not null,
  oppiuf06    number(6,0) default 0 not null,
  oppiuf07    number(6,0) default 0 not null,
  oppiuf08    number(6,0) default 0 not null,
  oppiuf09    number(6,0) default 0 not null,
  oppiuf10    number(6,0) default 0 not null,
  oppidtrt    varchar2(6) default ' ' not null,
  oppidumm    varchar2(1) default ' ' not null,
  oppionum    varchar2(7) default ' ' not null,
  oppiicos    varchar2(15) default ' ' not null,
  oppircnt    varchar2(2) default ' ' not null,
  oppicdat    varchar2(8) default ' ' not null,
  oppictim    varchar2(8) default ' ' not null,
  oppicuid    varchar2(10) default ' ' not null,
  oppibcod    varchar2(60) default ' ' not null,
  oppiaimp    varchar2(1) default ' ' not null,
  oppiudat    varchar2(8) default ' ' not null,
  oppiutim    varchar2(8) default ' ' not null,
  oppiuuid    varchar2(10) default ' ' not null,
  oppispar    varchar2(24) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint oprpima1 primary key( 
oppiunid,
oppitmno,
doppicnt)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index oprpima2 on oprpimaf
(
oppiicde,
oppiunid,
oppitmno,
doppicnt
)
  tablespace pas_indx; 
create unique index oprpima3 on oprpimaf
(
oppibcod,
oppiunid,
oppitmno,
doppicnt
)
  tablespace pas_indx; 
