create table oprpocaf
(
  oppounid    varchar2(10) default ' ' not null,
  dopporty    varchar2(1) default ' ' not null,
  oppopidb    varchar2(1) default ' ' not null,
  opposatf    varchar2(1) default ' ' not null,
  oppoaatf    varchar2(1) default ' ' not null,
  oppobatf    varchar2(1) default ' ' not null,
  oppotbpf    varchar2(1) default ' ' not null,
  oppotnbm    varchar2(8) default ' ' not null,
  oppotnbf    varchar2(8) default ' ' not null,
  opponbmc    varchar2(1) default ' ' not null,
  opponbfc    varchar2(1) default ' ' not null,
  oppoalln    varchar2(1) default ' ' not null,
  oppoecgr    varchar2(1) default ' ' not null,
  oppolabr    varchar2(1) default ' ' not null,
  oppocomb    varchar2(1) default ' ' not null,
  oppomedc    varchar2(1) default ' ' not null,
  oppodrin    varchar2(1) default ' ' not null,
  oppoflub    varchar2(1) default ' ' not null,
  oppoxray    varchar2(1) default ' ' not null,
  oppodiac    varchar2(1) default ' ' not null,
  oppodent    varchar2(3) default ' ' not null,
  oppovals    varchar2(3) default ' ' not null,
  opposhav    varchar2(1) default ' ' not null,
  oppourvd    varchar2(8) default ' ' not null,
  oppointr    varchar2(3) default ' ' not null,
  oppolabn    number(2,0) default 0 not null,
  oppouc01    varchar2(3) default ' ' not null,
  oppouc02    varchar2(3) default ' ' not null,
  oppouc03    varchar2(3) default ' ' not null,
  oppouc04    varchar2(3) default ' ' not null,
  oppouc05    varchar2(3) default ' ' not null,
  oppouc06    varchar2(3) default ' ' not null,
  oppouc07    varchar2(3) default ' ' not null,
  oppouc08    varchar2(3) default ' ' not null,
  oppouc09    varchar2(3) default ' ' not null,
  oppouc10    varchar2(3) default ' ' not null,
  oppouc11    varchar2(3) default ' ' not null,
  oppouc12    varchar2(3) default ' ' not null,
  oppouc13    varchar2(3) default ' ' not null,
  oppouc14    varchar2(3) default ' ' not null,
  oppouc15    varchar2(3) default ' ' not null,
  oppouc16    varchar2(3) default ' ' not null,
  oppouc17    varchar2(3) default ' ' not null,
  oppouc18    varchar2(3) default ' ' not null,
  oppouc19    varchar2(3) default ' ' not null,
  oppouc20    varchar2(3) default ' ' not null,
  oppouy01    varchar2(1) default ' ' not null,
  oppouy02    varchar2(1) default ' ' not null,
  oppouy03    varchar2(1) default ' ' not null,
  oppouy04    varchar2(1) default ' ' not null,
  oppouy05    varchar2(1) default ' ' not null,
  oppouy06    varchar2(1) default ' ' not null,
  oppouy07    varchar2(1) default ' ' not null,
  oppouy08    varchar2(1) default ' ' not null,
  oppouy09    varchar2(1) default ' ' not null,
  oppouy10    varchar2(1) default ' ' not null,
  oppout01    varchar2(8) default ' ' not null,
  oppout02    varchar2(8) default ' ' not null,
  oppout03    varchar2(8) default ' ' not null,
  oppout04    varchar2(8) default ' ' not null,
  oppout05    varchar2(8) default ' ' not null,
  oppout06    varchar2(8) default ' ' not null,
  oppout07    varchar2(8) default ' ' not null,
  oppout08    varchar2(8) default ' ' not null,
  oppout09    varchar2(8) default ' ' not null,
  oppout10    varchar2(8) default ' ' not null,
  oppouf01    number(6,0) default 0 not null,
  oppouf02    number(6,0) default 0 not null,
  oppouf03    number(6,0) default 0 not null,
  oppouf04    number(6,0) default 0 not null,
  oppouf05    number(6,0) default 0 not null,
  oppouf06    number(6,0) default 0 not null,
  oppouf07    number(6,0) default 0 not null,
  oppouf08    number(6,0) default 0 not null,
  oppouf09    number(6,0) default 0 not null,
  oppouf10    number(6,0) default 0 not null,
  oppoudr1    varchar2(10) default ' ' not null,
  oppoudr2    varchar2(10) default ' ' not null,
  oppoudr3    varchar2(10) default ' ' not null,
  oppoudr4    varchar2(10) default ' ' not null,
  oppoudr5    varchar2(10) default ' ' not null,
  oppounr1    varchar2(10) default ' ' not null,
  oppounr2    varchar2(10) default ' ' not null,
  oppounr3    varchar2(10) default ' ' not null,
  oppounr4    varchar2(10) default ' ' not null,
  oppounr5    varchar2(10) default ' ' not null,
  oppoud01    varchar2(8) default ' ' not null,
  oppoud02    varchar2(8) default ' ' not null,
  oppoud03    varchar2(8) default ' ' not null,
  oppoud04    varchar2(8) default ' ' not null,
  oppoud05    varchar2(8) default ' ' not null,
  oppoud06    varchar2(8) default ' ' not null,
  oppoud07    varchar2(8) default ' ' not null,
  oppoud08    varchar2(8) default ' ' not null,
  oppoud09    varchar2(8) default ' ' not null,
  oppoud10    varchar2(8) default ' ' not null,
  oppospar    varchar2(50) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint oprpoca1 primary key( 
oppounid,
dopporty)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index oprpoca2 on oprpocaf
(
dopporty,
oppounid
)
  tablespace pas_indx; 
