create table opraudse
(
  opseaudd    varchar2(8) default ' ' not null,
  opseaudt    varchar2(8) default ' ' not null,
  opseaudp    varchar2(2) default ' ' not null,
  opseaudr    varchar2(1) default ' ' not null,
  opseauds    number(1,0) default 0 not null,
  opseaudo    varchar2(4) default ' ' not null,
  opsedate    varchar2(8) default ' ' not null,
  opsetime    varchar2(5) default ' ' not null,
  opseclin    varchar2(6) default ' ' not null,
  dopsesus    varchar2(1) default ' ' not null,
  opseday     number(1,0) default 0 not null,
  opsebook    varchar2(8) default ' ' not null,
  opseendt    varchar2(5) default ' ' not null,
  opsedura    number(4,0) default 0 not null,
  opsebrkt    number(3,0) default 0 not null,
  opseprep    number(2,0) default 0 not null,
  opsetper    varchar2(3) default ' ' not null,
  opsetype    varchar2(3) default ' ' not null,
  opsethet    varchar2(6) default ' ' not null,
  opsecord    varchar2(6) default ' ' not null,
  opseanae    varchar2(6) default ' ' not null,
  opsestat    number(1,0) default 0 not null,
  opsetimb    number(4,0) default 0 not null,
  opseacts    varchar2(5) default ' ' not null,
  opseacte    varchar2(5) default ' ' not null,
  opseactd    number(4,0) default 0 not null,
  opseover    varchar2(3) default ' ' not null,
  opsedela    varchar2(3) default ' ' not null,
  opsecanc    varchar2(3) default ' ' not null,
  opsetyd1    varchar2(3) default ' ' not null,
  opsetyd2    varchar2(3) default ' ' not null,
  opsetyd3    varchar2(3) default ' ' not null,
  opsetyd4    varchar2(3) default ' ' not null,
  opsetyd5    varchar2(3) default ' ' not null,
  opsetyd6    varchar2(3) default ' ' not null,
  opsetyd7    varchar2(3) default ' ' not null,
  opsetyd8    varchar2(3) default ' ' not null,
  opsedcc1    varchar2(6) default ' ' not null,
  opsedcc2    varchar2(6) default ' ' not null,
  opsedcc3    varchar2(6) default ' ' not null,
  opsedcc4    varchar2(6) default ' ' not null,
  opsedcc5    varchar2(6) default ' ' not null,
  opsedcc6    varchar2(6) default ' ' not null,
  opsedcc7    varchar2(6) default ' ' not null,
  opsedcc8    varchar2(6) default ' ' not null,
  opselvd1    varchar2(3) default ' ' not null,
  opselvd2    varchar2(3) default ' ' not null,
  opselvd3    varchar2(3) default ' ' not null,
  opselvd4    varchar2(3) default ' ' not null,
  opselvd5    varchar2(3) default ' ' not null,
  opselvd6    varchar2(3) default ' ' not null,
  opselvd7    varchar2(3) default ' ' not null,
  opselvd8    varchar2(3) default ' ' not null,
  opsetyn1    varchar2(3) default ' ' not null,
  opsetyn2    varchar2(3) default ' ' not null,
  opsetyn3    varchar2(3) default ' ' not null,
  opsetyn4    varchar2(3) default ' ' not null,
  opsetyn5    varchar2(3) default ' ' not null,
  opsetyn6    varchar2(3) default ' ' not null,
  opsenuc1    varchar2(6) default ' ' not null,
  opsenuc2    varchar2(6) default ' ' not null,
  opsenuc3    varchar2(6) default ' ' not null,
  opsenuc4    varchar2(6) default ' ' not null,
  opsenuc5    varchar2(6) default ' ' not null,
  opsenuc6    varchar2(6) default ' ' not null,
  opseusr1    varchar2(3) default ' ' not null,
  opseusr2    varchar2(3) default ' ' not null,
  opseusr3    varchar2(3) default ' ' not null,
  opseusr4    varchar2(3) default ' ' not null,
  opsexdoc    varchar2(6) default ' ' not null,
  opseendd    varchar2(8) default ' ' not null,
  opseacds    varchar2(8) default ' ' not null,
  opseacde    varchar2(8) default ' ' not null,
  opsespi1    varchar2(50) default ' ' not null,
  opsespi2    varchar2(50) default ' ' not null,
  opsendlk    varchar2(2) default ' ' not null,
  opsestyp    varchar2(3) default ' ' not null,
  opsedgsi    varchar2(3) default ' ' not null,
  opsefind    varchar2(8) default ' ' not null,
  opsefint    varchar2(8) default ' ' not null,
  opsehosp    varchar2(3) default ' ' not null,
  opsecndt    varchar2(8) default ' ' not null,
  opsecntm    varchar2(8) default ' ' not null,
  opsecnid    varchar2(10) default ' ' not null,
  opsedtcm    varchar2(1) default ' ' not null,
  opseucdt    varchar2(10) default ' ' not null,
  opsedcdt    varchar2(8) default ' ' not null,
  opsetcdt    varchar2(8) default ' ' not null,
  opseuudt    varchar2(10) default ' ' not null,
  opsedudt    varchar2(8) default ' ' not null,
  opsetudt    varchar2(8) default ' ' not null,
  opseadts    varchar2(1) default ' ' not null,
  opsespar    varchar2(49) default ' ' not null,
  lf          varchar2(1) default ' ' not null
)
tablespace pas_data; 
create index opraudse on opraudse
(
opseaudd,
opseaudt,
opseaudp,
opseaudr
)
tablespace pas_indx; 
create table oprsesaf
(
  opsedate    varchar2(8) default ' ' not null,
  opsetime    varchar2(5) default ' ' not null,
  opseclin    varchar2(6) default ' ' not null,
  dopsesus    varchar2(1) default ' ' not null,
  opseday     number(1,0) default 0 not null,
  opsebook    varchar2(8) default ' ' not null,
  opseendt    varchar2(5) default ' ' not null,
  opsedura    number(4,0) default 0 not null,
  opsebrkt    number(3,0) default 0 not null,
  opseprep    number(2,0) default 0 not null,
  opsetper    varchar2(3) default ' ' not null,
  opsetype    varchar2(3) default ' ' not null,
  opsethet    varchar2(6) default ' ' not null,
  opsecord    varchar2(6) default ' ' not null,
  opseanae    varchar2(6) default ' ' not null,
  opsestat    number(1,0) default 0 not null,
  opsetimb    number(4,0) default 0 not null,
  opseacts    varchar2(5) default ' ' not null,
  opseacte    varchar2(5) default ' ' not null,
  opseactd    number(4,0) default 0 not null,
  opseover    varchar2(3) default ' ' not null,
  opsedela    varchar2(3) default ' ' not null,
  opsecanc    varchar2(3) default ' ' not null,
  opsetyd1    varchar2(3) default ' ' not null,
  opsetyd2    varchar2(3) default ' ' not null,
  opsetyd3    varchar2(3) default ' ' not null,
  opsetyd4    varchar2(3) default ' ' not null,
  opsetyd5    varchar2(3) default ' ' not null,
  opsetyd6    varchar2(3) default ' ' not null,
  opsetyd7    varchar2(3) default ' ' not null,
  opsetyd8    varchar2(3) default ' ' not null,
  opsedcc1    varchar2(6) default ' ' not null,
  opsedcc2    varchar2(6) default ' ' not null,
  opsedcc3    varchar2(6) default ' ' not null,
  opsedcc4    varchar2(6) default ' ' not null,
  opsedcc5    varchar2(6) default ' ' not null,
  opsedcc6    varchar2(6) default ' ' not null,
  opsedcc7    varchar2(6) default ' ' not null,
  opsedcc8    varchar2(6) default ' ' not null,
  opselvd1    varchar2(3) default ' ' not null,
  opselvd2    varchar2(3) default ' ' not null,
  opselvd3    varchar2(3) default ' ' not null,
  opselvd4    varchar2(3) default ' ' not null,
  opselvd5    varchar2(3) default ' ' not null,
  opselvd6    varchar2(3) default ' ' not null,
  opselvd7    varchar2(3) default ' ' not null,
  opselvd8    varchar2(3) default ' ' not null,
  opsetyn1    varchar2(3) default ' ' not null,
  opsetyn2    varchar2(3) default ' ' not null,
  opsetyn3    varchar2(3) default ' ' not null,
  opsetyn4    varchar2(3) default ' ' not null,
  opsetyn5    varchar2(3) default ' ' not null,
  opsetyn6    varchar2(3) default ' ' not null,
  opsenuc1    varchar2(6) default ' ' not null,
  opsenuc2    varchar2(6) default ' ' not null,
  opsenuc3    varchar2(6) default ' ' not null,
  opsenuc4    varchar2(6) default ' ' not null,
  opsenuc5    varchar2(6) default ' ' not null,
  opsenuc6    varchar2(6) default ' ' not null,
  opseusr1    varchar2(3) default ' ' not null,
  opseusr2    varchar2(3) default ' ' not null,
  opseusr3    varchar2(3) default ' ' not null,
  opseusr4    varchar2(3) default ' ' not null,
  opsexdoc    varchar2(6) default ' ' not null,
  opseendd    varchar2(8) default ' ' not null,
  opseacds    varchar2(8) default ' ' not null,
  opseacde    varchar2(8) default ' ' not null,
  opsespi1    varchar2(50) default ' ' not null,
  opsespi2    varchar2(50) default ' ' not null,
  opsendlk    varchar2(2) default ' ' not null,
  opsestyp    varchar2(3) default ' ' not null,
  opsedgsi    varchar2(3) default ' ' not null,
  opsefind    varchar2(8) default ' ' not null,
  opsefint    varchar2(8) default ' ' not null,
  opsehosp    varchar2(3) default ' ' not null,
  opsecndt    varchar2(8) default ' ' not null,
  opsecntm    varchar2(8) default ' ' not null,
  opsecnid    varchar2(10) default ' ' not null,
  opsedtcm    varchar2(1) default ' ' not null,
  opseucdt    varchar2(10) default ' ' not null,
  opsedcdt    varchar2(8) default ' ' not null,
  opsetcdt    varchar2(8) default ' ' not null,
  opseuudt    varchar2(10) default ' ' not null,
  opsedudt    varchar2(8) default ' ' not null,
  opsetudt    varchar2(8) default ' ' not null,
  opseadts    varchar2(1) default ' ' not null,
  opsespar    varchar2(49) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint oprsesa1 primary key( 
opsehosp,
opsedate,
opsetime,
opseclin)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index oprsesa2 on oprsesaf
(
opseclin,
opsehosp,
opsedate,
opsetime
)
  tablespace pas_indx; 
create unique index oprsesa3 on oprsesaf
(
dopsesus,
opseclin,
opsehosp,
opsedate,
opsetime
)
  tablespace pas_indx; 
create unique index oprsesa4 on oprsesaf
(
opsehosp,
opsedate,
opsethet,
opsetime,
opseclin
)
  tablespace pas_indx; 
create unique index oprsesa5 on oprsesaf
(
opsetype,
opsehosp,
opsedate,
opsetime,
opsethet,
opseclin
)
  tablespace pas_indx; 
create unique index oprsesa6 on oprsesaf
(
opseanae,
opsehosp,
opsedate,
opsetime,
opseclin
)
  tablespace pas_indx; 
create unique index oprsesa7 on oprsesaf
(
opsedate,
opsetime,
opseclin,
opsehosp
)
  tablespace pas_indx; 
