create table opraudsg
(
  opsgaudd    varchar2(8) default ' ' not null,
  opsgaudt    varchar2(8) default ' ' not null,
  opsgaudp    varchar2(2) default ' ' not null,
  opsgaudr    varchar2(1) default ' ' not null,
  opsgauds    number(1,0) default 0 not null,
  opsgaudo    varchar2(4) default ' ' not null,
  opsgunid    varchar2(10) default ' ' not null,
  opsgtmno    varchar2(1) default ' ' not null,
  opsgtips    varchar2(8) default ' ' not null,
  opsgtidr    varchar2(8) default ' ' not null,
  opsgtiss    varchar2(8) default ' ' not null,
  opsgtise    varchar2(8) default ' ' not null,
  opsgsgdl    varchar2(3) default ' ' not null,
  opsgccnt    varchar2(1) default ' ' not null,
  opsgcnto    varchar2(6) default ' ' not null,
  opsgblos    varchar2(3) default ' ' not null,
  opsgwcon    varchar2(3) default ' ' not null,
  opsgwcm1    varchar2(3) default ' ' not null,
  opsgwcm2    varchar2(3) default ' ' not null,
  opsgwcm3    varchar2(3) default ' ' not null,
  opsgicd1    varchar2(15) default ' ' not null,
  opsgicd2    varchar2(15) default ' ' not null,
  opsgicd3    varchar2(15) default ' ' not null,
  opsgdst1    varchar2(4) default ' ' not null,
  opsgdcd1    varchar2(15) default ' ' not null,
  opsgdnm1    varchar2(15) default ' ' not null,
  opsgdps1    varchar2(20) default ' ' not null,
  opsgdck1    varchar2(1) default ' ' not null,
  opsgdpr1    varchar2(1) default ' ' not null,
  opsgdst2    varchar2(4) default ' ' not null,
  opsgdcd2    varchar2(15) default ' ' not null,
  opsgdnm2    varchar2(15) default ' ' not null,
  opsgdps2    varchar2(20) default ' ' not null,
  opsgdck2    varchar2(1) default ' ' not null,
  opsgdpr2    varchar2(1) default ' ' not null,
  opsgcat1    varchar2(15) default ' ' not null,
  opsgcat2    varchar2(15) default ' ' not null,
  opsgdrt1    varchar2(15) default ' ' not null,
  opsgdrt2    varchar2(15) default ' ' not null,
  opsgpack    varchar2(15) default ' ' not null,
  opsgdrs1    varchar2(15) default ' ' not null,
  opsgdrs2    varchar2(15) default ' ' not null,
  opsgdrs3    varchar2(15) default ' ' not null,
  opsgwdv1    varchar2(15) default ' ' not null,
  opsgwdv2    varchar2(15) default ' ' not null,
  opsgwdv3    varchar2(15) default ' ' not null,
  opsgirig    varchar2(15) default ' ' not null,
  opsgirgs    varchar2(15) default ' ' not null,
  opsgirai    number(4,0) default 0 not null,
  opsgirao    number(4,0) default 0 not null,
  opsgclfs    varchar2(2) default ' ' not null,
  opsginfc    varchar2(1) default ' ' not null,
  opsgspmi    varchar2(2) default ' ' not null,
  opsgspap    varchar2(2) default ' ' not null,
  opsgothr    varchar2(37) default ' ' not null,
  opsguc01    varchar2(3) default ' ' not null,
  opsguc02    varchar2(3) default ' ' not null,
  opsguc03    varchar2(3) default ' ' not null,
  opsguc04    varchar2(3) default ' ' not null,
  opsguc05    varchar2(3) default ' ' not null,
  opsguc06    varchar2(3) default ' ' not null,
  opsguc07    varchar2(3) default ' ' not null,
  opsguc08    varchar2(3) default ' ' not null,
  opsguc09    varchar2(3) default ' ' not null,
  opsguc10    varchar2(3) default ' ' not null,
  opsguc11    varchar2(3) default ' ' not null,
  opsguc12    varchar2(3) default ' ' not null,
  opsguc13    varchar2(3) default ' ' not null,
  opsguc14    varchar2(3) default ' ' not null,
  opsguc15    varchar2(3) default ' ' not null,
  opsguc16    varchar2(3) default ' ' not null,
  opsguc17    varchar2(3) default ' ' not null,
  opsguc18    varchar2(3) default ' ' not null,
  opsguc19    varchar2(3) default ' ' not null,
  opsguc20    varchar2(3) default ' ' not null,
  opsguy01    varchar2(1) default ' ' not null,
  opsguy02    varchar2(1) default ' ' not null,
  opsguy03    varchar2(1) default ' ' not null,
  opsguy04    varchar2(1) default ' ' not null,
  opsguy05    varchar2(1) default ' ' not null,
  opsguy06    varchar2(1) default ' ' not null,
  opsguy07    varchar2(1) default ' ' not null,
  opsguy08    varchar2(1) default ' ' not null,
  opsguy09    varchar2(1) default ' ' not null,
  opsguy10    varchar2(1) default ' ' not null,
  opsgut01    varchar2(8) default ' ' not null,
  opsgut02    varchar2(8) default ' ' not null,
  opsgut03    varchar2(8) default ' ' not null,
  opsgut04    varchar2(8) default ' ' not null,
  opsgut05    varchar2(8) default ' ' not null,
  opsgut06    varchar2(8) default ' ' not null,
  opsgut07    varchar2(8) default ' ' not null,
  opsgut08    varchar2(8) default ' ' not null,
  opsgut09    varchar2(8) default ' ' not null,
  opsgut10    varchar2(8) default ' ' not null,
  opsguf01    number(6,0) default 0 not null,
  opsguf02    number(6,0) default 0 not null,
  opsguf03    number(6,0) default 0 not null,
  opsguf04    number(6,0) default 0 not null,
  opsguf05    number(6,0) default 0 not null,
  opsguf06    number(6,0) default 0 not null,
  opsguf07    number(6,0) default 0 not null,
  opsguf08    number(6,0) default 0 not null,
  opsguf09    number(6,0) default 0 not null,
  opsguf10    number(6,0) default 0 not null,
  opsguthr    varchar2(10) default ' ' not null,
  opsgides    varchar2(60) default ' ' not null,
  opsgnoop    number(3,0) default 0 not null,
  opsgdt3u    varchar2(6) default ' ' not null,
  opsgdt3c    varchar2(15) default ' ' not null,
  opsgspar    varchar2(28) default ' ' not null,
  lf          varchar2(1) default ' ' not null
)
tablespace pas_data; 
create index opraudsg on opraudsg
(
opsgaudd,
opsgaudt,
opsgaudp,
opsgaudr
)
tablespace pas_indx; 
create table oprsrgaf
(
  opsgunid    varchar2(10) default ' ' not null,
  opsgtmno    varchar2(1) default ' ' not null,
  opsgtips    varchar2(8) default ' ' not null,
  opsgtidr    varchar2(8) default ' ' not null,
  opsgtiss    varchar2(8) default ' ' not null,
  opsgtise    varchar2(8) default ' ' not null,
  opsgsgdl    varchar2(3) default ' ' not null,
  opsgccnt    varchar2(1) default ' ' not null,
  opsgcnto    varchar2(6) default ' ' not null,
  opsgblos    varchar2(3) default ' ' not null,
  opsgwcon    varchar2(3) default ' ' not null,
  opsgwcm1    varchar2(3) default ' ' not null,
  opsgwcm2    varchar2(3) default ' ' not null,
  opsgwcm3    varchar2(3) default ' ' not null,
  opsgicd1    varchar2(15) default ' ' not null,
  opsgicd2    varchar2(15) default ' ' not null,
  opsgicd3    varchar2(15) default ' ' not null,
  opsgdst1    varchar2(4) default ' ' not null,
  opsgdcd1    varchar2(15) default ' ' not null,
  opsgdnm1    varchar2(15) default ' ' not null,
  opsgdps1    varchar2(20) default ' ' not null,
  opsgdck1    varchar2(1) default ' ' not null,
  opsgdpr1    varchar2(1) default ' ' not null,
  opsgdst2    varchar2(4) default ' ' not null,
  opsgdcd2    varchar2(15) default ' ' not null,
  opsgdnm2    varchar2(15) default ' ' not null,
  opsgdps2    varchar2(20) default ' ' not null,
  opsgdck2    varchar2(1) default ' ' not null,
  opsgdpr2    varchar2(1) default ' ' not null,
  opsgcat1    varchar2(15) default ' ' not null,
  opsgcat2    varchar2(15) default ' ' not null,
  opsgdrt1    varchar2(15) default ' ' not null,
  opsgdrt2    varchar2(15) default ' ' not null,
  opsgpack    varchar2(15) default ' ' not null,
  opsgdrs1    varchar2(15) default ' ' not null,
  opsgdrs2    varchar2(15) default ' ' not null,
  opsgdrs3    varchar2(15) default ' ' not null,
  opsgwdv1    varchar2(15) default ' ' not null,
  opsgwdv2    varchar2(15) default ' ' not null,
  opsgwdv3    varchar2(15) default ' ' not null,
  opsgirig    varchar2(15) default ' ' not null,
  opsgirgs    varchar2(15) default ' ' not null,
  opsgirai    number(4,0) default 0 not null,
  opsgirao    number(4,0) default 0 not null,
  opsgclfs    varchar2(2) default ' ' not null,
  opsginfc    varchar2(1) default ' ' not null,
  opsgspmi    varchar2(2) default ' ' not null,
  opsgspap    varchar2(2) default ' ' not null,
  opsgothr    varchar2(37) default ' ' not null,
  opsguc01    varchar2(3) default ' ' not null,
  opsguc02    varchar2(3) default ' ' not null,
  opsguc03    varchar2(3) default ' ' not null,
  opsguc04    varchar2(3) default ' ' not null,
  opsguc05    varchar2(3) default ' ' not null,
  opsguc06    varchar2(3) default ' ' not null,
  opsguc07    varchar2(3) default ' ' not null,
  opsguc08    varchar2(3) default ' ' not null,
  opsguc09    varchar2(3) default ' ' not null,
  opsguc10    varchar2(3) default ' ' not null,
  opsguc11    varchar2(3) default ' ' not null,
  opsguc12    varchar2(3) default ' ' not null,
  opsguc13    varchar2(3) default ' ' not null,
  opsguc14    varchar2(3) default ' ' not null,
  opsguc15    varchar2(3) default ' ' not null,
  opsguc16    varchar2(3) default ' ' not null,
  opsguc17    varchar2(3) default ' ' not null,
  opsguc18    varchar2(3) default ' ' not null,
  opsguc19    varchar2(3) default ' ' not null,
  opsguc20    varchar2(3) default ' ' not null,
  opsguy01    varchar2(1) default ' ' not null,
  opsguy02    varchar2(1) default ' ' not null,
  opsguy03    varchar2(1) default ' ' not null,
  opsguy04    varchar2(1) default ' ' not null,
  opsguy05    varchar2(1) default ' ' not null,
  opsguy06    varchar2(1) default ' ' not null,
  opsguy07    varchar2(1) default ' ' not null,
  opsguy08    varchar2(1) default ' ' not null,
  opsguy09    varchar2(1) default ' ' not null,
  opsguy10    varchar2(1) default ' ' not null,
  opsgut01    varchar2(8) default ' ' not null,
  opsgut02    varchar2(8) default ' ' not null,
  opsgut03    varchar2(8) default ' ' not null,
  opsgut04    varchar2(8) default ' ' not null,
  opsgut05    varchar2(8) default ' ' not null,
  opsgut06    varchar2(8) default ' ' not null,
  opsgut07    varchar2(8) default ' ' not null,
  opsgut08    varchar2(8) default ' ' not null,
  opsgut09    varchar2(8) default ' ' not null,
  opsgut10    varchar2(8) default ' ' not null,
  opsguf01    number(6,0) default 0 not null,
  opsguf02    number(6,0) default 0 not null,
  opsguf03    number(6,0) default 0 not null,
  opsguf04    number(6,0) default 0 not null,
  opsguf05    number(6,0) default 0 not null,
  opsguf06    number(6,0) default 0 not null,
  opsguf07    number(6,0) default 0 not null,
  opsguf08    number(6,0) default 0 not null,
  opsguf09    number(6,0) default 0 not null,
  opsguf10    number(6,0) default 0 not null,
  opsguthr    varchar2(10) default ' ' not null,
  opsgides    varchar2(60) default ' ' not null,
  opsgnoop    number(3,0) default 0 not null,
  opsgdt3u    varchar2(6) default ' ' not null,
  opsgdt3c    varchar2(15) default ' ' not null,
  opsgspar    varchar2(28) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint oprsrga1 primary key( 
opsgunid,
opsgtmno)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
