create table outaudb1
(
  otbbaudd    varchar2(8) default ' ' not null,
  otbbaudt    varchar2(8) default ' ' not null,
  otbbaudp    varchar2(2) default ' ' not null,
  otbbaudr    varchar2(1) default ' ' not null,
  otbbauds    number(1,0) default 0 not null,
  otbbaudo    varchar2(4) default ' ' not null,
  otbbsite    varchar2(6) default ' ' not null,
  dobaoutn    varchar2(8) default ' ' not null,
  obasrcr     varchar2(3) default ' ' not null,
  obacomp     varchar2(3) default ' ' not null,
  obaclass    varchar2(3) default ' ' not null,
  obains      varchar2(3) default ' ' not null,
  obaattn     varchar2(3) default ' ' not null,
  obadoct     varchar2(6) default ' ' not null,
  obacomm     varchar2(25) default ' ' not null,
  otbbfund    varchar2(6) default ' ' not null,
  otbbtble    varchar2(8) default ' ' not null,
  dotbbpvi    varchar2(3) default ' ' not null,
  otbbclal    varchar2(3) default ' ' not null,
  otbbspar    varchar2(4) default ' ' not null,
  obadate     varchar2(8) default ' ' not null,
  obacat      varchar2(3) default ' ' not null,
  obaprty     varchar2(3) default ' ' not null,
  obarschd    varchar2(3) default ' ' not null,
  obbport     varchar2(2) default ' ' not null,
  obbbook     varchar2(1) default ' ' not null,
  obbctyp     varchar2(6) default ' ' not null,
  obousr1     varchar2(3) default ' ' not null,
  obousr2     varchar2(3) default ' ' not null,
  obousr3     varchar2(3) default ' ' not null,
  obousr4     varchar2(3) default ' ' not null,
  obaladmn    varchar2(8) default ' ' not null,
  otbbdept    varchar2(3) default ' ' not null,
  otbbtran    varchar2(3) default ' ' not null,
  otbblngi    varchar2(3) default ' ' not null,
  otbbtmfs    varchar2(8) default ' ' not null,
  otbbtmbo    varchar2(8) default ' ' not null,
  otbbgpfa    varchar2(20) default ' ' not null,
  otbbecra    varchar2(20) default ' ' not null,
  otbbrfgp    varchar2(10) default ' ' not null,
  otbbgppc    varchar2(10) default ' ' not null,
  otbbadcs    varchar2(10) default ' ' not null,
  otbbcitm    varchar2(5) default ' ' not null,
  otbbastm    varchar2(5) default ' ' not null,
  otbbdptm    varchar2(5) default ' ' not null,
  otbboutc    varchar2(3) default ' ' not null,
  otbbsndl    varchar2(1) default ' ' not null,
  otbbgppt    varchar2(2) default ' ' not null,
  otbbdofr    varchar2(3) default ' ' not null,
  otbboper    varchar2(4) default ' ' not null,
  obousr5     varchar2(3) default ' ' not null,
  obousr6     varchar2(3) default ' ' not null,
  obousr7     varchar2(3) default ' ' not null,
  obousr8     varchar2(3) default ' ' not null,
  otbbrank    varchar2(6) default ' ' not null,
  otbbspca    varchar2(3) default ' ' not null,
  otbbcind    varchar2(3) default ' ' not null,
  otbbflup    varchar2(1) default ' ' not null,
  otbbscar    varchar2(1) default ' ' not null,
  otbbgldt    varchar2(8) default ' ' not null,
  otbbsngl    varchar2(1) default ' ' not null,
  otbbnmds    varchar2(3) default ' ' not null,
  otbbcart    varchar2(3) default ' ' not null,
  otbbsrvd    varchar2(3) default ' ' not null,
  otbbclhr    varchar2(1) default ' ' not null,
  otbbcont    varchar2(3) default ' ' not null,
  otbbtcod    varchar2(3) default ' ' not null,
  otbbpurc    varchar2(3) default ' ' not null,
  otbbbkov    varchar2(3) default ' ' not null,
  otbbbkpr    varchar2(3) default ' ' not null,
  otbbbkpm    varchar2(2) default ' ' not null,
  otbbbkba    varchar2(1) default ' ' not null,
  otbbrdat    varchar2(8) default ' ' not null,
  otbbhcp1    varchar2(10) default ' ' not null,
  otbbhcp2    varchar2(10) default ' ' not null,
  otbbhcp3    varchar2(10) default ' ' not null,
  otbbhcp4    varchar2(10) default ' ' not null,
  otbbspr1    varchar2(10) default ' ' not null,
  lf          varchar2(1) default ' ' not null
)
tablespace pas_data; 
create index outaubb1 on outaudb1
(
otbbaudd,
otbbaudt,
otbbaudp,
otbbaudr
)
tablespace pas_indx; 
create table outbb1af
(
  dobaoutn    varchar2(8) default ' ' not null,
  obasrcr     varchar2(3) default ' ' not null,
  obacomp     varchar2(3) default ' ' not null,
  obaclass    varchar2(3) default ' ' not null,
  obains      varchar2(3) default ' ' not null,
  obaattn     varchar2(3) default ' ' not null,
  obadoct     varchar2(6) default ' ' not null,
  obacomm     varchar2(25) default ' ' not null,
  otbbfund    varchar2(6) default ' ' not null,
  otbbtble    varchar2(8) default ' ' not null,
  dotbbpvi    varchar2(3) default ' ' not null,
  otbbclal    varchar2(3) default ' ' not null,
  otbbspar    varchar2(4) default ' ' not null,
  obadate     varchar2(8) default ' ' not null,
  obacat      varchar2(3) default ' ' not null,
  obaprty     varchar2(3) default ' ' not null,
  obarschd    varchar2(3) default ' ' not null,
  obbport     varchar2(2) default ' ' not null,
  obbbook     varchar2(1) default ' ' not null,
  obbctyp     varchar2(6) default ' ' not null,
  obousr1     varchar2(3) default ' ' not null,
  obousr2     varchar2(3) default ' ' not null,
  obousr3     varchar2(3) default ' ' not null,
  obousr4     varchar2(3) default ' ' not null,
  obaladmn    varchar2(8) default ' ' not null,
  otbbdept    varchar2(3) default ' ' not null,
  otbbtran    varchar2(3) default ' ' not null,
  otbblngi    varchar2(3) default ' ' not null,
  otbbtmfs    varchar2(8) default ' ' not null,
  otbbtmbo    varchar2(8) default ' ' not null,
  otbbgpfa    varchar2(20) default ' ' not null,
  otbbecra    varchar2(20) default ' ' not null,
  otbbrfgp    varchar2(10) default ' ' not null,
  otbbgppc    varchar2(10) default ' ' not null,
  otbbadcs    varchar2(10) default ' ' not null,
  otbbcitm    varchar2(5) default ' ' not null,
  otbbastm    varchar2(5) default ' ' not null,
  otbbdptm    varchar2(5) default ' ' not null,
  otbboutc    varchar2(3) default ' ' not null,
  otbbsndl    varchar2(1) default ' ' not null,
  otbbgppt    varchar2(2) default ' ' not null,
  otbbdofr    varchar2(3) default ' ' not null,
  otbboper    varchar2(4) default ' ' not null,
  obousr5     varchar2(3) default ' ' not null,
  obousr6     varchar2(3) default ' ' not null,
  obousr7     varchar2(3) default ' ' not null,
  obousr8     varchar2(3) default ' ' not null,
  otbbrank    varchar2(6) default ' ' not null,
  otbbspca    varchar2(3) default ' ' not null,
  otbbcind    varchar2(3) default ' ' not null,
  otbbflup    varchar2(1) default ' ' not null,
  otbbscar    varchar2(1) default ' ' not null,
  otbbgldt    varchar2(8) default ' ' not null,
  otbbsngl    varchar2(1) default ' ' not null,
  otbbnmds    varchar2(3) default ' ' not null,
  otbbcart    varchar2(3) default ' ' not null,
  otbbsrvd    varchar2(3) default ' ' not null,
  otbbclhr    varchar2(1) default ' ' not null,
  otbbcont    varchar2(3) default ' ' not null,
  otbbtcod    varchar2(3) default ' ' not null,
  otbbpurc    varchar2(3) default ' ' not null,
  otbbbkov    varchar2(3) default ' ' not null,
  otbbbkpr    varchar2(3) default ' ' not null,
  otbbbkpm    varchar2(2) default ' ' not null,
  otbbbkba    varchar2(1) default ' ' not null,
  otbbrdat    varchar2(8) default ' ' not null,
  otbbhcp1    varchar2(10) default ' ' not null,
  otbbhcp2    varchar2(10) default ' ' not null,
  otbbhcp3    varchar2(10) default ' ' not null,
  otbbhcp4    varchar2(10) default ' ' not null,
  otbbspr1    varchar2(10) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint outbb1a1 primary key( 
dobaoutn)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index outbb1a2 on outbb1af
(
obadate,
dobaoutn
)
  tablespace pas_indx; 
