create table outdemaf
(
  otdmurno    varchar2(8) default ' ' not null,
  otdmadat    varchar2(8) default ' ' not null,
  otdmatim    varchar2(8) default ' ' not null,
  otdmtitl    varchar2(4) default ' ' not null,
  otdmsnam    varchar2(40) default ' ' not null,
  otdmfgnm    varchar2(40) default ' ' not null,
  otdmsgnm    varchar2(40) default ' ' not null,
  otdmgend    varchar2(1) default ' ' not null,
  otdmbdat    varchar2(8) default ' ' not null,
  otdmmsta    varchar2(3) default ' ' not null,
  otdmmedn    varchar2(10) default ' ' not null,
  otdmmedr    varchar2(2) default ' ' not null,
  otdmmedv    varchar2(8) default ' ' not null,
  otdmdved    varchar2(8) default ' ' not null,
  otdmdvan    varchar2(20) default ' ' not null,
  otdmdvac    varchar2(3) default ' ' not null,
  otdmadd1    varchar2(35) default ' ' not null,
  otdmadd2    varchar2(35) default ' ' not null,
  otdmadd3    varchar2(35) default ' ' not null,
  otdmadd4    varchar2(35) default ' ' not null,
  otdmpost    varchar2(8) default ' ' not null,
  otdmtelp    varchar2(20) default ' ' not null,
  otdmtelw    varchar2(20) default ' ' not null,
  otdmtelm    varchar2(20) default ' ' not null,
  otdmemai    varchar2(80) default ' ' not null,
  otdmdecd    varchar2(8) default ' ' not null,
  otdmdety    varchar2(3) default ' ' not null,
  otdmukdd    varchar2(1) default ' ' not null,
  otdmc1ty    varchar2(3) default ' ' not null,
  otdmc1tl    varchar2(4) default ' ' not null,
  otdmc1sn    varchar2(40) default ' ' not null,
  otdmc1g1    varchar2(40) default ' ' not null,
  otdmc1g2    varchar2(40) default ' ' not null,
  otdmc1a1    varchar2(35) default ' ' not null,
  otdmc1a2    varchar2(35) default ' ' not null,
  otdmc1a3    varchar2(35) default ' ' not null,
  otdmc1a4    varchar2(35) default ' ' not null,
  otdmc1pc    varchar2(8) default ' ' not null,
  otdmc1tp    varchar2(20) default ' ' not null,
  otdmc1tb    varchar2(20) default ' ' not null,
  otdmc1tm    varchar2(20) default ' ' not null,
  otdmc1rp    varchar2(10) default ' ' not null,
  otdmc1em    varchar2(80) default ' ' not null,
  otdmc2ty    varchar2(3) default ' ' not null,
  otdmc2tl    varchar2(4) default ' ' not null,
  otdmc2sn    varchar2(40) default ' ' not null,
  otdmc2g1    varchar2(40) default ' ' not null,
  otdmc2g2    varchar2(40) default ' ' not null,
  otdmc2a1    varchar2(35) default ' ' not null,
  otdmc2a2    varchar2(35) default ' ' not null,
  otdmc2a3    varchar2(35) default ' ' not null,
  otdmc2a4    varchar2(35) default ' ' not null,
  otdmc2pc    varchar2(8) default ' ' not null,
  otdmc2tp    varchar2(20) default ' ' not null,
  otdmc2tb    varchar2(20) default ' ' not null,
  otdmc2tm    varchar2(20) default ' ' not null,
  otdmc2rp    varchar2(10) default ' ' not null,
  otdmc2em    varchar2(80) default ' ' not null,
  otdma1sn    varchar2(30) default ' ' not null,
  otdma1fg    varchar2(30) default ' ' not null,
  otdma1sg    varchar2(30) default ' ' not null,
  otdma1ge    varchar2(1) default ' ' not null,
  otdma1db    varchar2(8) default ' ' not null,
  otdma2sn    varchar2(30) default ' ' not null,
  otdma2fg    varchar2(30) default ' ' not null,
  otdma2sg    varchar2(30) default ' ' not null,
  otdma2ge    varchar2(1) default ' ' not null,
  otdma2db    varchar2(8) default ' ' not null,
  otdma3sn    varchar2(30) default ' ' not null,
  otdma3fg    varchar2(30) default ' ' not null,
  otdma3sg    varchar2(30) default ' ' not null,
  otdma3ge    varchar2(1) default ' ' not null,
  otdma3db    varchar2(8) default ' ' not null,
  otdma4sn    varchar2(30) default ' ' not null,
  otdma4fg    varchar2(30) default ' ' not null,
  otdma4sg    varchar2(30) default ' ' not null,
  otdma4ge    varchar2(1) default ' ' not null,
  otdma4db    varchar2(8) default ' ' not null,
  otdmsfed    varchar2(8) default ' ' not null,
  otdmsfno    varchar2(20) default ' ' not null,
  otdmsfct    varchar2(3) default ' ' not null,
  otdmdvct    varchar2(3) default ' ' not null,
  otdmcdat    varchar2(8) default ' ' not null,
  otdmctim    varchar2(8) default ' ' not null,
  otdmcuid    varchar2(10) default ' ' not null,
  otdmudat    varchar2(8) default ' ' not null,
  otdmutim    varchar2(8) default ' ' not null,
  otdmuuid    varchar2(10) default ' ' not null,
  otdmpmcn    varchar2(3) default ' ' not null,
  otdmpmcr    varchar2(3) default ' ' not null,
  otdmspar    varchar2(44) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint outdema1 primary key( 
otdmurno,
otdmadat,
otdmatim)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
