create table outhedaf
(
  othesite    varchar2(6) default ' ' not null,
  otheclin    varchar2(6) default ' ' not null,
  othewday    varchar2(1) default ' ' not null,
  othestrt    varchar2(5) default ' ' not null,
  otheshno    varchar2(2) default ' ' not null,
  othesdat    varchar2(8) default ' ' not null,
  othedtcc    varchar2(8) default ' ' not null,
  othecom1    varchar2(40) default ' ' not null,
  othecom2    varchar2(40) default ' ' not null,
  otheins1    varchar2(40) default ' ' not null,
  otheins2    varchar2(40) default ' ' not null,
  otheins3    varchar2(40) default ' ' not null,
  othedurn    number(3,0) default 0 not null,
  othebfin    varchar2(5) default ' ' not null,
  othesend    varchar2(5) default ' ' not null,
  otheltyp    varchar2(3) default ' ' not null,
  otheclse    varchar2(6) default ' ' not null,
  othehosp    varchar2(3) default ' ' not null,
  othelocn    varchar2(4) default ' ' not null,
  othectyp    varchar2(6) default ' ' not null,
  othecind    varchar2(3) default ' ' not null,
  othegbok    varchar2(1) default ' ' not null,
  otheadep    varchar2(3) default ' ' not null,
  othecenc    varchar2(1) default ' ' not null,
  othekdoc    varchar2(1) default ' ' not null,
  othedefd    varchar2(10) default ' ' not null,
  otheccar    varchar2(1) default ' ' not null,
  othectrn    varchar2(1) default ' ' not null,
  othendps    varchar2(3) default ' ' not null,
  othecpmi    varchar2(1) default ' ' not null,
  othecpag    varchar2(1) default ' ' not null,
  othectel    varchar2(20) default ' ' not null,
  othenmds    varchar2(3) default ' ' not null,
  othecart    varchar2(3) default ' ' not null,
  othesrvd    varchar2(3) default ' ' not null,
  otheclhr    varchar2(1) default ' ' not null,
  othemltd    varchar2(1) default ' ' not null,
  othexpul    varchar2(1) default ' ' not null,
  othemref    varchar2(1) default ' ' not null,
  othehpio    varchar2(20) default ' ' not null,
  othetcod    varchar2(3) default ' ' not null,
  othetced    varchar2(8) default ' ' not null,
  othehcli    varchar2(20) default ' ' not null,
  othehcai    varchar2(20) default ' ' not null,
  otheaopn    varchar2(1) default ' ' not null,
  otheaofr    varchar2(1) default ' ' not null,
  otheaowm    varchar2(5) default ' ' not null,
  otheaaow    varchar2(3) default ' ' not null,
  othedate    varchar2(8) default ' ' not null,
  othehcp1    varchar2(10) default ' ' not null,
  othehcp2    varchar2(10) default ' ' not null,
  othehcp3    varchar2(10) default ' ' not null,
  othehcp4    varchar2(10) default ' ' not null,
  othepcod    varchar2(9) default ' ' not null,
  othespar    varchar2(41) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint outheda1 primary key( 
othesite,
otheclin,
othewday,
othestrt,
otheshno,
othesdat)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index outheda2 on outhedaf
(
othesite,
othehosp,
otheclin,
othewday,
othestrt,
otheshno,
othesdat
)
  tablespace pas_indx; 
