create table outladaf
(
  otlaseid    varchar2(4) default ' ' not null,
  otlapcls    varchar2(1) default ' ' not null,
  otlaoutn    varchar2(8) default ' ' not null,
  otlaattd    varchar2(20) default ' ' not null,
  otlaatdt    varchar2(20) default ' ' not null,
  otlaattm    varchar2(8) default ' ' not null,
  otlabdat    varchar2(20) default ' ' not null,
  otlactry    varchar2(20) default ' ' not null,
  otlactyp    varchar2(30) default ' ' not null,
  otlacomp    varchar2(20) default ' ' not null,
  otlatday    varchar2(20) default ' ' not null,
  otlaname    varchar2(50) default ' ' not null,
  otlainsr    varchar2(20) default ' ' not null,
  otlapcat    varchar2(20) default ' ' not null,
  otlaclss    varchar2(20) default ' ' not null,
  otlaprty    varchar2(20) default ' ' not null,
  otlapsex    varchar2(6) default ' ' not null,
  otlasref    varchar2(20) default ' ' not null,
  otlaurno    varchar2(8) default ' ' not null,
  otlasite    varchar2(30) default ' ' not null,
  otlabkdt    varchar2(20) default ' ' not null,
  otlabtim    varchar2(8) default ' ' not null,
  otlaslot    varchar2(3) default ' ' not null,
  otlastim    varchar2(8) default ' ' not null,
  otlaclid    varchar2(6) default ' ' not null,
  otlacldx    varchar2(30) default ' ' not null,
  otladtit    varchar2(9) default ' ' not null,
  otladsnm    varchar2(20) default ' ' not null,
  otladgnm    varchar2(25) default ' ' not null,
  otladoct    varchar2(6) default ' ' not null,
  otlasitc    varchar2(6) default ' ' not null,
  otlaclty    varchar2(6) default ' ' not null,
  otladate    varchar2(8) default ' ' not null,
  otlastrt    varchar2(5) default ' ' not null,
  otlarshf    varchar2(1) default ' ' not null,
  otladlst    varchar2(1) default ' ' not null,
  otlaspar    varchar2(49) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint outlada1 primary key( 
otlaseid,
otlapcls,
otlaoutn,
otlaclid,
otlaclty)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
