create table outma1af
(
  omasite     varchar2(6) default ' ' not null,
  omaclin     varchar2(6) default ' ' not null,
  omatyp      varchar2(6) default ' ' not null,
  domaday     varchar2(1) default ' ' not null,
  omastart    varchar2(5) default ' ' not null,
  omafin      varchar2(5) default ' ' not null,
  omaend      varchar2(5) default ' ' not null,
  omacind     varchar2(3) default ' ' not null,
  omareg      varchar2(1) default ' ' not null,
  omakdoc     varchar2(1) default ' ' not null,
  omacom1     varchar2(40) default ' ' not null,
  omacom2     varchar2(40) default ' ' not null,
  omadurn     number(3,0) default 0 not null,
  omanewsl    number(1,0) default 0 not null,
  omaspcsl    number(1,0) default 0 not null,
  omastat     number(1,0) default 0 not null,
  omafreqm    varchar2(5) default ' ' not null,
  domaseq     varchar2(4) default ' ' not null,
  omalock     varchar2(2) default ' ' not null,
  omafreqf    number(1,0) default 0 not null,
  omafreqy    varchar2(52) default ' ' not null,
  omadate     varchar2(8) default ' ' not null,
  otmaavis    varchar2(1) default ' ' not null,
  otmastvt    varchar2(1) default ' ' not null,
  otmasupx    varchar2(1) default ' ' not null,
  otmaruse    varchar2(1) default ' ' not null,
  otmadcmb    varchar2(1) default ' ' not null,
  otmaixta    varchar2(1) default ' ' not null,
  otmadefd    varchar2(6) default ' ' not null,
  otmauatr    varchar2(1) default ' ' not null,
  otmaddna    number(2,0) default 0 not null,
  otmandrp    number(2,0) default 0 not null,
  otmalptr    number(3,0) default 0 not null,
  otmalgpd    number(3,0) default 0 not null,
  otmalptd    number(3,0) default 0 not null,
  otmabklt    number(3,0) default 0 not null,
  otmaralt    number(3,0) default 0 not null,
  otmarslt    number(3,0) default 0 not null,
  otmaclse    varchar2(6) default ' ' not null,
  otmahosp    varchar2(3) default ' ' not null,
  otmacloc    varchar2(30) default ' ' not null,
  otmawdcl    varchar2(1) default ' ' not null,
  otmaward    varchar2(3) default ' ' not null,
  otmaltyp    varchar2(3) default ' ' not null,
  otmadfsl    varchar2(1) default ' ' not null,
  otmadfgn    varchar2(1) default ' ' not null,
  otmagrps    varchar2(1) default ' ' not null,
  dotmasov    varchar2(1) default ' ' not null,
  dotmanoo    varchar2(2) default ' ' not null,
  dotmaslf    varchar2(1) default ' ' not null,
  dotmaslr    varchar2(1) default ' ' not null,
  otmasbkl    varchar2(2) default ' ' not null,
  otmasapl    varchar2(2) default ' ' not null,
  otmaspmm    varchar2(2) default ' ' not null,
  otmasgpm    varchar2(2) default ' ' not null,
  dotmalpp    varchar2(3) default ' ' not null,
  dotmasrl    varchar2(3) default ' ' not null,
  dotmanco    varchar2(1) default ' ' not null,
  otmalocn    varchar2(4) default ' ' not null,
  otmadtco    varchar2(8) default ' ' not null,
  otmadtcc    varchar2(8) default ' ' not null,
  otmains1    varchar2(40) default ' ' not null,
  otmains2    varchar2(40) default ' ' not null,
  otmains3    varchar2(40) default ' ' not null,
  otmalser    varchar2(3) default ' ' not null,
  otmaumci    varchar2(1) default ' ' not null,
  otmaprov    varchar2(10) default ' ' not null,
  otmambst    varchar2(4) default ' ' not null,
  otmaroom    varchar2(3) default ' ' not null,
  otmaledg    varchar2(2) default ' ' not null,
  otmacctr    varchar2(12) default ' ' not null,
  otmamprc    varchar2(6) default ' ' not null,
  otmambsa    varchar2(1) default ' ' not null,
  otmaldna    varchar2(3) default ' ' not null,
  otmaadep    varchar2(3) default ' ' not null,
  otmacenc    varchar2(1) default ' ' not null,
  otmaccar    varchar2(1) default ' ' not null,
  otmactrn    varchar2(1) default ' ' not null,
  otmadpsl    varchar2(3) default ' ' not null,
  otmacpmi    varchar2(1) default ' ' not null,
  otmacpag    varchar2(1) default ' ' not null,
  otmactel    varchar2(20) default ' ' not null,
  otmanmds    varchar2(3) default ' ' not null,
  otmacart    varchar2(3) default ' ' not null,
  otmasrvd    varchar2(3) default ' ' not null,
  otmaclhr    varchar2(1) default ' ' not null,
  otmamltd    varchar2(1) default ' ' not null,
  otmaxpul    varchar2(1) default ' ' not null,
  otmamref    varchar2(1) default ' ' not null,
  otmatcod    varchar2(3) default ' ' not null,
  otmahcli    varchar2(20) default ' ' not null,
  otmahcai    varchar2(20) default ' ' not null,
  otmaaopn    varchar2(1) default ' ' not null,
  otmaaofr    varchar2(1) default ' ' not null,
  otmaaowm    varchar2(5) default ' ' not null,
  otmaaowa    varchar2(3) default ' ' not null,
  otmahcp1    varchar2(10) default ' ' not null,
  otmahcp2    varchar2(10) default ' ' not null,
  otmahcp3    varchar2(10) default ' ' not null,
  otmahcp4    varchar2(10) default ' ' not null,
  otmapcod    varchar2(9) default ' ' not null,
  otmaspar    varchar2(41) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint outma1a1 primary key( 
omasite,
omaclin,
domaday,
omastart)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index outma1a2 on outma1af
(
omasite,
omatyp,
omaclin,
domaday,
omastart
)
  tablespace pas_indx; 
create unique index outma1a3 on outma1af
(
omasite,
domaseq,
omaclin,
domaday,
omastart
)
  tablespace pas_indx; 
