create table outqueaf
(
  dotqumes    varchar2(20) default ' ' not null,
  obasite     varchar2(6) default ' ' not null,
  obaclin     varchar2(6) default ' ' not null,
  obadate     varchar2(8) default ' ' not null,
  obastrt     varchar2(5) default ' ' not null,
  obaslot     number(3,0) default 0 not null,
  obatime     varchar2(5) default ' ' not null,
  obactyp     varchar2(6) default ' ' not null,
  obavisit    varchar2(3) default ' ' not null,
  obaoutno    varchar2(8) default ' ' not null,
  obasesst    varchar2(3) default ' ' not null,
  obasrcr     varchar2(3) default ' ' not null,
  obacomp     varchar2(3) default ' ' not null,
  obaclass    varchar2(3) default ' ' not null,
  obains      varchar2(3) default ' ' not null,
  obaattn     varchar2(3) default ' ' not null,
  obadoct     varchar2(6) default ' ' not null,
  obacomm     varchar2(25) default ' ' not null,
  otbbfund    varchar2(6) default ' ' not null,
  otbbtble    varchar2(8) default ' ' not null,
  otbbpvis    number(3,0) default 0 not null,
  otbbclal    varchar2(3) default ' ' not null,
  otbbspar    varchar2(4) default ' ' not null,
  obacat      varchar2(3) default ' ' not null,
  obaprty     varchar2(3) default ' ' not null,
  obarschd    varchar2(3) default ' ' not null,
  obbbook     varchar2(1) default ' ' not null,
  obousr1     varchar2(3) default ' ' not null,
  obousr2     varchar2(3) default ' ' not null,
  obousr3     varchar2(3) default ' ' not null,
  obousr4     varchar2(3) default ' ' not null,
  obaladmn    varchar2(8) default ' ' not null,
  otbbdept    varchar2(3) default ' ' not null,
  otbbtran    varchar2(3) default ' ' not null,
  otbblngi    varchar2(3) default ' ' not null,
  otbbtmfs    varchar2(8) default ' ' not null,
  otbbtmbo    varchar2(8) default ' ' not null,
  otbbgpfa    varchar2(20) default ' ' not null,
  otbbecra    varchar2(20) default ' ' not null,
  otbbrfgp    varchar2(10) default ' ' not null,
  otbbgppc    varchar2(10) default ' ' not null,
  otbbadcs    varchar2(10) default ' ' not null,
  otbbcitm    varchar2(5) default ' ' not null,
  otbbastm    varchar2(5) default ' ' not null,
  otbbdptm    varchar2(5) default ' ' not null,
  otbboutc    varchar2(3) default ' ' not null,
  otbbsndl    varchar2(1) default ' ' not null,
  otbbgppt    varchar2(2) default ' ' not null,
  otbbdofr    varchar2(3) default ' ' not null,
  obousr5     varchar2(3) default ' ' not null,
  obousr6     varchar2(3) default ' ' not null,
  obousr7     varchar2(3) default ' ' not null,
  obousr8     varchar2(3) default ' ' not null,
  otbbrank    varchar2(6) default ' ' not null,
  otbbspca    varchar2(3) default ' ' not null,
  otbbcind    varchar2(3) default ' ' not null,
  otbbflup    varchar2(1) default ' ' not null,
  otbbscar    varchar2(1) default ' ' not null,
  otbbgldt    varchar2(8) default ' ' not null,
  otbbsngl    varchar2(1) default ' ' not null,
  otbbnmds    varchar2(3) default ' ' not null,
  otbbcart    varchar2(3) default ' ' not null,
  otbbsrvd    varchar2(3) default ' ' not null,
  otbbclhr    varchar2(1) default ' ' not null,
  otbbcont    varchar2(3) default ' ' not null,
  otbbtcod    varchar2(3) default ' ' not null,
  oprssite    varchar2(6) default ' ' not null,
  oprsclin    varchar2(6) default ' ' not null,
  oprsdate    varchar2(8) default ' ' not null,
  oprsstrt    varchar2(5) default ' ' not null,
  oprsslot    number(3,0) default 0 not null,
  oprstime    varchar2(5) default ' ' not null,
  oprsoutn    varchar2(8) default ' ' not null,
  oprsreas    varchar2(3) default ' ' not null,
  oprsncli    varchar2(6) default ' ' not null,
  oprsndat    varchar2(8) default ' ' not null,
  oprsnstr    varchar2(5) default ' ' not null,
  oprsnslo    number(3,0) default 0 not null,
  oprsntim    varchar2(5) default ' ' not null,
  oprsnvis    varchar2(3) default ' ' not null,
  oprsntyp    varchar2(6) default ' ' not null,
  oprsvist    varchar2(3) default ' ' not null,
  oprsctyp    varchar2(6) default ' ' not null,
  opcnsite    varchar2(6) default ' ' not null,
  opcnclin    varchar2(6) default ' ' not null,
  opcndate    varchar2(8) default ' ' not null,
  opcnstrt    varchar2(5) default ' ' not null,
  opcnslot    number(3,0) default 0 not null,
  opcntime    varchar2(5) default ' ' not null,
  opcnoutn    varchar2(8) default ' ' not null,
  opcnreas    varchar2(3) default ' ' not null,
  opcnvtyp    varchar2(3) default ' ' not null,
  otmaltyp    varchar2(3) default ' ' not null,
  obastat     number(1,0) default 0 not null,
  otbbpurc    varchar2(3) default ' ' not null,
  otbbbkov    varchar2(3) default ' ' not null,
  otbbbkpr    varchar2(3) default ' ' not null,
  otbbbkpm    varchar2(2) default ' ' not null,
  otbbbkba    varchar2(1) default ' ' not null,
  otbbrdat    varchar2(8) default ' ' not null,
  otthstat    varchar2(3) default ' ' not null,
  otthrsit    varchar2(255) default ' ' not null,
  otthrcod    varchar2(10) default ' ' not null,
  otthradd    varchar2(512) default ' ' not null,
  otthwurl    varchar2(255) default ' ' not null,
  otthe164    varchar2(20) default ' ' not null,
  otquspar    varchar2(21) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint outquea1 primary key( 
dotqumes)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
