create table outaudxs
(
  otxsaudd    varchar2(8) default ' ' not null,
  otxsaudt    varchar2(8) default ' ' not null,
  otxsaudp    varchar2(2) default ' ' not null,
  otxsaudr    varchar2(1) default ' ' not null,
  otxsauds    number(1,0) default 0 not null,
  otxsaudo    varchar2(4) default ' ' not null,
  dotxsout    varchar2(8) default ' ' not null,
  otxsdte1    varchar2(8) default ' ' not null,
  otxsdte2    varchar2(8) default ' ' not null,
  otxsdte3    varchar2(8) default ' ' not null,
  otxsdte4    varchar2(8) default ' ' not null,
  otxsdte5    varchar2(8) default ' ' not null,
  otxsdte6    varchar2(8) default ' ' not null,
  otxsco01    varchar2(3) default ' ' not null,
  otxsco02    varchar2(3) default ' ' not null,
  otxsco03    varchar2(3) default ' ' not null,
  otxsco04    varchar2(3) default ' ' not null,
  otxsco05    varchar2(3) default ' ' not null,
  otxsco06    varchar2(3) default ' ' not null,
  otxsco07    varchar2(3) default ' ' not null,
  otxsco08    varchar2(3) default ' ' not null,
  otxsco09    varchar2(3) default ' ' not null,
  otxsco10    varchar2(3) default ' ' not null,
  otxsco11    varchar2(3) default ' ' not null,
  otxsco12    varchar2(3) default ' ' not null,
  otxsco13    varchar2(3) default ' ' not null,
  otxsco14    varchar2(3) default ' ' not null,
  otxsco15    varchar2(3) default ' ' not null,
  otxsco16    varchar2(3) default ' ' not null,
  otxsco17    varchar2(3) default ' ' not null,
  otxsco18    varchar2(3) default ' ' not null,
  otxsco19    varchar2(3) default ' ' not null,
  otxsco20    varchar2(3) default ' ' not null,
  otxsdoc1    varchar2(6) default ' ' not null,
  otxsdoc2    varchar2(6) default ' ' not null,
  otxsdoc3    varchar2(6) default ' ' not null,
  otxsamt1    number(14,2) default 0 not null,
  otxsamt2    number(14,2) default 0 not null,
  otxsdsc1    varchar2(40) default ' ' not null,
  otxsdsc2    varchar2(40) default ' ' not null,
  otxsdsc3    varchar2(40) default ' ' not null,
  otxsdsc4    varchar2(40) default ' ' not null,
  otxsdsc5    varchar2(40) default ' ' not null,
  otxsdsc6    varchar2(40) default ' ' not null,
  otxstim1    varchar2(5) default ' ' not null,
  otxstim2    varchar2(5) default ' ' not null,
  otxstim3    varchar2(5) default ' ' not null,
  otxstim4    varchar2(5) default ' ' not null,
  otxstim5    varchar2(5) default ' ' not null,
  otxstim6    varchar2(5) default ' ' not null,
  otxsspar    varchar2(6) default ' ' not null,
  lf          varchar2(1) default ' ' not null
)
tablespace pas_data; 
create index outaudxs on outaudxs
(
otxsaudd,
otxsaudt,
otxsaudp,
otxsaudr
)
tablespace pas_indx; 
create table outxscaf
(
  dotxsout    varchar2(8) default ' ' not null,
  otxsdte1    varchar2(8) default ' ' not null,
  otxsdte2    varchar2(8) default ' ' not null,
  otxsdte3    varchar2(8) default ' ' not null,
  otxsdte4    varchar2(8) default ' ' not null,
  otxsdte5    varchar2(8) default ' ' not null,
  otxsdte6    varchar2(8) default ' ' not null,
  otxsco01    varchar2(3) default ' ' not null,
  otxsco02    varchar2(3) default ' ' not null,
  otxsco03    varchar2(3) default ' ' not null,
  otxsco04    varchar2(3) default ' ' not null,
  otxsco05    varchar2(3) default ' ' not null,
  otxsco06    varchar2(3) default ' ' not null,
  otxsco07    varchar2(3) default ' ' not null,
  otxsco08    varchar2(3) default ' ' not null,
  otxsco09    varchar2(3) default ' ' not null,
  otxsco10    varchar2(3) default ' ' not null,
  otxsco11    varchar2(3) default ' ' not null,
  otxsco12    varchar2(3) default ' ' not null,
  otxsco13    varchar2(3) default ' ' not null,
  otxsco14    varchar2(3) default ' ' not null,
  otxsco15    varchar2(3) default ' ' not null,
  otxsco16    varchar2(3) default ' ' not null,
  otxsco17    varchar2(3) default ' ' not null,
  otxsco18    varchar2(3) default ' ' not null,
  otxsco19    varchar2(3) default ' ' not null,
  otxsco20    varchar2(3) default ' ' not null,
  otxsdoc1    varchar2(6) default ' ' not null,
  otxsdoc2    varchar2(6) default ' ' not null,
  otxsdoc3    varchar2(6) default ' ' not null,
  otxsamt1    number(14,2) default 0 not null,
  otxsamt2    number(14,2) default 0 not null,
  otxsdsc1    varchar2(40) default ' ' not null,
  otxsdsc2    varchar2(40) default ' ' not null,
  otxsdsc3    varchar2(40) default ' ' not null,
  otxsdsc4    varchar2(40) default ' ' not null,
  otxsdsc5    varchar2(40) default ' ' not null,
  otxsdsc6    varchar2(40) default ' ' not null,
  otxstim1    varchar2(5) default ' ' not null,
  otxstim2    varchar2(5) default ' ' not null,
  otxstim3    varchar2(5) default ' ' not null,
  otxstim4    varchar2(5) default ' ' not null,
  otxstim5    varchar2(5) default ' ' not null,
  otxstim6    varchar2(5) default ' ' not null,
  otxsspar    varchar2(6) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint outxsca1 primary key( 
dotxsout)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
