create table pataxeaf
(
  dptaxadm    varchar2(8) default ' ' not null,
  ptaxnric    varchar2(20) default ' ' not null,
  ptaxguty    number(1,0) default 0 not null,
  ptaxguin    varchar2(20) default ' ' not null,
  ptaxguit    varchar2(3) default ' ' not null,
  ptaxgunm    varchar2(45) default ' ' not null,
  ptaxgua1    varchar2(35) default ' ' not null,
  ptaxgua2    varchar2(35) default ' ' not null,
  ptaxgua3    varchar2(35) default ' ' not null,
  ptaxgua4    varchar2(35) default ' ' not null,
  ptaxgupc    varchar2(8) default ' ' not null,
  ptaxguph    varchar2(20) default ' ' not null,
  ptaxguoc    varchar2(14) default ' ' not null,
  ptaxguec    varchar2(6) default ' ' not null,
  ptaxgurl    varchar2(10) default ' ' not null,
  ptaxdfpc    varchar2(6) default ' ' not null,
  ptaxdfpi    number(14,2) default 0 not null,
  ptaxdfpt    number(14,2) default 0 not null,
  ptaxdfpf    number(14,2) default 0 not null,
  ptaxdfpo    varchar2(1) default ' ' not null,
  ptaxdfps    varchar2(10) default ' ' not null,
  ptaxdfoc    varchar2(6) default ' ' not null,
  ptaxdfoi    number(14,2) default 0 not null,
  ptaxdfot    number(14,2) default 0 not null,
  ptaxdfof    number(14,2) default 0 not null,
  ptaxdfoo    varchar2(1) default ' ' not null,
  ptaxdfos    varchar2(10) default ' ' not null,
  ptaxdfdc    varchar2(6) default ' ' not null,
  ptaxdfdi    number(14,2) default 0 not null,
  ptaxdfdt    number(14,2) default 0 not null,
  ptaxdfdf    number(14,2) default 0 not null,
  ptaxdfdo    varchar2(1) default ' ' not null,
  ptaxdfds    varchar2(10) default ' ' not null,
  ptaxdfbc    varchar2(6) default ' ' not null,
  ptaxdfbi    number(14,2) default 0 not null,
  ptaxdfbt    number(14,2) default 0 not null,
  ptaxdfbf    number(14,2) default 0 not null,
  ptaxdfbo    varchar2(1) default ' ' not null,
  ptaxdfbs    varchar2(10) default ' ' not null,
  ptaxdfac    varchar2(6) default ' ' not null,
  ptaxdfai    number(14,2) default 0 not null,
  ptaxdfat    number(14,2) default 0 not null,
  ptaxdfaf    number(14,2) default 0 not null,
  ptaxdfao    varchar2(1) default ' ' not null,
  ptaxdfas    varchar2(10) default ' ' not null,
  ptaxdcfr    varchar2(1) default ' ' not null,
  ptaxsdpm    varchar2(8) default ' ' not null,
  ptaxenpm    varchar2(8) default ' ' not null,
  ptaxcppi    number(14,2) default 0 not null,
  ptaxcppt    number(14,2) default 0 not null,
  ptaxcpoi    number(14,2) default 0 not null,
  ptaxcpot    number(14,2) default 0 not null,
  ptaxcpdi    number(14,2) default 0 not null,
  ptaxcpdt    number(14,2) default 0 not null,
  ptaxcpbi    number(14,2) default 0 not null,
  ptaxcpbt    number(14,2) default 0 not null,
  ptaxcpai    number(14,2) default 0 not null,
  ptaxcpat    number(14,2) default 0 not null,
  ptaxcpmi    number(14,2) default 0 not null,
  ptaxcpmt    number(14,2) default 0 not null,
  dptaxdam    varchar2(2) default ' ' not null,
  ptaxai1c    varchar2(2) default ' ' not null,
  ptaxai2c    varchar2(2) default ' ' not null,
  ptaxai3c    varchar2(2) default ' ' not null,
  ptaxmsai    varchar2(1) default ' ' not null,
  ptaxapdt    varchar2(8) default ' ' not null,
  ptaxtbam    number(14,2) default 0 not null,
  ptaxfndi    varchar2(9) default ' ' not null,
  ptaxotd1    varchar2(9) default ' ' not null,
  ptaxotd2    varchar2(9) default ' ' not null,
  ptaxcaij    varchar2(9) default ' ' not null,
  ptaxdtls    varchar2(8) default ' ' not null,
  ptaxnd01    number(6,0) default 0 not null,
  ptaxrt01    varchar2(6) default ' ' not null,
  ptaxbt01    varchar2(6) default ' ' not null,
  ptaxba01    number(14,2) default 0 not null,
  ptaxnd02    number(6,0) default 0 not null,
  ptaxrt02    varchar2(6) default ' ' not null,
  ptaxbt02    varchar2(6) default ' ' not null,
  ptaxba02    number(14,2) default 0 not null,
  ptaxnd03    number(6,0) default 0 not null,
  ptaxrt03    varchar2(6) default ' ' not null,
  ptaxbt03    varchar2(6) default ' ' not null,
  ptaxba03    number(14,2) default 0 not null,
  ptaxnd04    number(6,0) default 0 not null,
  ptaxrt04    varchar2(6) default ' ' not null,
  ptaxbt04    varchar2(6) default ' ' not null,
  ptaxba04    number(14,2) default 0 not null,
  ptaxnd05    number(6,0) default 0 not null,
  ptaxrt05    varchar2(6) default ' ' not null,
  ptaxbt05    varchar2(6) default ' ' not null,
  ptaxba05    number(14,2) default 0 not null,
  ptaxnd06    number(6,0) default 0 not null,
  ptaxrt06    varchar2(6) default ' ' not null,
  ptaxbt06    varchar2(6) default ' ' not null,
  ptaxba06    number(14,2) default 0 not null,
  ptaxnd07    number(6,0) default 0 not null,
  ptaxrt07    varchar2(6) default ' ' not null,
  ptaxbt07    varchar2(6) default ' ' not null,
  ptaxba07    number(14,2) default 0 not null,
  ptaxnd08    number(6,0) default 0 not null,
  ptaxrt08    varchar2(6) default ' ' not null,
  ptaxbt08    varchar2(6) default ' ' not null,
  ptaxba08    number(14,2) default 0 not null,
  ptaxnd09    number(6,0) default 0 not null,
  ptaxrt09    varchar2(6) default ' ' not null,
  ptaxbt09    varchar2(6) default ' ' not null,
  ptaxba09    number(14,2) default 0 not null,
  ptaxnd10    number(6,0) default 0 not null,
  ptaxrt10    varchar2(6) default ' ' not null,
  ptaxbt10    varchar2(6) default ' ' not null,
  ptaxba10    number(14,2) default 0 not null,
  ptaxnd11    number(6,0) default 0 not null,
  ptaxrt11    varchar2(6) default ' ' not null,
  ptaxbt11    varchar2(6) default ' ' not null,
  ptaxba11    number(14,2) default 0 not null,
  ptaxnd12    number(6,0) default 0 not null,
  ptaxrt12    varchar2(6) default ' ' not null,
  ptaxbt12    varchar2(6) default ' ' not null,
  ptaxba12    number(14,2) default 0 not null,
  ptaxnd13    number(6,0) default 0 not null,
  ptaxrt13    varchar2(6) default ' ' not null,
  ptaxbt13    varchar2(6) default ' ' not null,
  ptaxba13    number(14,2) default 0 not null,
  ptaxnd14    number(6,0) default 0 not null,
  ptaxrt14    varchar2(6) default ' ' not null,
  ptaxbt14    varchar2(6) default ' ' not null,
  ptaxba14    number(14,2) default 0 not null,
  ptaxnd15    number(6,0) default 0 not null,
  ptaxrt15    varchar2(6) default ' ' not null,
  ptaxbt15    varchar2(6) default ' ' not null,
  ptaxba15    number(14,2) default 0 not null,
  ptaxb101    varchar2(6) default ' ' not null,
  ptaxa101    number(14,2) default 0 not null,
  ptaxb102    varchar2(6) default ' ' not null,
  ptaxa102    number(14,2) default 0 not null,
  ptaxb103    varchar2(6) default ' ' not null,
  ptaxa103    number(14,2) default 0 not null,
  ptaxb104    varchar2(6) default ' ' not null,
  ptaxa104    number(14,2) default 0 not null,
  ptaxb105    varchar2(6) default ' ' not null,
  ptaxa105    number(14,2) default 0 not null,
  ptaxb106    varchar2(6) default ' ' not null,
  ptaxa106    number(14,2) default 0 not null,
  ptaxb107    varchar2(6) default ' ' not null,
  ptaxa107    number(14,2) default 0 not null,
  ptaxb108    varchar2(6) default ' ' not null,
  ptaxa108    number(14,2) default 0 not null,
  ptaxb109    varchar2(6) default ' ' not null,
  ptaxa109    number(14,2) default 0 not null,
  ptaxb110    varchar2(6) default ' ' not null,
  ptaxa110    number(14,2) default 0 not null,
  ptaxb111    varchar2(6) default ' ' not null,
  ptaxa111    number(14,2) default 0 not null,
  ptaxb112    varchar2(6) default ' ' not null,
  ptaxa112    number(14,2) default 0 not null,
  ptaxb113    varchar2(6) default ' ' not null,
  ptaxa113    number(14,2) default 0 not null,
  ptaxb114    varchar2(6) default ' ' not null,
  ptaxa114    number(14,2) default 0 not null,
  ptaxb115    varchar2(6) default ' ' not null,
  ptaxa115    number(14,2) default 0 not null,
  ptaxb116    varchar2(6) default ' ' not null,
  ptaxa116    number(14,2) default 0 not null,
  ptaxb117    varchar2(6) default ' ' not null,
  ptaxa117    number(14,2) default 0 not null,
  ptaxb118    varchar2(6) default ' ' not null,
  ptaxa118    number(14,2) default 0 not null,
  ptaxb119    varchar2(6) default ' ' not null,
  ptaxa119    number(14,2) default 0 not null,
  ptaxb120    varchar2(6) default ' ' not null,
  ptaxa120    number(14,2) default 0 not null,
  ptaxopc1    varchar2(9) default ' ' not null,
  ptaxdop1    varchar2(8) default ' ' not null,
  ptaxopc2    varchar2(9) default ' ' not null,
  ptaxdop2    varchar2(8) default ' ' not null,
  ptaxopc3    varchar2(9) default ' ' not null,
  ptaxdop3    varchar2(8) default ' ' not null,
  ptaxopc4    varchar2(9) default ' ' not null,
  ptaxdop4    varchar2(8) default ' ' not null,
  ptaxopc5    varchar2(9) default ' ' not null,
  ptaxdop5    varchar2(8) default ' ' not null,
  ptaxopc6    varchar2(9) default ' ' not null,
  ptaxdop6    varchar2(8) default ' ' not null,
  ptaxmbal    number(14,2) default 0 not null,
  ptaxmbfl    number(1,0) default 0 not null,
  ptaxspar    varchar2(14) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint pataxea1 primary key( 
dptaxadm)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index pataxea2 on pataxeaf
(
ptaxapdt,
dptaxadm
)
  tablespace pas_indx; 
create  index pataxea3 on pataxeaf
(
dptaxdam,
ptaxapdt
)
  tablespace pas_indx; 
