create table patcrdaf
(
  dptcddad    varchar2(8) default ' ' not null,
  dptcdcnr    varchar2(8) default ' ' not null,
  ptcdadte    varchar2(8) default ' ' not null,
  ptcdddte    varchar2(8) default ' ' not null,
  ptcdtmrc    varchar2(8) default ' ' not null,
  ptcdmtsp    varchar2(8) default ' ' not null,
  ptcdukpr    number(1,0) default 0 not null,
  ptcdprmm    varchar2(9) default ' ' not null,
  ptcdhtyp    varchar2(9) default ' ' not null,
  ptcdmet1    varchar2(9) default ' ' not null,
  ptcdmet2    varchar2(9) default ' ' not null,
  ptcdmet3    varchar2(9) default ' ' not null,
  ptcdlatr    varchar2(3) default ' ' not null,
  ptcdstag    varchar2(3) default ' ' not null,
  ptcdbt01    varchar2(1) default ' ' not null,
  ptcdbt02    varchar2(1) default ' ' not null,
  ptcdbt03    varchar2(1) default ' ' not null,
  ptcdbt04    varchar2(1) default ' ' not null,
  ptcdbt05    varchar2(1) default ' ' not null,
  ptcdbt06    varchar2(1) default ' ' not null,
  ptcdbt07    varchar2(1) default ' ' not null,
  ptcdbt08    varchar2(1) default ' ' not null,
  ptcdbt09    varchar2(1) default ' ' not null,
  ptcdbt10    varchar2(1) default ' ' not null,
  ptcdotdg    varchar2(50) default ' ' not null,
  ptcdrflg    number(1,0) default 0 not null,
  ptcdpath    varchar2(9) default ' ' not null,
  ptcddgpr    varchar2(1) default ' ' not null,
  ptcdfcpr    varchar2(250) default ' ' not null,
  ptcdbo01    varchar2(1) default ' ' not null,
  ptcdbo02    varchar2(1) default ' ' not null,
  ptcdbo03    varchar2(1) default ' ' not null,
  ptcdbo04    varchar2(1) default ' ' not null,
  ptcdbo05    varchar2(1) default ' ' not null,
  ptcdbo06    varchar2(1) default ' ' not null,
  ptcdbo07    varchar2(1) default ' ' not null,
  ptcdbo08    varchar2(1) default ' ' not null,
  ptcdbo09    varchar2(1) default ' ' not null,
  ptcddgot    varchar2(50) default ' ' not null,
  ptcdautp    number(1,0) default 0 not null,
  ptcdbrlw    number(5,3) default 0 not null,
  ptcdmlin    varchar2(3) default ' ' not null,
  ptcdrplb    varchar2(3) default ' ' not null,
  ptcdbtsz    number(5,3) default 0 not null,
  ptcdcklv    varchar2(3) default ' ' not null,
  ptcdglsc    number(5,3) default 0 not null,
  ptcdcomm    varchar2(50) default ' ' not null,
  ptcddtex    varchar2(8) default ' ' not null,
  ptcddtrc    varchar2(8) default ' ' not null,
  ptcdtmcr    varchar2(8) default ' ' not null,
  ptcduscr    varchar2(10) default ' ' not null,
  ptcddtup    varchar2(8) default ' ' not null,
  ptcdtmup    varchar2(8) default ' ' not null,
  ptcdusup    varchar2(10) default ' ' not null,
  ptcdbsdg    varchar2(3) default ' ' not null,
  ptcdestm    varchar2(1) default ' ' not null,
  ptcdcelt    varchar2(1) default ' ' not null,
  ptcddocc    varchar2(10) default ' ' not null,
  ptcddocn    varchar2(10) default ' ' not null,
  ptcdntdt    varchar2(8) default ' ' not null,
  ptcdsnt1    varchar2(1) default ' ' not null,
  ptcdsnt2    varchar2(1) default ' ' not null,
  ptcdsnt3    varchar2(1) default ' ' not null,
  ptcdbod1    varchar2(1) default ' ' not null,
  ptcdbod2    varchar2(1) default ' ' not null,
  ptcdbod3    varchar2(1) default ' ' not null,
  ptcdbod4    varchar2(1) default ' ' not null,
  ptcdbod5    varchar2(1) default ' ' not null,
  ptcdbol5    varchar2(10) default ' ' not null,
  ptcdbod6    varchar2(1) default ' ' not null,
  ptcdbol6    varchar2(10) default ' ' not null,
  ptcdbod7    varchar2(1) default ' ' not null,
  ptcdbol7    varchar2(10) default ' ' not null,
  ptcdgd01    varchar2(1) default ' ' not null,
  ptcdgd02    varchar2(1) default ' ' not null,
  ptcdgd03    varchar2(1) default ' ' not null,
  ptcdgd04    varchar2(1) default ' ' not null,
  ptcdgd05    varchar2(1) default ' ' not null,
  ptcdgd06    varchar2(1) default ' ' not null,
  ptcdgd07    varchar2(1) default ' ' not null,
  ptcdgd08    varchar2(1) default ' ' not null,
  ptcdgd09    varchar2(1) default ' ' not null,
  ptcdplod    varchar2(25) default ' ' not null,
  ptcdcod1    varchar2(35) default ' ' not null,
  ptcdcod2    varchar2(35) default ' ' not null,
  ptcdcsgt    varchar2(10) default ' ' not null,
  ptcdcsgn    varchar2(10) default ' ' not null,
  ptcdcsgm    varchar2(10) default ' ' not null,
  ptcdcssg    varchar2(10) default ' ' not null,
  ptcdcscm    varchar2(10) default ' ' not null,
  ptcdtnon    varchar2(1) default ' ' not null,
  ptcdtsur    varchar2(1) default ' ' not null,
  ptcdtsdt    varchar2(8) default ' ' not null,
  ptcdtrad    varchar2(1) default ' ' not null,
  ptcdtrdt    varchar2(8) default ' ' not null,
  ptcdtchm    varchar2(1) default ' ' not null,
  ptcdtcdt    varchar2(8) default ' ' not null,
  ptcdthor    varchar2(1) default ' ' not null,
  ptcdthdt    varchar2(8) default ' ' not null,
  ptcdtbio    varchar2(1) default ' ' not null,
  ptcdtbdt    varchar2(8) default ' ' not null,
  ptcdrldt    varchar2(8) default ' ' not null,
  ptcdndcl    varchar2(35) default ' ' not null,
  ptcdtsab    varchar2(1) default ' ' not null,
  ptcdtoth    varchar2(1) default ' ' not null,
  ptcdthos    varchar2(35) default ' ' not null,
  ptcdrst1    varchar2(1) default ' ' not null,
  ptcdrst2    varchar2(1) default ' ' not null,
  ptcdrst3    varchar2(1) default ' ' not null,
  ptcdrst4    varchar2(1) default ' ' not null,
  ptcdrst5    varchar2(1) default ' ' not null,
  ptcdsurb    varchar2(45) default ' ' not null,
  ptcdstte    varchar2(7) default ' ' not null,
  ptcdpost    varchar2(8) default ' ' not null,
  ptcdmet4    varchar2(9) default ' ' not null,
  ptcdmet5    varchar2(9) default ' ' not null,
  ptcdmet6    varchar2(9) default ' ' not null,
  ptcdecog    varchar2(3) default ' ' not null,
  ptcdradi    varchar2(3) default ' ' not null,
  ptcdsyst    varchar2(3) default ' ' not null,
  ptcdscfl    varchar2(1) default ' ' not null,
  ptcdcssy    varchar2(3) default ' ' not null,
  ptcdbdia    varchar2(3) default ' ' not null,
  ptcdspar    varchar2(50) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint patcrda1 primary key( 
dptcddad,
ptcdprmm,
dptcdcnr)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index patcrda2 on patcrdaf
(
ptcddtex,
dptcddad,
ptcdprmm,
dptcdcnr
)
  tablespace pas_indx; 
create unique index patcrda3 on patcrdaf
(
ptcddtrc,
ptcdtmcr,
dptcddad,
ptcdprmm,
dptcdcnr
)
  tablespace pas_indx; 
create unique index patcrda4 on patcrdaf
(
ptcddtup,
ptcdtmup,
dptcddad,
ptcdprmm,
dptcdcnr
)
  tablespace pas_indx; 
