create table patdo1af
(
  dcode       varchar2(6) default ' ' not null,
  dtitl       varchar2(9) default ' ' not null,
  dgname      varchar2(25) default ' ' not null,
  dsname      varchar2(20) default ' ' not null,
  drtype      varchar2(3) default ' ' not null,
  drname      varchar2(25) default ' ' not null,
  dsadd1      varchar2(35) default ' ' not null,
  dsadd2      varchar2(35) default ' ' not null,
  dsadd3      varchar2(35) default ' ' not null,
  dsadd4      varchar2(35) default ' ' not null,
  dspost      varchar2(8) default ' ' not null,
  ptdoseml    varchar2(80) default ' ' not null,
  dteles      varchar2(20) default ' ' not null,
  dtelep      varchar2(20) default ' ' not null,
  dpager      varchar2(20) default ' ' not null,
  dassoc1     varchar2(25) default ' ' not null,
  dassoc2     varchar2(25) default ' ' not null,
  dassoc3     varchar2(25) default ' ' not null,
  dassoc4     varchar2(25) default ' ' not null,
  dassoc5     varchar2(25) default ' ' not null,
  dprov       varchar2(10) default ' ' not null,
  dteleh      varchar2(20) default ' ' not null,
  dhadd1      varchar2(35) default ' ' not null,
  dhadd2      varchar2(35) default ' ' not null,
  dhadd3      varchar2(35) default ' ' not null,
  dhadd4      varchar2(35) default ' ' not null,
  dhpost      varchar2(8) default ' ' not null,
  ptdoheml    varchar2(80) default ' ' not null,
  dafirst     varchar2(8) default ' ' not null,
  dalast      varchar2(8) default ' ' not null,
  dayears     number(2,0) default 0 not null,
  daccred     varchar2(3) default ' ' not null,
  drtype2     varchar2(3) default ' ' not null,
  drtype3     varchar2(3) default ' ' not null,
  drtype4     varchar2(3) default ' ' not null,
  drtype5     varchar2(3) default ' ' not null,
  dfspare     varchar2(2) default ' ' not null,
  dbirth      varchar2(8) default ' ' not null,
  dhcscod     number(3,0) default 0 not null,
  dalevel     varchar2(3) default ' ' not null,
  drstat      number(1,0) default 0 not null,
  ptdofaxn    varchar2(12) default ' ' not null,
  ptdohfax    varchar2(12) default ' ' not null,
  ptdomobl    varchar2(12) default ' ' not null,
  ptdoglcc    varchar2(5) default ' ' not null,
  ptdowhdp    varchar2(6) default ' ' not null,
  ptdomreg    varchar2(10) default ' ' not null,
  ptdonhsn    varchar2(10) default ' ' not null,
  dlupddte    varchar2(8) default ' ' not null,
  dlupdtme    varchar2(8) default ' ' not null,
  ptdoudf1    varchar2(3) default ' ' not null,
  ptdoudf2    varchar2(3) default ' ' not null,
  ptdoudf3    varchar2(3) default ' ' not null,
  ptdoudf4    varchar2(3) default ' ' not null,
  ptdoudf5    varchar2(3) default ' ' not null,
  ptdoinsc    varchar2(6) default ' ' not null,
  ptdoinsn    varchar2(20) default ' ' not null,
  ptdoinsf    varchar2(8) default ' ' not null,
  ptdoinst    varchar2(8) default ' ' not null,
  ptdoregn    varchar2(20) default ' ' not null,
  ptdoregf    varchar2(8) default ' ' not null,
  ptdoregt    varchar2(8) default ' ' not null,
  ptdovisa    varchar2(8) default ' ' not null,
  ptdocomt    varchar2(3) default ' ' not null,
  ptdopref    varchar2(30) default ' ' not null,
  ptdoabnn    varchar2(11) default ' ' not null,
  ptdodina    varchar2(8) default ' ' not null,
  ptdodact    varchar2(8) default ' ' not null,
  ptdodaco    varchar2(8) default ' ' not null,
  ptdopro2    varchar2(10) default ' ' not null,
  ptdopro3    varchar2(10) default ' ' not null,
  ptdopro4    varchar2(10) default ' ' not null,
  ptdopro5    varchar2(10) default ' ' not null,
  ptdosdat    varchar2(8) default ' ' not null,
  ptdoedat    varchar2(8) default ' ' not null,
  ptdoaupd    varchar2(1) default ' ' not null,
  ptdohoss    varchar2(1) default ' ' not null,
  ptdoexml    varchar2(1) default ' ' not null,
  ptdodeac    varchar2(8) default ' ' not null,
  ptdoahc1    varchar2(3) default ' ' not null,
  ptdoahc2    varchar2(3) default ' ' not null,
  ptdoahc3    varchar2(3) default ' ' not null,
  daspare     varchar2(50) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint patdo1a1 primary key( 
dcode)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index patdo1a2 on patdo1af
(
dsname,
dcode
)
  tablespace pas_indx; 
create unique index patdo1a3 on patdo1af
(
dalevel,
dsname,
dcode
)
  tablespace pas_indx; 
