create table patex1nn
(
  dptxaadm    varchar2(8) default ' ' not null,
  ptxaadat    varchar2(8) default ' ' not null,
  ptxaddat    varchar2(8) default ' ' not null,
  ptxadayc    number(1,0) default 0 not null,
  ptxaplos    number(4,0) default 0 not null,
  ptxaalos    number(4,0) default 0 not null,
  ptxaplve    number(4,0) default 0 not null,
  ptxaalve    number(4,0) default 0 not null,
  ptxaawrd    varchar2(3) default ' ' not null,
  ptxaabed    varchar2(3) default ' ' not null,
  ptxaswrd    varchar2(3) default ' ' not null,
  ptxasbed    varchar2(3) default ' ' not null,
  ptxadwrd    varchar2(3) default ' ' not null,
  ptxadbed    varchar2(3) default ' ' not null,
  ptxaatyp    varchar2(3) default ' ' not null,
  ptxastyp    varchar2(3) default ' ' not null,
  ptxadtyp    varchar2(3) default ' ' not null,
  ptxasex     varchar2(1) default ' ' not null,
  ptxapost    varchar2(8) default ' ' not null,
  ptxamlga    varchar2(4) default ' ' not null,
  ptxaplga    varchar2(4) default ' ' not null,
  ptxarelg    varchar2(3) default ' ' not null,
  ptxacont    varchar2(3) default ' ' not null,
  ptxaresi    varchar2(3) default ' ' not null,
  ptxamstt    varchar2(3) default ' ' not null,
  ptxaaagd    number(5,0) default 0 not null,
  ptxaaagm    number(4,0) default 0 not null,
  ptxaaagy    number(3,0) default 0 not null,
  ptxasagd    number(5,0) default 0 not null,
  ptxasagm    number(4,0) default 0 not null,
  ptxasagy    number(3,0) default 0 not null,
  ptxadagd    number(5,0) default 0 not null,
  ptxadagm    number(4,0) default 0 not null,
  ptxadagy    number(3,0) default 0 not null,
  ptxapus1    varchar2(3) default ' ' not null,
  ptxapus2    varchar2(3) default ' ' not null,
  ptxapus3    varchar2(3) default ' ' not null,
  ptxapus4    varchar2(3) default ' ' not null,
  ptxapus5    varchar2(3) default ' ' not null,
  ptxapus6    varchar2(3) default ' ' not null,
  ptxapyn1    varchar2(1) default ' ' not null,
  ptxapyn2    varchar2(1) default ' ' not null,
  ptxapyn3    varchar2(1) default ' ' not null,
  ptxadcse    varchar2(1) default ' ' not null,
  ptxaddth    varchar2(8) default ' ' not null,
  ptxabadd    varchar2(1) default ' ' not null,
  ptxaaadc    varchar2(6) default ' ' not null,
  ptxaaadt    varchar2(3) default ' ' not null,
  ptxasadc    varchar2(6) default ' ' not null,
  ptxasadt    varchar2(3) default ' ' not null,
  ptxadadc    varchar2(6) default ' ' not null,
  ptxadadt    varchar2(3) default ' ' not null,
  ptxaardc    varchar2(6) default ' ' not null,
  ptxaardt    varchar2(3) default ' ' not null,
  ptxaatdc    varchar2(6) default ' ' not null,
  ptxaatdt    varchar2(6) default ' ' not null,
  ptxasour    varchar2(3) default ' ' not null,
  ptxaahos    varchar2(5) default ' ' not null,
  ptxaclmc    varchar2(3) default ' ' not null,
  ptxadiet    varchar2(3) default ' ' not null,
  ptxaacls    varchar2(3) default ' ' not null,
  ptxaacre    varchar2(3) default ' ' not null,
  ptxascre    varchar2(3) default ' ' not null,
  ptxadcre    varchar2(3) default ' ' not null,
  ptxaadpt    varchar2(3) default ' ' not null,
  ptxasdpt    varchar2(3) default ' ' not null,
  ptxaddpt    varchar2(3) default ' ' not null,
  ptxafund    varchar2(6) default ' ' not null,
  ptxaftbl    varchar2(8) default ' ' not null,
  ptxaaus1    varchar2(3) default ' ' not null,
  ptxaaus2    varchar2(3) default ' ' not null,
  ptxaaus3    varchar2(3) default ' ' not null,
  ptxaaus4    varchar2(3) default ' ' not null,
  ptxaaus5    varchar2(3) default ' ' not null,
  ptxaaus6    varchar2(3) default ' ' not null,
  ptxaaus7    varchar2(3) default ' ' not null,
  ptxaadia    varchar2(9) default ' ' not null,
  ptxaddia    varchar2(9) default ' ' not null,
  ptxadstt    varchar2(3) default ' ' not null,
  ptxaddst    varchar2(3) default ' ' not null,
  ptxadhos    varchar2(5) default ' ' not null,
  ptxadus1    varchar2(3) default ' ' not null,
  ptxadus2    varchar2(3) default ' ' not null,
  ptxadus3    varchar2(3) default ' ' not null,
  ptxadus4    varchar2(3) default ' ' not null,
  ptxadus5    varchar2(3) default ' ' not null,
  ptxadrgc    varchar2(6) default ' ' not null,
  ptxamdcc    varchar2(5) default ' ' not null,
  ptxaopid    varchar2(10) default ' ' not null,
  ptxarloc    varchar2(3) default ' ' not null,
  ptxaabrg    varchar2(3) default ' ' not null,
  ptxacadm    varchar2(3) default ' ' not null,
  ptxairad    varchar2(3) default ' ' not null,
  ptxaidus    varchar2(3) default ' ' not null,
  ptxamhls    varchar2(3) default ' ' not null,
  ptxaasut    varchar2(3) default ' ' not null,
  ptxaelps    varchar2(3) default ' ' not null,
  ptxaempl    varchar2(3) default ' ' not null,
  ptxaread    varchar2(3) default ' ' not null,
  ptxaudin    varchar2(3) default ' ' not null,
  ptxaurea    varchar2(3) default ' ' not null,
  ptxauvth    varchar2(3) default ' ' not null,
  ptxaplan    varchar2(3) default ' ' not null,
  ptxaspre    varchar2(19) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint patex1a1 primary key( 
dptxaadm)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
