create table patelgaf
(
  ptelvisn    varchar2(8) default ' ' not null,
  ptelfinc    varchar2(1) default ' ' not null,
  ptelxcss    number(14,2) default 0 not null,
  ptelppri    number(14,2) default 0 not null,
  ptelpsha    number(14,2) default 0 not null,
  ptelpthe    number(14,2) default 0 not null,
  ptelxcls    varchar2(1) default ' ' not null,
  ptelcmpl    varchar2(1) default ' ' not null,
  ptelcovr    varchar2(1) default ' ' not null,
  ptelqexs    varchar2(1) default ' ' not null,
  ptelqacc    varchar2(1) default ' ' not null,
  ptelcdon    varchar2(3) default ' ' not null,
  ptelrdat    varchar2(8) default ' ' not null,
  ptelspea    varchar2(1) default ' ' not null,
  ptelhfrn    varchar2(20) default ' ' not null,
  ptelpthf    varchar2(25) default ' ' not null,
  ptelxcmn    varchar2(100) default ' ' not null,
  ptelpput    number(7,2) default 0 not null,
  ptelpsut    number(7,2) default 0 not null,
  ptelptut    number(7,2) default 0 not null,
  ptelecmn    varchar2(200) default ' ' not null,
  ptelhstm    varchar2(25) default ' ' not null,
  ptelhfpn    varchar2(80) default ' ' not null,
  ptelpsdy    number(14,2) default 0 not null,
  ptelpsdu    number(7,2) default 0 not null,
  ptelphsp    number(14,2) default 0 not null,
  ptelphsu    number(7,2) default 0 not null,
  ptelafrm    varchar2(1) default ' ' not null,
  ptelqlps    varchar2(1) default ' ' not null,
  ptelmdes    varchar2(70) default ' ' not null,
  ptelmamt    number(14,2) default 0 not null,
  pteleadm    varchar2(1) default ' ' not null,
  ptelcpcp    varchar2(1) default ' ' not null,
  ptelcscp    varchar2(1) default ' ' not null,
  ptelcdcp    varchar2(1) default ' ' not null,
  ptelchcp    varchar2(1) default ' ' not null,
  ptelctcp    varchar2(1) default ' ' not null,
  pteltoop    number(14,2) default 0 not null,
  ptelxcsd    number(14,2) default 0 not null,
  ptelpccu    number(14,2) default 0 not null,
  ptelcccu    varchar2(1) default ' ' not null,
  ptelpcut    number(7,2) default 0 not null,
  ptelcmxc    varchar2(9) default ' ' not null,
  ptelecls    varchar2(3) default ' ' not null,
  ptelspar    varchar2(88) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint patelga1 primary key( 
ptelvisn)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
