create table patfapaf
(
  ptfpclai    varchar2(3) default ' ' not null,
  ptfpacpl    varchar2(3) default ' ' not null,
  ptfpfac1    varchar2(3) default ' ' not null,
  ptfpdfa1    varchar2(3) default ' ' not null,
  ptfpplt1    varchar2(1) default ' ' not null,
  ptfppin1    varchar2(1) default ' ' not null,
  ptfpocg1    varchar2(3) default ' ' not null,
  ptfpfac2    varchar2(3) default ' ' not null,
  ptfpdfa2    varchar2(3) default ' ' not null,
  ptfpplt2    varchar2(1) default ' ' not null,
  ptfppin2    varchar2(1) default ' ' not null,
  ptfpocg2    varchar2(3) default ' ' not null,
  ptfpfac3    varchar2(3) default ' ' not null,
  ptfpdfa3    varchar2(3) default ' ' not null,
  ptfpplt3    varchar2(1) default ' ' not null,
  ptfppin3    varchar2(1) default ' ' not null,
  ptfpocg3    varchar2(3) default ' ' not null,
  ptfpfac4    varchar2(3) default ' ' not null,
  ptfpdfa4    varchar2(3) default ' ' not null,
  ptfpplt4    varchar2(1) default ' ' not null,
  ptfppin4    varchar2(1) default ' ' not null,
  ptfpocg4    varchar2(3) default ' ' not null,
  ptfpfac5    varchar2(3) default ' ' not null,
  ptfpdfa5    varchar2(3) default ' ' not null,
  ptfpplt5    varchar2(1) default ' ' not null,
  ptfppin5    varchar2(1) default ' ' not null,
  ptfpocg5    varchar2(3) default ' ' not null,
  ptfpfac6    varchar2(3) default ' ' not null,
  ptfpdfa6    varchar2(3) default ' ' not null,
  ptfpplt6    varchar2(1) default ' ' not null,
  ptfppin6    varchar2(1) default ' ' not null,
  ptfpocg6    varchar2(3) default ' ' not null,
  ptfpfac7    varchar2(3) default ' ' not null,
  ptfpdfa7    varchar2(3) default ' ' not null,
  ptfpplt7    varchar2(1) default ' ' not null,
  ptfppin7    varchar2(1) default ' ' not null,
  ptfpocg7    varchar2(3) default ' ' not null,
  ptfpfac8    varchar2(3) default ' ' not null,
  ptfpdfa8    varchar2(3) default ' ' not null,
  ptfpplt8    varchar2(1) default ' ' not null,
  ptfppin8    varchar2(1) default ' ' not null,
  ptfpocg8    varchar2(3) default ' ' not null,
  ptfpfac9    varchar2(3) default ' ' not null,
  ptfpdfa9    varchar2(3) default ' ' not null,
  ptfpplt9    varchar2(1) default ' ' not null,
  ptfppin9    varchar2(1) default ' ' not null,
  ptfpocg9    varchar2(3) default ' ' not null,
  ptfpfac0    varchar2(3) default ' ' not null,
  ptfpdfa0    varchar2(3) default ' ' not null,
  ptfpplt0    varchar2(1) default ' ' not null,
  ptfppin0    varchar2(1) default ' ' not null,
  ptfpocg0    varchar2(3) default ' ' not null,
  ptfpspar    varchar2(77) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint patfapa1 primary key( 
ptfpclai,
ptfpacpl)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
