create table patfimaf
(
  ptfivisn    varchar2(8) default ' ' not null,
  ptfidate    varchar2(8) default ' ' not null,
  ptfitime    varchar2(8) default ' ' not null,
  ptfitype    varchar2(1) default ' ' not null,
  ptfieats    number(2,0) default 0 not null,
  ptfieatg    number(2,0) default 0 not null,
  ptfieatc    varchar2(50) default ' ' not null,
  ptfigrms    number(2,0) default 0 not null,
  ptfigrmg    number(2,0) default 0 not null,
  ptfigrmc    varchar2(50) default ' ' not null,
  ptfibths    number(2,0) default 0 not null,
  ptfibthg    number(2,0) default 0 not null,
  ptfibthc    varchar2(50) default ' ' not null,
  ptfiupbs    number(2,0) default 0 not null,
  ptfiupbg    number(2,0) default 0 not null,
  ptfiupbc    varchar2(50) default ' ' not null,
  ptfilwbs    number(2,0) default 0 not null,
  ptfilwbg    number(2,0) default 0 not null,
  ptfilwbc    varchar2(50) default ' ' not null,
  ptfitlts    number(2,0) default 0 not null,
  ptfitltg    number(2,0) default 0 not null,
  ptfitltc    varchar2(50) default ' ' not null,
  ptfiblms    number(2,0) default 0 not null,
  ptfiblmg    number(2,0) default 0 not null,
  ptfiblmc    varchar2(50) default ' ' not null,
  ptfibwms    number(2,0) default 0 not null,
  ptfibwmg    number(2,0) default 0 not null,
  ptfibwmc    varchar2(50) default ' ' not null,
  ptfitbds    number(2,0) default 0 not null,
  ptfitbdg    number(2,0) default 0 not null,
  ptfitbdc    varchar2(50) default ' ' not null,
  ptfittls    number(2,0) default 0 not null,
  ptfittlg    number(2,0) default 0 not null,
  ptfittlc    varchar2(50) default ' ' not null,
  ptfitbts    number(2,0) default 0 not null,
  ptfitbtg    number(2,0) default 0 not null,
  ptfitbtc    varchar2(50) default ' ' not null,
  ptfilocd    varchar2(3) default ' ' not null,
  ptfilocs    number(2,0) default 0 not null,
  ptfilocg    number(2,0) default 0 not null,
  ptfilocc    varchar2(50) default ' ' not null,
  ptfistrs    number(2,0) default 0 not null,
  ptfistrg    number(2,0) default 0 not null,
  ptfistrc    varchar2(50) default ' ' not null,
  ptficocd    varchar2(3) default ' ' not null,
  ptficoms    number(2,0) default 0 not null,
  ptficomg    number(2,0) default 0 not null,
  ptficomc    varchar2(50) default ' ' not null,
  ptfiexcd    varchar2(3) default ' ' not null,
  ptfiexps    number(2,0) default 0 not null,
  ptfiexpg    number(2,0) default 0 not null,
  ptfiexpc    varchar2(50) default ' ' not null,
  ptfiscis    number(2,0) default 0 not null,
  ptfiscig    number(2,0) default 0 not null,
  ptfiscic    varchar2(50) default ' ' not null,
  ptfiprbs    number(2,0) default 0 not null,
  ptfiprbg    number(2,0) default 0 not null,
  ptfiprbc    varchar2(50) default ' ' not null,
  ptfimems    number(2,0) default 0 not null,
  ptfimemg    number(2,0) default 0 not null,
  ptfimemc    varchar2(50) default ' ' not null,
  ptfiases    varchar2(1) default ' ' not null,
  ptfiascd    varchar2(10) default ' ' not null,
  ptfiasdn    varchar2(3) default ' ' not null,
  ptfinscd    varchar2(10) default ' ' not null,
  ptfinsid    varchar2(10) default ' ' not null,
  ptfinsdt    varchar2(8) default ' ' not null,
  ptfinstm    varchar2(8) default ' ' not null,
  ptfiphcd    varchar2(10) default ' ' not null,
  ptfiphdt    varchar2(8) default ' ' not null,
  ptfiphtm    varchar2(8) default ' ' not null,
  ptfiotcd    varchar2(10) default ' ' not null,
  ptfiotdt    varchar2(8) default ' ' not null,
  ptfiottm    varchar2(8) default ' ' not null,
  ptfidelt    varchar2(1) default ' ' not null,
  ptficuid    varchar2(10) default ' ' not null,
  ptficdat    varchar2(8) default ' ' not null,
  ptfictim    varchar2(8) default ' ' not null,
  ptfiuuid    varchar2(10) default ' ' not null,
  ptfiudat    varchar2(8) default ' ' not null,
  ptfiutim    varchar2(8) default ' ' not null,
  ptfiduid    varchar2(10) default ' ' not null,
  ptfiddat    varchar2(8) default ' ' not null,
  ptfidtim    varchar2(8) default ' ' not null,
  ptfiimpc    varchar2(7) default ' ' not null,
  ptficplt    varchar2(1) default ' ' not null,
  ptfifuid    varchar2(10) default ' ' not null,
  ptfifdte    varchar2(8) default ' ' not null,
  ptfiftme    varchar2(8) default ' ' not null,
  ptfidres    varchar2(3) default ' ' not null,
  ptfispar    varchar2(50) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint patfima1 primary key( 
ptfivisn,
ptfidate,
ptfitime)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
