create table pathspaf
(
  pthshosp    varchar2(3) default ' ' not null,
  pthsname    varchar2(50) default ' ' not null,
  pthsadd1    varchar2(35) default ' ' not null,
  pthsadd2    varchar2(35) default ' ' not null,
  pthsadd3    varchar2(35) default ' ' not null,
  pthsadd4    varchar2(35) default ' ' not null,
  pthspcod    varchar2(8) default ' ' not null,
  pthstele    varchar2(20) default ' ' not null,
  pthsfaxn    varchar2(20) default ' ' not null,
  pthsunit    varchar2(5) default ' ' not null,
  pthshdpc    varchar2(8) default ' ' not null,
  pthsmrpr    varchar2(6) default ' ' not null,
  pthspact    varchar2(12) default ' ' not null,
  pthshsno    varchar2(2) default ' ' not null,
  pthspmbs    varchar2(1) default ' ' not null,
  pthstfee    varchar2(1) default ' ' not null,
  pthshloc    varchar2(4) default ' ' not null,
  pthsrcty    varchar2(3) default ' ' not null,
  pthsvolm    varchar2(2) default ' ' not null,
  pthsstat    varchar2(3) default ' ' not null,
  pthsdclm    varchar2(3) default ' ' not null,
  pthsappr    varchar2(10) default ' ' not null,
  pthsufms    varchar2(1) default ' ' not null,
  pthsabnn    varchar2(11) default ' ' not null,
  pthshsid    varchar2(5) default ' ' not null,
  pthshcen    varchar2(3) default ' ' not null,
  pthsptin    varchar2(1) default ' ' not null,
  pthsspid    varchar2(1) default ' ' not null,
  pthsedip    varchar2(2) default ' ' not null,
  pthsorid    varchar2(8) default ' ' not null,
  pthsmorg    varchar2(1) default ' ' not null,
  pthschot    varchar2(1) default ' ' not null,
  pthschod    varchar2(1) default ' ' not null,
  pthshost    varchar2(1) default ' ' not null,
  pthsudva    varchar2(1) default ' ' not null,
  pthslocn    varchar2(8) default ' ' not null,
  pthserre    varchar2(3) default ' ' not null,
  pthsercd    varchar2(6) default ' ' not null,
  pthserca    varchar2(15) default ' ' not null,
  pthscfcd    varchar2(6) default ' ' not null,
  pthsemal    varchar2(80) default ' ' not null,
  pthsersr    varchar2(3) default ' ' not null,
  pthssnam    varchar2(10) default ' ' not null,
  pthstord    varchar2(1) default ' ' not null,
  pthshhos    varchar2(3) default ' ' not null,
  pthscrsr    varchar2(3) default ' ' not null,
  pthsrcop    varchar2(10) default ' ' not null,
  pthshbid    varchar2(4) default ' ' not null,
  pthsdcdt    varchar2(4) default ' ' not null,
  pthshpio    varchar2(20) default ' ' not null,
  pthscfst    varchar2(3) default ' ' not null,
  pthshdhb    varchar2(3) default ' ' not null,
  pthsagnc    varchar2(3) default ' ' not null,
  pthsucrg    varchar2(1) default ' ' not null,
  pthshsst    varchar2(1) default ' ' not null,
  pthsactr    varchar2(10) default ' ' not null,
  pthsagel    varchar2(3) default ' ' not null,
  pthsageh    varchar2(3) default ' ' not null,
  pthsmaph    varchar2(2) default ' ' not null,
  pthsspar    varchar2(16) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint pathspa1 primary key( 
pthshosp)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
