create table pathtraf
(
  pthtadmn    varchar2(8) default ' ' not null,
  pthttrns    varchar2(6) default ' ' not null,
  pthttdeb    varchar2(1) default ' ' not null,
  pthtdcod    varchar2(8) default ' ' not null,
  pthtamtt    number(14,2) default 0 not null,
  pthtamtg    number(14,2) default 0 not null,
  pthtamth    number(14,2) default 0 not null,
  pthtamti    number(14,2) default 0 not null,
  pthtamtp    number(14,2) default 0 not null,
  pthtfcen    varchar2(2) default ' ' not null,
  pthtfyer    varchar2(2) default ' ' not null,
  pthtfmon    varchar2(2) default ' ' not null,
  pthtfday    varchar2(2) default ' ' not null,
  pthttcen    varchar2(2) default ' ' not null,
  pthttyer    number(2,0) default 0 not null,
  pthttmon    number(2,0) default 0 not null,
  pthttday    number(2,0) default 0 not null,
  pthtttyp    varchar2(2) default ' ' not null,
  pthtitem    varchar2(9) default ' ' not null,
  pthttref    varchar2(8) default ' ' not null,
  pthtpayt    number(1,0) default 0 not null,
  pthtrcpt    varchar2(12) default ' ' not null,
  pthtdesc    varchar2(30) default ' ' not null,
  pthtinvp    number(1,0) default 0 not null,
  pthtrect    varchar2(1) default ' ' not null,
  pthtnday    number(4,0) default 0 not null,
  pthtclmd    number(1,0) default 0 not null,
  pthtrbat    number(14,2) default 0 not null,
  pthtdoct    varchar2(6) default ' ' not null,
  pthtserv    number(5,0) default 0 not null,
  pthtdoco    varchar2(6) default ' ' not null,
  pthtpinv    varchar2(8) default ' ' not null,
  pthtptrn    varchar2(6) default ' ' not null,
  pthtsess    varchar2(2) default ' ' not null,
  pthtmisg    varchar2(3) default ' ' not null,
  pthtdept    varchar2(3) default ' ' not null,
  pthtward    varchar2(3) default ' ' not null,
  pthtclmt    varchar2(3) default ' ' not null,
  pthtadmt    varchar2(3) default ' ' not null,
  pthtbtch    varchar2(8) default ' ' not null,
  pthtninv    number(1,0) default 0 not null,
  pthtlspt    number(14,2) default 0 not null,
  pthtlsrb    number(14,2) default 0 not null,
  pthtdtyp    number(1,0) default 0 not null,
  pthtdes2    varchar2(35) default ' ' not null,
  pthtepsd    number(1,0) default 0 not null,
  pthttccu    number(1,0) default 0 not null,
  pthtgsta    number(1,0) default 0 not null,
  pthtgstc    varchar2(6) default ' ' not null,
  pthtgstm    number(14,2) default 0 not null,
  pthteffd    varchar2(8) default ' ' not null,
  pthtgstl    number(14,2) default 0 not null,
  pthtttim    varchar2(8) default ' ' not null,
  pthtcrst    varchar2(1) default ' ' not null,
  pthtuniq    varchar2(10) default ' ' not null,
  pthtbtyp    varchar2(3) default ' ' not null,
  pthtcntr    varchar2(6) default ' ' not null,
  pthtsunq    varchar2(3) default ' ' not null,
  pthtbatc    varchar2(16) default ' ' not null,
  pthtadpt    number(14,2) default 0 not null,
  pthtadrb    number(14,2) default 0 not null,
  pthtcnid    varchar2(6) default ' ' not null,
  pthtlsd1    varchar2(30) default ' ' not null,
  pthtlsd2    varchar2(35) default ' ' not null,
  pthttmno    varchar2(1) default ' ' not null,
  pthtpmbs    varchar2(3) default ' ' not null,
  pthtpcod    varchar2(3) default ' ' not null,
  pthtspar    varchar2(100) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint pathtra1 primary key( 
pthtadmn,
pthttref,
pthttrns)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index pathtra2 on pathtraf
(
pthtadmn,
pthtpinv,
pthtptrn,
pthttref,
pthttrns
)
  tablespace pas_indx; 
