create table patinpaf
(
  dptipadm    varchar2(8) default ' ' not null,
  ptipurno    varchar2(8) default ' ' not null,
  ptiprtyp    varchar2(2) default ' ' not null,
  ptipclam    varchar2(3) default ' ' not null,
  ptiphfnd    varchar2(6) default ' ' not null,
  ptipftbl    varchar2(8) default ' ' not null,
  ptipatyp    varchar2(3) default ' ' not null,
  ptipward    varchar2(3) default ' ' not null,
  ptipwbed    varchar2(3) default ' ' not null,
  ptipbtyp    varchar2(3) default ' ' not null,
  ptipbday    number(3,0) default 0 not null,
  ptipeday    number(3,0) default 0 not null,
  ptiplday    number(3,0) default 0 not null,
  ptipcuri    varchar2(1) default ' ' not null,
  ptipadat    varchar2(8) default ' ' not null,
  ptipddat    varchar2(8) default ' ' not null,
  ptipaccf    varchar2(8) default ' ' not null,
  ptipacct    varchar2(8) default ' ' not null,
  ptipadoc    varchar2(6) default ' ' not null,
  ptipfnam    varchar2(54) default ' ' not null,
  ptipdtyp    varchar2(3) default ' ' not null,
  ptipddoc    varchar2(6) default ' ' not null,
  ptiprdoc    varchar2(6) default ' ' not null,
  ptiproom    varchar2(6) default ' ' not null,
  ptipitem    varchar2(9) default ' ' not null,
  ptipmhdp    varchar2(1) default ' ' not null,
  ptipband    varchar2(3) default ' ' not null,
  dptiptrn    varchar2(6) default ' ' not null,
  ptipttyp    number(1,0) default 0 not null,
  ptiparev    number(14,2) default 0 not null,
  ptiptrev    number(14,2) default 0 not null,
  ptipprev    number(14,2) default 0 not null,
  ptiphrev    number(14,2) default 0 not null,
  ptipirev    number(14,2) default 0 not null,
  ptiplrev    number(14,2) default 0 not null,
  ptipmrev    number(14,2) default 0 not null,
  ptipgrev    number(14,2) default 0 not null,
  ptippmbs    varchar2(9) default ' ' not null,
  ptipgpor    number(14,2) default 0 not null,
  ptiporat    number(14,2) default 0 not null,
  ptipdrat    number(14,2) default 0 not null,
  ptipaddt    number(14,2) default 0 not null,
  ptipfreb    number(14,2) default 0 not null,
  ptipppor    number(14,2) default 0 not null,
  ptiprpor    number(14,2) default 0 not null,
  ptipctyp    number(1,0) default 0 not null,
  ptippdrg    varchar2(9) default ' ' not null,
  ptipndrg    varchar2(4) default ' ' not null,
  ptipsdrg    varchar2(4) default ' ' not null,
  ptipnmdc    varchar2(4) default ' ' not null,
  ptipsmdc    varchar2(4) default ' ' not null,
  ptipgrp1    varchar2(3) default ' ' not null,
  ptipgrp2    varchar2(3) default ' ' not null,
  ptipgrp3    varchar2(3) default ' ' not null,
  ptipcdat    varchar2(8) default ' ' not null,
  ptipctim    varchar2(8) default ' ' not null,
  ptipoper    varchar2(4) default ' ' not null,
  ptipgstu    varchar2(1) default ' ' not null,
  ptipspar    varchar2(30) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint patinpa1 primary key( 
dptipadm,
ptiprtyp,
dptiptrn)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
