create table patmtdaf
(
  dptmdadm    varchar2(8) default ' ' not null,
  ptmdmadm    number(4,0) default 0 not null,
  ptmdmsep    number(4,0) default 0 not null,
  ptmdmsts    number(4,0) default 0 not null,
  ptmdmlve    number(3,0) default 0 not null,
  ptmdminh    number(4,0) default 0 not null,
  ptmdmbed    number(5,0) default 0 not null,
  ptmdmhas    number(4,0) default 0 not null,
  ptmdmhab    number(5,0) default 0 not null,
  ptmdmpas    number(4,0) default 0 not null,
  ptmdmpab    number(5,0) default 0 not null,
  ptmdmhns    number(4,0) default 0 not null,
  ptmdmhnb    number(5,0) default 0 not null,
  ptmdmpns    number(4,0) default 0 not null,
  ptmdmpnb    number(5,0) default 0 not null,
  ptmdmh5s    number(4,0) default 0 not null,
  ptmdmh5b    number(5,0) default 0 not null,
  ptmdmp5s    number(4,0) default 0 not null,
  ptmdmp5b    number(5,0) default 0 not null,
  ptmdmcos    number(4,0) default 0 not null,
  ptmdmcob    number(5,0) default 0 not null,
  ptmdmcns    number(4,0) default 0 not null,
  ptmdmcnb    number(5,0) default 0 not null,
  ptmdmies    number(4,0) default 0 not null,
  ptmdmieb    number(5,0) default 0 not null,
  ptmdmins    number(4,0) default 0 not null,
  ptmdminb    number(5,0) default 0 not null,
  ptmdmhcs    number(4,0) default 0 not null,
  ptmdmhcb    number(5,0) default 0 not null,
  ptmdmpcs    number(4,0) default 0 not null,
  ptmdmpcb    number(5,0) default 0 not null,
  ptmdyhat    number(6,0) default 0 not null,
  ptmdypat    number(6,0) default 0 not null,
  ptmdycot    number(6,0) default 0 not null,
  ptmdyiet    number(6,0) default 0 not null,
  ptmdyhnt    number(6,0) default 0 not null,
  ptmdypnt    number(6,0) default 0 not null,
  ptmdyh5t    number(6,0) default 0 not null,
  ptmdyp5t    number(6,0) default 0 not null,
  ptmdyhct    number(6,0) default 0 not null,
  ptmdypct    number(6,0) default 0 not null,
  ptmdycnt    number(6,0) default 0 not null,
  ptmdyint    number(6,0) default 0 not null,
  ptmdmhsd    number(4,0) default 0 not null,
  ptmdmpsd    number(4,0) default 0 not null,
  ptmdmcsd    number(4,0) default 0 not null,
  ptmdmisd    number(4,0) default 0 not null,
  ptmdmhcd    number(4,0) default 0 not null,
  ptmdmpcd    number(4,0) default 0 not null,
  ptmdform    number(1,0) default 0 not null,
  ptmdmuep    number(3,0) default 0 not null,
  ptmdmubd    number(4,0) default 0 not null,
  ptmdhosp    varchar2(3) default ' ' not null,
  ptmdmops    number(2,0) default 0 not null,
  ptmdmopb    number(3,0) default 0 not null,
  ptmdyopt    number(5,0) default 0 not null,
  ptmdspar    varchar2(52) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint patmtda1 primary key( 
dptmdadm)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
