create table patma1af
(
  purno       varchar2(8) default ' ' not null,
  pport       varchar2(2) default ' ' not null,
  pchgdte     varchar2(8) default ' ' not null,
  ptitl       varchar2(4) default ' ' not null,
  phosp       number(1,0) default 0 not null,
  pldays      number(3,0) default 0 not null,
  pbdebt      number(1,0) default 0 not null,
  psname      varchar2(20) default ' ' not null,
  pgname      varchar2(25) default ' ' not null,
  ppsname     varchar2(19) default ' ' not null,
  padd1       varchar2(35) default ' ' not null,
  padd2       varchar2(35) default ' ' not null,
  psubrb      varchar2(35) default ' ' not null,
  padd4       varchar2(35) default ' ' not null,
  ppost       varchar2(8) default ' ' not null,
  ptelep      varchar2(20) default ' ' not null,
  pteleb      varchar2(20) default ' ' not null,
  psex        varchar2(1) default ' ' not null,
  pmstat      varchar2(3) default ' ' not null,
  pbdate      varchar2(8) default ' ' not null,
  psage       number(3,0) default 0 not null,
  pcont       varchar2(3) default ' ' not null,
  preg        varchar2(3) default ' ' not null,
  ptype       varchar2(3) default ' ' not null,
  poccup      varchar2(14) default ' ' not null,
  plddate     varchar2(8) default ' ' not null,
  pmedi       varchar2(10) default ' ' not null,
  ppenno      varchar2(15) default ' ' not null,
  ppndte      varchar2(6) default ' ' not null,
  prepat      varchar2(10) default ' ' not null,
  psmok       number(1,0) default 0 not null,
  pstat       number(1,0) default 0 not null,
  pmicro      varchar2(20) default ' ' not null,
  pcease      number(1,0) default 0 not null,
  pcase       number(1,0) default 0 not null,
  pautopy     number(1,0) default 0 not null,
  phigh1      varchar2(3) default ' ' not null,
  phigh2      varchar2(3) default ' ' not null,
  phigh3      varchar2(3) default ' ' not null,
  plocdoc     varchar2(30) default ' ' not null,
  pfundh      varchar2(6) default ' ' not null,
  pfndtb      varchar2(8) default ' ' not null,
  ptmaspar    varchar2(10) default ' ' not null,
  pusr1       varchar2(3) default ' ' not null,
  pusr2       varchar2(3) default ' ' not null,
  pusr3       varchar2(3) default ' ' not null,
  pusr4       varchar2(3) default ' ' not null,
  pusr5       varchar2(3) default ' ' not null,
  pusr6       varchar2(3) default ' ' not null,
  puyn1       number(1,0) default 0 not null,
  puyn2       number(1,0) default 0 not null,
  puyn3       number(1,0) default 0 not null,
  pyrres      number(2,0) default 0 not null,
  pnkname     varchar2(20) default ' ' not null,
  pnkadd1     varchar2(35) default ' ' not null,
  pnkadd2     varchar2(35) default ' ' not null,
  pnksubr     varchar2(35) default ' ' not null,
  pnkadd4     varchar2(35) default ' ' not null,
  pnkpost     varchar2(8) default ' ' not null,
  pnktelp     varchar2(20) default ' ' not null,
  pnktelb     varchar2(20) default ' ' not null,
  pnkrelp     varchar2(10) default ' ' not null,
  plstinp     varchar2(8) default ' ' not null,
  plstout     varchar2(8) default ' ' not null,
  pnxray      number(3,0) default 0 not null,
  pfndyy      varchar2(2) default ' ' not null,
  pfndcg      varchar2(6) default ' ' not null,
  pdecdte     varchar2(8) default ' ' not null,
  phcnotes    varchar2(20) default ' ' not null,
  pdiet       varchar2(3) default ' ' not null,
  pinithos    varchar2(2) default ' ' not null,
  phkaduni    varchar2(10) default ' ' not null,
  ptmaempc    varchar2(6) default ' ' not null,
  ptmanoko    varchar2(14) default ' ' not null,
  ptmanoke    varchar2(6) default ' ' not null,
  ptmadcno    varchar2(10) default ' ' not null,
  ptmaukdb    varchar2(1) default ' ' not null,
  ptmaukdd    varchar2(1) default ' ' not null,
  pfndmm      varchar2(19) default ' ' not null,
  ptmadcdt    varchar2(8) default ' ' not null,
  ptmahcp1    varchar2(10) default ' ' not null,
  ptmahcl1    varchar2(10) default ' ' not null,
  ptmahcg1    varchar2(2) default ' ' not null,
  ptmahcp2    varchar2(10) default ' ' not null,
  ptmahcl2    varchar2(10) default ' ' not null,
  ptmahcg2    varchar2(2) default ' ' not null,
  ptmahcp3    varchar2(10) default ' ' not null,
  ptmahcl3    varchar2(10) default ' ' not null,
  ptmahcg3    varchar2(2) default ' ' not null,
  ptmahcp4    varchar2(10) default ' ' not null,
  ptmahcl4    varchar2(10) default ' ' not null,
  ptmahcg4    varchar2(2) default ' ' not null,
  ptmahcp5    varchar2(10) default ' ' not null,
  ptmahcl5    varchar2(10) default ' ' not null,
  ptmahcg5    varchar2(2) default ' ' not null,
  ptmasnam    varchar2(40) default ' ' not null,
  ptmadcud    varchar2(8) default ' ' not null,
  ptmadcut    varchar2(8) default ' ' not null,
  ptmadcuu    varchar2(10) default ' ' not null,
  ptmauuid    varchar2(10) default ' ' not null,
  ptmautim    varchar2(8) default ' ' not null,
  ptmaspa2    varchar2(10) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint patma1a1 primary key( 
purno)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create  index patma1a2 on patma1af
(
pbdate
)
  tablespace pas_indx; 
create unique index patma1a3 on patma1af
(
pmedi,
purno
)
  tablespace pas_indx; 
create unique index patma1a4 on patma1af
(
ppsname,
purno
)
  tablespace pas_indx; 
