create table patptdaf
(
  dptpdadm    varchar2(8) default ' ' not null,
  ptpdmadm    number(4,0) default 0 not null,
  ptpdmsep    number(4,0) default 0 not null,
  ptpdmsts    number(4,0) default 0 not null,
  ptpdmlve    number(3,0) default 0 not null,
  ptpdminh    number(4,0) default 0 not null,
  ptpdmbed    number(5,0) default 0 not null,
  ptpdmhas    number(4,0) default 0 not null,
  ptpdmhab    number(5,0) default 0 not null,
  ptpdmpas    number(4,0) default 0 not null,
  ptpdmpab    number(5,0) default 0 not null,
  ptpdmhns    number(4,0) default 0 not null,
  ptpdmhnb    number(5,0) default 0 not null,
  ptpdmpns    number(4,0) default 0 not null,
  ptpdmpnb    number(5,0) default 0 not null,
  ptpdmh5s    number(4,0) default 0 not null,
  ptpdmh5b    number(5,0) default 0 not null,
  ptpdmp5s    number(4,0) default 0 not null,
  ptpdmp5b    number(5,0) default 0 not null,
  ptpdmcos    number(4,0) default 0 not null,
  ptpdmcob    number(5,0) default 0 not null,
  ptpdmcns    number(4,0) default 0 not null,
  ptpdmcnb    number(5,0) default 0 not null,
  ptpdmies    number(4,0) default 0 not null,
  ptpdmieb    number(5,0) default 0 not null,
  ptpdmins    number(4,0) default 0 not null,
  ptpdminb    number(5,0) default 0 not null,
  ptpdmhcs    number(4,0) default 0 not null,
  ptpdmhcb    number(5,0) default 0 not null,
  ptpdmpcs    number(4,0) default 0 not null,
  ptpdmpcb    number(5,0) default 0 not null,
  ptpdyhat    number(6,0) default 0 not null,
  ptpdypat    number(6,0) default 0 not null,
  ptpdycot    number(6,0) default 0 not null,
  ptpdyiet    number(6,0) default 0 not null,
  ptpdyhnt    number(6,0) default 0 not null,
  ptpdypnt    number(6,0) default 0 not null,
  ptpdyh5t    number(6,0) default 0 not null,
  ptpdyp5t    number(6,0) default 0 not null,
  ptpdyhct    number(6,0) default 0 not null,
  ptpdypct    number(6,0) default 0 not null,
  ptpdycnt    number(6,0) default 0 not null,
  ptpdyint    number(6,0) default 0 not null,
  ptpdmhsd    number(4,0) default 0 not null,
  ptpdmpsd    number(4,0) default 0 not null,
  ptpdmcsd    number(4,0) default 0 not null,
  ptpdmisd    number(4,0) default 0 not null,
  ptpdmhcd    number(4,0) default 0 not null,
  ptpdmpcd    number(4,0) default 0 not null,
  ptpdform    number(1,0) default 0 not null,
  ptpdmuep    number(3,0) default 0 not null,
  ptpdmubd    number(4,0) default 0 not null,
  ptpdhosp    varchar2(3) default ' ' not null,
  ptpdmops    number(2,0) default 0 not null,
  ptpdmopb    number(3,0) default 0 not null,
  ptpdyopt    number(5,0) default 0 not null,
  ptpdspar    varchar2(52) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint patptda1 primary key( 
dptpdadm)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
