create table patpx1af
(
  purno       varchar2(8) default ' ' not null,
  ptmxrdat    varchar2(8) default ' ' not null,
  ptmxmeal    varchar2(30) default ' ' not null,
  ptmxlga     varchar2(4) default ' ' not null,
  ptmxls      varchar2(3) default ' ' not null,
  ptmxlsdt    varchar2(8) default ' ' not null,
  ptmxfhmd    varchar2(1) default ' ' not null,
  ptmxmhu1    varchar2(3) default ' ' not null,
  ptmxmhu2    varchar2(3) default ' ' not null,
  ptmxmhu3    varchar2(3) default ' ' not null,
  ptmxecnm    varchar2(20) default ' ' not null,
  ptmxeca1    varchar2(35) default ' ' not null,
  ptmxeca2    varchar2(35) default ' ' not null,
  ptmxeca3    varchar2(35) default ' ' not null,
  ptmxeca4    varchar2(35) default ' ' not null,
  ptmxecpc    varchar2(8) default ' ' not null,
  ptmxecpp    varchar2(20) default ' ' not null,
  ptmxecbp    varchar2(20) default ' ' not null,
  ptmxecre    varchar2(10) default ' ' not null,
  ptmxnrnm    varchar2(20) default ' ' not null,
  ptmxnra1    varchar2(35) default ' ' not null,
  ptmxnra2    varchar2(35) default ' ' not null,
  ptmxnra3    varchar2(35) default ' ' not null,
  ptmxnra4    varchar2(35) default ' ' not null,
  ptmxnrpc    varchar2(8) default ' ' not null,
  ptmxnrpp    varchar2(20) default ' ' not null,
  ptmxnrbp    varchar2(20) default ' ' not null,
  ptmxnrre    varchar2(10) default ' ' not null,
  ptmx3bex    varchar2(8) default ' ' not null,
  ptmxcard    varchar2(20) default ' ' not null,
  ptmxcexp    varchar2(8) default ' ' not null,
  ptmxcxmp    varchar2(3) default ' ' not null,
  ptmxfmly    varchar2(12) default ' ' not null,
  ptmxchnm    varchar2(20) default ' ' not null,
  ptmxdofr    varchar2(3) default ' ' not null,
  ptmxregp    varchar2(8) default ' ' not null,
  ptmxgppc    varchar2(6) default ' ' not null,
  ptmxspid    varchar2(20) default ' ' not null,
  ptmxgppt    varchar2(2) default ' ' not null,
  ptmxosdt    varchar2(8) default ' ' not null,
  ptmxoper    varchar2(4) default ' ' not null,
  ptmxukdo    varchar2(1) default ' ' not null,
  ptmxcell    varchar2(20) default ' ' not null,
  ptmxadd1    varchar2(35) default ' ' not null,
  ptmxadd2    varchar2(35) default ' ' not null,
  ptmxadd3    varchar2(35) default ' ' not null,
  ptmxadd4    varchar2(35) default ' ' not null,
  ptmxpost    varchar2(8) default ' ' not null,
  ptmxmccd    varchar2(2) default ' ' not null,
  ptmxsin1    varchar2(1) default ' ' not null,
  ptmxsin2    varchar2(1) default ' ' not null,
  ptmxsin3    varchar2(1) default ' ' not null,
  ptmxsin4    varchar2(1) default ' ' not null,
  ptmxsin5    varchar2(1) default ' ' not null,
  ptmxctim    varchar2(20) default ' ' not null,
  ptmxslac    varchar2(8) default ' ' not null,
  ptmxfiln    varchar2(3) default ' ' not null,
  ptmxdeaf    varchar2(3) default ' ' not null,
  ptmxosms    varchar2(1) default ' ' not null,
  ptmxspar    varchar2(9) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint patpx1a1 primary key( 
purno)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
