create table patytdaf
(
  dptydadm    varchar2(8) default ' ' not null,
  ptydyadm    number(5,0) default 0 not null,
  ptydysep    number(5,0) default 0 not null,
  ptydysts    number(5,0) default 0 not null,
  ptydybed    number(6,0) default 0 not null,
  ptydyhas    number(5,0) default 0 not null,
  ptydyhab    number(6,0) default 0 not null,
  ptydyhat    number(6,0) default 0 not null,
  ptydypas    number(5,0) default 0 not null,
  ptydypab    number(6,0) default 0 not null,
  ptydypat    number(6,0) default 0 not null,
  ptydycos    number(5,0) default 0 not null,
  ptydycob    number(6,0) default 0 not null,
  ptydycot    number(6,0) default 0 not null,
  ptydyies    number(5,0) default 0 not null,
  ptydyieb    number(6,0) default 0 not null,
  ptydyiet    number(6,0) default 0 not null,
  ptydyhns    number(5,0) default 0 not null,
  ptydyhnb    number(6,0) default 0 not null,
  ptydyhnt    number(6,0) default 0 not null,
  ptydypns    number(5,0) default 0 not null,
  ptydypnb    number(6,0) default 0 not null,
  ptydypnt    number(6,0) default 0 not null,
  ptydyh5s    number(5,0) default 0 not null,
  ptydyh5b    number(6,0) default 0 not null,
  ptydyh5t    number(6,0) default 0 not null,
  ptydyp5s    number(5,0) default 0 not null,
  ptydyp5b    number(6,0) default 0 not null,
  ptydyp5t    number(6,0) default 0 not null,
  ptydyhcs    number(5,0) default 0 not null,
  ptydyhcb    number(6,0) default 0 not null,
  ptydyhct    number(6,0) default 0 not null,
  ptydypcs    number(5,0) default 0 not null,
  ptydypcb    number(6,0) default 0 not null,
  ptydypct    number(6,0) default 0 not null,
  ptydycns    number(5,0) default 0 not null,
  ptydycnb    number(6,0) default 0 not null,
  ptydycnt    number(6,0) default 0 not null,
  ptydyins    number(5,0) default 0 not null,
  ptydyinb    number(6,0) default 0 not null,
  ptydyint    number(6,0) default 0 not null,
  ptydyhsd    number(5,0) default 0 not null,
  ptydypsd    number(5,0) default 0 not null,
  ptydycsd    number(5,0) default 0 not null,
  ptydyisd    number(5,0) default 0 not null,
  ptydyhcd    number(5,0) default 0 not null,
  ptydypcd    number(5,0) default 0 not null,
  ptydform    number(1,0) default 0 not null,
  ptydyuep    number(4,0) default 0 not null,
  ptydyubd    number(5,0) default 0 not null,
  ptyddtdl    varchar2(8) default ' ' not null,
  ptydhosp    varchar2(3) default ' ' not null,
  ptydyops    number(4,0) default 0 not null,
  ptydyopb    number(5,0) default 0 not null,
  ptydyopt    number(5,0) default 0 not null,
  ptydspar    varchar2(50) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint patytda1 primary key( 
dptydadm)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
