create table pmsapgaf
(
  pmagurno    varchar2(8) default ' ' not null,
  pmagatyp    varchar2(3) default ' ' not null,
  pmagclam    varchar2(3) default ' ' not null,
  pmagfund    varchar2(6) default ' ' not null,
  pmagtabt    varchar2(3) default ' ' not null,
  pmagedat    varchar2(8) default ' ' not null,
  pmagpcde    varchar2(8) default ' ' not null,
  pmagicde    varchar2(7) default ' ' not null,
  pmagvers    varchar2(2) default ' ' not null,
  pmagsnap    varchar2(3) default ' ' not null,
  pmagmest    varchar2(3) default ' ' not null,
  pmagmeen    varchar2(3) default ' ' not null,
  pmagfadm    varchar2(1) default ' ' not null,
  pmagtimp    varchar2(1) default ' ' not null,
  pmagdadm    varchar2(8) default ' ' not null,
  pmagtocc    varchar2(3) default ' ' not null,
  pmagemor    varchar2(1) default ' ' not null,
  pmagcmr1    varchar2(3) default ' ' not null,
  pmagcmr2    varchar2(3) default ' ' not null,
  pmagcmr3    varchar2(3) default ' ' not null,
  pmagcmr4    varchar2(3) default ' ' not null,
  pmagcmp1    varchar2(3) default ' ' not null,
  pmagcmp2    varchar2(3) default ' ' not null,
  pmagcmp3    varchar2(3) default ' ' not null,
  pmagcmp4    varchar2(3) default ' ' not null,
  pmagasso    varchar2(1) default ' ' not null,
  pmagacpa    varchar2(3) default ' ' not null,
  pmagacpd    varchar2(3) default ' ' not null,
  pmaglspa    varchar2(3) default ' ' not null,
  pmaglspd    varchar2(3) default ' ' not null,
  pmagemst    varchar2(3) default ' ' not null,
  pmagrfdt    varchar2(8) default ' ' not null,
  pmagdart    varchar2(8) default ' ' not null,
  pmagsrpd    varchar2(1) default ' ' not null,
  pmagsrps    varchar2(1) default ' ' not null,
  pmagsrpn    varchar2(1) default ' ' not null,
  pmagsrpa    varchar2(1) default ' ' not null,
  pmagsrpp    varchar2(1) default ' ' not null,
  pmagsrpm    varchar2(1) default ' ' not null,
  pmagsrpg    varchar2(1) default ' ' not null,
  pmagsrpt    varchar2(1) default ' ' not null,
  pmagsrpc    varchar2(1) default ' ' not null,
  pmagdrae    varchar2(8) default ' ' not null,
  pmagemsa    varchar2(3) default ' ' not null,
  pmagdcrd    varchar2(8) default ' ' not null,
  pmagsrad    varchar2(1) default ' ' not null,
  pmagsras    varchar2(1) default ' ' not null,
  pmagsran    varchar2(1) default ' ' not null,
  pmagsraa    varchar2(1) default ' ' not null,
  pmagsrap    varchar2(1) default ' ' not null,
  pmagsram    varchar2(1) default ' ' not null,
  pmagsrag    varchar2(1) default ' ' not null,
  pmagsrat    varchar2(1) default ' ' not null,
  pmagsrac    varchar2(1) default ' ' not null,
  pmagdefp    varchar2(8) default ' ' not null,
  pmagcamn    varchar2(1) default ' ' not null,
  pmagesas    varchar2(3) default ' ' not null,
  pmagessc    varchar2(3) default ' ' not null,
  pmageesc    varchar2(3) default ' ' not null,
  pmagvdee    varchar2(1) default ' ' not null,
  pmageeas    varchar2(3) default ' ' not null,
  pmagdrca    varchar2(8) default ' ' not null,
  pmagpacs    varchar2(3) default ' ' not null,
  pmagdwpc    varchar2(1) default ' ' not null,
  pmagpppc    varchar2(1) default ' ' not null,
  pmagappc    varchar2(1) default ' ' not null,
  pmagpace    varchar2(3) default ' ' not null,
  pmagpros    varchar2(1) default ' ' not null,
  pmagdfpf    varchar2(8) default ' ' not null,
  pmagrdif    varchar2(3) default ' ' not null,
  pmagdtug    number(3,1) default 0 not null,
  pmagd06m    number(4,1) default 0 not null,
  pmagd10m    number(3,1) default 0 not null,
  pmagfrai    varchar2(3) default ' ' not null,
  pmagpitd    varchar2(1) default ' ' not null,
  pmagf12m    varchar2(1) default ' ' not null,
  pmagwl12    varchar2(1) default ' ' not null,
  pmagdcrc    varchar2(10) default ' ' not null,
  pmagides    varchar2(3) default ' ' not null,
  pmagudt1    varchar2(8) default ' ' not null,
  pmagudt2    varchar2(8) default ' ' not null,
  pmagudt3    varchar2(8) default ' ' not null,
  pmaguct1    varchar2(3) default ' ' not null,
  pmaguct2    varchar2(3) default ' ' not null,
  pmaguct3    varchar2(3) default ' ' not null,
  pmaguct4    varchar2(3) default ' ' not null,
  pmaguct5    varchar2(3) default ' ' not null,
  pmaguyn1    varchar2(1) default ' ' not null,
  pmaguyn2    varchar2(1) default ' ' not null,
  pmaguyn3    varchar2(1) default ' ' not null,
  pmaguyn4    varchar2(1) default ' ' not null,
  pmaguyn5    varchar2(1) default ' ' not null,
  pmagcdat    varchar2(8) default ' ' not null,
  pmagctim    varchar2(8) default ' ' not null,
  pmagcuid    varchar2(10) default ' ' not null,
  pmagudat    varchar2(8) default ' ' not null,
  pmagutim    varchar2(8) default ' ' not null,
  pmaguuid    varchar2(10) default ' ' not null,
  pmagdugo    varchar2(4) default ' ' not null,
  pmagdwlk    varchar2(4) default ' ' not null,
  pmagspar    varchar2(92) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint pmsapga1 primary key( 
pmagurno,
pmagatyp,
pmagclam,
pmagfund,
pmagtabt,
pmagedat)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
