create table pmsextaf
(
  pmexvisn    varchar2(8) default ' ' not null,
  pmexclam    varchar2(3) default ' ' not null,
  pmexname    varchar2(50) default ' ' not null,
  pmexadd1    varchar2(35) default ' ' not null,
  pmexadd2    varchar2(35) default ' ' not null,
  pmexadd3    varchar2(35) default ' ' not null,
  pmexadd4    varchar2(35) default ' ' not null,
  pmexpost    varchar2(8) default ' ' not null,
  pmextele    varchar2(20) default ' ' not null,
  pmexadat    varchar2(8) default ' ' not null,
  pmexabic    varchar2(1) default ' ' not null,
  pmexicod    varchar2(6) default ' ' not null,
  pmexclmn    varchar2(20) default ' ' not null,
  pmexicon    varchar2(50) default ' ' not null,
  pmexcom1    varchar2(40) default ' ' not null,
  pmexcom2    varchar2(40) default ' ' not null,
  pmexurno    varchar2(8) default ' ' not null,
  pmexvdat    varchar2(8) default ' ' not null,
  pmexodin    varchar2(1) default ' ' not null,
  pmexserv    varchar2(3) default ' ' not null,
  pmexrank    varchar2(50) default ' ' not null,
  pmexsnum    varchar2(20) default ' ' not null,
  pmexbase    varchar2(50) default ' ' not null,
  pmexmcom    varchar2(3) default ' ' not null,
  pmexunit    varchar2(50) default ' ' not null,
  pmexmcnm    varchar2(80) default ' ' not null,
  pmexssnm    varchar2(20) default ' ' not null,
  pmexcont    varchar2(3) default ' ' not null,
  pmexctel    varchar2(20) default ' ' not null,
  pmexomem    varchar2(20) default ' ' not null,
  pmexiedt    varchar2(8) default ' ' not null,
  pmexsbil    varchar2(1) default ' ' not null,
  pmextins    varchar2(1) default ' ' not null,
  pmexipol    varchar2(20) default ' ' not null,
  pmexiexd    varchar2(8) default ' ' not null,
  pmexsnam    varchar2(50) default ' ' not null,
  pmexsagn    varchar2(50) default ' ' not null,
  pmexscon    varchar2(50) default ' ' not null,
  pmexdat1    varchar2(8) default ' ' not null,
  pmexdat2    varchar2(8) default ' ' not null,
  pmexdat3    varchar2(8) default ' ' not null,
  pmexdat4    varchar2(8) default ' ' not null,
  pmexdat5    varchar2(8) default ' ' not null,
  pmextim1    varchar2(8) default ' ' not null,
  pmextim2    varchar2(8) default ' ' not null,
  pmextim3    varchar2(8) default ' ' not null,
  pmextim4    varchar2(8) default ' ' not null,
  pmextim5    varchar2(8) default ' ' not null,
  pmexuyn1    varchar2(1) default ' ' not null,
  pmexuyn2    varchar2(1) default ' ' not null,
  pmexuyn3    varchar2(1) default ' ' not null,
  pmexuyn4    varchar2(1) default ' ' not null,
  pmexuyn5    varchar2(1) default ' ' not null,
  pmexcat1    varchar2(3) default ' ' not null,
  pmexcat2    varchar2(3) default ' ' not null,
  pmexcat3    varchar2(3) default ' ' not null,
  pmexcat4    varchar2(3) default ' ' not null,
  pmexcat5    varchar2(3) default ' ' not null,
  pmexucm1    varchar2(50) default ' ' not null,
  pmexucm2    varchar2(50) default ' ' not null,
  pmexucm3    varchar2(50) default ' ' not null,
  pmexucm4    varchar2(50) default ' ' not null,
  pmexucm5    varchar2(50) default ' ' not null,
  pmexslnm    varchar2(50) default ' ' not null,
  pmexsad1    varchar2(35) default ' ' not null,
  pmexsad2    varchar2(35) default ' ' not null,
  pmexsad3    varchar2(35) default ' ' not null,
  pmexsad4    varchar2(35) default ' ' not null,
  pmexspos    varchar2(8) default ' ' not null,
  pmexstel    varchar2(20) default ' ' not null,
  pmexscnm    varchar2(50) default ' ' not null,
  pmexvtyp    varchar2(3) default ' ' not null,
  pmexvexp    varchar2(8) default ' ' not null,
  pmexpasn    varchar2(20) default ' ' not null,
  pmexpasc    varchar2(3) default ' ' not null,
  pmexosvs    varchar2(3) default ' ' not null,
  pmexbasc    varchar2(3) default ' ' not null,
  pmexecon    varchar2(50) default ' ' not null,
  pmexephn    varchar2(20) default ' ' not null,
  pmexcad1    varchar2(35) default ' ' not null,
  pmexcad2    varchar2(35) default ' ' not null,
  pmexcad3    varchar2(35) default ' ' not null,
  pmexcad4    varchar2(35) default ' ' not null,
  pmexcpcd    varchar2(8) default ' ' not null,
  pmexcnam    varchar2(50) default ' ' not null,
  pmexcphn    varchar2(20) default ' ' not null,
  pmexcinj    varchar2(3) default ' ' not null,
  pmexincd    varchar2(3) default ' ' not null,
  pmexaccf    varchar2(3) default ' ' not null,
  pmexplin    varchar2(3) default ' ' not null,
  pmexacti    varchar2(3) default ' ' not null,
  pmexadte    varchar2(8) default ' ' not null,
  pmexatme    varchar2(8) default ' ' not null,
  pmexaclc    varchar2(3) default ' ' not null,
  pmexaloc    varchar2(50) default ' ' not null,
  pmexainz    varchar2(1) default ' ' not null,
  pmexmovv    varchar2(1) default ' ' not null,
  pmexspti    varchar2(1) default ' ' not null,
  pmexsprt    varchar2(3) default ' ' not null,
  pmexreci    varchar2(1) default ' ' not null,
  pmextric    varchar2(1) default ' ' not null,
  pmexesta    varchar2(3) default ' ' not null,
  pmexpddt    varchar2(8) default ' ' not null,
  pmexarg1    varchar2(40) default ' ' not null,
  pmexarg2    varchar2(40) default ' ' not null,
  pmexarsn    varchar2(40) default ' ' not null,
  pmexartl    varchar2(4) default ' ' not null,
  pmexarrp    varchar2(10) default ' ' not null,
  pmexasst    varchar2(1) default ' ' not null,
  pmexneed    varchar2(1) default ' ' not null,
  pmexcnor    varchar2(1) default ' ' not null,
  pmexaltw    varchar2(1) default ' ' not null,
  pmextypa    varchar2(3) default ' ' not null,
  pmexsalt    varchar2(8) default ' ' not null,
  pmexhpda    varchar2(2) default ' ' not null,
  pmexunfd    varchar2(3) default ' ' not null,
  pmexunft    varchar2(3) default ' ' not null,
  pmexfisd    varchar2(8) default ' ' not null,
  pmexrnwd    varchar2(8) default ' ' not null,
  pmexcsta    varchar2(1) default ' ' not null,
  pmextwrk    varchar2(3) default ' ' not null,
  pmexoest    varchar2(50) default ' ' not null,
  pmextpro    varchar2(10) default ' ' not null,
  pmexauth    varchar2(20) default ' ' not null,
  pmexauda    varchar2(8) default ' ' not null,
  pmexrefn    varchar2(20) default ' ' not null,
  pmexpoli    varchar2(20) default ' ' not null,
  pmexrego    varchar2(36) default ' ' not null,
  pmexdrps    varchar2(1) default ' ' not null,
  pmexengd    varchar2(20) default ' ' not null,
  pmexinjr    varchar2(30) default ' ' not null,
  pmexmtrn    varchar2(10) default ' ' not null,
  pmexmsev    varchar2(30) default ' ' not null,
  pmexrsev    varchar2(20) default ' ' not null,
  pmexodd1    varchar2(30) default ' ' not null,
  pmexodd2    varchar2(30) default ' ' not null,
  pmexodd3    varchar2(30) default ' ' not null,
  pmextclm    varchar2(1) default ' ' not null,
  pmexmtyp    varchar2(3) default ' ' not null,
  pmexalel    varchar2(3) default ' ' not null,
  pmexpolc    varchar2(1) default ' ' not null,
  pmexidno    varchar2(20) default ' ' not null,
  pmexschl    varchar2(6) default ' ' not null,
  pmexcuid    varchar2(10) default ' ' not null,
  pmexcdat    varchar2(8) default ' ' not null,
  pmexctim    varchar2(8) default ' ' not null,
  pmexuuid    varchar2(10) default ' ' not null,
  pmexudat    varchar2(8) default ' ' not null,
  pmexutim    varchar2(8) default ' ' not null,
  pmexdano    varchar2(20) default ' ' not null,
  pmexpmkn    varchar2(20) default ' ' not null,
  pmexfsrc    varchar2(3) default ' ' not null,
  pmexhfnd    varchar2(6) default ' ' not null,
  pmexftbl    varchar2(8) default ' ' not null,
  pmexhfmn    varchar2(19) default ' ' not null,
  pmexhfcn    varchar2(40) default ' ' not null,
  pmexspar    varchar2(40) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint pmsexta1 primary key( 
pmexvisn,
pmexclam)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index pmsexta2 on pmsextaf
(
pmexurno,
pmexvisn,
pmexclam
)
  tablespace pas_indx; 
create unique index pmsexta3 on pmsextaf
(
pmexurno,
pmexadat,
pmexvisn,
pmexclam
)
  tablespace pas_indx; 
