create table pmsencaf
(
  pmenvisn    varchar2(8) default ' ' not null,
  pmenenct    varchar2(8) default ' ' not null,
  pmensdep    varchar2(3) default ' ' not null,
  pmenshcp    varchar2(10) default ' ' not null,
  pmensdat    varchar2(8) default ' ' not null,
  pmenstim    varchar2(8) default ' ' not null,
  pmenloca    varchar2(3) default ' ' not null,
  pmenserv    varchar2(6) default ' ' not null,
  pmensrvd    varchar2(3) default ' ' not null,
  pmendiun    number(6,0) default 0 not null,
  pmendbun    number(6,0) default 0 not null,
  pmeninun    number(6,0) default 0 not null,
  pmenibun    number(6,0) default 0 not null,
  pmencomp    varchar2(3) default ' ' not null,
  pmenbulk    varchar2(3) default ' ' not null,
  pmenpurc    varchar2(3) default ' ' not null,
  pmencont    varchar2(3) default ' ' not null,
  pmentype    varchar2(3) default ' ' not null,
  pmenrsta    varchar2(1) default ' ' not null,
  pmenudt1    varchar2(8) default ' ' not null,
  pmenutm1    varchar2(8) default ' ' not null,
  pmenudt2    varchar2(8) default ' ' not null,
  pmenutm2    varchar2(8) default ' ' not null,
  pmenudt3    varchar2(8) default ' ' not null,
  pmenutm3    varchar2(8) default ' ' not null,
  pmenudt4    varchar2(8) default ' ' not null,
  pmenutm4    varchar2(8) default ' ' not null,
  pmenahc1    varchar2(10) default ' ' not null,
  pmenahc2    varchar2(10) default ' ' not null,
  pmenahc3    varchar2(10) default ' ' not null,
  pmenahc4    varchar2(10) default ' ' not null,
  pmenuhc1    varchar2(10) default ' ' not null,
  pmenuhc2    varchar2(10) default ' ' not null,
  pmenuhc3    varchar2(10) default ' ' not null,
  pmenuhc4    varchar2(10) default ' ' not null,
  pmenudi1    varchar2(9) default ' ' not null,
  pmenudi2    varchar2(9) default ' ' not null,
  pmenudi3    varchar2(9) default ' ' not null,
  pmenffd1    varchar2(80) default ' ' not null,
  pmenffd2    varchar2(80) default ' ' not null,
  pmenffd3    varchar2(80) default ' ' not null,
  pmenudp1    varchar2(9) default ' ' not null,
  pmenudp2    varchar2(9) default ' ' not null,
  pmenudp3    varchar2(9) default ' ' not null,
  pmenuyn1    varchar2(1) default ' ' not null,
  pmenuyn2    varchar2(1) default ' ' not null,
  pmenuyn3    varchar2(1) default ' ' not null,
  pmenuyn4    varchar2(1) default ' ' not null,
  pmenuyn5    varchar2(1) default ' ' not null,
  pmenuyn6    varchar2(1) default ' ' not null,
  pmenuyn7    varchar2(1) default ' ' not null,
  pmenuyn8    varchar2(1) default ' ' not null,
  pmenuyn9    varchar2(1) default ' ' not null,
  pmenuff1    varchar2(80) default ' ' not null,
  pmenuff2    varchar2(80) default ' ' not null,
  pmenuff3    varchar2(80) default ' ' not null,
  pmenuc01    varchar2(3) default ' ' not null,
  pmenuc02    varchar2(3) default ' ' not null,
  pmenuc03    varchar2(3) default ' ' not null,
  pmenuc04    varchar2(3) default ' ' not null,
  pmenuc05    varchar2(3) default ' ' not null,
  pmenuc06    varchar2(3) default ' ' not null,
  pmenuc07    varchar2(3) default ' ' not null,
  pmenuc08    varchar2(3) default ' ' not null,
  pmenuc09    varchar2(3) default ' ' not null,
  pmenuc10    varchar2(3) default ' ' not null,
  pmenuc11    varchar2(3) default ' ' not null,
  pmenuc12    varchar2(3) default ' ' not null,
  pmenuc13    varchar2(3) default ' ' not null,
  pmenuc14    varchar2(3) default ' ' not null,
  pmenuc15    varchar2(3) default ' ' not null,
  pmenuc16    varchar2(3) default ' ' not null,
  pmenuc17    varchar2(3) default ' ' not null,
  pmenuc18    varchar2(3) default ' ' not null,
  pmenuc19    varchar2(3) default ' ' not null,
  pmenuc20    varchar2(3) default ' ' not null,
  pmenuc21    varchar2(3) default ' ' not null,
  pmenuc22    varchar2(3) default ' ' not null,
  pmenuc23    varchar2(3) default ' ' not null,
  pmenuc24    varchar2(3) default ' ' not null,
  pmenuc25    varchar2(3) default ' ' not null,
  pmenuc26    varchar2(3) default ' ' not null,
  pmenuc27    varchar2(3) default ' ' not null,
  pmenuc28    varchar2(3) default ' ' not null,
  pmenuc29    varchar2(3) default ' ' not null,
  pmenuc30    varchar2(3) default ' ' not null,
  pmenuc31    varchar2(3) default ' ' not null,
  pmenuc32    varchar2(3) default ' ' not null,
  pmenuc33    varchar2(3) default ' ' not null,
  pmenuc34    varchar2(3) default ' ' not null,
  pmenuc35    varchar2(3) default ' ' not null,
  pmenuc36    varchar2(3) default ' ' not null,
  pmenuc37    varchar2(3) default ' ' not null,
  pmenuc38    varchar2(3) default ' ' not null,
  pmenuc39    varchar2(3) default ' ' not null,
  pmenuc40    varchar2(3) default ' ' not null,
  pmenuf01    number(16,2) default 0 not null,
  pmenuf02    number(16,2) default 0 not null,
  pmenuf03    number(16,2) default 0 not null,
  pmenuf04    number(16,2) default 0 not null,
  pmenuf05    number(16,2) default 0 not null,
  pmenuf06    number(16,2) default 0 not null,
  pmenuf07    number(16,2) default 0 not null,
  pmenuf08    number(16,2) default 0 not null,
  pmenuf09    number(16,2) default 0 not null,
  pmenuf10    number(16,2) default 0 not null,
  pmenuf11    number(8,0) default 0 not null,
  pmenuf12    number(8,0) default 0 not null,
  pmenuf13    number(8,0) default 0 not null,
  pmenuf14    number(8,0) default 0 not null,
  pmenuf15    number(8,0) default 0 not null,
  pmenuf16    number(8,0) default 0 not null,
  pmenuf17    number(8,0) default 0 not null,
  pmenuf18    number(8,0) default 0 not null,
  pmenuf19    number(8,0) default 0 not null,
  pmenuf20    number(8,0) default 0 not null,
  pmencmt1    varchar2(80) default ' ' not null,
  pmencmt2    varchar2(80) default ' ' not null,
  pmencdat    varchar2(8) default ' ' not null,
  pmenctim    varchar2(8) default ' ' not null,
  pmencuid    varchar2(10) default ' ' not null,
  pmenudat    varchar2(8) default ' ' not null,
  pmenutim    varchar2(8) default ' ' not null,
  pmenuuid    varchar2(10) default ' ' not null,
  pmenssac    varchar2(1) default ' ' not null,
  pmenmohr    varchar2(1) default ' ' not null,
  pmenoutc    varchar2(3) default ' ' not null,
  pmenaccn    varchar2(20) default ' ' not null,
  pmenspar    varchar2(50) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint pmsenca1 primary key( 
pmenvisn,
pmenenct)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index pmsenca2 on pmsencaf
(
pmenvisn,
pmensdat,
pmenstim,
pmenenct
)
  tablespace pas_indx; 
