create table pmsfidaf
(
pmfifino    varchar2(12),
pmfiuniq    varchar2(3),
pmfiurno    varchar2(8),
pmfiadmn    varchar2(8),
pmfiadat    varchar2(8),
pmfistay    varchar2(3),
pmfieddt    varchar2(8),
pmficlty    varchar2(3),
pmfihfnd    varchar2(6),
pmfihftb    varchar2(8),
pmfisgam    number(8,2),
pmfiagam    number(8,2),
pmfianga    number(8,2),
pmfiphyi    number(8,2),
pmfiphys    number(8,2),
pmfixray    number(8,2),
pmfisplb    number(8,2),
pmfimisc    number(8,2),
pmfiphar    number(8,2),
pmfipros    number(8,2),
pmfihexc    number(8,2),
pmfifast    varchar2(50),
pmfidedt    varchar2(5),
pmfieanp    varchar2(10),
pmfithf1    varchar2(9),
pmfithf2    varchar2(9),
pmfithf3    varchar2(9),
pmfithf4    varchar2(9),
pmfithf5    varchar2(9),
pmfithf6    varchar2(9),
pmfimcc1    varchar2(9),
pmfimcc2    varchar2(9),
pmfimcc3    varchar2(9),
pmfibtyp    varchar2(3),
pmfiatyp    varchar2(3),
pmfiagst    varchar2(1),
pmfiecos    number(14,2),
pmfitpoa    number(14,2),
pmfieacp    number(14,2),
pmfieach    number(14,2),
pmfietcp    number(14,2),
pmfietch    number(14,2),
pmfiemcp    number(14,2),
pmfiemch    number(14,2),
pmfiqua1    number(3,0),
pmfiqua2    number(3,0),
pmfiqua3    number(3,0),
pmfithq1    number(3,0),
pmfithq2    number(3,0),
pmfithq3    number(3,0),
pmfithq4    number(3,0),
pmfithq5    number(3,0),
pmfithq6    number(3,0),
pmfiitg1    number(8,2),
pmfiitg2    number(8,2),
pmfiitg3    number(8,2),
pmfithg1    number(8,2),
pmfithg2    number(8,2),
pmfithg3    number(8,2),
pmfithg4    number(8,2),
pmfithg5    number(8,2),
pmfithg6    number(8,2),
pmficdat    varchar2(8),
pmfictim    varchar2(8),
pmficuid    varchar2(10),
pmfiudat    varchar2(8),
pmfiutim    varchar2(8),
pmfiuuid    varchar2(10),
pmfiphca    number(8,2),
pmfiedva    number(8,2),
pmfispar    varchar2(20),
lf          varchar2(1),
constraint pmsfida1 primary key( 
pmfifino,
pmfiuniq)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create public synonym pmsfidaf for pmsfidaf;
create unique index pmsfida2 on pmsfidaf
(
pmfiurno,
pmfifino,
pmfiuniq
)
  tablespace pas_indx; 
