create table pmsirsaf
(
  pmisrtyp    varchar2(2) default ' ' not null,
  pmiscode    varchar2(50) default ' ' not null,
  pmisrdat    varchar2(8) default ' ' not null,
  pmisrtim    varchar2(8) default ' ' not null,
  pmisruid    varchar2(10) default ' ' not null,
  pmissurn    varchar2(40) default ' ' not null,
  pmisfnam    varchar2(40) default ' ' not null,
  pmissnam    varchar2(40) default ' ' not null,
  pmisbdat    varchar2(8) default ' ' not null,
  pmispsex    varchar2(1) default ' ' not null,
  pmismedi    varchar2(10) default ' ' not null,
  pmismccd    varchar2(2) default ' ' not null,
  pmismedv    varchar2(8) default ' ' not null,
  pmisdvan    varchar2(20) default ' ' not null,
  pmisihin    varchar2(20) default ' ' not null,
  pmisadd1    varchar2(60) default ' ' not null,
  pmisadd2    varchar2(60) default ' ' not null,
  pmisadd3    varchar2(60) default ' ' not null,
  pmisadd4    varchar2(60) default ' ' not null,
  pmispost    varchar2(8) default ' ' not null,
  pmissad1    varchar2(60) default ' ' not null,
  pmissad2    varchar2(60) default ' ' not null,
  pmissad3    varchar2(60) default ' ' not null,
  pmissad4    varchar2(60) default ' ' not null,
  pmisspst    varchar2(8) default ' ' not null,
  pmishpii    varchar2(20) default ' ' not null,
  pmisptyp    varchar2(1) default ' ' not null,
  pmisname    varchar2(50) default ' ' not null,
  pmishpio    varchar2(20) default ' ' not null,
  pmisstyp    varchar2(1) default ' ' not null,
  pmisunit    varchar2(20) default ' ' not null,
  pmisvsta    varchar2(1) default ' ' not null,
  pmisasta    varchar2(1) default ' ' not null,
  pmisrscd    varchar2(3) default ' ' not null,
  pmisrsde    varchar2(500) default ' ' not null,
  pmisrver    varchar2(10) default ' ' not null,
  pmisspar    varchar2(100) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint pmsirsa1 primary key( 
pmisrtyp,
pmiscode,
pmisrdat,
pmisrtim)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
