create table pmslbraf
(
  pmlbuniq    varchar2(10) default ' ' not null,
  pmlbadmn    varchar2(8) default ' ' not null,
  pmlbcntr    varchar2(3) default ' ' not null,
  pmlbaudc    varchar2(3) default ' ' not null,
  pmlbonsl    varchar2(3) default ' ' not null,
  pmlbdatl    varchar2(8) default ' ' not null,
  pmlbtiml    varchar2(8) default ' ' not null,
  pmlbmin1    varchar2(5) default ' ' not null,
  pmlbdat2    varchar2(8) default ' ' not null,
  pmlbtim2    varchar2(8) default ' ' not null,
  pmlbmin2    varchar2(5) default ' ' not null,
  pmlbdatr    varchar2(8) default ' ' not null,
  pmlbindi    varchar2(9) default ' ' not null,
  pmlbindf    varchar2(50) default ' ' not null,
  pmlbindo    varchar2(9) default ' ' not null,
  pmlbinof    varchar2(50) default ' ' not null,
  pmlbanlg    varchar2(3) default ' ' not null,
  pmlbposd    varchar2(3) default ' ' not null,
  pmlbcoll    varchar2(3) default ' ' not null,
  pmlbpres    varchar2(3) default ' ' not null,
  pmlbmemb    varchar2(3) default ' ' not null,
  pmlbnves    varchar2(2) default ' ' not null,
  pmlbtypb    varchar2(3) default ' ' not null,
  pmlbprop    varchar2(3) default ' ' not null,
  pmlbman3    varchar2(3) default ' ' not null,
  pmlbplac    varchar2(3) default ' ' not null,
  pmlbmpla    varchar2(3) default ' ' not null,
  pmlbepis    varchar2(3) default ' ' not null,
  pmlbperi    varchar2(3) default ' ' not null,
  pmlbpert    varchar2(3) default ' ' not null,
  pmlbperr    varchar2(3) default ' ' not null,
  pmlbbldl    varchar2(4) default ' ' not null,
  pmlbbltr    varchar2(3) default ' ' not null,
  pmlbdlic    varchar2(3) default ' ' not null,
  pmlbdmid    varchar2(10) default ' ' not null,
  pmlbddoc    varchar2(10) default ' ' not null,
  pmlbdana    varchar2(10) default ' ' not null,
  pmlbnumb    varchar2(2) default ' ' not null,
  pmlbmidr    varchar2(10) default ' ' not null,
  pmlbwebc    varchar2(10) default ' ' not null,
  pmlbdatc    varchar2(8) default ' ' not null,
  pmlbtimc    varchar2(8) default ' ' not null,
  pmlbwebu    varchar2(10) default ' ' not null,
  pmlbdatu    varchar2(8) default ' ' not null,
  pmlbtimu    varchar2(8) default ' ' not null,
  pmlbrecs    varchar2(1) default ' ' not null,
  pmlbwebd    varchar2(10) default ' ' not null,
  pmlbdatd    varchar2(8) default ' ' not null,
  pmlbtimd    varchar2(8) default ' ' not null,
  pmlbreas    varchar2(3) default ' ' not null,
  pmlbspar    varchar2(57) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint pmslbra1 primary key( 
pmlbuniq,
pmlbadmn,
pmlbcntr,
pmlbaudc)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
