create table pmsqviaf
(
  dpmqvmes    varchar2(20) default ' ' not null,
  dpmqvtrn    varchar2(2) default ' ' not null,
  aadmno      varchar2(8) default ' ' not null,
  aurno       varchar2(8) default ' ' not null,
  adate       varchar2(8) default ' ' not null,
  atime       varchar2(8) default ' ' not null,
  astat       number(1,0) default 0 not null,
  ainvprt     number(3,0) default 0 not null,
  alacdte     varchar2(8) default ' ' not null,
  acancel     varchar2(3) default ' ' not null,
  adoctr      varchar2(6) default ' ' not null,
  adocta      varchar2(6) default ' ' not null,
  adoctl      varchar2(30) default ' ' not null,
  asrce       varchar2(3) default ' ' not null,
  atype       varchar2(3) default ' ' not null,
  aclss       varchar2(3) default ' ' not null,
  acare       varchar2(3) default ' ' not null,
  afundh      varchar2(6) default ' ' not null,
  afndtb      varchar2(8) default ' ' not null,
  afndmm      varchar2(19) default ' ' not null,
  aelig       number(1,0) default 0 not null,
  avisit      number(1,0) default 0 not null,
  aalerg      number(1,0) default 0 not null,
  ailln       number(1,0) default 0 not null,
  adiag1      varchar2(80) default ' ' not null,
  adiag2      varchar2(80) default ' ' not null,
  adisc       number(8,2) default 0 not null,
  adoctt      varchar2(6) default ' ' not null,
  aclssft     varchar2(3) default ' ' not null,
  aallow      varchar2(2) default ' ' not null,
  ambs        varchar2(9) default ' ' not null,
  aclaim      varchar2(3) default ' ' not null,
  adiet       varchar2(3) default ' ' not null,
  aploccr     varchar2(3) default ' ' not null,
  astay       number(3,0) default 0 not null,
  adyhosp     number(4,0) default 0 not null,
  amemb       number(1,0) default 0 not null,
  amembno     number(6,0) default 0 not null,
  acomm1      varchar2(40) default ' ' not null,
  acomm2      varchar2(30) default ' ' not null,
  aplur       number(1,0) default 0 not null,
  apurge      number(1,0) default 0 not null,
  ausr1       varchar2(3) default ' ' not null,
  ausr2       varchar2(3) default ' ' not null,
  ausr3       varchar2(3) default ' ' not null,
  ausr4       varchar2(3) default ' ' not null,
  ausr5       varchar2(3) default ' ' not null,
  ausr6       varchar2(3) default ' ' not null,
  ausr7       varchar2(3) default ' ' not null,
  adschi      number(1,0) default 0 not null,
  ardrnam     varchar2(22) default ' ' not null,
  afndyy      varchar2(2) default ' ' not null,
  afndcg      varchar2(6) default ' ' not null,
  aoccdte     varchar2(8) default ' ' not null,
  acoddte     varchar2(8) default ' ' not null,
  aretdte     varchar2(8) default ' ' not null,
  amumadm     varchar2(8) default ' ' not null,
  ptmipvis    number(3,0) default 0 not null,
  abwght      varchar2(6) default ' ' not null,
  ptmsrfgp    varchar2(8) default ' ' not null,
  ptmsgppc    varchar2(6) default ' ' not null,
  ptmsfhan    varchar2(20) default ' ' not null,
  ptmsecra    varchar2(20) default ' ' not null,
  ptmsmgin    varchar2(3) default ' ' not null,
  ptmiddig    number(1,0) default 0 not null,
  ptmigppt    varchar2(2) default ' ' not null,
  ptmidofr    varchar2(3) default ' ' not null,
  ptmirefd    varchar2(8) default ' ' not null,
  ptmidfcn    varchar2(8) default ' ' not null,
  ptmiphpu    varchar2(3) default ' ' not null,
  ptmiagnc    varchar2(3) default ' ' not null,
  ptmiessf    varchar2(1) default ' ' not null,
  ptmiusr8    varchar2(3) default ' ' not null,
  ptmiusr9    varchar2(3) default ' ' not null,
  ptmiusr0    varchar2(3) default ' ' not null,
  ptmipdrg    varchar2(4) default ' ' not null,
  ptmioper    varchar2(4) default ' ' not null,
  ptmixwrd    varchar2(3) default ' ' not null,
  ptmiadoc    varchar2(6) default ' ' not null,
  ptmiregs    varchar2(6) default ' ' not null,
  ptmiuyn1    number(1,0) default 0 not null,
  ptmiuyn2    number(1,0) default 0 not null,
  ptmipano    varchar2(8) default ' ' not null,
  ptmipadt    varchar2(8) default ' ' not null,
  ptmipcmx    varchar2(9) default ' ' not null,
  ptmigsta    varchar2(1) default ' ' not null,
  ptmicmxp    varchar2(1) default ' ' not null,
  ptmiebed    varchar2(3) default ' ' not null,
  ptmidmov    varchar2(1) default ' ' not null,
  ptmidfas    varchar2(8) default ' ' not null,
  ptmicrcd    varchar2(1) default ' ' not null,
  ptmifinv    varchar2(1) default ' ' not null,
  ptmiconb    varchar2(1) default ' ' not null,
  ptmidatc    varchar2(8) default ' ' not null,
  ptmitimc    varchar2(8) default ' ' not null,
  ptmiwebc    varchar2(10) default ' ' not null,
  ptmidatu    varchar2(8) default ' ' not null,
  ptmitimu    varchar2(8) default ' ' not null,
  ptmiwebu    varchar2(10) default ' ' not null,
  ptmi3bdy    varchar2(4) default ' ' not null,
  ptmi3bad    varchar2(8) default ' ' not null,
  ptmilsdn    varchar2(8) default ' ' not null,
  ptmiogno    varchar2(8) default ' ' not null,
  tward       varchar2(3) default ' ' not null,
  tbed        varchar2(3) default ' ' not null,
  tdate       varchar2(8) default ' ' not null,
  ttime       varchar2(8) default ' ' not null,
  turno       varchar2(8) default ' ' not null,
  tadmn       varchar2(8) default ' ' not null,
  tratef      number(14,2) default 0 not null,
  trateg      number(14,2) default 0 not null,
  tdisc       number(14,2) default 0 not null,
  tallw       number(14,2) default 0 not null,
  tatype      varchar2(3) default ' ' not null,
  tadoct      varchar2(6) default ' ' not null,
  trateh      number(14,2) default 0 not null,
  textra      number(14,2) default 0 not null,
  pttritfs    number(14,2) default 0 not null,
  trbtyp      varchar2(3) default ' ' not null,
  trbend      number(3,0) default 0 not null,
  tchstat     varchar2(3) default ' ' not null,
  tdept       varchar2(3) default ' ' not null,
  pttrltyp    varchar2(3) default ' ' not null,
  pttrepno    number(2,0) default 0 not null,
  pttrepsd    number(1,0) default 0 not null,
  pttrlspt    number(14,2) default 0 not null,
  pttrlsrb    number(14,2) default 0 not null,
  pttraend    number(4,0) default 0 not null,
  pttradpt    number(14,2) default 0 not null,
  pttradrb    number(14,2) default 0 not null,
  pttrnhac    varchar2(3) default ' ' not null,
  pttroper    varchar2(4) default ' ' not null,
  pttrauat    varchar2(1) default ' ' not null,
  pttrcdat    varchar2(8) default ' ' not null,
  pttrctim    varchar2(8) default ' ' not null,
  pttrcuid    varchar2(4) default ' ' not null,
  pttrltsc    varchar2(5) default ' ' not null,
  pttrucid    varchar2(10) default ' ' not null,
  pttruuid    varchar2(10) default ' ' not null,
  pttrclty    varchar2(3) default ' ' not null,
  pttrtrty    varchar2(3) default ' ' not null,
  pttrteam    varchar2(5) default ' ' not null,
  pttrrstr    varchar2(10) default ' ' not null,
  pttrresi    varchar2(10) default ' ' not null,
  pttrfsrc    varchar2(3) default ' ' not null,
  pttrhfnd    varchar2(6) default ' ' not null,
  pttrftbl    varchar2(8) default ' ' not null,
  pttrhfmn    varchar2(19) default ' ' not null,
  pttrhfcn    varchar2(40) default ' ' not null,
  pmvxcsnr    varchar2(1) default ' ' not null,
  pmvxpost    varchar2(8) default ' ' not null,
  pmvxpind    varchar2(3) default ' ' not null,
  pmvxvloc    varchar2(40) default ' ' not null,
  pmvxcfsg    varchar2(1) default ' ' not null,
  pmvxingp    varchar2(1) default ' ' not null,
  pmvxcpth    varchar2(3) default ' ' not null,
  pmvxhcp1    varchar2(1) default ' ' not null,
  pmvxhcp2    varchar2(1) default ' ' not null,
  pmvxhcp3    varchar2(1) default ' ' not null,
  pmvxhcp4    varchar2(1) default ' ' not null,
  pmvxrhc1    varchar2(10) default ' ' not null,
  pmvxrh1g    varchar2(10) default ' ' not null,
  pmvxrh1c    varchar2(2) default ' ' not null,
  pmvxrhc2    varchar2(10) default ' ' not null,
  pmvxrh2g    varchar2(10) default ' ' not null,
  pmvxrh2c    varchar2(2) default ' ' not null,
  pmvxrhc3    varchar2(10) default ' ' not null,
  pmvxrh3g    varchar2(10) default ' ' not null,
  pmvxrh3c    varchar2(2) default ' ' not null,
  pmvxrhc4    varchar2(10) default ' ' not null,
  pmvxrh4g    varchar2(10) default ' ' not null,
  pmvxrh4c    varchar2(2) default ' ' not null,
  pmvxabrg    varchar2(3) default ' ' not null,
  pmvxcadm    varchar2(3) default ' ' not null,
  pmvxirad    varchar2(3) default ' ' not null,
  pmvxidus    varchar2(3) default ' ' not null,
  pmvxcrav    varchar2(3) default ' ' not null,
  pmvxrcct    varchar2(3) default ' ' not null,
  pmvxapwd    varchar2(3) default ' ' not null,
  pmvxapbd    varchar2(3) default ' ' not null,
  pmvxpowd    varchar2(3) default ' ' not null,
  pmvxpobd    varchar2(3) default ' ' not null,
  pmvxpsty    varchar2(1) default ' ' not null,
  pmvxvalw    varchar2(1) default ' ' not null,
  pmvxpalw    varchar2(1) default ' ' not null,
  pmvxindc    varchar2(1) default ' ' not null,
  pmvxmdav    varchar2(3) default ' ' not null,
  pmvxfrms    varchar2(3) default ' ' not null,
  pmvxcsng    varchar2(3) default ' ' not null,
  pmvxpwgt    number(6,0) default 0 not null,
  pmvxphgt    number(6,0) default 0 not null,
  pmvxdhwr    varchar2(8) default ' ' not null,
  pmvxedc1    varchar2(10) default ' ' not null,
  pmvxedc2    varchar2(10) default ' ' not null,
  pmvxedc3    varchar2(10) default ' ' not null,
  pmvxhome    varchar2(1) default ' ' not null,
  pmvxudf1    varchar2(50) default ' ' not null,
  pmvxudf2    varchar2(50) default ' ' not null,
  pmvxudf3    varchar2(50) default ' ' not null,
  pmvxudf4    varchar2(50) default ' ' not null,
  pmvxudt1    varchar2(13) default ' ' not null,
  pmvxudt2    varchar2(13) default ' ' not null,
  pmvxudt3    varchar2(13) default ' ' not null,
  pmvxudt4    varchar2(13) default ' ' not null,
  pmvxudt5    varchar2(13) default ' ' not null,
  pmvxudt6    varchar2(13) default ' ' not null,
  pmvxcdte    varchar2(8) default ' ' not null,
  pmvxctim    varchar2(8) default ' ' not null,
  pmvxwebc    varchar2(10) default ' ' not null,
  pmvxlupd    varchar2(8) default ' ' not null,
  pmvxlupt    varchar2(8) default ' ' not null,
  pmvxwebu    varchar2(10) default ' ' not null,
  pmvxmhls    varchar2(3) default ' ' not null,
  pmvxpicd    varchar2(9) default ' ' not null,
  pmvxrmor    varchar2(3) default ' ' not null,
  pmvxasut    varchar2(3) default ' ' not null,
  pmvxelps    varchar2(3) default ' ' not null,
  pmvxempl    varchar2(3) default ' ' not null,
  pmvxfinp    varchar2(3) default ' ' not null,
  pmvxoccp    varchar2(3) default ' ' not null,
  pmvxpalc    varchar2(3) default ' ' not null,
  pmvxppal    varchar2(3) default ' ' not null,
  pmvxpppt    varchar2(3) default ' ' not null,
  pmvxpsos    varchar2(3) default ' ' not null,
  pmvxpysp    varchar2(3) default ' ' not null,
  pmvxqldb    varchar2(3) default ' ' not null,
  pmvxread    varchar2(3) default ' ' not null,
  pmvxudin    varchar2(3) default ' ' not null,
  pmvxurea    varchar2(3) default ' ' not null,
  pmvxusac    varchar2(3) default ' ' not null,
  pmvxuvth    varchar2(3) default ' ' not null,
  pmvxintr    varchar2(1) default ' ' not null,
  pmvxlng1    varchar2(3) default ' ' not null,
  pmvxasgc    varchar2(9) default ' ' not null,
  pmvxmhos    varchar2(3) default ' ' not null,
  pmvxdspd    varchar2(8) default ' ' not null,
  pmvxdsif    varchar2(1) default ' ' not null,
  pmvxprmi    varchar2(1) default ' ' not null,
  pmvxprai    varchar2(1) default ' ' not null,
  pmvxpres    varchar2(1) default ' ' not null,
  pmvxuitr    varchar2(1) default ' ' not null,
  pmvxrpoa    varchar2(1) default ' ' not null,
  pmvxrcn1    varchar2(1) default ' ' not null,
  pmvxrcn2    varchar2(1) default ' ' not null,
  pmvxrhfu    varchar2(1) default ' ' not null,
  pmvxrdva    varchar2(1) default ' ' not null,
  pmvxrslo    varchar2(1) default ' ' not null,
  pmvxmloc    varchar2(3) default ' ' not null,
  pmvxpacc    varchar2(3) default ' ' not null,
  pmvxedu1    varchar2(3) default ' ' not null,
  pmvxedu2    varchar2(3) default ' ' not null,
  pmvxedu3    varchar2(3) default ' ' not null,
  pmvxprgm    varchar2(8) default ' ' not null,
  pmvxconf    varchar2(1) default ' ' not null,
  pmvxeocl    varchar2(8) default ' ' not null,
  pmvxsloc    varchar2(3) default ' ' not null,
  pmvxscli    varchar2(3) default ' ' not null,
  pmvxstra    varchar2(3) default ' ' not null,
  pmvxqasn    varchar2(12) default ' ' not null,
  pmvxatcp    varchar2(1) default ' ' not null,
  pmvxatim    varchar2(8) default ' ' not null,
  pmvxitim    varchar2(8) default ' ' not null,
  pmvxhfgn    varchar2(40) default ' ' not null,
  pmvxhfsn    varchar2(40) default ' ' not null,
  pmvxfupi    varchar2(2) default ' ' not null,
  pmvxpoec    varchar2(1) default ' ' not null,
  pmvxpgid    varchar2(3) default ' ' not null,
  pmvxticm    varchar2(3) default ' ' not null,
  pmvxpilc    varchar2(3) default ' ' not null,
  pmvxfvio    varchar2(3) default ' ' not null,
  pmvxfndm    varchar2(19) default ' ' not null,
  pmvxudf5    varchar2(3) default ' ' not null,
  pmvxudf6    varchar2(3) default ' ' not null,
  pmvxudf7    varchar2(3) default ' ' not null,
  pmvxudf8    varchar2(3) default ' ' not null,
  pmvxudf9    varchar2(3) default ' ' not null,
  pmvxud10    varchar2(3) default ' ' not null,
  pmvxud11    varchar2(3) default ' ' not null,
  pmvxud12    varchar2(3) default ' ' not null,
  pmvxud13    varchar2(3) default ' ' not null,
  pmvxud14    varchar2(3) default ' ' not null,
  pmvxud15    varchar2(3) default ' ' not null,
  pmvxteam    varchar2(5) default ' ' not null,
  pmvxnwhc    varchar2(3) default ' ' not null,
  pmvxeddt    varchar2(8) default ' ' not null,
  pmvxphld    varchar2(3) default ' ' not null,
  pmvxploc    varchar2(3) default ' ' not null,
  pmvxdtrt    varchar2(8) default ' ' not null,
  pmvxdflg    varchar2(9) default ' ' not null,
  pmvxfsrc    varchar2(3) default ' ' not null,
  pmvxconm    varchar2(40) default ' ' not null,
  pmvxcpdd    varchar2(8) default ' ' not null,
  pmvxpbmi    varchar2(5) default ' ' not null,
  ddate       varchar2(8) default ' ' not null,
  dtime       varchar2(8) default ' ' not null,
  dstat       varchar2(3) default ' ' not null,
  ddest       varchar2(3) default ' ' not null,
  ddiag       varchar2(50) default ' ' not null,
  ddiag2      varchar2(50) default ' ' not null,
  dusd1       varchar2(3) default ' ' not null,
  dusd2       varchar2(3) default ' ' not null,
  dusd3       varchar2(3) default ' ' not null,
  dusd4       varchar2(3) default ' ' not null,
  dusd5       varchar2(3) default ' ' not null,
  dfmbs       varchar2(9) default ' ' not null,
  ptdsdmdc    varchar2(4) default ' ' not null,
  ptdsddrg    varchar2(4) default ' ' not null,
  dwlreasn    varchar2(3) default ' ' not null,
  ptdssidx    varchar2(1) default ' ' not null,
  ptdsvogu    varchar2(3) default ' ' not null,
  ptdsoper    varchar2(4) default ' ' not null,
  ptdsuyn1    number(1,0) default 0 not null,
  ptdsuyn2    number(1,0) default 0 not null,
  ptdsuyn3    number(1,0) default 0 not null,
  ptdsuyn4    number(1,0) default 0 not null,
  ptdsdwrd    varchar2(3) default ' ' not null,
  ptdsdlos    number(4,0) default 0 not null,
  ptdssref    varchar2(4) default ' ' not null,
  ptdspald    varchar2(3) default ' ' not null,
  ptdsdpmn    varchar2(3) default ' ' not null,
  mhlrcode    varchar2(3) default ' ' not null,
  pkname      varchar2(80) default ' ' not null,
  pkadd1      varchar2(35) default ' ' not null,
  pkadd2      varchar2(35) default ' ' not null,
  pksubr      varchar2(35) default ' ' not null,
  pkadd4      varchar2(35) default ' ' not null,
  pkpost      varchar2(8) default ' ' not null,
  pktelep     varchar2(20) default ' ' not null,
  pkteleb     varchar2(20) default ' ' not null,
  pkrelp      varchar2(10) default ' ' not null,
  ptremobl    varchar2(20) default ' ' not null,
  ptresnam    varchar2(40) default ' ' not null,
  ptregnam    varchar2(40) default ' ' not null,
  wstby       varchar2(8) default ' ' not null,
  pmqvtdat    varchar2(8) default ' ' not null,
  pmqvttim    varchar2(8) default ' ' not null,
  oerdate     varchar2(8) default ' ' not null,
  oertime     varchar2(8) default ' ' not null,
  pmbrreqd    varchar2(8) default ' ' not null,
  pmbrreqt    varchar2(8) default ' ' not null,
  pmvxcnid    varchar2(10) default ' ' not null,
  pmvxcndt    varchar2(13) default ' ' not null,
  pmvxcase    varchar2(10) default ' ' not null,
  pmvxeafl    varchar2(1) default ' ' not null,
  ptdslsdn    varchar2(8) default ' ' not null,
  ptdsclgp    varchar2(12) default ' ' not null,
  pmqvspar    varchar2(28) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint pmsqvia1 primary key( 
dpmqvmes,
dpmqvtrn)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
