create table pmsresaf
(
  pmrsurno    varchar2(8) default ' ' not null,
  pmrscont    varchar2(3) default ' ' not null,
  pmrstexp    varchar2(8) default ' ' not null,
  pmrsgrdt    varchar2(8) default ' ' not null,
  pmrscomm    varchar2(127) default ' ' not null,
  pmrsvisn    varchar2(10) default ' ' not null,
  pmrsvexp    varchar2(8) default ' ' not null,
  pmrsvtyp    varchar2(3) default ' ' not null,
  pmrspnum    varchar2(20) default ' ' not null,
  pmrspexp    varchar2(8) default ' ' not null,
  pmrspcou    varchar2(3) default ' ' not null,
  pmrsincd    varchar2(6) default ' ' not null,
  pmrsinfm    varchar2(20) default ' ' not null,
  pmrsinex    varchar2(8) default ' ' not null,
  pmrsstdn    varchar2(20) default ' ' not null,
  pmrsschl    varchar2(6) default ' ' not null,
  pmrsecon    varchar2(50) default ' ' not null,
  pmrscad1    varchar2(35) default ' ' not null,
  pmrscad2    varchar2(35) default ' ' not null,
  pmrscad3    varchar2(35) default ' ' not null,
  pmrscad4    varchar2(35) default ' ' not null,
  pmrscpcd    varchar2(8) default ' ' not null,
  pmrssbil    varchar2(1) default ' ' not null,
  pmrstins    varchar2(1) default ' ' not null,
  pmrsipol    varchar2(20) default ' ' not null,
  pmrsiexd    varchar2(8) default ' ' not null,
  pmrsucm1    varchar2(50) default ' ' not null,
  pmrsucm2    varchar2(50) default ' ' not null,
  pmrsucm3    varchar2(50) default ' ' not null,
  pmrsucm4    varchar2(50) default ' ' not null,
  pmrsucm5    varchar2(50) default ' ' not null,
  pmrsccnt    varchar2(50) default ' ' not null,
  pmrscphn    varchar2(20) default ' ' not null,
  pmrsfsch    varchar2(30) default ' ' not null,
  pmrssad1    varchar2(35) default ' ' not null,
  pmrssad2    varchar2(35) default ' ' not null,
  pmrssad3    varchar2(35) default ' ' not null,
  pmrssad4    varchar2(35) default ' ' not null,
  pmrsspcd    varchar2(8) default ' ' not null,
  pmrsscnt    varchar2(50) default ' ' not null,
  pmrssphn    varchar2(20) default ' ' not null,
  pmrscuid    varchar2(10) default ' ' not null,
  pmrscdat    varchar2(8) default ' ' not null,
  pmrsctim    varchar2(8) default ' ' not null,
  pmrsuuid    varchar2(10) default ' ' not null,
  pmrsudat    varchar2(8) default ' ' not null,
  pmrsutim    varchar2(8) default ' ' not null,
  pmrsspar    varchar2(60) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint pmsresa1 primary key( 
pmrsurno)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
