create table pmstspaf
(
pmtsurno    varchar2(8),
pmtsvisn    varchar2(8),
pmtsuniq    varchar2(3),
pmtstdat    varchar2(8),
pmtsttim    varchar2(8),
pmtspad1    varchar2(35),
pmtspad2    varchar2(35),
pmtspad3    varchar2(35),
pmtspad4    varchar2(35),
pmtsppos    varchar2(8),
pmtsptlp    varchar2(20),
pmtsptlb    varchar2(20),
pmtsptlm    varchar2(20),
pmtspeml    varchar2(80),
pmtspmel    varchar2(20),
pmtsrad1    varchar2(35),
pmtsrad2    varchar2(35),
pmtsrad3    varchar2(35),
pmtsrad4    varchar2(35),
pmtsrpos    varchar2(8),
pmtsrtlp    varchar2(20),
pmtsrtlb    varchar2(20),
pmtsrtlm    varchar2(20),
pmtsreml    varchar2(80),
pmtsrmel    varchar2(20),
pmtssame    varchar2(1),
pmtsdad1    varchar2(35),
pmtsdad2    varchar2(35),
pmtsdad3    varchar2(35),
pmtsdad4    varchar2(35),
pmtsdpos    varchar2(8),
pmtsdtlp    varchar2(20),
pmtsdtlb    varchar2(20),
pmtsdtlm    varchar2(20),
pmtsdeml    varchar2(80),
pmtsdmel    varchar2(20),
pmtsfacl    varchar2(3),
pmtstrns    varchar2(3),
pmtsmobl    varchar2(3),
pmtsbook    varchar2(1),
pmtsaids    varchar2(3),
pmtsment    varchar2(3),
pmtsspec    varchar2(3),
pmtsccen    varchar2(10),
pmtsclam    varchar2(3),
pmtsambs    varchar2(1),
pmtsambn    varchar2(10),
pmtsm40s    varchar2(1),
pmtsm40n    varchar2(20),
pmtsm40e    varchar2(8),
pmtsrunn    varchar2(3),
pmtscdat    varchar2(8),
pmtsctim    varchar2(8),
pmtscuid    varchar2(10),
pmtsudat    varchar2(8),
pmtsutim    varchar2(8),
pmtsuuid    varchar2(10),
pmtsruno    varchar2(3),
pmtstrno    varchar2(3),
pmtsrtdt    varchar2(8),
pmtsrttm    varchar2(8),
pmtsrtbk    varchar2(1),
pmtsspar    varchar2(77),
lf          varchar2(1),
constraint pmstspa1 primary key( 
pmtsurno,
pmtsvisn,
pmtsuniq)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create public synonym pmstspaf for pmstspaf;
create unique index pmstspa2 on pmstspaf
(
pmtstdat,
pmtsttim,
pmtsurno,
pmtsvisn,
pmtsuniq
)
  tablespace pas_indx; 
