create table pmsvx1af
(
  pmvxvisn    varchar2(8) default ' ' not null,
  pmvxvsdt    varchar2(8) default ' ' not null,
  pmvxdoca    varchar2(10) default ' ' not null,
  pmvxdoct    varchar2(10) default ' ' not null,
  pmvxcsnr    varchar2(1) default ' ' not null,
  pmvxpost    varchar2(8) default ' ' not null,
  pmvxpind    varchar2(3) default ' ' not null,
  pmvxvloc    varchar2(40) default ' ' not null,
  pmvxcfsg    varchar2(1) default ' ' not null,
  pmvxingp    varchar2(1) default ' ' not null,
  pmvxcpth    varchar2(3) default ' ' not null,
  pmvxhcp1    varchar2(1) default ' ' not null,
  pmvxhcp2    varchar2(1) default ' ' not null,
  pmvxhcp3    varchar2(1) default ' ' not null,
  pmvxhcp4    varchar2(1) default ' ' not null,
  pmvxrhc1    varchar2(10) default ' ' not null,
  pmvxrh1g    varchar2(10) default ' ' not null,
  pmvxrh1c    varchar2(2) default ' ' not null,
  pmvxrhc2    varchar2(10) default ' ' not null,
  pmvxrh2g    varchar2(10) default ' ' not null,
  pmvxrh2c    varchar2(2) default ' ' not null,
  pmvxrhc3    varchar2(10) default ' ' not null,
  pmvxrh3g    varchar2(10) default ' ' not null,
  pmvxrh3c    varchar2(2) default ' ' not null,
  pmvxrhc4    varchar2(10) default ' ' not null,
  pmvxrh4g    varchar2(10) default ' ' not null,
  pmvxrh4c    varchar2(2) default ' ' not null,
  pmvxabrg    varchar2(3) default ' ' not null,
  pmvxcadm    varchar2(3) default ' ' not null,
  pmvxirad    varchar2(3) default ' ' not null,
  pmvxidus    varchar2(3) default ' ' not null,
  pmvxcrav    varchar2(3) default ' ' not null,
  pmvxrcct    varchar2(3) default ' ' not null,
  pmvxapwd    varchar2(3) default ' ' not null,
  pmvxapbd    varchar2(3) default ' ' not null,
  pmvxpowd    varchar2(3) default ' ' not null,
  pmvxpobd    varchar2(3) default ' ' not null,
  pmvxpsty    varchar2(1) default ' ' not null,
  pmvxvalw    varchar2(1) default ' ' not null,
  pmvxpalw    varchar2(1) default ' ' not null,
  pmvxindc    varchar2(1) default ' ' not null,
  pmvxmdav    varchar2(3) default ' ' not null,
  pmvxfrms    varchar2(3) default ' ' not null,
  pmvxcsng    varchar2(3) default ' ' not null,
  pmvxpwgt    number(6,0) default 0 not null,
  pmvxphgt    number(6,0) default 0 not null,
  pmvxdhwr    varchar2(8) default ' ' not null,
  pmvxedc1    varchar2(10) default ' ' not null,
  pmvxedc2    varchar2(10) default ' ' not null,
  pmvxedc3    varchar2(10) default ' ' not null,
  pmvxhome    varchar2(1) default ' ' not null,
  pmvxudf1    varchar2(50) default ' ' not null,
  pmvxudf2    varchar2(50) default ' ' not null,
  pmvxudf3    varchar2(50) default ' ' not null,
  pmvxudf4    varchar2(50) default ' ' not null,
  pmvxudt1    varchar2(13) default ' ' not null,
  pmvxudt2    varchar2(13) default ' ' not null,
  pmvxudt3    varchar2(13) default ' ' not null,
  pmvxudt4    varchar2(13) default ' ' not null,
  pmvxudt5    varchar2(13) default ' ' not null,
  pmvxudt6    varchar2(13) default ' ' not null,
  pmvxcdte    varchar2(8) default ' ' not null,
  pmvxctim    varchar2(8) default ' ' not null,
  pmvxwebc    varchar2(10) default ' ' not null,
  pmvxlupd    varchar2(8) default ' ' not null,
  pmvxlupt    varchar2(8) default ' ' not null,
  pmvxwebu    varchar2(10) default ' ' not null,
  pmvxmhls    varchar2(3) default ' ' not null,
  pmvxpicd    varchar2(9) default ' ' not null,
  pmvxrmor    varchar2(3) default ' ' not null,
  pmvxasut    varchar2(3) default ' ' not null,
  pmvxelps    varchar2(3) default ' ' not null,
  pmvxempl    varchar2(3) default ' ' not null,
  pmvxfinp    varchar2(3) default ' ' not null,
  pmvxoccp    varchar2(3) default ' ' not null,
  pmvxpalc    varchar2(3) default ' ' not null,
  pmvxppal    varchar2(3) default ' ' not null,
  pmvxpppt    varchar2(3) default ' ' not null,
  pmvxpsos    varchar2(3) default ' ' not null,
  pmvxpysp    varchar2(3) default ' ' not null,
  pmvxqldb    varchar2(3) default ' ' not null,
  pmvxread    varchar2(3) default ' ' not null,
  pmvxudin    varchar2(3) default ' ' not null,
  pmvxurea    varchar2(3) default ' ' not null,
  pmvxusac    varchar2(3) default ' ' not null,
  pmvxuvth    varchar2(3) default ' ' not null,
  pmvxintr    varchar2(1) default ' ' not null,
  pmvxlng1    varchar2(3) default ' ' not null,
  pmvxasgc    varchar2(9) default ' ' not null,
  pmvxmhos    varchar2(3) default ' ' not null,
  pmvxdspd    varchar2(8) default ' ' not null,
  pmvxdsif    varchar2(1) default ' ' not null,
  pmvxprmi    varchar2(1) default ' ' not null,
  pmvxprai    varchar2(1) default ' ' not null,
  pmvxpres    varchar2(1) default ' ' not null,
  pmvxuitr    varchar2(1) default ' ' not null,
  pmvxrpoa    varchar2(1) default ' ' not null,
  pmvxrcn1    varchar2(1) default ' ' not null,
  pmvxrcn2    varchar2(1) default ' ' not null,
  pmvxrhfu    varchar2(1) default ' ' not null,
  pmvxrdva    varchar2(1) default ' ' not null,
  pmvxrslo    varchar2(1) default ' ' not null,
  pmvxmloc    varchar2(3) default ' ' not null,
  pmvxpacc    varchar2(3) default ' ' not null,
  pmvxedu1    varchar2(3) default ' ' not null,
  pmvxedu2    varchar2(3) default ' ' not null,
  pmvxedu3    varchar2(3) default ' ' not null,
  pmvxprgm    varchar2(8) default ' ' not null,
  pmvxconf    varchar2(1) default ' ' not null,
  pmvxeocl    varchar2(8) default ' ' not null,
  pmvxsloc    varchar2(3) default ' ' not null,
  pmvxscli    varchar2(3) default ' ' not null,
  pmvxstra    varchar2(3) default ' ' not null,
  pmvxqasn    varchar2(12) default ' ' not null,
  pmvxatcp    varchar2(1) default ' ' not null,
  pmvxatim    varchar2(8) default ' ' not null,
  pmvxitim    varchar2(8) default ' ' not null,
  pmvxhfgn    varchar2(40) default ' ' not null,
  pmvxhfsn    varchar2(40) default ' ' not null,
  pmvxfupi    varchar2(2) default ' ' not null,
  pmvxpoec    varchar2(1) default ' ' not null,
  pmvxpgid    varchar2(3) default ' ' not null,
  pmvxticm    varchar2(3) default ' ' not null,
  pmvxpilc    varchar2(3) default ' ' not null,
  pmvxfvio    varchar2(3) default ' ' not null,
  pmvxfndm    varchar2(19) default ' ' not null,
  pmvxudf5    varchar2(3) default ' ' not null,
  pmvxudf6    varchar2(3) default ' ' not null,
  pmvxudf7    varchar2(3) default ' ' not null,
  pmvxudf8    varchar2(3) default ' ' not null,
  pmvxudf9    varchar2(3) default ' ' not null,
  pmvxud10    varchar2(3) default ' ' not null,
  pmvxud11    varchar2(3) default ' ' not null,
  pmvxud12    varchar2(3) default ' ' not null,
  pmvxud13    varchar2(3) default ' ' not null,
  pmvxud14    varchar2(3) default ' ' not null,
  pmvxud15    varchar2(3) default ' ' not null,
  pmvxteam    varchar2(5) default ' ' not null,
  pmvxnwhc    varchar2(3) default ' ' not null,
  pmvxeddt    varchar2(8) default ' ' not null,
  pmvxphld    varchar2(3) default ' ' not null,
  pmvxploc    varchar2(3) default ' ' not null,
  pmvxdtrt    varchar2(8) default ' ' not null,
  pmvxdflg    varchar2(9) default ' ' not null,
  pmvxfsrc    varchar2(3) default ' ' not null,
  pmvxconm    varchar2(40) default ' ' not null,
  pmvxcpdd    varchar2(8) default ' ' not null,
  pmvxpbmi    varchar2(5) default ' ' not null,
  pmvxcnid    varchar2(10) default ' ' not null,
  pmvxcndt    varchar2(13) default ' ' not null,
  pmvxcase    varchar2(10) default ' ' not null,
  pmvxeafl    varchar2(1) default ' ' not null,
  pmvxadmp    varchar2(1) default ' ' not null,
  pmvxcono    varchar2(1) default ' ' not null,
  pmvxmedh    varchar2(1) default ' ' not null,
  pmvxspar    varchar2(13) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint pmsvx1a1 primary key( 
pmvxvisn)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index pmsvx1a2 on pmsvx1af
(
pmvxvsdt,
pmvxvisn
)
  tablespace pas_indx; 
create unique index pmsvx1a3 on pmsvx1af
(
pmvxmhos,
pmvxvisn
)
  tablespace pas_indx; 
create unique index pmsvx1a4 on pmsvx1af
(
pmvxcdte,
pmvxctim,
pmvxvisn
)
  tablespace pas_indx; 
