create table syshvraf
(
  syhvsys     varchar2(2) default ' ' not null,
  syhvfil     varchar2(2) default ' ' not null,
  syhvhid     varchar2(1) default ' ' not null,
  syhvdes     varchar2(20) default ' ' not null,
  syhvfld     varchar2(4) default ' ' not null,
  syhvidx     varchar2(1) default ' ' not null,
  syhvdtop    varchar2(2) default ' ' not null,
  syhvdbot    varchar2(2) default ' ' not null,
  syhvdlef    varchar2(2) default ' ' not null,
  syhvdrig    varchar2(2) default ' ' not null,
  syhvch01    varchar2(20) default ' ' not null,
  syhvch02    varchar2(20) default ' ' not null,
  syhvch03    varchar2(20) default ' ' not null,
  syhvch04    varchar2(20) default ' ' not null,
  syhvch05    varchar2(20) default ' ' not null,
  syhvch06    varchar2(20) default ' ' not null,
  syhvch07    varchar2(20) default ' ' not null,
  syhvch08    varchar2(20) default ' ' not null,
  syhvch09    varchar2(20) default ' ' not null,
  syhvch10    varchar2(20) default ' ' not null,
  syhvcf01    varchar2(8) default ' ' not null,
  syhvcf02    varchar2(8) default ' ' not null,
  syhvcf03    varchar2(8) default ' ' not null,
  syhvcf04    varchar2(8) default ' ' not null,
  syhvcf05    varchar2(8) default ' ' not null,
  syhvcf06    varchar2(8) default ' ' not null,
  syhvcf07    varchar2(8) default ' ' not null,
  syhvcf08    varchar2(8) default ' ' not null,
  syhvcf09    varchar2(8) default ' ' not null,
  syhvcf10    varchar2(8) default ' ' not null,
  syhver01    varchar2(8) default ' ' not null,
  syhver02    varchar2(8) default ' ' not null,
  syhver03    varchar2(8) default ' ' not null,
  syhver04    varchar2(8) default ' ' not null,
  syhver05    varchar2(8) default ' ' not null,
  syhver06    varchar2(8) default ' ' not null,
  syhver07    varchar2(8) default ' ' not null,
  syhver08    varchar2(8) default ' ' not null,
  syhver09    varchar2(8) default ' ' not null,
  syhver10    varchar2(8) default ' ' not null,
  syhvcw01    number(2,0) default 0 not null,
  syhvcw02    number(2,0) default 0 not null,
  syhvcw03    number(2,0) default 0 not null,
  syhvcw04    number(2,0) default 0 not null,
  syhvcw05    number(2,0) default 0 not null,
  syhvcw06    number(2,0) default 0 not null,
  syhvcw07    number(2,0) default 0 not null,
  syhvcw08    number(2,0) default 0 not null,
  syhvcw09    number(2,0) default 0 not null,
  syhvcw10    number(2,0) default 0 not null,
  syhvcbf     varchar2(8) default ' ' not null,
  syhvspar    varchar2(42) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint syshvra1 primary key( 
syhvsys,
syhvfil,
syhvhid)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
