create table visxdcaf
(
  vsxdvisn    varchar2(8) default ' ' not null,
  vsxdtyda    varchar2(3) default ' ' not null,
  vsxdval1    varchar2(10) default ' ' not null,
  vsxdval2    varchar2(10) default ' ' not null,
  vsxdval3    varchar2(10) default ' ' not null,
  vsxdval4    varchar2(10) default ' ' not null,
  vsxdval5    varchar2(10) default ' ' not null,
  vsxdval6    varchar2(10) default ' ' not null,
  vsxdval7    varchar2(10) default ' ' not null,
  vsxdval8    varchar2(10) default ' ' not null,
  vsxdval9    varchar2(10) default ' ' not null,
  vsxdva10    varchar2(10) default ' ' not null,
  vsxdcod1    varchar2(3) default ' ' not null,
  vsxdcod2    varchar2(3) default ' ' not null,
  vsxdcod3    varchar2(3) default ' ' not null,
  vsxdcod4    varchar2(3) default ' ' not null,
  vsxdcod5    varchar2(3) default ' ' not null,
  vsxdcod6    varchar2(3) default ' ' not null,
  vsxdcod7    varchar2(3) default ' ' not null,
  vsxdcod8    varchar2(3) default ' ' not null,
  vsxdcod9    varchar2(3) default ' ' not null,
  vsxdco10    varchar2(3) default ' ' not null,
  vsxdtxt1    varchar2(80) default ' ' not null,
  vsxdtxt2    varchar2(80) default ' ' not null,
  vsxdtxt3    varchar2(80) default ' ' not null,
  vsxdtxt4    varchar2(80) default ' ' not null,
  vsxdtxt5    varchar2(80) default ' ' not null,
  vsxdtxt6    varchar2(80) default ' ' not null,
  vsxdtxt7    varchar2(80) default ' ' not null,
  vsxdtxt8    varchar2(80) default ' ' not null,
  vsxdtxt9    varchar2(80) default ' ' not null,
  vsxdtx10    varchar2(80) default ' ' not null,
  vsxdyn01    varchar2(1) default ' ' not null,
  vsxdyn02    varchar2(1) default ' ' not null,
  vsxdyn03    varchar2(1) default ' ' not null,
  vsxdyn04    varchar2(1) default ' ' not null,
  vsxdyn05    varchar2(1) default ' ' not null,
  vsxdyn06    varchar2(1) default ' ' not null,
  vsxdyn07    varchar2(1) default ' ' not null,
  vsxdyn08    varchar2(1) default ' ' not null,
  vsxdyn09    varchar2(1) default ' ' not null,
  vsxdyn10    varchar2(1) default ' ' not null,
  vsxddat1    varchar2(8) default ' ' not null,
  vsxdtim1    varchar2(8) default ' ' not null,
  vsxddat2    varchar2(8) default ' ' not null,
  vsxdtim2    varchar2(8) default ' ' not null,
  vsxddat3    varchar2(8) default ' ' not null,
  vsxdtim3    varchar2(8) default ' ' not null,
  vsxddat4    varchar2(8) default ' ' not null,
  vsxdtim4    varchar2(8) default ' ' not null,
  vsxddat5    varchar2(8) default ' ' not null,
  vsxdtim5    varchar2(8) default ' ' not null,
  vsxddat6    varchar2(8) default ' ' not null,
  vsxdtim6    varchar2(8) default ' ' not null,
  vsxddat7    varchar2(8) default ' ' not null,
  vsxdtim7    varchar2(8) default ' ' not null,
  vsxddat8    varchar2(8) default ' ' not null,
  vsxdtim8    varchar2(8) default ' ' not null,
  vsxddat9    varchar2(8) default ' ' not null,
  vsxdtim9    varchar2(8) default ' ' not null,
  vsxdda10    varchar2(8) default ' ' not null,
  vsxdti10    varchar2(8) default ' ' not null,
  vsxddelt    varchar2(1) default ' ' not null,
  vsxdcusr    varchar2(10) default ' ' not null,
  vsxdcdat    varchar2(8) default ' ' not null,
  vsxdctim    varchar2(8) default ' ' not null,
  vsxduusr    varchar2(10) default ' ' not null,
  vsxdudat    varchar2(8) default ' ' not null,
  vsxdutim    varchar2(8) default ' ' not null,
  vsxducid    varchar2(10) default ' ' not null,
  vsxducdt    varchar2(8) default ' ' not null,
  vsxductm    varchar2(8) default ' ' not null,
  vsxdspar    varchar2(100) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint visxdca1 primary key( 
vsxdvisn,
vsxdtyda)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
