create table watextaf
(
wtexcode    varchar2(4),
wtexdesc    varchar2(35),
wtexfldt    varchar2(8),
wtextldt    varchar2(8),
wtexfvdt    varchar2(8),
wtextvdt    varchar2(8),
wtexfsdt    varchar2(8),
wtextsdt    varchar2(8),
wtexfrdt    varchar2(8),
wtextrdt    varchar2(8),
wtexunt     varchar2(3),
wtexpri     varchar2(3),
wtexnot     varchar2(3),
wtexpgp     varchar2(3),
wtexrmr     varchar2(3),
wtexrgp     varchar2(8),
wtexcon     varchar2(6),
wtexpro     varchar2(9),
wtexsrc     varchar2(3),
wtexud1     varchar2(3),
wtexud2     varchar2(3),
wtexud3     varchar2(3),
wtexud4     varchar2(3),
wtexud5     varchar2(3),
wtexud6     varchar2(3),
wtexud7     varchar2(3),
wtexud8     varchar2(3),
wtexsta     varchar2(1),
wtexanl1    varchar2(3),
wtexanl2    varchar2(3),
wtexanl3    varchar2(3),
wtexanl4    varchar2(3),
wtexanm1    varchar2(3),
wtexanm2    varchar2(3),
wtexanm3    varchar2(3),
wtexpowd    varchar2(3),
wtexidyc    varchar2(3),
wtexllsc    varchar2(3),
wtexcrtl    varchar2(1),
wtexadmw    varchar2(3),
wtexincd    varchar2(1),
wtexovon    varchar2(1),
wtexctyp    varchar2(3),
wtexlist    varchar2(3),
wtexfurn    varchar2(8),
wtexturn    varchar2(8),
wtexfpro    varchar2(9),
wtextpro    varchar2(9),
wtexfprs    varchar2(1),
wtextprs    varchar2(1),
wtexfuni    varchar2(3),
wtextuni    varchar2(3),
wtexfcon    varchar2(10),
wtextcon    varchar2(10),
wtexfses    number(5,0),
wtextses    number(5,0),
wtexadty    varchar2(3),
wtexrsta    varchar2(3),
wtexfpad    varchar2(8),
wtextpad    varchar2(8),
wtexfsyd    varchar2(8),
wtextsyd    varchar2(8),
wtexfsud    varchar2(8),
wtextsud    varchar2(8),
wtexfosd    varchar2(8),
wtextosd    varchar2(8),
wtexspa     varchar2(57),
lf          varchar2(1),
constraint watexta1 primary key( 
wtexcode)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create public synonym watextaf for watextaf;
create unique index watexta2 on watextaf
(
wtexdesc,
wtexcode
)
  tablespace pas_indx; 
