create table wattx1af
(
  wttxurno    varchar2(8) default ' ' not null,
  wttxpcod    varchar2(9) default ' ' not null,
  wttxpcnt    varchar2(2) default ' ' not null,
  wttxplst    varchar2(3) default ' ' not null,
  wttxpowd    varchar2(3) default ' ' not null,
  wttxadmw    varchar2(3) default ' ' not null,
  wttxpsty    varchar2(1) default ' ' not null,
  wttxidyc    varchar2(3) default ' ' not null,
  wttxadmf    varchar2(3) default ' ' not null,
  wttxeqr1    varchar2(3) default ' ' not null,
  wttxeqr2    varchar2(3) default ' ' not null,
  wttxpast    varchar2(3) default ' ' not null,
  wttxcnsn    varchar2(1) default ' ' not null,
  wttxntgp    varchar2(1) default ' ' not null,
  wttxpatm    varchar2(8) default ' ' not null,
  wttxuidr    varchar2(10) default ' ' not null,
  wttxleqr    varchar2(3) default ' ' not null,
  wttxdprc    varchar2(9) default ' ' not null,
  wttxdpcn    varchar2(2) default ' ' not null,
  wttxcdte    varchar2(8) default ' ' not null,
  wttxctim    varchar2(8) default ' ' not null,
  wttxwebc    varchar2(10) default ' ' not null,
  wttxlupd    varchar2(8) default ' ' not null,
  wttxlupt    varchar2(8) default ' ' not null,
  wttxwebu    varchar2(10) default ' ' not null,
  wttxctyp    varchar2(3) default ' ' not null,
  wttxeqr3    varchar2(3) default ' ' not null,
  wttxptim    varchar2(8) default ' ' not null,
  wttxpotm    varchar2(8) default ' ' not null,
  wttxpans    varchar2(3) default ' ' not null,
  wttxpant    varchar2(8) default ' ' not null,
  wttx23hr    varchar2(1) default ' ' not null,
  wttxanae    varchar2(3) default ' ' not null,
  wttxboty    varchar2(3) default ' ' not null,
  wttxteam    varchar2(5) default ' ' not null,
  wttxfund    varchar2(3) default ' ' not null,
  wttxward    varchar2(3) default ' ' not null,
  wttxpref    varchar2(3) default ' ' not null,
  wttxnwhc    varchar2(3) default ' ' not null,
  wttxintd    varchar2(3) default ' ' not null,
  wttxmaut    varchar2(1) default ' ' not null,
  wttxexpd    varchar2(8) default ' ' not null,
  wttxtcrs    varchar2(3) default ' ' not null,
  wttxdisc    varchar2(9) default ' ' not null,
  wttxrtim    varchar2(8) default ' ' not null,
  wttxrcli    varchar2(10) default ' ' not null,
  wttxrclp    varchar2(10) default ' ' not null,
  wttxpsah    varchar2(1) default ' ' not null,
  wttxphos    varchar2(3) default ' ' not null,
  wttxprpb    varchar2(3) default ' ' not null,
  wttxaasc    varchar2(4) default ' ' not null,
  wttxud09    varchar2(3) default ' ' not null,
  wttxud10    varchar2(3) default ' ' not null,
  wttxud11    varchar2(3) default ' ' not null,
  wttxud12    varchar2(3) default ' ' not null,
  wttxud13    varchar2(3) default ' ' not null,
  wttxasas    varchar2(3) default ' ' not null,
  wttxspar    varchar2(20) default ' ' not null,
  lf          varchar2(1) default ' ' not null,
constraint wattx1a1 primary key( 
wttxurno,
wttxpcod,
wttxpcnt)
)
tablespace pas_data 
enable primary key using index 
  tablespace pas_indx; 
create unique index wattx1a2 on wattx1af
(
wttxcdte,
wttxurno,
wttxpcod,
wttxpcnt
)
  tablespace pas_indx; 
