. *----------------------------------------------------------------------
. * Include Name  :   CCSEYATD.INC
. *
. * Function      :   CGI variables for CCSEYAFD - ccseyaaf.dat
. *----------------------------------------------------------------------
.  Modifications Done :
.
.  V9.03.00   12/02/2004  Ebon Clements             CAR 45487
.             Created include
. *----------------------------------------------------------------------
.
.Name     Type      Length  Description
.----     ----      ------  -----------
CSEYA001  DIM       4       Extract ID
CSEYA002  DIM       1       Bed Days Accom. User Def 1
CSEYA003  DIM       1       Bed Days Accom. User Def 2
CSEYA004  DIM       1       Bed Days Accom. User Def 3
CSEYA005  DIM       1       Bed Days Accom. Other
CSEYA006  DIM       1       Income Theatre
CSEYA007  DIM       1       Income Accom. User Def 1
CSEYA008  DIM       1       Income Accom. User Def 2
CSEYA009  DIM       1       Income Accom. User Def 3
CSEYA010  DIM       1       Income Accom. Other
CSEYA011  DIM       1       Income Misc. User Def 1
CSEYA012  DIM       1       Income Misc. User Def 2
CSEYA013  DIM       1       Income Misc. User Def 3
CSEYA014  DIM       1       Income Misc. Other
CSEYA015  DIM       1       Exp Theatre Cost Comp 1
CSEYA016  DIM       1       Exp Accom. 1 Cost Comp 1
CSEYA017  DIM       1       Exp Accom. 2 Cost Comp 1
CSEYA018  DIM       1       Exp Accom. 3 Cost Comp 1
CSEYA019  DIM       1       Exp Accom. Other Cost Comp 1
CSEYA020  DIM       1       Exp Misc. 1 Cost Comp 1
CSEYA021  DIM       1       Exp Misc. 2 Cost Comp 1
CSEYA022  DIM       1       Exp Misc. 3 Cost Comp 1
CSEYA023  DIM       1       Exp Misc. Other Cost Comp 1
CSEYA024  DIM       1       Exp Theatre Cost Comp 2
CSEYA025  DIM       1       Exp Accom. 1 Cost Comp 2
CSEYA026  DIM       1       Exp Accom. 2 Cost Comp 2
CSEYA027  DIM       1       Exp Accom. 3 Cost Comp 2
CSEYA028  DIM       1       Exp Accom. Other Cost Comp 2
CSEYA029  DIM       1       Exp Misc. 1 Cost Comp 2
CSEYA030  DIM       1       Exp Misc. 2 Cost Comp 2
CSEYA031  DIM       1       Exp Misc. 3 Cost Comp 2
CSEYA032  DIM       1       Exp Misc. Other Cost Comp 2
CSEYA033  DIM       1       Exp Theatre Cost Comp 3
CSEYA034  DIM       1       Exp Accom. 1 Cost Comp 3
CSEYA035  DIM       1       Exp Accom. 2 Cost Comp 3
CSEYA036  DIM       1       Exp Accom. 3 Cost Comp 3
CSEYA037  DIM       1       Exp Accom. Other Cost Comp 3
CSEYA038  DIM       1       Exp Misc. 1 Cost Comp 3
CSEYA039  DIM       1       Exp Misc. 2 Cost Comp 3
CSEYA040  DIM       1       Exp Misc. 3 Cost Comp 3
CSEYA041  DIM       1       Exp Misc. Other Cost Comp 3
CSEYA042  DIM       1       Exp Theatre Cost Comp 4
CSEYA043  DIM       1       Exp Accom. 1 Cost Comp 4
CSEYA044  DIM       1       Exp Accom. 2 Cost Comp 4
CSEYA045  DIM       1       Exp Accom. 3 Cost Comp 4
CSEYA046  DIM       1       Exp Accom. Other Cost Comp 4
CSEYA047  DIM       1       Exp Misc. 1 Cost Comp 4
CSEYA048  DIM       1       Exp Misc. 2 Cost Comp 4
CSEYA049  DIM       1       Exp Misc. 3 Cost Comp 4
CSEYA050  DIM       1       Exp Misc. Other Cost Comp 4
CSEYA051  DIM       1       Exp Theatre Cost Comp 5
CSEYA052  DIM       1       Exp Accom. 1 Cost Comp 5
CSEYA053  DIM       1       Exp Accom. 2 Cost Comp 5
CSEYA054  DIM       1       Exp Accom. 3 Cost Comp 5
CSEYA055  DIM       1       Exp Accom. Other Cost Comp 5
CSEYA056  DIM       1       Exp Misc. 1 Cost Comp 5
CSEYA057  DIM       1       Exp Misc. 2 Cost Comp 5
CSEYA058  DIM       1       Exp Misc. 3 Cost Comp 5
CSEYA059  DIM       1       Exp Misc. Other Cost Comp 5
.
