.*******************************************************************************
.*                      ACONVARS.INC                                           *
.*        Variables for ACONTACT used by HL7RECVR                              *
.*                                                                             *
.*    Mods:                                                                    *
.*        21/05/2014  Davin            CAR 292355                              *
.*                    Created for hl7recvr from allweb03 variables             *
.*******************************************************************************
ALENC005  DIM       8                       * Service Date (CCYYMMDD)
ALENC006  DIM       8                       * Service Time (HH:MM:SS)
ALENC118  DIM       8                       * Case Review Date
ALREF006  DIM       3                       * Reason for Closure (Category LL)
AUDITKEY  DIM       24                      * Audit Key
CHECKBX1  DIM       1                       * Stay on Waiting List
CHECKBX2  DIM       1                       * Last Encounter
KEYENCTR  DIM       16                      * Key for encounter
MASTREFN  DIM       8                       * Master referral number
NEXTPAGE  DIM       1                       * Nextpage parameter CGI parameter
PRHDUNIQ  FORM      8
RACTVFLG  FORM      1
REDIRECT  DIM       240
SAVIADAT  DIM       8                       * Save internal ref date active
WEBTITLE  DIM       80
