. *----------------------------------------------------------------------
. * Include Name  :   ALLEIDTD.INC
. *
. * Function      :   CGI variables for ALLEIDFD - alleidaf.dat
. *----------------------------------------------------------------------
.  Modifications Done :
.
.  V10.03.00  08/10/2013  Don Nguyen    CAR 286923 
.             Created new.
.
. *----------------------------------------------------------------------
.
.Name     Type      Length  Description
.----     ----      ------  -----------
ALEID001  DIM       8       Referral/Visit Number                       
ALEID002  DIM       180     Original Sending Application (HL7) 
ALEID003  DIM       100     Service (received by HL7 only)     
ALEID004  DIM       50      Referred By Other
ALEID005  DIM       100     Referrer Contact
.
