. *----------------------------------------------------------------------
. * Include Name  :   ALLEMDTD.INC
. *
. * Function      :   CGI variables for ALLEMDFD - allemdaf.dat
. *
. * Modifications :
. *                 V9.08.00  23/03/2007  Jill Habasque CAR 135532
. *                           Created Include
. *----------------------------------------------------------------------
.
.Name     Type      Length Description
.----     ----      ------ -----------
ALEMD001  DIM       8      Referral/Visit number
ALEMD002  DIM       8      Encounter Number
ALEMD003  DIM       8      Medication count
ALEMD004  DIM       20     Medication Code
ALEMD005  DIM       3      Quantity
ALEMD006  DIM       3      Unit
ALEMD007  DIM       4      Duration
ALEMD008  DIM       3      Duration type
ALEMD009  DIM       3      Medication Route
ALEMD010  DIM       3      Medication Type
ALEMD011  DIM       50     Free Text
