. *----------------------------------------------------------------------
. * Include Name  :   ALLPROTD.INC
. *
. * Function      :   CGI variables for ALLPROFD - allproaf.dat
. *----------------------------------------------------------------------
.  Modifications Done :
.
.  V10.06.00  06/05/2015  Ebon Clements     CAR 303890
.             Created include
. *----------------------------------------------------------------------
.Name     Type      Length  Description
.----     ----      ------  -----------
ALPRO001  DIM       3       Department (alldepaf)
ALPRO002  DIM       9       Procedure Code
ALPRO003  DIM       50      Procedure Description
ALPRO004  DIM       9       Equivalent ICD10 Code
ALPRO005  DIM       1       Active (0=No,1=Yes)
ALPRO006  DIM       8       Date Record Created (CCYYMMDD)
ALPRO007  DIM       8       Time Record Created (HH:MM:SS)
ALPRO008  DIM       10      WEB User ID Created (websecaf)
ALPRO009  DIM       8       Date Record Updated (CCYYMMDD)
ALPRO010  DIM       8       Time Record Updated (HH:MM:SS)
ALPRO011  DIM       10      WEB User ID Updated (websecaf)
ALPRO012  DIM       4       HDP Equivalent
ALPRO013  DIM       4       HCP Equivalent

