. *----------------------------------------------------------------------
. * Include Name  :   ALLRHLTD.INC
. *
. * Function      :   CGI variables for ALLRHLFD - allrhlaf.dat
. *----------------------------------------------------------------------
.  Modifications Done :
.
.  V10.00.01  18/05/2010  Ebon Clements CAR 220289
.             Added ALRHL006
.  V9.12.01   14/10/2009  Ebon Clements CAR 207550
.             Created include
. *----------------------------------------------------------------------
.
.Name     Type      Length  Description
.----     ----      ------  -----------
ALRHL001  DIM       8       Referral/Visit Number
ALRHL002  DIM       2       Condition Type
ALRHL003  DIM       3       Unique Number
ALRHL004  DIM       9       Health Condition Code
ALRHL005  DIM       8       Date (CCYYMMDD)
ALRHL006  DIM       9       Code  2
