. *----------------------------------------------------------------------
. * Include Name  :   ALLSUPTD.INC
. *
. * Function      :   CGI variables for ALLSUPFD - allsupaf.dat
. *
. * Modifications :
. *                 V10.03.01 25/03/2014  Patrick Adair CAR 226788
. *                           Added ALSUP007
. *                 V10.00.01 25/03/2010  Ebon Clements CAR 208232
. *                           Added ALSUP005 and ALSUP006
. *                 V9.08.00  10/04/2007  Jill Habasque CAR 135532
. *                           Created Include
. *----------------------------------------------------------------------
.
.Name     Type      Length Description
.----     ----      ------ -----------
ALSUP001  DIM       8      Referral/Visit number
ALSUP002  DIM       8      Encounter Number
ALSUP003  DIM       8      Supply count
ALSUP004  DIM       7      Supply Code
ALSUP005  DIM       3      Supply Quantity
ALSUP006  DIM       19     Supply Price
ALSUP007  DIM       20     Approval Number
