. *----------------------------------------------------------------------
. * Include Name  :   ALLSASTD.INC
. *
. * Function      :   CGI variables for ALLSASFD - allsasaf.dat
. *
. * V10.06.01 14/04/2015  Patrick Adair  CAR 271541
. *           Added Reason for Delete
. * V10.00.00 13/05/2010  Ebon Clements  CAR 220289
. *           Created include
. *----------------------------------------------------------------------
.
.Name     Type      Length Description
.----     ----      ------ -----------
ALSAS001  DIM       8      Visit Number               
ALSAS002  DIM       8      Assessment Date (ccyymmdd)
ALSAS003  DIM       8      Assessment Time (hh:mm:ss)
ALSAS004  DIM       2      Pain Sub-Scale
ALSAS005  DIM       2      Other Symptoms Sub-Scale
ALSAS006  DIM       2      Psychosocial Sub-Scale
ALSAS007  DIM       2      Family/Carer Sub-Scale
ALSAS008  DIM       1      Deleted Flag
ALSAS009  DIM       3      Reason For Delete
