. *----------------------------------------------------------------------
. * Include Name  :   APSMASTD.INC
. *
. * Function      :   CGI variables for APSMASFD - apsmasaf.dat
. * 
. * Modifications :
. *                V9.02.01 21/09/2001 Ebon Clements
. *                         Added all fields to WEB TD
. *----------------------------------------------------------------------
.
.Name     Type      Length Description
.----     ----      ------ -----------
APMAS001   DIM       5     Creditor Code 
APMAS002   DIM       3     Creditor Type                  
APMAS003   DIM       6     Sort Key
APMAS004   DIM       30    Creditor Name 1         
APMAS005   DIM       30    Creditor Name 2                    
APMAS006   DIM       25    Creditor Address Line 1            
APMAS007   DIM       25    Creditor Address Line 2            
APMAS008   DIM       25    Creditor Address Line 3            
APMAS009   DIM       6     Creditor Postcode                  
APMAS010   DIM       15    Creditor Telephone Business        
APMAS011   DIM       15    Creditor Telephone Fax             
APMAS012   DIM       15    Creditor Telephone Modem (EDI)     
APMAS013   DIM       15    Creditor EDI Post Box Details      
APMAS014   DIM       30    Creditor Contact                   
APMAS015   DIM       30    Supplier Name 1                    
APMAS016   DIM       30    Supplier Name 2                    
APMAS017   DIM       25    Supplier Address Line 1            
APMAS018   DIM       25    Supplier Address Line 2            
APMAS019   DIM       25    Supplier Address Line 3            
APMAS020   DIM       6     Supplier Postcode                  
APMAS021   DIM       15    Supplier Telephone Business        
APMAS022   DIM       15    Supplier Telephone Fax             
APMAS023   DIM       15    Supplier Telephone Modem (EDI)     
APMAS024   DIM       15    Supplier EDI Post Box Details      
APMAS025   DIM       30    Supplier Contact                   
APMAS026   DIM       7     B ank State Branch                  
APMAS027   DIM       9     Bank Account                       
APMAS028   DIM       35    Payee Name                         
APMAS029   DIM       15    Purchases Total at Last Purge      
APMAS030   DIM       15    Balance at Last Purge              
APMAS031   DIM       1     Hold Order Input 0=No              
APMAS032   DIM       1     Hold Invoice Input 0=No            
APMAS033   DIM       1     Hold Credit Input 0=No             
APMAS034   DIM       1     Hold Payments 0=No                 
APMAS035   DIM       1     Default Payment Method             
APMAS036   DIM       1     Payment Generation Method          
APMAS037   DIM       2     Default Payment Period             
APMAS038   DIM       3     Default Terms                      
APMAS039   DIM       30    User Defined Reference 1           
APMAS040   DIM       30    P/O Fax or Email Address           
APMAS041   DIM       8     User Defined Date 1                
APMAS042   DIM       8     User Defined Date 2                
APMAS043   DIM       3     User Defined Code 1                
APMAS044   DIM       3     User Defined Code 2                
APMAS045   DIM       1     GST Registered Yes/No 0=No         
APMAS046   DIM       1     User Defined Yes/No 2 0=No         
APMAS047   DIM       7     Supplier Discount                  
APMAS048   DIM       10    Target Sector (HRH DOF)            
APMAS049   DIM       11    ABN Number                         
