.
.  **********************************************************************
.  *                                                                    *
.  *     Include Name : CATCOMTD.INC                                    *
.  *                                                                    *
.  *     Function     : CGI variables for Completed Menus Table         *
.  *                                                                    *
.  *     File Name    : catcomaf.dat                                    *
.  *                                                                    *
.  *     Modifications:                                                 *
.  *        V10.07.00   24.11.2015   Davin          CAR 310749          *
.  *                    Created include                                 *
.  *                                                                    *
.  **********************************************************************
.
CTCOM001  DIM       8                       *  Admission code
CTCOM002  DIM       8                       *  Meal Date (CCYYMMDD)
CTCOM003  DIM       1                       *  Meal Code
CTCOM004  DIM       3                       *  Menu Code for this meal
CTCOM005  DIM       3                       *  Diet Code for this meal
CTCOM006  DIM       3                       *  Ward for this meal
CTCOM007  FORM      1                       *  Serving Size
CTCOM008  FORM      1                       *  Meal Status
CTCOM009  FORM      1                       *  Belt line ticket printed ?
CTCOM010  FORM      1                       *  Menu type printed
CTCOM011  DIM      16                       *  Date & time meal was printed
CTCOM012  DIM       5                       *  Selected Item 01 (from CATITEFD)
CTCOM013  DIM       5                       *  Selected Item 02 (from CATITEFD)
CTCOM014  DIM       5                       *  Selected Item 03 (from CATITEFD)
CTCOM015  DIM       5                       *  Selected Item 04 (from CATITEFD)
CTCOM016  DIM       5                       *  Selected Item 05 (from CATITEFD)
CTCOM017  DIM       5                       *  Selected Item 06 (from CATITEFD)
CTCOM018  DIM       5                       *  Selected Item 07 (from CATITEFD)
CTCOM019  DIM       5                       *  Selected Item 08 (from CATITEFD)
CTCOM020  DIM       5                       *  Selected Item 09 (from CATITEFD)
CTCOM021  DIM       5                       *  Selected Item 10 (from CATITEFD)
CTCOM022  DIM       5                       *  Selected Item 11 (from CATITEFD)
CTCOM023  DIM       5                       *  Selected Item 12 (from CATITEFD)
CTCOM024  DIM       5                       *  Selected Item 13 (from CATITEFD)
CTCOM025  DIM       5                       *  Selected Item 14 (from CATITEFD)
CTCOM026  DIM       5                       *  Selected Item 15 (from CATITEFD)
CTCOM027  DIM       5                       *  Selected Item 16 (from CATITEFD)
CTCOM028  DIM       5                       *  Selected Item 17 (from CATITEFD)
CTCOM029  DIM       5                       *  Selected Item 18 (from CATITEFD)
CTCOM030  DIM       5                       *  Selected Item 19 (from CATITEFD)
CTCOM031  DIM       5                       *  Selected Item 20 (from CATITEFD)
CTCOM032  DIM      10                       *  Name of Dietician
CTCOM033  DIM      20                       *  Dietician's Pager Number
CTCOM034  DIM       3                       *  Other Details (Cat MM)
CTCOM035  DIM       3                       *  Diet Type (Cat MJ)
CTCOM036  DIM       3                       *  Assistance Lvl (Dietary req.)
.
CTCOB001  DIM       3                       *  Diet Code for meal type 1
CTCOB002  DIM       3                       *  Diet 2 for meal type 1
CTCOB003  DIM       3                       *  Diet 3 for meal type 1
CTCOB004  DIM       3                       *  Diet 4 for meal type 1
CTCOB005  DIM       3                       *  Diet 5 for meal type 1
CTCOL001  DIM       3                       *  Diet Code for meal type 3
CTCOL002  DIM       3                       *  Diet 2 for meal type 3
CTCOL003  DIM       3                       *  Diet 3 for meal type 3
CTCOL004  DIM       3                       *  Diet 4 for meal type 3
CTCOL005  DIM       3                       *  Diet 5 for meal type 3
CTCOD001  DIM       3                       *  Diet Code for meal type 5
CTCOD002  DIM       3                       *  Diet 2 for meal type 5
CTCOD003  DIM       3                       *  Diet 3 for meal type 5
CTCOD004  DIM       3                       *  Diet 4 for meal type 5
CTCOD005  DIM       3                       *  Diet 5 for meal type 5
.
