. *----------------------------------------------------------------------
. * Include Name  :   CCSHLCTD.INC
. *
. * Function      :   CGI variables for CCSHLCFD - ccshlcaf.dat
. *----------------------------------------------------------------------
.  Modifications Done :
.
.  V9.03.00   01/03/2004  Ebon Clements             CAR 46515
.             Created include
. *----------------------------------------------------------------------
.
.Name     Type      Length  Description
.----     ----      ------  -----------
CSHLC001  DIM       2       Hospital Code
CSHLC002  DIM       30      patmastf - Directory
CSHLC003  DIM       30      pattranf - Directory
CSHLC004  DIM       30      patmissf - Directory
CSHLC005  DIM       30      patdschf - Directory
CSHLC006  DIM       30      patvisaf - Directory
CSHLC007  DIM       30      patmoprf - Directory
CSHLC008  DIM       30      patmdisf - Directory
CSHLC009  DIM       30      aaedetaf - Directory
CSHLC010  DIM       30      aaedisaf - Directory
CSHLC011  DIM       30      outsitaf - Directory
CSHLC012  DIM       30      outbokbf - Directory
CSHLC013  DIM       30      ccidptaf - Directory
CSHLC014  DIM       30      patmasxf - Directory
CSHLC015  DIM       30      patinvrf - Directory
CSHLC016  DIM       30      patdtraf - Directory
CSHLC017  DIM       30      patcodef - Directory
CSHLC018  DIM       30      patmmbsf - Directory
CSHLC019  DIM       30      patdoctf - Directory
CSHLC020  DIM       30      paticuaf - Directory (Southland)
CSHLC021  DIM       30      allrefaf - Directory
CSHLC022  DIM       30      allencaf - Directory
CSHLC023  DIM       30      emrvisaf - Directory
CSHLC024  DIM       30      oprdetaf - Directory
