.----------------------------------------------------------------------
. Function : Convert single quote character in name/description
.----------------------------------------------------------------------
. V10.15.00 19/11/2019  Thanh T        TSK 0882708
.           Initial Version
.----------------------------------------------------------------------
.
. NAME    TYPE      LENGTH     DESCRIPTION
. ----    ----      ------     -----------
CNVQTDES  DIM       80         Input/output name/description
CNVQTSTR  DIM       80         Start string before single quote
CNVQTEND  DIM       80         End string after single quote 
