. *----------------------------------------------------------------------
. * Include Name  :   EMRACPTD.INC
. *
. * Function      :   CGI Variables for EMRACPFD - emracpaf
. *
. * Mods          :   V11.01.00 31/05/2021 Tony Hui        TSK 0905305
. *                             Created include
. *----------------------------------------------------------------------
.Name     Type      Length  Description
.----     ----      ------  -----------
EMACP001  DIM       30      ECDG Code
EMACP002  DIM       8       Date Effective From (CCYYMMDD)
EMACP003  DIM       8       Date Effective To (CCYYMMDD)
EMACP004  DIM       10      Age 0 to 14 
EMACP005  DIM       10      Age 80+
EMACP006  DIM       10      Triage Category 1
EMACP007  DIM       10      Triage Category 2
EMACP008  DIM       10      Triage Category 3
EMACP009  DIM       10      Triage Category 4
EMACP010  DIM       10      Triage Category 5
EMACP011  DIM       1       Inactive Flag
