. *----------------------------------------------------------------------
. * Include Name  :   EMRRESTD.INC
. *
. * Function      :   CGI variables for EMRRESFD - emrresaf.dat
. *----------------------------------------------------------------------
.  Modifications Done :
.
.  V10.03.00  22/10/2012  Ebon Clements CAR 266929
.             Created include
. *----------------------------------------------------------------------
.
.Name     Type      Length  Description
.----     ----      ------  -----------
EMRES001  DIM       3       Research Code (Cat eu)
EMRES002  DIM       8       Start Date (CCYYMMDD)
EMRES003  DIM       8       End Date (CCYYMMDD)
EMRES004  DIM       1       Active/Inactive
.
