. V5.06.001 01/12/1998
.*------------------------------------------------------------
.* Include Name  :    HL7NTEFD.INC
.*
.* Function      :    File Definition include for WEB
.*                    HL7 NTE SEGMENT
.*
.*------------------------------------------------------------
.
.NAME     TYPE      Length Description
.----     ----      ------ -----------
NTE001    DIM       1      Set ID - Notes and Comments
NTE002    DIM       1      Source of Comment
NTE003    DIM       127    Comment 
