. * Include Name  :   IBASCETD.INC
. *
. * Function      :   CGI variables for IBASCEFD - ibasceaf.dat
. *----------------------------------------------------------------------
.  Modifications Done :
.
.         V9.10.00  29/05/2008  Mike Laming   CAR 152286
.                   Created include
. *----------------------------------------------------------------------
.
.Name     Type      Length  Description
.----     ----      ------  -----------
IBSCE001  DIM       8       U/R Number                      ibseurno
IBSCE002  DIM       8       Visit Number                    ibsevisn
IBSCE003  DIM       8       Counter                         ibsecntr
IBSCE004  DIM       1       Flag Field 01 (0=No,1=Yes)      ibsefl01
IBSCE005  DIM       1       Flag Field 02 (0=No,1=Yes)      ibsefl02
IBSCE006  DIM       1       Flag Field 03 (0=No,1=Yes)      ibsefl03
IBSCE007  DIM       1       Flag Field 04 (0=No,1=Yes)      ibsefl04
IBSCE008  DIM       1       Flag Field 05 (0=No,1=Yes)      ibsefl05
IBSCE009  DIM       1       Flag Field 06 (0=No,1=Yes)      ibsefl06
IBSCE010  DIM       1       Flag Field 07 (0=No,1=Yes)      ibsefl07
IBSCE011  DIM       1       Flag Field 08 (0=No,1=Yes)      ibsefl08
IBSCE012  DIM       1       Flag Field 09 (0=No,1=Yes)      ibsefl09
IBSCE013  DIM       1       Flag Field 10 (0=No,1=Yes)      ibsefl10
IBSCE014  DIM       1       Flag Field 11 (0=No,1=Yes)      ibsefl11
IBSCE015  DIM       1       Flag Field 12 (0=No,1=Yes)      ibsefl12
IBSCE016  DIM       1       Flag Field 13 (0=No,1=Yes)      ibsefl13
IBSCE017  DIM       1       Flag Field 14 (0=No,1=Yes)      ibsefl14
IBSCE018  DIM       1       Flag Field 15 (0=No,1=Yes)      ibsefl15
IBSCE019  DIM       1       Flag Field 16 (0=No,1=Yes)      ibsefl16
IBSCE020  DIM       1       Flag Field 17 (0=No,1=Yes)      ibsefl17
IBSCE021  DIM       1       Flag Field 18 (0=No,1=Yes)      ibsefl18
IBSCE022  DIM       1       Flag Field 19 (0=No,1=Yes)      ibsefl19
IBSCE023  DIM       1       Flag Field 20 (0=No,1=Yes)      ibsefl20
IBSCE024  DIM       1       Numeric Code  1  ( 0 to 9 )     ibsecd01
IBSCE025  DIM       1       Numeric Code  2  ( 0 to 9 )     ibsecd02
IBSCE026  DIM       1       Numeric Code  3  ( 0 to 9 )     ibsecd03
IBSCE027  DIM       1       Numeric Code  4  ( 0 to 9 )     ibsecd04
IBSCE028  DIM       1       Numeric Code  5  ( 0 to 9 )     ibsecd05
IBSCE029  DIM       1       Numeric Code  6  ( 0 to 9 )     ibsecd06
IBSCE030  DIM       1       Numeric Code  7  ( 0 to 9 )     ibsecd07
IBSCE031  DIM       1       Numeric Code  8  ( 0 to 9 )     ibsecd08
IBSCE032  DIM       1       Numeric Code  9  ( 0 to 9 )     ibsecd09
IBSCE033  DIM       1       Numeric Code  10 ( 0 to 9 )     ibsecd10
IBSCE034  DIM       1       Numeric Code  11 ( 0 to 9 )     ibsecd11
IBSCE035  DIM       1       Numeric Code  12 ( 0 to 9 )     ibsecd12
IBSCE036  DIM       1       Numeric Code  13 ( 0 to 9 )     ibsecd13
IBSCE037  DIM       1       Numeric Code  14 ( 0 to 9 )     ibsecd14
IBSCE038  DIM       1       Numeric Code  15 ( 0 to 9 )     ibsecd15
IBSCE039  DIM       6       Small Char Fld 01               ibsesd01
IBSCE040  DIM       6       Small Char Fld 02               ibsesd02
IBSCE041  DIM       8       Small Char Fld 03               ibsesd03
IBSCE042  DIM       8       Small Char Fld 04               ibsesd04
IBSCE043  DIM       10      Small Char Fld 05               ibsesd05
IBSCE044  DIM       10      Small Char Fld 06               ibsesd06
IBSCE045  DIM       50      Medium Free Format 01           ibsemd01
IBSCE046  DIM       50      Medium Free Format 02           ibsemd02
IBSCE047  DIM       50      Medium Free Format 03           ibsemd03
IBSCE048  DIM       50      Medium Free Format 04           ibsemd04
IBSCE049  DIM       50      Medium Free Format 05           ibsemd05
IBSCE050  DIM       50      Medium Free Format 06           ibsemd06
IBSCE051  DIM       50      Medium Free Format 07           ibsemd07
IBSCE052  DIM       50      Medium Free Format 08           ibsemd08
IBSCE053  DIM       50      Medium Free Format 09           ibsemd09
IBSCE054  DIM       50      Medium Free Format 10           ibsemd10
IBSCE055  DIM       50      Medium Free Format 11           ibsemd11
IBSCE056  DIM       50      Medium Free Format 12           ibsemd12
IBSCE057  DIM       200     XLarge Free Format 01           ibsexl01
IBSCE058  DIM       200     XLarge Free Format 02           ibsexl02
IBSCE059  DIM       200     XLarge Free Format 03           ibsexl03
IBSCE060  DIM       200     XLarge Free Format 04           ibsexl04
IBSCE061  DIM       200     XLarge Free Format 05           ibsexl05
IBSCE062  DIM       8       Date Record Created (CCYYMMDD)  ibsecdat
IBSCE063  DIM       8       Time Record Created (HH:MM:SS)  ibsectim
IBSCE064  DIM       10      WEB User ID Created (websecaf)  ibsecuid
IBSCE065  DIM       8       Date Record Updated (CCYYMMDD)  ibseudat
IBSCE066  DIM       8       Time Record Updated (HH:MM:SS)  ibseutim
IBSCE067  DIM       10      WEB User ID Updated (websecaf)  ibseuuid
IBSCE068  DIM       40      Spare Variable    ibsespar
