.  **********************************************************************
.  *                                                                    *
.  *     Include Name : JHSTF1FD.INC                                    *
.  *                                                                    *
.  *     Function     : File Definition include for                     *
.  *                    JHS NEW THEATRE FEES FILE                       *
.  *                                                                    *
.  *     File Type    : SQL                                             *
.  *                                                                    *
.  *     File Name    : newtfeaf.dat                                    *
.  *                                                                    *
.  *     Keys         : KEY 23                                          *
.  *                                                                    *
.  **********************************************************************
.
JHSTF1A1   IFILE   SQL, FIXED=133, KEY="U1-3,4-9,10-17,18-18,19-23"
.
. NAME     TYPE   LENGTH   PHYSICAL  START LOC.   DESCRIPTION
. ----     ----   ------   --------  ----------   -----------
.
.      SAME FORMAT AS JHSTFEFD
.
