.--------------------------------------------------------------------------
.MEHREVTD.INC
.---------------------------------------------------------------------------
.  Mental Health Legal status Review History file
.
MEHRV001  DIM       8    Admission number
MEHRV002  DIM       8    Date of review
MEHRV003  DIM       5    Time of review (HH:MM)
MEHRV004  FORM      1    Review decision
MEHRV005  DIM       8    Date of new legal status (Yes only)
MEHRV006  DIM       5    Time of new legal status (Yes only)
MEHRV007  DIM       3    Reason for decision (Cat DE) (No only)
MEHRV008  DIM       8    Date of next review
.
