. *----------------------------------------------------------------------
. * Include Name  :   NZPCMTTD.INC
. *
. * Function      :   CGI variables for NZPCMTFD - nzpcmtaf.dat
. *----------------------------------------------------------------------
.
.  Modifications  :
.
.
.Name     Type      Length   Description
.----     ----      ------   -----------
NZCMT001  DIM       3        Claim code
NZCMT002  DIM       6        Contract/Health Fund
NZCMT003  DIM       1        Record Type E=Either O=Overnight D=Daycase
NZCMT004  DIM       9        Contract Procedure code
NZCMT005  DIM       1        Item Type 0=Proc 1=Misc.
NZCMT006  DIM       6        Counter
NZCMT007  DIM       1        Field Type 0=Include 1=Exclude
NZCMT008  DIM       9        Procedure/Misc.Charge Code
NZCMT009  DIM       3        Category FI Code
