. V9.08.003 22/11/2006 JH  Added hospital code                               
. V9.08.004 22/11/2006                                                       
. V9.08.005 22/11/2006                                                       
. *----------------------------------------------------------------------
. * Include Name  :   NZPCF1FD.INC
. *
. * Function      :   File Def'n Include for New Zealand Private                
. *                   NZ Private Contract Funding File   
. *
. * File Type     :   SQL
. *
. * File Name     :   nzpcf1af.dat
. *
. *----------------------------------------------------------------------
.
.Data File Definition
.--------------------
NZPCFN11   IFILE    SQL, FIXED=391, KEY="U1-3,4-6,7-12,13-21,22-22,23-30"       
.
.Name     Type      Length Physical Start Description
.----     ----      ------ -------- ----- -----------
. Same layout as NZPCFNFD
.
.End of Record                      391  
.
