. *----------------------------------------------------------------------
. * Include Name  :   NZPPTYTD.INC
. *
. * Function      :   CGI Vars for NZPPTYFD.INC - nzpptyaf                      
. *
. * File Name     :   nzpptyaf.dat
. *
. * V9.08.00  02/01/2007  Ebon Clements CAR 126779
. *           Created include
. *----------------------------------------------------------------------
.
.Name     Type      Length Description
.----     ----      ------ -----------
NZPTY001  DIM       3      Related Provider Type
NZPTY002  DIM       30     Description
NZPTY003  DIM       1      Related Provider Indicator
NZPTY004  DIM       3      Cost Centre
NZPTY005  DIM       5      Account Code
NZPTY006  DIM       3      Sub Account Code
NZPTY007  DIM       3      GST Cost Centre
NZPTY008  DIM       5      GST Account Code
NZPTY009  DIM       3      GST Sub Account Code
NZPTY010  DIM       1      Active/Inactive 0=Active 1=Inactive
.
