. *----------------------------------------------------------------------
. * Include Name  :   OPRPRFFD.INC
. *
. * Function      :   CGI variables for OPRPRFFD -oprprfaf                      
. *
. * File Name     :   oprprfaf.dat
. *
. * Modifications :
. * V9.04.00 25/02/2005 Lina Vo                  CAR 56404
. *          Created include
. *----------------------------------------------------------------------
.
.Name     Type      Length Description
.----     ----      ------ -----------
OPPRF001  DIM       10     Unique id for theatre booking      
OPPRF002  DIM       1      Tram Number                   
OPPRF003  DIM       15     Preference Code                    
OPPRF004  DIM       6      Doctor Code                        
OPPRF005  DIM       3      Quantity                           
