. *----------------------------------------------------------------------
. * Include Name  :   OUTCPBTD.INC
. *
. * Function      :   CGI variables for OUTCPBFD - outcpbaf.dat
. *
. * Modifications :
. * V10.06.00  14/05/2015  Ebon Clements     CAR 303890                        
. *            Created Include                     
. *----------------------------------------------------------------------
.
.Name     Type      Length Description
.----     ----      ------ -----------
OTCPB001  DIM       6      Site Code
OTCPB002  DIM       6      Clinic Cype
OTCPB003  DIM       9      Problem Code
OTCPB004  DIM       70     Problem Description
OTCPB005  DIM       9      Equivalent ICD10 Code
OTCPB006  DIM       1      Active (0=No,1=Yes
OTCPB007  DIM       8      Date Record Created (CCYYMMDD
OTCPB008  DIM       8      Time Record Created (HH:MM:SS)
OTCPB009  DIM       10     WEB User ID Created (websecaf
OTCPB010  DIM       8      Date Record Updated (CCYYMMDD
OTCPB011  DIM       8      Time Record Updated (HH:MM:SS)
OTCPB012  DIM       10     WEB User ID Updated (websecaf)

