. *----------------------------------------------------------------------
. * Include Name  :   OUTXSCTD.INC
. *
. * Function      :   CGI Variables for OUTXSCFD - outxscaf
. *
. * Mods          :   V9.02.01  12/11/2002  Sylvek Litewka
. *                   Created include
. *----------------------------------------------------------------------
.
.Name     Type      Length   Description
.----     ----      ------   -----------
OUTXS001  DIM       8        User Def Date 1
OUTXS002  DIM       8        User Def Date 2
OUTXS003  DIM       8        User Def Date 3
OUTXS004  DIM       8        User Def Date 4
OUTXS005  DIM       8        User Def Date 5
OUTXS006  DIM       8        User Def Date 6
OUTXS007  DIM       3        User Def Code 1
OUTXS008  DIM       3        User Def Code 2
OUTXS009  DIM       3        User Def Code 3
OUTXS010  DIM       3        User Def Code 4
OUTXS011  DIM       3        User Def Code 5
OUTXS012  DIM       3        User Def Code 6
OUTXS013  DIM       3        User Def Code 7
OUTXS014  DIM       3        User Def Code 8
OUTXS015  DIM       3        User Def Code 9
OUTXS016  DIM       3        User Def Code 10
OUTXS017  DIM       3        User Def Code 11
OUTXS018  DIM       3        User Def Code 12
OUTXS019  DIM       3        User Def Code 13
OUTXS020  DIM       3        User Def Code 14
OUTXS021  DIM       3        User Def Code 15
OUTXS022  DIM       3        User Def Code 16
OUTXS023  DIM       3        User Def Code 17
OUTXS024  DIM       3        User Def Code 18
OUTXS025  DIM       3        User Def Code 19
OUTXS026  DIM       3        User Def Code 20
OUTXS027  DIM       6        User Def Doctor 1
OUTXS028  DIM       6        User Def Doctor 2
OUTXS029  DIM       6        User Def Doctor 3
OUTXS030  FORM      12.2     User Def Amount 1
OUTXS031  FORM      12.2     User Def Amount 2
OUTXS032  DIM       40       User Def Comment 1
OUTXS033  DIM       40       User Def Comment 2
OUTXS034  DIM       40       User Def Comment 3
OUTXS035  DIM       40       User Def Comment 4
OUTXS036  DIM       40       User Def Comment 5
OUTXS037  DIM       40       User Def Comment 6
OUTXS038  DIM       5        User Def Time 1
OUTXS039  DIM       5        User Def Time 2
OUTXS040  DIM       5        User Def Time 3
OUTXS041  DIM       5        User Def Time 4
OUTXS042  DIM       5        User Def Time 5
OUTXS043  DIM       5        User Def Time 6
