. *----------------------------------------------------------------------
. * Include Name  :   PATBRDTD.INC
. *
. * Function      :   CGI variables for PATBRDTD - Boarders Details file
. *----------------------------------------------------------------------
.  Modifications Done :
.
.  V10.02.02  05/05/2011  Peter Vela    CAR 240705
.             Added Title    
.  V10.02.01  08/06/2011  Peter Vela    CAR 240705
.             Created include
. *----------------------------------------------------------------------
.
.Name     Type      Length  Description
.----     ----      ------  -----------
PTBRD001  DIM       10      Unique Boarder Number
PTBRD002  DIM       8       Patient U/R No
PTBRD003  DIM       8       Admission Number
PTBRD004  DIM       2       Count
PTBRD005  DIM       8       Linked U/R No (existing Reg Pat)
PTBRD030  DIM       4       Title
PTBRD006  DIM       35      Surname
PTBRD007  DIM       35      Given Name
PTBRD008  DIM       1       Gender
PTBRD009  DIM       8       Date of Birth
PTBRD010  DIM       35      Address Line 1
PTBRD011  DIM       35      Address Line 2
PTBRD012  DIM       35      Address Line 3
PTBRD013  DIM       35      Address Line 4
PTBRD014  DIM       8       Postcode
PTBRD015  DIM       20      Home Phone
PTBRD016  DIM       20      Work Phone
PTBRD017  DIM       20      Mobile Phone
PTBRD018  DIM       50      Email Address
PTBRD019  DIM       3       Hospital Code
PTBRD020  DIM       8       Boarder Start Date
PTBRD021  DIM       8       Boarder Start Time
PTBRD022  DIM       8       Boarder End Date
PTBRD023  DIM       8       Boarder End Time
PTBRD024  DIM       10      User who created record
PTBRD025  DIM       8       Date record created
PTBRD026  DIM       8       Time record created
PTBRD027  DIM       10      User who updated record
PTBRD028  DIM       8       Date record updated
PTBRD029  DIM       8       Time record updated
