. *----------------------------------------------------------------------
. * Include Name  :   PATFHITD.INC
. *
. * Function      :   CGI variables for Overnight tables
. * Modifications :
. *
. *        V11.01.01 15/10/2021 J.Tan   TSK 0880410
. *                  Created
. *----------------------------------------------------------------------
.
.  Modifications  :
.
.Health Fund On Hold Invoice
.
.Name     Type      Length   Description
.----     ----      ------   -----------
PTFHI001  DIM       3        Hospital ID (pathspaf)
PTFHI002  DIM       6        Health Fund (patfn1af)
PTFHI003  DIM       2        System Indicator
PTFHI004  DIM       8        Hold Invoice From date (ccyymmdd)
PTFHI005  DIM       3        On Hold Reason (Cat rh)
PTFHI006  DIM       80       Decription for On Hold
.
