. *----------------------------------------------------------------------
. * Include Name  :   PATFAPTD.INC
. *
. * Function      :   CGI variables for PATFAPTD - patfapaf.dat
. *----------------------------------------------------------------------
.  Modifications Done :     
.                      
.  V9.12.01   28.10.2009  Jill Parkinson CAR 174079
.             Created include
. *----------------------------------------------------------------------
.Name     Type      Length  Description
.----     ----      ------  -----------
PTFAP001  DIM       3       Claim Code (Cat CL)
PTFAP002  DIM       3       Action Plan (Cat AK)
PTFAP003  DIM       3       (Cat FA)Future Action Code 1
PTFAP004  DIM       3       No of days from initiate date
PTFAP005  DIM       1       Print Letter 1
PTFAP006  DIM       1       Print Invoice 1
PTFAP007  DIM       3       Occupation Group 1 (Cat w0)
PTFAP008  DIM       3       (Cat FA)Future Action Code 2
PTFAP009  DIM       3       No of days from initiate date 2
PTFAP010  DIM       1       Print Letter 2
PTFAP011  DIM       1       Print Invoice 2
PTFAP012  DIM       3       Occupation Group 2 (Cat w0)
PTFAP013  DIM       3       (Cat FA)Future Action Code 3
PTFAP014  DIM       3       No of days from initiate date 3
PTFAP015  DIM       1       Print Letter 3
PTFAP016  DIM       1       Print Invoice 3
PTFAP017  DIM       3       Occupation Group 3 (Cat w0)
PTFAP018  DIM       3       (Cat FA)Future Action Code 4
PTFAP019  DIM       3       No of days from initiate date 4
PTFAP020  DIM       1       Print Letter 4
PTFAP021  DIM       1       Print Invoice 4
PTFAP022  DIM       3       Occupation Group 4 (Cat w0)
PTFAP023  DIM       3       (Cat FA)Future Action Code 5
PTFAP024  DIM       3       No of days from initiate date 5
PTFAP025  DIM       1       Print Letter 5
PTFAP026  DIM       1       Print Invoice 5
PTFAP027  DIM       3       Occupation Group 5 (Cat w0)
PTFAP028  DIM       3       (Cat FA)Future Action Code 6
PTFAP029  DIM       3       No of days from initiate date 6
PTFAP030  DIM       1       Print Letter 6
PTFAP031  DIM       1       Print Invoice 6
PTFAP032  DIM       3       Occupation Group 6 (Cat w0)
PTFAP033  DIM       3       (Cat FA)Future Action Code 7
PTFAP034  DIM       3       No of days from initiate date 7
PTFAP035  DIM       1       Print Letter 7
PTFAP036  DIM       1       Print Invoice 7
PTFAP037  DIM       3       Occupation Group 7 (Cat w0)
PTFAP038  DIM       3       (Cat FA)Future Action Code 8
PTFAP039  DIM       3       No of days from initiate date 8
PTFAP040  DIM       1       Print Letter 8
PTFAP041  DIM       1       Print Invoice 8
PTFAP042  DIM       3       Occupation Group 8 (Cat w0)
PTFAP043  DIM       3       (Cat FA)Future Action Code 9
PTFAP044  DIM       3       No of days from initiate date 9
PTFAP045  DIM       1       Print Letter 9
PTFAP046  DIM       1       Print Invoice 9
PTFAP047  DIM       3       Occupation Group 9 (Cat w0)
PTFAP048  DIM       3       (Cat FA)Future Action Code 10
PTFAP049  DIM       3       No of days from initiate date 10
PTFAP050  DIM       1       Print Letter 10
PTFAP051  DIM       1       Print Invoice 10
PTFAP052  DIM       3       Occupation Group 10 (Cat w0)
+
