. *----------------------------------------------------------------------
. * Include Name  :   PATIPRTD.INC
. *
. * Function      :   CGI variables for PATIPRFD - patipraf.dat
. *
. * Modifications :   
. *                  V10.03.01 11/08/2011 J.Tan   CAR 237245
. *                            Changed Police No to Amt 
. *                   V9.09.01 18/04/2011 - J.Tan  New TD CAR 237245
. *----------------------------------------------------------------------
.
.Name     Type      Length Description
.----     ----      ------ -----------
PTIPR001  DIM      8       Admission Number
PTIPR002  DIM      8       Invoice Number
PTIPR003  DIM      3       Count
PTIPR004  DIM      40      Medical Claim
PTIPR005  FORM     12.2    Policy Amount
PTIPR006  DIM      32      Account Holder
PTIPR007  DIM      15      CPF Number
PTIPR008  FORM     12.2    Amount
