. *----------------------------------------------------------------------
. * Include Name  :   PMSRFLTD.INC
. *
. * Function      :   CGI variables for PMSADCFD - pmsadcaf.dat
. *----------------------------------------------------------------------
.  Modifications Done :
.
.  V9.09.00   05/10/2007  Jill Habasque CAR 153381
.             Created include
. *----------------------------------------------------------------------
PMADC001  DIM       6      Outcome Code
PMADC002  DIM       30     Description
PMADC003  DIM       1      ACHS Indicator 1=Yes
PMADC004  DIM       1      Deceased Indicator 1=Yes
PMADC005  DIM       3      Infection Code (Category IY)
PMADC006  DIM       100    Short Definition
PMADC007  DIM       1      Valid Grade 1 (1=Yes)
PMADC008  DIM       1      Valid Grade 2 (1=Yes)
PMADC009  DIM       1      Valid Grade 3 (1=Yes)
PMADC010  DIM       1      Valid Grade 4 (1=Yes)
PMADC011  DIM       1      Valid Grade 5 (1=Yes)
PMADC012  DIM       1      Valid Grade 6 (1=Yes)
PMADC013  DIM       1      Valid Grade 7 (1=Yes)
PMADC014  DIM       1      Valid Grade 8 (1=Yes)
PMADC015  DIM       1      Valid Grade 9 (1=Yes)
PMADC016  DIM       1      Valid Grade 10 (1=Yes)
PMADC017  DIM       1      Valid Grade N/A (1=Yes)
PMADC018  DIM       1      Inactive (1=Yes)
