. *----------------------------------------------------------------------
. * Include Name  :   PMSARVTD.INC
. *
. * Function      :   CGI variables for PMSARVFD - pmsarvaf.dat
. *----------------------------------------------------------------------
.  Modifications Done :
.
.  V10.03.02  11/11/2013  Ebon Clements     CAR 291974
.             Changed category of PMARV009
.  V10.03.01  28/10/2013  Ebon Clements     CAR 291974
.             Changed category of PMARV008
.  V10.03.00  20/09/2013  Ebon Clements     CAR 275205
.             Created include
. *----------------------------------------------------------------------
.
.Name     Type      Length  Description
.----     ----      ------  -----------
PMARV001  DIM       10      Admission Request Number
PMARV002  DIM       3       Type of Review
PMARV003  DIM       3       Counter
PMARV004  DIM       8       Date of Review (CCYYMMDD)
PMARV005  DIM       8       Time of Review (hh:mm:ss)
PMARV006  DIM       8       U/R Number
PMARV007  DIM       8       Visit Number
PMARV008  DIM       3       Review Status 
.                           Type of Review 001 - Pre Anaesthetic (Cat ym)
.                                          002 - Clinical Review (Cat yl)
PMARV009  DIM       3       Type of Bed Required (Cat yj)
PMARV010  DIM       1       Patient Suitable for Another Hospit
PMARV011  DIM       3       Other Hospital Code (pathspaf)
PMARV012  DIM       4       ASA Score
PMARV013  DIM       8       Review Status End Date (CCYYMMDD)
PMARV014  DIM       8       User Defined Date 1 (CCYYMMDD)
PMARV015  DIM       8       User Defined Date 2 (CCYYMMDD)
PMARV016  DIM       8       User Defined Date 3
PMARV017  DIM       8       User Defined Date 4 (CCYYMMDD)
PMARV018  DIM       8       User Defined Date 5 (CCYYMMDD)
PMARV019  DIM       8       User Defined Time 1 (HH:MM:SS)
PMARV020  DIM       8       User Defined Time 2 (HH:MM:SS)
PMARV021  DIM       8       User Defined Time 3 (HH:MM:SS)
PMARV022  DIM       8       User Defined Time 4 (HH:MM:SS)
PMARV023  DIM       8       User Defined Time 5 (HH:MM:SS)
PMARV024  DIM       1       User Defined Y/N 1
PMARV025  DIM       1       User Defined Y/N 2
PMARV026  DIM       1       User Defined Y/N 3
PMARV027  DIM       1       User Defined Y/N 4
PMARV028  DIM       1       User Defined Y/N 5
PMARV029  DIM       10      User Defined HCP 1
PMARV030  DIM       10      User Defined HCP 2
PMARV031  DIM       10      User Defined HCP 3
PMARV032  DIM       10      User Defined HCP 4
PMARV033  DIM       10      User Defined HCP 5
PMARV034  DIM       3       User Definded Coded Field 1
PMARV035  DIM       3       User Definded Coded Field 2
PMARV036  DIM       3       User Definded Coded Field 3
PMARV037  DIM       3       User Definded Coded Field 4
PMARV038  DIM       3       User Definded Coded Field 5

