. *----------------------------------------------------------------------
. * Include Name  :   PMSBTHTD.INC
. *
. * Function      :   CGI variables for PMSBTHFD - pmsbthaf.dat
. *----------------------------------------------------------------------
.  Modifications Done :
.
.  V10.00.00  26/07/2010  Jill Parkinson CAR 222551
.             Created include
.
. *----------------------------------------------------------------------
.
.Name     Type      Length Description
.----     ----      ------ -----------
PMBTH001  DIM       10     10       1     Pregnancy Unique Id
PMBTH002  DIM       10     10       11    Birth Unique Id
PMBTH003  DIM       8      8        21    Admission Number
PMBTH004  DIM       8      8        29    Admission Number (Mother)
PMBTH005  DIM       8      8        37    Linked UR (if baby registered)
PMBTH006  DIM       10     10       45    No. of Birth Form
PMBTH007  DIM       2      2        55    Plurality
PMBTH008  DIM       3      3        57    Adoption (Cat mk)
PMBTH009  DIM       3      3        60    Born Before Arrival (Cat ml)
PMBTH010  DIM       8      8        63    Birth Date (CCYYMMDD)
PMBTH011  DIM       9      9        71    Birth Time (hh:mm:ss)
PMBTH012  DIM       2      2        80    Estimated Gestation at Birth
PMBTH013  DIM       1      1        82    Gender
PMBTH014  DIM       3      3        83    Birth Status/Condition (Cat mp)
PMBTH015  DIM       3      3        86    Method of Delivery (Cat mn)
PMBTH016  DIM       1      1        89    Apgar score at 1 minute
PMBTH017  DIM       1      1        90    Apgar Score at 5 minutes
PMBTH018  DIM       3      3        91    Time to Establish Respiration
PMBTH019  DIM       80     80       94    Resuscitation Drugs (Free Format)
PMBTH020  DIM       5      5        174   Birth Weight (grams)
PMBTH021  DIM       3      3        179   Length (cms)
PMBTH022  DIM       3      3        182   Head Circumference (cms)
PMBTH023  DIM       3      3        185   Moulding (Cat ms)
PMBTH024  DIM       3      3        188   Caput (Cat mt)
PMBTH025  DIM       3      3        191   Cord Blood Taken (Cat mv)
PMBTH026  DIM       3      3        194   Meconium (Cat mw)
PMBTH027  DIM       3      3        197   Urine (Cat mx)
PMBTH028  DIM       10     10       200   Paediatrician (pmshcpaf)
PMBTH029  DIM       3      3        210   NICU Admission Indicator (Cat my)
PMBTH030  DIM       1      1        213   Vitamin K 1=yes
PMBTH031  DIM       8      8        214   Hep B Received Date (CCYYMMDD)
PMBTH032  DIM       8      8        222   Hep B Received Time (hh:mm:ss)
PMBTH033  DIM       3      3        230   Breastfeeding Attempted (Cat mz)
PMBTH034  DIM       3      3        233   Infant Feeding on Discharge (CatNB)
PMBTH035  DIM       10     10       236   Baby Examined By (pmshcpaf)
PMBTH036  DIM       10     10       246   Label Attached By (pmshcpaf)
PMBTH037  DIM       10     10       256   Label Checked By (pmshcpaf)
PMBTH038  DIM       8      8        266   Guthrie Hypothyroidism Test Date
PMBTH039  DIM       8      8        274   Guthrie Hypothyroidisn Test Time
PMBTH040  DIM       5      5        282   Discharge Weight (grams)
PMBTH041  DIM       3      3        288   Birth Presentation
PMBTH042  DIM       3      3        292   Cord around neck
PMBTH043  DIM       3      3        298   Cord around body
PMBTH044  DIM       3      3              Audit Counter
PMBTH045  DIM       3      3              Reason for Changed (Cat FY)
.
