. *----------------------------------------------------------------------
. * Include Name  :   PMSDLTTD.INC
. *
. * Function      :   CGI variables for PMSDLTFD - pmsdltaf.dat
. *----------------------------------------------------------------------
.  Modifications Done :
.
.  V9.09.00   15.10.2007  Ebon Clements CAR 152175
.             Created Include
. *----------------------------------------------------------------------
.
.Name     Type      Length  Description
.----     ----      ------  -----------
PMDLT001  DIM       4       Selection ID                       
PMDLT002  DIM       35      Selection Description              
PMDLT003  DIM       10      HCP Code From (pmshcpaf)           
PMDLT004  DIM       10      HCP Code To (pmshcpaf)             
PMDLT005  DIM       3       Primary Speciality From (Cat DT)   
PMDLT006  DIM       3       Primary Speciality From (Cat DT)   
PMDLT007  DIM       3       Additional Speciality From (Cat DT)
PMDLT008  DIM       3       Additional Speciality To (Cat DT)  
PMDLT009  DIM       3       Hospital                           
PMDLT010  DIM       3       Preferred Communication (Cat CZ)     
PMDLT011  DIM       8       First Accred. Date From (ccyymmdd) 
PMDLT012  DIM       8       First Accred. Date To (ccyymmdd)   
PMDLT013  DIM       8       Last Accred. Date From (ccyymmdd)  
PMDLT014  DIM       8       Last Accred. Date To (ccyymmdd)    
PMDLT015  DIM       2       HCP Status                         
PMDLT016  DIM       3       Accreditation Type (Cat AT)        
PMDLT017  DIM       2       Years Of Accreditation From        
PMDLT018  DIM       2       Years Of Accreditation To          
PMDLT019  DIM       6       Insurance Code (patin1af)          
PMDLT020  DIM       8       Insurance Date From From(ccyymmdd) 
PMDLT021  DIM       8       Insurance Date From To(ccyymmdd)   
PMDLT022  DIM       8       Insurance Date To From(ccyymmdd)   
PMDLT023  DIM       8       Insurance Date To To(ccyymmdd)     
PMDLT024  DIM       1       HCP Status 0=Active 1=Inactive     
.
