. *----------------------------------------------------------------------
. * Include Name  :   PMSHATTD.INC
. *
. * Function      :   CGI variables for PMSHATFD - pmshataf
. *
. * Modifications :
. *
. * V11.05.00 30/01/2025  J.Tan         TASK 0946490           
. *           Created include
. *----------------------------------------------------------------------
.
.Name     Type      Length Description
.----     ----      ------ -----------
PMHAT001  DIM       3      Hospital Id (pathspaf)
PMHAT002  DIM       3      Type of Attribute
PMHAT003  DIM       25     Key Value
PMHAT004  DIM       8      Effective Start Date (ccyymmdd)
PMHAT005  DIM       8      Effective End Date (ccyymmdd)
PMHAT006  DIM       80     Text 1
PMHAT007  DIM       80     Text 2
PMHAT008  DIM       80     Text 3
PMHAT009  DIM       80     Text 4
PMHAT010  DIM       6      Value 1
PMHAT011  DIM       6      Value 2
PMHAT012  DIM       6      Value 3
PMHAT013  DIM       6      Value 4
PMHAT014  DIM       1      Indicator 1 (Yes/No)
PMHAT015  DIM       1      Indicator 2 (Yes/No)
PMHAT016  DIM       1      Indicator 3 (Yes/No)
PMHAT017  DIM       1      Indicator 4 (Yes/No)
PMHAT018  DIM       3      Coded Value 1
PMHAT019  DIM       3      Coded Value 2
PMHAT020  DIM       3      Coded Value 3
PMHAT021  DIM       3      Coded Value 4

