. *----------------------------------------------------------------------
. * Include Name  :   PMSHCLFD.INC
. *
. * Function      :   CGI variables for PMSHCLFD - pmshclaf.dat
. *
. *----------------------------------------------------------------------
.
.Name     Type      Length Description
.----     ----      ------ -----------
PMHCL001  DIM       10     HCP Code (pmshcpaf)                
PMHCL002  DIM       10     HCP Practice (pmshcgaf)            
PMHCL003  DIM       1      HCP Record Type                    
PMHCL004  DIM       8      Date HCP Joined Practice (ccyymmdd)
PMHCL005  DIM       8      Date HCP Left Practice (ccyymmdd)  
PMHCL006  DIM       1      Processed Rec. Marker (1=Processed)
PMHCL007  DIM       10     Provider Number 1                  
PMHCL008  DIM       10     Provider Number 2                  
PMHCL009  DIM       10     Provider Number 3                  
PMHCL010  DIM       10     Provider Number 4                  
PMHCL011  DIM       10     Provider Number 5                  
PMHCL012  DIM       1      Status (0=Active,1=Not Active)     
PMHCL013  DIM       8      Date Record Created (ccyymmdd)     
PMHCL014  DIM       8      Time Record Created (hh:mm:ss)     
PMHCL015  DIM       10     WEB User Id creator (websecaf)     
PMHCL016  DIM       8      Last Update Date (ccyymmdd)        
PMHCL017  DIM       8      Last Update Time (hh:mm:ss)        
PMHCL018  DIM       10     WEB user Id updated (websecaf)     
.
