.----------------------------------------------------------------------
. Include Name  :   PMSHADTD.INC
.
. Function      :   CGI variables for PMSHADFD - pmshadaf.dat
.----------------------------------------------------------------------
.
. Modifications  :
. V10.14.00 16/04/2019  Richa Phogat  TSK 0857392
.           Created
.----------------------------------------------------------------------
.Name     Type      Length Description
.----     ----      ------ -----------
PMHAD001  DIM       6      Contract ID
PMHAD002  DIM       3      HAC Group 01-16 Cat Ha  
PMHAD003  DIM       3      Value From
PMHAD004  DIM       3      Value To
PMHAD005  FORM      10.4   Complexity Adjusment %
