. *-----------------------------------------------------------------------------
. * Include Name  :  PMSIMPTD.INC
. *
. * Function      :  CGI Variables for PMSIGRFD - pmsigraf
. *
. * Mods          :                                                    
. * V10.12.01 04/04/2018 Tracey Nguyen   TSK 0841644  
. *           Created include
. *-----------------------------------------------------------------------------
.Name     Type      Length  Description
.----     ----      ------  -----------
PMIGR001  DIM       3       Impairment Group Code
PMIGR002  DIM       80      Impairment Group Description
PMIGR003  FORM      5.3     FIM Eating
PMIGR004  FORM      5.3     FIM Grooming
PMIGR005  FORM      5.3     FIM Bathing
PMIGR006  FORM      5.3     FIM Dressing Upper Body
PMIGR007  FORM      5.3     FIM Dressing Lower Body
PMIGR008  FORM      5.3     FIM Toilet
PMIGR009  FORM      5.3     FIM Bladder
PMIGR010  FORM      5.3     FIM Bowel
PMIGR011  FORM      5.3     FIM Transfer Bed/Chair
PMIGR012  FORM      5.3     FIM Transfer Toilet
PMIGR013  FORM      5.3     FIM Transfer Tub/Shower
PMIGR014  FORM      5.3     FIM Walk/Locomotion
PMIGR015  FORM      5.3     FIM Stairs
