. *-----------------------------------------------------------------------------
. * Include Name  :  PMSIMPTD.INC
. *
. * Function      :  CGI Variables for PMSIMPFD - pmsimpaf
. *
. * Mods          :                                                    
. * V10.12.01 04/04/2018 Tracey Nguyen   TSK 0841644  
. *           Added Impairment Group Code
. * V10.03.01 04/05/2012 Davin           CAR 260600
. *           Added HDP Equivalent
. * V10.03.00 05/03/2012 Patrick Adair   CAR 257776
. *           Created include
. *-----------------------------------------------------------------------------
.Name     Type      Length  Description
.----     ----      ------  -----------
PMIMP001  DIM       7       Code
PMIMP002  DIM       50      Description
PMIMP003  DIM       1       Active (1=yes)
PMIMP004  DIM       8       Date Active
PMIMP005  DIM       8       Date Inactive
PMIMP006  DIM       10      User who created record
PMIMP007  DIM       8       Date record created
PMIMP008  DIM       8       Time record created
PMIMP009  DIM       10      User who updated record
PMIMP010  DIM       8       Date record updated
PMIMP011  DIM       8       Time record updated
PMIMP012  DIM       7       HDP Equivalent
PMIMP013  DIM       3       Impairment Group Code
