. *----------------------------------------------------------------------
. * Include Name  :   PMSLETTD.INC
. *
. * Function      :   CGI Variables for PMSLETFD - pmsletaf
. *
. * Mods          :   V9.02.01 28.08.2001 Ebon Clements
. *                            Created include
. *----------------------------------------------------------------------
.
.Name     Type      Length Description
.----     ----      ------ -----------
PMSLE001  DIM       4      * Selection ID.
PMSLE002  DIM       35     * Selection Description
PMSLE003  DIM       8      * From U/R
PMSLE004  DIM       8      * To U/R
PMSLE005  DIM       20     * From Surname
PMSLE006  DIM       20     * To Surname
PMSLE007  DIM       8      * From Admission Date (ccyymmdd)
PMSLE008  DIM       8      * To Admission Date (ccyymmdd)
PMSLE009  DIM       8      * From Discharge Date (ccyymmdd)
PMSLE010  DIM       8      * To Discharge Date (ccyymmdd)
PMSLE011  DIM       3      * From Admission Type (category A)
PMSLE012  DIM       3      * To Admission Type (category A)
PMSLE013  DIM       3      * From Claim Code (category CL)
PMSLE014  DIM       3      * To Claim Code (category CL)
PMSLE015  DIM       3      * From Care Class (category CC)
PMSLE016  DIM       3      * To Care Class (category CC)
PMSLE017  DIM       3      * From Admission Class (category P)
PMSLE018  DIM       3      * To Admission Class (category P)
PMSLE019  DIM       3      * From Referral Source (category S)
PMSLE020  DIM       3      * To Referral Source (category S)
PMSLE021  DIM       3      * From Discharge Status (category D)
PMSLE022  DIM       3      * To Discharge Status (category D)
PMSLE023  DIM       3      * From Country of Birth (category C)
PMSLE024  DIM       3      * To Country of Birth (category C)
PMSLE025  DIM       3      * From Religion (category R)
PMSLE026  DIM       3      * To Religion (category R)
PMSLE027  DIM       6      * From Health Fund
PMSLE028  DIM       6      * To Health Fund
PMSLE029  DIM       1      * Deceased Status
