. *----------------------------------------------------------------------
. * Include Name  :   PMSLBRTD.INC
. *
. * Function      :   CGI variables for PMSLBRFD - pmslbraf.dat
. *----------------------------------------------------------------------
.  Modifications Done :
.
.  V10.00.00  20/07/2010  Jill Parkinson CAR 222551
.             Created include
.
. *----------------------------------------------------------------------
.
.Name     Type      Length Description
.----     ----      ------ -----------
PMLBR001  DIM       10     10       1     Pregnancy Unique Id
PMLBR002  DIM       8      8        11    Admission Number
PMLBR003  DIM       3      3        22    Onset of Labour (Cat LH)
PMLBR004  DIM       8      8        25    Date of onset (CCYYMMDD)
PMLBR005  DIM       8      8        33    Time of onset (hh:mm:ss)
PMLBR006  DIM       5      5        41    Minutes of 1st Stage of Labour
PMLBR007  DIM       8      8        46    Date of 2nd Stage (CCYYMMDD)
PMLBR008  DIM       8      8        54    Time of 2nd Stage (hh:mm:ss)
PMLBR009  DIM       5      5        62    Minutes of 2nd Stage Labour
PMLBR010  DIM       8      8        67    Date of Rupture of Membranes
PMLBR011  DIM       9      9        75    Indication of Induction (ICD code)
PMLBR012  DIM       50     50       84    Ind of Induction Free Format
PMLBR013  DIM       9      9        134   Ind of Operative Delivery (ICD code
PMLBR014  DIM       50     50       143   Ind of Operative Free Format
PMLBR015  DIM       3      3        193   Analgesia for Labour Ind (Cat LJ)
PMLBR016  DIM       3      3        196   Position of Delivery (Cat LK)
PMLBR017  DIM       3      3        199   Colour of Liquor (Cat LM)
PMLBR018  DIM       3      3        202   Presentation (Cat LV)
PMLBR019  DIM       3      3        205   Membranes (Cat LX)
PMLBR020  DIM       2      2        208   Number of Cord Vessels
PMLBR021  DIM       3      3        210   Type of Birth (Cat LZ)
PMLBR022  DIM       3      3        213   Prophylactice Oxytocin 3rd (Cat ma)
PMLBR023  DIM       3      3        216   Management of 3rd Stage (Cat mb)
PMLBR024  DIM       3      3        219   Placenta (Cat mc)
PMLBR025  DIM       3      3        222   Manual Removal of Placenta (Cat md)
PMLBR026  DIM       3      3        225   Episotomy Indicator (Cat me)
PMLBR027  DIM       3      3        228   Perineal Laceration Ind (Cat mf)
PMLBR028  DIM       3      3        231   Perineal Degree/Type (Cat mg)
PMLBR029  DIM       3      3        234   Perineal Repair (Cat mh)
PMLBR030  DIM       4      4        237   Estimated Blood Loss (mls)
PMLBR031  DIM       3      3        241   Blood Product Transfusion (Cat mi)
PMLBR032  DIM       3      3        244   Disc of Lead Intrapartum Carer (MJ)
PMLBR033  DIM       10     10       247   Delivery Midwife (pmshcpaf)
PMLBR034  DIM       10     10       257   Delivery Doctor (pmshcpaf)
PMLBR035  DIM       10     10       267   Delivery Anaesthetist (pmshcpaf)
PMLBR036  DIM       2      2        277   Number of babies this birth
PMLBR037  DIM       10     10       279   Midwife at Discharge (pmshcpaf)
PMLBR038  DIM       3      3              Counter
PMLBR039  DIM       3      3              Audit Counter
PMLBR040  DIM       3      3              Reason for Change (cat FY)
.
