.*------------------------------------------------------------------------------
.* Include Name  :   PMSUDTTD.INC
.*
.* Function      :   CGI variables for PMSUTXFD - pmsutxaf.dat
.*------------------------------------------------------------------------------
.
.  Modifications Done :
.
.  V10.05.01  08/08/2014 Patrick Adair                                CAR 294210
.             Created Include
.
.*------------------------------------------------------------------------------
.
.  Program Maintenance Comments
.
PMUTX001  DIM       8                            * U/R Number
PMUTX002  DIM       3                            * Admission Type (Cat A)
PMUTX003  DIM       3                            * Claim Type (Cat CL)
PMUTX004  DIM       6                            * Health Fund
PMUTX005  DIM       3                            * Health Fund Table Type (Cat HT)
PMUTX006  DIM       8                            * Expiry Date (ccyymmdd)
PMUTX007  DIM       3                            * Comment Type
PMUTX008  DIM       6                            * Note Number
PMUTX009  DIM       3                            * Line Number 
PMUTX010  DIM       100                          * Comment
.
