. *----------------------------------------------------------------------
. * Include Name  :   RCPBNKTD.INC
. *
. * Function      :   CGI variables for RCPBNKFD - rcpbnkaf
. *
. * Modifications :
. *
. * V9.03.00 26/11/2003 Ebon Clements            CAR 44095
. *          Created include
. *----------------------------------------------------------------------
.
.Name     Type      Length Description
.----     ----      ------ -----------
RCPBK001  DIM       12     Receipt Number
RCPBK002  DIM       8      Transaction Date (CCYYMMDD)
RCPBK003  DIM       15     Total Payment
RCPBK004  DIM       6      Cash Drawer
RCPBK005  DIM       3      Multi Hospital Id (pathspaf)
RCPBK006  DIM       2      Multi Database Hosp Id (pathospf)
RCPBK007  DIM       1      Received From Type
RCPBK008  DIM       6      Received From Code
rCPBK009  DIM       1      Status
RCPBK010  DIM       8      Bank Deposit Date (CCYYMMDD)
RCPBK011  DIM       8      Bank Deposit Time (hh:mm:ss)
RCPBK012  DIM       8      Reconciliation Date (CCYYMMDD)
RCPBK013  DIM       8      Reconciliation Time (hh:mm:ss)
RCPBK014  DIM       15     Cheque Account Number
RCPBK015  DIM       8      Date Record Created (CCYYMMDD)
RCPBK016  DIM       8      Time Record Created (hh:mm:ss)
RCPBK017  DIM       10     Web User Id Created (websecaf)
RCPBK018  DIM       8      Date Record Updated (CCYYMMDD)
RCPBK019  DIM       8      Time Record Updated (hh:mm:ss)
RCPBK020  DIM       10     Web User Id Updated (websecaf)
