. V6.00.001 02/09/0091 BGA Generated                                         
. *----------------------------------------------------------------------
. * Include Name  :   SCRTFCFD.INC
. *
. * Function      :   File Def'n Include for Common                      
. *                   Screen Temporary Functions Table                
. *
. * File Type     :   SQL
. *
. * File Name     :   scrtfcaf.dat
. *
. *----------------------------------------------------------------------
.
.Data File Definition
.--------------------
SCRTFCA1   IFILE    SQL, FIXED=9, KEY="U1-8"                                    
.
.Name     Type      Length Physical Start Description
.----     ----      ------ -------- ----- -----------
SCTFFUN   DIM       8      8        1     Function                           
.
.End of Record                      9    
.
