.------------------------------------------------------------------------------
. Include File   : TFILEVAR.INC
.
. Function       : Variables for standard routine TFILENAM.PBL to generate a 
.                  temp file name
.
. Author         : Ebon Clements 
.
. Modifications  :
.
. V10.03.01  11/04/2013  Ebon Clements     CAR 261630
.            Changed temp file prefix from CSC to T
. V10.03.00  19/07/2012  Ebon Clements     CAR 261630
.            Created include
.------------------------------------------------------------------------------
TFILEUNQ  FORM      7
TFILNAME  DIM       8
TFILPRFX  INIT      "T"
.
