.******************************************************************************
.*                                                                            *
.* Include Name     : VARWIS14.INC                                            *
.*                                                                            *
.* Description      : Common variables for PATWIS14                           *
.*                                                                            *
.* Author           : Davin S      10/07/2006                                 *
.*                                                                            *
.* Modifications    :                                                         *
.*                                                                            *
.*        V9.09.01  02/08/2007  Steve Armstrong  CAR 145161                   *
.*                  Removed common variables (now in VARWISCM)                *
.*        V9.09.00  17/07/2007  Steve Armstrong  CAR 145161                   *
.*                  Modified from VARWIS13 for 2007/2008 changes              *
.******************************************************************************
.
TOTIES14  FORM      12.4                    * Total IES14
TOTWIS14  FORM      12.4                    * Total WIES14
.
W14NLIER  DIM       1                       * Inlier status (L/I/H)
WIS14DRG  DIM       4                       * DRG working variable
WIS14DSC  DIM       13                      * Display weight description
WIS14LOS  FORM      4                       * Length of stay
WIS14WGT  FORM      6.4                     * Display weight
+
