.******************************************************************************
.*                                                                            *
.* Include Name     : VARWIS17.INC                                            *
.*                                                                            *
.* Description      : Common variables for PATWIS17                           *
.*                                                                            *
.* Author           : Davin S      10/07/2006                                 *
.*                                                                            *
.* Modifications    :                                                         *
.*                                                                            *
.*       V10.00.00  19/03/2010  Davin             CAR 216505                  *
.*                  Modified from VARWIS16 for 2010/2011 changes              *
.******************************************************************************
.
TOTIES17  FORM      12.4                    * Total IES17
TOTWIS17  FORM      12.4                    * Total WIES17
.
W17NLIER  DIM       1                       * Inlier status (L/I/H)
WIS17DRG  DIM       4                       * DRG working variable
WIS17DSC  DIM       13                      * Display weight description
WIS17LOS  FORM      4                       * Length of stay
WIS17WGT  FORM      6.4                     * Display weight
+
