.******************************************************************************
.*                                                                            *
.* Include Name     : VARWIS18.INC                                            *
.*                                                                            *
.* Description      : Common variables for PATWIS18                           *
.*                                                                            *
.* Author           : Davin S      10/07/2006                                 *
.*                                                                            *
.* Modifications    :                                                         *
.*                                                                            *
.*       V10.02.00  08/08/2011  Davin             CAR 238236                  *
.*                  Modified from VARWIS17 for 2011/2012 changes              *
.******************************************************************************
.
TOTIES18  FORM      12.4                    * Total IES18
TOTWIS18  FORM      12.4                    * Total WIES18
.
W18NLIER  DIM       1                       * Inlier status (L/I/H)
WIS18DRG  DIM       4                       * DRG working variable
WIS18DSC  DIM       13                      * Display weight description
WIS18LOS  FORM      4                       * Length of stay
WIS18WGT  FORM      6.4                     * Display weight
+
