.******************************************************************************
.*                                                                            *
.* Include Name     : VARWIS21.INC                                            *
.*                                                                            *
.* Description      : Common variables for PATWIS21                           *
.*                                                                            *
.* Author           : Davin S      10/07/2006                                 *
.*                                                                            *
.* Modifications    :                                                         *
.*                                                                            *
.*       V10.05.00  21/08/2014  Davin             CAR 296980                  *
.*                  Modified from VARWIS20 for 2014/2015 changes              *
.******************************************************************************
.
TOTIES21  FORM      12.4                    * Total IES21
TOTWIS21  FORM      12.4                    * Total WIES21
.
W21NLIER  DIM       1                       * Inlier status (L/I/H)
WIS21DRG  DIM       4                       * DRG working variable
WIS21DSC  DIM       13                      * Display weight description
WIS21LOS  FORM      4                       * Length of stay
WIS21WGT  FORM      6.4                     * Display weight
+
