. *----------------------------------------------------------------------
. * Include Name  :   VISPAYTD.INC
. *
. * Function      :   CGI variables for VISPAYFD - vispayaf.dat
. *----------------------------------------------------------------------
.  Modifications Done :
.
.  V9.07.00   07/07/2006  Ebon Clements CAR 103365
.             Created include
. *----------------------------------------------------------------------
.
.Name     Type      Length  Description
.----     ----      ------  -----------
VSPAY001  DIM       8       Visit Number                       
VSPAY002  DIM       6       Expected Payor Code (patfn1af)     
VSPAY003  DIM       2       Sequence                           
VSPAY004  DIM       30      Comments                           
VSPAY005  DIM       1       Active 0=Active 1=Inactive         
VSPAY006  DIM       1       Invoice Sent 0=No 1=Yes
.
