. *----------------------------------------------------------------------
. * Include Name  :   WEBOESTD.INC
. *
. * Function      :   CGI variables for WEBOESFD - weboesaf.dat                 
. *----------------------------------------------------------------------
. *
. * Modifications :  V11.00.01 24/08/2020 Peter Vela TSK 0895969
. *                   Created include
. *
. *----------------------------------------------------------------------
.
.Name     Type      Length Description
.----     ----      ------ -----------
WEBOS001  DIM       8[50]  Visit Number
WEBOS002  DIM       3[50]  Report Counter (right just.)
WEBOS003  DIM       3[50]  Service Counter (right just.)
WEBOS004  DIM       1[50]  Service Record Type
WEBOS005  DIM       9[50]  Theatre/Item Code
WEBOS006  DIM       3[50]  Quantity
WEBOS007  DIM       8[50]  Date of Procedure
WEBOS008  DIM       8[50]  Date Created (ccyymmdd)
WEBOS009  DIM       8[50]  Time Created (hh:mm:ss)
.
